.gitignore
README.md

Update readme so it tells the user to create a .env and ignore the .env
2. etc...

Add copy env sample and ignore .env

---

src/AppProviders.tsx
src/assets/translations/messages-en.json
src/components/Modals/Receive/Receive.tsx
src/components/Modals/Send/Details.tsx
src/components/Modals/Send/Form.tsx
src/components/Modals/Send/Send.tsx
src/context/ModalProvider/ModalProvider.tsx
src/pages/Assets/AssetDetails/AssetActions.tsx

closes #40 
* refactors modal provider (controversial, can split out into a separate PR)
* wires up receive UI
1. pair a wallet
2. generate a receive address using a known correct third party source
3. click receive on an asset
4. verify receive address displayed matches known correct address
5. verify receive address copied to clipboard matches known correct address
6. verify scanned QR code matches known correct address

Receive UI data

---

.gitignore
src/context/WalletProvider/SelectModal.tsx

Closes #27 
Small PR to get familiar.

Fix unique keys in selectmodal

---

src/context/ModalProvider/ModalProvider.test.tsx
src/context/ModalProvider/ModalProvider.tsx
src/pages/Assets/AssetDetails/AssetActions.tsx

make ModalProvider generic and dependency injectable and add tests

---

src/assets/translations/messages-en.json
src/components/Modals/Receive/Receive.tsx
src/context/WalletProvider/NativeWallet/NativeSuccess.tsx

closes #72 
sometimes the copy button wouldn't work, this try/catches it
2. etc...

chore: try/catch receive address, add padding to copy button, fix lint

---

src/assets/translations/messages-en.json
src/components/Transactions/TransactionRow.tsx
src/components/Transactions/Transactions.tsx
src/context/WalletProvider/NativeWallet/NativePasswordRequired.tsx
src/context/WalletProvider/NativeWallet/NativeSuccess.tsx
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/WalletViewsSwitch.tsx
src/hooks/useIsComponentMounted/useIsComponentMounted.test.ts
src/hooks/useIsComponentMounted/useIsComponentMounted.ts
src/hooks/useStateIfMounted/useStateIfMounted.test.ts
src/hooks/useStateIfMounted/useStateIfMounted.ts
src/hooks/useTransactions/useTransactions.test.ts
src/hooks/useTransactions/useTransactions.ts
src/lib/math.ts
src/pages/Assets/AssetDetails/AssetDetails.tsx
src/pages/Assets/AssetDetails/AssetHistory.tsx
src/pages/Dashboard/RecentTransactions.tsx
src/pages/Dashboard/components/AssetList/AssetList.tsx

This PR closes [this issue](https://github.com/shapeshift/lib/issues/4) in `lib` which will be closed when this [PR](https://github.com/shapeshift/lib/pull/14) is merged.
- Add v1 of transaction history. 
- This is the initial implementation of transaction history before we migrate over to using web socket (v2) functionality from unchained. The implementation details and architecture is yet to be determined for v2.
2. etc...

Tx history

---

src/components/Transactions/TransactionRow.tsx

Small update to use amount component and middle ellipsis

Use amount component and middle ellipsis

---

package.json
src/components/Graph/Graph.tsx
src/components/Modals/Receive/Receive.tsx
src/components/Modals/Send/Form.tsx
src/components/Modals/Send/Send.tsx
src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Modals/Send/hooks/useSendFees/useSendFees.tsx
src/hooks/useAsset/useAsset.tsx
src/pages/Assets/Asset.tsx
src/pages/Assets/AssetDetails/AssetActions.tsx
src/pages/Assets/AssetDetails/AssetDetails.tsx
src/pages/Assets/AssetDetails/AssetHeader.tsx
src/pages/Assets/AssetDetails/AssetHistory.tsx
src/pages/Dashboard/Portfolio.tsx
yarn.lock

frontend changes for separating asset service market service
2. Everything still works as before

changes for seperating asset service market service

---

src/components/Graph/Graph.tsx

closes #91 
We were passing the network, but needed the chain for the coingecko.
1. Go to an asset
2. See the chart data

Update network to chain

---

src/lib/consoleArt.ts

Change console art Discord URL

---

src/components/Layout/Header/HeaderContent.tsx

Make foxicon link to dashboard

---

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Modals/Send/hooks/useSendFees/useSendFees.tsx
src/pages/Assets/Asset.tsx
src/pages/Dashboard/Portfolio.tsx

closes #101 
shakesfist.gif
2. etc...

fix: use correct imported enums from lib

---

package.json
src/components/AssetSearch/AssetList.tsx
src/hooks/useRefCallback/useRefCallback.test.tsx
src/hooks/useRefCallback/useRefCallback.ts

Scroll back to top asset when searching

---

src/components/AssetSearch/helpers/filterAssetsBySearchTerm/filterAssetsBySearchTerm.test.ts
src/components/AssetSearch/helpers/filterAssetsBySearchTerm/filterAssetsBySearchTerm.ts

Fix broken Asset search test

---

src/context/WalletProvider/NativeWallet/NativePasswordRequired.tsx
src/context/WalletProvider/NativeWallet/NativeSuccess/NativeSuccess.tsx
src/context/WalletProvider/NativeWallet/NativeSuccess/hooks/useNativeSuccess/useNativeSuccess.test.ts
src/context/WalletProvider/NativeWallet/NativeSuccess/hooks/useNativeSuccess/useNativeSuccess.ts
src/context/WalletProvider/NativeWallet/setup.ts
src/context/WalletProvider/config.ts

Closes #22 
- This refactor removes the business logic inside of the `NativeSuccess` component and puts it into a hook.
2. etc...

Pull out logic from NativeSuccess into useNativeSuccess hook

---

src/hooks/useAsset/useAsset.tsx

relies on https://github.com/shapeshift/lib/pull/49
https://github.com/shapeshift/lib/issues/47
asset service `byTokenId()` function now takes an object rather than three arguments
2. etc...

update usage of asset service with slightly modified api

---

package.json
src/components/AssetSearch/helpers/filterAssetsBySearchTerm/filterAssetsBySearchTerm.test.ts
src/components/AssetSearch/helpers/filterAssetsBySearchTerm/filterAssetsBySearchTerm.ts
src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
src/context/WalletProvider/NativeWallet/NativeSuccess/hooks/useNativeSuccess/useNativeSuccess.test.ts
src/context/WalletProvider/WalletProvider.test.tsx

closes #106 
ci: add type-check and lint step, fix type errors.
1. ci should run and type-check and lint all branches going into develop

chore: fix type errors and tests

---

src/components/Graph/Graph.tsx
src/hooks/useAsset/useAsset.tsx

closes #108 
This updates the breaking api changes from this [PR](https://github.com/shapeshift/lib/pull/50/files) and this [PR](https://github.com/shapeshift/lib/pull/49/files) to `getMarketData`, `byTokenId` and `getPriceHistory`
2. etc...

fix: update asset service and  market service api

---

.github/workflows/commitlint.yml
commitlint.config.js
package.json
yarn.lock

only commitlint the PR title instead of all commits
PR titles conforming to conventional commits spec will be accepted, others will not

ci: commitlint PR title instead of all commits

---

.github/workflows/commitlint.yml

ci: add interim env var to avoid injection

---

src/hooks/useBalances/useBalances.tsx
src/hooks/useBalances/useFlattenedBalances.test.ts
src/hooks/useTransactions/useTransactions.test.ts
src/hooks/useTransactions/useTransactions.ts
src/pages/Assets/Asset.tsx
src/pages/Assets/AssetDetails/AssetHistory.tsx

closes #122 
depends on https://github.com/shapeshift/lib/pull/89 being merged first
2. etc...

chore: use generic chain adapters

---

.github/workflows/pr.yml

closes #136 
adds vercel deployments to each PR into develop, i actually set this up in the Vercel UI as the runs complete faster and means we don't need to store secrets in this repo
vercel link below should work

ci: vercel deploys on PRs

---

src/constants/FeatureFlagEnum.ts
src/hooks/useFeature/useFeature.ts

feat: add hard coded feature flags
2. etc...

feat: add hard coded feature flags

---

src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx

Fix: eth gas fee2

---

src/context/EarnManagerProvider/providers/yearn/constants/vaults.ts

chore: removed the eth vault and added yfi vault

---

src/assets/translations/messages-en.json
src/constants/FeatureFlagEnum.ts
src/context/EarnManagerProvider/components/BroadcastTx/BroadcastTx.tsx
src/context/EarnManagerProvider/components/Confirm/Confirm.tsx
src/context/EarnManagerProvider/providers/yearn/components/YearnManager/YearnDeposit.tsx
src/context/EarnManagerProvider/providers/yearn/components/YearnManager/YearnWithdraw.tsx

Added broadcast screen, reworked the components to be more modular to change the data more easily.
closes #265 
2. etc...

feat: broadcast screen

---

src/context/EarnManagerProvider/providers/yearn/components/YearnManager/YearnDeposit.tsx
src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx

fix: earn buttons toggle
2. etc...

fix: earn buttons toggle

---

src/context/EarnManagerProvider/components/Approve/Approve.tsx
src/context/EarnManagerProvider/providers/yearn/api/api.ts
src/context/EarnManagerProvider/providers/yearn/api/yearn-types.ts
src/context/EarnManagerProvider/providers/yearn/components/YearnManager/YearnDeposit.tsx
src/context/EarnManagerProvider/providers/yearn/constants/vaults.ts
src/lib/poll/poll.ts
src/pages/Assets/AssetCards/Rewards.tsx

feat: add yearn deposit approve step
2. etc...

feat: add yearn deposit approve step

---

src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/MetaMask/hooks/useMetaSuccess/useMetaSuccess.ts
src/context/WalletProvider/NativeWallet/components/NativePasswordRequired.tsx
src/context/WalletProvider/NativeWallet/hooks/useInitializeWalletFromStorage/useInitializeWalletFromStorage.test.ts
src/context/WalletProvider/NativeWallet/hooks/useInitializeWalletFromStorage/useInitializeWalletFromStorage.ts
src/context/WalletProvider/NativeWallet/hooks/useNativePasswordRequired/useNativePasswordRequired.ts
src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess/useNativeSuccess.test.ts
src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess/useNativeSuccess.ts
src/context/WalletProvider/SelectModal.tsx
src/context/WalletProvider/WalletProvider.test.tsx
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/WalletViewsSwitch.tsx
src/context/WalletProvider/config.ts

Use an enum for the list of supported Wallets / KeyManagers. This allows us to avoid casting types in other places.

chore: improve types for HDWallet adapters

---

src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess/useNativeSuccess.test.ts
src/context/WalletProvider/WalletProvider.test.tsx

* mock metamask in `WalletProvider` test
* Bonus: Handle properly console errors in `useNativeSucess` test
closes #282

test: mock metamask in WalletProvider tests

---

src/assets/translations/messages-en.json
src/context/EarnManagerProvider/components/Deposit/Deposit.tsx
src/context/EarnManagerProvider/components/TxStatus/TxStatus.tsx
src/context/EarnManagerProvider/providers/yearn/api/api.ts
src/context/EarnManagerProvider/providers/yearn/components/YearnManager/YearnDeposit.tsx
src/context/EarnManagerProvider/providers/yearn/components/YearnManager/YearnWithdraw.tsx
src/pages/Assets/AssetCards/Rewards.tsx

feat: yearn deposit status screen

---

public/index.html

Use a proper Shapeshift description in metadata
_Shapeshift: non-custodial, decentralized, and cross-chain platform | Where Crypto Lives._
closes #285

chore: change web public metadata

---

src/pages/Dashboard/components/AccountList/AccountList.tsx

feat: sort your assets/portfolio by highest balance first

---

src/hooks/useLocaleFormatter/useLocaleFormatter.test.ts

Added some tests for `useLocaleFormatter.toCrypto`. 

chore: add some "toCrypto" tests

---

src/components/Transactions/TransactionRow.tsx
src/context/EarnManagerProvider/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
src/context/EarnManagerProvider/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
src/pages/Assets/AssetCards/StakingVaults/StakingVaultRow.tsx
src/pages/Dashboard/components/AccountList/AccountList.tsx
src/pages/Dashboard/helpers/sortByFiat/sortByFiat.ts

feat: update withdraw to use vault asset
2. etc...

feat: update withdraw to use vault asset

---

src/features/earn/providers/yearn/constants/vaults.ts

Updates vault list for underlying tokens on the coingecko list so we have market data for them.
2. etc...

chore: update vault list

---

src/components/StakingVaults/StakingVaults.tsx
src/features/earn/contexts/YearnProvider/YearnProvider.tsx
src/features/earn/providers/yearn/components/YearnManager/YearnManager.tsx
src/pages/Assets/AssetCards/UnderlyingToken/UnderlyingToken.tsx

fix: use yearn regression
2. etc...

fix: use yearn regression

---

src/assets/translations/messages-en.json

fix: add Portis translations

---

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/hooks/useBalances/useBalances.tsx

Fix not showing BTC balances
Closes #239 
1. Connect a wallet with a BTC balance
2. Go the BTC asset page
3. Click on the different script types
4. wait for the balance to update
p2sh-p2wpkh
p2sh

fix: not showing BTC balances

---

src/components/Layout/Page.tsx
src/components/Layout/PageTransition.tsx
src/components/StakingVaults/StakingVaultRow.tsx
src/components/StakingVaults/StakingVaults.tsx
src/features/earn/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
src/pages/Earn/views/StakingVaults.tsx

fix: page animation and yearn loading
2. etc...

fix: page animation and yearn loading

---

src/features/earn/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
src/features/earn/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
src/features/earn/providers/yearn/helpers/buildTxToSign.ts

fix: fix kk bug and clean up old stuff

fix: fix kk bug and clean up old stuff

---

src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useSwapper/useSwapper.ts
yarn.lock

Adds `Send Max` button functionality to trade component.
closes #234 
2. etc...

feat: add send max

---

src/assets/translations/messages-en.json

fix: keepkey passphrase text

---

src/components/Graph/Graph.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Trade/TradeInput.tsx
src/context/ModalProvider/ModalProvider.tsx
src/features/earn/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
src/features/earn/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
src/pages/Assets/AssetDetails/AssetDetails.tsx
src/state/slices/marketDataSlice/marketDataSlice.tsx

fix: remove loading from marketdata, memo graph, add comment
2. etc...

fix: remove loading from marketdata, memo graph, add comment

---

src/hooks/useBalances/useBalances.test.tsx
src/hooks/useBalances/useBalances.tsx

ETH balances in the asset header component now display properly when using MetaMask.
2. etc...

fix: metamask balances should display properly

---

src/components/Modals/KeyManagement/KeepKey/Passphrase.tsx
src/components/Modals/KeyManagement/KeepKey/Pin.tsx

Add "autocomplete" attribute to PIN and Passphrase.

fix: add autocomplete attribute to PIN and Passphrase modals

---

src/features/earn/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx

Needed link for learn more
closes #389 
2. etc...

fix: add learn more link on approval

---

src/assets/translations/messages-en.json
src/components/Modals/KeyManagement/Native/Password.tsx
src/context/WalletProvider/NativeWallet/components/NativePassword.tsx

chore: update translations for password modals

chore: update translations for password modals

---

src/components/Trade/hooks/useSwapper/useSwapper.test.tsx
src/components/Trade/hooks/useSwapper/useSwapper.ts
src/jest/constants.ts

- Fixes issue where trade component couldn't get an initial rate on page load.
closes #400 
2. etc...

fix: update minMax in getQuoteFromSwapper

---

src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx
src/pages/Dashboard/Portfolio.tsx

fix: change default chart timeframe to day

---

src/components/Modals/Send/hooks/useSendFees/useSendFees.tsx

Adds some protection to the calculation of send fees by ensuring that asset and fee asset exist.
2. etc...

chore: added asset and feeAsset protection for useSendFees

---

src/App.tsx
src/assets/translations/messages-en.json
src/hooks/useHasAppUpdated/useHasAppUpdated.ts

hook to detect if app has updated
@reallybeard can you please implement a modal to pop up on this hook returning true?
required for #413 
2. etc...

feat: useHasAppUpdated hook and app refresh modal

---

src/components/Trade/TradeConfirm/TradeConfirm.tsx

Fix trade complete state where all values show 0
2. etc...

fix: fix trade complete showing

---

src/components/AccountRow/AccountRow.tsx
src/components/AccountRow/LoadingRow.tsx
src/pages/Dashboard/Portfolio.tsx
src/pages/Dashboard/components/AccountList/AccountList.tsx

- Loading state for chart and account list
2. etc...

chore: dashboard loading state

---

src/context/WalletProvider/NativeWallet/components/NativeStart.tsx

We except people to use "Saved Wallets" the most frequently so we should have it as the first option.

chore: change order or buttons in ss load screen

---

src/index.tsx

Don't swallow CRA's `reportWebVitals` output.

feat: log web vitals

---

package.json
src/components/Trade/TradeInput.tsx
yarn.lock

- bump swapper version 1.11.8 to 1.11.9
- Add error handling for ETH max trade
2. etc...

chore: bump swapper v1.11.8 to v1.11.9

---

headers.js

Add `data:` URIs and for images, and `https://fwd.metamask.io/` for frames
2. etc...

fix: loosen CSP to allow QR codes and MM install prompt

---

src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
src/hooks/useBalanceChartData/useBalanceChartData.test.ts
src/hooks/useBalanceChartData/useBalanceChartData.ts
src/pages/Dashboard/components/AccountList/AccountList.tsx

we were deducting erc20 values from eth, causing charts to go negative 
i added a bunch of utility functions that turned up not being required and associated tests
2. etc...

fix: fix negative balances

---

headers.js

fix: add gas.api.0x.org to CSP

---

package.json
src/hooks/useBalanceChartData/useBalanceChartData.ts
yarn.lock

fix: set new balances

---

src/components/AssetSearch/AssetSearch.tsx
src/components/Trade/SelectAsset.tsx

- Filter out non-eth/erc20 assets from trade
2. etc...

fix: filter out non-eth/erc20 assets in trade

---

headers.js
src/assets/translations/messages-en.json
src/context/WalletProvider/MetaMask/components/Connect.tsx
src/context/WalletProvider/MetaMask/components/Failure.tsx

Hack to handle MetaMask account changes

fix: hack to handle MM account changes

---

headers.js

Fix `frame-ancestors` typo in CSP

fix: csp typo

---

headers.js
package.json
yarn.lock

Pull in https://github.com/shapeshift/lib/pull/246. 

fix: bump `chain-adapters` to fix portis btc sends

---

package.json
yarn.lock

Keeping out dependencies up-to-date:
chore: upgrade axios to 0.24.0

chore: upgrade axios to 0.24.0

---

src/assets/translations/messages-en.json
src/components/Layout/Header/NavBar/UserMenu.tsx

Adding feedback link to user menu
closes #502 
2. etc...

feat: add submit feedback link

---

package.json
yarn.lock

This package is not referenced anywhere in the code

chore: remove unused dependency react-device-detect

---

src/assets/translations/messages-en.json
src/features/earn/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx

- Updated some copy across the app
- Added tooltip text
2. etc...

chore: translation updates

---

src/components/Modals/KeyManagement/Native/Password.tsx
src/context/WalletProvider/NativeWallet/components/NativePassword.tsx

- Fix the error state
- Validate on change
- Stop trapping focus so you can fill password
closes #464 
2. etc...

fix: validation on native password

---

public/index.html

Merge of #480 clobbered `REACT_APP_CSP_META` in `public/index.html`; this puts it back.

fix: merge of #480 clobbered REACT_APP_CSP_META

---

package.json
src/components/TokenRow/TokenRow.tsx
src/hooks/useLocaleFormatter/useLocaleFormatter.ts
yarn.lock

chore: upgrade typescript to 4.5.2 (was 4.4.4)

chore: upgrade typescript to 4.5.2

---

package.json
yarn.lock

Bump swapper version
2. etc...

chore: bump swapper from 1.11.11 to 1.11.12

---

package.json
react-app-rewired.config.js

Re-enable source maps so we can debug things in prod.

chore: enable source maps

---

src/context/WalletProvider/components/SuccessModal.tsx

Close wallet connect success modal after 2 seconds.
closes #491 
2. etc...

fix: close wallet success modal after 2 seconds

---

package.json
yarn.lock

fix: fix to erc20 address
https://github.com/shapeshift/web/issues/528

fix: fix to erc20 address

---

package.json
src/assets/translations/messages-en.json
src/context/WalletProvider/MetaMask/components/Connect.tsx
src/context/WalletProvider/components/ConnectModal.tsx
yarn.lock

- Add a spinner to the walletConnectModal component so that the user is made aware when attempting to pair a wallet that the application has not hung.
- Pull in hdwallet changes to fix the broken metamask desktop functionality.
2. etc...

feat: add spinner to walletconnect modal

---

scripts/postinstall.sh

chore: update the postinstall script to work with macOS

chore: update the postinstall script to work with macOS

---

CONTRIBUTING.md

chore: typo fix

---

README.md

Update the README to indicate to use WSL for developers using Windows.

chore: update readme for windows users

---

package.json
yarn.lock

chore: upgrade react-number-format to 4.8.0

chore: upgrade react-number-format to 4.8.0

---

package.json
yarn.lock

Upgrade is just for the sake of keeping up to date so we don't get behind on dependencies.
I reviewed their changelog and it doesn't look like there are any backward incompatible changes that we have to worry about.
Check the GitHub Actions results

chore: upgrade commitlint to 15.0

---

package.json
yarn.lock

Upgrade chakra-ui components just to make sure we're keeping up to date and don't get stuck way behind later.

chore: upgrade chakra-ui components

---

src/components/Modals/Send/views/Address.tsx
src/components/Modals/Send/views/Details.tsx

fix send modal regression @cjthompson
#598
clicking send button should open modal

fix: fix send modal not appearing

---

headers.js

This should help us keep track of where the requirement for each CSP rule comes from.

chore: document source of 'connect-src' CSP URLs

---

headers.js

fix: add some missing CSP lines

---

src/features/earn/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx

Fixes a bug where clicking on weth vault causes a blank screen.
1. Go to earn tab. 
2. Click staking and Vaults.
3. Click on WETH vault and you should see a deposit model instead of a white screen.

fixed bug with white screen for yearn weth deposit

---

README.md
package.json
scripts/release.sh

Add a script to automate creating release branches and merging to main
1. ./scripts/release.sh release v1.0.5
2. ./scripts/release.sh main v1.0.5

feat: add script to automate releases

---

scripts/postinstall.sh

chore: add some "echo" calls to the `postinstall.sh` script to tell the developer what's going on

chore: in postinstall.sh, tell the user what's going on

---

package.json
yarn.lock

feat: bump version of swapper

---

src/state/slices/marketDataSlice/marketDataSlice.tsx

Fixes https://github.com/shapeshift/web/issues/700
1. Reproduce bug
2. Find place in code where bug probably lies
3. Find other chart code where there is no bug
4. Compare and fix bug in first place
5. Verify bug is fixed

fix: incorrect date showing on price chart

---

src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx

fix: space between balance and unit on balance charts

---

src/context/TransactionsProvider/TransactionsProvider.tsx
src/state/slices/portfolioSlice/portfolioSlice.test.ts
src/state/slices/portfolioSlice/portfolioSlice.ts
src/state/slices/txHistorySlice/txHistorySlice.test.ts
src/state/slices/txHistorySlice/txHistorySlice.ts
src/test/mocks/store.ts

wip - index txs by account for upcoming account pages
#626 
this won't require any testing as we're not acting on this data yet
n/a

feat: index tx by account

---

src/components/AccountRow/AccountRow.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/features/earn/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
src/features/earn/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
src/hooks/useBalanceChartData/useBalanceChartData.ts
src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx
src/pages/Earn/hooks/useVaultBalances.tsx
src/state/slices/portfolioSlice/portfolioSlice.test.ts
src/state/slices/portfolioSlice/portfolioSlice.ts

- Add needed selectors for accounts implementation
- Rename selectors that end in `ById` to the appropriate Id, ie `ById` to ByAssetId`
- Add selector tests
closes #686 
2. etc...

feat: web 686

---

src/components/AssetAccounts/AssetAccountRow.tsx
src/pages/Accounts/Account.tsx
src/pages/Accounts/AccountRowWithTokens.tsx
src/state/slices/portfolioSlice/portfolioSlice.ts
src/state/slices/portfolioSlice/utils.test.ts
src/state/slices/portfolioSlice/utils.ts

account id to label for accounts page
#748
n/a - wip for @reallybeard
n/a but sooon

feat: add account id to label utils, rename some functions that weren't selectors

---

src/components/AssetAccounts/AssetAccountRow.tsx
src/components/SelectAssets/SelectAccount.tsx

- Styled the label tag on AssetAccountRow
- Added a compact flag to the AssetAccountRow
closes #768 
2. etc...

chore: added compact and styled the tag

---

src/components/AssetAccounts/AssetAccountRow.tsx
src/state/slices/portfolioSlice/utils.test.ts
src/state/slices/portfolioSlice/utils.ts

account label tweaks
closes #777
see screenshot

fix: account label tweaks

---

src/components/AssetAccounts/AssetAccountRow.tsx

Hook allocation data to the column in accountrow
closes #790 
2. etc...

feat: add allocation data

---

src/AppProviders.tsx
src/Routes/ScrollToTop.ts

Detect location change and reset scroll state.
https://v5.reactrouter.com/web/guides/scroll-restoration
closes #791 
2. etc...

chore: router scroll reset

---

src/pages/Accounts/Accounts.tsx
src/state/slices/portfolioSlice/portfolioSlice.test.ts
src/state/slices/portfolioSlice/portfolioSlice.ts

`selectPortfolioAccountBalancesSortedFiat` returns accountIds sorted by fiat balance
closes #787 
2. etc...

feat: Account sort by fiat

---

src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/state/slices/portfolioSlice/utils.ts

Fixes a bug where ETH sends were broken from a thrown error when trying to get BTC Account Type.
2. etc...

fix: eth send caused white screen

---

src/components/AssetHeader/AssetHeader.tsx
src/components/TxHistory.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts

does what it says
n/a
1. open console
2. pair metamask
3. shouldn't see errors about failing to subscribe to btc as per below

fix: don't subscribe btc txs with metamask

---

package.json
yarn.lock

unpinned `@shapeshiftoss/types` (#757)
`yarn type-check` shows `Found 0 errors.`
closes #757
* run `yarn type-check`

chore: unpin @shapeshiftoss/types

---

src/components/AssetAccounts/AssetAccountRow.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/state/slices/portfolioSlice/portfolioSlice.ts

Fixes a bug where send max on ETH was causing an infinite spinner.
1. Go to ETH send.
2. Click Max
3. Should be able to click next to go to the confirm transaction page.

fix: fixed bug for send max eth

---

.storybook/preview.js
package.json
public/mockServiceWorker.js
src/setupTests.ts
src/test/msw-utils.ts
yarn.lock

set up [msw](https://github.com/mswjs/msw)
msw intercepts requests on the network level
what allows us isolate the tests without a need to jest.mock anything
closes #725
jest:
1. go offline
2. run `yarn test`
3. tests pass and you see a few `[MSW] Error: captured a request without a matching request handler:` errors
storybook:
1. go offline
2. run `yarn storybook`
3. "stories" are visible and you can see a few `[MSW] Error: captured a request without a matching request handler:`

chore: set up msw

---

package.json

useful instead of PRing things, esp for first time contributors
n/a
1. run `yarn local-ci`
2. cry if it fails on your branch
n/a

chore: yarn script to run ci things locally

---

README.md
sample.env

Makes things that are not secret, not so hard to find for new developers who are contributing. 
Specifically the `REACT_APP_PORTIS_DAPP_ID` and `REACT_APP_ETHEREUM_NODE_URL`
2. etc...

chore: adds sample.env vars and updates readme to ease dev onboarding

---

src/context/PortfolioProvider/PortfolioContext.tsx
src/state/slices/portfolioSlice/portfolioSlice.ts

closes #820 
1. Pull branch locally and run `yarn dev` to start the server
2. Go to your dashboard and switch between your wallets 
3. Notice how the charts and wallet assets are now loading up
https://user-images.githubusercontent.com/35400192/151299673-3cb9cb51-ecca-45a0-b015-0962b19c7725.mov
I was asked to provide an estimate on how much time this took, and this issue took way longer than expected and the solution was a rather simple one. My rough estimate for this is around 4-5 hours

fix: portfolio dispatching (#820)

---

src/context/PortfolioProvider/PortfolioContext.tsx
src/state/slices/marketDataSlice/marketDataSlice.tsx
src/state/slices/portfolioSlice/portfolioSlice.ts

Fixes #858
#858
1. Setup local dev environment
2. Connect a wallet with assets in it
3. Note any one assets current value
4. Wait atleast 2 minutes and then check the value of the same asset
5. It should reflect the new market data

feat: realtime market data

---

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx

Updated useSendDetails tests as required in https://github.com/shapeshift/web/issues/755
2. etc...

feat: update use send details tests

---

headers.js

Part of adding trust wallet icons, we'll need to allow that url, adding this here.
2. etc...

chore: add support for trust wallet src

---

src/config.ts
src/constants/FeatureFlagEnum.ts

chore: add cosmosinvestor to config and featureflag

---

.github/workflows/pr.yml

Enabling github actions to trigger testing on release branches
closes https://github.com/shapeshift/web/issues/805
Github actions trigger on this PR

chore: trigger github actions testing on release branches

---

src/AppProviders.tsx
src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/config.ts
src/constants/FeatureFlag.ts
src/constants/FeatureFlagEnum.ts
src/hooks/useFeature/useFeature.ts

closes #901 
also removes the need of `useFeature` function

chore: change existing featureflags to use config

---

src/assets/translations/messages-pt.json

feat: v2 in portuguese (revised)

---

src/assets/translations/messages-fr.json

Translation of the UI strings in French.

feat: initial french translation

---

src/components/StakingVaults/EarnOpportunityRow.tsx

If applicable, please link to the github issue and put `closes #932` in your comment to auto-close the issue that your PR fixes.
2. etc...

chore: remove second "vault" from yearn opportunities - WEB-932

---

src/AppProviders.tsx
src/assets/translations/index.ts
src/lib/browserLocale.ts

- Quick and dirty solution until product team is ready with a language select component. 
- Defaults back to EN if no translation is available for the locale.
- Probably not the best implementation, but it works and its temporary

feat: default language to match browsers set preference

---

src/assets/translations/messages-en.json
src/context/WalletProvider/SelectModal.tsx
src/context/WalletProvider/WalletProvider.test.tsx
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/config.ts

1- Added translations properties for the footer text and button implemented in the SelectModal - commit 2e871eb2256a6c53fcdd3406aa6c16984447c276
2 - Implemented the text and button in the SelectModal, both inserted in a flex component which is completely responsive - commit 274dc0b79242bd52444b60f1ead569c2aba214ef
3 - I've created a callback function for dispatch a new action route according to the key, which it's being passed as Native in the SelectModal - This way, providing a path of creating new possible integrations for creating new wallets with other keys in the future - commit 7369b863487a2fe72314a753cd29f27c84c1ec83
closes the Issue: #931 related to the Gitcoin Bounty: …

feat: create a wallet button in SelectModal wallet modal

---

src/assets/translations/index.ts
src/assets/translations/messages-ko.json

Authored by: LPX
Co-Authored by: 0xGupta

feat: Korean locale

---

.github/ISSUE_TEMPLATE/bounty.yml
.github/ISSUE_TEMPLATE/config.yml

template for consistency in creating bounties, forked from https://github.com/shapeshift/web/pull/1000/files
closes #982 
wip
see https://github.com/shapeshift/web/pull/1000/files

docs: bounty template

---

package.json
public/index.html
react-app-rewired.config.js
yarn.lock

This eliminates the dependency on `PUBLIC_URL` to make social sharing embed magic work, which will help make builds consistent across deployments.
Helps fix #958. (Will also need env var tweaks in the build pipeline after this.)

feat: use IPFS link for social sharing thumbnail

---

README.md

Improve README instructions for linking local packages. 

chore: improve package linking instructions in README

---

src/components/StakingVaults/EarnOpportunityRow.tsx
src/pages/Defi/components/OverviewHeader.tsx

Fixed mobile defi rows
Purely isolated to the view layer of yearn vaults. Will not impact deposit/withdraw functionality.
As long as the vault rows appear and the button works to open the deposit/withdraw this works correctly. 
There is no need to test deposit/withdrawals.
before

fix: fix mobile defi row

---

package.json
src/assets/translations/messages-en.json
src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/AssetTeaser.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunityRow.tsx
src/components/StakingVaults/EarnTableHeader.tsx
src/components/Table/Table.theme.ts
src/constants/UsdcPrecision.ts
src/theme/theme.ts
yarn.lock

- Reworked earn table to include more data
- Added an asset teaser popover
- Updated the latest version of framer-motion to fix a bug in the older version
E.g. an upgrade to `hdwallet` or core state management would be considered higher risk, and might require a full regression test. UI or isolated view changes, or something behind a feature flag may have near zero risk. Small bug fixes might require testing isolated …

feat: update earn table

---

src/assets/translations/index.ts
src/assets/translations/messages-id.json

Authored by: Eternal Flame#7739

feat: indonesian locale

---

src/components/StakingVaults/AssetTeaser.tsx

Do not encode the URL with the new structure
E.g. an upgrade to `hdwallet` or core state management would be considered higher risk, and might require a full regression test. UI or isolated view changes, or something behind a feature flag may have near zero risk. Small bug fixes might require testing isolated to the specific fix.
If your testing steps are technical, outline steps for an engineer to verify.
If your …

bug: do not encode url for asset

---

yarn.lock

chore: upgrade @types packages
N/A
None.
Nothing to test.

chore: upgrade @types packages

---

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/TokenRow/TokenRow.tsx

reverts regression in release branch not in prod
fixes 
will be isolated to the send functionality
please regression test sends
n/a

fix: revert send detail error handling 

---

.github/workflows/pr.yml

populates environment variables needed for tests in CI
n/a
if CI passes we're good
no testing required for ops - this doesn't affect application code.
n/a

chore: environment variables in PR ci runs

---

src/hooks/useTxDetails/useTxDetails.ts

A quick PR to implement gomes' suggestion to use enums.
Addresses https://github.com/shapeshift/web/pull/1076#discussion_r817022099
Refactor - N/A
Refactor - N/A
Refactor - N/A

refactor: use Direction enum

---

src/components/Transactions/TransactionContract.tsx
src/components/Transactions/TransactionReceive.tsx
src/components/Transactions/TransactionSend.tsx
src/components/Transactions/TransactionStatus.tsx
src/components/Transactions/TransactionTrade.tsx

Add a `TransactionStatus` component to reduce duplication across transaction rendering components.
Addresses comment https://github.com/shapeshift/web/pull/1076#discussion_r817016617
N/A
`yarn dev` and ensure transactions still display a status.
N/A

refactor: use TransactionStatus component

---

.github/workflows/pr-cypress.yml

Changes from package-lock.json to yarn.lock hash comparison in pr-cypress.yml
Minimal risk to CI pipeline
CI should pass on package updates.

fix: changed package-lock to yarn.lock in cypress yml

---

cypress/integration/dashboard_spec.ts

_This supersedes similarly named https://github.com/shapeshift/web/pull/1115, fixing base branch issues._
The skipped tests are flakey. I'm not yet sure why, but I'm removing them until I do.
N/A
N/A
`yarn test:cypress`
N/A

chore: skip flakey tests

---

src/context/ModalProvider/ModalProvider.tsx

Fix #1095
For close animation to work, we need to have the base chakra UI modal component rendered in vdom (which include AnimatePresence component)
https://github.com/shapeshift/web/issues/1095

fix: modal close animation

---

.github/workflows/bootstrap.yml
.github/workflows/pr-cypress.yml
.github/workflows/pr.yml

Note from @0xApotheosis: as our workflow names have changed with the introduction of an initial bootstrap workflow, we (@0xdef1cafe) will need to update the required checks accordingly. 
To mitigate the risk of blocking other `web` PRs, we should update this as close to merge time as possible - a dummy PR should then be created to triple check there are no teething issues.
This PR adds a `bootstrap` workflow that installs and caches all required files so that in `pr` and `pr-cypress` workflow the dependencies are not needed to be installed again.
closes #1104

feat: reduce redundant caches in github actions

---

src/Routes/Routes.tsx
src/pages/Flags/FlagRow.tsx
src/pages/Flags/Flags.tsx

Added a ui for turning on and off flags
No risk
Not hooked up to anything just stubbed out UI

feat: flag ui

---

cypress/integration/dashboard_spec.ts

test: fix dashboard cypress test when Cosmos plugin is enabled
N/A
None
Check Actions results for Cypress

test: fix dashboard cypress test when Cosmos plugin is enabled

---

.github/ISSUE_TEMPLATE/bounty.yml

Hopefully fixes issues with template not showing the bounty hunters section once an issue is created.
none
none, will have to iterate to see it take effect

chore: updated bounty template

---

headers.js

There is a new market service for osmosis tokens that uses this api.
E.g. an upgrade to `hdwallet` or core state management would be considered higher risk, and might require a full regression test. UI or isolated view changes, or something behind a feature flag may have near zero risk. Small bug fixes might require testing isolated to the specific fix.
If your testing steps are technical, outline steps for an engineer to verify.
If your testing steps are functional, please provide a full guide with any features requiring special attention for …

chore: updated CSP to include new osmosis market data provider

---

src/components/Card/Card.theme.ts
src/components/Layout/Header/NavBar/NavBar.tsx
src/components/Layout/Header/SideNavContent.tsx
src/components/StakingVaults/Cells.tsx
src/pages/Dashboard/Portfolio.tsx
src/pages/Defi/components/OverviewHeader.tsx
src/pages/Defi/components/VaultList.tsx

- Add the % change back to the portfolio
- Fix DOM warning for the isCompact prop
closes #1158 
no risk
Click the time frame buttons on the dashboard to see your % change.

feat: add percent change back to portfolio

---

package.json
yarn.lock

Bump market service from 2.0.2 to 2.0.3
E.g. an upgrade to `hdwallet` or core state management would be considered higher risk, and might require a full regression test. UI or isolated view changes, or something behind a feature flag may have near zero risk. Small bug fixes might require testing isolated to the specific fix.
If your testing steps are technical, outline steps for an engineer to verify.
If your testing …

chore: bump market service from 2.0.2 to 2.0.3

---

src/pages/Flags/Flags.tsx

feat: add feature flags reset button
N/A
None to users
1. Press ALT+SHIFT+F
2. Change a flag
3. Click Reset App
4. Press ALT+SHIFT+F
5. Press Reset Feature Flags

feat: add feature flags reset button

---

src/components/Layout/Header/NavBar/MainNavLink.tsx

- Fix the console warning about isCompact
None
None

fix: iscompact prop

---

src/context/TransactionsProvider/TransactionsProvider.tsx
src/hooks/useAccountSpecifiers/useAccountSpecifiers.ts
src/state/slices/txHistorySlice/selectors.ts
src/state/slices/txHistorySlice/txHistorySlice.test.ts
src/state/slices/txHistorySlice/txHistorySlice.ts
src/state/store.ts
src/test/mocks/store.ts

wip - a state machine for loaded tx's until we have restful tx history for btc and eth
related to a bunch of issues i won't link here as it'll close them when this is merged
this currently isn't consumed anywhere, only sets a flag in the state to be consumed by future bugfix PRs.
no testing required - if the app loads we're good

feat: transactions loaded state

---

src/state/store.ts

Blacklists txHistory from persisted store.
E.g. an upgrade to `hdwallet` or core state management would be considered higher risk, and might require a full regression test. UI or isolated view changes, or something behind a feature flag may have near zero risk. Small bug fixes might require testing isolated to the specific fix.
If your testing steps are technical, outline steps for an engineer to verify.
If your …

fix: blacklisting tx history from persisted store

---

.github/ISSUE_TEMPLATE/bounty.yml

Issues are often created without sufficient replication steps / related transaction IDs, which increases friction.
The aim of this PR is to add a prompt during the bounty creation process to encourage better replication steps to be provided.
N/A
N/A
Create a new issue and ensure the new fields render as expected.

chore: add additional details to bounty template

---

.github/workflows/pr-cypress.yml
.github/workflows/pr.yml
sample.env

This uses the newly provided API key from Gem
#847
We're not using the secret provided by Gem. There doesn't seem to be any implication but we should keep an eye on the requests possibly being blocked in the future. 
There's no Gem regression.
N/A

feat: use new gem API key

---

src/state/reducer.ts
src/test/mocks/store.ts

Fixes a console error with the new tx history api.
Then new tx history api wasn't added to the store, this causes a console error for it. This fix adds it to the store
No risk. Removes a console error and properly registers the new api to the store

fix: added new txhistory api reducer to store

---

src/context/PortfolioProvider/PortfolioContext.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/hooks/useAccountSpecifiers/useAccountSpecifiers.ts

When tx provider was rerendering, it was clearing the tx history without refetching from the rest endpoint.
Minimal risk. Refetching a lot right now, but that is a separate issue with tx provider re-rendering whenever an asset page is loaded.

fix: refetching tx history after clearing tx history

---

src/App.tsx
src/components/Trade/hooks/useSwapper/useSwapper.test.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/hooks/useAccountSpecifiers/useAccountSpecifiers.ts

getSupportedAdapters returns the constructors so doing getAdapter() instantiates a new class. Moving to getSupportedChains then using byChain(chain) will use singletons.
Minimal risk. Should see optimization improvement

chore: changed from using getSupportedAdapters to getSupportedChains

---

src/hooks/useVaultWithoutBalance/useVaultWithoutBalance.ts

This adds back filtering of yearn vaults with 0 USDC TVL.
Vaults with 0 value TVL were showing up with absurd APYs. This change filters out any vault without a TVL USDC value greater than 0.
Minimal Risk.
See that no yearn vaults in the Earn Opportunites show that have a $0 TVL

fix: filtering out all vaults with 0 USDC tvl value

---

package.json
yarn.lock

chore: update asset-service

---

src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts

hotfix: fix: wip fix for trade widget

fix: wip fix for trade widget

---

package.json
yarn.lock

chore: upgrade axios to 0.26.1
N/A
Low

chore: upgrade axios to 0.26.1

---

src/state/store.ts

Adds the new txHistoryApi middleware to the store.
Minimal Risk
Not much testing, a warning for RTK middleware should go away.
`react_devtools_backend.js:3973 Warning: Middleware for RTK-Query API at reducerPath "txHistoryApi" has not been added to the store.
Features like automatic cache collection, automatic refetching etc. will not be available.`

fix: add tx history api middleware

---

src/components/Layout/Header/NavBar/MainNavLink.tsx

- It adds tooltips on the menu when it's not on the mobile breakpoint and when it's not over 2xl breakpoint
closes #1175
- No risk
- Resize your window under `1440px` and hover your mouse on the menu on the left

feat: add tooltip to on smaller screen size

---

src/plugins/cosmos/CosmosAsset.tsx
src/plugins/cosmos/CosmostAssetTxHistory.tsx
src/plugins/cosmos/index.tsx

- `CosmosAsset.tsx` were missing the subroutes `Overview` and `Transactions`
- I added both routes but as the asset is not wired up right now, we needed to duplicate the `AssetTxHistory` file into the cosmos plugin in order to provide the chainId using a prop
- This file will be removed when it gets wired up because the chainId will be a `param` and we will be able to use both `Asset` and `AssetTxHistory`
closes #1291
- No risk, behind a feature flag and not wired up so
- Go to Cosmos asset page and see if `Overview` and `Transactions` tabs are showing and working as expected

fix: show overview and transaction tab on cosmos asset page

---

headers.js

Some suggested changes to #1360, the CF-testable version of @NeOMakinG's #1338.
- Adds doc comments with types so we can get the benefits of TS even though we can't use a .ts file
- A more comprehensive, and hopefully maintainable, set of functions for CSP transformation
- removes `'report-sample'` from `child-src`; it doesn't hurt anything, but it's not valid there
(doing this as a PR-into-a-PR so @NeOMakinG can see the changes separately)

chore: csp header splitting improvements

---

src/context/PortfolioProvider/PortfolioContext.tsx
src/hooks/useBalanceChartData/cosmoUtils.ts
src/hooks/useBalanceChartData/useBalanceChartData.ts
src/state/slices/stakingDataSlice/selectors.ts
src/state/slices/stakingDataSlice/stakingDataSlice.ts

Chart cosmos selectors

---

package.json
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawReducer.ts
yarn.lock

Fix minor UI bug + Update lib packages to fix bn issue
DO NOT MERGE UNTIL
https://github.com/shapeshift/lib/pull/507
IS MERGED AND INVESTOR-FOXY IS BUMPED

fix: initial withdraw type & bignumber issue

---

package.json
yarn.lock

chore: update lib

---

src/App.tsx
src/components/Alert/Alert.theme.ts
src/theme/theme.ts

- Make the update toast solid style
none
none

fix: remove ghost styling of update box and make solid

---

src/components/Graph/PrimaryChart/PrimaryChart.tsx

This PR renames a handful of tooltip-related variables in the PrimaryChart component. Specific changes include:
- Use `defaultTooltipStyles` instead of `defaultToopTipStyles` (typo)
- Use `tooltip*` instead of `toolTip*` for a number of style variables (to be consistent with other instances in the repo)
N/A
N/A
N/A
N/A

chore: use consistent spelling and casing for tooltip variables

---

src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx

App was crashing when navigating to Withdraw without any funds.  This follows the same pattern FoxyDeposit uses to get marketData in case the app doesn't have it stored in redux

fix: white screen

---

src/pages/Accounts/Account.tsx
src/plugins/cosmos/CosmosAccount.tsx
src/plugins/cosmos/CosmosAccountTxHistory.tsx
src/plugins/cosmos/CosmosAsset.tsx
src/plugins/cosmos/CosmostAssetTxHistory.tsx
src/plugins/cosmos/index.tsx

- Refactor plugin path pattern matching to add account pages. The new pattern matching for plugin `path` eliminates the need for repeated hard coded paths that we previously used.
- Add Cosmos `Account` component.
closes [Asset Allocation and Staking section missing](https://github.com/shapeshift/web/issues/1392) #1392 
There is a risk that this feature adds regressions with other paths, however, the risk is minimal, given it should only affect cosmos paths.
- Set both `cosmos-investor` and `plugin-cosmos` feature flags to true
- Navigate to the cosmos `Asset` page
- Click on the `Allocation` section of the Cosmos page, which takes you to the Cosmos `Account` page
- You should see the `Staking` section

feat: refactor plugin path to add cosmos accounts

---

src/App.tsx
src/assets/translations/main.json
src/components/Alert/Alert.theme.ts
src/components/Graph/PrimaryChart/PrimaryChart.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
src/pages/Accounts/Account.tsx
src/plugins/cosmos/CosmosAccount.tsx
src/plugins/cosmos/CosmosAccountTxHistory.tsx
src/plugins/cosmos/CosmosAsset.tsx
src/plugins/cosmos/CosmostAssetTxHistory.tsx
src/plugins/cosmos/components/AssetClaimCard/AssetClaimCard.tsx
src/plugins/cosmos/components/AssetHoldingsCard/AssetHoldingsCard.tsx
src/plugins/cosmos/components/StakedRow/StakedRow.tsx
src/plugins/cosmos/components/modals/Staking/views/Overview.tsx
src/plugins/cosmos/components/modals/Staking/views/Stake.tsx
src/plugins/cosmos/components/modals/Staking/views/StakeConfirm.tsx
src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
src/plugins/cosmos/components/modals/Staking/views/UnstakeBroadcast.tsx
src/plugins/cosmos/components/modals/Staking/views/UnstakeConfirm.tsx
src/plugins/cosmos/index.tsx
src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap
src/state/slices/portfolioSlice/portfolioSlice.test.ts
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/portfolioSlice/utils.test.ts
src/state/slices/portfolioSlice/utils.ts
src/state/slices/stakingDataSlice/selectors.ts
src/theme/theme.ts

7b73b868 fix: decimal places fix on percent click (#1424)
4d305a73 feat: refactor plugin path to add cosmos accounts (#1410)
1ba41c4d fix: white screen (#1421)
f0de60dc test: account balances buckets functions (#1334)
a3377295 chore: use consistent spelling and casing for tooltip variables (#1407)
6a887d0b fix: debounce send input (#1399)
906007d3 fix(cosmos): crypto/fiat amount fixes (#1398)
5a380513 fix(cosmos): ui nitpicks (#1391)
25e429d0 fix: updated links to use dynamic validator moniker and link to mintscan for them (#1403)
a861ed8a fix: wrong allocation computation (#1384)
0fa7a5b1 remove ghost styling of update box and make solid (#1397)
3db31ad4 Merge branch 'main' into develop
540f48dd fix: replace the cosmos static icon to asset icon on overview (#1388)

chore: create release 1.4.2 [DO NOT MERGE]

---

src/components/StakingVaults/StakingTable.tsx

this fixes deep linking to `/defi/earn` that causes the connect wallet modal to show incorrectly when clicking on the staking table

fix: fix memoized earn modal

---

src/assets/translations/main.json

Changed "FOXy" to "Staked FOX" because it makes more sense, plz merge if you agree

Small copy tweak to FOXy Overview

---

src/context/PortfolioProvider/PortfolioContext.tsx

When you are claiming, staking or unstaking, every cosmos datas should be reloaded
closes #1409
Not sure there are some risks, except if unchained is down when the reload happen!
- Go on the cosmos staking modal, stake, claim or unstake and see if every datas are reloaded when the websocket send a message to the app
https://user-images.githubusercontent.com/14963751/162471193-91c0244d-d909-4b6e-93fa-e045e6eec17f.mp4

fix: fetch staking datas on message from websocket

---

headers.js
src/components/Delegate/StakingOpportunities.tsx
src/plugins/cosmos/components/ClaimButton/ClaimButton.tsx
src/plugins/cosmos/components/modals/Staking/views/ClaimConfirm.tsx
src/plugins/cosmos/components/modals/Staking/views/Overview.tsx
src/plugins/cosmos/components/modals/Staking/views/StakeConfirm.tsx
src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
src/plugins/cosmos/components/modals/Staking/views/UnstakeConfirm.tsx

- Fix the validator logo, It's coming from cosmostation now.
- Disable claim button if rewards === 0
- Calculate balance and gas fees in order to disable buttons, so we can't go further in case we don't have enough balance (Staking Confirm, Claim Confirm, Unstake Confirm)
- Hide unstaking part if no undelegations yet
#1445 but not really closing as some questions has been added to the issue
Cosmos claim, stake, unstake flow
- Try to claim, stake, unstake, play with really low balances, try with a fresh wallet without any cosmos (for the claim button disabled)
- See the video
https://www.awesomescreenshot.com/video/8318019?key=8d1c9a4463503ad184c7def24d7eb6c1

fix: multiple UI/UX bugs on cosmos staking modal

---

.github/workflows/pr-cypress.yml
cypress/plugins/index.ts
src/Routes/PrivateRoute.tsx
src/config.ts

Closes #1458.
_De minimis._
None required.

chore: remove unused env vars

---

src/plugins/cosmos/components/AssetHoldingsCard/AssetHoldingsCard.tsx
src/plugins/cosmos/components/modals/Staking/views/Stake.tsx
src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx

On cosmos Stake and Unstake, we want to use the same design as Yearn and Foxy, including USD amounts
closes #1462 
- Showing wrong info in cosmos Stake and Unstake modal
- Go on stake modal, look at the card amount
- Go to unstake modal, look at the card amount
- See screenshots and issue

fix: show usd amount in cosmos stake and unstake

---

sample.env
src/config.ts
src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyDetails.tsx
src/pages/Defi/hooks/useFoxyBalances.tsx

add FOXy APY to env file to make it easier to change until they complete their api
closes #1469

chore: add apy to env file

---

src/pages/Defi/components/OverviewHeader.tsx

closes #1272
- Wrong amount on the defi page in case I did something wrong
- Go on defi page while having some earn/staking amount
- See if the net worth and wallet balance is fine

fix: balance and net worth amount of the defi page

---

cypress.json
sample.env
scripts/postinstall.sh
src/AppProviders.tsx
src/components/Breadcrumbs/Breadcrumbs.tsx
src/config.ts
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/WalletViewsSwitch.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyDetails.tsx
src/pages/Defi/components/OverviewHeader.tsx
src/pages/Defi/hooks/useFoxyBalances.tsx
src/plugins/cosmos/components/modals/Staking/views/Overview.tsx
src/plugins/cosmos/components/modals/Staking/views/Stake.tsx
src/plugins/cosmos/components/modals/Staking/views/StakeBroadcast.tsx
src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
src/plugins/cosmos/components/modals/Staking/views/UnstakeBroadcast.tsx
src/plugins/cosmos/index.tsx

0ce2e154 chore: change FOXY_APY config to 'num' instead of 'str' (#1481)
39e53ad1 fix: balance and networth amount of defi page (#1487)
df3fc2f1 fix: don't claim fractions of uatom (#1486)
a9c4065e fix: remove default validator in <StakeBroadcast /> and use validator link in <UnstakeBroadcast /> (#1485)
476edb7a chore: avoid possible lockfile changes in CI (#1476)
7f714fd3 chore: don't call hdwallet adapter.initialize if it's not there (#1447)
44d41304 fix: set percents at the top of the stack on cosmos (#1480)
ac0a0812 fix: add additional path for cosmos plugin account page (#1443)
69a767e2 refactor: invert noBackButton to showBackButton (#1463)
65f43073 chore: add apy to env file (#1470)
abc7075d feat: use hash routing instead of browser routing (#1457)

chore: create release v1.5.0 [DO NOT MERGE]

---

src/hooks/useTxDetails/useTxDetails.ts
src/state/slices/assetsSlice/selectors.ts

There are some cases when shapeshift api returns transactions with no CAIP19 assets (like some pending transactions) and `useTxDetails` is unable to identify block explorer for this transaction (because `standardAsset`, `tradeAsset` and `feeAsset` are all undefined) which then generates invalid link in tx history UI. I propose additional `defaultFeeAsset` determined by CAIP2 of transaction which will be used if all other assets are undefined. 
closes https://github.com/shapeshift/web/issues/1374

fix: fallback to default fee asset based on tx.caip2

---

src/context/WalletProvider/KeepKey/components/WipedSuccessfully.tsx

Properly disable the Recover Wallet button.
We are disablIng this button until the recovery flow is complete.
N/A
N/A
N/A
N/A

fix: disable recover wallet

---

sample.env
src/config.ts

Adds a feature flag to hide the wallet migration feature until development is done.
closes #1504 
minimal risk
No code is merged behind the feature flag yet, so we can't yet test it.

chore: added feature flag for wallet migration

---

src/assets/translations/es/main.json
src/assets/translations/fr/main.json
src/assets/translations/ko/main.json
src/assets/translations/main.json
src/assets/translations/zh/main.json
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Confirm.tsx

Git settings were all messed up on local repo. Re-done on fresh repo. `common.approve` and `common.confirm` updated for active languages updated as well. Indonesian and Russian locales should be caught up in 3-4 days.
closes #1440

chore: foxy wording changes

---

package.json
yarn.lock

bumps the asset service version to blacklist KICK and update ATOM custom description
closes #509 - we missed KICK originally
essentially zero
search for KICK - no results should be returned
n/a

chore: bump asset service version

---

src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

Missed a spot for a new feature flag. This fills that spot.
n/a
minimal
Should see a new feature flag in feature flag area.

fix: updated preferences with new feature flag

---

src/components/Modals/FiatRamps/components/AssetSearch/AssetSearch.tsx
src/components/Modals/FiatRamps/config.ts
src/components/Modals/FiatRamps/hooks/useFiatRampCurrencyList.ts
src/components/Modals/FiatRamps/utils.ts
src/components/Modals/FiatRamps/views/AssetSelect.tsx
src/components/Modals/FiatRamps/views/Manager.tsx
src/components/Modals/FiatRamps/views/Overview.tsx
src/components/Modals/FiatRamps/views/RampsList.tsx
src/state/slices/portfolioSlice/utils.ts

suggested changes to original PR https://github.com/shapeshift/web/pull/1449
closes #1387 
fairly hefty refactor - risk is isolated to fiat ramps
all functionality including ens names, wallets not supporting bitcoin, should be tested up until going to purchases

refactor: fiat ramp abstraction changes

---

src/components/Trade/hooks/useSwapper/useSwapper.ts
src/components/TransactionHistoryRows/TransactionTrade.tsx
src/components/TransactionHistoryRows/UnknownTransaction.tsx

Cleanup before adding thor trading:
Remove thortrade specific code from web because it doesnt make sense as implemented and will be changing.
very little. removing code that wasnt used anyway
Make sure everything works as usual -- sends, receives, tx history, trades

chore: remove thorchain specific code from web

---

src/assets/translations/main.json
src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx
src/context/WalletProvider/NativeWallet/components/NativeStart.tsx
src/context/WalletProvider/config.ts

- We want's to add a link to the ShapeShift starting route from the wallet modal
- We want's a login form for the native wallet feature, including controls, captcha (to be changed by a real captcha) and an hidden 2fa field
closes #1493
- Having a non-working form inside the ShapeShift modal wallet
- Open the wallet modal
- Click on ShapeShift
- Click on the `Log In` link at the bottom
- Play with the form => It should contain validation, errors, 2fa hidden input

feat: add legacy login form to the wallet modal

---

src/hooks/useHasAppUpdated/useHasAppUpdated.test.ts
src/hooks/useHasAppUpdated/useHasAppUpdated.ts

this got broken on localhost. this refactors the hook, adds tests for both localhost and hosted environments and stops log spew.
closes #1309

fix: fix app updater hook again

---

src/assets/translations/main.json
src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx

This PR is a follow-up PR of the login screen of legacy wallet, adding the error handling of the login page, waiting for the API implementation
partially #1497
- Not that risky, behind a feature flag
- Try to login and see the error (or watch the screen)

feat: handle legacy login form errors

---

src/lib/cryptography/login.test.ts
src/lib/cryptography/login.ts

This creates the hashing algorithm that will be used for the legacy wallet migration
closes #1495 
No risk, unused code at the moment.
Can be tested with the full login flow later once we have a backend

feat: add password hashing for legacy wallet migration

---

public/index.html

https://www.debugbear.com/blog/rel-preload-problems
this causes warnings and we can preload (low priority) rather than prefetch (high priority) with the same effect and no
warning
n/a - quality of life
the app doesn't load - we'll know quickly
nothing for ops
n/a

fix: fix env.json prefetch warning

---

.github/workflows/add-issue.yml
public/index.html
src/AppProviders.tsx
src/context/AppProvider/AppContext.tsx
src/context/PluginProvider/PluginProvider.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/context/WalletProvider/NativeWallet/components/NativeImport.tsx
src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts
src/state/slices/accountSpecifiersSlice/accountSpecifiersSlice.ts
src/state/slices/accountSpecifiersSlice/selectors.ts
src/state/slices/assetsSlice/selectors.ts
src/state/slices/portfolioSlice/portfolioSlice.test.ts
src/state/slices/portfolioSlice/portfolioSlice.ts
src/state/slices/portfolioSlice/portfolioSliceCommon.ts
src/state/slices/portfolioSlice/selectors.test.ts
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/portfolioSlice/utils.ts
src/state/slices/stakingDataSlice/stakingDataSlice.test.ts
src/state/slices/txHistorySlice/txHistorySlice.test.ts
src/state/slices/txHistorySlice/txHistorySlice.ts

5255645c fix: correct validations on import native wallet (#1517)
e469b829 fix: fix env.json prefetch warning (#1542)
34250488 chore: cleanup workflow comments
b1794220 chore: add-issue action
34a17854 fix: wallet, portfolio and tx management (#1520)
5bc1e7f3 chore: trigger ci

chore: create release v1.7.0 [DO NOT MERGE]

---

package.json
src/hooks/useBalanceChartData/useBalanceChartData.ts
src/state/slices/assetsSlice/selectors.ts
src/state/slices/marketDataSlice/selectors.ts
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/preferencesSlice/preferencesSlice.ts
src/state/slices/preferencesSlice/selectors.ts
src/state/slices/stakingDataSlice/selectors.ts
src/state/slices/txHistorySlice/selectors.ts
src/state/store.ts
yarn.lock

* **download [reselect devtools](https://chrome.google.com/webstore/detail/reselect-devtools/cjmaipngmabglflfeepmdiffcijhjlbb?hl=en) to test**
* correctly initializes/configures reselect-tools to make reselect-tools work with inputs and outputs
* sanitizes large actions and state so redux dev tools work again
* adds re-reselect as a dependency - necessary for most things we're querying by id 
* https://github.com/toomuchdesign/re-reselect#why--example
n/a - developer quality of life and performance improvements
this changes the way selectors are memoized - the app feels correct but could do with a pass of operations testing
general use of the app - it will be pretty quickly apparently if things are broken

chore: fix reselect and redux dev tools

---

src/components/Trade/TradeInput.tsx
src/index.tsx
src/service-worker.ts
src/serviceWorkerRegistration.ts

b368a59d feat: add service-worker (#1558)
fe9c03cc fix: double gas fee deduction (#1529)

chore: create release v1.8.0 [DO NOT MERGE]

---

src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositReducer.ts
src/features/defi/providers/foxy/components/FoxyManager/FoxyManager.tsx
src/features/defi/providers/yearn/components/YearnManager/YearnManager.tsx

Fix FOXy APY estimation on confirm
Fix routing issue for FOXy & yearn.  If navigating to Confirm and then switching between Deposit/Withdraw the routes would break
closes #1586

fix: foxy apy

---

src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx

This logs the caught error (with `console.error`) in `useStakingAction` so we don't let nasty bugs slip through.

feat: log caught error in useStakingAction

---

package.json
yarn.lock

bump chain adapters to include https://github.com/shapeshift/lib/pull/563
n/a bugfix
regressions around ATOM reward claiming
ATOM reward claiming must be tested with both native and keepkey
n/a

chore: bump chain-adapters

---

src/features/defi/components/Withdraw/Withdraw.tsx

- fix: enable instant withdrawals button
- fix: update instant withdrawal hardcoded amount with comment as to source of truth
n/a - first rebase event
FOXy instant withdrawals fail
test FOXy instant withdrawals

fix: foxy instant withdrawals

---

src/assets/translations/main.json

- Improve copy across KeepKey and PIN modals
- Uppercase all instances of PIN in English translations
Closes https://github.com/shapeshift/web/issues/1612
Minimal - cosmetic only.
N/A
N/A

feat: keepkey and pin modal copy improvements

---

headers.js
sample.env
src/assets/translations/main.json
src/config.ts
src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx
src/context/WalletProvider/NativeWallet/types.ts
src/lib/cryptography/login.ts
yarn.lock

Wires up the api call to the legacy migration flow.
closes #1528 
closes #1498 
Low risk to the legacy migration flow (behind a feature flag).
To test, we'll need to update the env var REACT_APP_WALLET_MIGRATION_URL to point at the new backend cloud instances. Then you'll need auth creds to an existing user on legacy ShapeShift (staging or prod depending on environment). Once you login with your existing creds, it should bring back your wallet, decrypt it and allow you to back it up, then ask you to re-encrypt it with a new password, then show your dashboard with your existing balances.

feat: login api calls

---

cypress/integration/dashboard_spec.ts
cypress/integration/login_spec.ts
cypress/support/commands.ts
src/components/Layout/Header/NavBar/NavBar.tsx
src/components/Layout/Header/NavBar/UserMenu.tsx
src/components/Layout/Header/SideNavContent.tsx
src/components/NestedMenu/NestedMenu.tsx
src/components/StakingVaults/Cells.tsx
src/components/Trade/TradeConfirm/TradeConfirm.tsx
src/components/Trade/TradeInput.tsx
src/context/WalletProvider/SelectModal.tsx
src/pages/Defi/components/OpportunityCardList.tsx

Adding human readable `data-test` tags to components as described in #1551

chore(data-test): add data-test tags

---

src/components/Layout/Header/NavBar/SubmenuHeader.tsx
src/components/Tooltip/Tooltip.theme.ts
src/components/TransactionHistoryRows/TransactionGenericRow.tsx
src/components/UnderlyingToken.tsx
src/features/defi/components/Withdraw/Withdraw.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Status.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx
src/hooks/useHasAppUpdated/useHasAppUpdated.test.ts
src/hooks/useVaultWithoutBalance/useVaultWithoutBalance.ts
src/pages/Defi/views/StakingVaults.tsx
src/plugins/cosmos/components/StakingInput/StakingInput.tsx
src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx

We are passing properties around that are not used. 
Fix that, part 2.
N/A
There is a risk I altered behaviour in a way I didn't expect.
Everything should work as it did before.
N/A

chore: remove unused local symbols (2)

---

src/components/AccountRow/AccountRow.tsx
src/components/AccountRow/Allocations.tsx
src/components/AssetAccounts/AssetAccountRow.tsx
src/components/Form/form.theme.ts
src/components/Modals/Settings/Languages.tsx
src/components/Modals/Settings/SettingsRouter.tsx
src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
src/context/WalletProvider/NativeWallet/components/NativeTestPhrase.tsx
src/features/defi/components/Deposit/Deposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/FoxyManager.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyDetails.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
src/pages/Dashboard/components/AccountList/AccountTable.tsx
src/pages/Flags/Flags.tsx
src/plugins/cosmos/components/modals/Staking/views/Stake.tsx

We are passing properties around that are not used. 
Fix that, part 1.
N/A
There is a risk I altered behaviour in a way I didn't expect.
Everything should work as it did before.
N/A

chore: remove unused local symbols (1)

---

src/components/Trade/hooks/useSwapper/useSwapper.ts

Test swapper shouldnt be here. accidentally included it in another pr

fix: dont include test swapper

---

src/components/ReactTable/ReactTable.tsx
src/components/StakingVaults/Cells.tsx
src/components/StakingVaults/StakingTable.tsx
src/pages/Dashboard/components/AccountList/AccountTable.tsx

closes #1638
Now It's possible to click anywhere in the row.
closes #1638 
minimal
there should be no change to existing behavior
check the screens where ReactTable is used:
- https://app.shapeshift.com/#/assets/cosmos:cosmoshub-4/slip44:118 (src/components/Delegate/StakingOpportunities)
- https://app.shapeshift.com/#/defi/earn
- https://app.shapeshift.com/#/assets
- https://app.shapeshift.com/#/accounts
- https://app.shapeshift.com/#/assets/eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d

fix: portfolio asset row click handler

---

src/context/WalletProvider/KeepKey/components/Label.tsx
src/context/WalletProvider/KeepKey/components/RecoverySentenceEntry.tsx
src/context/WalletProvider/KeepKey/helpers.test.ts
src/context/WalletProvider/KeepKey/helpers.ts

Extracts pure functions into helper and adds tests.
Closes https://github.com/shapeshift/web/issues/1576
Minimal - there should be no change to existing behavior.
`yarn test` should pass, so should CI.
N/A

chore: add tests for KeepKey helpers

---

.eslintrc
src/components/AssetHeader/AssetActions.tsx
src/components/Button/Button.theme.ts
src/components/Graph/MaxPrice.tsx
src/components/Graph/MinPrice.tsx
src/components/Layout/Header/NavBar/KeepKey/LastDeviceInteractionStatus.tsx
src/components/Modals/FiatRamps/components/AssetSearch/AssetList.tsx
src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useSwapper/useSwapper.ts
src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx
src/context/WalletProvider/WalletProvider.tsx
src/features/defi/contexts/FoxyProvider/FoxyProvider.tsx
src/hooks/useSortedYearnVaults/useSortedYearnVaults.test.ts
src/pages/Defi/components/OpportunityCard.tsx
src/pages/Defi/hooks/useEarnBalances.tsx
src/state/slices/stakingDataSlice/stakingDataSlice.ts

Add `object-shorthand` lint rule, and fix non-complying occurrences.
N/A
N/A
N/A
N/A

chore: add `object-shorthand` ESLint rule

---

src/components/Layout/Header/NavBar/KeepKey/Modals/Wipe.tsx
src/components/Layout/Header/SideNav.tsx
src/context/WalletProvider/KeepKey/KeepKeyTypes.ts
src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/NativeWallet/components/NativePassword.tsx
src/context/WalletProvider/NativeWallet/components/NativeRename.tsx
src/context/WalletProvider/WalletViewsRouter.tsx
src/service-worker.ts
tsconfig.json

Add `noUnusedLocals` TS rule.
N/A
N/A
N/A
N/A

chore: add noUnusedLocals TS rule

---

src/components/Graph/MaxPrice.tsx
src/components/Graph/MinPrice.tsx
src/components/Graph/PrimaryChart/PrimaryChart.tsx
src/components/Modals/FiatRamps/fiatRampProviders/gem.ts
src/components/SelectAssets/SelectAccount.tsx
src/components/SelectAssets/SelectAssets.tsx
src/service-worker.ts
src/state/slices/marketDataSlice/selectors.ts
src/state/slices/preferencesSlice/selectors.ts
src/state/slices/stakingDataSlice/selectors.ts
src/state/store.ts
tsconfig.json

Following on from https://github.com/shapeshift/web/pull/1633 and https://github.com/shapeshift/web/pull/1634, this PR is the final piece of the puzzle to turn on the `noUnusedParameters` TS rule.
Note, whilst `_` was prepended to unused selector arguments, these arguments will go away entirely once @gomesalexandre's [PR](https://github.com/shapeshift/web/pull/1635) to improve selector arity is in.
N/A
Minimal, no changes to logic.
Everything should continue to work unchanged.
N/A

chore: add noUnusedParameters TS rule

---

src/context/WalletProvider/KeepKey/components/RecoverySentence.tsx
src/context/WalletProvider/KeepKey/components/RecoverySentenceEntry.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyCancel.ts
src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts

Revert "Revert "fix: keepkey recovery flow cancel and close events (#1653)""

---

src/context/AppProvider/AppContext.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts
src/state/slices/accountSpecifiersSlice/accountSpecifiersSlice.ts
src/state/slices/portfolioSlice/portfolioSlice.ts
src/state/slices/txHistorySlice/txHistorySlice.ts

updates existing logging to be compatible/fancy with new logger
same as parent branch
negligible - logging.
console should look pretty

chore: update existing logging

---

scripts/release.sh

Change merge release script to update local `main` branch after the release has been merged.
N/A
No user impact. Only affects the developer merging the release branch.
Very hard to test without doing merges. I manually tested the 3 commands that were added and it worked.

chore(scripts): after release merge, pull main branch

---

src/components/Approval/Approval.tsx
src/components/Layout/Header/NavBar/KeepKey/ChangeLabel.tsx
src/components/Layout/Header/NavBar/KeepKey/ChangePassphrase.tsx
src/components/Layout/Header/NavBar/KeepKey/ChangePin.tsx
src/components/Layout/Header/NavBar/KeepKey/ChangeTimeout.tsx
src/components/Layout/Header/NavBar/hooks/useMenuRoutes.ts
src/components/UnderlyingToken.tsx

This is an ongoing process and there will be multiple PRs.
N/A
Low. TypeScript should catch any invalid uses of the logger
Depends on what ends up getting changed in this PR.

chore(logging): change console logging to structured logging

---

src/components/Layout/Header/NavBar/KeepKey/Modals/Wipe.tsx
src/components/Modals/FiatRamps/fiatRampProviders/gem.ts
src/components/Modals/FiatRamps/views/Manager.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Trade/TradeInput.tsx

This is an ongoing process and there will be multiple PRs.
N/A
Low
None

chore: update logging in various components

---

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx

028d2fb1a8225da2e00ab6302290c5419cfedc14 fix: use feeAsset.assetId for nativeAssetBalance (#1696)

chore: create release v1.15.1 [DO NOT MERGE]

---

src/components/AssetHeader/AssetChart.tsx

With this code, on asset page, balance chart is displayed when there is a non zero balance, otherwise the price chart is displayed. Previously, price chart was displayed everytime.
https://github.com/shapeshift/web/issues/1639
No risk identified
- go to asset page for an asset with a non zero balance
- verify the balance chart is displayed by default
- go to asset page for an asset with a zero balance
- verify the price chart is displayed by default

feat: asset page - default to balance chart for non zero balance

---

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/TransactionHistoryRows/TransactionContract.tsx
src/components/TransactionHistoryRows/TransactionDetails/TransferCol.tsx
src/components/TransactionHistoryRows/TransactionDetails/Transfers.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/WithdrawCard.tsx
src/pages/Defi/hooks/useFoxyBalances.tsx
src/plugins/bitcoin/index.tsx
src/plugins/cosmos/components/modals/Staking/views/ClaimConfirm.tsx
src/plugins/cosmos/components/modals/Staking/views/StakeConfirm.tsx
src/plugins/cosmos/components/modals/Staking/views/UnstakeConfirm.tsx
src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx
src/plugins/cosmos/utils.ts
src/plugins/ethereum/index.tsx
src/state/slices/stakingDataSlice/selectors.ts
src/state/slices/stakingDataSlice/stakingDataSlice.ts

This updates the dist imports to their `index.d.ts` counterparts.
N/A
None, this is just changing the import from dist to the actual package exports. I did some regression testing to be sure and didn't find any regressions nor logs weirdnesses.
N/A
N/A

chore: don't import from lib dist

---

src/features/defi/components/Approve/Approve.tsx
src/features/defi/components/Confirm/Confirm.tsx
src/features/defi/components/DefiModal/DefiModal.tsx
src/features/defi/components/Deposit/Deposit.tsx
src/features/defi/components/TxStatus/TxStatus.tsx

- Added some additional tags for pendo on the defi modals
closes #1713 
low risk
n/a

chore: add more test tags for pendo

---

src/assets/translations/en/main.json
src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx
src/context/WalletProvider/NativeWallet/types.ts

Adds a rate limiting error to the legacy wallet migration to tell the user to try again later.
Minimal risk to legacy wallet migration flow.
Need to try to login with the same email or ip address 10 times within 10 min. If you do, then you should see an error telling you to try again later.
Ignore the removal of catpcha, that was just removed for development.

chore: added a rate limiting error to legacy wallet flow

---

src/components/Layout/Header/NavBar/UserMenu.tsx
src/context/WalletProvider/MetaMask/components/Connect.tsx
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/actions.ts

Added a button group to separate the dropdown button while wallet is stuck in a loading state when Metamask is locked
Fixes #1262 
Reproduced by locking Metamask and checked to see that the dropdown button is usable and reveals dropdown menu
https://user-images.githubusercontent.com/14836056/166608288-62e27d26-5b38-4884-8000-468f7e057098.mov

fix(UserMenu): locked metamask not reconnecting

---

src/context/WalletProvider/NativeWallet/components/LegacyLogin.tsx

n/a - identified manually testing prod endpoint
negligible - fixes error handling not handling errors
* try with a wrong username/password combo a few times, should display a rate limiting error
* screenshot below should not appear in console

fix(walletmigration): opt chain rate limit check

---

sample.env
src/context/WalletProvider/NativeWallet/components/NativeCreate.tsx

- chore: update sample.env with new wallet migration url
- chore: update wallet migration learn more support link
points "Learn more" link to zendesk support article regarding deprecation
n/a - discovered in testing
none - link works or it doesn't
**please note** - this does not work locally due to CORS, please test in the hosted environments
check that the learn more link links out to the correct support article

chore: fix wallet migration learn more link

---

sample.env
src/config.ts
src/pages/ConnectWallet/ConnectWallet.tsx
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

Remove the `REACT_APP_FEATURE_DEMO_WALLET` feature flag and all corresponding logic.
NOTE: Still in draft until this Demo Wallet is fully deployed to Production and tested more extensively.
N/A
Given this flag is already enabled in production, the risk of removing it should be minimal. 
As long as no directly-related issues are raised while being tested in prod, we should be perfectly safe to remove it.
Everything should still work as it did before, including both the Demo Wallet, as well as all other non-demo functionality.

chore(featureFlags): remove REACT_APP_FEATURE_DEMO_WALLET flag

---

src/features/defi/components/Deposit/Deposit.tsx

The term of service link was wrong on defi modals, leading to a redirect to the dashboard and another bug while navigating
closes #1745
No risk
- Go to a Yearn Vault modal
- Click on deposit
- Click on the term of service link at the bottom
- You should have a new tab opened with the right content

fix: wrong term of service link on defi modals

---

src/components/AssetSearch/AssetSearch.tsx
src/components/Modals/FiatRamps/components/AssetSearch/AssetSearch.tsx

This enables auto focus on asset search input box for trade asset / search asset / buy and sell asset modals
https://github.com/shapeshift/web/issues/1723
No particular risk identified
- Navigate to assets page
- Verify input field is auto focused
- Click on one asset in the trade window
- Verify input field is auto focused
- Click on buy / sell crypto => Gem / Buy => Select an asset to buy
- Verify input field is auto focused

fix: asset search auto focus

---

sample.env
src/config.ts
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

We will need a feature flag for the Foxy Page feature
closes #1756
No risk
See if the feature flag is shown inside the feature flag page

chore: add FoxyPage feature flag

---

src/plugins/cosmos/components/modals/Staking/views/GetStarted/GetStarted.tsx
src/plugins/cosmos/components/modals/Staking/views/GetStarted/LearnMore.tsx
src/state/slices/assetsSlice/selectors.ts

this was hardcoded to osmo - this now uses a selector to get the correct asset name from the assetId param
n/a - found in release testing
low - asset name should appear correctly
follow the same steps used to discover this bug

fix: show correct asset name for staking info

---

src/components/Layout/Header/NavBar/NavBar.tsx
src/context/PluginProvider/PluginProvider.tsx
src/plugins/foxPage/foxPage.tsx
src/plugins/foxPage/index.tsx

This adds a skeleton plugin for fox page, only available when REACT_APP_FEATURE_FOX_PAGE flag is enabled
closes https://github.com/shapeshift/web/issues/1762
- Try accessing /fox without feature flag, notice we are not able to navigate to fox page
- Enables feature flag
- Notice FOX Token appeared in nav bar
- It is possible to navigate to dummy / temporary fox page

feat: add fox page as plugin

---

src/assets/translations/en/main.json
src/hooks/useTxDetails/useTxDetails.ts

Added support for Stake/Unstake transaction methods from uniV2 parser
closes https://github.com/shapeshift/web/issues/1214
Pull this PR https://github.com/shapeshift/web/pull/1798, build `unchained-client` and `asset-service` and link them to the `web`
Connect ethereum account which interacted with contract `0x212ebf9FD3c10F371557b08E993eAaB385c3932b`
Go to `Transaction History` page

feat: uni-v2 staking txns support

---

src/components/Trade/hooks/useSwapper/calculateAmounts.test.ts
src/components/Trade/hooks/useSwapper/calculateAmounts.ts
src/components/Trade/hooks/useSwapper/useSwapper.ts

Cleanup of `usSwapper`. This is the follow up PR to #1691, however we still need to address [this](https://github.com/shapeshift/web/pull/1691/files#r869447635) comment. There will be another follow up PR to this one after [#665](https://github.com/shapeshift/lib/pull/665) in lib is merged.
Contributes to https://github.com/shapeshift/web/issues/1728
Can affect the populated values inside trade.
- Change the values inside of the trade section 
- Make sure all of the trade values are calculating properly.

chore: refactor calculateAmounts helper function for useSwapper

---

.storybook/main.js

Some storybook stories do not load properly due to missing `buffer` polyfill.

fix: add buffer polyfill to storybook

---

src/state/reselect-tools.test.ts
src/state/slices/marketDataSlice/selectors.ts
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/preferencesSlice/selectors.ts

the reselect tools got broken again. i fixed them, and added a test so it won't happen again.
- fix: fix reselect dev tools
- test: add test so these don't get broken again
n/a - i needed the tools to debug another branch.
negative - adds some optional chaining that was breaking things that just never actually got hit at
runtime, but was hit by the tools traversing the selector graph
download https://chrome.google.com/webstore/detail/reselect-devtools/cjmaipngmabglflfeepmdiffcijhjlbb
check if it works in the dev tools

fix: fix reselect-tools

---

src/assets/translations/en/main.json
src/plugins/foxPage/components/FoxTab.stories.tsx
src/plugins/foxPage/components/FoxTab.tsx
src/plugins/foxPage/components/Layout.stories.tsx
src/plugins/foxPage/components/Layout.tsx
src/plugins/foxPage/foxPage.tsx
src/plugins/foxPage/index.tsx

This implements routing with tabs on the fox page.
closes https://github.com/shapeshift/web/issues/1767
No risk
- Navigate to fox page
- Click on tabs and notice the selected tab is changing as well as the routing address (first tab is '/fox' or '/fox/fox', second tab is '/fox/foxy')
FOX tab
FOXy tab

feat: fox page tabs components routing

---

src/components/Trade/hooks/useSwapper/useSwapper.ts

Abstract out hardcoded magic 18 with appropriate abstracted out `asset.precision` property
Closes #1085

chore(asset.precision): replace magic 18

---

package.json
yarn.lock

Bump asset-service to `^4.1.0` to display `UNI-V2-FOX-WETH` asset.
closes #1214

chore: bump asset-service to 4.1.0

---

src/context/I18nProvider/I18nProvider.tsx

This reverts commit 47ad9b53f0fe471fb54b6e96a363e3fcb8aeba8d.
During XDEFI wallet testing, @loxator spotted that we are getting some errors:
```shell
TypeError: Polyglot.transformPhrase expects argument #1 to be string
at transformPhrase (index.js:203:1)
at transform (index.js:426:1)
at onMissingKey (I18nProvider.tsx:14:1)
at Polyglot.t (index.js:406:1)
at Text.tsx:25:1
at renderWithHooks (react-dom.development.js:14985:1)
at updateForwardRef (react-dom.development.js:17044:1)
at beginWork (react-dom.development.js:19098:1)
at beginWork$1 (react-dom.development.js:23940:1)
at performUnitOfWork (react-dom.development.js:22776:1) undefined 'transactionRow.parser.weth.deposit'
```
This reverts the commit until a fix of the fix is found
#1857

fix: revert "fix: interpolation on english fallback (#1858)"

---

src/plugins/foxPage/foxPage.tsx

FoxPage current implementation makes it hard to add an asset as you have to duplicate a lot of markup/component
- I added an `assetsRoutes` variable so it's easier to get the route of the current asset
- I added memoized variables in order to select `selectedAssetIndex`, `selectedAsset` so it's easier to play with them later and with the tabs component
- Used only one function to handle the click behavior on tabs
- I did construct every tabs using `Array.map` so we only have to add an asset to the asset routes and add a selector to add a new asset easily
- No risk, behind a feature flag
- FoxPage should work as expected (mainly about tabs)

fix: refactor foxpage

---

package.json
yarn.lock

Upgrade Cypress to 9.7.0: https://docs.cypress.io/guides/references/changelog#9-7-0
N/A
Minimal.
N/A

chore: upgrade cypress to 9.7.0

---

src/assets/translations/en/main.json

fix(translations): misspelling for occurred
N/A
None
None

fix(translations): misspelling for occurred

---

src/hooks/useBalanceChartData/useBalanceChartData.ts
src/state/slices/assetsSlice/assetsSlice.ts

there's a long tail of bugs in the charts causing them not to go to zero
i've written various forms of the logic a dozen or more times temporarily to figure out what's going on, this just makes it pretty and permanent
when this happens in future we have useful error messages to help narrow it down
n/a
extremely low - logging only
open the console and go to the all timeframe with a wallet with an affected tx

chore: balance chart debugging error

---

package.json
src/assets/translations/en/main.json
src/assets/translations/es/main.json
src/assets/translations/id/main.json
src/assets/translations/ko/main.json
src/assets/translations/pt/main.json
src/assets/translations/zh/main.json
src/components/AssetHeader/AssetDescription.tsx
src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
src/hooks/useBalanceChartData/useBalanceChartData.ts
src/pages/Defi/hooks/useFoxyBalances.tsx
src/plugins/foxPage/hooks/getGovernanceData.ts
src/state/slices/assetsSlice/assetsSlice.ts
yarn.lock

d2d17b34 chore: balance chart debugging error (#1883)
98af9dfd fix: add missing translation entries for WETH parser (#1882)
2d4a4517 fix: about section collapse (#1888)
d9da0c60 feat: add a governance fetching service (#1875)
74139d93 fix(translations): misspelling for occurred (#1894)
195627fb fix: add missing minLimit translation param (#1887)
885e5901 chore: upgrade cypress to 9.7.0 (#1891)
d44bbdf3 fix: catch foxy opportunity failure (#1890)
1456c45d fix: remove feeasset from dep array (#1886)

chore: create release v1.23.1 [DO NOT MERGE]

---

src/plugins/foxPage/foxPage.tsx

This PR connects crypto and fiat data showed on fox page to app state.
Demo wallet already has FOX / FOXy.
https://github.com/shapeshift/web/issues/1829
No risk
- Connect with demo wallet
- Go to fox page
- Notice values of the demo wallet are showed in fox / foxy tabs

feat: integrate data on fox page

---

headers/csps/marketService/coingecko.ts
package.json
src/config.ts
src/state/slices/marketDataSlice/marketDataSlice.tsx
yarn.lock

adds support for coingecko pro api key and endpoint
n/a - we've been rate limited by coingecko free plan for some time since their production outage a
week or two back
market data doesn't load
click around the charts - they should load fast
no user facing changes

feat: add coingecko pro support

---

src/assets/translations/en/main.json
src/components/Trade/TradeConfirm/TradeConfirm.tsx

Add warnings for unusual trade situations based on mockups and spec provided in #1185 
closes #1185

feat(Trade): add warnings for unusual situations

---

src/pages/Defi/components/OpportunityCard.tsx
src/pages/Defi/components/OpportunityCardList.tsx

closes #1540 
You will now see the Foxy icon instead Fox in the defi page.
Go to the defi page and see if the 'FOX token staking' icon is indeed Foxy's.

chore: update the OpportunityCard component to show the icon for Foxy

---

src/assets/translations/en/main.json
src/context/WalletProvider/NativeWallet/components/NativePassword.tsx

Added warning to the wallet creation modal
Closes https://github.com/shapeshift/web/issues/1919
N/A
- Go to the home page of the web application (Log out from the dashboard if you are logged in)
- Try creating a new shapeshift wallet or a native one

feat: added warning to wallet creation modal

---

sample.env

Update the default log level in sample.env to match the one used in prod.
None.
None.

chore: sample.env log level to match prod

---

src/plugins/foxPage/components/Layout.tsx

Currently, going from fox to foxy tab causes tabs to move because of the varying description. This fixes this visual issue by setting a `minHeight` according to screen size.
Discussed with @gomesalexandre before any work.
No risk
- Go to fox page
- Click on fox / foxy tabs with various screen sizes
- Notice Tabs stay at the same height

fix: min height for title and description on fox page

---

src/components/Trade/hooks/useSwapper/useSwapper.ts
src/test/constants.ts

Adding bitcoin specific fee data requires this change to be made first.
Will merge the following pr after this one:
https://github.com/shapeshift/lib/pull/753
thor swapper
low risk type changes
type changes only. very low risk

chore: prefactor for swapper type changes

---

src/components/Modals/Send/Send.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/state/slices/portfolioSlice/utils.ts

Remove all instances of control flow based on `NetworkType`.
Contributes to https://github.com/shapeshift/web/issues/1570
Minimal, refactor-only.
Ensure no chain-related regressions.
N/A

chore: remove `NetworkType` control flow

---

package.json
src/components/Approval/Approval.tsx
yarn.lock

Accidentally introduced a type error during recent swapper refactor.
This fixes it -- approvals are always eth so this casting should be ok
bug fix thorswapper
low risk. fix type error
Should be no risk as this is only a type change

fix: type error on approvals

---

package.json
patches/friendly-challenge+0.9.2.patch
yarn.lock

chore: update friendly-challenge from 0.9.1 to 0.9.2
N/A
Low. It's a minor upgrade but it does affect the wallet migration flow.
Test migrating a wallet from a ShapeShift account

chore: update friendly-challenge from 0.9.1 to 0.9.2

---

src/plugins/cosmos/components/modals/Staking/views/ClaimBroadcast.tsx

Fixes an incorrect translation path on the atom claim broadcast step.
Minimial to zero risk.
When claiming a reward with staked atom, the button should read "Claiming Rewards", not " defi.modals.staking.claimingRewards"

fix: fixed translation path on atom claim button text

---

package.json
yarn.lock

refactor(package.json): move dependencies next to devDependencies
It was really confusing having `dependencies` and `devDependencies` so far away from each other in `package.json`
* remove the `babel-loader` forced version resolution
* force hdwallet-core to resolve to 1.23.0 to resolve an issue with tendermint-tx-builder deps
N/A
None to users. This is only for development.
None

refactor(package.json): move dependencies next to devDependencies

---

src/components/Trade/hooks/useSwapper/useSwapper.ts
src/test/constants.ts

Rename zrxtrade to ethtrade and remove type hacks
low risk
low risk. make sure swapping still works as expected

chore: rename zrxtrade to ethtrade

---

package.json
patches/friendly-challenge+0.9.1.patch
yarn.lock

This reverts 09642953f6363266af21c802dbaa2d430c277b8f breaking release branch
N/A
None, this reverts the broken commit
- Wallet migration should be working

fix: revert "chore: update friendly-challenge to 0.9.2"

---

sample.env
src/config.ts
src/context/WalletProvider/SelectModal.tsx
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

removes dead feature flags for stable features
n/a
ensure keplr and tallyho can be used
ensure keplr and tallyho can be used
nothing user facing

chore: remove keplr and tallyho flags

---

src/plugins/foxPage/hooks/getGovernanceData.ts

c05fef9bbb68be96f9b9fe289de485e344916307 fix: zero out empty boardroom results

chore: create release v1.31.1 [DO NOT MERGE]

---

src/plugins/foxPage/components/MainOpportunity.tsx

- The get started button alignment was wrong because it hasn't been changed while adding skeletons while wiring it up!
No issue
No risk
Go on the Fox Page, see if the `Get Started` button on `MainOpportunity` is correctly horizontally aligned

fix: get started button alignment on foxPage

---

package.json
src/components/Trade/hooks/useSwapper/useSwapper.ts
yarn.lock

We dont need to pass in this type. Must be merged after this lib pr is published:
https://github.com/shapeshift/lib/pull/825

fix: remove unnecessary type passing

---

package.json
src/components/Trade/hooks/useSwapper/useSwapper.ts
yarn.lock

We had to modify the buildTrade and getQuote inputs to be a discriminated union on chainId -- Bitcoin will need some extra fields to be passed in for thorchain trading
based on this pr:
https://github.com/shapeshift/lib/pull/829
thorchain swapper
low risk. make sure trades still work
make sure trades still work

chore: update swapper trade quote input

---

package.json
yarn.lock

Minor version bump for Cypress: https://docs.cypress.io/guides/references/changelog#10-1-0
Minimal.
Cypress should still pass CI.
N/A

chore: bump Cypress to 10.1.0

---

src/plugins/foxPage/hooks/useOtherOpportunities.ts

Fixed incorrect links on the FOX opportunity page.
1. Renamed ETH-FOX V2 to ETH-FOX UNI V2 and linked it to the Fox Farm page so KeepKey users could add/manage their liquidity.
2. Renamed ETH-FOX V3 to ETH-FOX UNI V2 Farm and linked it to the Fox Farm page so users could stake (previously it was linking to Uniswap v3)
3. Replaced the link to Tokemak for Borrowing and Lending with a link to the Fox and Frens Rari Pool
We should add the ElasticSwap farm for FOXy too, right?

fix: updating FOX opportunity URLs

---

package.json
yarn.lock

FOXy icon was updated in the asset service but not bumped in web
n/a - found in release testing
minimal
FOXy icon should work

chore: bump asset-service for new FOXy icon

---

src/context/WalletProvider/SelectModal.tsx

00a0da63 feat: turn the wallet select into a grid (#2074)

chore: create release v1.35.0 [DO NOT MERGE]

---

package.json
src/assets/translations/en/main.json
src/assets/translations/ko/main.json
src/components/AssetHeader/AssetDescription.tsx
src/components/Modals/Send/views/QrCodeScanner.tsx
src/components/StakingVaults/AssetTeaser.tsx
src/pages/Defi/views/StakingVaults.tsx
src/plugins/foxPage/foxPage.tsx
src/state/slices/assetsSlice/assetsSlice.ts
yarn.lock

64af9ff7 chore: bump cypress to 10.3.0 (#2109)
f9839cb3 feat: localized asset descriptions (#2098)
0bdd8d1a fix: clickHereToEarn translation fix (#2100)
9263ae97 Merge branch 'main' into develop
e2a563c1 fix: qr code not filling address input (#2017)

chore: create release v1.36.2 [DO NOT MERGE]

---

yarn.lock

update yarn.lock
N/A
None
None

refactor: update yarn.lock

---

src/assets/translations/en/main.json
src/plugins/foxPage/foxPage.tsx

This makes the custom FOX description on the Fox Page translatable.
- closes https://github.com/shapeshift/web/issues/2052
None
- FOX description shows no regression in Fox Page Header

chore: make FOX custom description translatable

---

package.json
yarn.lock

Bumps lib to remove test bitcoin from the asset list.
closes #2080 
Minimal risk.
To test, your global state must be reset first. One can do that by changing a feature flag and applying it.
Once your global state has been reset, there should only be one Bitcoin asset with the symbol BTC when searching for Bitcoin.
Before fix:
After fix:

fix: remove bitcoin testnet

---

src/components/Trade/hooks/useSwapper/useSwapper.test.tsx
src/components/Trade/hooks/useSwapper/useSwapper.ts
src/context/PluginProvider/PluginProvider.tsx

**hooks are not singletons**
* move the instantiation of the swapper manager to a singleton and setup the swappers there
* also addresses bug where we were incorrectly setting up avalanche zrx swapper as an eth mainnet swapper
* flags adding avalanche zrx swapper behind existing avalanche flag
Closes https://github.com/shapeshift/web/issues/2123
swapper regressions
have a play setting up trades and watch the console for errors
unlikely needed to actually execute trades
n/a

fix: don't add swapper multiple times

---

package.json
yarn.lock

This bumps `@shapeshiftoss/unchained-client` to latest and fixes a bug where develop crashes if latest `main` `@shapeshiftoss/chain-adapters` is linked. This happens during loading because of undefined provider in the Tx Parser.
Also bumps `@shapeshiftoss/chain-adapters` to latest, since it's the one where the bug currently happens.
Included releases:
- [`@shapeshiftoss/unchained-client-v9.0.3`](https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss%2Funchained-client-v9.0.3)
- [`@shapeshiftoss/unchained-client-v9.1.0`](https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss%2Funchained-client-v9.1.0)
- [`@shapeshiftoss/unchained-client-v9.1.1`](https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss%2Funchained-client-v9.1.1) (the actual fix)
- …

fix: make web great again

---

package.json
yarn.lock

475f61fc4 fix: bump chain-adapters version to fix KK showOnDevice issue (#2169)

chore: create release v1.41.1 [DO NOT MERGE]

---

src/components/Trade/hooks/useSwapper/useSwapper.ts

this probably only affected dev - but it accountSpecifiers was length 0 we were trying to get a
receive address and throwing. this just changes the check from existence to length
n/a - found locally
swapper changes - should be fixing a bug and not causing a regression
poke around swapper - no need to do a trade

fix: don't get quote unless accountSpecifiers is actually populated

---

package.json
src/assets/translations/en/main.json
src/components/Modals/FiatRamps/config.ts
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Modals/Send/views/Details.tsx
src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useSwapper/useSwapper.test.tsx
src/components/Trade/hooks/useSwapper/useSwapper.ts
src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
src/hooks/useErrorToast/useErrorToast.ts
src/plugins/cosmos/components/modals/Send/views/Details.tsx
yarn.lock

443d62f5a feat(swapper): add toast for invalid trading types (#2171)
952632a45 fix: don't get quote unless accountSpecifiers is actually populated (#2173)
ce07944d0 fix: send eth modal gas error (#1835)
d74fc8824 feat(banxa): support USDC and USDT sell orders (#2172)
dd4da561a Merge branch 'main' into develop
994ce361f feat: get quote for btc trades (#2153)

chore: create release v1.42.0 [DO NOT MERGE]

---

src/assets/translations/en/main.json
src/plugins/pendo/components/OptInModal/OptInModalBody.tsx

Make T lowercase in the defi modal "No thanks..."

fix: lowercase t

---

src/components/Modals/FiatRamps/views/Overview.tsx
src/plugins/pendo/components/OptInModal/OptInModalBody.tsx

c2c574f3 fix: onramp undefined assetId (#2191)
518d1eb2 Update OptInModalBody.tsx (#2190)

chore: create release v1.43.1 [DO NOT MERGE]

---

src/plugins/pendo/index.tsx
src/plugins/pendo/sanitizeUrl.ts

safari doesn't support lookbehind in regex, the app currently doesn't load.
this replaces the regex with one provided by @MrNerdHair with an alternative implementation with the
same effect
n/a - noticed by @reallybeard
pendo URL sanitation doesn't work
the app should load on mobile
n/a

fix: fix app for safari

---

src/plugins/pendo/index.tsx
src/plugins/pendo/sanitizeUrl.ts

241dfa71e fix: fix app for safari (#2203)

chore: create release v1.45.1 [DO NOT MERGE]

---

src/config.ts

chore: memoize getConfig()
This avoids showing a config errors repeatedly in the console by only parsing the config once
N/A
Almost none

chore: memoize getConfig()

---

src/components/Layout/Header/NavBar/FiatRamps.tsx
src/components/Modals/FiatRamps/views/RampsList.tsx

- Add data-test tags so we can track fiat ramp clicks
no risk
n/a

fix: add data test labels for fiat ramps

---

package.json
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimConfirm.tsx
yarn.lock

I used the method `canClaimWithdraw` from `foxy-investor` to enable or disable the withdraw button
⚠️ This pr depends on https://github.com/shapeshift/lib/pull/903/files
partially fix #2103 
No real risk, maybe not being able to claim while you could?
Pretty hard to test, I still added a monkey patch in order to visit the withdraw button on a not-yet ready Foxy withdraw

fix: disable Foxy confirm claim button if user cant claim yet

---

src/constants/PublicWalletXpubs.ts

fixes demo wallet with dogecoin feature enabled

feat: add dgubs to demo wallet for the doge

---

src/state/slices/portfolioSlice/selectors.ts
src/state/slices/portfolioSlice/utils.ts

* we shouldn't show the token list for accounts without tokens
* we should show the avalanche `0x` address on the accounts page
n/a - noticed by ops testing
minimal - essentially zero
go to the avalanche account page and see screenshots below
before
after

fix: show address and hide tokens for avalanche

---

package.json
src/components/Trade/hooks/useSwapper/useSwapper.ts
yarn.lock

use latest swapper
low
make sure swaps still work. unlikely anything breaks

chore: use latest swapper

---

src/components/Approval/Approval.tsx
src/components/Trade/TradeConfirm/TradeConfirm.tsx
src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useSwapper/calculateAmounts.test.ts
src/components/Trade/hooks/useSwapper/calculateAmounts.ts
src/components/Trade/hooks/useSwapper/useSwapper.test.tsx
src/components/Trade/hooks/useSwapper/useSwapper.ts
src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx
src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
src/state/slices/marketDataSlice/selectors.ts

closes #1995
It's related to the trade-card, so there's a risk.
Enable `Multicurrencies` feature flag, open up the settings modal, and change the currency to something other than USD,
Test trading.

feat: multicurrency trade support

---

package.json
yarn.lock

bumps market service with fix
closes #2199
chart regressions
* set your system clock to a timezone with a positive timezone offset, e.g. sydney AEST
* look at any balance chart on a timeframe of 1 month or less
* charts should not go to zero on the right hand side
n/a - you know what a working chart looks like

fix: fix charts for users in positive timezone offset

---

sample.env
src/config.ts
src/plugins/dogecoin/index.tsx
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

this is stable and can be removed
closes #2250
the doge don't work
doge should still be functional
no user facing changes, flag gone from menu.

chore: remove doge feature flag

---

sample.env
src/config.ts
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

FOX LP and Farming feature flags
closes #2269

feat: fox lp and farming feature flags

---

.eslintrc

This enforces eqeqeq rule, emitting an error vs. a warning currently.
N/A
N/A
- Replace a strict equality operator (===) with a loose equality
operator (==)
- Run `yarn lint`
- stderr is happy

chore: enforce eqeqeq rule

---

src/components/Modals/FiatRamps/FiatRamps.tsx
src/components/Modals/FiatRamps/views/AssetSelect.tsx

I added a back button to the fiat ramp modal. This is connected to [this issue](https://github.com/shapeshift/web/issues/2273).
closes #2273 
Small, ui changes to only the fiat ramp modal
- Open the buy/sell crypto button on the dashboard
- Click on any of the ramps
- click the back button at the top left

feat: fiat ramp back button

---

src/assets/translations/en/main.json
src/assets/translations/es/main.json
src/assets/translations/fr/main.json
src/assets/translations/ko/main.json
src/assets/translations/pt/main.json
src/plugins/foxPage/components/AssetActions.tsx

this was removed when we removed the coinbase feature - this brings it back
closes #2299
button doesn't work
* button should only appear for FOX asset, not FOXy
* button should open new tab to https://www.coinbase.com/price/fox-token
before
after

feat: buy fox on coinbase button

---

src/components/AccountAssets/AccountAssets.tsx

This fixes the `<AccountAssets />` component currently early returning if not within the context of an Ethereum chainReference. As a result, other EVM chains will not show the Account Tokens section as they should.
N/A
Release:
This diff:

fix: show account tokens for all EVM chains

---

src/assets/translations/en/main.json
src/assets/translations/es/main.json
src/assets/translations/fr/main.json
src/assets/translations/id/main.json
src/assets/translations/ko/main.json
src/assets/translations/pt/main.json
src/assets/translations/zh/main.json

This updates the translations and removes the now unused old staking ones.
- We will need to make sure translations are provided for all languages.
- None in this PR, compare with part1 to make sure translations are referenced properly.

feat: cosmos defi UI part 2: update translations

---

src/AppProviders.tsx
src/assets/translations/en/main.json
src/context/AppProvider/AppContext.tsx
src/hooks/useBalanceChartData/useBalanceChartData.ts
src/state/slices/marketDataSlice/marketDataSlice.tsx
src/state/slices/marketDataSlice/selectors.ts

the upstream data provider for multi currency data can be flaky. this adds error handling and
switches the currency back to USD, which we can handle gracefully, and notifies the user with a
toast they must dismiss.
n/a - noticed by ops
may cause multicurrency regressions
this is hard to test for non developers. for developers make the fiat fetching apis in
`marketDataSlice` throw to trigger. see the video below for mocked behavior.
https://user-images.githubusercontent.com/88504456/182674593-c640aa1e-4cd6-4146-9e39-7f991e595116.mov

fix: gracefully handle multi currency failures

---

src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimConfirm.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimStatus.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Deposit/CosmosDeposit.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Confirm.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/CosmosWithdraw.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimConfirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimStatus.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Withdraw.tsx

This updates the console.error calls to be `moduleLogger.error` calls in the DeFi providers.
N/A - housekeeping
None.
- Errors should be properly logged with structured logger

feat(defi providers): console.error -> moduleLogger.error

---

src/constants/PublicWalletXpubs.ts

demo wallet works with BCH and LTC
closes #2330
demo wallet breaks
demo wallet should show BCH and LTC accounts

fix: demo wallet xpubs for LTC and BCH

---

src/assets/translations/en/main.json
src/assets/translations/id/main.json
src/assets/translations/ru/main.json
src/components/Approval/Approval.tsx
src/components/DeFi/components/Steps.tsx
src/features/defi/components/Approve/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx

I still added the contract name inside a link to the explorer.
There are 2 approvals components, `Approval.tsx` is linked to the swap feature, this one is afaik only linked to ERC20, meaning that we can use etherscan
The other one (`Approve.tsx`) is linked to DeFi features, which will be linked to Cosmos soon and other blockchain we will be supporting some staking contracts
closes #2268
- Try to swap a token, like FOX => ETH for example, when you see the approval window, you'll see the swapper name + a link to the explorer 
- Try to stake some Fox to the Foxy contract, you'll see the approval modal with the same thing

feat: add explorer's link and contract name when approving

---

src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx

Unrugs develop
N/A
Develop might get unrugged
- CI passes

fix: unrug develop

---

src/components/AuroraBackground.tsx

disables aurora splash screen animation for firefox
closes #2338
aurora doesn't render on other browsers
* aurora shouldn't show on firefox
* aurora should show on all other browsers
splash screen on firefox after this PR

fix: disable splash animation for firefox

---

src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts

When passphraseProtection is on and user close the passphrase request modal, there was a `Keepkey successfully wiped` message, which was wrong because we just want to redirect to the wallet select modal
For this, when we receive the failure event, I'm just checking if the `passphraseProtection` is on, meaning that the keepkey has been initialized already, so it's a passphrase request cancel.
See https://github.com/shapeshift/web/issues/1607#issuecomment-1207751928 for further informations
closes #1607
Keepkey events handling
See video
https://www.awesomescreenshot.com/video/10393851?key=0825aa58e97a1eff46578dcaaab572f3

fix: handle keepkey waiting for passphrase cancelled event

---

package.json
src/assets/translations/en/main.json
src/components/Trade/TradeConfirm/TradeConfirm.tsx
src/components/Trade/types.ts
yarn.lock

This adds a protocol fee row to display CowSwap fees - and later on Thorchain fees. 
Note: Copy has been confirmed by product, as well as not adding the sell asset symbol for now, but rather in a follow-up PR, in the "Miner Fee" row as well for consistency.
- closes https://github.com/shapeshift/web/issues/2271
None, no changes to current logic, only a new row added to `<TradeConfirm />` 
- Input an amount/pair to be swapped with CowSwap e.g USDC -> FOX
- Confirm step should show the estimated fees in sell token for that trade

feat(trade): cowswap trade confirm protocol fees

---

package.json
yarn.lock

Uses CowSwap-provided AppData to identify ShapeShift cow swaps
See matching lib PR https://github.com/shapeshift/lib/pull/956
closes https://github.com/shapeshift/web/issues/2364
None - tested CowSwapper still works both at quotes and execution steps
- Make a moo swap
- Go to CowSwap explorer and click on that trade
- AppData should be `0x68a7b5781dfe48bd5d7aeb11261c17517f5c587da682e4fade9b6a00a59b8970`

feat(trade): use CowSwap-provided AppData

---

package.json
src/assets/translations/en/main.json
src/constants/Config.ts
src/context/AppProvider/AppContext.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyVersions.ts
src/context/WalletProvider/KeepKeyProvider.tsx
yarn.lock

KK 7.4.0 is required for LTC support
closes #2374
we erroneously skip LTC for a working firmware version
**dear ops - plz coordinate amongst yourselves and do NOT update all your KK firmware at once**
plz test with LTC flag **on**
* half of ops update to latest firmware and check LTC works
* half of ops stay on current firmware and ensure that KK works with all other chains with LTC flag
on, LTC should not show in accounts
wip

fix: keepkey firmware version check for LTC

---

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts

fixing bugs discovered in [this thread](https://discord.com/channels/554694662431178782/1007234455531962378/1007234458874822708)

fix: fox eth lp bugs

---

src/assets/translations/en/main.json
src/components/AssetHeader/AssetMarketData.tsx

Market Data was not a translated string
partially #2253 
No risk
Go to an asset page, see if the title `Market Data` is translated on the bottom right

fix: translate Market Data on asset page

---

src/assets/translations/en/main.json
src/components/Modals/FiatRamps/config.ts
src/components/Modals/FiatRamps/views/RampsList.tsx

closes #2350 
none
open up buy/sell modal
there should be a label under Juno saying "US-Only"

feat: tags for fiatramps, us-only tag for JunoPay

---

src/components/Layout/Header/SideNavContent.tsx

unique link to track new users via discord link in app
n/a
zero
link should go to shapeshift discord
no user facing changes

chore: unique discord tracking link

---

src/assets/translations/en/main.json
src/components/AccountAssets/AccountAssetsList.tsx
src/components/AssetAccounts/AssetAccountRow.tsx
src/components/DeFi/components/MaxButtonGroup.tsx
src/components/DeFi/components/StepRow.tsx
src/components/Layout/Header/SideNavContent.tsx
src/components/Modals/FiatRamps/FiatRamps.tsx
src/components/Modals/FiatRamps/views/Manager.tsx
src/components/Modals/FiatRamps/views/RampsList.tsx
src/components/ReactTable/ReactTable.tsx
src/components/StakingVaults/StakingTable.tsx
src/components/Table/Table.theme.ts
src/components/Tag/Tag.theme.ts
src/features/defi/components/DefiActionButtons.tsx
src/features/defi/components/DefiModal/DefiModal.tsx
src/features/defi/components/EmptyOverview/EmptyOverview.tsx
src/features/defi/providers/cosmos/components/CosmosManager/LearnMore/CosmosLearnMore.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosEmpty.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/Claim.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimRoutes.tsx

- Small updates and fixes to improve the mobile experience.
low risk, mostly changed styling
Make sure everything works as normal

fix: mobile ui improvements

---

src/hooks/useHasAppUpdated/useHasAppUpdated.test.ts
src/hooks/useHasAppUpdated/useHasAppUpdated.ts

fix: use has app updated bug

---

package.json
src/assets/translations/en/main.json
src/components/AccountAssets/AccountAssetsList.tsx
src/components/AssetAccounts/AssetAccountRow.tsx
src/components/DeFi/components/MaxButtonGroup.tsx
src/components/DeFi/components/StepRow.tsx
src/components/Layout/Header/SideNavContent.tsx
src/components/Modals/FiatRamps/FiatRamps.tsx
src/components/Modals/FiatRamps/views/Manager.tsx
src/components/Modals/FiatRamps/views/RampsList.tsx
src/components/ReactTable/ReactTable.tsx
src/components/StakingVaults/Cells.tsx
src/components/StakingVaults/StakingTable.tsx
src/components/Table/Table.theme.ts
src/components/Tag/Tag.theme.ts
src/features/defi/components/DefiActionButtons.tsx
src/features/defi/components/DefiModal/DefiModal.tsx
src/features/defi/components/EmptyOverview/EmptyOverview.tsx
src/features/defi/providers/cosmos/components/CosmosManager/LearnMore/CosmosLearnMore.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosEmpty.tsx
src/features/defi/providers/fox-eth-lp/constants.ts
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/Claim.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimRoutes.tsx
src/hooks/useHasAppUpdated/useHasAppUpdated.test.ts
src/hooks/useHasAppUpdated/useHasAppUpdated.ts
src/pages/Defi/views/StakingVaults.tsx
yarn.lock

74ebafc10 fix: use has app updated bug (#2456)
77cae327b fix: mobile ui improvements (#2455)
39809cb86 chore: match eth/fox pool naming (#2459)
fcfe6671d feat: fox farm internal earn CTA (#2458)

chore: create release v1.58.1 [DO NOT MERGE]

---

src/assets/translations/constants.ts
src/assets/translations/index.ts

adds boilerplate for german (de) language support
closes #2442
translations might break
* german should appear as a language option
* missing translations are a responsibility of globalization, not engineering

feat: german language support

---

src/components/Layout/Header/Header.tsx
src/components/Layout/Header/SideNav.tsx
src/components/Layout/Layout.tsx
src/theme/theme.tsx

Reduce the overall width of the layout
n/a
no risk
n/a

fix: add max width

---

src/components/Layout/Header/NavBar/MainNavLink.tsx
src/components/Layout/Header/NavBar/NavBar.tsx
src/components/Layout/Header/SideNavContent.tsx
src/components/TransactionHistoryRows/components/ApproveIcon.tsx

- fix the alignment of the secondary buttons on the nav
- add a divider for the compact view
- add the group labels back for mobile view
- fix approve checkmark size
n/a
n/a 
n/a

fix: nav issues

---

src/state/apis/const.ts
src/state/apis/foxy/foxyBalancesApi.ts
src/state/slices/assetsSlice/assetsSlice.ts
src/state/slices/marketDataSlice/marketDataSlice.tsx
src/state/slices/portfolioSlice/portfolioSlice.ts
src/state/slices/txHistorySlice/txHistorySlice.ts
src/state/slices/validatorDataSlice/validatorDataSlice.ts

This creates, exposes and consumes a base RTK `createApi` config.
N/A
None, same as before but abstracted away.
CI is happy

feat: base RTK createApi config

---

.env.private

i missed this in the previous PR - we don't have a prod cluster for osmo yet
n/a
should be negative
* infrastructure for existing values doesn't exist
* osmo is flagged off
`yarn env private && yarn build && serve -s build -l 4000` and check osmo works on `localhost:4000`
with flag on
n/a

chore: align app and private env vars for osmo unchained

---

package.json
scripts/release.ts
scripts/utils.ts
scripts/writeBuildMetadata.ts
src/pages/Flags/Debugging.tsx
src/pages/Flags/Flags.tsx

this adds two new features to the feature flags page
* the git short commit hash of the current build
* the latest production tag of the repo
this is intended for @shapeshift/operations to use to verify that
* they are testing the most recent version of the `release` branch
* that a release has successfully deployed to production
n/a - quality of life
* the build fails to succeed (engineering won't merge this PR)
* this shows incorrect/misleading information
* this will not work locally with the dev server - the static files aren't available nor relevant via webpack
* you can test a locally served build via `yarn build && serve -s build -l 4000` if you comment out the `isLocalhost` check
* add `./metadata.json` to the ephemeral environment url path to review the served file, or see it …

feat: show commit hash of current build in flags menu

---

src/components/Modals/Receive/ReceiveInfo.tsx
src/state/slices/portfolioSlice/selectors.ts

* use the accountNumber from the bip44params in the store when deriving a receive address
n/a - next incremental step of removing hardcoded account number
* we generate the wrong receive address
* ensure that the receive address generated matches against production
* ensure that the receive address generated matches against production
* no user facing change in this PR

feat: receive address account number

---

src/components/Layout/Header/NavBar/ChainMenu.tsx
src/hooks/useEvm/useEvm.ts

Also adds a loading state to avoid flash of "Unsupported Network" `<ChainMenu />` while we are getting the wallet network state (without a loader state, it could be added but trading a flash of "Unsupported network" for a flash of spinner probably doesn't make sense, we're talking ms here)
closes https://github.com/shapeshift/web/issues/2581
None, tested both the unsupported network flow as well as the current flow with supported networks and noticed no regressions.
- Switching EVM chains still work
- Loading the app on an unsupported chain displays "Unsupported Network" instead of Ethereum/Avalanche with the option to switch
- Switching from unsupported to any supported network **through the app** displays the network name
- Switching from networks through the wallet doesn't update the …

feat(chainMenu): unsupported network

---

src/context/FoxEthProvider/FoxEthProvider.tsx

Uses the new FOX icon in the FOX/ETH that we consistently use across the app following the override in https://github.com/shapeshift/lib/pull/985
N/A
- The FOX icon in the FOX Page is consistent with the one used across the app
- Same as engineering
Develop:
This branch:

feat(foxEth): new fox icon

---

src/plugins/foxPage/hooks/useOtherOpportunities.ts

Uses the new FOX icon that we consistently use across the app following the override in https://github.com/shapeshift/lib/pull/985
N/A
None
- The FOX icon in the FOX Page is consistent with the one used across the app
- Same as engineering
This branch:
Develop:

feat(foxPage): new fox icon

---

src/assets/translations/en/main.json
src/components/AccountDropdown/AccountChildOption.tsx
src/components/AccountDropdown/AccountDropdown.tsx
src/pages/Accounts/V2/Accounts.tsx
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/portfolioSlice/utils.test.ts
src/state/slices/portfolioSlice/utils.ts

fancy pants account selector component
todo
closes #2598
* none till we consume this component
* returning the wrong `AccountId` would be **bad**
* this components API is designed such that a consumer passes an `AssetId` and gets back an `AccountId` via the `onChange` callback
* turn on the multi account flag, set your `.env` log level and browser console to trace logging, and navigate to the accounts page
* see that there is a single log event emitted by the `onChange` callback for each chain supported by the connected wallet on the `/accounts` route load. testing with native wallet is preferred for obvious reasons.
* note that only BTC and LTC are rendered - these are the only chains that require user facing account selectors with the flag off before we ship multi account.
* switch the …

feat: account selector

---

src/components/AccountDropdown/AccountDropdown.tsx

small logic fix - we want this dropdown to display with the multi account flag off for BTC and LTC
only 
n/a - noticed during local development using this component
negative - this component
* currently isn't consumed anywhere, and
* isn't functioning correctly
* force the [accounts page](https://github.com/shapeshift/web/blob/develop/src/pages/Accounts/Accounts.tsx#L6) to always return the `AccountsV2` component
* connect native wallet
* with the multi account flag off - BTC and LTC dropdowns should be rendered (we need this for
backwards compatibility)
* with the multi account flag on - all supported chains by the wallet should be rendered
* nothing operations-facing that can be tested

fix: show account selection dropdown for BTC and LTC with multi account flag off

---

docs/file-structure.md
docs/state-management.md
docs/testing.md

Correct spelling mistakes in the documents.

chore: fix typos (docs)

---

patches/PATCHES.md
patches/react-dom+18.2.0.patch
src/Routes/Routes.tsx
src/components/Modals/Receive/ReceiveInfo.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/context/WalletProvider/KeyManager.ts
src/context/WalletProvider/MobileWallet/RevocableWallet.ts
src/context/WalletProvider/MobileWallet/components/Captcha.tsx
src/context/WalletProvider/MobileWallet/components/MobileCreate.tsx
src/context/WalletProvider/MobileWallet/components/MobileImport.tsx
src/context/WalletProvider/MobileWallet/components/MobileLoad.tsx
src/context/WalletProvider/MobileWallet/components/MobileRename.tsx
src/context/WalletProvider/MobileWallet/components/MobileStart.tsx
src/context/WalletProvider/MobileWallet/components/MobileSuccess.tsx
src/context/WalletProvider/MobileWallet/components/MobileTestPhrase.tsx
src/context/WalletProvider/MobileWallet/config.ts
src/context/WalletProvider/MobileWallet/mobileMessageHandlers.ts
src/context/WalletProvider/MobileWallet/types.ts
src/context/WalletProvider/SelectModal.tsx
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/WalletViewsSwitch.tsx
src/context/WalletProvider/actions.ts
src/context/WalletProvider/config.ts
src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts
src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
src/lib/globals.ts
src/state/slices/portfolioSlice/portfolioSlice.ts
src/state/slices/portfolioSlice/selectors.ts

feat: add new wallet pairing flow for the mobile app (#2655)
feat(fox lp/farming): remove hardcoded accountNumber bip44Param (#2644)

chore: release v1.75.0 [DO NOT MERGE]

---

.eslintrc
.git-blame-ignore-revs
src/Routes/RoutesCommon.tsx
src/components/StakingVaults/Cells.tsx
src/context/WalletProvider/KeepKey/helpers.ts
src/features/defi/components/Approve/PairIcons.tsx
src/features/defi/components/PairIcons/PairIcons.tsx
src/features/defi/components/TxStatus/PairIcons.tsx
src/features/defi/helpers/normalizeOpportunity.tsx
src/hooks/useBalanceChartData/useBalanceChartData.test.ts
src/hooks/useBalanceChartData/useBalanceChartData.ts
src/hooks/useRefCallback/useRefCallback.ts
src/plugins/foxPage/hooks/getGovernanceData.ts
src/plugins/pendo/agent/types.ts
src/plugins/types.ts
src/state/slices/txHistorySlice/txHistorySlice.ts
src/state/store.ts

Adds `array-type` lint rule for codebase consistency.
https://typescript-eslint.io/rules/array-type/
N/A - standardising codebase consistency for reviewers to improve bounty hunter velocity.
Almost none.
CI should pass. If so we should be gravy ⛵ 
See the generic testing note above.
See the generic testing note above.
N/A

chore: add `array-type` lint rule

---

.git-blame-ignore-revs

chore: add git blame ignore for #2685
N/A
N/A
N/A

chore: add git blame ignore for #2685

---

src/context/AppProvider/AppContext.tsx
src/lib/account/account.ts
src/lib/account/cosmosSdk.ts
src/lib/account/evm.ts
src/lib/account/utxo.ts

abstracts accountId and metadata derivation to reusable functions/files for maintainability, and such that we can reuse this logic to add additional accounts with `accountNumber > 0`
n/a - required for multi accounts
* using the redux dev tools compared to production - ensure the `accountSpecifiers` slice and `accountMetadata` match up for the accounts
* nothing user-facing that is testable by operations

refactor: derive account ids and metadata abstraction

---

src/context/AppProvider/AppContext.tsx

this was a relic/just wrong - we don't need to block chain specific (FOXy or validator) data loading based on tx history status
n/a
* there may have been some reason this blocked previously, but i can't see or think of any reason why
* see that FOXy and validator requests don't block on accounts successfully loading
* no user facing changes for ops to test - should be slightly faster to load the dashboard

fix: faster dashboard load

---

.eslintrc
src/components/Graph/MaxPrice.tsx
src/components/Graph/MinPrice.tsx
src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx
src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx
src/components/Modals/FiatRamps/FiatRamps.tsx
src/components/Modals/FiatRamps/views/Overview.tsx
src/context/WalletProvider/Keplr/components/Connect.tsx
src/context/WalletProvider/MetaMask/components/Connect.tsx
src/context/WalletProvider/Portis/components/Connect.tsx
src/context/WalletProvider/TallyHo/components/Connect.tsx
src/context/WalletProvider/WalletConnect/components/Connect.tsx
src/context/WalletProvider/XDEFI/components/Connect.tsx
src/context/WalletProvider/components/ConnectModal.tsx
src/pages/Flags/Debugging.tsx

This adds the [`react/jsx-handler-names`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md) eslint rule and (not auto) fixes all lint violations after adding it. 
Uses the default conservative options, as we get around ~300 lint violations if using `checkLocalVariables` and `checkInlineFunction`:
```
...
"react/jsx-handler-names": [<enabled>, {
"eventHandlerPrefix": <eventHandlerPrefix>,
"eventHandlerPropPrefix": <eventHandlerPropPrefix>,
"checkLocalVariables": <boolean>,
"checkInlineFunction": <boolean>
}]
```
N/A
None
- If CI is happy, we are 🛍️ 
- See top-level notes
- Nothing to see here

feat: add react/jsx-handler-names eslint rule

---

src/context/WalletProvider/KeepKey/components/Label.tsx
src/context/WalletProvider/KeepKey/components/Pin.tsx

Applied changes to the pin entry modal for keepkey to improve ux as described in the A/C [here](https://github.com/shapeshift/web/issues/1613#issue-1218137363)
closes #1613 
Lower risk as this changes add UI related improvements and bug fixes that don't affect core state management.
Testing can be done with a keepkey wallet with a pin that has been previously set, however to test the Acceptance criteria 3 & 4 -> [here](https://github.com/shapeshift/web/issues/1613#issue-1218137363), you would need to also reset the pin in order to test the A/C 3 & 4.
Edit: this PR no longer addresses issue in A/C 3, please refer to [this comment](https://github.com/shapeshift/web/pull/2689/files#r967681760), issue will be fixed in another PR.
1. Disconnect existing connected wallet and plug-in keepkey …

feat(pin): improve pin modal with keyboard entry

---

src/components/AccountDropdown/AccountDropdown.tsx
src/components/Modals/FiatRamps/views/Manager.tsx
src/components/Modals/FiatRamps/views/Overview.tsx
src/context/FoxEthProvider/FoxEthProvider.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/FoxyManager.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/Claim.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimConfirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimRoutes.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/yearn/components/YearnManager/YearnManager.tsx
src/hooks/useRefCallback/useRefCallback.ts
src/types/common.ts

Convenience end-of-stack PR that moves the existing `Nullable<T>` type away from `useRefCallback` into `types/common`, and consumes it across the multi-account featureset as a convenience type.
N/A
None, this is only a type system change, if tsc is happy, we are happy 
- `yarn type-check` is happy
- None, no runtime change

feat: export and use Nullable<T> type in multi-account featureset

---

src/components/Alert/Alert.theme.ts
src/pages/Accounts/AddAccountModal.tsx

uses Chakra's `Alert` component over my ugly hand rolled attempt
closes #2708
minimal - visual only
* check this looks nice in dark and light mode, see testing steps in https://github.com/shapeshift/web/pull/2702

fix: use chakra component in add account modal

---

src/plugins/cosmos/components/modals/Staking/StakingCommon.ts

fix logic to compare chainId strings
closes #
None
Staking view should show for cosmos and osmosis
see above
see above

fix: correct supports staking logic

---

.env.base
src/config.ts
src/context/AppProvider/AppContext.tsx

This temporarily excludes all Ethereum data from our app while the merge infra update is in progress.
Does so by excluding ethereumChainId accountSpecifiers, which consequently never fetches the data for it since they're never loaded as accountSpecifiers in the first place.
N/A
Only disables ethereum accountSpecifiers, though this might break other things related to ethereum as a result.
FOX Page will not load at all which is expected.
DeFi opportunities will be borked since they use Ethereum data, but they are still visible read-only
- Avalanche and UTXO data properly loads and the app is working as expected, without Ethereum data.

feat: temporarily excludes ethereum data

---

package.json
yarn.lock

This bumps `@shapeshiftoss/swapper` to latest following https://github.com/shapeshift/lib/pull/1019, supporting CoW swaps signing for KeepKey.
closes #2392
- Ensure CoW swaps are working with KeepKey
- Refer to top-level testing steps
- Refer to top-level testing steps

feat: bump swapper to support KK CoW swaps

---

.env.base

See #2775 - updates .base env which will update the production infura url to a new key. 
infura rate limiting
low - prod already broken. 
tested simliar changes in #2775

fix: updates .base infura url for prod

---

.github/workflows/bootstrap.yml

This will make CI pass until we get caching back - reinstalls yarn modules with `yarn --frozen-lockfile`
- This could produce too many cache entries and rug us, consider this temporary.
`gh api repos/shapeshift/web/actions/caches` can be ran locally to see the current cache entries for the web repo.
- CI is happy
N/A

fix(ci): reinstall yarn modules on bootstrap

---

src/context/FoxEthProvider/FoxEthProvider.tsx
src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts
src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
src/pages/Defi/views/StakingVaults.tsx
src/plugins/foxPage/hooks/useCurrentBlockNumber.ts
src/plugins/foxPage/hooks/useFarmingApr.ts
src/plugins/foxPage/hooks/useLpApr.ts
src/plugins/foxPage/hooks/useOtherOpportunities.ts
src/plugins/foxPage/utils.ts

Paranoia PR against overfetching, makes sure we skip fetching FOX-ETH LP/Farming data when the flag(s) are off.
N/A
Ensure FOX/ETH LP/Farming is still working as expected and no console errors are displayed. Tested with the flags on and off.
- No network calls are present with FOX/ETH modules as initiators with the flag off.
- FOX/ETH feature is still working with the flag on
- See top-level testing notes
- See top-level testing notes
- Initiator can be seen by clicking a specific request, then clicking "Initiator"

feat(no-overfetching): don't fetch FOX/ETH data with the flags off

---

src/features/defi/providers/cosmos/components/CosmosManager/Claim/components/Confirm.tsx

Removed the cancel button, made confirm button full-width
closes #2518
none
open up claim modal, the buttons should be as described
see above section
see above section

fix: claim buttons layout

---

.env.app
.env.base
.env.dev
.env.develop
.env.private
src/state/slices/txHistorySlice/txHistorySlice.ts

- chore: revert eth mainnet tx history page size changes
- chore: use our ethereum node for most calls
n/a - production issue resolution
* this is configured incorrectly and we can't load eth data
* eth accounts should load on all environments (develop/app/private)
* check my changes
* eth accounts should still load nicely

chore: eth node config reversion

---

.env.app
.env.private

chore: hotfix use etheruem dev endpoints

---

.env.base

confirmed with product that this referal code is correct
n/a
none
no testing is required

chore: remove dead config comment

---

src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx

This adds the missing `accountId` optional filter param when calling the `selectPortfolioCryptoBalanceByFilter` selector, making sure we select the balance to withdraw from the selected account.
- relates to the closed https://github.com/shapeshift/web/issues/2611
- Open the FOXy modal
- Click "Withdraw"
- When selecting an account other than 0, ensure that the balance shown as available to withdraw is the one for the selected account
- See top-level testing notes
- See top-level testing notes

fix(foxy): add missing withdraw accountId filter

---

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx

This adds the missing discrimination by account when selecting the FOX / ETH balances in the FOX/ETH LP modal st deposit step.
Note: Sync / accountId change when accounts directly from the deposit step is broken and will be tackled in a follow-up PR
- relates to the closed https://github.com/shapeshift/web/issues/2611
- Open the FOX/ETH LP modal
- Select any account, zero or another
- Ensure that the available to deposit balance matches the one for the selected account 
- See top-level testing notes
- See top-level testing notes

fix: fox eth lp deposit account balance

---

src/context/FoxEthProvider/FoxEthProvider.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/FoxFarmingManager.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/Claim.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimRoutes.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimStatus.tsx

This fixes the polling of the FOX/ETH Farming/LP modals status state.
- x ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- closes https://github.com/shapeshift/web/issues/2818
- Broadcast Txs for aforementioned steps
- When confirmed on-chain, the state should change from pending to confirmed
- Refer to top-level notes
- Refer to top-level notes

fix: fox/eth polling

---

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Status.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Status.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Status.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Status.tsx
src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Withdraw.tsx

This PR brings safety across the DeFi modals following the multi-account support, ensuring we never call `fromAccountId()` with an empty accountId string, which would throw an error.
While this wasn't a problem at runtime and we seemingly never pass an empty accountId, we could theoretically end up in this state, and this prevents it.
- relates to the closed https://github.com/shapeshift/web/issues/2610
- relates to the closed https://github.com/shapeshift/web/issues/2605
- relates to the closed https://github.com/shapeshift/web/issues/2605
- Defi opportunities show no regressions at all steps
- CI is happy
- Refer to top-level testing notes
- Refer to top-level testing notes

feat: nullish check accountId before fromAccountId() call

---

src/components/AssetAccountDetails.tsx
src/components/TransactionHistoryRows/TransactionGenericRow.tsx
src/context/WalletProvider/MobileWallet/components/MobileCreate.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyEmpty.tsx
src/pages/Dashboard/DashboardSidebar.tsx
src/pages/Dashboard/TradeCard.tsx
src/pages/Trade/Trade.tsx

fix: use location.state.vault only if its defined inside MobileCreate (#2835)
fix: mobile fixes (#2832)

chore: release v1.89.0 [DO NOT MERGE]

---

src/components/Modals/Settings/Settings.tsx
src/context/WalletProvider/MobileWallet/mobileMessageHandlers.ts
src/pages/Flags/Debugging.tsx
src/plugins/mobile/index.tsx

- feat: shake for flags on settings modal
- feat: button in flags menu to show developer modal
closes #2841
very low
* ensure my handlers and logic look sane
* see https://github.com/shapeshift/mobile-app/pull/66/files for the other side of what's handling this message
* **operations will not be able to test this until production as the mobile app is currently locked to
app.shapeshift.com**
* shake the device on a regular page, e.g. dashboard, nothing should happen
* open the settings modal on a physical device
* shake the device - the settings modal will close and you will be redirected to the flags menu
* scroll down and notice there is a new `Mobile environment` button
* the button should be labelled with the current environment you are on
* clicking the button should open the …

feat: mobile developer options

---

src/components/Modals/Settings/SettingsList.tsx

extension of https://github.com/shapeshift/web/pull/2844
android users seem to have problems with the shake event
this allows tapping the settings modal header 5 times to navigate to the flags page instead
related to #2841
extremely low
same testing steps as #2841, but tapping settings modal header 5 times should take you to the flags
page
* see common steps
* see common steps
n/a - no visual changes

feat: tap settings to get to flags

---

src/context/WalletProvider/MobileWallet/mobileMessageHandlers.ts

i'm a dum dum. the handler on the mobile app side required the existence of a truthy string to show
the native mobile environment switcher
related to #2841
extremely low, this was a bug and this should fix it
* clicking the environment switcher button on the flags page on a mobile device should bring up the
environment switcher modal

fix: send key with message to mobile app

---

src/features/defi/components/Overview/Overview.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/WithdrawCard.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/WithdrawCard.tsx

- Adjust the claim button to be more responsive
n/a
all visual should be no risk
n/a
This component seems like it could become one, we use it in two places currently. 
Confirm, you can still claim and see your claims. Also no numbers are running into each other.

fix: fix claim button for mobile

---

.github/workflows/bootstrap.yml
.github/workflows/pr-cypress.yml
.github/workflows/pr.yml

this does a few things to speed up CI
* we never actually needed the build - checking cypress docs it's [actually an antipattern to run cypress tests against build artifacts](https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Step-1-Start-your-server)
* adds env vars from to make test output readable
* uses the cache key based on `yarn.lock` - that's the only unique thing we care about for caching the install
n/a - CI has been a laggard for a while
will close #2768 unintentionally
* nothing user facing
* CI could be more flaky than previously, but the passed runs here suggest otherwise
* push empty commits to this branch to rerun things - the fleek failures were upstream yarn timeouts, not related to this branch (i promise)
* you can [delete cache keys using the gh …

chore: faster ci

---

src/components/Graph/RainbowChart/RainbowChart.tsx
src/components/Trade/TradeConfirm/TradeConfirm.tsx

fix: remove high low values on rainbow (#2863)
fix: spacing of the alert message (#2860)

chore: release v1.93.0 [DO NOT MERGE]

---

.env.develop

enables zendesk for develop environment
n/a
* configuration risk only, previously tested as working
* product and operations to sign off on this "feeling" correct
* plz test on device in mobile app

chore: enable zendesk in develop only

---

.github/workflows/bootstrap.yml
.github/workflows/pr-cypress.yml
.github/workflows/pr.yml

things were ugly, now they're not
n/a
* nothing related to application code - CI only
* branch protection rules need to be updated - you guys should be able to do this?
* nothing required from operations

chore: ci run naming

---

package.json
yarn.lock

This PR bumps `@shapeshiftoss/swapper` to latest following the RUNE trading lib fix in https://github.com/shapeshift/lib/pull/1041.
- relates to https://github.com/shapeshift/lib/issues/957
See testing steps
- Ensure Thor swaps show no regressions with the `ThorSwap` flag on
- Ensure RUNE swaps work with the `ThorChain` flag on
- Refer to top-level testing steps
- Refer to top-level testing steps

feat: bump swapper to latest

---

src/context/WalletProvider/NativeWallet/components/LegacyMigration/LegacyLogin.tsx
src/context/WalletProvider/NativeWallet/components/LegacyMigration/LegacyLoginSuccess.tsx
src/context/WalletProvider/NativeWallet/components/NativeTestPhrase.tsx

- Added data-test tags for login button, verify 2fa, import wallet, and skip test pass phrase
n/a
no risk
n/a
These are just for pendo, not testing is required.
These are just for pendo, not testing is required.

fix: add missing data tags for pendo

---

src/components/Trade/TradeRoutes/TradeRoutes.tsx

Spotted while testing https://github.com/shapeshift/web/pull/2917 - another case of us adding keys where we shouldn't, breaking the whole declarative routing of react-router and making the routing components unmount/remount.
Explanation: react-router `<Switch />`, `<Route />` and other declarative components are just that, components, and by adding a `key` property we're effectively telling react "this is one instance of a component" - keys in such components are valid if they are stable, but in this case, the key was `location.pathname`, which changes on every swapper location, and causes the whole `<TradeRoutes />` tree to unmount and remount again.
This exclusively improves swapper performance, the issue of amount / fees being rugged after confirmation is still present.
- tackles …

fix: trade routes unmounting and re-mounting

---

package.json
yarn.lock

bumps caip to remove the HEGIC pool from thor trades
closes #2907
extremely low - removes a dead pool from thorchain trading
* ensure my lib package bump is sane, trades to/from HEGIC should not route via thorchain

chore: bump caip remove hegic from thor pools

---

src/plugins/pendo/agent/filters.ts

we added visitor tracking in https://github.com/shapeshift/web/pull/2922 but the pendo filter is blocking these events
this allows the `&type=track` through the URL filter
n/a but related to https://github.com/shapeshift/web/pull/2922
we allow random things through the pendo filter
* ensure this change seems sane vs `develop`
* we should no longer see the console error below

fix: allow pendo track events through request filter

---

src/components/AssetSearch/AssetSearch.tsx
src/components/DeFi/components/AssetInput.tsx

- Used the HTML version not the "react" version
n/a
no risk
n/a
n/a

fix: update autocomplete prop to autoComplete

---

package.json
yarn.lock

package bump to include https://github.com/shapeshift/lib/pull/1049
n/a - discovered testing release
should be negligible and isolated to getting a price ratio
* setup a trade with native RUNE as the buy asset
* the swapper should correctly fetch a rate and quote, allowing you to proceed without entering buy
or sell amounts
* see common testing steps
* see common testing steps
wip

fix: bump swapper fix buy rune price ratio

---

src/components/Trade/hooks/useSwapper/swapperManager.ts

puts swappers in order cow, 0x, thor, as cow or 0x generally get better rates than thorchain
closes #2984
* trouble getting quotes
* note cowswap is currently disabled
* setup an erc20 -> erc20 quote for two assets supported by thorchain, e.g. fox -> usdc, it should be routed via 0x
* we should still be able to get quotes for thor trades, e.g. eth -> btc
* there is no need to actually do trades, just quotes are prioritizing 0x where possible
* see common testing steps
* see common testing steps

chore: reprioritize swappers

---

src/plugins/foxPage/FoxCommon.ts
src/plugins/foxPage/components/AssetActions.tsx
src/plugins/foxPage/components/MainOpportunity.tsx
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
src/plugins/foxPage/foxPage.tsx
src/plugins/foxPage/hooks/useOtherOpportunities.ts

This PR:
- Fixes the Fox Page not displaying with Keplr connected
- Changes the button copies to be "Connect Wallet" on a wallet without ETH support
- Adds missing/revamps button skeletons to be in loading state until wallet is loaded and wallet feature detection is ready 
- Disabled "Receive FOX" on a wallet without ETH support
- Does a bit of house-keeping
- adding `useCallback()` for event handlers
- abstracting and memoizing translations logic
- using our in-house `<Text />` component instead of chakra's `<Text />` with unmemoized `translate()` calls
- removing the links to the ShapeShift FOX page as we're now using FOX/ETH
closes https://github.com/shapeshift/web/issues/2980
- Fox Page should show with Keplr connected
- The Get Started / Manage buttons should display "Connect Wallet" …

feat: fox page keplr support / cleanup

---

src/components/AssetSearch/AssetList.tsx
src/components/AssetSearch/AssetRow.tsx
src/components/Layout/Header/NavBar/FiatRamps.tsx
src/components/Modals/FiatRamps/components/AssetSearch/AssetList.tsx
src/components/Modals/FiatRamps/components/AssetSearch/AssetRow.tsx
src/components/Modals/FiatRamps/views/Overview.tsx
src/components/Trade/hooks/useSwapper/swapperManager.ts
src/pages/Assets/Assets.tsx

- Remove the class on the FixedSizeList so we don't remove visibility
- Fix empty state on asset list
- Fix icon size for the list
closes #2990 
no real risk
n/a
On mobile and desktop, you should be able to scroll the asset list.

fix: remove class that sets the visibility to hidden

---

src/context/WalletProvider/WalletConnect/config.ts

Enable walletconnect for mobile
https://github.com/shapeshift/mobile-app/issues/47

fix: enable wallet connect in mobile

---

src/components/Trade/hooks/useSwapper/swapperManager.ts

this accidentally got reverted, puts swappers in priority cow, 0x, thor
n/a - noticed in develop
* eth/fox defaults to thor instead of 0x?
* erc trades should be routed via 0x

fix: put thorchain back above 0x as swapper priority

---

src/components/AssetSearch/AssetList.tsx
src/components/AssetSearch/AssetRow.tsx
src/components/DeFi/components/AssetInput.tsx
src/components/Layout/Header/NavBar/FiatRamps.tsx
src/components/Modals/FiatRamps/components/AssetSearch/AssetList.tsx
src/components/Modals/FiatRamps/components/AssetSearch/AssetRow.tsx
src/components/Modals/FiatRamps/views/Overview.tsx
src/components/Trade/hooks/useSwapper/swapperManager.ts
src/context/WalletProvider/WalletConnect/config.ts
src/pages/Assets/Assets.tsx
src/plugins/foxPage/FoxCommon.ts
src/plugins/foxPage/components/AssetActions.tsx
src/plugins/foxPage/components/MainOpportunity.tsx
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
src/plugins/foxPage/foxPage.tsx
src/plugins/foxPage/hooks/useOtherOpportunities.ts

fix: put thorchain back above 0x as swapper priority (#3002)
fix: enable wallet connect in mobile (#3001)
fix: remove class that sets the visibility to hidden (#2991)
feat: fox page keplr support / cleanup (#2981)
fix: use placeholder when value is zero (#2989)

chore: release v1.101.0 [DO NOT MERGE]

---

src/assets/translations/de/main.json
src/assets/translations/es/main.json
src/assets/translations/fr/main.json
src/assets/translations/pt/main.json

chore: global translations update - pt/es/fr/de

---

src/components/Trade/TradeConfirm/TradeConfirm.tsx

- Network should be THORChain 
no risk
n/a
n/a

chore: update thorchain text

---

src/assets/translations/en/main.json
src/plugins/foxPage/components/DappBack.tsx
src/plugins/foxPage/foxPage.tsx

- Add simple CTA for DappBack to earn rewards
n/a
no risk
On the fox page you should see a new card for earning rewards, when you click the button it should take you to the dappback page for ShapeShift.

feat: add dappback cta button

---

package.json
src/components/AccountDropdown/AccountDropdown.tsx
src/components/AssetAccounts/AssetAccountRow.tsx
src/components/AssetHeader/AssetChart.tsx
src/components/AssetSearch/AssetSearch.tsx
src/components/DeFi/components/AssetInput.tsx
src/components/Input/Input.theme.ts
src/components/Modals/AssetSearch/AssetSearch.tsx
src/components/Trade/TradeInputV2.tsx
src/components/Trade/hooks/useAccountsService.tsx
src/components/Trade/hooks/useSwapper/useSwapperV2.tsx
src/components/Trade/hooks/useSwapper/utils.ts
src/context/ModalProvider/ModalProvider.tsx
src/hooks/useWindowSize/useWindowSize.ts
src/plugins/foxPage/components/AssetActions.tsx
src/plugins/foxPage/components/MainOpportunity.tsx
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
src/plugins/foxPage/foxPage.tsx
src/state/slices/accountSpecifiersSlice/selectors.ts
src/state/slices/portfolioSlice/selectors.ts
yarn.lock

feat: lock buy account to sell account for 0x & CowSwaps (#3028)
fix: negative send max quote request (#3029)
chore: update caniuse db (#3018)
fix: fox page demo wallet / ready state checks (#3030)
revert: fix: use placeholder when value is zero (#2989) (#3031)
feat: asset select modal (#3015)
fix: cosmos asset account allocation (#3027)
fix: fox and foxy balances on fox page respect multiple accounts (#3023)

chore: release v1.105.0 [DO NOT MERGE]

---

src/plugins/pendo/visitorData.ts

we were checking for the existence of an object which was always truthy, then returning an empty
string. we wanted to check for the value of the string, the visitor id, and return that if it
exists.
see https://github.com/shapeshift/web/pull/3008/files for where this was originally broken by me
n/a - noticed by product
negligible - should fix missing visitor ids
* ensure my truthiness check is sane
n/a

fix: pendo visitor id bug

---

src/plugins/pendo/visitorData.ts

fix: pendo visitor id bug (#3035)

chore: release v1.106.0 [DO NOT MERGE]

---

.env.base
src/assets/translations/en/main.json
src/config.ts
src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/KeepKey/components/DownloadUpdaterApp.tsx
src/context/WalletProvider/KeepKey/helpers.ts
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/actions.ts
src/context/WalletProvider/config.ts
src/context/WalletProvider/routes.ts

feat(Keepkey): handle factory new keepkey connect (#3010)

chore: release v1.107.0 [DO NOT MERGE]

---

.github/workflows/bootstrap.yml
.github/workflows/pr-cypress.yml
.github/workflows/pr.yml

i like big girls. we now have github hosted runners that aren't puny. use `size-bertha`, our big
girl, for CI.
n/a
if CI goes green, big bertha is happy and so am i
* no testing required

chore: big bertha sized runners

---

src/components/Trade/hooks/useAccountsService.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Status.tsx

fix: no  on asset select (#3063)
fix: update cosmos staking translations (#3061)

chore: release v1.110.0 [DO NOT MERGE]

---

src/assets/translations/de/main.json
src/assets/translations/es/main.json
src/assets/translations/fr/main.json
src/assets/translations/pt/main.json
src/features/defi/components/Approve/ApprovePreFooter.tsx
src/features/defi/helpers/utils.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Approve.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx

feat: abstract DeFi Approve preFooter and hasEnoughBalanceForGas (#3037)
chore: pt/de/fr/es app translations (#3046)

chore: release v1.111.0 [DO NOT MERGE]

---

src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimRoutes.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
src/pages/Defi/hooks/useEarnBalances.tsx
src/pages/Defi/hooks/useFoxyBalances.tsx
src/plugins/foxPage/components/MainOpportunity.tsx
src/plugins/foxPage/foxPage.tsx
src/state/apis/foxy/foxyApi.ts

feat: useFoxyBalances multi-account (#3075)

chore: release v1.113.0 [DO NOT MERGE]

---

src/components/Modals/FiatRamps/config.ts
src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts

fix: remove address from the generated fiat url (#3068)

chore: release v1.114.0 [DO NOT MERGE]

---

.github/ISSUE_TEMPLATE/bounty.yml
.github/ISSUE_TEMPLATE/issue.yml
CONTRIBUTING.md
scripts/bootstrap-env.ts
src/context/FoxEthProvider/FoxEthProvider.tsx
src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
src/context/WalletProvider/NativeWallet/components/NativeStart.tsx
src/features/defi/components/Confirm/Confirm.tsx
src/features/defi/components/Deposit/PairDeposit.tsx
src/features/defi/providers/fox-eth-lp/api.ts
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx
src/plugins/foxPage/foxPage.tsx
src/plugins/foxPage/hooks/useFarmingApr.ts
src/plugins/pendo/agent/parse.test.ts

Correct grammar is good grammar.
N/A
Minimal.
☝️ 
☝️ 
N/A

refactor: fix typos

---

scripts/scrapeWalletConnectRegistry.ts
src/plugins/walletConnectToDapps/components/DappRegistryGrid.tsx
src/plugins/walletConnectToDapps/registry.json

We wanted to filter out all the listings that are wallets
n/a
n/a
With the `WalletConnectToDapps` flag on go to the dapps page and you should see a listing without wallets.

fix: filter out wallets from dapp list

---

src/features/defi/providers/cosmos/components/CosmosManager/Overview/WithdrawCard.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/WithdrawCard.tsx

Fixes issue of shade of yellow used being too light & hard to read for light mode by using a darker shade. Change applied also in similar context in `CosmosManager`
closes #2277 
Low risk, minor UI change
1. Log into app.shapeshift.com
2. Connect to a wallet of preference.
3. Under Settings change from dark mode to light mode.
4. Select the Fox Token Staking card from the DeFi vault
5. "Pending" word under Withdrawals section should have a darker shade of yellow for better legibility
Same instructions as in Engineering

fix(color): use darker yellow in light mode

---

src/components/AccountDropdown/AccountDropdown.tsx

Does what it says on the box, we were mapping over fragments without giving them a key - fixed by not using the shorthand and moving the key to the React.Fragment itself, not its children - the latter had no effect on the top-level element (a Fragment) being mapped over
N/A
If this breaks anything, we have bigger problems - will give us confidence that the right account is rendered
- Test AccountId is still properly working and being selected everywhere
- Swapper
- DeFi opportunities
- Send/Receive
☝🏽 
☝🏽

fix: key error on AccountDropdown

---

src/context/AppProvider/AppContext.tsx

this logic was backwards and broken yesterday, causing us not to clear out the previous portfolio when switching wallets
n/a - discovered in release
isolated to wallet switching
* look at the console and make sure the order of operations are sane, e.g. wallet event, clear portfolio and txs, upsert new account ids, fetch account + subscribe
* switch wallets - to a completely different mnemonic, not the same mnemonic in a different type of wallet, e.g. metamask and keepkey
* you should no longer see previous balances from the old wallet
no user facing changes

fix: fix wallet switching logic

---

.github/workflows/bootstrap.yml

we don't use `releases/**` branches any more - only the `release` branch
n/a - noticed CI wasn't running against release branch
zero - not application code
* make sure PRs run against a release branch
* no testing required by operations

chore: update github workflow to run against release branch too

---

src/components/Trade/TradeConfirm/TradeConfirm.tsx
src/components/Trade/TradeConfirm/useFrozenTradeValues.tsx

- Adds buy asset fiat amount on the confirm trade screen
closes #3119 
No huge risk, just hooking up values that already existed
When going to the trade confirm you should see the fiat amount below the expected amount.
if applicable)

feat: add buy asset fiat amount

---

src/state/slices/foxEthSlice/foxEthSlice.ts

This PR ensures we actually have market data to calculate FOX/ETH values e.g API, TVL. We currently have non-deterministic zero'd out values on the LP token price, fiat balance, and farming TVL as a result of requests silently falling back to 0 as the price of the LP token.
N/A, spotted by @shapeshift/operations in triage
- Loading states should be working for FOX/ETH LP/Farming TVL and fiat balance
- TVL for FOX/ETH LP/farming should be displayed in the earn row
- Rejections look sane
☝🏽

fix: reject FOX/ETH RTK queries while market data is loading

---

src/state/selectors.ts
src/state/slices/foxEthSlice/selectors.ts
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/txHistorySlice/selectors.ts

Gives a better home to `selectParamFromFilter` / `selectParamFromFilterOptional`, introducing the notion of a non-slice-related selectors module.
Also consumes the cached version of these two in `foxEthSlice`, which should bring performance improvements as we will now have stable destructured param from params input reference.
N/A
- Fox Page could be borked, test accordingly
- CI is happy
- FOX/ETH features across the app show no regressions

feat: move selectParamFromFilter into state/selectors

---

src/state/reducer.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/store.ts
src/test/mocks/store.ts
src/types/common.ts

This PR prototypes the new `opportunitySlice`, to be used as an RTK query slice for opportunities data e.g:
- FOX/ETH LP/farming data
- Yearn opportunities
N/A
The state isn't populated nor consumed, thus this PR doesn't produce any runtime changes yet
- Slice shape looks sane
- None

feat: prototype opportunities slice

---

package.json
src/react-app-env.d.ts
yarn.lock

Authored types for `eth-url-parser` have been released so we don't need to roll our own module declaration anymore.
- Relates to the closes https://github.com/shapeshift/web/issues/2059
- See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62399
None
- CI should be happy
☝🏽 
N/A

feat: add @types/eth-url-parser

---

src/state/slices/assetsSlice/selectors.ts

we missed this in our cache selector cleanup - was computing ~300 times
n/a
* minimal - smoke test that the app loads
* reselect dev tools -> check this selector only computes once per chain of the wallet connected
n/a

chore: memoize common fee asset selector

---

src/components/TransactionHistoryRows/TransactionGenericRow.tsx

Does what it says on the box, missing `key` in mapped JSX node.
N/A
- No console error is displayed in console on missing TransactionGenericRow key
^
^

fix: key error TransactionGenericRow

---

package.json
src/assets/translations/en/main.json
src/components/AccountDropdown/AccountDropdown.tsx
src/components/DeFi/components/GasInput.tsx
src/components/Modals/Send/TxFeeRadioGroup.tsx
src/components/TransactionHistoryRows/TransactionGenericRow.tsx
src/plugins/walletConnectToDapps/components/modal/ModalSection.tsx
src/plugins/walletConnectToDapps/components/modal/SignMessageConfirmation.tsx
src/plugins/walletConnectToDapps/components/modal/SignTransactionAdvancedParameters.tsx
src/react-app-env.d.ts
src/state/reducer.ts
src/state/selectors.ts
src/state/slices/assetsSlice/selectors.ts
src/state/slices/foxEthSlice/selectors.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/txHistorySlice/selectors.ts
src/state/store.ts
src/test/mocks/store.ts
src/types/common.ts
yarn.lock

feat: walletconnect gas price input (#3143)
fix: key error TransactionGenericRow (#3153)
chore: memoize common fee asset selector (#3152)
feat: add @types/eth-url-parser (#3149)
feat: prototype opportunities slice (#3136)
feat: move selectParamFromFilter into state/selectors (#3150)

chore: release v1.122.0 [DO NOT MERGE]

---

src/components/AccountDropdown/AccountDropdown.tsx

- Don't preselect the first item in the menu list
closes #3106 
no risk
When opening the account dropdown, you shouldn't see the first item selected.

fix: dont auto select the first item

---

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimConfirm.tsx

- Add the fiat amount under the amount
closes #3161 
small risk
When going to claim for FOXy and for FOX Farming you should see the fiat amount under the crypto amount.

feat: add fiat amount to claim

---

src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx

This PR fixes the FOX/ETH LP/farming overview modals opening with an empty state from the earn tab, by making sure we pass the highest balance account address when routing to it.
closes https://github.com/shapeshift/web/issues/3160
- Ensure FOX/ETH LP/farming modals still open from the DeFi section
= ^ 
- ^

fix: fox farming empty state in earn section

---

src/state/selectors.ts
src/state/slices/opportunitiesSlice/constants.ts
src/state/slices/opportunitiesSlice/mocks.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/slices/opportunitiesSlice/selectors.test.ts
src/state/slices/opportunitiesSlice/selectors.ts
src/state/slices/opportunitiesSlice/utils.ts

This PR adds opportunities slice selectors and matching tests, validating that the shape is sane.
Also improves typings in the process, add utilities related to de/serialization, and constants.
N/A
In theory none, this isn't consumed, but ensure no circular dependencies at runtime
- None
- Ensure no circular dependencies

feat: opportunity slice AccountId selectors

---

package.json
src/assets/translations/de/main.json
src/assets/translations/es/main.json
src/assets/translations/fr/main.json
src/assets/translations/pt/main.json
src/components/AccountDropdown/AccountDropdown.tsx
src/components/Bridge/BridgeRoutes/BridgeInput.tsx
src/components/Bridge/BridgeRoutes/Confirm.tsx
src/components/DeFi/components/AssetInput.tsx
src/components/DeFi/components/PercentOptionsButtonGroup.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Modals/Send/views/Confirm.tsx
src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/components/Trade/TradeInputV2.tsx
src/features/defi/components/Deposit/Deposit.tsx
src/features/defi/components/Deposit/PairDeposit.tsx
src/features/defi/components/Withdraw/Withdraw.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimConfirm.tsx
src/state/selectors.ts
src/state/slices/opportunitiesSlice/constants.ts
src/state/slices/opportunitiesSlice/mocks.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/slices/opportunitiesSlice/selectors.test.ts
src/state/slices/opportunitiesSlice/selectors.ts
src/state/slices/opportunitiesSlice/utils.ts
src/stories/Forms.stories.mdx
yarn.lock

feat: bump @shapeshiftoss/chain-adapters (#3176)
chore: translations update - pt/es/de/fr (#3175)
feat: opportunity slice AccountId selectors (#3139)
feat(defi): sane max / percent click handlers (#3171)
chore: remove useless estimateFees reexport (#3170)
feat: rename MaxButtonGroup -> PercentOptionsButtonGroup (#3169)
fix: fox farming empty state in earn section (#3166)
feat: add fiat amount to claim (#3164)
fix: show the fee crypto amount and send amount (#3165)
fix: dont auto select the first item (#3163)

chore: release v1.124.0 [DO NOT MERGE]

---

src/state/slices/opportunitiesSlice/utils.test.ts
src/state/slices/opportunitiesSlice/utils.ts

Simplish tests ensuring the serialization and deserialization utils are sane.
N/A
None, no runtime changes
CI is happy

feat: add opportunitiesSlice utils tests

---

src/context/AppProvider/AppContext.tsx
src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/resolvers/foxfarming.ts
src/state/slices/opportunitiesSlice/types.ts

Tightening types by removing the previously hardcoded union `'lp' | 'staking'` across the opportunitiesSlice and defining a new `OpportunityDefiType` type instead, leveraging the existing `DeFiType`. 
N/A
`DefiType.LiquidityPool` enum value has been renamed from `liquidity_pool` to `lp` to be able to reuse it here, double checked this isn't used anywhere in web nor lib so we should be safe here
- CI is happy
☝🏽 
None

feat(opportunitiesSlice): add OpportunityDefiType

---

cypress.config.ts

Add retry logic to Cypress so we can detect flakey tests, and not let them slow down development due to non-determinism.
https://docs.cypress.io/guides/guides/test-retries
N/A
Minimal.
☝️ 
N/A
N/A

feat: add cypress retry

---

src/assets/translations/en/main.json

Adds missing translations in https://github.com/shapeshift/web/pull/3143 for globalization to take over and translate
Copies provided by @shapeshift/product
N/A
None
None

feat: add missing walletconnect gas input translations

---

src/plugins/walletConnectToDapps/components/DappRegistryGrid.tsx

allows us to see which dapps users are connecting to w/ walletconnect
n/a
negligible - `data-test` attribute only
* see screenshot 👇
* no testing required by operations

feat: add pendo tracking to walletconnect dapp registry

---

src/components/Graph/RainbowChart/RainbowChart.tsx
src/plugins/walletConnectToDapps/components/DappRegistryGrid.tsx

feat: add pendo tracking to walletconnect dapp registry (#3205)
fix: rainbow chart tooltip mouseover bug (#3191)

chore: release v1.128.0 [DO NOT MERGE]

---

src/pages/Dashboard/RecentTransactions.tsx
src/pages/Trade/Trade.tsx

- Align the trade component to the top
- Remove the styling of the tx card
closes #
no risk
The trade component should be top aligned, and the tx card right sidebar should have no background

fix: align trade top

---

src/Routes/RoutesCommon.tsx
src/components/Tabs/Tabs.theme.ts
src/pages/Buy/Buy.tsx

- Allow the ability to pass in asset ID from the URL to buy
closes #
Small risk this could mess with the buy page functionality
BUY LTC
`/#/demo/buy-crypto/bip122:12a765e31ffd4059bada1e25190f6e98/slip44:2`
BUY BTC
`/#/demo/buy-crypto/bip122:000000000019d6689c085ae165831e93/slip44:0`

feat: pass asset from params to buy

---

src/context/AppProvider/AppContext.tsx
src/state/slices/opportunitiesSlice/constants.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/slices/opportunitiesSlice/resolvers/foxfarming.ts
src/state/slices/opportunitiesSlice/resolvers/index.ts
src/state/slices/opportunitiesSlice/thunks.ts
src/state/slices/opportunitiesSlice/types.ts

This PR populates the store with ETH/FOX staking metadata / userdata
N/A
Low - the slice data isn't consumed yet, but we might be making too many requests, ensure queries are rejected when they should and only dispatched once
- Ensure queries are rejected without market data, then fired only once per staking contract, can be tested by setting breakpoints here
https://github.com/shapeshift/web/blob/aa1ed12081067321e41e42a0b34249b256c62048/src/state/slices/opportunitiesSlice/resolvers/foxfarming.ts#L165
and there https://github.com/shapeshift/web/blob/aa1ed12081067321e41e42a0b34249b256c62048/src/state/slices/opportunitiesSlice/resolvers/foxfarming.ts#L285
- None

feat: populate ETH/FOX staking opportunities

---

src/context/ModalProvider/ModalProvider.tsx

Fixing some warnings from the compiler.
closes #
no risk functions as normal -- this is mainly for developing
n/a
n/a

chore: fix typing errors on modalprovider

---

src/assets/translations/en/main.json
src/components/Trade/hooks/useTradeAmounts.tsx
src/components/Trade/hooks/useTradeQuoteService.tsx
src/context/ModalProvider/ModalProvider.tsx
src/pages/Accounts/components/AccountNumberRow.tsx
src/pages/Accounts/components/ChainRow.tsx

fix: rework the way we handle clicking on accounts and expanding them (#3229)
chore: fix typing errors on modalprovider (#3230)
fix: set quote on route change (#3228)
fix: re-calculate values on NAN amount (#3227)

chore: release v1.132.0 [DO NOT MERGE]

---

package.json
yarn.lock

chore: release v1.133.0 [DO NOT MERGE]

---

src/components/Trade/TradeInputV2.tsx
yarn.lock

chore(deps): bump loader-utils from 1.4.0 to 1.4.1 (#3245)
fix: show not enough fee asset for gas multi-account (#3244)

chore: release v1.135.0 [DO NOT MERGE]

---

README.md
docs/rerenders.md
package.json
src/index.tsx
src/wdyr.ts
yarn.lock

Adds [`why-did-you-render`](https://github.com/welldone-software/why-did-you-render) for development, so we can track rerender madness 
- relates to https://github.com/shapeshift/lib/issues/943
This could not detect `development` NODE_ENV properly and run on prod, worst case scenario we don't actually commit `ComponentName.whyDidYouRender` property in prod so we're safu
- Add the following after any component declaration
```typescript
ComponentName.whyDidYouRender = {
logOnDifferentValues: true,
}
```
- Development server logs re-renders
- Served `yarn build` doesn't log re-renders
N/A
https://user-images.githubusercontent.com/17035424/200682473-180d41e7-fc88-4fbc-a7b3-cd8f96cb8376.mov

feat: add wdyr

---

src/components/AssetHeader/AssetChart.tsx
src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts
src/components/Modals/FiatRamps/utils.ts
src/features/defi/components/Approve/Approve.tsx
src/features/defi/contexts/IdleProvider/IdleProvider.tsx
src/features/defi/contexts/IdleProvider/useIdle.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx
src/features/defi/providers/idle/components/IdleManager/Claim/IdleClaim.tsx
src/features/defi/providers/idle/components/IdleManager/Claim/components/Confirm.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/IdleDeposit.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Confirm.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Deposit.tsx
src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx
src/features/defi/providers/idle/components/IdleManager/Withdraw/IdleWithdraw.tsx
src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Withdraw.tsx
src/hooks/useVaultWithoutBalance/useVaultWithoutBalance.ts
src/lib/utils.ts
src/pages/Defi/hooks/useVaultBalances.tsx
src/pages/TransactionHistory/TransactionHistory.tsx
src/state/slices/foxEthSlice/selectors.ts
src/state/slices/opportunitiesSlice/selectors.test.ts
src/state/slices/opportunitiesSlice/selectors.ts
src/state/slices/opportunitiesSlice/types.ts
src/state/slices/portfolioSlice/utils.ts

fix(defi): unrug idle infinite deposit/withdraw loop (#3253)
feat(defi): idle sanity (#3248)
fix: properly type partial records (#3260)
chore: optimise selectFoxEthLpAccountsOpportunitiesAggregated (#3255)
chore: type-guard boolean filters (#3259)
fix: defi approval loading state (#3258)

chore: release v1.137.0 [DO NOT MERGE]

---

src/lib/utils.ts

Uses generic naming conventions of `k`, `v`, as @gomesalexandre [rightly pointed out](https://github.com/shapeshift/web/pull/3260#discussion_r1017763745).
N/A
Almost literally none.
N/A
☝️ 
☝️ 
N/A

refactor: use generic type naming convention

---

src/components/Layout/Main.tsx

- Fix the console warning about useViewportScroll
closes #
no risk

fix: remove viewport scroll for usescroll

---

src/state/slices/opportunitiesSlice/constants.ts

Smallish PR keeping things DRY in opportunities constants
N/A
None
- I can count up to 4 without making a mistake
None

feat: reuse STAKING_ID_TO_NAME constants in base opportunities names

---

src/state/slices/opportunitiesSlice/constants.ts

Adds FOX farming v5 constant, unused yet - cc @0xean 
N/A
None, this is unused
N/A

feat: add fox farming v5 const

---

src/features/defi/components/Approve/ApprovePreFooter.tsx
src/features/defi/helpers/utils.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Approve.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx

This PR makes sure we always check for the current AccountId native asset balance to determine whether or not we have enough native asset for gas.
- relates to https://github.com/shapeshift/lib/issues/943
Allowances could be borkerood, test accordingly
Either
- Have gas over multiple accounts that total to enough ETH for approval gas
- Have enough as in one account, but not enough in the one that you need to make an approval for
Then
- You should not be able to continue with the approval
- ☝🏽 
☝🏽

fix: hasEnoughBalanceForGas account granularity

---

.git-blame-ignore-revs

Adds #3287 to `.git-blame-ignore-revs` making sure robots AST work don't spew blame
N/A
- Blame any line from #3287
- Ensure the blame is the original blame of that line before this PR
- None

chore: add #3287 to .git-blame-ignore-revs

---

package.json
yarn.lock

- Bump CAIP package to get new fiat assets for onramper
closes #
Added DOGE, LTC, BCH, 1INCH, AUSDC, LUSD, MASK, MINDS, OKG, POLS, STETH, TUSD, UMA, WETH, YFI, ZRX, USDC on AVAX
These should now be options to buy or sell on the fiat ramps.

chore: bump caip package

---

src/components/Layout/Layout.tsx
src/context/AppProvider/AppContext.tsx
src/context/TransactionsProvider/TransactionsProvider.tsx
src/pages/Accounts/AddAccountModal.tsx
src/state/slices/portfolioSlice/portfolioSlice.ts

i broke this with automatic account detection
n/a
low
check my logic is sane where we should automatically upsert vs not (auto account detection)
do a basic cheap tx - portfolio should refetch and update when the pending/confirmed tx comes through

fix: upsert portfolio on new tx

---

.env.app

prod cluster currently down - point at dev in the interim
n/a - prod issue
low - config change, dev-api.thorchain.shapeshift.com is currently up, api. is not
* connect native wallet - thorchain should load

fix: point thorchain at dev cluster

---

.env.app
src/components/Modals/FiatRamps/config.ts
src/components/Modals/FiatRamps/fiatRampProviders/banxa.ts
src/components/Modals/FiatRamps/fiatRampProviders/gem.ts
src/components/Modals/FiatRamps/fiatRampProviders/junopay.ts
src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts
src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts
src/components/Modals/FiatRamps/types.ts
src/components/Modals/FiatRamps/views/Overview.tsx

fix: point thorchain at dev cluster (#3298)
feat: add language to onramps (#3296)

chore: release v1.143.0 [DO NOT MERGE]

---

src/state/slices/foxEthSlice/selectors.ts

Fixes the FOX farming balances being shown as double / accounted for twice instead of the actual staked LP balances, across the DeFi section
- partially tackles https://github.com/shapeshift/web/issues/3300
None, reducer was a derp and always reducing twice
- With an account with no staked LP tokens yet, take some ETH/FOX LP tokens 
- Notice how the amount shown in DeFi card/rows is the actual amount of LP tokens you have staked
- Oneliner looks sane
☝🏽

fix: double FOX farming balances

---

src/state/slices/foxEthSlice/selectors.ts
src/state/slices/opportunitiesSlice/resolvers/foxfarming.ts

fix: incorrect farming ratio calculation (#3302)
fix: double FOX farming balances (#3301)

chore: release v1.144.0 [DO NOT MERGE]

---

.env.app

point prod frontend and dev backend for thorchain nodes, indexer, midgard
n/a - prod backend down
config change only - should allow thorchain swaps to work
test we can get thorchain quote

chore: swap thorchain nodes

---

.env.app

chore: swap thorchain nodes (#3304)

chore: release v1.145.0 [DO NOT MERGE]

---

src/context/TransactionsProvider/TransactionsProvider.tsx
src/state/slices/opportunitiesSlice/thunks.ts

This PR ensures we refetch opportunities data onMessage (FOX/ETH LP/Farming currently), effectively updating balances on incoming Txs.
- relates to https://github.com/shapeshift/web/issues/3250
We will effectively be "overfetching", or rather be fetching user opportunities data on FOX / FOX LP tokens Txs which are not LP/staking Txs
- Make a deposit/withdraw/claim Tx on FOX LP/farming
- Ensure the values get updated in DeFi cards, rows, DeFi modals and accounts pages

feat: refetch user opportunities data on incoming Tx

---

.env.app

Point thorchain and ethereum at prod endpoints (taxistake)
closes #
Low
- Thorchain and Ethereum load correctly
:point_up: 
:point_up:

chore: use prod endpoints

---

package.json
src/features/defi/providers/idle/components/IdleManager/Claim/ClaimReducer.ts
src/features/defi/providers/idle/components/IdleManager/Deposit/DepositCommon.ts
src/features/defi/providers/idle/components/IdleManager/Withdraw/WithdrawReducer.ts
yarn.lock

Included change: https://github.com/shapeshift/lib/pull/1086
Not consumed yet, though this unveiled that the `SET_OPPORTUNITY` was actually upserting opportunity inner data, which is not something we want to do and tsc caught.
N/A
None, not consumed yet
N/A
N/A

feat: bump @shapeshiftoss/investor-idle to latest

---

package.json
src/assets/translations/en/main.json
src/components/AssetAccountDetails.tsx
src/components/Delegate/StakingOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/components/TransactionHistory/AssetTransactionHistory.tsx
src/features/defi/providers/idle/components/IdleManager/Claim/ClaimReducer.ts
src/features/defi/providers/idle/components/IdleManager/Deposit/DepositCommon.ts
src/features/defi/providers/idle/components/IdleManager/Withdraw/WithdrawReducer.ts
yarn.lock

fix: typo (#3323)
feat: bump @shapeshiftoss/investor-idle to latest (#3321)
feat: add see all link to the tx history (#3319)

chore: release v1.148.0 [DO NOT MERGE]

---

.env.app
.env.base
.env.dev
.env.develop
.env.private

Use self hosted nodes for cosmos and osmosis
closes #
Low - we had run into issues related to mempool size and some other odd edge cases using datahub, so there is a chance we could run into some of them again with our current node configuration. We have full control over configuration now however, so adding fixes should be straightforward.
- Osmosis -> Atom or Atom -> Osmosis swaps
:point_up: 
:point_up:

chore: update endpoints to use self hosted nodes

---

src/context/FoxEthProvider/FoxEthProvider.tsx
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/slices/opportunitiesSlice/thunks.ts
src/state/slices/opportunitiesSlice/types.ts

Smallish PR making things a bit more programmatic preparing for Idle opportunitiesSlice
- relates to https://github.com/shapeshift/web/pull/3261
Minimal, ensure FOX/ETH shows no regressions
- FOX/ETH shows no regressions
- No console weirdness
- ☝🏽 
- Ensure opportunities are still populated
- ☝🏽

feat: opportunitiesSlice programmatic DefiProvider

---

src/components/Trade/hooks/useSwapper/useSwapper.tsx

Osmo needs to support cross account trade
closes #
NONE
Balances should show on sell asset with OSMO swapper
same as testing
same as testing

fix: osmo swapper balances weren't showing

---

src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/context/FoxEthProvider/FoxEthProvider.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimRoutes.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx
src/pages/Dashboard/PortfolioBreakdown.tsx
src/pages/Defi/hooks/useEarnBalances.tsx
src/pages/Defi/views/StakingVaults.tsx
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
src/plugins/foxPage/hooks/useOtherOpportunities.ts
src/state/slices/opportunitiesSlice/constants.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts
src/state/slices/opportunitiesSlice/resolvers/idle.ts
src/state/slices/opportunitiesSlice/resolvers/types.ts
src/state/slices/opportunitiesSlice/selectors.ts
src/state/slices/opportunitiesSlice/thunks.ts
src/state/slices/opportunitiesSlice/types.ts
src/state/slices/opportunitiesSlice/utils.ts

This PR:
- Flavors `LpId` and `StakingId` as an intersection of their underlying flavor and `AssetId`
- Adds an `OpportunityId` union of `LpId` and `StakingId`
- Adds a `toOpportunityId` curried version of `toAssetId` returning an `OpportunityId`
- Removes `as LpId | StakingId` and `as AssetId` type guards for opportunityIds
N/A
Zero to none, if CI is happy we're happy
- CI is happy
- ☝🏽
- None

feat: opportunityId AssetId intersection

---

src/components/StakingVaults/AllEarnOpportunities.tsx

https://github.com/shapeshift/web/pull/3337 introduced filtering of earn tab opportunities with low TVL, but now that  https://fox.shapeshift.com/fox-farming is deprecated, app.shapeshift.com is the only place to start staking FOX.
In other words, all new FOX farming contracts will have 0 TVL initially, thus making users unable to initially stake, which means the TVL would never go up to that threshold.
This PR adds an additional filter for earn tab opportunities, so that ETH/FOX staking opportunities are always displayed (as long as they're not expired / users have a balance)
closes #
- V5 is shown in earn opportunities
☝🏽 
☝🏽

fix: don't filter out fox farming opportunities with low TVL

---

src/components/Modals/PopupWindowModal.tsx

- Update the button from cancel to close to not confuse users.
closes #
The secondary button should say Close and not Cancel

chore: change translation from cancel to close

---

src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx

This PR fixes Idle's overview modal to display the actual underlying balance vs. assuming 1/1 peg between the Idle asset and the underlying asset
relates to https://github.com/shapeshift/web/issues/3392
- Ensure the underlying amounts in Idle overview are matching Idle asset portfolio balance * (Idle asset price / underlying asset price)
☝🏽 
☝🏽

fix(idle): overview underlying asset balance

---

src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx

Fixes the TVL displayed in Idle overview, since we assumed base unit USDC (6 dp) amounts from the API whereas we're getting human USDC amounts
N/A
None
- TVL in Idle opportunities overview modal are matching the ones in the matching earn rows / Idle asset pages
☝🏽 
☝🏽

fix(idle): overview tvl precision

---

src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Withdraw.tsx

Until we got precision and display amounts sorted, using idle token at Idle withdraw step and not displaying the underlying token is going to be the safest
relates to https://github.com/shapeshift/web/issues/3392
None, this brings safety, more safety = more safu
- Available to withdraw amounts match the actual own Idle token
- It is possible to withdraw max.
- Fiat values are correct (pending market data lib fix)
☝🏽 
☝🏽

feat: use idle token withdraw

---

src/assets/translations/en/main.json
src/components/Layout/Layout.tsx
src/context/AppProvider/AppContext.tsx

- Added chains to the alert message
- Removed the degraded state toast
- Updated the copy to be a little more friendly
closes #
Moved some logic from the toast into the alert, possible it could work differently.
You'll need the app to go into a mode where it can't load chain data --- not sure how to reproduce so you can see it.

chore: add chains to alert and remove toast

---

package.json
react-app-rewired/headers/csps/webflow.ts
src/components/Carousel/Arrow.tsx
src/components/Carousel/Carousel.tsx
src/components/Carousel/Dots.tsx
src/components/Carousel/Slider.tsx
src/components/Carousel/types.ts
src/components/Promo/PromoCard.tsx
src/components/Trade/Trade.tsx
src/components/Trade/TradeConfirm/ReceiveSummary.tsx
src/components/Trade/hooks/useSwapper/useSwapper.tsx
src/components/Trade/hooks/useTradeQuoteService.tsx
src/components/Trade/types.ts
src/constants/UsdcPrecision.ts
src/constants/constants.ts
src/features/defi/helpers/normalizeOpportunity.tsx
src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx
src/hooks/useSortedVaults/useSortedVaults.ts
src/pages/Dashboard/DashboardSidebar.tsx
yarn.lock

feat: add dynamic slippage to trades (#3419)
feat: add promo banner for foxy (#3413)

chore: release v1.164.0 [DO NOT MERGE]

---

src/wdyr.ts

excludes `withBoundingRects()` and `Portal` from why did you render log messages, happens whenever you mouse over the chart
https://github.com/welldone-software/why-did-you-render#include--exclude
n/a - this was annoying
nearly zero, dev tooling only
* no more log spew in console
* not testable by ops
no more of this

fix: stop why did you render log spew

---

src/state/slices/opportunitiesSlice/selectors.ts

Adds some selector safety from https://github.com/shapeshift/web/pull/3424, unrugging develop whitescreen until it gets merged
N/A
None, adds missing optional chaining
- App doesn't throw an error boundary on load

fix: make develop great again

---

src/components/TransactionHistoryRows/TransactionGenericRow.tsx
src/components/TransactionHistoryRows/TransactionMethod.tsx
src/components/TransactionHistoryRows/TransactionReceive.tsx
src/components/TransactionHistoryRows/TransactionSend.tsx
src/components/TransactionHistoryRows/TransactionTrade.tsx
src/components/TransactionHistoryRows/UnknownTransaction.tsx

Better indicate a failed transaction status with a red warning icon
closes #
Low
- Validate failed transaction shows the new icon
:point_up: 
:point_up:

feat: indicate failed transaction with red warning icon

---

src/state/migrations/000_clear_opportunities_slice.ts
src/state/migrations/index.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
src/state/store.ts

This PR migrates the opportuniesSlice / opportunitiesApi slices persistence, so that we don't display Idle MATIC staking opportunities anymore, which are incompatible with our app given the fact that withdraws are made with an NFT, see: https://medium.com/idle-finance/expanding-risk-hedging-liquid-staking-stmatic-pyts-a6331e74b5ae
Currently untested, this is pending Idle update of their API endpoint so that MATIC opportunities aren't returned anymore.
- closes https://github.com/shapeshift/web/issues/3407
- closes  https://github.com/shapeshift/web/issues/3434

feat: redux-persist opportunitiesSlice / opportunitiesApi migration

---

package.json
yarn.lock

Includes https://github.com/shapeshift/lib/pull/1106:
- brings Idle asset symbols in
- excludes MATIC assets from generated assets
N/A
None, this simply brings regenerated asset-data - excluded assets might need a migration and are not guaranteed to be excluded on the front-end for now because of persisted opportunitiesSlice (see https://github.com/shapeshift/web/pull/3439), to be tested on the deployed build
- Idle asset symbols are shown and match the on-chain ones

feat: bump @shapeshiftoss/asset-service to latest

---

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx
src/features/defi/providers/idle/components/IdleManager/Claim/components/Confirm.tsx
src/features/defi/providers/idle/components/IdleManager/Claim/components/Status.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/IdleDeposit.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Confirm.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Deposit.tsx
src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx
src/features/defi/providers/idle/components/IdleManager/Withdraw/IdleWithdraw.tsx
src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Withdraw.tsx
src/state/slices/opportunitiesSlice/selectors.ts

This PR fixes the following for ETH/FOX farming V5:
- consumption of undefined `state.opportunity` at withdraw step instead of consuming the earn opportunity from the selector where it now belongs
- missing base unit to precision conversion at withdraw step 
Additionally, diffes a global LSP rename from `selectEarnUserStakingOpportunity` to `selectEarnUserStakingOpportunityByUserStakingId` for sanity
N/A
None, most of this PR diff is simply an LSP rename
- Withdraws from FOX farming V5 are working
- The correct amounts are withdrawn 
☝🏽 
☝🏽

fix: eth/fox staking withdraw

---

package.json
yarn.lock

Gets the market movement increase into next release (https://github.com/shapeshift/lib/pull/1115).
N/A - related to support thread on Discord.
Minimal - limit should be slightly more lenient (smaller).
Nothing noticeably user facing.
☝️ 
☝️ 
N/A

chore: bump @shapeshiftoss/swapper to 14.5.3

---

src/state/slices/portfolioSlice/selectors.ts

Reverted a section of code that I removed during PR review, but is actually needed.
We must filter validatorId's 
closes #3437 
Breaks feature flag stuff
Any of the OSMO feature flags are turned on, but staking is off:
There should be no OSMO staking opportunities on the defi page and asset page
Any of the OSMO feature flags are turned on, but staking is off:
There should be no OSMO staking opportunities on the defi page and asset page
OSMO staking flag is turned on:
OSMO staking opportunities are available on defi page and asset page
Any of the OSMO feature flags are turned on, but staking is off:
There should be no OSMO staking opportunities on the defi page and asset page

fix: osmosis staking showing when disabled

---

package.json
src/components/Approval/Approval.tsx
src/components/Trade/TradeInput.tsx
src/state/slices/portfolioSlice/selectors.ts
yarn.lock

feat: bump @shapeshiftoss/investor-idle to latest (#3461)
fix: use correct fee symbol for trade error and approval confirmation (#3458)
fix: osmosis staking showing when disabled (#3450)
chore(deps): bump decode-uri-component from 0.2.0 to 0.2.2 (#3457)
chore: bump @shapeshiftoss/swapper to 14.5.3 (#3456)

chore: release v1.167.0 [DO NOT MERGE]

---

src/components/AssetAccounts/AssetAccountRow.tsx
src/components/AssetHeader/AccountLabel.tsx
src/components/AssetHeader/AssetHeader.tsx
src/components/Layout/Layout.tsx
src/components/TransactionHistory/AssetTransactionHistory.tsx
src/pages/Accounts/Account.tsx
src/pages/Accounts/AccountTxHistory.tsx
src/pages/Accounts/components/AccountNumberRow.tsx
src/plugins/cosmos/CosmosAccount.tsx
src/plugins/cosmos/CosmosAccountTxHistory.tsx
src/state/slices/assetsSlice/selectors.ts
src/state/slices/portfolioSlice/selectors.ts
src/state/slices/portfolioSlice/utils.ts

how do we not already have these? handy util functions to get fee asset id from chain or asset ids
n/a - developer QOL
low - not consumed anywhere, surprised we don't have these already
note - this non-null assertion *is* going to fuck us when we turn osmo on - we'll need to do a redux persistence migration to blow away persisted account ids in the store if we ever turn it off, e.g. there will exist account ids we no longer have a chain adapter for
testing not required by ops
n/a

feat: fee asset utility functions

---

src/assets/translations/en/main.json
src/components/Modals/FiatRamps/FiatCurrencyList.json
src/components/Modals/FiatRamps/config.ts
src/components/Modals/FiatRamps/fiatRampProviders/banxa.ts
src/components/Modals/FiatRamps/fiatRampProviders/gem.ts
src/components/Modals/FiatRamps/fiatRampProviders/junopay.ts
src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts
src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts
src/components/Modals/FiatRamps/views/Overview.tsx

- Added a select field for fiat currency for buy/sell
- Added the supported fiat currencies for each provider
- Added a common currency json file
closes #
This shouldn't really effect too much it's possible that we may have missed some of the currency options and a provider might not show up for that fiat/asset pair.
On the buy/sell form if you change the fiat currency you should see the list filter based on what that provider supports.

feat: add fiat currency selection to fiat form

---

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Status.tsx

This PR ensures we use the right "withdraw" copy at FOX farming withdraw status step
closes https://github.com/shapeshift/web/issues/3473
None
- Withdraw from FOX Farming and broadcast a Tx
- Ensure the `You have successfully <action> from Fox Farming V5.` says `withdrawn`
☝🏽 
☝🏽

fix: defi withdraw status wrong copy

---

src/pages/Dashboard/TradeCard.tsx
src/pages/Defi/components/FeaturedCards/FeaturedCard.tsx

- Remove variant on trade card so it matches the other sidebar components
- Move data tag to button on FeaturedCard
closes #
Trade component matches the other sidebar components

fix: use correct variant for trade card

---

src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts

- This broke the foxy deposit, reverting back for now.
closes #
Go to foxy deposit and you should be able to deposit as normal.

fix: revert foxy provider enum

---

src/state/slices/opportunitiesSlice/selectors.ts

Do not display opportunity cards that the user is already in
closes #3497 
Go to dashboard or DeFi -> Earn you should only see eligible opportunities that you have not currently deposited into.

fix: remove opportunity cards if user has  a balance

---

src/components/StakingVaults/StakingTable.tsx

On load the earn table should be sorted by balance
closes #3498 
Go to DeFi -> Earn the table should be sorting by balance

fix: sort earn table by balance

---

src/components/Layout/Header/Header.tsx
src/components/StakingVaults/StakingTable.tsx
src/state/slices/opportunitiesSlice/selectors.ts

fix: sort earn table by balance (#3499)
fix: remove opportunity cards if user has  a balance (#3500)
feat: buy button in the header for mobile (#3494)

chore: release v1.172.0 [DO NOT MERGE]

---

package.json
yarn.lock

Includes https://github.com/shapeshift/lib/pull/1128
N/A
None, `adapter.getName()` is only used for logging purposes
- CI is happy
☝🏽 
☝🏽

feat: bump @shapeshiftoss/chain-adapters to latest

---

src/components/Trade/hooks/useSwapper/useSwapper.tsx
src/components/Trade/hooks/useSwapper/utils.ts
src/state/slices/portfolioSlice/utils.ts

fix - hard coded account value specifically when swapping out of utxo coins
delete associated unused utility functions
closes #3430
* isolated to swapper and swapping out of utxo coins
* please test selling utxo coins out of both account 0 and account 0+
* verify #3430 is resolved
👆
👆

fix: fix hard coded sell account 0 when swapping out of utxo coins

---

src/components/AccountDropdown/AccountDropdown.tsx
src/components/Trade/hooks/useSwapper/useSwapper.tsx
src/components/Trade/hooks/useSwapper/utils.ts
src/state/slices/portfolioSlice/utils.ts

chore: account dropdown safety (#3514)

chore: release v1.175.0 [DO NOT MERGE]

---

package.json
yarn.lock

fix: use sell AssetId in getInboundAddressDataForChain (#3522)

chore: release v1.177.0 [DO NOT MERGE]

---

src/assets/translations/constants.ts
src/assets/translations/index.ts

- Adds the Turkish in the language selector.
- This should only be merged after #3526 is merged, it is missing the Turkish `main.json` (and tests will fail until it added in this other PR)
closes #3528 
None. An additional full review of the strings in situ in the UI will be performed by the translator once merged.
Verify that the language can be selected and used in all the user interfaces.
☝️ 
☝️

feat: add turkish in language selector

---

yarn.lock

`yarn.lock` got out of sync. This PR fixes that.
N/A
Small.
No user-facing changes expected.
☝️ 
☝️ 
N/A

chore: fix `yarn.lock`

---

package.json
src/assets/translations/constants.ts
src/assets/translations/de/main.json
src/assets/translations/es/main.json
src/assets/translations/fr/main.json
src/assets/translations/index.ts
src/assets/translations/pt/main.json
src/assets/translations/ru/main.json
src/assets/translations/tr/main.json
yarn.lock

chore: fix  (#3531)
feat: add turkish in language selector (#3527)
chore: add tr translations and update pt/es/de/ru/fr (#3526)
chore(deps): bump loader-utils from 1.4.0 to 1.4.2 (#3530)
chore: upgrade wherever widget (#3525)

chore: release v1.178.0 [DO NOT MERGE]

---

package.json
react-app-rewired/headers/csps/plugins/wherever.ts
src/components/Layout/Header/NavBar/Notifications.tsx
yarn.lock

please see original PR https://github.com/shapeshift/web/pull/3550
closes #

chore: wherever widget version bump

---

src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx

removes throw in favor of opt chaining on icon - it appears on the next render when it's ready
n/a - noticed in `1.182.0` release testing
very low, isolated entirely to yearn deposit modal
clicking deposit into a yearn opportunity should work
👆
👆

fix: don't crash on yearn deposit

---

src/state/migrations/001_filter_expired_yearn_opportunities.ts
src/state/migrations/index.ts
src/state/slices/opportunitiesSlice/resolvers/yearn/index.ts

Note: USDT 0.3.5 is still not removed, since it will require some custom logic - not a regression from prod since it's already broken there
- partially tackles https://github.com/shapeshift/web/issues/3529 - still doesn't remove that faulty opportunity but we now know that `excluded` isn't the way to go to tackle this one
None
Ensure USDC 0.3.0 / 0.3.5 Yearn opportunities are gone

fix: filter out expired yearn opportunities

---

src/components/Modals/FiatRamps/config.ts

- JunoPay has paused buying and forcing users to withdraw their funds so we should not offer it as an option for now.
closes #
No risk
JunoPay should not be an option in the buy/sell flow.

fix: remove junopay

---

package.json
src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx
src/state/migrations/002_filter_retired_yearn_opportunities.ts
src/state/migrations/index.ts
src/state/slices/opportunitiesSlice/selectors.ts
yarn.lock

✅  Requires https://github.com/shapeshift/lib/pull/1145 to be published
Properly handles expired opportunities
- at selector-level, so that they're only shown in case a staked / rewards balance is available
- at view layer level for Yearn, so that it is impossible to deposit on expired Yearn vaults
This effectively uses the same list as https://vaults.yearn.finance/ethereum/retired-vaults, see https://github.com/yearn/yearn-vaults-descriptions/blob/8751b66ec49d40b9259c087ef12f14c633d1356d/pages/api/vaults.tsx#L70
closes https://github.com/shapeshift/web/issues/3529
None?
- Test with any of the vaults listed in https://vaults.yearn.finance/ethereum/retired-vaults
- If you have a balance for said opportunity, the vault should be listed in DeFi earn, clicking it will only allow withdrawing, …

fix(defi): handle expired opportunities

---

package.json
src/components/Modals/FiatRamps/config.ts
src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx
src/state/migrations/002_filter_retired_yearn_opportunities.ts
src/state/migrations/index.ts
src/state/slices/opportunitiesSlice/selectors.ts
yarn.lock

fix(defi): handle expired opportunities (#3556)
fix: remove junopay (#3557)

chore: release v1.183.0 [DO NOT MERGE]

---

src/pages/Defi/components/EligibleCarousel.tsx
src/pages/Defi/components/EligibleSlider.tsx

Filters out low APY eligible opportuniries on the Dashboard and DeFi/Earn pages.
closes #3563 
None.
Own assets like USDC or UNI currently which have 0% APY for some opportunities currently and verify the carousel of eligible opportunities on the Dashboard and the DeFi/Earn pages, they should not appear anymore.
Before:
After:

feat: filter low apy eligible opportunities

---

src/components/Trade/TradeConfirm/TradeConfirm.tsx

- Fix message to show for THORChain trades
- Show message for COW Swap trades as well
closes #
This is mainly visual so shouldn't be any real risk
When doing an ERC20 -> ERC20 on the trade confirm screen you should see a message that the trade could take a few minutes. 
When doing a THORChain trade you should also see this message.

feat: show cow swap trade may take a minute to complete

---

package.json
src/hooks/useErrorToast/useErrorToast.ts
yarn.lock

Part of some pre-factor work to handle THORSwap `halt` flags to better handle errors from `lib` and in our RTK query APIs.
Consumes changes from https://github.com/shapeshift/web/pull/3581.
Will pass CI once packages are updated.
Contributes to https://github.com/shapeshift/web/issues/2925
Very small - if CI passes after package update we are good.
Everything should work as normal.
☝️ 
☝️ 
N/A

chore: handle singular enum name for SwapErrorTypes

---

src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts

N/A
Given Midgard is more failure-prone, Midgard failing would rug the whole flow - which is intended, we probably don't want half-populated opportunities?
- Ensure APR is fetched and displayed
- Nothing to see here yet 👀

feat: fetch thorchain savers APY from midgard

---

package.json
src/assets/translations/en/main.json
src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useIsTradingActive.tsx
src/components/Trade/utils.test.ts
src/components/Trade/utils.ts
src/features/defi/providers/cosmos/components/CosmosManager/Claim/components/Confirm.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
src/state/apis/swapper/getIsTradingActiveApi.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
yarn.lock

fix: don't throw in <ExpiredWithdraw /> render while underlyingAssetId is loading (#3593)
feat: handle THORSwap halts (#3597)
fix: don't throw in Cosmos SDK <Withdraw /> render while assetId is loading (#3594)
feat: fetch thorchain savers APY from midgard (#3591)

chore: release v1.188.0 [DO NOT MERGE]

---

src/assets/translations/en/main.json

Small copy change request from @DiggyDiggy2.
N/A
As small as it gets.
N/A
☝️ 
☝️

chore: update tradingNotActive translation

---

src/components/Promo/iOSPromoCards.tsx
src/pages/Dashboard/DashboardSidebar.tsx

- After some feedback, we should show this to all users and they can figure out how to use apple pay to buy with no KYC
closes #
No risk
This promo card should now show for everyone regardless of platform.

fix: let everyone see apple pay cta

---

src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts
src/features/defi/contexts/DefiManagerProvider/DefiManagerProvider.tsx
src/features/defi/contexts/DefiManagerProvider/utils.ts
src/pages/Defi/components/OpportunityCard.tsx
src/plugins/foxPage/FoxCommon.ts
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanel.tsx
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
src/plugins/foxPage/hooks/useOtherOpportunities.ts
src/state/slices/opportunitiesSlice/constants.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts
src/state/slices/opportunitiesSlice/resolvers/idle/index.ts
src/state/slices/opportunitiesSlice/selectors.test.ts

Big refactor needed for https://github.com/shapeshift/web/pull/3598, which exposed our currently wrong types stemming from the previous implementation that were "fine for now", won't be compatible anymore, see this removed comment / runtime bit:
https://github.com/shapeshift/web/blob/23a9cc22d3091dfc3af338e701c080fb434e8a41/src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx#L86-L89
- N/A, though it's effectively groundwork for https://github.com/shapeshift/web/issues/3595
- The whole routing from any page (DeFi overview / earn, account/asset pages, FOX page) could be borked, test accordingly
- **Test with ALL DeFi opportunity Types**
- In DeFi overview / earn, account/asset pages, and FOX page, clicking an opportunity still routes to it
- Implementation …

feat: remove DefiProvider.FoxEthLP

---

package.json
src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/components/Trade/hooks/useAccountsService.tsx
src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts
src/features/defi/contexts/DefiManagerProvider/DefiManagerProvider.tsx
src/features/defi/contexts/DefiManagerProvider/utils.ts
src/pages/Defi/components/FeaturedCards/FeaturedCard.tsx
src/pages/Defi/components/OpportunityCard.tsx
src/plugins/foxPage/FoxCommon.ts
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanel.tsx
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
src/plugins/foxPage/hooks/useOtherOpportunities.ts
src/state/slices/opportunitiesSlice/constants.ts
src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts
src/state/slices/opportunitiesSlice/resolvers/idle/index.ts
src/state/slices/opportunitiesSlice/selectors.test.ts
yarn.lock

fix: undefined swapper on first render (concise) (#3617)
feat: remove DefiProvider.FoxEthLP (#3600)
chore: bump swapper to 15.3.3 (#3618)

chore: release v1.190.0 [DO NOT MERGE]

---

package.json
yarn.lock

Use latest swapper to fix osmo swapper invalid pair bug
low risk bug fix for feature flagged osmo swapping
swap osmo and atom and see it work
see testing
see testing

fix: latest swapper osmo fix

---

src/state/migrations/004_opportunities_underlyingAssetRatios_underlyingAssetRatiosBaseUnit.ts
src/state/migrations/index.ts

Derp, we need to purge the current opportunities with `underlyingAssetRatios` after https://github.com/shapeshift/web/pull/3626 - if we try to access `underlyingAssetRatiosBaseUnit[i]`, we get an error
N/A
None
- App loads
- ☝🏽 
- ☝🏽

fix: underlyingAssetRatios -> underlyingAssetRatiosBaseUnit migration

---

src/context/AppProvider/AppContext.tsx
src/state/slices/opportunitiesSlice/resolvers/index.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
src/state/slices/opportunitiesSlice/thunks.ts

N/A
In theory isolated to savers, and additionally under flag - though `<AppContext />` has been updated with thunks dispatches for more chains, which could cause degraded state
- Clear your persisted store
- DeFi data still loads fine
- ☝🏽 
- Create a new native wallet or ape your seed into Thorswap
- Deposit into all vaults except BNB
- Come back to the app and hard refresh
- Ensure the cards/row/overview DeFi modal are working and the data is matching the THORSwap one
- ☝🏽

feat: thorchain savers userData

---

.env.base
react-app-rewired/headers/csps/defi/osmosis.ts
src/Routes/RoutesCommon.tsx
src/components/Bridge/BridgeRoutes/Confirm.tsx
src/components/Modals/Send/Form.tsx
src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
src/components/Modals/Send/utils.ts
src/config.ts
src/context/AppProvider/AppContext.tsx
src/context/WalletProvider/KeepKey/components/DownloadUpdaterApp.tsx
src/hooks/useEvm/useEvm.ts
src/pages/Recovery/Recovery.tsx
src/state/slices/opportunitiesSlice/resolvers/index.ts
src/state/slices/opportunitiesSlice/resolvers/osmosis/index.ts
src/state/slices/opportunitiesSlice/resolvers/osmosis/utils.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
src/state/slices/opportunitiesSlice/thunks.ts

fix: fund recovery (#3631)
feat: add osmosis lp opportunity resolvers (#3569)
feat: decouple handleSend and handleFormSend (#3629)
feat: thorchain savers userData (#3613)
chore: update keepkey updater links (#3632)

chore: release v1.192.0 [DO NOT MERGE]

---

package.json
yarn.lock

adds optimism to fiat ramps
n/a
minimal - isolated to fiat ramps
optimism should appear in fiat ramps

feat: optimism on fiat ramps

---

src/plugins/pendo/agent/parse.test.ts
src/plugins/pendo/agent/parse.ts

- Pendo added a new line to their pendo agent make it so it doesn't fail anymore
closes #

fix: update new line for pendo agent

---

src/plugins/pendo/agent/parse.ts

- Pendo agent has whitepespace at the end need to check for it when parsing
closes #

fix: check if last line is empty on parse

---

src/plugins/foxPage/components/AssetActions.tsx

- Update foxy cta to match new abstraction
closes #3654 
No risk
On the fox opportunities page, with foxy selected clicking "get foxy" should open the modal.

fix: update url for get foxy cta

---

package.json
src/components/Bridge/BridgeRoutes/Confirm.tsx
src/components/Modals/Send/Form.tsx
src/components/Modals/Send/SendCommon.tsx
src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Modals/Send/utils.ts
src/components/Modals/Send/views/Address.tsx
src/components/Modals/Send/views/Confirm.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/ThorchainSaversDeposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.test.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
yarn.lock

Base deposit featureset for THORCHain savers:
- Confirmed working:
closes N/A
Low, theoretically isolated to THORChain savers, though send input API has changed from `address` to to everywhere
- It is possible to deposit into savers vaults for all chains
- Re-depositing for UTXOs is currently expected to fail, though it might work out of pure luck depending of your current UTXO outputs - to be fixed in https://github.com/shapeshift/web/pull/3635
** CONSIDER THIS VIEW LAYER ONLY AND DON'T DEPOSIT, SEE https://github.com/shapeshift/web/pull/3640 **
- Code looks like code
- Again, DON'T DEPOSIT. THORSwap UI is built with a single address in mind so you won't be able to withdraw from there, and this will rug you forever when https://github.com/shapeshift/web/pull/3640 goes in. The reason for …

feat: thorchain savers deposit

---

src/plugins/foxPage/foxPage.tsx

- Missed this in my previous PR to fix foxy on the fox page
closes #3654 
No risk
Clicking on "manage" from the fox staking table opens the modal

fix: update the opportunity row on click

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx

This PR:
- Brings a similar missing UTXO account address safety added as part of https://github.com/shapeshift/web/pull/3643 CR, this time for deposits
- Makes sure we throw actual sign/broadcast errors for non-UTXOs
- Tightens the deposit async flow similarly to what was done in https://github.com/shapeshift/web/pull/3643
N/A
None, isolated to savers
- This looks like code
- None

feat(savers): more deposit/withdraw safety

---

src/state/slices/opportunitiesSlice/selectors/lpSelectors.ts

* fixes crypto amount display for LP opportunities on earn page
closes #
None
* Load the application at `app.shapeshift.com` and connect the demo wallet.
* Navigate to the earn page, and view both the fiat and crypto amounts for the FOX-ETH LP opportunity.
* Deploy this branch locally, connect the demo wallet, and navigate to the earn page.
* Verify that both the fiat and crypto amounts for the FOX-ETH LP opportunity appear correct.
* Earn page from production environment with demo wallet connected
* Earn page from local environment with demo wallet connected

fix: unbreak lp opportunity crypto amounts

---

src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx

* Fixes broken "Get Started" button click on FOX Opportunities page
closes #
* Load any wallet and navigate to FOX Opportunities page.
* Click "Get Started" in the "FOX Token Staking" section.
* Make sure that the application does not give the "Oops" screen.
Same as above.
Result of clicking "Get Started" in current production environment:
Result of clicking "Get Started" in local environment with fix applied:

fix: broken get started button on fox opportunities page

---

src/components/StakingVaults/AllEarnOpportunities.tsx
src/components/StakingVaults/EarnOpportunities.tsx
src/components/StakingVaults/StakingTable.tsx
src/features/defi/contexts/DefiManagerProvider/DefiManagerProvider.tsx
src/features/defi/contexts/YearnProvider/YearnProvider.tsx
src/features/defi/helpers/normalizeOpportunity.tsx
src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/pages/Defi/hooks/useEarnBalances.tsx
src/plugins/foxPage/foxPage.tsx
src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts
src/state/slices/opportunitiesSlice/resolvers/foxy/index.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
src/state/slices/opportunitiesSlice/selectors/index.ts
src/state/slices/opportunitiesSlice/selectors/lpSelectors.ts
src/state/slices/opportunitiesSlice/selectors/selectors.test.ts
src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
src/state/slices/opportunitiesSlice/types.ts

feat: thorchain savers minimum deposit amounts (#3644)
fix: update the opportunity row on click (#3658)
feat: cleanup log spew (#3660)
fix: unbreak lp opportunity fiat amounts (#3659)
feat: add aggregated earn user lp opportunity selector (#3651)

chore: release v1.196.0 [DO NOT MERGE]

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositCommon.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositReducer.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx

Adds missing deposit fee logic at confirm step and passes it down from the final quote as deposit route params, so that we can consume them at status step.
N/A
- Do a deposit up to the sign and broadcast step
- Click sign and broadcast, and confirm the values are matching the ones at confirm step
- ☝🏽 
- ☝🏽

feat(savers): add/pass deposit fee in deposit routes

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
yarn.lock

feat(savers): maxish UTXO deposits / mempool seen safety (#3682)
chore(deps): bump ua-parser-js from 1.0.2 to 1.0.33 (#3681)

chore: release v1.200.0 [DO NOT MERGE]

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositCommon.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositReducer.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/WithdrawCommon.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/WithdrawReducer.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx

This PR passes the `maybeFromUtxoAccountAddress` at status step i.e the *actual* UTXO input address, vs. assuming the `account` part of the AccountId is the address, which isn't going to be true for UTXO accounts because of
address reuse.
N/A
None, isolated to THORChain
- Broadcast an UTXO savers Tx (deposit/withdraw)
- Ensure the status is completed after 1 on-chain confirmation
- ^
- ^

fix(savers): utxo confirmed status

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositCommon.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositReducer.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/WithdrawCommon.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/WithdrawReducer.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
src/plugins/walletConnectToDapps/utils.ts

fix: remove contractAddress from getFeeData call (#3685)
fix(savers): utxo confirmed status (#3684)

chore: release v1.201.0 [DO NOT MERGE]

---

src/features/defi/components/Deposit/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositCommon.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx

- unrugs EVM deposits/withdraws Tx detection, got rugged by nullish coalescing operator again, JS pls
- unrugs EVM max sends
N/A
Isolated to savers
- It is possible to deposit / withdraw any amount from EVM positions, including max send and close to max send (e.g remove 1 wei)
☝🏽 
☝🏽

fix(savers): evm max/ish sends

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx

This PR handles minimum savers withdraw amount i.e the withdraw amounts should be above the `outbound_fee` for that `inbound_address`.
N/A
Isolated to savers
- Try to deposit smallish amounts (e.g < 1$ for all chains)
- Ensure you are seeing "Minimum: {minimumAmount} {symbol}"
- Ensure inputting anything above that lets you proceed up to a working savers withdraw
- ☝🏽 
- ☝🏽

feat(savers): minimum withdraw amounts

---

src/pages/Dashboard/DashboardSidebar.tsx

- Hide this CTA till onramper adds back Mercuryo
closes #3693 
No risk
Should no longer see the CTA for NO KYC on the dashboard

fix: hide onramper cta

---

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx

Gremlins how this worked before, spotted by big @reallybeard - fixes the routing so that we're building an AssetId from the correct params vs. non-existing `contractAddress`.
Also does a bit of housekeeping with identical `assetId` / `underlyingAssetId` while at it
N/A
None
- ETH/FOX LP withdraw opens when clicking withdraw
- ^ 
- ^

fix: eth/fox lp withdraw

---

src/Routes/RoutesCommon.tsx
src/features/defi/components/Deposit/Deposit.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/DepositCommon.ts
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
src/pages/Dashboard/DashboardSidebar.tsx
src/pages/Recovery/Waterman.tsx

fix: eth/fox lp withdraw (#3692)
fix: hide onramper cta (#3694)
chore: user fund recovery (#3662)
fix(savers): bch initial deposits (#3691)
feat(savers): minimum withdraw amounts (#3689)
fix(savers): evm max/ish sends (#3688)

chore: release v1.202.0 [DO NOT MERGE]

---

src/state/store.ts

fixes blocking renders in dev mode only. RTK query calls an internal function `findNonSerializableValue` which deeply checks if an object is serialiazable. this happens on every action and state change, both in api and data slices. osmo lp data is 750kb and chokes up on it. this doesn't happen in production but can block page interaction for 20s+ in dev mode.
n/a
we end up with non-serialiazable data in the store. redux dev tools will stop working/page will crash. would be easy to bisect out and no way to affect users.
fresh load of the page shouldn't hang ~20s in when app context calls `fetchAllOpportunitiesUserData`
tangentially - we're way overfetching osmo data, like 750kb 6 times
not testable by operations

fix: local dev perf

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx

This PR refetches savers userData on deposit/withdraw, by waiting 15 seconds before both setting the Tx as completed and refetching. This way, we ensure that by the time the Tx is shown as completed, the position is updated.
Refetching in the view-layer is only the temporary naive way to refetch until we build a THORChain savers parsers, which we will be able to now that we have memos. Fetching in `<Status />` effectively means that closing the status modal would not refetch, which could be the case for UTXOs with 5+ minutes to 1 confirmation, less likely for EVM chains / ATOM.
N/A
- Deposit/withdraw from savers
- Ensure the position is updated accordingly as soon as the Tx shows completed
https://user-images.githubusercontent.com/17035424/215135254-19bea4b2-7371-4e63-a5d6-28bc157f6377.mov …

feat(savers): refetch opportunities on deposit/withdraw

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/ThorchainSaversDeposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx

Adds some `AccountId` safety at status step, to ensure we serialize a Tx for the correct one.
N/A
None, if we have issues with this, it means a bigger problem as transactions serialization from messages would be wrong across the app
- Deposit from any account > 0
- Ensure the Tx shows as confirmed after on-chain confirmation
- ☝🏽 
- ☝🏽

fix(savers): multi-account thorchain deposit confirmed state

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx

Fixes `getSupportedEvmChainIds` being called outside of component scope and not having access to the `context/PluginProvider/chainAdapterSingleton`, rugging our evmChainId check and in turn sending an invalid string value to ethers `hexlify`:
https://github.com/shapeshift/web/blob/dc97fcebef4c345450ed730c206fba2824fe31b0/src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx#L174-L176
N/A
None
- EVM saver deposits are working
- ☝🏽 
- ☝🏽

fix(savers): evm deposits

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts

Temporarily disables memos since:
- We do not have L1 addresses
- Our `ss` affiliate isn't linked to any address except a THOR address (which would only work for the THOR saver, which doesn't exist)
- We don't have a THORName linking L1 addresses together
Without a valid affiliate, the quotes will effectively error on us and rug the whole flow.
N/A
- Savers deposits work again
- ^ 
- ^

feat(savers): temporarily disable memos

---

src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts

Safety factor to ensure we are getting updated THOR positions.
N/A
- Deposit/withdraw from savers
- Confirmed screen is shown 25s after actual on-chain confirmation and refetches user data
- Closing the status modal before completion also refetches savers user data 
- ^
- ^

feat(savers): bump update time to 25s

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts

Wrong calculation was wrong, we were picking the wrong field from the API - the TVL was actually the one we needed 
N/A
None, this was wrong 
- Savers caps look sound
- BTC shows as full cap
- ☝🏽 
- ☝🏽

fix(savers): accurate caps

---

package.json
src/components/AccountDropdown/AccountDropdown.tsx
src/components/Trade/TradeConfirm/TradeConfirm.tsx
yarn.lock

fix: correct zrx approve amount (#3731)
fix: overflow issue on account dropdown (#3730)

chore: release v1.205.0 [DO NOT MERGE]

---

src/pages/Defi/components/FeaturedCards/FeaturedCard.tsx

Fixes missing queryparam in the `<FeatureCard />` routing
N/A
- Savers eligible cards are working
- Other opportunities eligible cards still open
- ☝🏽 
- ☝🏽

fix(savers): eligible cards

---

src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts
src/state/slices/opportunitiesSlice/resolvers/index.ts
src/state/slices/opportunitiesSlice/thunks.ts

Adds a resolver for Cosmos opportunities metadata - not handling the default opportunity case yet.
N/A
None, under flag and not consumed in the view layer yet
- Connect a wallet with an active validator (default validators aren't fetched yet)
- Enable `CosmosSdkOpportunitiesAbstraction`
- Ensure the validator metadata is matching the one in the current `validatorData` slice / view-layer data
None

feat(cosmos): opportunities metadata

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx

- We need users to see the caps so show overview after they click button.
closes #
When clicking I understand, they should see the overview screen with caps and everything else.

fix: hide empty state and show overview

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts
src/state/slices/opportunitiesSlice/resolvers/index.ts
src/state/slices/opportunitiesSlice/thunks.ts

fix(savers): estimate gas for deposits
Merge remote-tracking branch 'origin/main' into develop
feat(cosmos): opportunities metadata (#3741)

chore: release v1.208.0 [DO NOT MERGE]

---

src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/types.ts
src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/utils.ts
src/state/slices/opportunitiesSlice/types.ts

The undelegations counterpart of https://github.com/shapeshift/web/pull/3746 - adding a new Cosmos SDK-specific union since undelegations are not part of the base opportunities standard.
N/A
closes #
- Ensure `opportunitiesSlice` undelegations entries look sound compared to the current `portfolioSlice` ones (same data really, no 💆ing has been done on it)
- Nada

feat(cosmos): opportunities userData undelegations

---

src/assets/translations/en/main.json
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx

Spotted by @reallybeard, if a user has enough balance for gas, but not enough for dust, we should block from continuing since the Tx won't be able to go through.
N/A
None
- Have enough native asset for gas but not enough for dust e.g 0.015 DOGE
- Ensure you see "Not enough {asset} for gas" at confirm step and cannot continue with the withdraw
- ☝🏽 
- ☝🏽

fix(savers): not enough gas + dust to withdraw

---

package.json
src/components/Trade/utils.ts
yarn.lock

@0xApotheosis https://github.com/shapeshift/web/pull/3757 fix as a hotfix to main - PRd to ensure no shaenanigans
closes #

fix: incorrect RUNE halt (#3757) 

---

src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts
src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts
src/state/slices/opportunitiesSlice/resolvers/foxy/index.ts
src/state/slices/opportunitiesSlice/resolvers/idle/constants.ts
src/state/slices/opportunitiesSlice/resolvers/idle/index.ts
src/state/slices/opportunitiesSlice/resolvers/osmosis/index.ts
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
src/state/slices/opportunitiesSlice/resolvers/yearn/index.ts
src/state/slices/opportunitiesSlice/selectors/selectors.test.ts
src/state/slices/opportunitiesSlice/types.ts

Required for https://github.com/shapeshift/web/pull/3760 - we have no way to get the validator address / AccountId from `OpportunityMetadataBase` currently since we assume the `AssetId` as an accessor of sorts but Cosmos staking uses `ValidatorId` as an ID i.e a CAIP-10 representing a validator.
N/A
None, not consumed yet, but doesn't hurt to sanity test this
- Clear your persisted redux store
- Ensure no shaenanigans across opportunities
- ☝🏽 
- ☝🏽

feat(opportunities): opportunity metadata IDs

---

src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts

Preemptive fix for https://github.com/shapeshift/web/pull/3760 to be happy - the current DeFi routing assumes a `contractAddress` which does not exist yet for Cosmos SDK opportunities.
Note the quotation marks around `contractAddress`. This is a limitation of the current routing, as this is the terminology used to refer to an upstream opportunity address, but this really isn't a contract.
This shouldn't produce any regressions since `contractAddress` isn't consumed yet for Cosmos SDK opportunities.
N/A
Zero to none, see testing
- Clear your persisted redux store
- Cosmos opportunities are still displayed and their routing is still happy
- ☝🏽 
- ☝🏽

fix: cosmos aggregated opportunities "contractAddress"

---

src/components/Trade/hooks/useSwapper/swapperManager.ts

this is probably not necessary, but there's an ongoing cowswap exploit and i'd rather users not be potentially unrisk until cowswap acknowledges and responds to the problem
https://twitter.com/MevRefund/status/1622797628760096769?s=20&t=Qf5DdQfrnuESTcx2fEeinQ
n/a - noticed by ops
low? high? - potential loss of user funds if we *don't* turn it off
trades should not be routed via cowswap
👆
👆

chore: disable cowswap better safe than sorry

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx

Fixes gas estimation for THORChain savers withdraw when trying to withdraw any amount greater than your actual account balance.
N/A
- Ensure the amount you have staked for a given savers opportunity is greater than your account balance
- Try to withdraw any amount from that savers that's greater than your account balance (either user-input, a percentage, or a max withdraw)
- The withdraw flow should be great again
- ☝🏽 
- ☝🏽

fix(savers): withdraw gas estimation

---

src/state/apis/foxy/foxyApiSingleton.ts

Does what it says in the comments - see diff.
N/A
The localhost check could be rugged - no way to test before deploying a build unless you fiddle with DNS and exposing your build anywhere else than localhost which is non-trivial
- FOXy is working again locally (purge your persisted store as a sanity check, though recent migrations went in since this is broken so you most likely won't have any FOXy stale data)
- FOXy is still showing up on the build you're testing this in (purge your persisted store before testing)

feat: use own node for FOXy on localhost

---

src/assets/translations/en/main.json
src/components/AssetSearch/AssetSearch.tsx
src/plugins/arkeo/LpCard.tsx
src/plugins/arkeo/StakingCard.tsx
src/state/apis/foxy/foxyApiSingleton.ts

- Update the arkeo cards copy
closes #
no real risk
Click each card's cta button and make sure that it does what it says.
1. Deposit into LP pool
2. Stake into position
3. Buy FOX
4. Trade for FOX

fix: update copy for the cards on arkeo

---

src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts
src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/utils.ts

Does what it says on the box - big short removed feature flag guarantees and this brings them back
N/A
None
- Ensure Osmo flag off is turned off as code (turned off in prod and release envs currently, which will allow for ops testing)
- Purge your persisted userData
- Osmo staking shouldn't appear anywhere
- ☝🏽 
- ☝🏽

fix: don't fetch osmo staking metadata/userData with the flag off

---

src/components/Modals/FiatRamps/fiatRampProviders/coinbase.ts

- Hardcode this one specific use case for buying fox on coinbase
closes #
no risk
Clicking fox on buy should take you to the FOX page on coinbase

fix: use correct ticker for coinbase

---

.env.base
src/components/Banners/YatBanner.tsx

- Use the correct yat link
closes #
no risk
Click on the yat link takes you to the branded yat welcome page, you should see the shapeshift logo

fix: update yat link to the correct one

---

src/components/Card/Card.theme.ts
src/components/Menu/Menu.theme.ts
src/components/Modal/Modal.theme.ts
src/features/defi/components/DefiModal/DefiModal.tsx

- This is mainly for visual consistency, the outer container radius should be double of the inner container radius (e.g. button radius is xl, the container should be 2xl)
closes #
no risk
No testing

chore: outer container should be double the inner container radius

---

.env.base
src/config.ts
src/plugins/foxPage/components/Governance.tsx

- Use snapshot link for the view all proposals on the fox page
closes #
No risk
Clicking the view all proposals on the fox page takes you to snapshot

fix: replace boardroom view all with snapshot

---

src/assets/translations/en/main.json
src/plugins/arkeo/Arkeo.tsx

On Arkeo Airdrop page, replacing "Coinbase Ventures" and hyperlink with 'Coinbase Cloud' and link to https://shapeshift.com/library/foxchain-shapeshift-partners-with-coinbase-cloud
closes #

fix: ventures to cloud

---

src/assets/translations/de/main.json
src/assets/translations/en/main.json
src/components/Trade/TradeConfirm/AssetToAsset.tsx
src/components/Trade/TradeConfirm/TradeConfirm.tsx
src/lib/utils.ts

Updates the title of the TradeConfirm modal based on the state of the trade. When the trade is being executed, the modal title will now display "Trade Pending".
Contributes to #3329
Small, affects TradeConfirm title during a trade.
Test trades that they work as normal. Ensure modal title is correct as specced in #3329

feat: update title of trade modal when trade is pending and completed

---

src/pages/Defi/hooks/useEarnBalances.tsx

Fixes a bug where FOXy balances where double-counted in earn balances and as part of staking opportunities, effectively making the earn balances/net worth too high, off whatever your FOXy balance is.
Cut as a separate PR in case we want to ship it separately before https://github.com/shapeshift/web/pull/3802 goes in
N/a
None, this was simply wrong
- Have an account with FOXy only for easy testing (or FOXy + anything else if you're feeling like doing some math)
- Ensure your FOXy balance is counted only once
- ☝🏽 
- ☝🏽

fix: foxy balances double count

---

src/Routes/RoutesCommon.tsx
src/components/Layout/Header/Header.tsx
src/components/Layout/Header/NavBar/MobileNavBar.tsx

- Need to account for the safe areas for the header and the new bottom nav
closes #
small risk
Going to need to test on a mobile device, the header and nav should account for the safe areas of a device (camera notch, bottom thumb line)

fix: safe areas for mobile

---

package.json
scripts/scrapeWalletConnectRegistry.ts
src/plugins/walletConnectToDapps/registry-overrides.json
src/plugins/walletConnectToDapps/registry.json
src/plugins/walletConnectToDapps/types.ts
yarn.lock

- Updates the `yarn scrape-walletconnect-dapps` script to use the WalletConnect Cloud API properly. Everything is requested in one `fetch` now. Re-using the `projectID` I've found in image URLs of the `registry.json` file we had generated. We continue to import all entries except the one with the `app_type` "wallet" as we do not want to list other wallets.
- Updates the `registry.json` with fresh data from WalletConnect.
- Manually fixes two URL we know are outdated in the source data: Zapper and SnapShot.
closes #3833
None.
Check the listing of dApps for WalletConnect. Verify also 2 specific entries, Zapper and SnapShot, they should have working URLs without redirect.
☝️ 
☝️

fix: walletconnect dapps listing and scraping script

---

src/components/Trade/Components/AssetSelection.tsx

- fix: swapper v3 account change handler
we had a dummy handler hooked up, this hooks up the real one 🤦
n/a - noticed in release
lower than before - but deals with account selection in swapper, so still needs a good test
switch accounts in the swapper, do a handful of trades. previously it was only selecting the highest balance account, now it should respect the selected account.
see that we're using a real handler.
see above.
no visual changes in this PR - see #3772 for swapper UI changes

fix: new swapper account change

---

package.json
yarn.lock

Updated Wherever widget to version without global css overrides, and a better markdown parser for messages

fix: bump wherever version

---

.env.base
src/context/WalletProvider/KeepKey/components/DownloadUpdaterApp.tsx

reverts links
reverts https://github.com/shapeshift/web/pull/3632
- [ x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
closes #
low, old functionality

feat: revert to updater app

---

src/components/Layout/Header/Header.tsx

- Multiple people reported as bug removing it
closes #
Header is always there

fix: remove header scroll

---

src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx
src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts
src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
src/state/slices/opportunitiesSlice/types.ts
src/state/slices/opportunitiesSlice/utils.ts

This brings the notion of `icon` as an opportunity metadata property.
Prerequisite for https://github.com/shapeshift/web/pull/3841 - we somehow had a Cosmos SDK flavor of `<EarnOpportunities />` with validator icons, but DeFi overview/earn used the ATOM/OSMO icon (i.e `underlyingAssetIds[0]` instead of the validator icon.
This standardizes things before we remove the aforementioned Cosmos-SDK specific component and move out to `<EarnOpportunities />` for Cosmos SDK.
N/A
Cosmos SDK opportunities icons might be borked 
- In DeFi overview / earn, Cosmos SDK staking icons are matching the validator icon
- In the DeFi overview modal of Cosmos SDK staking, the icon is matching the validator icon
- ☝🏽 
- ☝🏽

feat(defi): opportunities metadata icons

---

src/state/migrations/008_clear_cosmos_sdk_opportunities.ts
src/state/migrations/index.ts

Clears the Cosmos SDK opportunities to ensure we get the freshest Cosmos SDK opportunities shape
N/A
None
- Cosmos SDK opportunities are happy
- ☝🏽 
- ☝🏽

feat: clear cosmos sdk opportunities migration

---

.env.base
src/config.ts
src/state/slices/opportunitiesSlice/resolvers/osmosis/index.ts
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

closes #
Low
* Enable REACT_APP_FEATURE_OSMOSIS_LP flag
* Verify that REACT_APP_FEATURE_OSMOSIS_LP_ADDITIONAL_POOLS flag is disabled
* Verify OSMO/ATOM LP is the only Osmosis LP opportunity available on the DeFi/Earn page

feat: add feature flag to disable additional osmosis liquidity pools

---

src/assets/translations/en/main.json
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversEmpty.tsx

- Show a buy cta for users that have no balance and we support buy
closes #
low risk
Go to a savers vault for an asset you have no balance of -- if the asset is supported to buy with you will see a CTA.

feat: add buy cta to thorchain savers

---

src/assets/translations/en/main.json
src/components/Promo/PromoCard.tsx
src/components/Promo/types.ts
src/pages/Dashboard/DashboardSidebar.tsx

- Adding a few promo cards for specific stuff for ETH Denver
closes #
no risk
Can't really test as these are time based and will only show up at those times.

feat: add promos for eth denver

---

package.json
src/components/Modals/Send/utils.ts
yarn.lock

* adds support Osmosis network token sends
* depends on: https://github.com/shapeshift/lib/pull/1201
closes #
Medium risk - this modifies the send code path for all cosmos-sdk sends.
* verify that non-OSMO sends function as expected
* verify that there are no regressions with native Osmosis and Cosmos sends

fix: add osmosis token send support

---

scripts/bootstrap-env.ts
scripts/release.ts

please see original PR opened from wrong branch https://github.com/shapeshift/web/pull/3867
- feat: cloudflare CI
- feat: private branch tracks main branch
closes #

feat: cloudflare CI and release script

---

scripts/bootstrap-env.ts
scripts/release.ts

feat: cloudflare CI and release script (#3870)

chore: release v1.218.0 [DO NOT MERGE]

---

.env.base
package.json
src/assets/translations/en/main.json
src/components/Modals/Send/utils.ts
src/config.ts
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Confirm.tsx
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx
src/state/slices/opportunitiesSlice/resolvers/osmosis/index.ts
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts
yarn.lock

fix: update native onboarding copy (#3862)
fix: osmosis add token send support (#3878)
fix: fix osmosis lp withdraw confirm amounts (#3877)
feat: flag off additional osmosis liquidity pools (#3876)

chore: release v1.219.0 [DO NOT MERGE]

---

package.json
scripts/utils.ts
yarn.lock

fixes build hash for all environments
n/a - noticed by ops with cloudflare change
low
* not user facing
* tested and working on https://yeet.shapeshift.com/#/demo/flags
* build will fail if this doesn't work
see https://github.com/npm/node-semver#ranges-1 for docs used
see that the tag and commit hash matches https://yeet.shapeshift.com/#/demo/flags

fix: commit hash fix for build/flags page

---

src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Overview/OsmosisLpOverview.tsx

Spotted by ops in https://discord.com/channels/554694662431178782/1066088208905031681/1077428383144759376
Does what it says on the box - the simple fix to this was actually a missing `useEffect` deps array (no idea how this slipped through eslint):
https://github.com/shapeshift/web/blob/db224768666fba659faaa9499d6e053c111b6fb8/src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Overview/OsmosisLpOverview.tsx#L166-L173
Additionally clean things up a bit by removing async `calculateBalances` callback in favor of memoized `underlyingAssetsCryptoPrecision`, avoiding overfetching in the process since the Osmosis pool is now a state variable and won't be refetched on any deps change (except for `lpAssetId` which should never change).
N/A
We might be too blazingly fast since we …

fix: osmosis LP overview account granularity

---

src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Overview/OsmosisLpOverview.tsx

Spotted by ops in https://discord.com/channels/554694662431178782/1066088208905031681/1077422488134352938 / https://discord.com/channels/554694662431178782/1066088208905031681/1077428383144759376 - adds missing highest balance AccountId logic to Osmosis LP.
N/A
None?
- Be staked in an Osmosis LP opoprtunity in more than one account
- Ensure the highest balance account is selected when opening the opportunity from DeFi earn/overview
- ^
- ^

feat: osmosis LP overview highest balance account selection

---

package.json
scripts/utils.ts
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Overview/OsmosisLpOverview.tsx
yarn.lock

feat: osmosis LP overview highest balance account selection (#3882)
fix: osmosis LP overview account granularity (#3881)
fix: commit hash fix for build/flags page (#3880)

chore: release v1.220.0 [DO NOT MERGE]

---

package.json
yarn.lock

contains package bump for https://github.com/shapeshift/lib/pull/1204
n/a
hopefully negative - asserts/prevents invalid memo generation
check thor swaps still work
👆
👆

fix: swapper safety

---

src/features/defi/providers/cosmos/components/CosmosManager/Deposit/DepositReducer.ts

closes https://github.com/shapeshift/web/issues/3883
None?
- Clear your persisted store then refresh
- Ensure depositing into ATOM/OSMO default validators shows APY when you're not already staked
- Deposit and clear your persisted store again then refresh
- Ensure depositing into ATOM/OSMO default validators still shows APY with the opportunity now being an active one
- ☝🏽 
- ☝🏽

fix: cosmos sdk deposit step apy

---

src/features/defi/components/Deposit/PairDeposit.tsx
src/features/defi/components/Deposit/PairDepositWithAllocation.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx
src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Deposit.tsx

Fixes a few regressions introduced by https://github.com/shapeshift/web/pull/3892, mostly WRT the arity of methods accepting amounts/assets 0/1.
N/A
- ETH/FOX deposit is happy again (untested, waiting for test funds)
- Osmosis LP deposit is happy again
- For both of these, the estimated yearly returns shows no regressions vs. prod
☝🏽 
☝🏽

fix: pair deposit fixes

---

package.json
yarn.lock

- feat: yarn bump for upgrading @shapeshiftoss packages
- fix: bump swapper - lower default slippag
- feat: enable avax
https://github.com/shapeshift/lib/pull/1207
https://github.com/shapeshift/lib/pull/1208
n/a
**reasonably high w.r.t specific swaps - see PR testing steps in associated lib PRs**
* please check trades routed via CoWSwap still work - complete trades to ensure new slippage tolerance is ok
* check swaps in and out of avax on multiple accounts via THORChain
* **ensure funds are actually received on chain on avax side!**
* **ensure funds go into correctly avax receive account number**
https://github.com/shapeshift/lib/pull/1207
https://github.com/shapeshift/lib/pull/1208
see below
n/a
as above

fix: swapper default slippage and enable avax

---

src/plugins/walletConnectToDapps/v2/walletUtils.ts

Use the `getConfig`
N/A
Almost 0.
Everything should work as usual.
☝️ 
☝️ 
N/A

chore: use getConfig helper

---

src/components/Breadcrumbs/Breadcrumbs.tsx

Does what it says on the box, see screenshots
N/A
None, isolated to IBC tokens
- IBC tokens breadcrumbs are working in account/asset pages
- IBC pool tokens breadcrumbs are working in account/asset pages
- ☝🏽 
- ☝🏽

fix: osmosis ibc tokens breadcrumbs

---

src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useIsTradingActive.tsx

We currently only guard against chain halted on the sell asset, this brings similar safety in case the pool for the buy asset is currently halted, resulting in trades being refunded.
N/A
None?
Note, LTC, BCH, and DOGE are currently halted as we speak
- We should still guard against pool halt on the sell asset for THOR trades
- We should now also guard against pool halt on the buy asset for THOR trades
☝🏽 
☝🏽

fix: buy asset trade halted on THOR swaps

---

package.json
src/state/slices/opportunitiesSlice/resolvers/idle/constants.ts
src/state/slices/opportunitiesSlice/resolvers/idle/index.ts
yarn.lock

Consumes the exposed `strategy` field and adds it to the base opportunities, so we can show the Idle strategy type https://github.com/shapeshift/lib/pull/1212
N/A
None
- Idle overview modal displays the current opportunity's strategy description
- ☝🏽 
- ☝🏽

feat: idle opportunity metadata tags

---

package.json
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/LpWithdrawCommon.ts
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/LpWithdrawReducer.ts
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Confirm.tsx
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx
yarn.lock

* fixes improperly-named field in Osmosis LP remove transaction
* depends on https://github.com/shapeshift/lib/pull/1214
closes #
Low risk
* From the Defi/Earn page, select an Osmosis pool in which you have already taken a position. If no position yet exists, deposit liquidity
* Execute a withdrawal and verify that the transaction is successful
* Make sure that this works on KeepKey in addition to Native/Keplr

fix: osmosis lp remove transaction

---

src/plugins/walletConnectToDapps/v2/WalletConnectV2Provider.tsx
src/plugins/walletConnectToDapps/v2/eventsManager/useWalletConnectEventsManager.ts
src/plugins/walletConnectToDapps/v2/hooks/useWalletConnectState.ts
src/plugins/walletConnectToDapps/v2/utils/CosmosRequestHandlerUtil.ts
src/plugins/walletConnectToDapps/v2/utils/EIP155RequestHandlerUtil.ts

Minor WalletConnect improvements I had stashed, but missed the main PR.
Relates to https://github.com/shapeshift/web/issues/3756
Minimal.
N/A
☝️ 
☝️
N/A

chore: small WalletConnect improvements

---

package.json
yarn.lock

Does what it says on the box, see https://github.com/shapeshift/lib/pull/1217
N/A
None
- Swaps to RUNE work
- ☝🏽 
- ☝🏽

fix: unrug THOR swaps to RUNE

---

package.json
src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts
src/features/defi/providers/cosmos/components/CosmosManager/Deposit/DepositReducer.ts
src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/WithdrawReducer.ts
src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositCommon.ts
src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositReducer.ts
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawCommon.ts
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawReducer.ts
src/plugins/arkeo/Arkeo.tsx
yarn.lock

~~⚠️  Blocked by https://github.com/shapeshift/lib/pull/1218~~
N/A
Theoretically, FOXy and Cosmos SDK might break.
Effectively, that was only used in the initial state, so we are 🛍️ 
- Clear your persisted store
- Ensure FOXy and Cosmos SDK (routing from DeFi earn/overview and account/asset pages and actual modals) show no regressions
- ☝🏽 
- ☝🏽

chore: remove TokenStaking DefiType

---

.github/workflows/bootstrap.yml
scripts/bootstrap-env.ts

feat: warn which invalid environment in bootstrap-env 

---

.github/workflows/cloudflare.yml
scripts/bootstrap-env.ts

See https://docs.github.com/en/actions/learn-github-actions/contexts#github-context - we are checking that the *target* (the branch we're merging to) is matching one of the valid branch, not that the `source` (the `head_ref` e.g the PR branch) is so.
closes #

fix: use github base_ref as GITHUB_BRANCH_NAME env var

---

.github/workflows/cloudflare.yml
scripts/bootstrap-env.ts

Use the source branch if there is no target branch.
N/A
Small
Release should deploy.
☝️ 
☝️
N/A

fix: release deployment

---

src/components/Approval/Approval.tsx
src/components/Trade/SelectAccount.tsx
src/components/Trade/SwapperProvider/swapperProvider.tsx
src/components/Trade/TradeConfirm/useFrozenTradeValues.tsx
src/components/Trade/TradeInput.tsx
src/components/Trade/hooks/useAccountsService.tsx
src/components/Trade/hooks/useAvailableSwappers.tsx
src/components/Trade/hooks/useFeesService.tsx
src/components/Trade/hooks/useFiatRateService.tsx
src/components/Trade/hooks/useGetTradeAmounts.tsx
src/components/Trade/hooks/useIsTradingActive.tsx
src/components/Trade/hooks/useReceiveAddress.tsx
src/components/Trade/hooks/useSwapper/useSwapper.tsx
src/components/Trade/hooks/useTradeAmounts.tsx
src/components/Trade/hooks/useTradeQuoteService.tsx
src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.tsx

Address feedback from @gomesalexandre in https://github.com/shapeshift/web/pull/3927#discussion_r1120901567 by returning the entire context object.
N/A
Minimal.
N/A
☝️ 
☝️ 
N/A

chore: return context from useSwapperState

---

src/components/Delegate/StakingOpportunities.tsx

Littlish cleanup, icons are now defined at resolver/metadata-level so we don't need all this jazz anymore
N/A
None if CI is happy
- Cosmos/Osmo staking opportunities in account/asset pages are still showing with the right validator icon

feat: cleanup <StakingOpportunities />

---

.github/workflows/bootstrap.yml
.github/workflows/cloudflare.yml

- ci: bootstrap target events and branches
- ci: target branches again
- ci: simplify
- ci: fix target branch name for pr and push events
- ci: debug context
- ci: ignore me empty pr
closes #

ci: ignore me ci testing

---

scripts/bootstrap-env.ts

this caused pain, hopefully it won't again.
n/a
none - docs only
no testing required
no testing required
no testing required

chore: comment script

---

src/App.tsx

- Allow users to dismiss the update toast
closes #
small risk
When you see the update toast notification you should be able to close it with the X button.

feat: allow dismiss of update toast

---

package.json
src/App.tsx
yarn.lock

fix: 0x swapper slippage (#3950)
feat: allow dismiss of update toast (#3957)

chore: release v1.227.0

---

src/state/migrations/010_clear_fox_farming.ts
src/state/migrations/index.ts

Migrates the `opportunitiesSlice` one more time to ensure clients aren't stuck in a weird broken state. Technically a feature that will help narrow down https://discord.com/channels/554694662431178782/1080979981326364703/1080979983360606268, though it *might* fix things if some clients are borked for that reason.
N/A
None, this is a migration
- ETH/FOX farming still shows up under overview/earn
☝🏽 
☝🏽

feat: clear fox farming migration

---

src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts

Another try at solving the ETH/FOX staking opportunity being missing for some users - shouldn't have user-facing diff for those who couldn't reproduce, but may solve it for the affected users.
Assumes ETH market data is fetched first and is more reliable
N/A
None, at worst this has no user-facing difference, at best this solves it
- ETH/FOX LP and staking opportunities are still displayed
- ☝🏽 
- ☝🏽

feat: get price from ETH instead of WETH in univ2 resolvers

---

src/assets/translations/en/main.json
src/features/defi/components/DefiActionButtons.tsx
src/features/defi/components/Overview/Overview.tsx
src/features/defi/components/Overview/UnderlyingAssetsTags.tsx

- Move the account selector above the overview header
- Wrap the buttons instead of stacking by default
- Wrap the underlying assets and rewards
closes #
no risk
On mobile sizes the buttons should wrap like the screenshots

fix: responsive account selector defi modal

---

src/assets/translations/en/main.json
src/features/defi/components/DefiActionButtons.tsx
src/features/defi/components/Overview/Overview.tsx
src/features/defi/components/Overview/UnderlyingAssetsTags.tsx

fix: responsive account selector defi modal (#3974)

chore: release v1.231.0

---

.env.base

* Activates osmosis lp feature flag in production environment
closes #
none
* Verify that Osmosis LP features are available in production environment.
* Verify that the KeepKey wallet load issue noted [here](https://github.com/shapeshift/web/issues/3976) is not still present.

feat: activate osmosis lp feature flag

---

.env.base

feat: activate osmosis lp feature flag (#3977)

chore: release v1.232.0

---

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx

Fixes the infinite overview flicker in both overview modals in case your
account 1 or + has a higher balance than your account 0
N/A
Highest balance logic might now get rugged - tested on my account 1
balance being the highest and it showed no regressions.
- Have a higher balance on your account 1 or more than on your account 0
- Ensure the account is still properly selected when opening the ETH/FOX LP
or staking modal
- ^
- ^

fix: eth/fox LP/staking infinite overview flicker

---

src/state/slices/opportunitiesSlice/types.ts

Gives us more reliable types, removing some that shouldn't be here at all, and makes others that were previously defined as optional, required.
N/A
None, if CI is happy we're happy
- CI is happy
- None

feat: improve EarnOpportunityType

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Approve.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx

- Use helper to track defi events
closes #
small risk

fix: use new helper for opportunity mixpanel events

---

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx

Fixes the routing to ETH/FOX farming from the Arkeo page, by not assuming `state.opportunity` is populated (it won't be when routing directing to deposit step, since the `SET_OPPORTUNITY` action is fired at overview step.
N/A
None
- Go to Arkeo page
- Ensure clicking ETH/FOX farming routes you to a working deposit step
- ☝🏽 
- ☝🏽

fix: eth/fox farming arkeo page routing

---

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Approve.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Confirm.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Status.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimStatus.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/WithdrawCommon.ts
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/WithdrawReducer.ts
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Approve.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Status.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx

Add the following events for mixpanel:
- Withdraw
- Deposit
- Claim
Also added an alert on claim when the user doesn't have enough gas to actually claim. Instead of just throwing some random generic error.
closes #
small risk
Test that claims work with and without enough gas.

feat: add mixpanel events for fox farming

---

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/DepositCommon.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/DepositReducer.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/FoxEthLpManager.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/WithdrawCommon.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/WithdrawReducer.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx

Second of many PRs following this bugfix: https://github.com/shapeshift/web/pull/3994
Storing the current opportunity as state was a leftover from previous implementations before we had a DeFi abstraction and could select an opportunity from state, and is highly bug prone, will break when e.g routing directly to deposit/withdraw.
N/A
- ETH/FOX LP might be broken, test accordingly
- ETH/FOX LP flow shows no regressions e.g steps crashing
- Account selection for ETH/FOX LP shows no regressions
- ☝🏽 
- ☝🏽

feat: remove ETH/FOX LP opportunity state

---

package.json
scripts/removeOutdatedTranslations.ts

A maintenance script for translations which removes translations from all the non-English translation JSON files for entries which have been modified in English since a specific Git revision.
The new and deleted English copies are ignored as they will be automatically handled by Gitlocalize, our translation platform.
It can be invoked with the command `yarn remove-outdated-translations`. A revision must be entered at the command prompt (it will usually be the last commit pushing all the translations to the app during the last update). Changes are then applied to the working copy, only after a preview of the affected JSON keys and a manual confirmation.
None.
If you want to test (it will mostly be used by the Globalization WS when preparing a new sync) it you can use this commit id: …

feat: translation maintenance script

---

src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/WalletProvider.tsx
src/hooks/useMixpanelPortfolioTracking/useMixpanelPortfolioTracking.tsx
src/lib/mixpanel/mixPanelSingleton.ts
src/lib/mixpanel/types.ts
src/state/slices/portfolioSlice/selectors.ts

* b74542840 feat: make shit nicer in mixpanel - human readable labels for reports
* 597ce9674 fix: use KeepKey name for KK while preserving custom label for UI - preserves user privacy by not leaking custom user labels which may include names
* 7197822ba fix: use numbers for values in anonymized portfolio - allows us to sum/filter data more easily in mixpanel
* e9dc27890 fix: separate out identify and wallet connection/portfolio loaded events - only identify once per page load
* bdc1ec5f9 feat: add wallet connection event - separate out wallet connection event from mixpanel instantiation
n/a
* mixpanel tracking only
* ensure this looks sane?
* keepkey with custom label should still be labelled correctly in wallet connection menu button

feat: mixpanel wallet changes

---

package.json
scripts/removeOutdatedTranslations.ts
src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/WalletProvider.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/WithdrawCommon.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/WithdrawReducer.ts
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx
src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx
src/hooks/useMixpanelPortfolioTracking/useMixpanelPortfolioTracking.tsx
src/lib/mixpanel/mixPanelSingleton.ts
src/lib/mixpanel/types.ts
src/state/slices/opportunitiesSlice/types.ts
src/state/slices/portfolioSlice/selectors.ts

feat: mixpanel wallet changes (#4018)
feat: translation maintenance script (#4019)
feat: add mixpanel events for fox eth lp (#4012)
fix: don't track demo wallet in mixpanel (#4015)
feat: add EarnOpportunityTypeBase (#4004)

chore: release v1.238.0

---

src/state/slices/opportunitiesSlice/resolvers/index.ts
src/state/slices/opportunitiesSlice/resolvers/osmosis/index.ts
src/state/slices/opportunitiesSlice/thunks.ts

Cleans up debug spew for Osmosis, consequently removing an unused resolver.
`osmosisLpUserDataResolver` was implemented following the pattern of `uniV2LpUserDataResolver` which itself is implemented for completeness and only fetch `allLpOpportunitiesUserdata` for ETH/FOX since the opportunity IDs are known ahead-of-time, but this doesn't apply to OSMO.
N/A
None, this is pretty much a chore since this this code was previously unused
- None

chore: cleanup osmosis log spew

---

src/components/Modals/FiatRamps/views/Overview.tsx
src/lib/mixpanel/types.ts

track the following payload for fiat ramp clicks
```
{
"action": "sell",
"assetId": "Bitcoin.BTC",
"ramp": "OnRamper",
}
```
closes #4041
minimal - tracking only
@reallybeard check this is appropriate
n/a

feat: mixpanel track fiat ramps

---

src/components/ReactTable/ReactTable.tsx

developer qol - fix gross console error
n/a
zero - `data-label` aren't user facing
ensure below screenshot doesn't happen
not testable by operations

fix: data table react error

---

src/lib/mixpanel/types.ts
src/plugins/foxPage/components/AssetActions.tsx
src/plugins/foxPage/components/DappBack.tsx
src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
src/plugins/foxPage/foxPage.tsx

Track events for
- Clicking opportunities
- Clicking coinbase
- Clicking dappback
- Toggle fox/foxy
closes #4040 

feat: add events for fox page

---

src/plugins/arkeo/FoxTokenHolders.tsx
src/plugins/arkeo/LpCards.tsx
src/plugins/arkeo/StakingCards.tsx

Following events:
- Track opportunity clicks
- Track trade eth/fox click
closes #4042 
no testing required - tracking only

feat: add arkeo page tracking

---

src/features/defi/providers/cosmos/components/CosmosManager/Claim/components/Confirm.tsx

Fixes cosmos claims currently borked in prod as spotted by bigly
@reallybeard
N/A
None?
- Cosmos claims should be great again
- ^
- ^

fix: unbork cosmos claims

---

src/AppProviders.tsx
src/lib/mixpanel/types.ts

- Fire an event when the app crashes
closes #

feat: track error boundary errors

---

src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx

Adds missing `assetNamespace` routing from FOX page, fixing the routing
to FOX farming modal
closes https://github.com/shapeshift/web/issues/4064
None
- Navigate to FOX page
- Click on "Manage" in the FOX farming opportunity
- Ensure the farming modal correctly opens
- ^
- ^

fix: fox page ETH/FOX staking routing

---

src/features/defi/providers/cosmos/components/CosmosManager/Claim/CosmosClaim.tsx
src/features/defi/providers/cosmos/components/CosmosManager/CosmosManager.tsx

Makes Cosmos SDK staking routes AccountId-agnostic so that #4073 can consume it and route to rewards step
N/A
Low/none, though we should sanity check the current claim logic still
claim from the selected account
- Click "Claim" from a given AccountId Cosmos SDK staking overview modal
- Ensure the claim step reflects the previously selected account
- ^
- ^

feat: route to Cosmos SDK staking without AccountId

---

package.json
src/lib/utils.ts
src/state/slices/assetsSlice/assetsSlice.test.ts
src/state/slices/assetsSlice/assetsSlice.ts
src/state/slices/portfolioSlice/portfolioSlice.test.ts
yarn.lock

**draft - wip**
- feat: wip makeAsset and upsertAsset
- test: better test
todo
currently, the asset service loads all assets from a statically generated file
as we pull in more data services, e.g. zerion/zapper/NFTs, we can't possibly have all supported assets at compile time, and need to upsert assets at runtime.
this is a POC with a utility function to generate assets from minimal data, such that they can be upserted.
n/a
reasonable - messes with asset service
* open for scrutiny
n/a

feat: asset slice upsert

---

src/components/Trade/Trade.tsx
src/components/Trade/TradeConfirm/TradeConfirm.tsx

This PR:
- ensures we don't `updateTrade(undefined)` on location change. If we go from trade to another route and back to trade, or if we go to the trade route, the `useEffect` will kick in either way, so setting it to `undefined` actually causes issues here
- moves the `if (!trade)` logic from the not-react-y throwing at component-level, to returning null `if (!trade)`, with the actual *error* handling now only happening `onSubmit`
Note that given something something SPA routing, this PR does *not* unmount and remount `<Trade />`. This is effectively consistent with all other routing we have, which is referentially stable and doesn't re-render components on the same routes. In other words, clicking "Trade" again won't reset the swapper.
closes …

feat: don't updateTrade(undefined) on location change

---

src/assets/translations/en/main.json

Add translations for `bep20` parser
https://discord.com/channels/554694662431178782/1087499423661178930/1087504202575642674
Low
- ensure approve and revoke display correctly for bep20 tokens
:point_up: 
:point_up:

fix: add bep20 translations

---

src/components/Trade/Trade.tsx

This fixes the swapper confirmed component currently returning null when going to another route, then back to `/trade`
N/A
This is swapper, so risks are never low - ensure swapper is still working as it should i.e actually rendering things
- Open the app to the default dashboard route
- Go to the trade page - don't interact with swapper
- Go back to dashboard (or to any route that isn't trade for that matter)
- Ensure you can continue the swapper flow all the way to confirmation
- Repeat the steps above while actually interacting with the swapper in step 2 (going to the confirm step without actually broadcasting a Tx is fine) as a sanity check
- ☝🏽 
- ☝🏽

fix: swapper confirmed state after location change

---

src/state/migrations/012_clear_opportunities.ts
src/state/migrations/index.ts

Hotfix unrugging opportunities after https://github.com/shapeshift/web/pull/4098
closes #

feat: clear opportunities migration

---

src/components/Layout/Header/Header.tsx

buy/sell has lived in the mobile footer for a long while now and this is redundant, assymmetric, and ugly.
n/a
basically zero - removing button from the mobile header
* see screenshots
* see screenshots
before
after

chore: remove buy button from mobile header

---

src/assets/translations/en/main.json
src/components/EarnDashboard/components/PositionDetails/StakingPositionsByProvider.tsx
src/components/EarnDashboard/components/ProviderDetails/StakingOpportunitiesByPosition.tsx

Discussed with big @reallybeard ed man and agreed the current naming looked off
N/A
None
- Additional char looks better

feat: rename "Reward Balance" to "Rewards Balance"

---

src/pages/Dashboard/Dashboard.tsx
src/state/slices/preferencesSlice/preferencesSlice.ts
src/test/mocks/store.ts

Two flags same effect - consoilidates them into one because why not
N/A
None, just a consolidation
- See previous PRs in the stack

feat: consolidate DashboardTabs and DefiDashboard flags

---

src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts

Adds some additional `rewardsCryptoBaseUnit` opt chain safety, which theoretically shouldn't be needed as we ran a migration, but users still seem to see "Oops" on first app load.
See https://discord.com/channels/554694662431178782/1088584656103932105/1088612352708071505 for reference.
N/A
None - worst case scenario the opt chain is useless
- Wait for this to be built and deployed in any of our envs
- Ensure you don't see "Oops" on first load of the new build
- Opt chain looks good
- ☝🏽

fix: oops on first app load

---

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Claim/ClaimConfirm.tsx

Fixes the routing from confirm to status step in FOX farming claims
closes https://github.com/shapeshift/web/issues/4126
None, we were using browser history instead of the memory router's history
- Claim FOX farming rewards
- You should be routed to the status step
- ☝🏽 
- ☝🏽

fix: fox farming claim status routing

---

package.json
src/components/Modals/Send/views/Address.tsx
src/lib/address/address.ts
src/lib/address/yat.ts
yarn.lock

y.at can map different addresses for different assets
this PR handles sends for USDC to a different address than other assets
see #4150 for a good description
closes #4150
medium - affects all sending
**see #4150 for testing steps with y.at addresses**
do a 0 value tx for the following
* ensure unstoppable domains still resolve
* ensure plain eth addresses still resolve
* ensure y.at addresses still resolve
* ensure sending USDC to the above yats resolve correctly (0 amount)
* ensure sending ETH to the above yats resolve correctly (0 amount)
* ensure btc addresses still resolve
as above
as above
n/a

feat: handle yat addresses for USDC

---

package.json
src/components/Modals/Send/views/Address.tsx
src/lib/address/address.ts
src/lib/address/yat.ts
yarn.lock

feat: handle yat addresses for USDC (#4153)

chore: release v1.257.0

---

src/components/EarnDashboard/components/ProviderDetails/LpPositionsByPosition.tsx
src/components/EarnDashboard/components/ProviderDetails/StakingOpportunitiesByPosition.tsx
src/components/Layout/Layout.tsx

fix: don't show empty errored chain names (#4166)
fix: add version to nested earn tables (#4163)

chore: release v1.259.0

---

package.json
src/hooks/useIsAnyApiFetching/useIsAnyApiFetching.tsx
src/state/store.ts
yarn.lock

Boimps RTK to latest RTK. See 1.9.0 breaking changes: https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.0
Also adds the recommended `autoBatchEnhancer`:
> RTK Query also can take advantage of the new "auto-batch enhancer" (described below) for some additional perf optimization, and we recommend adding that to your Redux store configuration.
N/A
Smallish, though a smolish sanity regression testing 
- Top-left app loading state is still working
- App is still doing its app things, including store persistence

feat: bump redux toolkit to latest

---

src/assets/translations/en/main.json
src/components/EarnDashboard/components/ProviderDetails/LpPositionsByAsset.tsx
src/components/EarnDashboard/components/ProviderDetails/ProviderDetails.tsx
src/components/EarnDashboard/components/ProviderDetails/StakingOpportunitiesByAsset.tsx
src/components/StakingVaults/DeFiEarn.tsx

renames by position to by asset on earn sections
n/a - debate/request
rename only
see screenshots
before
after

chore: rename by position to by asset

---

src/components/Layout/Main.tsx
src/pages/Trade/Trade.tsx

- In an effort to lower the cognitive load, i've centered the trade card and knocked the transactions below. Now the trade components is front and center.
- I've also removed the redundant breadcrumbs.
closes #

fix: center trade

---

src/state/slices/assetsSlice/selectors.ts
src/state/slices/assetsSlice/utils.ts

LLM generated description:
This PR refactors the selectFeeAssetByChainId and selectFeeAssetById selector functions to extract their business logic into separate pure functions. The new pure functions, getFeeAssetByChainId and getFeeAssetByAssetId, have been added to the utils.ts file.
The changes made in this PR include:
Create getFeeAssetByChainId and getFeeAssetByAssetId pure functions in the utils.ts file, with the specified function signatures and business logic from the original selector functions.
Update the selectFeeAssetByChainId and selectFeeAssetById selector functions in the selectors.ts file to use the new pure functions.
n/a - this has been pissing me off for a long time
minimal - biz logic extraction only
ensure fn sig changes are sane
n/a

chore: get fee asset refactor

---

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts

feat: remove days to break even on savers withdraw (#4195)
fix: thorchain savers deposit days to break even (#4194)

chore: release v1.267.0

---

public/index.html
react-app-rewired/headers/csps/InterFont.ts
src/components/Text/Text.tsx
src/state/slices/assetsSlice/selectors.ts
src/state/slices/assetsSlice/utils.ts
src/theme/theme.tsx

feat: add inter font (#4199)
chore: get fee asset refactor (#4198)

chore: release v1.268.0

---

src/components/AccountDropdown/AccountDropdown.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx
src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
src/components/Trade/TradeInput.tsx
src/features/defi/components/Deposit/PairDepositWithAllocation.tsx
src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx
src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx
src/features/defi/providers/idle/components/IdleManager/Deposit/components/Deposit.tsx
src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Deposit.tsx
src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
src/features/defi/providers/univ2/components/UniV2Manager/Deposit/components/Deposit.tsx
src/features/defi/providers/univ2/components/UniV2Manager/Withdraw/components/Withdraw.tsx
src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx
src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx
src/lib/swapper/LifiSwapper/getTradeQuote/getTradeQuote.ts
src/state/slices/common-selectors.ts
src/state/slices/opportunitiesSlice/resolvers/foxy/index.ts
src/state/slices/opportunitiesSlice/resolvers/idle/index.ts
src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
src/state/slices/opportunitiesSlice/resolvers/yearn/index.ts
src/state/slices/opportunitiesSlice/selectors/lpSelectors.ts
src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
src/state/slices/portfolioSlice/selectors.ts

https://github.com/shapeshift/web/pull/4204 brought the precision terminology instead of `human`, so might as well rename the `cryptoBalance/s` / `portfolioBalance/s` selectors to `baseUnit` for clarity.
N/A
None

feat: base unit terminology in portfolio selectors

---

src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts

these were the most recomputed selectors on page load, now they're not
n/a
extremely low - memoizes things that should have already been
trust me bruh
not testable by operations

perf: slightly better staking selector performance

---

src/components/EarnDashboard/components/ProviderDetails/NestedAsset.tsx
src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx
src/components/EarnDashboard/components/ProviderDetails/WalletLpByAsset.tsx
src/components/StakingVaults/DeFiEarn.tsx

- Fix syntax on subtext on join
- Make by provider default tab
- key on lp ops
closes #
small risk
Subtext for opportunities should only have a • separator if there is more than two labels

fix: syntax on join

---

src/components/List/NestedListItem.tsx

Fixes small overhang over the line
closes #

fix: overlap on asseticons in defi provider view

---

packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts

Manually re-applied diff from
https://github.com/shapeshift/lib/pull/1235 after monorail. Refer to the
description in the lib PR for more info.
closes #

fix: isQuoteSellAmountBelowMinimum

---

packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts

fix: isQuoteSellAmountBelowMinimum (#4220)

chore: release v1.271.0

---

scripts/removeOutdatedTranslations.ts

Adds missing typing for a function in the TypeScript used to manually invalidate the translations. The script cannot run without it since 1e3429b18e91bf61f235c59c46c2134626e44012
- [ x Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
None.
No testing required.

fix: invalidated translations script typing

---

yarn.lock

housekeeping
n/a
none - dev QoL only
see `yarn.lock`

chore: update caniuse db

---

src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawCommon.ts
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawReducer.ts
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx

tl;dr we assumed that the approval step was not needed for FOXy and removed the components, but it *may* be needed in some specific cases, to send back the reward FOXy back to the staking contract to be able to withdraw the full balance, see:
https://github.com/shapeshift/yieldies/blob/b61e2ca12425488fc437bd1931d8ed6fbfa1bf16/src/contracts/Staking.sol#L489
Reverts the `<Approve />` and related hunks of b1b226cc27e143c9c87a7c2d1d5a6bec358ad114 to bring the approval flow back.
closes #4238
- Test with Frame watch-only user account in #4238
- Ensure you see an approval step for FOX *with this specific account* (none of my own actually needed an approval here)
- Unfortunately, unless you need an approval on one of your own accounts for which you're a signer, it is impossible to test the full …

feat: bring back FOXy approve

---

src/plugins/foxPage/foxPage.tsx

The current amount was turbo wrong, we were showing the FOX wallet balance, vs. the FOXy earn opportunity balance in the FOX page.
relates to https://github.com/shapeshift/web/issues/4238
None
- Go to the FOX Page
- FOX staking amount is matching the amount you see after opening the modal

fix: fox page FOXy balance

---

src/components/Trade/hooks/useAvailableSwappers.tsx

Currently, when triggering a cached query, we are not updating the swappers/quote.
This is caused by logic designed to prevent a race condition.
Unfortunately, whilst the logic _does_ fix the race condition, it also treats cached queries as "stale" and does not update the state.
This PR adds a check to see if we already have the result of the request in the cache, and if we do, we are ok to update the swapper and quote (negligable liklihood of a race condition occurring when accessing local state).
N/A - prod bug
Small - logic confined to setting quotes. If they are set properly for both cached and non-cached quiries, this should be ok.
- Input an amount for any trade pair, see that you get a result.
- Input another amount, see that you get a result.
- Re-enter the initial amount and …

fix: handle stale cached RTK queries
