shapeshift/web

src/context/WalletProvider/NativeWallet/NativePasswordRequired.tsx, src/context/WalletProvider/WalletViewsSwitch.tsx
closes #35 
when reconnecting a wallet after refreshing a browser it would initialize the wallet but not actually add it to the state in the context - this adds it to the state so it's actually available in the hook
1. import/create a wallet
2. refresh the page
3. enter your password
4. wallet should be available from `useWallet` hook
=> Reconnect native wallet correctly

src/context/WalletProvider/KeepKey/PinModal.tsx
closes #28 
Add key to pin modal btns
Open KK pin modal no error in console
=> Add key to pin modal

src/components/Modals/Send/views/Address.tsx
Use the correct chain adapter for address validation. This fixes it in 99% of cases.
There are 2 edge cases it doesn't work for but its fine because hdwallet and / or unchained also fail for these:
1) Mixed case eth addresses that are not in checksum format fail.  Theres no reason we shouldn't be able to send to mixed case eth
2) mixed case bc1 addresses don't work. according to internet it should be fine.
Fixing these 2 cases would mean adding to our validation code and also changing unchained & hdwallet. Does not seem necessary at this time
=> fix: address validation

src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx, src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
- Use get feeData instead of buildSendTransaction to estimate fees.
- Make it work with new btc specific fee data from lib
- Depends on this pr: https://github.com/shapeshift/lib/pull/190
https://github.com/shapeshift/web/issues/215
This is part 1 of a series of PR's to clean up how to handle fees
=> fix: fees part1 cleanup

src/assets/translations/messages-en.json, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/lib/math.ts
Small changes to translate tooltips in TradeConfirm component. 
Refactor `onFinish` in useSwapper.ts to use `bnOrZero` 
2. etc...
=> fix: translate tooltips; refactor to use bnOrZero

src/context/WalletProvider/WalletViewsSwitch.tsx
On connect wallet modal, allow to select the same wallet option after clicking on back arrow
closes #112 
2. Run `yarn dev`
3. Select "Connect Wallet"
4. Select "Shapeshift"
5. Press back button on connect wallet modal
6. Try to select "Shapeshift" again.
=> fix: allow to select same wallet option after back

src/components/Modals/Send/TxFeeRadioGroup.tsx, src/components/Modals/Send/views/Confirm.tsx, src/components/Transactions/TransactionRow.tsx
fix: dynamic asset precision and use 6 instead of 4 decimals small btc amounts dont show as 0
=> fix: dynamic asset precision and use 6 instead of 4 decimals small btc amounts dont show as 0

src/assets/translations/messages-en.json, src/components/Icons/KeepKeyIcon.tsx, src/components/Layout/Header/NavBar/WalletButton.tsx, src/context/WalletProvider/WalletViewsSwitch.tsx
Fixes the state management issue that was preventing the "Connect Wallet" modal from allowing a user to go back and pick the same wallet again from the list.
Fixed missing transactions in Connect Wallet menu
Removed non-functional placeholder icons in the Connect Wallet menu
closes #112
1. Click Connect Wallet
2. Click ShapeShift
3. Enter a password
4. Click Back twice
5. At the Select Wallet modal, select ShapeShift again.
If fixed, you go to the password screen. If not fixed, nothing happens.
=> fix: fix the "Connect Wallet" modal not working after clicking "Back"

src/jest/mocks/store.ts, src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx, src/pages/Assets/hooks/usePriceHistory/usePriceHistory.test.ts, src/pages/Assets/hooks/usePriceHistory/usePriceHistory.ts, src/state/slices/marketDataSlice/marketDataSlice.tsx
* modifies the usePriceHistory hook to support fetching multiple assets at once as an array of caip19s
* persists price history in market data in the store rather than locally in the hook
* price data is segmented by timeframe (according to charts) then indexed by caip19 (asset ids) - see screenshot below
this was needed in the store as a prerequisite to balance chart data
closes #351 
1. load an asset
2. look in the store for asset data
=> feat: fetch batch priceHistory

sample.env, src/Routes/PrivateRoute.tsx, src/config.ts, src/pages/ConnectWallet/ConnectWallet.tsx
Retain the route the user was trying to navigate to as a query param so if they refresh/connect a wallet we can take them to the correct page.
closed #353 
2. etc...
=> fix: keep the route when we redirect to connect wallet

src/context/WalletProvider/NativeWallet/components/NativePassword.tsx, src/context/WalletProvider/NativeWallet/components/NativePasswordRequired.tsx
Autogenerated input field id does not work with some password managers.
Force a proper _password_ id for the password field.
closes #344 
I tested with `Bitwarden` and it works.
According to the documentation it should also work with `1password` and `lastpass`.
=> fix: make password modal work with password managers

src/config.ts
Make the HIDE_SPLASH environment variable have a default value of `false`. Without this, vercel crashes for not having the correct environment variables.
=> fix: make HIDE_SPLASH have a default value of false

src/context/WalletProvider/WalletProvider.tsx
When closing the modal, the 'initialRoute' value wouldn't change, so when you open the modal again, clicking a button for the same wallet wouldn't change the state value so the useEffect hook wouldn't fire and show the expected component
closes #387
=> fix: connect a wallet modal state issue after closing

src/lib/math.ts
- Add rounding down to `fromBaseUnit` by default. This fixes an issue with send max rounding the values up and failing because the amount is greater than the balance.
2. etc...
=> fix: fix trade max button rounding issue

src/context/WalletProvider/KeepKey/components/Success.tsx, src/context/WalletProvider/MetaMask/components/Success.tsx, src/context/WalletProvider/Portis/components/Success.tsx, src/hooks/useBalanceChartData/useBalanceChartData.ts, src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts, src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx, src/pages/Assets/AssetDetails/AssetHistory.tsx
- fix: translations on wallet pairing
- fix: add wallet to useBalanceChartData effect to fetch assets and market data on wallet switch
- fix: no white screen of death for metamask on bitcoin
- feat: useWalletsSupportsChain hook, hide send/receive, account type buttons, and tx history on bitcoin if metamask or other non btc wallet connected
=> fix: translations, bitcoin/metamask

src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
fix: correctly pair a ShapeShift wallet if it's already initialized (unlocked, decrypted)
=> fix: correctly pair a ss wallet if it's already initialized

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInput.tsx
- Fix trade rate tooltip
closes #411 
2. etc...
=> fix: fix rate tooltip

src/components/Modals/Send/hooks/useSendFees/useSendFees.test.tsx, src/components/Modals/Send/hooks/useSendFees/useSendFees.tsx
If the token asset being sent was different than the chain asset used to calculate fees, then the estimated fees were grossly overshown.
2. etc...
=> fix: fixed bug where token precision differed with chain asset precision

src/components/AssetSearch/AssetSearch.tsx, src/components/AssetSearch/selectors/marketCapLoadingStatus/marketCapLoadingStatus.ts, src/hooks/useBalanceChartData/useBalanceChartData.ts
- fix: sort assets by market cap but don't overfetch
- fix: dont fail calculating balance charts if portfolio asset is not loaded
- chore: market cap loading status hook
=> fix: sort assets market cap

package.json
Also fixes a Validation error because `collectCoverageFrom` can't be null, apparently
=> chore: for yarn test, turn off watch mode except for test:dev

src/context/TransactionsProvider/TransactionsProvider.tsx, src/state/slices/preferencesSlice/preferencesSlice.ts
chain-adapters was updated to require `accountType` for `subscribeTxs` and we were missing it
Change default BTC account type to SegwitNative
=> fix: subscriptions needs accountType

src/hooks/useBalanceChartData/useBalanceChartData.ts
i suspect if a pending tx comes in after the balance chart has rendered, we're trying to put it in a time bucket of the chart in the future that doesn't exist and everything explodes with a white page.
this will stick it in the last bucket. charts may be slightly wrong but it won't crash the app.
2. etc...
=> fix: don't make balance charts explode on pending txs

src/assets/translations/messages-en.json, src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess.ts
Use the StorageManager API, if present -- which it is, everywhere but Safari -- to prompt the user to enable persistent storage for native wallet vaults.
=> feat: prompt user to enable persistent storage

src/pages/Earn/components/VaultList.tsx
Vaults with a historical balances were showing in the Earn overview page even if their current balance was 0.
closes #442 
2. etc...
=> fix: filter out vaults with 0 balance from list

headers.js
This relaxes the `Cross-Origin-Opener-Policy` from `same-origin` to `same-origin-allow-popups` so that Portis's `penpal` package can talk to its popup window.
=> fix: disable COOP for popups to fix portis

headers.js, public/index.html, react-app-rewired.config.js
This will silence the console warning that the `frame-ancestors` directive isn't allowed in meta tags.
=> fix: support different CSPs in meta and headers

package.json, scripts/postinstall.sh, yarn.lock
yarn-minify will hoist sub-dependencies when semver matches but yarn didn't hoist them.
See: https://www.npmjs.com/package/yarn-minify
See: https://github.com/yarnpkg/yarn/issues/4986
> This is a tool for "minifying" a yarn.lock file, in the sense of eliminating unnecessary use of old versions of packages.
> It can be used to work around yarn's inability to upgrade indirect dependencies, for example.
=> chore: add yarn-minify to help solve dependency issues

src/components/Trade/TradeConfirm/TradeConfirm.tsx
Add the asset amount in the miner fee (addition to fiat value already displayed)
closes #391
=> feat: add asset value in miner fees

react-app-rewired.config.js
Different build environments may import environment vars in different orders. This leads to non-determinism in the build, because the bundles contain webpack DefinePlugin output in different orders.
=> fix: sort REACT_APP env vars so build is deterministic

src/components/Modals/Receive/ReceiveInfo.tsx
Remove verify button on native wallet
closes #461 
Connect with wallet other than native:
1. Click on _receive_ button from any asset page
2. The _verify_ button is displayed
Connect with native wallet:
1. Click on _receive_ button from any asset page
2. The _verify_ button is **not** displayed
=> chore: remove verify button on native wallet

package.json, src/lib/polyfills.ts, yarn.lock
Missing polyfills broke the app on safari based browsers
closes #488 
2. etc...
=> fix: add missing polyfills

src/assets/translations/messages-en.json, src/components/AccountCard.tsx, src/components/Amount/Amount.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/Modals/Send/views/Address.tsx, src/components/Modals/Send/views/Details.tsx
- Added an account card that shows balance also allows you to go switch the asset
- Disable next button when address is invalid
closes #500 
2. etc...
=> feat: balance on send modal

src/hooks/useHasAppUpdated/useHasAppUpdated.ts
we made changes to make static assets be served by absolute urls rather than static
this actually simplifies the logic checking the main.js file in the dom vs from `asset-manifest.json` on the server
=> fix: fix app updater hook

src/components/AssetSearch/AssetSearch.tsx
- fixes app crash when a user presses the enter button while using asset search.
closes #495 
2. etc...
=> fix: fix asset search crash on enter press

src/components/Modals/Send/Form.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/Modals/Send/views/Details.tsx
- Add getFees call in handleInputChange and debounce
- set the fees on every input change and Validate that (balance-fee > sendAmount)
- no longer set the fees on clicking next.
- Got rid of the validateCryptoAmount and validateFiatAmount amount validators because we would need to redundantly do a debounced getFees call + logic there as well to correctly validate them.  The error message & disabled button is now only based on the amountFieldError string that gets set in handleInputChange
=> fix: calculate and validate fees on handleInputChange

src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx
Use proper format for fiat in asset header
closes #497
=> fix: use proper format for fiat in asset header

.eslintrc, package.json, yarn.lock
Symtom: eslint errors when running `yarn dev` and not `yarn lint`
chore: fix eslint duplicate plugins conflicting
=> chore: fix eslint duplicate plugins conflicting

package.json, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Transactions/TransactionRow.tsx, src/hooks/useBalanceChartData/useBalanceChartData.ts, src/lib/txs.ts, src/pages/Assets/AssetDetails/AssetHeader/SegwitSelectCard.tsx, src/pages/Assets/AssetDetails/AssetHistory.tsx, src/pages/Dashboard/RecentTransactions.tsx, src/state/slices/txHistorySlice/txHistorySlice.test.ts, src/state/slices/txHistorySlice/txHistorySlice.ts, yarn.lock
* adopts best practises from here https://redux.js.org/usage/structuring-reducers/normalizing-state-shape#designing-a-normalized-state
* transaction rows now accept id and look up transaction data themselves
* this kind of abuses indexes for filters, but i want to keep this PR smol and write more efficient filter selectors later
2. etc...
=> chore: refactor tx history state slice

src/components/AccountRow/AccountRow.tsx, src/components/AssetSearch/selectors/selectAndSortAssets/selectAndSortAssets.test.ts, src/components/AssetSearch/selectors/selectAndSortAssets/selectAndSortAssets.ts, src/components/Modals/Send/Form.tsx, src/components/Modals/Send/hooks/useAccountBalances/useAccountBalances.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/Modals/Send/hooks/useSendFees/useSendFees.tsx, src/components/StakingVaults/StakingVaultRow.tsx, src/components/Transactions/TransactionRow.tsx, src/features/earn/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx, src/features/earn/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx, src/hooks/useAsset/useAsset.tsx, src/hooks/useFetchAsset/useFetchAsset.tsx, src/hooks/useMarketData/useMarketData.tsx, src/jest/mocks/store.ts, src/pages/Assets/Asset.tsx, src/pages/Assets/AssetCards/UnderlyingToken/UnderlyingToken.tsx, src/pages/Dashboard/components/AccountList/AccountList.tsx, src/pages/Dashboard/helpers/sortByFiat/sortByFiat.ts, src/pages/Dashboard/hooks/useTotalBalance/useTotalBalance.test.tsx, src/pages/Dashboard/hooks/useTotalBalance/useTotalBalance.ts, src/pages/Earn/components/StakingCard.tsx, src/pages/Earn/components/VaultList.tsx, src/pages/Earn/hooks/useVaultBalances.tsx, src/state/slices/assetsSlice/assetsSlice.test.ts, src/state/slices/assetsSlice/assetsSlice.ts, src/state/slices/marketDataSlice/marketDataSlice.test.ts, src/state/slices/marketDataSlice/marketDataSlice.tsx
TODO: test trade before merging
we can now deal with assets, market data, price history data, market cap, all purely by caip19. we can currently do txs by caip19 in a hacky way that will be fixed soon upstream in unchained.
* normalizes assets in store
* normalizes market data in store
* allows us to join asset, market, and transaction data efficiently by a single id (caip19)
* stops the `chain ?? tokenId` insanity throughout the view layers
close #530
this will require a full regression test as it covers all aspects of web, especially yearn bits
=> chore: normalize assets and market data in store

src/components/TokenRow/TokenRow.tsx, src/components/Trade/TradeInput.tsx, src/features/earn/components/Deposit/Deposit.tsx, src/features/earn/components/Withdraw/Withdraw.tsx
It fix all inputs because the formatting didn't had isNumericString enabled which as the documentation says "If value is passed as string representation of numbers (unformatted) then this should be passed as true" which is our case.
closes #554
No special yet
=> fix: all input works regarding the language used

package.json, yarn.lock
chore: upgrade bignumber.js to 9.0.2
Changelog has 1 irrelevant bugfix and a change that may reduce the bundle size.
=> chore: upgrade bignumber.js to 9.0.2

src/Routes/PrivateRoute.tsx, src/Routes/Routes.tsx, src/assets/translations/messages-en.json, src/components/Layout/Header/NavBar/UserMenu.tsx, src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts, src/pages/ConnectWallet/ConnectWallet.tsx
Hardware wallets can be paired but also disconnected (unplugged).
This allows us to use paired wallets for which we've already gotten the PublicKeys (for showing asset balances and transaction history) but which have been unplugged after pairing.
If a paired device (KeepKey) gets unplugged, show a warning icon in the wallet menu. When a device is reconnected, remove the warning.
**Possibly incomplete** There may be other places in the code than this that assume when `WalletProvider.state.isConnected` is `false` that there isn't a pair wallet. We should be using `WalletProvider.state.walletInfo` to determine if a wallet is *paired* and `isConnected` just to determine if we can talk to it right now or not. …
=> feat: support wallets in "disconnected" state

src/context/WalletProvider/KeepKey/components/Connect.tsx, src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts, src/pages/Assets/AssetDetails/AssetHistory.tsx
* feat: Show the device's label in the WalletButton
* fix: improved connect event handling
closes #600
1. Connect a KeepKey
=> feat: show device label in the WalletButton

package.json, scripts/sha256sums.sh
This generates a SHA256SUMS file after building a production version that can be easily used to detect changes in build products via `sha256sums -c SHA256SUMS`. As we hone in on deterministic builds, this is a good first step to enable tools that people can use to verify the integrity of production code.
Also, dumps the hashes to the console so CI build logs will record them.
=> feat: generate SHA256SUMS on build

package.json, react-app-rewired.config.js, scripts/verifyWebpackHashes.sh, src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx, src/components/Trade/hooks/useSwapper/useSwapper.test.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx, src/context/WalletProvider/WalletProvider.test.tsx, src/hooks/useHasAppUpdated/useHasAppUpdated.ts, src/hooks/useRefCallback/useRefCallback.test.tsx, yarn.lock
Good news: closes #589, closes #605, closes #549
Bad news: Webpack 5 dropped support for node polyfills; note https://github.com/facebook/create-react-app/issues/11756, which basically says "whatever, not our problem" about it. Now we have to provide our own. Webpack can detect all the modules that need to be included, but ops testing will be needed to discover if any errors are triggered by modules which are using any more Node globals.
=> chore: upgrade to create-react-app 5

package.json, react-app-rewired.config.js, src/env/env.json, src/env/loader.js, src/env/process.js, yarn.lock
CRA uses Webpack's DefinePlugin to inject process.env vars by literally replacing the string `process.env` with `{"REACT_APP_FOO":"foo","REACT_APP_BAR":"bar"}` everywhere it finds it. (As in, `process.env.REACT_APP_FOO` becomes `{"REACT_APP_FOO":"foo","REACT_APP_BAR":"bar"}.REACT_APP_FOO` everywhere!)This is highly duplicative, but it also means that the hash of any chunk which includes any process.env env var changes each time any env var changes, and is a constant PITA for deterministic builds.
This uses some Webpack magic to collect the env vars CRA _would_ have injected, emit them as `/env.json`, and load that file at runtime. The env vars are injected into the `process` polyfill, which is then frozen to prevent shenanigans.
Note that the generated `env.json` file will _not_ protected …
=> feat: load env values from separate json file

headers.js, package.json, public/index.html, react-app-rewired.config.js, src/env/env.json, src/env/loader.js, src/env/process.js, yarn.lock
This uses the `webpack-subresource-integrity` plugin to add Subresource Integrity (SRI) attributes to everything. This includes all the `<script>` and `<link>` tags in the HTML, as well as the webpack async loader in `runtime-main.js`. After this change, the hash of `index.html` should implicate all other assets in the build (except for metadata like `manifest.json`, `asset-manifest.json`, and `robots.txt`).
It's possible that this may be useful as the basis for a runtime-verifiable signature scheme in the future.
=> feat: generate SRI attributes for all assets

src/assets/translations/messages-en.json, src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx, src/context/WalletProvider/NativeWallet/components/NativePassword.tsx, src/context/WalletProvider/NativeWallet/components/NativeRename.tsx
Add validation logic to Native Wallet name (aka nickname).
When both creating and renaming a Native Wallet:
- Set a maximum length of 64 characters for the name
- Show an error if the user inputs more than 64 characters and disable the Next button
When renaming a Native Wallet:
- If the length of the name is "0", display a confirm dialog to confirm the deletion of the name
- If confirmed, the name meta property is deleted
- If cancelled, we stay on the form
:nail_care: minor improvements of the UI of NativeLoad when we have several wallets with various name lengths.
:shield: the `name` field is only displayed through a `RawText` component (basically a wrapped chakra-ui `Text` component). I don't think there is an opportunity for HTML injection. I will be happy to modify something with …
=> chore: add validation logic to Native Wallet name

src/assets/translations/messages-en.json, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts
- This handles web3 client rejections of swaps, with a better error message. Before/After:
`Something went wrong - Insufficient funds for miner fee and amount` -> `"Something went wrong - User has rejected the transaction"`
- A new property `transactionRejected` was added, since we still want to handle the existing `"Insufficient funds for miner fee and amount"` error message - swapper not only returns errors on web3 client calls, but also on e.g XHRs to  `https://api.0x.org/swap/v1/quote`, in which case the error message is perfectly valid.
closes #638
- In `/dashboard`, get a quote
- Preview trade
- Confirm and Trade
- On metamask popup, reject transaction
=> feat: improve error message on transaction rejected by user

src/hooks/useFetchAssetDescription/useFetchAssetDescription.ts, src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx
fixes regression where asset descriptions aren't showing because i broke them
closes #681
- go to asset page
- description should appear
=> fix: bring back asset descriptions

src/hooks/useAccountSpecifiers/useAccountSpecifiers.ts, src/pages/Assets/Asset.tsx
fix: show correct BTC balance in portfolio and asset pages
fix: infinite loop in `useAsset` hook
closes #648 
1. Connect a KeepKey with a BTC balance
2. Go to the Assets page
=> fix: show correct BTC balance in portfolio and asset pages

src/hooks/useHasAppUpdated/useHasAppUpdated.ts, src/lib/utils.ts
I've applied desired changes to useHasAppUpdated hook:
- Save asset-manifest.json on page load 
- Use isEqual lodash function for deep object equality check on useInterval to update flag if applies
closes #634
closes #634
1. Pull branch locally and run it as usual
=> fix: fix useHasAppUpdated hook to cache asset-manifest.json 

src/assets/translations/messages-en.json, src/components/Trade/TradeInput.tsx, src/context/WalletProvider/NativeWallet/components/NativeCreate.tsx, src/context/WalletProvider/NativeWallet/components/NativeImport.tsx, src/features/earn/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
See issue #707 
1. (Copy )Update error messaging to"Enter your seed phrase with a single space in between words. Omit any commas, returns, or any additional characters. "
2. (Copy) Remove the title copy that says "Something went wrong"
3. (Copy) Update copy to "Allow ShapeShift DAO Router to spend your [ASSET NAME]"
4. (Copy) Replace 'View My Position' with 'View Transaction' (while pending) on Yearn withdrawal modal.
5. (Copy) Change any instance of "Backup Seed phrase", "backup phrase", or "seed phrase" to "Secret Recovery Phrase" throughout all pages of the above JSON file for V2
6. (Copy) Update "Withdraw amount" to "Withdrawal Amount"
7. (Copy) Update "Withdraw From" to "Withdrawal From"
I didn't change the point 8 as the _Reward Value_ in active opportunities has already been …
=> chore: translation copy changes

src/pages/Assets/AssetDetails/AssetHeader/AssetHeader.tsx
closes https://github.com/shapeshift/web/issues/705
I verified that there is no regression for en-US localization.
1. Reproduced bug
2. Found place to fix
3. Checked NumericFormat component possible options
4. Compared with others NumericFormat usage in the app
5. Fix and test
6. Check no regression for en-US localization
=> fix: asset price chart for french localization

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/state/slices/portfolioSlice/portfolioSlice.ts
after i refactored everything i ignored using account types for bitcoin. the send modal was looking at the portfolio balance for bitcoin - aggregated across all account types. this would try and create sends from the selected account type where a user may not have a balance, causing txs to fail.
- [?] Do all new and existing tests pass? Does the linter pass?
1. go to the bitcoin asset page with a wallet with bitcoin
2. click the send button
3. ensure the that balance displayed in the send modal is the same as the balance that you have for that account type
n/a
=> fix: bitcoin sends respects account types

src/assets/translations/messages-en.json, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/types/object.ts
This handles thrown `ZrxExecuteQuote` swap errors. Here are their messages in `@shapeshiftoss/swapper`: 
- [`ZrxSwapper:ZrxExecuteQuote Cannot execute a failed quote`](https://github.com/shapeshift/lib/blob/ca9e1b5ab18996f222dabd487835a9ab4b7b818a/packages/swapper/src/swappers/zrx/ZrxExecuteQuote/ZrxExecuteQuote.ts#L14)
- [`ZrxSwapper:ZrxExecuteQuote sellAssetNetwork and sellAssetSymbol are required`](https://github.com/shapeshift/lib/blob/ca9e1b5ab18996f222dabd487835a9ab4b7b818a/packages/swapper/src/swappers/zrx/ZrxExecuteQuote/ZrxExecuteQuote.ts#L19)
- [`ZrxSwapper:ZrxExecuteQuote sellAssetAccountId is required`](https://github.com/shapeshift/lib/blob/ca9e1b5ab18996f222dabd487835a9ab4b7b818a/packages/swapper/src/swappers/zrx/ZrxExecuteQuote/ZrxExecuteQuote.ts#L24)
- …
=> feat: handle ZrxExecuteQuote swapper errors

react-app-rewired.config.js
This is a quick-fix for some kind of hot module reloading regression introduced by #616. It's massive overkill, but it works. I've been fighting this all day and have not been able to narrow down what's actually busted because I can't reliably reproduce the issue -- or reliably reproduce _not_ having the issue. But even though my working tree is apparently cursed, this should unblock people until we can narrow it down properly.
=> fix: unbreak hot module reloading

src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
- fixes aggregate asset balances by upserting and summing in the portfolio reducer, previously the last account to come in would stomp on the previous asset balance
- simplifies logic in account to portfolio mapping for bitcoin, pulling account balances from top level of responses rather than aggregating address balances
#730
1. have a bitcoin wallet with balances across multiple account types, i.e. legacy/segwit/segwit native
2. the asset balance on the dashboard should be the sum of all account types
3. verify against beta.shapeshift.com or another wallet
n/a
=> fix: aggregate asset balance across account types correctly

src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
- Add `selectPortfolioCryptoHumanBalancesByFilter` to show human readable crypto balance by assetId or assetId and accountId. AssetId is also required now for `selectPortfolioFiatBalancesByFilter`.
- Fix issue where assetBalances did not aggregate balances across multiple accounts.
2. etc...
=> feat: add selectPortfolioCryptoHumanBalancesByFilter

package.json
Fixed script to link and to unlink packages. I work with **Ubuntu 20.04** and **zsh**. `find` command uses `-maxdepth` to set the max depth of folders. `depth` does not accept parameters.
From `man find`:
```shell
Global options
Global  options affect the operation of tests and actions speci‐
fied on any part of the command line.  Global options always re‐
turn  true.   The  -depth option for example makes find traverse
the file system in a depth-first order.
[...]
-maxdepth levels
Descend at most levels (a non-negative integer) levels of directories below the starting-points.  -maxdepth 0 means only apply the tests and actions to the starting-points themselves.
```
NA
Before the fix:
```shell
❯ yarn …
```
=> chore: fixed script to link and to unlink packages

sample.env, src/config.ts, src/context/WalletProvider/MetaMask/components/Connect.tsx
Instead of hardcoding it in `REACT_APP_METAMASK_DEEPLINK_URL`, calculate the MM deeplink URL from `window.location`. This ensures that non-prod branches don't get redirects to prod by accident.
=> fix: metamask on mobile should always go to the right place

src/hooks/useBalanceChartData/useBalanceChartData.test.ts, src/state/slices/txHistorySlice/txHistorySlice.test.ts, src/state/slices/txHistorySlice/txHistorySlice.ts, src/state/slices/txHistorySlice/utils.test.ts, src/state/slices/txHistorySlice/utils.ts, src/test/mocks/txs.ts
When using `txHistory.byAccountId` and `txHistory.byAssetId`, the return values should be sorted by block time
closes #729
=> fix: sort txHistory when using byAccount and byAsset

src/components/AssetHeader/AssetHeader.tsx, src/hooks/useFetchAssetDescription/useFetchAssetDescription.ts, src/pages/Accounts/Accounts.tsx, src/state/slices/assetsSlice/assetsSlice.ts
on clicking an asset from the left sidebar we'd infinitely dispatch fetching asset descriptions
this uses RTK query's fancy exported hooks to avoid an infinite render
also adds a key to stop react whinging
n/a
1. click on assets from the *left sidebar*
2. asset should load without crashing app with a white screen
n/a
=> fix: fix infinite render clicking asset list

src/components/AssetAccounts/AssetAccountRow.tsx, src/hooks/useHasAppUpdated/useHasAppUpdated.ts, src/state/slices/portfolioSlice/utils.test.ts, src/state/slices/portfolioSlice/utils.ts
- feat: wire up crypto balance on account row
- feat: add labels to accounts
- fix: stop showing app updated locally
closes #687
1. account rows should crypto balance and address or account type (see below)
2. app has updated notification won't appear during development
=> feat: asset account crypto balance

src/components/AssetHeader/AssetHeader.tsx
**Component Change** : 
AssetHeader Component 
**Problem**: 
when Select **Price** to **Balance** and vice versa.We got error Warning: `Cannot update a component (`BalanceChart`) while rendering a different component (`AssetHeader`). To locate the bad setState() call inside `AssetHeader`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render at AssetHeader `
**Root Cause**
The problem is when BalanceChart component queues an update in AssetHeader component, while the AssetHeader is rendering.
Explain when you select **Balance** the **BalanceChart** is render but during render **BalanceChart** call the function **setPercentChange** for update **percentChange** and then AssetHeader is re-render and BalanceChart update when
percentChange prop update. 
I add a …
=> fix: cannot update a component console warning

src/components/AssetHeader/AssetHeader.tsx
use balance charts on account pages, price chart on asset pages by default
closes #762
1. go to account page, should default to balance chart
2. go to asset page, should default to price chart
=> fix: use balance on accounts, price on assets, format balance correctly

src/components/TxHistory.tsx, src/state/slices/preferencesSlice/preferencesSlice.ts, src/state/slices/txHistorySlice/txHistorySlice.ts
- feat: tx history selector by asset id and account ids filter
- chore: delete unused account types by chain selector
- chore: delete dead selector hack
closes #752
1. go to an asset, it should should all tx's related to that asset
2. go to an account, it should show all tx's related to that account
3. go to an asset account, it should show only tx's related to that asset and account
do it live
=> feat: tx ids by account id

src/components/AssetAccounts/AssetAccountRow.tsx, src/components/AssetHeader/AssetHeader.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
- chore: rename selector to singular balance
- feat: use fiat balance by filter on asset header
closes #772
1. go to asset page, should show aggregated balance across all accounts
2. go to asset account page, should show account balance for asset
n/a
=> feat: balance by account

src/components/Modals/Receive/ReceiveInfo.tsx, src/state/slices/portfolioSlice/utils.ts
accountIdToAccountType throws an error if it can't find an account type, but ReceiveInfo.tsx also takes in eth assets, which don't have an accountType. So we need either to only run this function for BTC, or catch the error.
No ticket.
1. Open ETH asset.
2. Click receive.
3. App should show your ETH address.
=> fix: fixes crash when opening eth receive

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx, src/state/slices/portfolioSlice/portfolioSlice.ts
- selectPortfolioCryptoHumanBalanceByAccountTypeAndAssetId
- selectPortfolioFiatBalanceByAccountTypeAndAssetId
Removes obsolete selectors specified by #774
closes #774
* run `yarn test`
=> chore: remove obsolete portfolio account selectors

src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
Add `selectPortfolioAllocationPercentByAccountId` to get allocation by account
2. etc...
=> feat: add allocation by account

src/components/AssetHeader/AssetHeader.tsx, src/components/BalanceChart/BalanceChart.tsx, src/components/TxHistory.tsx, src/context/TransactionsProvider/TransactionsProvider.tsx, src/hooks/useBalanceChartData/useBalanceChartData.ts, src/state/slices/portfolioSlice/portfolioSlice.ts, src/state/slices/txHistorySlice/txHistorySlice.test.ts, src/state/slices/txHistorySlice/txHistorySlice.ts
fixes balance charts for everything except portfolio - eth, tokens, and btc asset and accounts all work correctly
closes #691
1. go to bitcoin asset page and balance chart, right hand side of chart should end with full balance across all accounts
2. go to bitcoin account page and balance chart, right hand side of chart should end with balance for that account
n/a
=> fix: update balance charts

src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
In order to get the correct allocation percentages, we needed to filter out any assets that were NOT the Fee asset for a given blockchain, ie if we're getting the allocation percentages for ETH, we need to filter out any token fiat balances from the total balance.
2. etc...
=> feat: add selectPortfolioTotalFiatBalancesForFeeAssetOnly for account allocations

src/state/slices/txHistorySlice/txHistorySlice.ts
fixes portfolio balance charts
when selecting all txs by all assets, we had duplicates, because the same tx can be related to two assets, so now we're deduping and charts work
closes #789 
1. check portfolio balance chart all time - should go back to zero
2. please also check all asset and account pages
=> fix: portfolio balance charts work again

src/components/AssetAccounts/AssetAccountRow.tsx, src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
fixes account allocation for erc20s
n/a
1. check account allocation percentage on an asset page, e.g. btc or fox
2. for assets with multiple accounts (btc) the allocation bars should add up to a full bar
3. for assets with a single account (eth or erc20s) the allocation bars should be 100% (until we have accountIndex > 0)
nah
=> fix: account allocation percent

src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
refactor `selectPortfolioAssetIdsByAccountIdExcludeFeeAsset` to sort assetIds by fiat balance.
closes #788 
2. etc...
=> feat: sort token asset Ids by fiat balance

src/components/Modals/Send/AddressInput/AddressInput.tsx
Trims leading and trailing whitespace for all "send" address inputs.
Addresses https://github.com/shapeshift/web/issues/735.
Attempt to paste an address with leaving or trailing spaces into the send address.
N/A
=> feat: trim leading and trailing whitespace on send addresses

src/components/AssetHeader/AssetHeader.tsx, src/state/slices/portfolioSlice/portfolioSlice.ts
- Added account ID to asset action if there is only one account
- Filter out tokens we don't support on the `selectPortfolioAssetIdsByAccountIdExcludeFeeAsset` selector
2. etc...
=> bug: add account id

src/components/Transactions/TransactionReceive.tsx, src/components/Transactions/TransactionRow.tsx, src/components/Transactions/TransactionSend.tsx, src/components/Transactions/TransactionTrade.tsx, src/hooks/useTxDetails/useTxDetails.test.ts, src/hooks/useTxDetails/useTxDetails.ts, src/test/mocks/txs.ts
- Separates transaction type rendering logic from `transactionRow` into child components
- Moves common transaction detail logic into a custom hook, `useTxDetails.ts`
- Adds (very) basic tests for transaction detail logic in `useTxDetails.test.ts`
We could reduce some duplication by making a generic component for the collapsed view, as I imagine this will stay fairly consistent (i.e. just passing in something like `icon`, `label`, `value`, `date`). 
The expanded view (everything inside the `Collapse` tag) is where I expect most of the transaction type-specific logic will sit, though without a full understanding of the direction I could be wrong here.
Issue: https://github.com/shapeshift/web/issues/560
- …
=> refactor: allow multiple transaction types in transactionRow

.github/workflows/pr.yml
adds a restore key to the actions/cache@v2 CI workflow to restore node_modules from the cache - it seems we were never actually trying to hit the cache.
n/a
1. a PR against develop with an unchanged `yarn.lock` file should restore from cache, and the install step shouldn't take ~90s
n/a - ci only
=> chore: cache node modules correctly in ci

src/hooks/useBalanceChartData/useBalanceChartData.ts
Load a zero balance chart when using a wallet with zero balances or trade history
closes #815
1. Create a new fresh native wallet
2. The dashboard should display a flat line with 0 balance
=> fix: load a zero balance chart when using a wallet with zero balances

src/features/defi/providers/yearn/constants/vaults.ts
Some yearn vaults have very low apy, this removes them in preparation for extending the assets and market services to include more vaults.
closed #842 
2. etc...
=> chore: removed 1inch uni and compound for low apy

src/assets/translations/messages-en.json, src/components/AssetHeader/AccountLabel.tsx, src/components/AssetHeader/AssetActions.tsx, src/components/AssetHeader/AssetHeader.tsx, src/components/Layout/Header/NavBar/MainNavLink.tsx, src/components/Tooltip/Tooltip.theme.ts, src/theme/theme.ts
- Added the account label to the asset details header
- Changed asset actions over to match the rounded style we use everywhere
- Added translations for asset action buttons
- Added theme file for tooltip
2. etc...
=> feat: add account label to asset details

src/components/FiatInput/FiatInput.tsx, src/components/FiatInput/computeFontSize.ts, src/components/Layout/RightSidebar.tsx, src/components/Trade/TradeInput.tsx
Adjust fiat text size to avoid clipping in Trade modal. The approach taken here allows the initial font size to be specified using a themable value, eg. `5xl`. 
Think I did a good job? Feel free to [tip](https://gitcoin.co/tip?username=helr441) me! (thanks in advance)
Closes #709.
2. Enter a large number in the ETH like 50,000 (depends on your locale) and wait for fiat rates to be fetched, and once fetched, see that fiat value displayed does not get clipped.
using the ID locale:
=> feat: adjust fiat text size to avoid clipping in Trade modal

headers.js
Safari (WebKit in general?) on both desktop and
iOS doesn't accept `script-src` for Workers.
Adding `child-src blob:` gives `react-qr-reader`
the required access to creating a Worker from
a Blob, thus removing the fatal SecurityError
and restoring expected behavior.
Added the `child-src` directive with a single `blob:` in the source list.
fixes #818 
1. `yarn build` (There's some quirks when developing on mobile/browserstack devices, which have nothing to do with #818)
2. Host the build (Port and IP/host name depend on your mobile development setup; let me know if you want me to set up a netlify instance for this branch)
3. Connect a wallet
4. Send an asset
5. Tap the QR button in the send modal's address field
The first two videos don't actually show a …
=> fix: http-equiv header missing 'child-src blob:' (#818)

src/state/slices/portfolioSlice/utils.test.ts, src/state/slices/portfolioSlice/utils.ts
If a user picks an erc20 token that they doesn't have a balance, when the user clicks `send` or `receive`, the `Accounts` modal is opened with no Accounts to pick from. This fixes that issue by returning all the accounts for a given chain if the asset does not have a balance.
closes #852 
2. etc...
=> fix: fix receive erc20 not finding proper accounts

src/assets/translations/messages-en.json, src/components/Modals/Send/Form.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
- fix(useSendDetails): verify that user has enough of native token (ERC20 for now, but that can the same logic can be used for other caip19 in the future) to cover the gas fee.
#872
1. Use an account without enough ETH to cover an ERC20 send tx gas fee
2. Try to send max, it should load for a few ms then display insufficient gas error button state
3. Try to send any amount of token (within the range of your balance), it should display insufficient gas message (loading state will be implemented separately in https://github.com/shapeshift/web/pull/873/ and I will update this then, but for now, you should just wait ~1s without clicking next and it will error out) 
- ERC20 - …
=> fix(useSendDetails): verify ETH balance for ETH/ERC20 send tx gas

src/components/Modals/Send/views/Details.tsx
- fix: disable send form next button en empty input
Currently, there is no condition to disable the Next button while input is empty, which produces a state with an empty gas estimation view after Next button click.
1. Click on `Send` for any asset
2. Enter a destination address and click `Next`
3. `Next` button should be disabled until you input some value
=> fix: disable send form next button on empty input

src/lib/utils.ts
I hunted down the history of this line and there wasn't a particular reason we made the `0x` optional; at the time it was added, though, this function wasn't necessarily supposed to be scoped to ETH addresses only. Now that it clearly is, there's no reason to leave the ambiguity. (I also swapped the `0-9a-fA-F` with `0-9A-Fa-f` so that the charater range is in ASCII lexographical order for OCD reasons.)
=> chore: slightly tighter regex in isEthAddress

src/assets/translations/messages-en.json, src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx
- feat: handle user-rejected send txs
This fixes the toast that is currently showing when sending of asset fails: "%{asset} sent. User has rejected the transaction" and instead shows "Your send of <token name> failed. User has rejected the transaction". The rest of the flow that leads to user being able to send an invalid tx in the first place is handled in a separate issue, see dev notes.
[ethSendTx](https://github.com/shapeshift/hdwallet/blob/f500e03e0f8f5bca076acaf3859ab6a14d363d66/packages/hdwallet-metamask/src/ethereum.ts#L90) in `hdwallet-metamask` currently captures the thrown Metamask error, `console.error`s it, and just returns null. Changing this would be a breaking change in many places. Since we have many checks in place before building, signing and broadcasting the tx, it …
=> feat: handle user-rejected send txs

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
- add missing setting of loading state during valid balance on `useSendDetails`'s input change handler
- don't debounce the leading call to `handleInputChange`, since it would miss out on trying to send [1-9]$ / 1ETH
- capture caught error on `estimateFormFees`, set error/loading state accordingly and rethrow it. This will make sure that the loading works as intended, as not handling the error would short-circuit the logic on thrown error which would result in an infinite loading state
This can be improved on a follow-up PR by not even executing the calls to the gas estimate API in case the current `inputValue` is greater than the previous one, since it will obviously be out of user's fees range. 
#872 …
=> fix(useSendDetails): loading state on valid balance check

src/components/AssetHeader/AssetActions.tsx, src/components/AssetHeader/AssetHeader.tsx, src/components/Trade/TradeInput.tsx
Restricts the users from sending tokens whenever their wallet balance is bellow 0 (Sell case) or the input amount is above wallet balance (trade flow).
Closes: https://github.com/shapeshift/web/issues/736
Sell flow:
1. Pull branch locally and  start the server
2. Under "Your Assets" select an asset which you used to have but currently shows 0 balance
3. Hover over "Sell" button
Trade flow:
1. Pull branch locally and  start the server
2. Input an amount in the Trade Input which is above the amount that is available on the user's wallet for that specific token.
3. Hover over "Trade" button
Sell attempt whenever the user's wallet is below 0:
Trade attempt whenever the input …
=> feat: disable send transactions when insufficient balance

cypress/README.md, cypress/plugins/index.ts, cypress/scripts/linux-brave-version.sh
- Address Cypress feedback from @rbeer and fix Cypress Brave support on Linux.
- Handle bad paths / no Brave installed more gracefully
A follow-on from https://github.com/shapeshift/web/pull/849
Run using GUI: `yarn test:cypress`
=> fix: brave support on Linux

cypress/scripts/linux-brave-version.sh
As suggested by @gomesalexandre in https://github.com/shapeshift/web/pull/954#discussion_r800595317:
`/usr/bin/which` might be a safer way to use `which`, since `which` is often aliased by some linux systems with a few additional flags like `--show-dot` or `--show-tilde`.
N/A
Run using GUI: `yarn test:cypress`
=> fix: improve Brave Linux path

src/features/defi/components/Deposit/Deposit.tsx, src/features/defi/components/Withdraw/Withdraw.tsx
By default the Chakra-UI `InputLeftElement` in `InputGroup` has the `position: absolute` property set, I changed the position to relative, this way, the cryptoInput will maintain a relative position to it, not having its value overlapping the asset button.
closes issue https://github.com/shapeshift/web/issues/938
1. Connect your wallet and arrive on the dashboard
2. Click on the DeFi tab, top center of the page
3. Click the get started button on any vault
4. Click deposit or withdraw
5. Type in a value or click a percentage of allotted asset
6. Numerical value isn't overlapping the name of the asset
=> fix: overlapping input number fixed by relative position

src/pages/Accounts/AccountToken.tsx
Redirecting users to the `accounts` page if they switched the connect wallet while visiting an account page (`/accounts/:accountId/:assetId?`), since these pages are related to the connected wallet there will be the necessity to select another account of the connected wallet.
- [ x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [ x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
closes #978 
2. Connect …
=> fix: redirect user to accounts page if changed wallet while on an account

cypress/support/commands.ts, src/Routes/Routes.tsx, src/pages/ConnectWallet/ConnectWallet.tsx
This PR adds programmatic login when testing with cypress.
Specifically, this PR set `walletId-cypress` and `walletPwd-cypress` in `localstorage` when testing. When `ConnectWallet.tsx` detects the above-mentioned fields during runtime, it will try to automatically connect the specified wallet by:
1. setting up the adapter.
2. initializing wallet.
3. find and open the vault.
4. decrypt the wallet.
5. set wallet by `dispatch()`
6. redirect to dashboard.
The `Password` modal will pop out due to the `MNEMONIC_REQUIRED` native event sent by `wallet.initialize()`. We can just ignore it as the wallet will be set programmatically.
#948 
The added logic in `ConnectWallet.tsx` will only be triggered during testing (i.e. `walletId-cypress` and `walletPwd-cypress` are appeared in `localstorage`) so …
=> feat: add programmatic login when testing with cypress

package.json
- add linting of cypress folder on `lint` script
There's already a `lint:cypress` script but it doesn't run on CI, which would potentially make contributors commit changes in this folder containing lint violations.
@0xApotheosis since there is a lint script specifically for cypress, does it make more sense to move it to CI? If so, I suggest extending from our base lint rules.
- make any modification to a file in /cypress that will make your editor not happy (since you might have autofix on, you might have to fire a vim/nano for that or disable it temporarily)
- `yarn lint` should produce errors
=> feat: lint cypress folder

src/components/Layout/Header/HeaderContent.tsx
Removed the back button in defi-overview while keeping the defi-earn back button as is. PR `closes #990`
https://user-images.githubusercontent.com/55772762/153614908-8421cd17-514a-451f-a792-7b9fc760250d.mov
=> fix: update defi back button

src/components/Delegate/StakingOpportunitiesRow.tsx, src/features/defi/components/AprTag/AprTag.tsx
This abstracts the APR tag into its own component, since it's going to be needed for many other views
- add `<AprTag />` component
- consume it in `<StakingOpportunitiesRow />`
1. Add `ChainTypes.Ethereum` to`useRenderForChains` in `<StakingOpportunities />`
2. Enable `REACT_APP_FEATURE_COSMOS_INVESTOR` feature flag
3. Go to Ethereum, and on Cosmos Validator opportunity, APR tag should still be visible
=> feat: <AprTag />

src/components/Transactions/TransactionTrade.tsx
I missed the removal of the `TransactionTrade`'s prop in https://github.com/shapeshift/web/pull/1035.
=> fix: remove activeAsset prop from TransactionTrade

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/TokenRow/TokenRow.tsx
fixed wrong button title on Send modal if the input is dirty.
closes #1051
Open Send modal, enter amount higher than your balance and change it to something you can afford, you must be able to go to the next step.
=> fix(useSendDetails): update errored state properly on input change

src/assets/translations/messages-en.json, src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
Added transaction link to toast on a successful transaction.
- [Yes ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ Yes] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
https://github.com/shapeshift/web/issues/986
Very low risk, minor change to toast notification
1) Visit app.shapeshift.com
2) Send funds from one address to another
3) Notice the toast notification signifying the successful txid
4) Click on the provided link to view transaction on the designated block explorer
=> feat: add transaction link to toast

src/state/store.ts
doesn't persist RTK query state - causing desired network requests to abort on app boot
n/a
low - this reverts to a previous behaviour we had before the wallet reconnect on page load feature was merged.
if the app loads as expected we're good
see that the rehydration is not rehydrating the RTK query reducers
=> fix: don't persist redux toolkit api reducers

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/TokenRow/TokenRow.tsx, src/components/Trade/TradeInput.tsx
`TokenRow` onChange fixed alongside its side-effects
- Send modal amount input should handle errors correctly
- Trade card amount inputs should handle state correctly
Throughout these two processes, your funds could be sent/traded which is irreversible.
=> fix: tokenrow onchange fixed alongside its side-effects

src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
fix: save the broadcast txid for the toast for wallets that do offline signing
this was implemented for wallets that support signAndBroadcastTransaction (metamask) but missed for all others
n/a found in release branch testing
none - bug fix.
do a send with a wallet other than metamask. the broadcast txid link should work in the success toast
=> fix: send tx toast fix

src/hooks/useBalanceChartData/useBalanceChartData.ts, src/state/slices/portfolioSlice/selectors.ts
fix: optional chain a bunch of things that don't exist in the store on page reload when deep linked
with the new routing changes, things were loading quicker and the selectors were trying to read data from the store before it existed on deep link page reloads. this opt chains things until it worked again
n/a - found in release branch testing
some selectors could work incorrectly.
go to an account page, and refresh the page. the page should loading without crashing.
n/a
=> fix: optional chain a bunch of things

src/components/Modals/Send/views/Address.tsx
The generic type was removed for `validateEnsAddress` so we change the check to check for the actual `EthereumChainAdapter` class instead of the generic `ChainAdapter<ChainTypes.Ethereum>` interface
N/A
Affects ENS address lookups, but the risk here is basically none.
Test Ethereum sends with an ENS address
=> fix: send modal address check for Ethereum ens addresses

src/pages/Defi/components/StakingCard.tsx
closes #1092
Looks like there are no risks
- Go to the DeFi page
- Have some assets staked
- Verify on light mode if the vault value is well displayed
=> fix: vault value color on both themes

.github/workflows/pr-cypress.yml
Working with @0xApotheosis to add a fallback Cypress key for forks by external contributors. 
This PR is proof by construction that an external contributor with limited permissions can open a PR with passing tests.
Closes #1136 
N/A
PRs on forks should pass expected checks.
N/A
=> chore: add fallback cypress key

src/components/Layout/Header/NavBar/UserMenu.tsx
Spotted while offline. When trying to get the reverse resolution for an address, ENS will timeout when offline and we do not gracefully handle this, the User Menu just shows "Metamask" (I didn't test it with other wallets):
Now, we don't have offline capabilities in the app to the extent that this fix would be useful when offline, but it's nice to know that any timeout to ENS reverse lookups - for any reason - will be gracefully handled.
N/A
We should do some regression testing to make sure that the user menu doesn't break in other circumstances because of this. 
- Go offline
- Run the app and connect to your wallet
- Current account's address should be displayed
=> fix: fallback to address on ENS timeout

src/components/Transactions/TransactionContract.tsx, src/hooks/useTxDetails/useTxDetails.ts, src/state/slices/assetsSlice/selectors.ts
Fixes a bug introduced in a recent change to support unknown transaction types. 
We currently fall back to a `feeAsset`'s `explorerTxLink`s and `explorerAddressLink` for unknown transaction types but don't check for undefined `feeAsset`s.
N/A
N/A
Rendering an unknown transaction without a `standardAsset` or `tradeAsset` should no longer throw.
N/A
=> fix: check for undefined feeAsset

src/components/Layout/Header/NavBar/MainNavLink.tsx, src/components/Layout/Header/NavBar/NavBar.tsx, src/components/Layout/Header/SideNav.tsx, src/components/Layout/Header/SideNavContent.tsx, src/pages/Dashboard/Dashboard.tsx, src/pages/Dashboard/Portfolio.tsx, src/theme/theme.ts
- Added back the dashboard sidebar component
- Made the side nav all use the same component to streamline styling
- Navbar now goes compact on a specific screen size to give the main component more real estate
closes #1150 
Very low risk here, just styling fixes
Test on large desktop, small desktop and mobile make sure all looks well.
=> feat: add back dashboard sidebar and fix sizing

src/App.tsx, src/AppProviders.tsx, src/components/Layout/Header/NavBar/NavBar.tsx, src/context/ChainAdaptersProvider/ChainAdaptersProvider.tsx, src/hooks/useAccountSpecifiers/useAccountSpecifiers.ts, src/plugins/cosmos/index.tsx, src/plugins/index.ts, src/state/slices/preferencesSlice/preferencesSlice.ts
fix: don't load cosmos chain adapter unless enabled
Known issue but not documented
The dashboard will show assets it shouldn't or visa-versa
1. Use a wallet that has ATOM
2. Load the dashboard
3. Press ALT+SHIFT+F to open Flags
4. disable/enable the `CosmosPlugin` flag
5. click "Reset App"
6. Repeat with different flags/wallets
=> fix: don't load cosmos chain adapter unless enabled

src/components/Layout/Header/NavBar/UserMenu.tsx
This fixes the "happy" path for `<UserMenu />`.
In https://github.com/shapeshift/web/pull/1139/files#diff-cf09d1257e0d923f05e5933d109cd808ac574231106cc258bdca19f02e0ce8dbR105, the unhappy path was handled on catch, but that left out the unhappy "happy" path, where there is no actual error, but rather an `{error: true}` property in `addressReverseLookup`.
As a result, the address isn't currently showing, only the ENS name. 
N/A
N/A
Account address should be displayed in the user menu.
=> fix: happy address UserMenu path

src/assets/translations/messages-en.json, src/plugins/cosmos/components/modals/Staking/views/StakeBroadcast.tsx, src/plugins/cosmos/components/modals/Staking/views/StakeConfirmRouter.tsx
- add `<Broadcast />` view and use it in `StakeConfirmRouter />`
#663
This won't close #663 as it is not wired up yet and loading states will be added then.
It is not a product risk since it is a new component but it is an engineering issue to keep in mind.
- Open cosmos staking modal
- Select any amount e.g 50%
- Click confirm
=> feat: cosmos 'Confirm Staking - Broadcast' view

.github/PULL_REQUEST_TEMPLATE.md
Noticed that sometimes contributors forget to remove the explanations from their Pull Request.
Also, it's easier for reviewers and maintainers to detect empty parts because they will really be empty!
No risk
Can't really test until it's merged
=> fix: comment the explanations inside pr template

src/components/Trade/TradeConfirm/AssetToAsset.tsx
I did adapt the asset trading header with flexbox in order to stick asset value on the top instead, so it's aligned on line break.
There was another wrong behavior on really big asset number that I fixed by limiting the width of right and left columns
closes #1164
No specific risk
- Go to an asset page, such as Ethereum for example
- Try to trade with FOX, the best way is to trade any value then edit in the devtools console so you get a bigger value
- It shouldn't break on line-break with big values
Also tested with really really big values because there was a buggy behavior too:
=> fix: confirm trade assets names stay consistent on line break

src/Routes/Routes.tsx
- I added a flag icon in the navigation bar to go to the "/flags" route
- It does show on localhost
- It doesn't show in production
closes #1225 
Not risky as it just adds a UI feature
- Go to main page on localhost
- Click on the flag icon in the navigation bar
=> feat: new icon for development flags

src/components/TransactionHistoryRows/TransactionContract.tsx, src/components/TransactionHistoryRows/TransactionDetails/Address.tsx, src/components/TransactionHistoryRows/TransactionReceive.tsx, src/components/TransactionHistoryRows/TransactionSend.tsx, src/components/TransactionHistoryRows/TransactionTrade.tsx, src/components/TransactionHistoryRows/UnknownTransaction.tsx
Fixes tx row address explorer link.
None
Clicking on the addresses of a tx should open up a healthy valid page on the explorer.
=> fix: address explorer link fixed

src/components/TransactionHistoryRows/TransactionGenericRow.tsx, src/components/TransactionHistoryRows/TransactionReceive.tsx
This hides miner fees for receive Txs in TransactionHistory.
Currently, fees are displayed for receive Txs in the Transaction History section but we shouldn't display them, as unchained is not returning us fees for receive txs, which results in unwanted behavior where we're not able to surface the symbol. Confirmed with @kaladinlight that's the correct unchained behavior.
Not displaying Tx fees is also the current behavior in the Transactions section in dashboard - if we want to display it, it should be implemented in unchained and surfaced from it then displayed in both the Transactions section and Transactions History section and it would have to be a product decision, this PR just brings consistency.
closes #1239
N/A, the hiding is only done for receive Txs so we don't have risks of …
=> fix(TransactionHistory): don't display receive Tx fees

.github/ISSUE_TEMPLATE/bounty.yml
When a bountied issue is created by a member of a non-engineering workstream it's not always clear to the bounty hunter who the bounty's technical stakeholder is.
This PR adds the option to provide this during issue creation and leaves a placeholder heading for Engineering to add once the `needs-engineering` phase is complete if it's originally omitted.
N/A
N/A
Create a new bounty issue and confirm the new input field displays as expected.
=> feat: add stakeholder input field to bounty template

src/pages/Accounts/AccountToken/AccountToken.tsx, src/state/slices/accountSpecifiersSlice/selectors.ts
This fixes a bug we have in Portis/Native/KeepKey on latest develop and release branch after https://github.com/shapeshift/web/commit/ad806dee305535434440679906f1d74f130a8fa4, where clicking an account token will route back to accounts page.
The reason for this redirect is this condition:
https://github.com/shapeshift/web/blob/ad806dee305535434440679906f1d74f130a8fa4/src/pages/Accounts/AccountToken/AccountToken.tsx#L26-L28
Since account specifiers are CAIP19s containing checksummed addresses (with a mix of upper and lowercase characters), but the `accountId` is lowercase, the condition will only return true if we use Metamask, for which hdwallet-metamask calls ethereum JsonRPC's `eth_accounts` - which gets accounts lowercased.
For Portis, KK, and Native, it will always return false. 
No …
=> fix: lowercase account specifier strings

src/components/Modals/KeyManagement/Native/Password.tsx, src/context/WalletProvider/NativeWallet/components/NativeImport.tsx, src/context/WalletProvider/NativeWallet/components/NativePassword.tsx, src/context/WalletProvider/NativeWallet/components/NativeRename.tsx
fix: clear form fields on unmount
Found by ops during testing
Low
Test the modals:
NativePassword, NativeImport, Password, NativeRename 
Walk through the create/import/load native wallet flow, disconnect, and redo
=> fix: clear form fields on unmount

src/context/I18nProvider/I18nProvider.tsx
This PR adds fallback English translations in cases where a specific translation key is missing.
Relevant documentation for the underlying library can be found [here](https://github.com/airbnb/polyglot.js#options-overview).
While I was initially concerned that this approach may cause issues with the pluralization, it does not appear that this codebase is currently making use of that functionality anyway.
Additionally, it seems that there is already plenty of discussion underway re. [Making the translations fetched, granular and consistent](https://github.com/shapeshift/web/discussions/1063), so I took the min diff approach.
Closes #1221 
This change could potentially cause some regression with the existing translations, but I would suggest that risk is on the low side. One possibility …
=> fix: fall back to English if translation key is missing

package.json, yarn.lock
This reverts commit 33fa94d9b8d222829790676f0ff53e1a33bdb944.
We don't know why, but upgrading axios to 0.26.1 breaks the app state in Cypress tests.
Closes https://github.com/shapeshift/web/issues/1287
N/A
=> chore: revert "chore: upgrade axios to 0.26.1 (#1275)"

src/state/slices/portfolioSlice/selectors.ts
This sorts accounts balances by chain buckets in the accounts page. 
- tested on an account with a mixed balance of BTC (on Segwit, Segwit Native and Legacy) and ATOM on CosmosHub. 
- also tested on an account with ETH and ERC20 tokens exclusively, in isolation (without other assets)
- not tested with both of these two cases at the same time (an account with a mix of BTC (Segwit, Segwit Native and Legacy), Atom on CosmosHub and ETH + ERC20 tokens
closes #1289
- Is using `asset.chain` as a discriminator the right way to go? Is there any case in the future where this could break sorting, and do we have a better way to achieve this using account specifiers?
- This could potentially break the sorting in the case of a mix of assets and account tokens e.g ERC20s
- Go to accounts page
- Accounts …
=> fix: accounts balances by chain buckets

src/state/slices/portfolioSlice/selectors.ts
- Fix for cosmos showing up as an Account and a Token on the `Accounts` page.
-  The `Accounts` page relies on the selector `selectPortfolioAssetIdsByAccountIdExcludeFeeAsset` to exclude fee assets. All fee assets that are excluded need to be added to the constant array `FEE_ASSET_IDS` maually. This is definitely not ideal, and we should look at better ways to determine the fee assets of each chain dynamically so we don't have to manually add each fee asset as we implement more chains.
closes #1273
The risk associated with this fix is minimal, given the array is only used for this purpose.
- Navigate to the `Accounts` page
- Cosmos should not have a token of the same name associated with it.
=> fix: add cosmos to feeAsset const

package.json, yarn.lock
chore: upgrade react-hook-form to 7.28.1
N/A
Anything form related, like trade widget, send, etc.
Test that all forms work correctly
=> chore: upgrade react-hook-form to 7.28.1

.github/ISSUE_TEMPLATE/bounty.yml
Help the bounty poster, aka 0xean, assign an appropriate payout for the bounty.
N/A
N/A
Create a new bounty - an input box to enter estimated effort should show.
=> chore: add effort estimate to bounty template

.github/workflows/pr-cypress.yml
`github-action@v2` uses Node 12, which I suspect could be causing some of the flakeyness in CI.
`github-action@v3` uses Node 16, which may resolve these issues.
Closes https://github.com/shapeshift/web/issues/1325
It could make CI worse, but we'll mitigate that by testing exhaustively in this PR.
CI on this PR should reliably pass.
N/A
=> chore: use cypress-io/github-action@v3

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx, src/components/Modals/Send/hooks/useSendFees/useSendFees.test.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx, src/state/slices/assetsSlice/selectors.ts, src/state/slices/portfolioSlice/selectors.ts, src/state/slices/selectors.ts, src/state/store.ts
`state/slices/selectors` file had circular imports, this PR will fix that.
this PR also uses all selectors to show them up in `reselect-tools`
also, some test files were refactored, they were previously failing because of this circular importing issue and `jest.fn()` was used to make them pass.
=> fix: redux selectors circular imports

src/pages/Defi/components/OpportunityCard.tsx, src/pages/Defi/components/OpportunityCardList.tsx, src/pages/Defi/components/OverviewHeader.tsx, src/pages/Defi/hooks/useEarnBalances.tsx, src/pages/Defi/views/Overview.tsx
- Add the foxy opportunities to the overview tab
- Rename some stuff that was vault specific to just the generic Earn Opportunity
Low risk -- reworked the logic to display the vaults and foxy opportunities to be more generic, if this doesn't show the user can still see these in all other places that we display opportunities. So it will not prevent the user from interacting with their opportunities.
Go to DeFi overview section, confirm your vaults are still showing.
=> feat: add foxies to the overview tab

src/features/defi/components/Approve/Approve.tsx, src/features/defi/components/Confirm/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyDetails.tsx
The logic on the overview section wasn't taking into account if the user had no balance but had a claim available.
Also don't want the user accidentally cancelling or rejecting in the middle of transaction being broadcast. So if the primary button is in a loading state we disable the cancel/reject. 
Very low risk, all behind a feature flag
If you have a foxy balance, and withdraw max with delayed withdraw type. You should see a 0 FOXY balance, and the pending withdraw on the overview tab.
While waiting for confirm on wallet on the deposit/approval screens -- the cancel/reject buttons should be disabled.
=> fix: update logic for overview and disable cancel buttons when loading

src/components/Modals/Settings/SettingsList.tsx
Language section in settings modal brought back to life
follow-up of settings-modal
none
Open up settings-modal, click on the language button, and select a language.
- The whole app should respect the selected language. if some key is missing in the selected language, the English fallback must be shown.
- Selected language should be persisted after reloading.
=> feat: language in settings-modal brought back to life

src/components/StakingVaults/EarnOpportunities.tsx, src/components/TransactionHistory/TransactionHistoryList.tsx, src/components/TransactionHistory/TransactionsLoading.tsx, src/components/TransactionHistoryRows/TransactionGenericRow.tsx, src/components/TransactionHistoryRows/TransactionLoading.tsx, src/context/TransactionsProvider/TransactionsProvider.tsx
- Add loading state for TX history
- Adjusted timeout on the `TransactionsProvider`
- Hide earn when there are no opportunities available
closes #1295 
Very low risk
Navigate to dashboard/asset page you should see a loading state on the history component then the tx history will populate
=> fix: add loading state for tx rows

src/components/TransactionHistoryRows/utils.ts
Fallback values for unknown assets. 
Note: this is using `18` precision as the fallback, so if that needs to be changed to `N/A` only without any numbers at all, please tell me.
closes #1213
none
=> fix: fallback values for unknown asset

src/assets/translations/main.json, src/features/defi/components/Deposit/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/WithdrawCard.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
- fix the hardcoded width on the defi modals
- link up terms of service in the footer of the FoxyDeposit modal
- Update the approval copy to say "use" instead of spend
- Add minFractionalDigitals to the withdraw claim card
closes #1381 
Low risk, all UI code behind a feature flag
Make sure the deposit/withdraw/overview modals scale correctly on mobile.
=> fix: ui tweaks for foxy

src/assets/translations/main.json, src/plugins/cosmos/components/modals/GetStarted/views/GetStarted.tsx, src/plugins/cosmos/components/modals/Staking/Staking.tsx, src/plugins/cosmos/components/modals/Staking/StakingCommon.ts, src/plugins/cosmos/components/modals/Staking/forms/StakeFormManager.tsx, src/plugins/cosmos/components/modals/Staking/views/ClaimBroadcast.tsx, src/plugins/cosmos/components/modals/Staking/views/ClaimCommon.ts, src/plugins/cosmos/components/modals/Staking/views/ClaimConfirm.tsx, src/plugins/cosmos/components/modals/Staking/views/Overview.tsx, src/plugins/cosmos/components/modals/Staking/views/Stake.tsx, src/plugins/cosmos/components/modals/Staking/views/StakeBroadcast.tsx, src/plugins/cosmos/components/modals/Staking/views/StakeConfirm.tsx, src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx, src/plugins/cosmos/components/modals/Staking/views/UnstakeBroadcast.tsx, src/plugins/cosmos/components/modals/Staking/views/UnstakeConfirm.tsx, src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx, src/plugins/cosmos/utils.ts, src/state/slices/stakingDataSlice/selectors.ts
This implements the building of unsigned claim Tx for cosmos and broadcasting of the Tx with native wallet.
To be added in a follow-up PR(s):
- Broadcast errors (will require working WS txhistory messages)
- Don't claim 0 rewards, since it is possible at protocol level to broadcast such Tx but no rewards will effectively be claimed (it could be abstracted to something similar to `useSendDetails`) - we will probably need to add some rounding logic in a follow-up PR, since we never really get `0` as rewards amount, but rather a very small number
- Don't allow undelegations if greater than `MaxEntries` (https://docs.cosmos.network/master/modules/staking/03_messages.html) - we would need to expose this in the unchained response for `/api/v1/account/{pubkey}`, and then add it to the parsed …
=> feat(cosmos): claim staking and unstaking

src/plugins/cosmos/components/AssetClaimCard/AssetClaimCard.tsx, src/plugins/cosmos/components/AssetHoldingsCard/AssetHoldingsCard.tsx, src/plugins/cosmos/components/StakedRow/StakedRow.tsx, src/plugins/cosmos/components/modals/Staking/views/Overview.tsx, src/plugins/cosmos/components/modals/Staking/views/Stake.tsx
The cosmos icon on the overview and staking modal was a static one, we should use the `asset.icon`
No much risks
Open the Overview and Staking modal of a cosmos asset and see if the icon is the right one
=> fix: replace the cosmos static icon to asset icon on overview

src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap, src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/selectors.ts
Fixes the allocation computation for portfolio rows.
Can be verified with an account with only one asset allocation (100%), the computation always returned something like 99,99X% or 100.01%.
Verify that the allocation is now 100%
Before fix
After fix
=> fix: wrong allocation for account portofolio rows

src/assets/translations/main.json, src/plugins/cosmos/components/AssetClaimCard/AssetClaimCard.tsx, src/plugins/cosmos/components/modals/Staking/views/Overview.tsx, src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
This PR is about small UI nitpicks after https://github.com/shapeshift/web/commit/435aa4d3a10334276205afcf07cd613d9f7d47aa and it:
- uses asset symbol vs. name everywhere in the cosmos staking modal for consistency and to match the mockups.
- uses the right hardcoded amount of days for Cosmos unbonding days (21).
N/A
- The right number of unbonding days should be displayed for Cosmos unstaking in the staking modal
- The symbol should consistently be used in place of the name in the staking modal
=> fix(cosmos): ui nitpicks

src/plugins/cosmos/components/modals/Staking/views/Stake.tsx, src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx, src/plugins/cosmos/components/modals/Staking/views/UnstakeBroadcast.tsx, src/state/slices/stakingDataSlice/selectors.ts
On Stake and Unstake steps of the staking modal, this:
- adds validation of staking/unstaking balance in the Stake/Unstake inputs.
- fixes the data shown as "Amount staked" in unstake (the amount that's available to unstake) which currently uses bondings total (staked + unstaked), which is wrong, since you can't unstake an already unstaked amount
- uses asset precision as decimal places for the crypto input amount. The fiat amount is left untouched as it is used for the crypto amount calculation
- resets crypto amount errors on percent click (since a percentage of the crypto balance/staked balance is guaranteed to be within bounds of availability)
- removes the division of crypto amount / asset precision for fiat rate calculation in `<UnstakeBroadcast />`, since that amount is already in …
=> fix(cosmos): crypto/fiat amount fixes

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
The debouncer in `useSendDetails` does not currently work, and so we make 3 network requests for every keystroke when sending.
This PR fixes that by memoizing the input handler. 
N/A
N/A
Send a transaction and rapidly mutate the input value - check we only make 3 network requests when keystrokes are less than 1,000 ms apart.
N/A
=> fix: debounce send input

src/plugins/cosmos/components/modals/Staking/views/Stake.tsx, src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
This fixes the percent click that's currently returning more than 6 decimal places currently depending on your staked/unstaked amount (it's not consistent, if the percentage has 6 or less decimal places, it would currently work)
#1395
N/A
- Test staking and unstaking with multiple wallets that have various account balance/staked amounts
- The crypto amount should consistently be max. 6 decimal places
=> fix: decimal places fix on percent click

src/components/TransactionHistoryRows/TransactionGenericRow.tsx, src/components/TransactionHistoryRows/utils.ts
Using the asset icon instead of the symbol for the `<AssetIcon>` component
low risk
Make sure the tx history icons are showing correctly
=> fix: switch to asset icon from symbol

.git-blame-ignore-revs, .gitconfig, scripts/postinstall.sh
A fast follow on from https://github.com/shapeshift/web/pull/1437, this PR sets up a `.git-blame-ignore-revs` so that formatting commits are ignored in git blame on both GibHub, locally, and in IDEs
- A `.git-blame-ignore-revs` file has been implemented, with the lint commit ignored - this ensures the lint commit is automatically ignored when using git blame on GitHub. 
- A `.gitconfig` file is added which allows IDEs (tested on WebStorm and VSCode) to respect all skipped commits
- `postinstall.sh` has been updated to automatically use the `.gitconfig` locally once `yarn` / `yarn install` is run
It also works locally by using `git blame --ignore-revs-file .git-blame-ignore-revs`.
For more information on this feature, please see here: …
=> chore: set up git-blame-ignore-revs

src/hooks/useBalanceChartData/useBalanceChartData.ts
Balance charts were including the "amounts" on failed txs. It should only consider the tx fee for failed txs
There should be very little risk with this PR
1) Create a failed TX somehow (sending an eth tx with invalid data to a contract address should do it)
2) see that the "amount" of the tx is no longer included in balance chart
BEFORE:
AFTER:
=> fix: exclude failed send receive values from balance charts

src/assets/translations/es/main.json, src/assets/translations/fr/main.json, src/assets/translations/ko/main.json, src/assets/translations/main.json, src/assets/translations/pt/main.json, src/components/AssetHeader/AssetActions.tsx, src/components/Button/Button.theme.ts
- We wants to have a button on the top of the asset/account page in order to be able to open the explorer link
- In case you are on ETH, BTC, redirect to the basic explorer link, else, redirect to the token link
- Mooved the `viewOnChain` translation key to `defi` part because it shouldn't be inside `transactionHistory` anymore
- Under `md` breakpoint, every buttons are reordered and well placed (see screenshots)
closes #1180
In case the explorer link or implementation changes, it can redirect to a wrong link
Try the button on BTC: It will redirect to blockcypher, because we don't have the link to the BTC page.
Try the button on ETH: It will redirect to etherscan home page.
Try the button on any ERC20: It will redirect to the contract page on etherscan.
Try the button on Cosmos: It will …
=> feat: add link button to the explorer on asset page

package.json, scripts/release.sh
This PR adds a little bit more automation to the release script.
* Automatically create the GitHub PR (if the user has the GitHub CLI installed)
* If the user doesn't have the GitHub CLI, then display a title and body to copy to the PR
* Add colors to some output
N/A
The only risk is to engineers creating release branches. No effect on users.
_This has been tested on Linux but not on macOS._
1. yarn create-release v1.x.x
2. yarn merge-release v1.x.x
=> chore: update release script to automatically create the PR

src/assets/translations/main.json, src/components/StakingVaults/AllEarnOpportunities.tsx, src/features/defi/components/Deposit/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/YearnManager.tsx, src/pages/Defi/components/OpportunityCard.tsx
- fix routing for going back and cancel
- fix translation for the gas
- redirect to deposit on yearn vaults till we have an overview screen
- open TOS in a new window
low risk
make sure the routing works correctly for yearn and foxy
1. Approval cancel, goes back to the input screen
2. Confirm goes back to the input screen
3. Status close takes you back to /defi
=> fix: defi modal routing

src/context/WalletProvider/WalletProvider.tsx, src/context/WalletProvider/WalletViewsSwitch.tsx
The `noBackButton` button property has a negative name, which is confusing.
This PR renames it to `showBackButton` and inverts all related logic.
N/A
N/A
N/A
N/A
=> refactor: invert noBackButton to showBackButton

src/components/Breadcrumbs/Breadcrumbs.tsx, src/plugins/cosmos/index.tsx
- Add additional path pattern matching for cosmos `Account` page. When navigating from the `Accounts` page (all accounts for a user) to a specific account (ie cosmos account page), the url path is `/accounts/:accountId` instead of  `/accounts/:accountId/:assetId`, which is used when navigating from an `Asset` page to an `Account` page. 
Closes [Cosmos showing wrong Account page](https://github.com/shapeshift/web/issues/1468) #1468 
- The risk with this PR is small, given the pattern matching with the path is only associated with cosmos, but it could affect other assets. I've done enough testing to make sure it wasn't affecting any assets that I could currently test, which are BTC, ETH, and ERC20s.
- Navigate to the `Account` page
- Select `Cosmos`
- You should see the cosmos account page …
=> fix: add additional path for cosmos plugin account page

src/plugins/cosmos/components/modals/Staking/views/Stake.tsx, src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
For consistency with yearn and foxy, percents in the VStack of cosmos should be at the top of the stack
None
- Go on cosmos staking modal
- Check on Stake/Unstake if the percents are on the top of the stack (see screenshots)
=> fix: move the percents at the top of the vstack on cosmos

src/context/WalletProvider/WalletProvider.tsx
Many `hdwallet-*` adapters don't do anything useful on `adapter.initialize()`, but because it's part of the exported API every new hdwallet implementation still has to cut-n-paste a boilerplate implementation. Making this call optional will allow us to consider removing `adapter.initialize()` from the upstream API and nuking all the boilerplate, which should make implementing new wallets (xdefi, tally, keplr, etc) a bit easier.
_De minimis._
None required.
=> chore: don't call hdwallet adapter.initialize if it's not there

scripts/postinstall.sh
CI is supposed to install yarn packages with `--frozen-lockfile` set, but that's somewhat undercut if it might be (under freak circumstances) immediately re-run without that option by `postinstall.sh`. Unconditionally using the safe behavior would also mean rejecting any breaking lockfile changes `yarn-minify` might possibly make.
_De minimis._
None required.
=> chore: avoid possible lockfile changes in CI

src/plugins/cosmos/components/modals/Staking/views/Overview.tsx
Currently, we can claim less than 1 uatom (0.000001 ATOM), since unchained returns such amounts as rewards.
However, such amounts are not possible to represent at protocol-level, and when trying to send Txs for claiming fractions of uatom, no rewards will effectively be claimed.
This tightens the check for disabling the claim button by disabling it if the rewards amount are lower than 1 (uatom) vs. equal to zero currently.
N/A
N/A
- Claim rewards
- A few minutes later, try to claim again (on unchained, rewards should then be equal to 0.0x atom)
- The claim button should be disabled
=> fix: don't claim fractions of uatom

sample.env, src/config.ts, src/pages/Defi/hooks/useFoxyBalances.tsx
chore: change `REACT_APP_FOXY_APY` config to `num` instead of `str` and set a default value of `0.15`.
This will make sure that any value we put in the environment variable is at least a valid number
N/A
Very very low. It actually reduces risk by catching mistakes in the environment variable.
Best to test locally. 
1. In `.env` add `REACT_APP_FOXY_APY`
2. Set the value to a valid number
3. Start the app `yarn dev`
4. Change the value to not a number
5. Start the app
=> chore: change FOXY_APY config to 'num' instead of 'str'

src/pages/Defi/views/Overview.tsx
Cosmos staking balance was missing from balance and networth displayed on defi overview page, this is a simple fix to add it back.
https://github.com/shapeshift/web/issues/1491
No risk
Having multiple earn sources (yearn, foxy, cosmos)
Navigate to defi overview page
Verify total earn / wallet balance and networth are correct
=> fix: missing cosmos earn balance

src/assets/translations/main.json, src/features/defi/components/Withdraw/Withdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
Instant shouldn't allow amount to be changed + show better error when reserve is empty.
These were comments from product
=> fix: show when lr is empty + disable input when instant unstake

headers.js, sample.env, src/config.ts
Ensure our headers are in sync with the KeepKey versions URL.
Closes https://github.com/shapeshift/web/issues/1453
`REACT_APP_KEEPKEY_VERSIONS_URL` needs to be added and set to `https://bafybeied24gc2ipvlxdbs4v676dwho2l5aafmngrleic3do2czdvgb546u.ipfs.dweb.link/keepKey.json` before this is deployed, else the KeepKey version in the settings menu won't load.
KeepKey settings should load correctly when the `REACT_APP_KEEPKEY_VERSIONS_URL` environment variable is set.
=> chore: use `REACT_APP_KEEPKEY_VERSIONS_URL` in `headers.js`

src/context/PortfolioProvider/PortfolioContext.tsx, src/context/TransactionsProvider/TransactionsProvider.tsx, src/features/defi/contexts/FoxyProvider/FoxyProvider.tsx, src/features/defi/contexts/YearnProvider/YearnProvider.tsx
fix: change calls to `getSupportedChains()` to use `PluginManager.supportedChains`
`supportedChains` is a reactive state variable so it will cause re-renders when it changes
using `adapters.getSupportedChains()` isn't reactive.
No issue, but prevents an issue if we have a feature flag that toggles support for a chain adapter (such as adding a new chain like Osmosis).
Also changes the code to be consistent in how we check if a chain is supported
There shouldn't be any risk right now until we add a new chain plugin with a feature flag
That that the following load correctly:
1. Portfolio
2. Transaction history
3. Foxy
4. Yearn
=> fix: change calls to "getSupportedChains()" to use "PluginManager.supportedChains"

src/hooks/useHasAppUpdated/useHasAppUpdated.test.ts, src/hooks/useHasAppUpdated/useHasAppUpdated.ts
Refactored [https://github.com/shapeshift/web/blob/develop/src/hooks/useHasAppUpdated/useHasAppUpdated.ts](https://github.com/shapeshift/web/blob/develop/src/hooks/useHasAppUpdated/useHasAppUpdated.ts) to poll `/env.json` for changes and sets a flag when either change.
`useHasAppUpdated` hook now polls both `/env.json` and `/asset-manifest.json` for changes and returns `true` when either change.
Closes #1309
zero risk
`useHasAppUpdated` hook benefits less from testing due to the nature of the internals of the hook. 
Reasons `useHasAppUpdated` benefits less from `unit` testing:
1. `useHasAppUpdated` implementation relies on the [useInterval](https://codesandbox.io/s/pyd7r?file=/src/use-interval.ts) hook due to `jest` failing to register timer when using `jest.useFakeTimers()`
[see a …
=> feat: show app updated toast when env vars change #1309

src/components/Layout/Header/Header.tsx, src/components/Layout/Header/NavBar/UserMenu.tsx, src/components/Layout/Header/SideNavContent.tsx
- when the drawer is open its trapping focus so we need to collapse it whenever you click on a menu item
- Pass down the onClose from the useDisclosure
- Add a helper handleClick function that fires the onClose and the onClick
closes #1400 
Small risk
Click on a switch wallet or submit feedback/settings the drawer should collapse giving focus to whatever menu you just clicked.
=> fix: collapse drawer when menu item is clicked

src/AppProviders.tsx, src/context/AppProvider/AppContext.tsx, src/context/PluginProvider/PluginProvider.tsx, src/context/PortfolioProvider/PortfolioContext.tsx, src/context/TransactionsProvider/TransactionsProvider.tsx, src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts, src/state/slices/accountSpecifiersSlice/accountSpecifiersSlice.ts, src/state/slices/accountSpecifiersSlice/selectors.ts, src/state/slices/assetsSlice/selectors.ts, src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/portfolioSlice.ts, src/state/slices/portfolioSlice/portfolioSliceCommon.ts, src/state/slices/portfolioSlice/selectors.test.ts, src/state/slices/portfolioSlice/selectors.ts, src/state/slices/portfolioSlice/utils.ts, src/state/slices/stakingDataSlice/stakingDataSlice.test.ts, src/state/slices/txHistorySlice/txHistorySlice.test.ts, src/state/slices/txHistorySlice/txHistorySlice.ts
**please note - this is only 200 lines but extremely terse, fragile, and core business logic in the app**
we're currently subscribing to txs multiple times and unsubbing multiple times - this was identified symptomatically while cosmos staking was being tested and uncovered more serious issues.
this PR solidifies how we manage wallet connection/switching/disconnection, to ensure we don't have any websocket related issues with the tx history, and also ensure we clear the portfolio when a wallet is disconnected/swapped.
* fixes bug where we'd reset account specifiers and unsub transactions every time we navigated to an account page
* changes the order of the transaction and portfolio providers for more logical order of actions (see console logging for the result)
* adds debugging logic that …
=> fix: wallet, portfolio and tx management

src/context/WalletProvider/NativeWallet/components/NativeImport.tsx
I've change value to validation , changend toLowerCase on import native wallet.
- [ x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
https://github.com/shapeshift/web/issues/1406
This modify have no risk , is limitate to native wallet to import and anyway now not working when insert uppercase text.
=> fix: correct validations on import native wallet

src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts
Fix double gas fee deduction. The gas fees are deducted here: https://github.com/shapeshift/web/blob/ddd08bad9526f8e67109ef4c49298ddf4d62686b/src/components/Trade/TradeInput.tsx#L86-L89
and the `estimatedGasFees` was also added to `tradeDeduction`, which resulted in double gas fee deduction in gas check.
I don't think anyone would really want to trade all of their ETH for other ERC-20 token because they won't have gas for trading it back, but the same risk also applies now, if the gas fees increase. The above `tradeDeduction` comment says "when trading from ETH, the value of TX in ETH is deducted", and nothing about double fee deduction, so that's not the intended behavior.
Try to trade `your all eth - estimated gas fee` for any other token, and you'll get "Not enough ETH to cover gas".
=> fix: double gas fee deduction

src/index.tsx, src/service-worker.ts, src/serviceWorkerRegistration.ts
feat: add service-worker
`create-react-app` already includes `workbox` for supporting service-workers for PWAs, so no change to the webpack config was required.
However, because `react-scripts` automatically calls `InjectManifest`, the `service-worker` file must include a reference to `__WB_MANIFEST` or the build will fail.  That manifest can be used for doing caching of assets but we're not doing that right now.
closes #1545
Low. The worst case is the service worker doesn't load but that won't cause anything else to stop working. It's possible there's a slight performance decrease when there are a lot of HTTP calls due to the logging of all service worker events.
It's best to test this is an ephemeral environment.
1. Check the Console tab in Developer Tools.
2. Look for `ServiceWorker` …
=> feat: add service-worker

src/pages/ConnectWallet/ConnectWallet.tsx, src/plugins/cosmos/components/modals/Staking/views/Stake.tsx
This fixes the "terms" link in cosmos staking modal
closes #1559
N/A
- Go to Cosmos Staking modal
- Click the `terms` link
- Terms and conditions should open in new tab
=> fix: cosmos staking ToS link

src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts
Fixed error affecting the Max option while trading ETH to include gas fees, moved gas estimation to be included before value is populated in input.
closes #1280 
To risks that I'm aware of.
(Tested using MetaMask on ETH Mainnet
1. Go to the trade widget toward the upper left hand side of the screen.
2. With ETH selected as the input asset, click the max send button.
https://user-images.githubusercontent.com/14836056/164548521-7d553bb8-f214-4071-a81b-8f086de1d9fa.mov
=> fix(TradeInput): max ETH Trade bug covering gas

package.json, yarn.lock
Bump Cypress to `9.6.0`.
N/A
Minor version bump, I didn't see anything in the change-log that would cause an issue.
CI should still pass ✅ 
N/A
=> chore(cypress): bump Cypress to 9.6.0

src/context/WalletProvider/KeepKey/components/RecoverySettings.tsx
I caused a regression to the word entropy constant in a refactor: https://github.com/shapeshift/web/pull/1561/commits/d3474e4092cca0e2baad79bcc6fb05f1aba5d710
This PR fixes that regression.
N/A
Things should be strictly better!
You can now correctly select the recovery word entropy again.
N/A
=> fix: entropy constant regression

src/components/AssetAccounts/AssetAccountRow.tsx, src/components/AssetHeader/AssetChart.tsx, src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/stakingDataSlice/selectors.ts, src/test/mocks/accounts.ts, src/test/mocks/portfolio.ts
This fixes the cosmos balance on asset and account pages which were different (staked amount not included).
This also removes the display of staked amount in case of price chart (now it is only showing the staked amount in case of balance chart).
It is possible there is still another bug, related to the cosmos balance displayed on dashboard. I preferred not to try to fix it since there is a big refactoring going on in https://github.com/shapeshift/web/pull/1479, the fix would probably be pretty ugly right now and hopefully more straightforward to do with the refactoring code.
closes #1541
Code for one selector used widely on asset chart pages has been changed, so it is probably better to do some regression testing on differents assets for their asset chart.
- Go to cosmos account and …
=> fix: cosmos balance on asset and account pages

package.json, yarn.lock
Included: https://github.com/shapeshift/lib/pull/561
This reverts the typo "fix" in chain-adapters: `cosmos-sdk/MsgWithdrawDelegationReward` is actually the "correct" one. It's not documented anywhere, but the amino spec uses this naming. 
N/A
N/A
N/A (this effectively re-breaks the native wallet claim until the new proto-tx-builder is published)
=> chore: bump @shapeshiftoss/chain-adapters to latest

src/assets/translations/main.json, src/context/WalletProvider/KeepKey/components/Label.tsx
"Setting a label is optional and this should be communicated to the user somehow".
- Adds "optional" placeholder and header copy
- Sets button copy to "Skip" when no label has been entered
Closes https://github.com/shapeshift/web/issues/1611
Minimal - cosmetic changes only.
Initialise or recover a KeepKey and set a label, or not, via the Label modal.
=> feat: show that label entry is optional

src/assets/translations/main.json, src/components/Modals/FiatRamps/FiatRampsCommon.ts, src/components/Modals/FiatRamps/config.ts, src/components/Modals/FiatRamps/hooks/useFiatRampCurrencyList.ts, src/components/Modals/FiatRamps/views/Overview.tsx
Show an error when the fiat balance of an asset is lower than the fiat-ramp provider minimum USD amount for selling.
closes #1186 
none
open up the buy/sell modal, select GEM, and choose an asset to sell which has a fiat value lower than $5. you should not be able to continue.
=> feat: error on fiat balance lower than fiat-ramp provider minimum usd

src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/state/slices/portfolioSlice/selectors.ts
Greatly simplify getSendMaxAmount() to be not use swapper.getSendMaxAmount().
It is now: `sendAssetBalance - estimatedFeePadded` and very easy to understand compared to before
This is basically the same logic but previously it was doing it a crazy spaghetti-code fashion passing tons of unneccessary data all over the place.
We can now remove getSendMaxAmount() from swapper which helps keep things loosely coupled and clean.
Sendmax could not work correctly
Test that sendmax still works for trades.
=> fix: refactor getsendmaxamount

src/plugins/cosmos/components/modals/Staking/views/Stake.tsx
This opens the ToS link in staking modal in a new tab.
- [] :nail_care: New Feature (Breaking/Non-breaking Change)
#1559
The "Enter your password" modal is shown, which is not the best UX. 
- Go to staking modal
- Click the `terms` link
- It should open in a new tab
=> fix: staking ToS link - open in a new tab

package.json, react-app-rewired.config.js, yarn.lock
When initially implementing Cypress we stripped `data-test` attributes from the production build as a small optimisation.
With Pendo on the roadmap, we need to ensure these tags are included in the build so that Pendo can work effectively.
There is a relevant discussion on this started by @mrnerdhair here: https://github.com/shapeshift/web/discussions/1477
The general consensus was that this is a thing we want to do.
Noting that @GMSteuart suggested an alternative approach here: https://github.com/shapeshift/web/discussions/1477#discussioncomment-2665320, but in the interest of expediency I'm just stripping out the code that removes the tags for now.
This relates to https://github.com/shapeshift/web/pull/1622, which closed https://github.com/shapeshift/web/issues/1551.
Minimal.
The …
=> chore: do not strip data-test attributes

scripts/sha256sums.sh
Alpha's build process uses a symbolic link for the `/build` folder, which find does not traverse by default. This change will enable [web.patch](https://github.com/shapeshift/alpha/blob/main/web.patch) in alpha to be a little smaller.
*De minimis.*
Need to verify `find -L` works on mac.
=> chore: make sha256sums.sh follow symbolic links

src/Routes/Routes.tsx
This removes the duplicate /connect-wallet route:
https://github.com/shapeshift/web/blob/8f975ac6f1315f96c6666c9e1721230fdfa9fbff/src/Routes/Routes.tsx#L35-L40
N/A
None, currently we route to the first route and the second does nothing.
- The "Connect wallet" page shows no regressions
- Reconnecting wallet modal shows no regressions
=> chore: remove duplicate /connect-wallet route

src/context/WalletProvider/KeepKey/components/RecoverySentence.tsx, src/context/WalletProvider/KeepKey/components/RecoverySentenceEntry.tsx, src/context/WalletProvider/KeepKey/hooks/useKeepKeyCancel.ts, src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
- I added a new hook: `useKeepKeyCancel` used to cancel the wallet + get back to the wallet select route
- It's used by the `AwaitKeepKey` component in both `RecoverySentence` and `RecoverySentenceEntry`
- In case the user unplug the keepkey, it opens and close the modal in order to be redirected to the `SelectModal` view
closes #1614
partially addresses #1610
KeepKey flow could be buggy
- Wipe your keepkey
- Try to recover it, click on cancel when you can, you should be redirected to the SelectModal
- Try to initialize it, click on cancel it's waiting for a keepkey button press, you should be redirected to the SelectModal view
- Try to go anywhere in the workflow, unplug the keepkey from your computer, you should be redirected to the SelectModal view
=> fix: keepkey recovery flow cancel and close events

src/pages/Accounts/AccountToken/AccountToken.tsx
This fixes reloading accounts other than native token accounts, by waiting on `accountSpecifiers` to be populated in state before checking for `isCurrentAccountIdOwner` and redirecting if false:
https://github.com/shapeshift/web/blob/89e26b31f9e46638e9578544486edc663311954e/src/pages/Accounts/AccountToken/AccountToken.tsx#L31
#1657
N/A: if `accountSpecifiers` was ever empty for any reason other than them not being loaded, we'd have some bigger problem here than a regression from this line
- Go to any non-native token page, which effectively means any ERC20
- Click on that asset's account
- Reload the page: The account page should reload properly
- There should be no regressions on native tokens pages - tested with ETH, ATOM, and all Bitcoin accounts
N/A
=> fix(mm/portis): delay `<AccountToken />` redirect until accountSpecifiers are loaded

src/components/Trade/hooks/useSwapper/useSwapper.ts
I tried to use the swapper in production today but got a white screen.
Seems we introduced a bug in https://github.com/shapeshift/web/pull/1626 with a missed optional chain.
When `defaultValue` is not defined, `useWatch` returns `undefined` on the first render because it is called before register, so our `sellAsset` needs optional chaining to access `assetId`.
N/A
Negligeble.
Should be able to use swapper without white-screening.
=> fix: white-screen caused by undefined sellAsset

src/pages/ConnectWallet/ConnectWallet.tsx
This PR fixes KeepKey/native wallet reconnect on an asset's account page by properly encoding the URI of the `assetId` part in `/:accountId/:assetId/` when reconnecting wallet and pushing the `returnUrl`:
https://github.com/shapeshift/web/blob/495260f2a7dbd6b4df2a86f7fed2cd3463e56b67/src/pages/ConnectWallet/ConnectWallet.tsx#L71
The bug that we currently have where reloading an asset page in Native/KeepKey redirects to Dashboard is caused by the fact that `/:accountId/:assetId` really is `/:accountId/:chainId/:assetSubId`, however, the `/:chainId/:assetSubId` part is URI encoded as one entity in the regular app flow when we route to `<AccountAsset />` in `<AssetAccountRow />`, using `generatePath()`:
https://github.com/shapeshift/web/blob/47da0e056eefce23c7d7f85b242c946d902d89e7/src/compon …
=> fix: encode assetId in <ConnectWallet />

src/plugins/cosmos/components/StakingInput/StakingInput.tsx, src/plugins/cosmos/components/modals/Staking/views/Stake.tsx, src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
- add validation on zero crypto/fiat amount
- fix removing a one-char input defaulting to zero
N/A
N/A
- Continue button should be disable on cosmos stake/unstake with 0
- Pressing the delete key on a single digit in staking should bring back empty input
=> fix(cosmos): crypto amount validation fixes

src/components/Trade/TradeConfirm/TradeConfirm.tsx
Fixes an issue that UI shows a green check before even confirming the tx.
~~This is marked as a draft as I can't get passed through the first step to see if it works as expected or not.~~
tested and worked as expected.
closes #845 
none
Go to the trade card and choose a pair to trade, in the confirmation step, the icon between assets should be `->` instead of a green check.
=> fix: dont show green check before trade is confirmed

src/components/StakingVaults/EarnOpportunities.tsx, src/pages/Defi/components/OpportunityCard.tsx
Fixes fox modal opening in "withdraw" or "deposit" tab instead of "overview".
This behaviour was present from defi page and asset page.
This raises the question of consistency with yearn vaults (modal is still opening in deposit / withdraw page depending on where you are calling it from)
https://github.com/shapeshift/web/issues/1656
There is a risk of affecting yearn vaults modal opening, I tested it and there is no regression.
- Go to fox asset page
- Click on foxy opportunity
- Verify the modal is opened in overview tab
- Go to defi page (+ have some fox staked in foxy)
- Click on foxy opportunity
- Verify the modal is opened in overview tab
=> fix: fox modal opening from defi and earn opportunity

src/components/Layout/Header/NavBar/UserMenu.tsx, src/context/WalletProvider/MetaMask/components/Connect.tsx, src/context/WalletProvider/WalletProvider.tsx, src/context/WalletProvider/actions.ts
This reverts commit 4097528e9d32a0266122330df0b52020ddf41fad.
reverts regression found in #1730
N/A
MetaMask should be able to connect as before
=> fix: revert fix(UserMenu): locked metamask not reconnecting (#1667)

src/components/AssetHeader/AssetChart.tsx
This adds the staked amount in asset charts for Yearn/Foxy staking types.
closes https://github.com/shapeshift/web/issues/1645
N/A
- Staked amount should be displayed in asset chart for yearn/foxy active staking
- No regressions exist in case of no active amount
- No regressions exist for Cosmos staking in asset chart
=> fix: foxy and yearn AssetChart delegation balance

src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
Input is already disabled when instant withdrawal is selected -- confirmation needed from someone with a staked FOXy balance.
closes #1441
=> chore: foxy polling and modal changes

cypress/integration/dashboard_spec.ts
We have non-deterministic behavior with the `trade-form-preview-button` element in Cypress, which is adding friction to the CI process.
Commenting this test until we have a fix for it.
N/A
Minimal.
N/A
=> chore: comment flaky Cypress test on `trade-form-preview-button` element

src/components/Trade/TradeConfirm/TradeConfirm.tsx
During swapper refactor, `ZrxExecuteQuote` was renamed to `ZrxExecuteTrade` but we didn't update the error-handling to support this new naming:
https://github.com/shapeshift/web/blob/fd67442e47da2136ddf7148fa3549c330a1b89e5/src/components/Trade/TradeConfirm/TradeConfirm.tsx#L64-L70
This brings back proper error-handling. 
closes #1775
N/A, this is just making it consistent with the previous implementation.
- Make a trade all the way to the MetaMask confirmation popup
- Reject Tx
- "User rejected the transaction" toast should be displayed
=> fix: replace ZrxExecuteQuote with ZrxExecuteTrade

src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/calculateAmounts.ts
- Fixes swapper loading quote state
- Promise.all for slightly faster async quote load
very low
test and see that the "Preview Trade" (submit) button is disabled while loading quote
BEFORE:
AFTER:
=> fix: loading state and promise.all

src/state/slices/txHistorySlice/txHistorySlice.test.ts, src/state/slices/txHistorySlice/txHistorySlice.ts, src/state/slices/txHistorySlice/utils.test.ts, src/state/slices/txHistorySlice/utils.ts
This updates the signature of the `makeUniqueTxId` signature, to be able to support different parts separately.
The reason for that is we currently pass a `tx: Tx` and an `accountId: AccountSpecifier` params and then accesses `txid` and `address` from Tx, but following the swapper refactor and going forward, these two parts might be coming from multiple variables, not only from a single `Tx`.
This is needed for https://github.com/shapeshift/web/pull/1787 to avoid reinventing the serialization wheel. 
N/A
None, this just passes arguments directly instead of passing a `Tx` object and accessing its properties.
Tests should still pass and CI should be happy
=> chore: update makeUniqueTxId signature

src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Status.tsx, src/plugins/cosmos/CosmosAsset.tsx
Remove unneeded refetch, as this is already handled at an RTK-level in `AppProvider`:
https://github.com/shapeshift/web/blob/498a9668dbdf5a3e09e702a670073b087658c54e/src/context/AppProvider/AppContext.tsx#L308-L312
We don't want or need components to be responsible for this data-fetching action.
N/A
Risk that one or more of their duplicates were needed for an unknown reason.
The app, especially UI using market data, should behave the same as before.
N/A
=> chore: remove unneeded market fetch

src/components/AssetHeader/AssetDescription.tsx
For example on `DAI`, the `Show More` button is displayed but the description isn't higher than the collapse.
To fix this, I increased a bit the default height of the description collapse component as 3 lines are a bit higher than 70.
Then I used a ref in order to check the height of the description, if it's higher than the default height of the collapse, we can display the button because it means that the description is longer than the space allowed
I used a useEffect and a setState to trigger the condition again in case the description or the ref element is not set yet
This is the best solution I could find because if we choose to trim the text and add some dots, it will add a lot of complexity (because the description contains some HTML elements, you can trim inside an HTML element …
=> fix: avoid displaying asset description collapse button if the description is small

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts
The existing swapper error handling isn't useful very useful in catching and displaying errors.
This PR removes the existing swapper error handling logic to the bare minimum.
We will follow up with more robust swapper error handling once this PR is merged: https://github.com/shapeshift/lib/pull/632
very low. errors from swapper are still caught and displayed in a toast in the same way.
make sure swaps still work- there are no user facing changes, just simplify the error handling
=> chore: remove useless swapper error handling in web

src/components/Trade/TradeInput.tsx
Was not correctly returning early if there was as error.
This was noticed for and fixes the case of `sellAmount < minimumSellAmount`
almost no risk
Enter a low amount (below $1) and see that it doesnt let you continue with the trade
BEFORE:
AFTER:
=> fix: dont continue to next screen on failure

src/components/Layout/Header/NavBar/UserMenu.tsx
This fixes the wrong icon being shown on outside `<UserMenu />` click by always showing the `<ChevronDown />` icon and as a result, removes the `isOpen` state, which was a previous hack not accounting for outside click.
closes #1807
None that I'm aware of. This removes any open/closed state so it should give us more confidence.
- Go to Dashboard with a connected wallet
- Notice how the icon that shows the user menu is a chevron down icon
- Click on the icon, the user menu opens and the icon should stay as a chevron down
- Click again, the user menu closes and the icon should stay as a chevron down icon
- Proceed again but this time closing the user menu by outside clicking it, it should stay as a chevron down icon
=> fix: remove isOpen state and use chevron down icon

package.json, yarn.lock
Patch version bump Cypress to 9.6.1.
N/A
Minimal - patch release.
Cypress should still pass CI.
N/A
=> chore: bump Cypress to 9.6.1

src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Status.tsx, src/plugins/cosmos/CosmosAsset.tsx
This reverts commit b7ca8078b93f0d24d2d75594bd1e9bd73f4eeb09.
#1808 removed the Cosmos `marketApi.endpoints.findByAssetId` calls that call the Imperator API and fetch market data for a single asset:
https://github.com/shapeshift/web/pull/1808/files#diff-3dda7a66a28b7a86ee7cbd83c820452c54cf2ad7ee596097c633d3f4598d3e98L28
https://github.com/shapeshift/lib/blob/e863695c46aa6550007941e4397fbdfed3f63839/packages/market-service/src/osmosis/osmosis.ts#L52-L54
This reverts it until we figure out how to make `<AppContext />` fetch market data for a single asset (if needed, i.e if there is an assetId in route)
#1808
N/A
- Go to the page of an asset on Osmosis e.g Akash Network on Osmosis
- The asset page should load (or if it doesn't, an Imperator request should be fired and failing)
=> fix: revert "chore: remove unneeded market fetch (#1808)"

headers.js, src/context/AppProvider/AppContext.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Status.tsx, src/hooks/useRouteAssetId/useRouteAssetId.ts, src/plugins/cosmos/CosmosAsset.tsx
Reverts the revert of b7ca8078b93f0d24d2d75594bd1e9bd73f4eeb09
Brings back the XYZ on Osmosis assets, which were showing an infinite Skeleton loading as the request to get the Market data was never fetched for these.
https://github.com/shapeshift/web/pull/1808
This touches `<AppContext />` so as always with this, we should be very cautious, many things can break.
Effectively, there's two layers of `useEffect`s , each with their relevant protection, so the only risk is overfetching market data in `/assets/:chainId/:assetSubId` routes, which itself is mitigated by the fact that there's caching involved.
Tl;dr big risks, low effective risks
- Go to Atom on Osmosis (or any XYZ on Osmosis asset)
- The asset page should load
- There should be no regression on other asset pages
=> feat: revert the revert of "chore: remove unneeded market fetch (#1808)"

src/assets/translations/en/main.json, src/components/Approval/Approval.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/hooks/useSwapperErrors/useSwapperErrors.ts, src/hooks/useErrorToast/useErrorToast.ts
Add `showErrorToast()` utility to translate and display known errors. Currently only handles swapper errors with translations but can easily be expanded.
Replace existing swap error handling to use showErrorToast(e)
Low risk. Nothing should change from a user perspective just how we handle errors under the hood
Nothing should change from a user perspective. Test that swaps still work
This screenshot should never happen under normal circumstances but is an example of what an error will look like to the user.
Error logs example:
=> chore: add error handling hook (swapper)

src/components/Breadcrumbs/Breadcrumbs.tsx
`react-router-breadcrumbs-hoc` confuses `transactions` path with `:assetId` and tries to render it as asset. Adding explicit `/accounts/:accountId/transactions` route solves this. I also did small refactoring of routes to make them more structured
closes #1781 
1. Log into app.shapeshift.com and connect to a wallet
2. Go to `Accounts` page and select account
3. Go to accounts transactions page
=> fix: add explicit transactions route

src/components/TransactionHistory/TransactionsGroupByDate.tsx, src/hooks/useRouteAssetId/useRouteAssetId.ts, src/pages/Assets/Asset.tsx, src/pages/Assets/AssetTxHistory.tsx, src/plugins/cosmos/CosmosAsset.tsx, src/plugins/cosmos/CosmostAssetTxHistory.tsx
This uses the newly added `useRouteAssetId` hook consistently instead of de/serializing it from `chainId` and `assetSubId`. Also removes the now unused `MatchParams` types. 
https://github.com/shapeshift/web/blob/18a70b7ab1324595a4a1db4f7dabc834eda0c500/src/hooks/useRouteAssetId/useRouteAssetId.ts#L5-L24
This isn't updated in `<ConnectWallet />` yet, which has some custom decoding logic, see https://github.com/shapeshift/web/commit/a705b74e7ac38c89c714b83b63637259095cf596.
I'll add it there in a follow-up PR as it's potentially bug-prone and should be tested in isolation.
N/A
This has implications on Tx history (both the page and the right-side component) and Asset pages. Tested it out against previous implementation and we're getting the same `assetId`. 
Tested on MM/Native/Portis
- Go …
=> feat: consistent use of useRouteAssetId

package.json, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts, yarn.lock
Buy asset on the default pair defaults to whatever page the user is on. Some assets (foxy) are unsupported by the swapper and cause problems when visiting those pages.
We now check to make sure we can support the pair and default to fox otherwise
Also check to make sure swapper exists before making swapper calls
Low risk, fixes foxy asset page
Go to foxy page and see that trade area isnt forever loading a quote.
=> fix: default pair for unsupported assets

src/context/I18nProvider/I18nProvider.tsx
This handles interpolations on missing translation strings that fallback to English.
closes https://github.com/shapeshift/web/issues/1857
None, if no interpolation object is existing for the missing translation access, it will work as it did previously, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-polyglot/index.d.ts#L36
- Switch to Russian language
- Try one of the untranslated keys from the issue (Cosmos Get Started / ETH-FOX CTA)
- Substitutions should be made and the same text should be rendered as with English translations
=> fix: interpolation on english fallback

src/components/Modals/Send/views/Address.tsx
Problem:
Strings with special characters in the send modal (if copy-pasted) would give a false valid address when it should actually reject saying an invalid address
RCA:
In the case where the chain adapter is an instance of cosmos, it's smooth sailing. If adapter. validate address returns true we consider a valid address otherwise we say invalid address.
In the case of ethereum however, there is a check in place for valid ENS addresses, i.e. even if ryan.eth is not a "valid" eth address we wait and check if the ens lookup returns a proper value and don't consider it a false invalid. 
The problem is when we don't find a valid ens address we try to do a "Reverse lookup" regardless of whether the value is valid or not. 
Now the issue is the library we use for resolving names …
=> fix: address validation in send modal for special characters 

src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
Replace hard coded ETH feeAsset to become dynamic based on chain id.
closes #1728 (this closes out the last comment that was apart of this work)
Updating a trade on load could be broken if we don't support a specific chain for an asset, but given the assets are hard coded to chains we support this should not happen.
Checking if an initial trade quote is supplied on load of the application.
=> chore: replace hard coded fee asset

src/Routes/Routes.tsx, src/assets/translations/en/main.json, src/assets/translations/es/main.json, src/assets/translations/fr/main.json, src/assets/translations/id/main.json, src/assets/translations/ko/main.json, src/assets/translations/pt/main.json, src/assets/translations/ru/main.json, src/assets/translations/zh/main.json, src/components/Layout/Header/AutoCompleteSearch/AutoCompleteSearch.tsx, src/components/Layout/Header/Header.tsx, src/components/Layout/Header/NavBar/UserMenu.tsx, src/components/Layout/Header/SideNav.tsx, src/components/Layout/Main.tsx, src/components/Layout/PageTransition.tsx, src/components/StakingVaults/AllEarnOpportunities.tsx, src/pages/ConnectWallet/ConnectWallet.tsx
This PR implements the outstanding changes to the demo wallet feature, as defined in [Demo wallet enhancements](https://github.com/shapeshift/web/issues/1637)
Closes #1637 
Most of the changes in this PR are fairly well constrained to new functionality, so I would suggest the risk is minimal/moderate.
There is the possibility of regression in layout on devices with very small screens, most likely on the connect wallet/splash screen. This is mostly due to the stacking of the "View a Demo" button below an additional line of text. 
I have tried to mitigate this with the removal of the ShapeShift Alpha footer, but it is still very tight on screens smaller than iPhone SE.
- All existing functionality should continue to work as expected (on both mobile and desktop).
- The new "demo wallet" …
=> feat: demo wallet enhancements

src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
Trade FeeAsset did not belong in the dependency array for setting default pair
It doesnt matter right now because its always eth and never changes but this was causing problems when adding swappers that support other chains
Low risk. fixes issue with thorchain that isnt merged yet
Nothing should be different from a user perspective. Check that trades still work
=> fix: remove feeasset from dep array

src/pages/Defi/hooks/useFoxyBalances.tsx
`getFoxyOpportunities()` in [packages/investor-foxy/src/api/api.ts](https://github.com/shapeshift/lib/blob/d595252f267baddd5ea47a555a2c815d0b424cf2/packages/investor-foxy/src/api/api.ts#L197) throws on request failure, which happens somewhat often.
We call it in `web` in `getFoxyOpportunities()`, `src/pages/Defi/hooks/useFoxyBalances.tsx`, but don't gracefully handle failures - this was caught by Cypress, which was intermittently throwing in CI, e.g. https://github.com/shapeshift/web/runs/6551637054?check_suite_focus=true
This PR updates `getFoxyOpportunities()` to handle failures.
N/A
Minimal.
No regressions expected - FOXy opportunities should work as expected.
Uncaught error
=> fix: catch foxy opportunity failure

src/components/Trade/TradeInput.tsx
This adds the missing `minLimit` translation param in the trade component, that gets sent to the toast.
Currently, we're seeing the raw translation string instead of the minimum crypto sell amount.
N/A
None
- Enter an amount to swap below the minimum sell amount
- Click "Preview Trade"
- The `Amount too small. The minimum trade amount for this pair is` toast should show the minimum crypto amount in a human-readable precision format of `<amount> <symbol>`
=> fix: add missing minLimit translation param

src/assets/translations/en/main.json, src/plugins/foxPage/hooks/getGovernanceData.ts
This adds a service (hook) fetching the governance data.
This doesn't add the governance component yet, although the wired up component is already available in the `foxpage-governance` branch https://github.com/shapeshift/web/commit/18083d9a479eab7dcc04a4482198a958c7ac5a1a
Wire up will be about committing the aforementioned component used as app code.
Partially tackles #1828
N/A
- Run FoxPage Layout story on storybook
- The last governance proposal should be shown, with working links in title and "See all proposals"
=> feat: add a governance fetching service

src/components/AssetHeader/AssetDescription.tsx
Collapses "About" section for assets when description changes.
closes #1826
Collapsing on any description change may be too broad.
Follow video found in [issue #1826](https://github.com/shapeshift/web/issues/1826)
=> fix: about section collapse

src/assets/translations/en/main.json, src/assets/translations/es/main.json, src/assets/translations/id/main.json, src/assets/translations/ko/main.json, src/assets/translations/pt/main.json, src/assets/translations/zh/main.json
This adds the missing weth parser translations entries, that currently result in WETH Txs defaulting to the raw translation string.
Checked against the unchained weth parser implementation:
https://github.com/shapeshift/lib/blob/0ed73a884dd2088fe704a4114c57f7787ad36dc3/packages/unchained-client/src/ethereum/parser/weth.ts#L24-L27
For ZRX, we don't actually need to add any new translations for it as this is already handled by the `<TransactionTrade />` component, vs. `<TransactionContract />` for the unhandled WETH Txs.
closes #1881
None, this is just copying the `yearn` parser translations into weth.
=> fix: add missing translation entries for WETH parser

src/components/Trade/hooks/useSwapper/useSwapper.ts
We were using an old legacy type for execute quote. This uses the new correct one so we can remove the old one (they have the exact same fields)
no risk. type change
Nothing is different from a user perspective.
=> fix: use correct type for execute quote

src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx
This adds a memo for advanced features Txs **to the Shapeshift DAO validator only**. 
closes #1904
N/A
- Broadcast any Cosmos staking Tx to the ShapeShift validator. Open Tx in explorer, the memo should be `Delegated with ShapeShift`
- Broadcast any other Cosmos staking Tx. Open Tx in explorer, the memo should be empty 
Cosmostation Tx:
ShapeShift DAO Tx:
=> feat: add ShapeShift DAO advanced features memo

package.json, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, yarn.lock
Make trade status swapper agnostic by using the new getTradeTxs() function to get incoming trade txid to determine if a trade has completed
https://github.com/shapeshift/lib/issues/704
Verify that trades still show up as "pending" on the confirm screen before they show up as completed
Low risk. Verify that trades still show up as "pending" on the confirm screen before they show up as completed
=> chore: trade status swapper agnostic

src/plugins/foxPage/components/Governance.tsx, src/plugins/foxPage/components/Layout.stories.tsx
This adds the `<Governance />` component, wired up with the governance service.
This is not app code yet and is just used inside Storybook.
closes #1825
None, just a story
- Open Storybook FoxPage Layout story
- A skeleton should be shown during governance data load
- Governance data should be shown matching Boardroom/Snapshot data after the data is loaded
- Links should be working
=> feat: add <Governance /> component

src/plugins/foxPage/components/FoxTab.stories.tsx, src/plugins/foxPage/components/FoxTab.tsx, src/plugins/foxPage/components/Layout.stories.tsx, src/plugins/foxPage/foxPage.tsx
Fixes 2 warnings related to recent fox page code.
Existing warnings for fox page on develop branch are :
Coming from review comment https://github.com/shapeshift/web/pull/1879#pullrequestreview-987068820
Risk is the change of tab on fox page is not working properly anymore. I tested it and it's working fine.
- Go to fox page
- Verify tab change is still working fine
- No more warnings related to fox page in console
=> fix: fox page warnings

src/components/Modals/FiatRamps/views/RampsList.tsx
Fixed buy or sell modal overflow issue on mobile devices
closes #1804 
N/A
- Open dev server
- Login
- Click on buy / sell crypto from the nav
=> fix: buy or sell modal overflow issue on mobile

cypress/integration/login_spec.ts, src/assets/translations/en/main.json, src/context/WalletProvider/NativeWallet/components/NativePassword.tsx
Added password confirmation for the wallet creation flow to improve UX and secure their password
Closes https://github.com/shapeshift/web/issues/1919
N/A
- Go to the home page of the web application (Log out from the dashboard if you are logged in)
- Try creating a new shapeshift wallet or a native one
=> feat: confirm password for wallet creation flow

src/components/AssetIcon.tsx, src/components/Icons/KeplrIcon.tsx, src/pages/Defi/components/OpportunityCardList.tsx, src/pages/Defi/hooks/useFoxyBalances.tsx, src/plugins/cosmos/components/AssetClaimCard/AssetClaimCard.tsx
This tackles most of the current warnings and errors in the build.
- add checks in `AssetIcon />` to early return null in case there is no `src` nor `symbol` props (during `sellTradeAsset` load)
- camelCases `≤KeplrIcon />` class attributes
- use unique keys in the mapped over `<OpportunityCard />`s in `<OpportunityCardList />
- check for Ethereum chain support in `useFoxyBalances` hook (the newly added Keplr wallet only supports IBC chain, meaning the DeFi section currently throws on `chainAdapter.getAddress({ wallet })` call since the instantiated `ChainAdapter` is an `EthereumChainAdapter`
N/A
The only potential risk is on FOXy balances, which I've regression tested and is still working fine on MetaMask
- asset icons (including Keplr icon) should still be shown across the app
- FOXy …
=> fix: warning/error spew

public/ipfs-404.html
Adds `/public/ipfs-404.html`, which redirects users who would otherwise get IPFS 404s to the root page.
Closes #1155. Closes #1932.
_De minimis._
Verify that e.g. `https://app.shapeshift.com/defi` redirects to `https://app.shapeshift.com/#/defi`.
=> feat: add ipfs-404.html

src/context/I18nProvider/I18nProvider.tsx
This tightens the `onMissingKey` check in case the translation key is a valid key, but isn't a string e.g an object containing more translation keys.
N/A
N/A
- Translations are still working
- Change a translation property to be an `Record<string, string>` object of translations instead of a key. The app shouldn't crash, no error should be thrown and the raw translation key should be shown.
=> fix: tighten onMissingKey checks

src/components/AssetSearch/AssetSearch.tsx, src/components/Trade/SelectAsset.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts, src/components/Trade/types.ts
Fixes the uncaught type errors that occur in `useSwapper.ts` and `TradeInput.tsx` on unhandled network request failures by updating the types to correctly reflect that `TradeState` and `TradeAsset` properties can be `undefined`.
Also adds some missing `await`s.
Closes https://github.com/shapeshift/web/issues/1945
This is a refactor, so no changes to behaviour are expected, though we should check for regressions.
Confirm that the trade component still works as expected.
N/A
=> fix: uncaught type errors in Trade component

src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/types.ts
Remove some unused types related to swapper. Removing this will allow us to safely remove "statusReason" and "success" from return values of swapper buildTrade() and getTradeQuote()
N/A
no risk.
Minimal testing needed - This is a very low risk PR removing types
=> chore: remove unused types

src/plugins/foxPage/foxPage.tsx
Adds back the `<AssetMarketData />` component for FOXy after it went away in https://github.com/shapeshift/web/pull/1840 mergefix
https://github.com/shapeshift/web/issues/1771
N/A
- Market data should be shown for both FOX and FOXy in the Fox Page
=> fix(foxPage): add back `<AssetMarketData />` for FOXy

cypress/factories/0x/ethFoxRate.ts, cypress/factories/0x/ethUsdcRate.ts, src/lib/address/ens.ts, src/test/mocks/txs.ts
This replaces all occurences of `0x0000000000000000000000000000000000000000` with imported `AddressZero` from ethers.js:
https://github.com/ethers-io/ethers.js/blob/a71f51825571d1ea0fa997c1352d5b4d85643416/packages/constants/src.ts/addresses.ts#L1
N/A
N/A, this is the same string
N/A
=> chore: use AddressZero const from @ethersproject/constants

src/plugins/bitcoin/index.tsx
fix: bitcoinChainAdapter reference was wrong
The code works because ethereum.Configuration and bitcoin.Configuration are the same code.
N/A
None
Shouldn't change anything but would affect Bitcoin stuff?
=> fix: bitcoinChainAdapter reference was wrong

src/pages/Defi/hooks/useFoxyBalances.tsx, src/plugins/foxPage/components/MainOpportunity.tsx
This PR sets the `loading` state field of the `useFoxyBalances` hook to be initially true.
It makes the loading state more reliable and fixes a flash of loading state in presentational components relying on `!(useFoxyBalances().loading)` consumption to render a `<Skeleton />`, which currently render the component, then a `<Skeleton />`, then the component again.
N/A
Components/hooks using `useFoxyBalances` could regress because of this. Tested across the DeFi section and didn't notice regressions.
- There should be no regression in the loading of DeFi opportunities
=> feat: improve useFoxyBalances loading state

src/plugins/foxPage/hooks/useCurrentBlockNumber.ts, src/plugins/foxPage/hooks/useFarmingApr.ts, src/plugins/foxPage/hooks/useLpApr.ts, src/plugins/foxPage/utils.ts
This PR:
- Instantiates ethers providers outside of hooks
- Makes sure that the underlying provider in `getEthersProvider` doesn't get re-instantiated
- Memoizes `fetchPairData`, `calculateAPRFromToken0`, `getTotalLpSupply` and `getRewardsRate`
- Removes the `web3Provider.on('block')` event listeners that use polling
This drastically reduces the number of Infura calls, but should be considered a naive patch for now. Quoting @0xdef1cafe:
> hooks are not singletons
Following this will be a PR creating a shared context for the current hooks to live in (whether that's as a simple singleton, a cached service, a RTK query or a React context is an implementation details) so that they, and their underlying XHRs don't get fired multiple times
Another PR will be coming along, abstracting away the …
=> fix: fox page memoization improvements

src/plugins/foxPage/hooks/getGovernanceData.test.ts, src/plugins/foxPage/hooks/getGovernanceData.ts
This adds tests for the `parseGovernanceData` function.
Also changes the `absolute` property to be a string for consistency and adds stylistic changes, see below.
- test the parsing of full/partial/empty results
- test the parsing of fallback latest proposal/active proposals
- parse to an `absolute` result property as a string for consistency
- use optional chaining when falling back to zero for `absolute`
- add types for a single Boardroom parsed result and use it as a `ParsedBoardroomGovernanceResult[]` return type for `parseGovernanceData`
N/A
None, this only adds tests cases/stylistic changes, and improves typings.
- Governance data should still be working with no regressions
=> feat: add parseGovernanceData tests

src/components/Approval/Approval.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.test.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts
We will need wallet in a couple more swapper calls for thorchain trading
This adds useWallet() to useSwapper() so we dont have to pass it through everywhere and can dismantle some of the spaghetti
low risk swapper changes
make sure swaps still work
=> chore: remove unnecessary passing of wallet into useswaper functions

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
This uses the correct accounts for sends:
- `fromAccountId(accountSpecifier).account` for Cosmos SDK
- `fromAccountId(accountSpecifier).account` for Bitcoin
It also removes a `fnLogger.error` call that was throwing and breaking the flow.
- Related to #1570
- Sends and max sends could still be broken. I have tested max/sends across BTC/ETH/ERC20s/Cosmos as well as stake/unstake/claim on Cosmos SDK.
- Sends should work across BTC/ETH/ERC20s/ATOM
- Receive should work across BTC/ETH/ERC20s/ATOM
- Cosmos advanced features should show no regressions
=> fix: use correct `from` account in handleSendMax

scripts/link-packages.sh
Small fix to make the `yarn link-packages` command usable again
None
1.) From project root, run `yarn link-packages`
2.) ?
3.) Profit
=> fix: modify broken link-packages script

.github/workflows/bootstrap.yml, .github/workflows/pr-cypress.yml, .github/workflows/pr.yml, react-app-rewired/headers/csps/defi/swappers/0x.ts, react-app-rewired/headers/csps/defi/swappers/Thor.ts, sample.env, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/config.ts
Swappers now must call the async function initialize() before being added to the manager.
low risk, changes how swappers initialize behind the scene
Make sure swapping still works
=> chore: initialize swappers

src/plugins/foxPage/FoxCommon.ts, src/plugins/foxPage/components/OtherOpportunities/OtherOpportunities.tsx, src/plugins/foxPage/hooks/useOtherOpportunities.ts
This disables the "Borrowing and Lending" section.
~~Also modifies the Tokemak Borrowing and Lending opportunity to be a Rari opportunity, so we can easily re-enable it by deleting the `isDisabled: true` line, if we need to.~~ Done in https://github.com/shapeshift/web/pull/2063
closes #2060
None
The "Borrowing and Lending" section should be hidden for FOX.
=> feat(foxPage): disable FOX borrowing and lending

src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
- If you already logged in a native wallet, the wallet is already initialized and you don't need to enter your password again
- So I just closed the modal in case the wallet is already initialized, if it's not, then it will redirect you to the `enter-password` route
More info on https://github.com/shapeshift/web/issues/1684#issuecomment-1139718910
closes #1684
No real risk tbh
- Open the app
- Connect to a native wallet
- Connect to any other provider, or even another native wallet
- Try to connect to the first native wallet, it shouldn't prompt the enter-password view
=> fix: close login modal when native wallet is already initialized

src/components/Trade/hooks/useSwapper/useSwapper.ts
This fixes a bug getting quotes for swapper pairs where it was always saying "bitcoin unsupported" if it hit the else
no risk. fixes stuff
no risk. make sure swapper works
=> fix: bad check for supported chain in get quote

src/components/Layout/Header/Header.tsx
Adjust padding to only show up on mobile for the connect banner
no risk
make sure the padding looks correct on desktop and mobile
=> bug: fix banner padding

src/context/WalletProvider/SelectModal.tsx
As we add more wallets, there is a need to update this style to be a grid.
n/a
No risk
Make sure the wallets are selectable, on most screen sizes.
=> feat: turn the wallet select into a grid

.github/workflows/bootstrap.yml, .github/workflows/pr-cypress.yml, package.json, yarn.lock
- Use V4 Cypress action to better handle Cypress 10 in our CI pipeline: https://github.com/cypress-io/github-action/releases
- Minor bump Cypress package to 10.2.0, which adds native support for Apple Silicon - running Cypress locally is now super quick on supported machines 🚀 
N/A
Minimal, as changes only affect CI/Cypress.
- CI should pass
- `yarn test:cypress` should work as expected (and be significantly faster if you're on an M1/M2 machine!)
N/A
=> feat(Cypress): add Apple Silicon support & use v4 CI action

package.json, yarn.lock
This bumps `@shapeshiftoss/market-service` to v6.4.0 and fixes the discrepancy in FOX/FOXy market data.
Release notes:
https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss%2Fmarket-service-v6.4.0
closes #2024
None. This uses FOX market data for FOXy, if there is any regression, this would mean we have bigger problems in getting Coingecko market data for ERC20s.
- FOX and FOXy price charts should show the same values
- FOXy market data data for price and day change should be the same for FOX and FOXy in accounts/assets pages as well as in FOX page
=> feat: bump @shapeshiftoss/market-service to latest

src/plugins/foxPage/components/MainOpportunity.tsx, src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanel.tsx
This PR removes the console errors at `validateDOMNesting` on the Fox Page:
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```
N/A
None, this is just semantic and makes the W3C validator as well as your browser very happy
- FoxPage main/other opportunities should show no visual regressions
=> fix: remove validateDOMNesting foxPage errors

package.json, yarn.lock
Lock `web3` to `1.7.4` to ensure the package version is synced with `lib`.
Relates to https://github.com/shapeshift/lib/pull/847
N/A
Minimal.
Running `yarn dev` whilst linked to `lib` locally should no longer show a `web3` type error.
N/A
=> chore: lock web3 to 1.7.4

package.json, src/components/AssetHeader/AssetDescription.tsx, src/components/StakingVaults/AssetTeaser.tsx, src/plugins/foxPage/foxPage.tsx, src/state/slices/assetsSlice/assetsSlice.ts, yarn.lock
This uses localized asset descriptions from Coingecko / overriden descriptions.
Since the overriden localized descriptions have been duplicated from the English ones, and the Coingecko ones fallback to English if the localized description is an empty string, this should show no user changes in most cases, see:
https://api.coingecko.com/api/v3/coins/ethereum
This will fallback to English if the Coingecko/overriden description for the user selected locale is empty, so from a logic perspective it *should* carry no risks but asset descriptions should still be regression-tested across the app.
- Go to Ethereum asset page with Chinese language set in preferences
- The asset description should show `Ethereum（以太坊）是一个平台和一种编程语…thereum（以太坊）的价格上涨超过50倍`
- Switch to Korean in preferences
- The asset …
=> feat: localized asset descriptions

package.json, yarn.lock
Bump Cypress to 10.3.0.
Adds some additional stats and quality of life improvements.
https://www.cypress.io/blog/2022/06/28/cypress-10-3-0-speed-up-testing-workflows-with-improved-visibility-into-your-test-results/
N/A
Minimal.
CI should still pass.
N/A
=> chore: bump cypress to 10.3.0

package.json, src/context/AppProvider/AppContext.tsx, src/context/PluginProvider/PluginProvider.tsx, yarn.lock
- Honor avalanche feature flag when filtering `supportedChains` based on `KnownChainIds`
- Handle missing chain adapter more gracefully
Low
Dashboard should now load against `@shapeshiftoss/typesv6.3.0`
=> fix: handle avalanche feature flag for supported chains

src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
Whenever the Dashboard is refreshed a race condition with `useWallet` prevents a quote from loading, and we end up with `Searching for best rate...` until the swapper state is changed by the user.
This PR fixes the bug, and wraps `updateQuote` in `useCallback` as a performance optimisation.
N/A
Minimal - a small change to the swapper.
- When refreshing the dashboard we should get a quote for the trade assets
- The swapper should have no regressions
=> fix: get rate on refresh

package.json, yarn.lock
This bumps `@shapeshiftoss/chain-adapters` to latest.
Included releases:
https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss%2Fchain-adapters-v7.3.0
https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss%2Fchain-adapters-v7.4.0
https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss%2Fchain-adapters-v7.4.1
This:
- abstracts `EthereumChainAdapter` into `EVMBaseAdapter`
- adds `AvalancheChainAdapter`
- adds `getRpcUrl()` method to `EVMBaseAdapter`
- bumps the osmosis gas limit, which now broadcasts Osmosis unstake Txs successfully 
N/A
- Possible EthereumChainAdapter regressions
- Ethereum features should still be working with no regressions
=> feat: bump @shapeshiftoss/chain-adapters to 7.4.1

src/assets/translations/en/main.json, src/assets/translations/es/main.json, src/assets/translations/fr/main.json, src/assets/translations/id/main.json, src/assets/translations/ko/main.json, src/assets/translations/pt/main.json, src/assets/translations/zh/main.json, src/plugins/cosmos/components/modals/Staking/views/GetStarted/GetStarted.tsx
This changes the static max APR to a dynamic one in the "Get Started" cosmos SDK (CosmosHub/Osmosis) component.
It also removes the "up to" terminology in all translations using the latin alphabet.
closes https://github.com/shapeshift/web/issues/2102
N/A
- If there is no active ATOM staking for the current account, the "Get Started" component should show "Earn X APY" where X is the current chain APY, similar to e.g the ShapeShift Staking Opportunities default validator row
- If there is no active OSMO staking for the current account, the "Get Started" component should show "Earn X APY" where X is the current chain APY, similar to e.g the TaxiStake Staking Opportunities default validator row
=> feat(cosmos): maxApr -> apr

src/pages/Dashboard/Portfolio.tsx, src/pages/Defi/views/Overview.tsx, src/state/slices/portfolioSlice/selectors.ts
This includes undelegations in the derived total fiat balance (which includes staking data).
The total balance is currently incorrect, as it is not accounting for undelegations. 
Accidentally fixes the DeFi section values: the fact that the DeFi wallet balance is negative / net worth is incorrect is actually a consequence of the incorrect total fiat balance, rather than a bug in itself.
- closes #2112
Isolated to portfolio balances / DeFi overview, for wallets supporting IBC staking.
- Undelegate some ATOM, so that wallet ((wallet fiat balance + delegated assets fiat balance) - undelegated assets fiat balance) is negative
- The DeFi section "Net worth" should show the total of wallet fiat balance + delegated assets fiat balance + undelegated assets fiat balance
- The DeFi section "Wallet …
=> fix: include undelegations in total fiat balance

src/pages/Dashboard/Portfolio.tsx, src/pages/Defi/views/Overview.tsx, src/state/slices/portfolioSlice/selectors.ts
This includes undelegations in the derived total fiat balance (which includes staking data).
The total balance is currently incorrect, as it is not accounting for undelegations. 
Accidentally fixes the DeFi section values: the fact that the DeFi wallet balance is negative / net worth is incorrect is actually a consequence of the incorrect total fiat balance, rather than a bug in itself.
- closes #2112
Isolated to portfolio balances / DeFi overview, for wallets supporting IBC staking.
- Undelegate some ATOM, so that wallet ((wallet fiat balance + delegated assets fiat balance) - undelegated assets fiat balance) is negative
- The DeFi section "Net worth" should show the total of wallet fiat balance + delegated assets fiat balance + undelegated assets fiat balance
- The DeFi section "Wallet …
=> fix: include undelegations in total fiat balance (#2114)

src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
When they changed their buy or sell asset it was incorrectly trying to recalculate amounts using the previous sell asset value and the newly selected sell asset.
- Now it updates recalculates new amounts based on the current trade FIAT amount.
- Also fix dependency array for handleSellClick
Low risk bug fix
See that switching the buy or sell asset does not mess up the amounts previously entered
=> fix: reset trade amount to fiat amount when they toggle assets

package.json, yarn.lock
Bump unchained-client to v9.2.0 which includes automatic websocket reconnect logic
- Medium: websocket client logic moved around and reworked some which does have the possibility for a missed edge case
- Keep an eye on the network tab (filter by WS) and make sure you always see a `pending` connection to each chain supported
- active (pending) websocket connections
- reconnect scenario: you can see one set of connections was only open for ~1min, but there is still a live set showing pending which shows the reconnect logic working
=> chore: unchained-client v9.2.0

src/components/Modals/Send/TxFeeRadioGroup.tsx
There was bad logic for determining the fee symbol. Replace with `selectFeeAssetById` selector.
Low
Ensure the correct fee asset shows on the confirm send modal
- Ethereum/ERC20s: `ETH`
- Bitcoin: `BTC`
- Cosmos: `ATOM`
Before:
- Bitcoin
- Cosmos
After:
- Bitcoin
- Cosmos
=> fix: use the correct fee symbol in send modal

package.json, yarn.lock
fix: bump chain-adapters version to fix KK showOnDevice issue
Fixes the issue with always showing the eth address on the KK when requesting the address from the device. This was due to a refactor in `chain-adapters`. The issue was fixed in the latest `chain-adapters`.
closes #2150 
1. Connect Wallet -> KeepKey
=> fix: bump chain-adapters version to fix KK showOnDevice issue

src/components/Modals/FiatRamps/config.ts
This adds support for the newly supported USDC and USDT stablecoins for Banxa sell orders.
N/A
None, this is just adding some new supported sell assets, for Banxa only
- Have 50$+ of USDC/USDT in your wallet, or monkey-patch this line to `disabled={false}`:
https://github.com/shapeshift/web/blob/8770737be7fe61363970659bfaf51d76c1361377/src/components/Modals/FiatRamps/views/Overview.tsx#L250
- Go to Banxa ramp option's sell tab
- USDC and USDT should be available as sell assets
- Banxa partner tab should open with USDC/USDT populated
=> feat(banxa): support USDC and USDT sell orders

package.json, src/assets/translations/en/main.json, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, yarn.lock
Add toast for invalid trade pairs.
- When a user is selecting assets to trade, a state where two trading assets that are not supported by any current swappers can happen. In that situation, we assume that if a swapper is NOT returned, the two assets are not supported by any current swappers.
closes #2152 
- This is a very minimal risk, given it just expands on the current logic of how to handle a best swapper not being returned.
- With the thorchain feature flag turned on (locally, you currently have to hard code the `REACT_APP_FEATURE_THOR` const to `true` inside of `.env`), choose `BTC` (or some asset that is supported by thorchain) for the buy asset. With `ETH` as the sell asset and `BTC` as the buy asset, change the buy asset to something that is not supported by Thochain (shiba Inu). …
=> feat(swapper): add toast for invalid trading types

src/context/WalletProvider/WalletViewsSwitch.tsx
Wrap `onContinue` in a `useCallback` to avoid an infinite loop caused by `history` changing.
N/A
Small, though this does touch wallet switching.
- Switching wallets should work
- Switching to a KeepKey should work
- No "maximum call depth exceeded" error should show in the console
N/A
=> fix: avoid infinite render

src/components/Trade/TradeConfirm/TradeConfirm.tsx
Added order routing protocol information in confirm trade modal
closes #2174
N/A
- Login to the app
- Initiate a trade preview
Before
After
=> feat: show order routing protocol in confirm trade modal

src/components/Modals/FiatRamps/views/Overview.tsx
We refactored `Overview.tsx` in https://github.com/shapeshift/web/pull/2188 to use the helpers in `@shapeshiftoss/caip`.
The behaviour changed slightly as the CAIP helpers will throw if the input is invalid, rather than silently failing.
This PR ensures we have an `assetId` before calling `fromAssetId`.
N/A
Minimal.
1. Click buy/sell crypto
2. Pick a fiat ramp provider
3. Should not whitescreen
N/A
=> fix: onramp undefined assetId

src/components/AssetAccounts/AssetAccountRow.tsx
fixes a small regression noticed by product
* we should only show the fee asset "exponentiated" icon on tokens
* we should only show the chain name label above tokens, not on top level accounts
all fee/account assets have an assetNamespace of `slip44` - if it's not this it's some type of token
on the given chain
n/a - noticed by product
other icon may render incorrectly
account page shouldn't show a little fee asset icon to the top right of accounts - they should only
appear for tokens
before - BTC incorrectly showing small BTC icon on top right
after - small icons of fee asset on top right for tokens, not on top level accounts (BTC)
=> fix: don't show 'exponentiated' icons for fee assets/acccounts on account page

src/plugins/foxPage/foxPage.tsx
This adds a `zIndex` prop to the `<MenuList />` rendering the Fox Page asset tab selection, fixing the main opportunity icon that's currently on top of it because of some higher z-index value.
closes https://github.com/shapeshift/web/issues/2205
None.
- Open the Fox Page tab selection on mobile
- The main opportunity icon should not be on top of the menu
=> fix(foxPage): fox assets <MenuList /> zIndex

package.json, yarn.lock
fix: fix hdwallet-core dependency resolution
in `package.json` right now we're forcing the resolution of hdwallet-core version to 1.25 which is causing many duplicates of the dependency to be installed.
- [] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
N/A
N/A
Wallets
before
```
=> Found "@shapeshiftoss/hdwallet-core@1.27.0"
info Has been hoisted to "@shapeshiftoss/hdwallet-core"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "444KB"
info Disk size with unique dependencies: "22.47MB"
info Disk size with transitive dependencies: "22.55MB"
info Number of shared dependencies: 5
=> Found "@shapeshiftoss/hdwallet-keepkey#@shapeshiftoss/hdwallet-core@1.25.0"
info This module exists because …
```
=> fix: fix hdwallet-core dependency resolution

src/assets/translations/fr/main.json
Fixes a smallish little typo using the old `plugins.foxPage.mainStakingTitle` translation in https://github.com/shapeshift/web/commit/e47cdd9574f0d53591b6c17fa5a51212a35881cb - which should use `assetSymbol` as an interpolation variable
N/A
None.
- Switch to French
- In the FOX opportunity, the main staking opportunity should display "Misez vos jetons FOX"
=> fix(foxPage): fox mainStakingTitle translation for french language

src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
This removes some duplicate logic on the native wallet initialization.
Currently, we route to the `/native/enter-password` route. This is already handled by the `useNativeEventHandler` hook using events handling:
https://github.com/shapeshift/web/blob/f7f4e955a4410e8d7065c3f9fa071bf00f97858e/src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts#L22
As a result, the duplicate `history.push` calls are causing duplicate `/native/enter-password` entries which are the root cause of https://github.com/shapeshift/web/issues/2215
The original logic was added in 76a762a88 and became duplicate after f4e25935d
closes https://github.com/shapeshift/web/issues/2215
That has potential risk on the native wallet initialization feature. Effectively, tested out the whole flow and didn't …
=> fix: remove duplicate native wallet logic

src/context/WalletProvider/SelectModal.tsx, src/context/WalletProvider/WalletViewsSwitch.tsx
This fixes the dead click on a wallet select button, after selecting the same wallet and clicking back.
Additionally, renames the `key` variable in `<SelectModal />` to `walletType`, as the previous naming didn't make it obvious what was that variable referring to, and added friction to debugging.
closes https://github.com/shapeshift/web/issues/2214
There shouldn't be any, the previous check was checking for the `/` route, which looks like the intent was to refer to the initial wallet select route, but that route is actually `/select`. 
- Open the wallet select modal
- Select a wallet
- Click the back button
- Clicking the same wallet button again should work
=> fix: dead click on same wallet selection after clicking back

src/assets/translations/en/main.json
Currently, the `failed` translation in `modals.withdraw.status` uses the `deposit` word instead of `withdraw` 
N/A
None.
- Applies to Foxy and Yearn failed witthdraws, which might be a tricky state to get to
=> fix: modals.withdraw.status.failed translation

src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx
This fixes the TVL in the yearn overview modal, which is currently using the raw TVL value and needs to be divided by a million
N/A
The TVL of Yearn opportunities rows should be the same as the one in the modal that opens on click.
=> fix: yearn overview modal tvl

src/state/slices/txHistorySlice/txHistorySlice.ts
Reduces the page size for TX requests to the Avalanche node from `100` to `10`.
Closes https://github.com/shapeshift/web/issues/2231
Minimal - more requests will be made addresses with a large numbers of Avalanche transactions.
1. Enable Avalanche feature flag
2. Load the transaction history page
3. Note that the `pageSize` query param for Avalanche transaction requests is `10`, and Ethereum transaction requests is still `100`.
=> feat: reduce tx page size for Avalanche

src/context/AppProvider/AppContext.tsx
This fixes a visual regression introduced where we we wrongly render a '0' char, assuming it to be false where it is
actually falsy:
https://github.com/shapeshift/web/blob/c515747e2e67764c774f3f8e593121beeeab93d2/src/context/AppProvider/AppContext.tsx#L342
React only skips rendering for a component when its return value is
null, false, or undefined, see [React docs](https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored).
N/A
None, this just casts the nullish value (the number 0) to an actual boolean
- Reload the app with CMD + Shift + R
- There shouldn't be a '0' char on the top left corner
=> fix: zero (0) char displayed on app load

src/plugins/foxPage/hooks/useOtherOpportunities.ts
This removes the V2 Fox Farm opportunity from Fox Page's farming opportunities
closes https://github.com/shapeshift/web/issues/2302
None
- The V2 farming opportunity should not be visible anymore
=> feat(foxPage): remove Uni V2 Fox Farm

package.json, src/state/slices/validatorDataSlice/constants.ts, yarn.lock
Update osmo validator to shapeshift instead from taxistake.
Update to latest swapper (affiliate fee)
Low risk. use different default validator
test osmo staking
=> fix: osmo validator to shapeshift

src/features/defi/providers/foxy/components/FoxyManager/FoxyCommon.ts, src/plugins/foxPage/components/AssetActions.tsx, src/plugins/foxPage/foxPage.tsx, src/plugins/foxPage/utils/getFoxPageRouteAssetId.ts
This fixes the "Get FOXy" and "Get Started / Manage" links for the main FOXy opportunity in the Fox Page following the DeFi UI refactor.
Also does some housekeeping by cleaning up the now unused `FoxyCommon` module as well as refactoring the `getFoxPageRouteAssetId` to use `foxyAddresses` from `@shapeshiftoss/investor-foxy` for consistency.
closes https://github.com/shapeshift/web/issues/2264
Minimal, isolated to one specific part of the Fox Page.
- In the FOXy tab of the Fox Page, "Get FOXy" should open the FOXy modal
- In the FOX tab of the Fox Page, "Get Started / Manage" should open the FOXy modal
=> fix(foxPage): defi modal history push

src/config.ts, src/lib/globals.ts
The `globalThis.isShapeShiftMobile` will be set to true via injected JavaScript from the new mobile app.
I've verified that the injected JavaScript runs before `config.ts` and returns true. This config variable can be used in the future to show different content as needed (such as a different wallet flow for the mobile app).
N/A
None. The worst case is that `isMobile` reports `false` when it should report `true`.
Requires new mobile app for testing
Mobile
Desktop
=> feat: add config to check if app is running in mobile

.eslintrc
This enforces the react-hooks/exhaustive-deps rule, which we usually skip with eslint-disable-next-line directives when needed, so we are safe with erroring vs. emitting warnings.
N/A
None
- Add some unused dependency in a useEffect() or useMemo() deps array
- `yarn lint` should not be happy
develop:
This diff:
=> feat: enforce react-hooks/exhaustive deps

src/assets/translations/en/main.json, src/features/defi/components/Deposit/Deposit.tsx, src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts, src/features/defi/contexts/DefiManagerProvider/DefiManagerProvider.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimConfirm.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimRoutes.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimStatus.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Claim/CosmosClaim.tsx, src/features/defi/providers/cosmos/components/CosmosManager/CosmosManager.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/CosmosDeposit.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/DepositCommon.ts, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/DepositContext.ts, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/DepositReducer.ts, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Confirm.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Status.tsx, src/features/defi/providers/cosmos/components/CosmosManager/LearnMore/CosmosLearnMore.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosEmpty.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/WithdrawCard.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/CosmosWithdraw.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/WithdrawCommon.ts, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/WithdrawContext.ts, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/WithdrawReducer.ts, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Status.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/WithdrawType.tsx, src/plugins/cosmos/utils.ts
This adds a new provider for Cosmos staking. Included in this PR:
- Staking
- Unstaking
- Claim
- Display of TVL, APY, staked balance/current active unbondings list in the modal
- Get Started / Learn More modal
This does **not**:
- wire the implementation just yet, this is done in https://github.com/shapeshift/web/pull/2295
- fix the current issues with the existing implementation WRT subtracting gas fees from the percentage estimation. This was originally intended in https://github.com/shapeshift/web/pull/1703 and will be following this PR, with a systematic, optional gas fee subtraction for all DeFi modals
- None in this PR. This does not route the provider yet.
- Current Cosmos DeFi modals should still open with no …
=> feat: cosmos defi UI part 1: Cosmos DeFi provider

src/components/Delegate/StakingOpportunities.tsx, src/components/StakingVaults/AllEarnOpportunities.tsx, src/pages/Defi/components/OpportunityCard.tsx
This wires up the new Cosmos DeFi UI components.
- This is a wire-up issue. I've tested in the various places that the old UI isn't opened (this would be caught by tsc) but operations should test that the routing works for all consumers of Cosmos staking modals. 
- See risks.
=> feat: cosmos defi UI part 3: modals routing

src/state/slices/portfolioSlice/selectors.ts
Small portfolio selector safeguard in case no cosmos account is found for the passed accountSpecifier (if e.g `''` is passed as an accountSpecifier before they're loaded)
None, this puts additional guards in place.
- Cosmos rewards across DeFi section should still work
=> feat: cosmos defi UI part 4: fix selectRewardsByValidator selector

src/features/defi/components/Deposit/Deposit.tsx
This uses the full wallet balance in `handlePercentClick`, when the 100% option is selected. This applies to all DeFi
consumers of this method, not only Cosmos. TODO copy description from 2233
None, this actually returns the actual wallet balance vs. a possibly off computation before that would result in insufficient balance state in some cases.
- 100% selection across all DeFi opportunities (Yearn/Foxy as well as this new Cosmos one) should select 100% of the wallet balance for said asset.
=> feat: cosmos defi UI part 5: use full balance for 100% handlePercentClick option

src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimStatus.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/CosmosDeposit.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/CosmosWithdraw.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimStatus.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
This removes the `react-hooks/exhaustive-deps` directives across DeFi UI providers. We should be safe, and even safer, using the dependencies that are currently skipped.
N/A - housekeeping
Low. They could be unexpected runs with the added dependencies, but effectively, the dependencies we react on are either effectively stable, or dependencies we actually **want** to react on.
- General regression test of DeFi providers - can be done with Keplr/Metamask with no need to actually broadcast a Tx.
=> feat(defi providers): remove react-hooks/exhaustive-deps directives

src/hooks/useBalanceChartData/cosmosUtils.test.ts, src/hooks/useBalanceChartData/cosmosUtils.ts, src/hooks/useBalanceChartData/useBalanceChartData.test.ts, src/hooks/useBalanceChartData/useBalanceChartData.ts, src/state/slices/portfolioSlice/portfolioSliceCommon.ts, src/state/slices/portfolioSlice/selectors.ts, src/state/slices/validatorDataSlice/validatorDataSlice.ts
* there was cosmos specific asset logic stinking up the balance chart. this moves it out to the selector layer and generalizes it to support all assets capable of delegation, and includes delegation, redelegation, and pending redelegation balances.
* balance charts should be faster on initial load as we no longer debounce to guess when tx history is loaded - we now know as we fetch historical tx's restfully and set a loaded state on completion
* this cleanup gets the balance charts in a better place to be turned into rainbows.
TODO
closes #1874 
this should actually fix the disparity between the right hand side of the charts and the total portfolio balance displayed. they still use different logic to calculate the same total but this can be unified in an additional PR.
* a general …
=> chore: simplify balance charts

src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Status.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Status.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Status.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Withdraw.tsx
This wraps DeFi provider event handlers in callbacks, giving us referentially stable callbacks.
None - housekeeping
Low. This in theory should just give us referentially stable callbacks vs. unstable ones currently.
- General regression test of DeFi providers - can be done with Keplr/Metamask with no need to actually broadcast a Tx.
=> feat(defi providers): add callbacks to event handlers

src/components/Trade/TradeConfirm/TradeConfirm.tsx
1) set txid to sell asset txid instead of buyAsset. The explorer link logic expects a sell asset
2) Fix osmo-specific explorer link logic. It was setting the explorer link to osmosis for all trades out of a cosmos-sdk chain. This was causing problems for thorchain swaps 
https://github.com/shapeshift/web/issues/2339
low risk. fixes incorrect explorer link logic
Do a swap into bch. see that explorer link is correct
=> fix: explorer links

package.json, yarn.lock
Bump `@shapeshiftoss/chain-adapters` from v7.15.0 to v7.15.1, which implements https://github.com/shapeshift/lib/pull/950
Makes Tx history great again after types refactor in https://github.com/shapeshift/lib/commit/944c8d12dc8380734fe197a8c7555c9c1ce903f7
Before:
After:
N/A
None - already tested with linked lib by @0xApotheosis and myself, retested before opening the PR as a sanity check
- Tx history should be great again
=> fix: unrug Tx history swapper info

react-app-rewired/headers/csps/bridges/axelar.ts, src/components/Bridge/BridgeRoutes/Confirm.tsx
When I did the Axelar demo the quote endpoint did not return CORS headers, so I made a passthrough proxy API (`https://9bo26t9rjb.execute-api.ap-southeast-2.amazonaws.com/apotheosis`) to add the needed headers.
I've been in touch with their team and they've now added the needed headers to the URL response, and we can now use it directly.
Note though that we still can't use their APK until they update the SDK's REST service to include the needed headers. I've reached out to them about this, too.
Relates to https://github.com/shapeshift/web/issues/2347.
Minimal.
The bridge should still be able to get quotes.
N/A
=> chore: remove proxy endpoint

package.json, yarn.lock
Bump `@shapeshiftoss/unchained-client` to consume the Avalanche parser changes made in https://github.com/shapeshift/lib/pull/952 and https://github.com/shapeshift/lib/pull/958.
Gets https://github.com/shapeshift/lib/issues/951 into use.
Minimal, only touches Avalanche parsing.
As per https://github.com/shapeshift/lib/pull/952
N/A
=> chore: consume `unchained-client` Avalanche parser

src/components/TransactionHistoryRows/TransactionTrade.tsx, src/components/TransactionHistoryRows/hooks.tsx, src/components/TransactionHistoryRows/utils.ts
This parses fees using market data for Cow Swaps.
They are not expected to be 100% accurate, but it should give us enough confidence to display fees without resorting to using Cow.fi subgraph or parsing Tx events ourselves in unchained.
- closes https://github.com/shapeshift/web/issues/2279
- This should show no regression for non-cow Txs 
- CowSwap trades should show fees in sell token under
=> feat: client-side cowswap Tx fees parsing

src/lib/logger.ts
* add a new `simpleLoggerFn` in the global `logger` . This is for use in the mobile app where logs don't support CSS.
* default to `simpleLoggerFn` if `isMobile` is `true`
N/A
None
1. Check the Dev Tools console and verify that logs are still being rendered in fancy colors
=> feat(logger): add a simple logger without colors

cypress/support/e2e.ts, package.json, yarn.lock
**Update mock data**
Updates Cypress mock data to match our current array of requests.
**Ignore erroneous exception**
Cypress is getting rugged by an exception that occurs when we get rate-limited by Yearn, which occurs when Cypress is run. We can't even record the Yearn responses without being `403`ed.
This PR creates a pattern for ignoring uncaught errors in Cypress, and ignores the current uncaught exception.
**Cypress version bump**
Bumps Cypress to `10.4.0` and adds caret to allow minor version updates.
https://docs.cypress.io/guides/references/changelog#10-4-0
N/A
Minimal.
N/A
=> fix: unrug CI

package.json, yarn.lock
⚠️  Blocked by https://github.com/shapeshift/lib/pull/963 - update yarn.lock and release notes link when merged
This bumps swapper to [v9.0.1]() (TODO: void link, post release notes when released), fixing the non-zero ShapeShift fees for cow swaps.
closes https://github.com/shapeshift/web/issues/2362
- isolated to `cowBuildTrade`, which in web means only the cow swaps are affected by this change
- With the `CowSwap` flag on, input some assets/amount to be swapped through CowSwap
- ShapeShift fees should be 0
=> fix: display 0 ShapeShift fees for cow swaps

package.json, src/components/Trade/TradeConfirm/TradeConfirm.tsx, yarn.lock
Uses the Cow Protocol Explorer as the `txLink`, which forms the URL for the "View Transaction" link on the `TradeConfirm` component.
Example of a generated transaction link: https://explorer.cow.fi/orders/0xafcf8125f2bc673056a40d4fd37983d3053b0428c4ab079ee0cffdf92df4ecfec2090e54b0db09a1515f203aea6ed62a115548ec62f49e5a
This can be merged beforehand, but it requires https://github.com/shapeshift/lib/pull/964 to be linked before it can be tested, as currently the `sellTxid` is returning as an empty string from `CowSwapper`.
Closes https://github.com/shapeshift/web/issues/2363
Minimal.
Once a swap is complete using CowSwap, the `TradeConfirm` component should correctly link to the Cow Protocol Explorer.
=> feat: use Cow Protocol Explorer URL

src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
We changed trade asset setting logic slightly in https://github.com/shapeshift/web/pull/2285 here: https://github.com/shapeshift/web/commit/92d3eb376bf6794448de73dfadabc72900446671#diff-62ce1d676340482a29d6dcef3d58bd421246f2b07ee978dc64ac7aca931af407L85
The effect is that if we have no amount in either the buy or sell input boxes the assets will reset:
```ts
setValue('buyAsset.asset', buyAsset)
setValue('sellAsset.asset', sellAsset)
```
What we really want is to only reset if we have no selected assets at all - this PR addresses that.
Closes https://github.com/shapeshift/web/issues/2395, specifically comment https://github.com/shapeshift/web/issues/2395#issuecomment-1211399726
Small, though this is a fragile part of the codebase 😬 
Removing the input amounts for both the buy and sell …
=> fix: don't change assets when no input amounts

src/components/DeFi/components/AssetInput.tsx, src/features/defi/components/Deposit/PairDeposit.tsx, src/features/defi/components/Overview/Overview.tsx, src/features/defi/components/PairIcons/PairIcons.tsx, src/features/defi/components/TxStatus/PairIcons.tsx, src/features/defi/components/TxStatus/TxStatus.tsx, src/features/defi/components/Withdraw/Withdraw.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx
- Adds support for pair icons across the Defi components for future usage
- Changed Uniswap icons with fox+eth
closes #2391 
none
=> feat: fox lp icons changed to a pair of fox and eth

src/pages/Defi/views/StakingVaults.tsx, src/plugins/foxPage/hooks/useLpApr.ts, src/plugins/foxPage/hooks/useOtherOpportunities.ts
This brings a consistent APR with the https://fox.shapeshift.com/fox-farming page.
The APR displayed from farming is now Farming APR (yield from farming) + LP APR (yield from LP token fees), the same as in the fox-farming page. Confirmed by product this was the original intent on the fox-farming page and the one we want here as well. 
- closes https://github.com/shapeshift/web/issues/2379
- Possibly more Infura requests - keep an eye on these.
- Go to Fox Page
- Farming APR should match the one in https://fox.shapeshift.com/fox-farming
- Go to DeFi earn tab
- CTA APR should match the one in https://fox.shapeshift.com/fox-farming
=> feat: consistent APR with fox-farming

src/plugins/foxPage/hooks/useOtherOpportunities.ts
This reorders the other opportunities of the Fox Page to show Fox Farming first. 
- closes https://github.com/shapeshift/web/issues/2404
- None, this just reorders things out
- Farming opportunity for Fox tab in the Fox Page is displayed first
=> feat(foxPage): display farming opportunities first

src/Routes/Routes.tsx, src/components/Layout/Header/Header.tsx, src/components/Layout/Header/NavBar/UserMenu.tsx, src/components/Layout/Header/SideNav.tsx, src/components/Layout/PageTransition.tsx, src/components/StakingVaults/AllEarnOpportunities.tsx, src/context/WalletProvider/WalletProvider.tsx, src/context/WalletProvider/actions.ts
This abstracts the demo wallet feature detection into a `isDemoWallet` field into `WalletProvider` state, to be consumed as `state.isDemoWallet` from `useWallet()`.
As we are adding more demo wallet logic, this will reduce the room for errors.
N/A
All the places this diff touches could theoretically show regressions:
- User Menu
- Side Nav
- Transitions
- DeFi Earn tab
- /demo routing 
- Deep linking to demo wallet still works
- All the aforementioned places still work with demo wallet
=> feat: abstract isDemoWallet into useWallet().state

package.json, yarn.lock
Bumps the swapper package to latest:
https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss/swapper-v9.12.1
Includes @0xApotheosis' fix to trade quotes when the `Thor` flag is on.
- closes https://github.com/shapeshift/web/issues/2417
Possible quote regressions, but didn't find any.
- Enable the `Thor` flag
- Select USDC/ETH as a trade pair
- Wait for the initial 1 USDC = x ETH to load when no input is present
- Input any amount of USDC/ETH
- x should still be (around, or exactly) the same
=> fix(trade): thorchainSwapper quote inversion

src/components/Trade/TradeInput.tsx
This removes the `error` const in `<TradeInput />`. All error-handling is currently done in other places and this one is effectively unused. 
Contributes to https://github.com/shapeshift/web/pull/2403
None. This is unused.
- CI is happy
=> feat(swapper): remove unused error var in `<TradeInput />`

src/constants/PublicWalletXpubs.ts
Add demo wallet public keys for litecoin segwit/segwit native
None
- Ensure segwit and segwit native account load on demo wallet for litecoin
=> chore: add public keys for litecoin segwit and segwit native

src/assets/translations/en/main.json
This rewords `trade.errors.rateError` from `trade.errors.rateError` to `We're not able to get a quote for this pair`
- closes https://github.com/shapeshift/web/issues/2179
None
- Get to an errored swapper state by inputting an invalid pair e.g USDC/yvDAI
- The error toast should display `We're not able to get a quote for this pair`
=> feat: reword trade.errors.rateError

src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx, src/components/Modals/Send/utils.ts, src/components/Trade/TradeInput.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/WithdrawReducer.ts, src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawReducer.ts, src/plugins/foxPage/utils.ts, src/state/slices/portfolioSlice/selectors.ts
A refactor to use only use `bnOrZero` when we actually need it.
N/A
Minimal.
N/A
=> refactor: tidy usage of `bnOrZero`

src/components/AssetIcon.tsx, src/components/Modals/FiatRamps/components/AssetSearch/AssetRow.tsx, src/components/Modals/FiatRamps/views/Overview.tsx
This PR removes the hardcoded `coincap` asset images in `<AssetIcon />`. fallback to redux asset icon if `src` not provided.
closes #2409
none
open up buy/sell modal, assets should have icons the same as the app
=> fix: get asset icon from redux assets if asset src not provided

src/components/Modals/FiatRamps/hooks/useFiatRampCurrencyList.ts
This PR:
- monkey patches the AVAX buy asset and gives it a name and `imageUrl` properties in the `if (!reduxAsset)` branch, since with the `REACT_APP_FEATURE_AVALANCHE` flag off, it doesn't exist in the assets slice
- uppercases the `symbol` property in this same branch, since it comes lowercased for all assets
N/A
None, the `addSellPropertiesAndSort` method doesn't have an `if (!reduxAsset)` branch so such monkey patches should be all we need to support assets not in the assets slice.
- Avalanche asset should be displaying the same with the flag on and off
Develop:
This diff:
=> fix(fiatRamps): monkey patch missing AVAX asset name and icon

src/Routes/Routes.tsx
This allows switching the locale with a `lang` queryparam so we can deeplink to specific languages of the app.
closes https://github.com/shapeshift/web/issues/2416
More logic in the main routes handlers, but with the memoization from selector, and the early return from the `useEffect()` we should be 🛍️ 
- On any of the app routes, add `?lang=<someSupportedLang>` e.g `http://localhost:3000/#/connect-wallet?returnUrl=/dashboard&lang=es`
- The app should automagically switch to said locale
- This should work for /demo routes
- This should work both when accessing said URL from the same tab, or when inputting it in a new tab
=> feat: handle language-switching queryparam

src/components/Trade/TradeConfirm/TradeConfirm.tsx
This limits the decimal places of the swapper protocol fee to 6 decimal places to avoid rugging the UI.
N/A
None
- Input some amount/pair to be swapped with CoW
- The protocol fee should have a maximum of 6 decimal places
Develop:
This diff:
=> feat(swapper): limit crypto protocol fee to 6 decimal places

src/components/Modals/FiatRamps/fiat-ramps.md
This adds instructions on how to add CAIP adapter mappings for the fiat ramp abstraction 
N/A
None, just diffes a markdown file
- Instructions are clear
=> feat: add lib instructions to fiat ramps docs

src/pages/Defi/views/StakingVaults.tsx
This routes to the internal fox farm modal with the `FoxLP` and `FoxFarming` flags on.
closes https://github.com/shapeshift/web/issues/2450
None
- With both flags on, internal routing should be used
- With either one of the flag on, or both off, external routing should still be used
=> feat: fox farm internal earn CTA

src/context/AppProvider/AppContext.tsx, src/state/slices/preferencesSlice/preferencesSlice.ts
This makes sure we rehydrate the dayjs language settings on app rehydrate, so that reloading the app keeps the date format of the selected locale.
- closes https://github.com/shapeshift/web/issues/2467
- This lives in `<AppContext />` which is already bloated and fragile, should it live somewhere else?
- Select a language
- Reloading the app should keep the date format
- Changing the selected language should update the date format
- Accessing a language through `?lang=<language>` (either through a new, or appended to the same tab's URL) queryparam should update the date format
=> feat: rehydrate dayjs locale settings on app reload

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Approve.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Approve.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx
Some housekeeping done while working on the original PR (https://github.com/shapeshift/web/pull/2473) - as a separate PR to keep things atomic.
- Related to https://github.com/shapeshift/web/issues/2461
- Related to https://github.com/shapeshift/web/issues/2434
None, double check that the hunks are correct. The diff might look a bit off in some places because of git shenanigans and manual hunk edits, but if you patch this diff in your editor of choice (and most likely after restack/rebase), it will look good.
- CI is happy
- DeFi opportunities are happy (tested as part of https://github.com/shapeshift/web/pull/2473)
=> chore(defi): no div(`1e+${asset.precision}`)

src/context/WalletProvider/KeepKey/components/Connect.tsx, src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts, src/context/WalletProvider/Keplr/components/Connect.tsx, src/context/WalletProvider/MetaMask/components/Connect.tsx, src/context/WalletProvider/NativeWallet/components/EnterPassword.tsx, src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx, src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess.ts, src/context/WalletProvider/Portis/components/Connect.tsx, src/context/WalletProvider/TallyHo/components/Connect.tsx, src/context/WalletProvider/WalletConnect/components/Connect.tsx, src/context/WalletProvider/XDEFI/components/Connect.tsx
This properly sets `isDemoWallet` to false on wallet connect - making sure we avoid:
- the demo wallet banner hanging after wallet connection
- potentially other unwanted side effects from `isDemoWallet` staying set on wallet connect
closes https://github.com/shapeshift/web/issues/2480
N/A
- Connect to demo wallet
- Open the wallet selection modal and connect any of our supported wallets
- The demo banner should disappear after connecting a wallet
=> fix: set isDemoWallet to false on wallet connect

src/components/Layout/Header/Header.tsx
Need to account for the status bar on mobile devices when running in PWA or the new mobile app.
N/A
None
n/a
=> fix: add inset top for mobile

src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts, src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
This properly narrows down ETH support and avoids calling `EthereumChainAdapter` methods with a non-Ethereum-supporting wallet.
Closes https://github.com/shapeshift/web/issues/2495
N/A
- Connect Keplr wallet
- No `wallet.ethGetaddress is not a function` errors are present in the console
=> fix: detect ETH support in fox LP/farming provider/hooks

src/components/Layout/Header/NavBar/UserMenu.tsx
This removes a check in `<UserMenu />` that was causing the wallet label not to show up on native wallet.
Closes https://github.com/shapeshift/web/issues/2493
None
- Native wallet label should be displayed
=> fix: native wallet label

src/components/Approval/Approval.tsx, src/components/Bridge/BridgeRoutes/Status.tsx, src/components/Bridge/components/EditableAddress.tsx, src/components/Layout/Header/NavBar/UserMenu.tsx, src/components/MiddleEllipsis/MiddleEllipsis.tsx, src/components/Modals/Receive/ReceiveInfo.tsx, src/components/Modals/Send/views/Confirm.tsx, src/components/TransactionHistoryRows/TransactionDetails/Address.tsx, src/components/TransactionHistoryRows/TransactionLink.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimConfirm.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimStatus.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Status.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimStatus.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimStatus.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx, src/plugins/cosmos/components/modals/Send/views/Confirm.tsx
Housekeeping PR, the current `address` prop is wrong, what we pass as `address` can be an address, wallet label, or NS domain name.
Additionally, this is namespaced under `components` and could be used for anything not address/domain/wallet label related.
N/A
None
- `tsc` is happy
=> chore: rename <MiddleEllipsis /> address prop to value

src/pages/ConnectWallet/ConnectWallet.tsx
- Fix the outline button on the connect wallet when in light mode
- Make the entire header on the connect wallet screen un-selectable
n/a
n/a
When on the connect wallet screen, in light mode the button should be white
=> fix: outline is dark on connect wallet

react-app-rewired/headers/csps/plugins/foxPage.ts, src/features/defi/helpers/normalizeOpportunity.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/pages/Defi/hooks/useFoxyBalances.tsx, src/plugins/foxPage/foxPage.tsx, src/state/apis/foxy/foxyApi.ts, src/state/reducer.ts, src/state/store.ts, src/test/mocks/store.ts
Rename the `foxyBalancesApi` module/slice to `foxyApi` following the addition of foxy APR RTK query in https://github.com/shapeshift/web/pull/2523
-  [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
N/A
None
- CI is happy
=> chore: rename foxyBalancesApi -> foxyApi

src/components/Modals/Send/views/Address.tsx
- Fix spacing on the send modal
n/a
n/a
=> fix: add spacing to yat banner on send modal

package.json, src/components/Trade/hooks/useSwapper/useSwapper.ts, yarn.lock
Supports the serialization of `GetTradeQuoteInput` type args made in https://github.com/shapeshift/lib/pull/989.
TODO: bump the swapper package to the new major version once it is published, and open this PR for review.
Thor trade quote logic touched - there is a risk of regression here.
Ensure quotes for Thor still work as expected.
N/A
=> feat: use serializable `GetTradeQuoteInput` args

src/Routes/Routes.tsx, src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx, src/context/WalletProvider/WalletViewsSwitch.tsx
This both improves performance and fixes a bug related to the whole layout tree unmounting and remounting on route change.
The `key` prop is used by react, and by extension by react-router as a react library, to uniquely identify components.
By giving a different `key` prop to `appRoute` outer component on each `appRoutes` iteration, we're effectively telling react "this is a whole new component` which is not true, we are effectively mapping over what is the exact same component, only rendering a different `{children}` prop which will cause the whole `<Layout />` JSX tree to rerender.
This currently causes some re-renders producing unwanted behaviors, such as, but most likely not related to the `<WalletButton />` flicker spotted by @reallybeard on route change.
Fixed by **not** providing …
=> fix: don't unmount/remount private routes on route change

src/components/StakingVaults/AllEarnOpportunities.tsx, src/pages/Defi/hooks/useCosmosSdkStakingBalances.tsx
This fixes the default validator not being displayed for KK.
Relates to https://github.com/shapeshift/web/issues/2500
N/A
- Enable the `Osmosis` flag
- Connect a KK
- The default Osmosis validator should be displayed
=> fix: display default osmo validator for KK

src/assets/translations/de/main.json, src/assets/translations/en/main.json, src/assets/translations/es/main.json, src/assets/translations/fr/main.json, src/assets/translations/id/main.json, src/assets/translations/ko/main.json, src/assets/translations/pt/main.json, src/assets/translations/ru/main.json, src/assets/translations/zh/main.json, src/components/TransactionHistoryRows/TransactionGenericRow.tsx
Removes an unused interpolation variable, confirmed by product we will never use it - see linked issue.
closes #2524
None, this is a chore - the interpolation variable was previously unused
- CI is happy
=> chore: remove unused transactionRow interpolation variable

src/assets/translations/en/main.json, src/components/Trade/TradeInput.tsx, src/pages/Dashboard/TradeCard.tsx
- Remove duplicate trade header
closes #2558 
No risk
Going through a trade make sure there are not duplicate headers.
=> fix: remove tab header when axelar is off

src/pages/Flags/Debugging.tsx, src/pages/Flags/Flags.tsx
Need an easy way for people to grab their visitor ID that are helping us test.
This a hidden page so not real risk.
Going to the flags page you will see your visitor ID and be able to copy it.
=> feat: add visitor id to the flags page

src/assets/translations/en/main.json, src/components/Layout/Header/Header.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseModal.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphrasePassword.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx, src/components/Modals/MobileWelcome/MobileWelcomeModal.tsx, src/components/Modals/MobileWelcome/views/ImportSuccess.tsx, src/components/Modals/MobileWelcome/views/Notice.tsx, src/context/ModalProvider/ModalProvider.tsx
Add the new welcome modal UI for mobile users that prompts them to backup their wallet.
You have to manually trigger the modal to see it right now. Follow up PR will be done to trigger the modal.
https://github.com/shapeshift/mobile-app/issues/39
Very small risk to the backup my wallet modal, I adjusted some logic to not allow mobile users to exit.
Make sure you can backup your wallet as normal, and close out of the modal freely.
Use the modal context to trigger the `mobileWelcomeModal` modal
Make sure you can backup your wallet as normal, and close out of the modal freely.
=> feat: add new welcome modal for mobile users

src/components/Trade/TradeConfirm/TradeConfirm.tsx
use sell asset explorer link as buy asset does not always exist right away.
no risk
do osmo -> atom trade or vice versa and when explorer link appears it should go to the osmosis "trade" transaction
=> fix: correct osmo explorer link

.env.base, package.json, yarn.lock
Osmosis and cosmos node urls were reversed, breaking osmosis swapping. Swapping is now working again with this pr
none. fixes incorrect osmosis & cosmos urls
1) Enable osmosis trading feature flag
2) Perform an atom -> osmosis  (or vice versa)  swap and see that it completes with no errors
see testing section
see testing section
=> fix: osmo cosmo urls reversed

src/components/LoadingBody.tsx, src/lib/globals.ts, src/plugins/pendo/components/OptInModal/OptInModal.tsx, src/plugins/pendo/components/OptInModal/OptInModalBody.tsx
- For the mobile app we will be running pendo by default, check the `isMobile` global var if its true --- launch pendo.
https://github.com/shapeshift/mobile-app/issues/38
Small risk that pendo modal doesn't launch correctly
Test the pendo modal is launched on web browsers as normal
Can't really test locally.
Go to the fleak build, and confirm that you still see the consent modal for pendo.
=> feat: auto enable pendo for mobile app

src/Routes/Routes.tsx, src/components/Icons/DeFi.tsx, src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx, src/context/WalletProvider/WalletViewsSwitch.tsx
This PR removes the current console errors in develop:
- gives a "unique" `key` to mapped routes (shared across all mapped routes to avoid creating new references, effectively the same behavior as https://github.com/shapeshift/web/pull/2557 without the react warnings)
- renames `clip-path` to `clipPath` in `<DefiIcon />` to honor react convention of camelCased html tags
N/A
- None. Same behavior, different syntactic sugar, happier compilers
- Ensure there are no ` Each child in an array should have a unique "key" prop` errors emitted from mapped routes
- Ensure there are no <code>Warning: Invalid DOM property `clip-path`. Did you mean `clipPath`?</code> errors emitted from `<DefiIcon />`
- The flickering native wallet on route change fixed in https://github.com/shapeshift/web/pull/2557 …
=> fix: remove console errors

src/context/WalletProvider/MetaMask/components/Connect.tsx, src/context/WalletProvider/TallyHo/components/Connect.tsx, src/context/WalletProvider/WalletConnect/components/Connect.tsx, src/context/WalletProvider/WalletContext.tsx, src/context/WalletProvider/WalletProvider.tsx, src/context/WalletProvider/XDEFI/components/Connect.tsx, src/context/WalletProvider/actions.ts
This moves the provider-setting logic from the silo'd `src/context/WalletProvider/<WalletName>/components/Connect.tsx` components, to the memoized wallet provider context.
Since the provider is now consumed from a single source of truth, this makes sure event handlers are added to a unique instance, both on wallet pairing (wallet connect screen) and load (app refresh).
This will prepare us for properly handling accounts and chain switch events, which currently disconnect the app and should be handled gracefully.
closes https://github.com/shapeshift/web/issues/2585
High. Affected areas are:
- Wallet pairing (after app load, and after disconnecting a wallet than reconnecting the same or another wallet)
- Wallet detection (MetaMask lookalikes should be properly detected, with prioritization …
=> feat: move providers to wallet state

src/context/WalletProvider/WalletContext.tsx, src/context/WalletProvider/WalletProvider.tsx
This moves away from the side effects model in `<WalletProvider />`'s `onProviderChange`, as proposed by @0xApotheosis in https://github.com/shapeshift/web/pull/2586#discussion_r958190835:
> Not blocking, though I'm not a fan of mixing computations with actions in this way.
> 
> A more functional version would have maybeProvider as a constant equal to the evaluation of an IIFE, and the provider events mutated by an action function, say `setProviderEvents()'.
Also adds a new `KeyManagerWithProvider` type and an associated type guard, with stricter provider discrimination and checks.
Relates to https://github.com/shapeshift/web/issues/2585 - which should be closed by the time this follow-up gets merged
In theory this is just changing from a side effects model to a declarative flow with …
=> feat: no side effects on onProviderChange

src/context/WalletProvider/WalletProvider.tsx
This PRs adds support for gracefully handling network change from MetaMask-like wallets.
closes https://github.com/shapeshift/web/issues/2335
High, needs a full wallet regression testing and ensuring there are no unnecessary reloads, both on the current flow and while switching network.
- Connect MM or XDEFI with Mainnet or Avalanche
- Switch networks in your wallet
- The app should refresh to reflect the change i.e the chain menu should show the newly selected chain
- This should work both on wallet connection through the wallet connect modal as well as on app reload
- Ensure there are no console errors when switching networks
Note: When switching from a supported to an unsupported network, the chain menu will disappear - unsupported networks display will be added in …
=> feat: gracefully handle network change

src/hooks/useToggle/useToggle.ts
I found a much cleaner way to create a `useToggle` hook using `useReducer`.
Minimal. `useToggle` is only used in swapper v2 to change between fiat and crypto input, and that still works.
With the `SwapperV2` feature flag enabled, confirm that we can still swap between crypto and fiat input.
N/A - no user-facing changes at present.
N/A
=> refactor: simplify `useToggle`

src/components/Trade/hooks/useSwapper/useSwapper.test.tsx, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/hooks/useSwapper/useSwapperV2.ts, src/components/Trade/hooks/useSwapper/utils.ts, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts, src/hooks/useToggle/useToggle.ts
In paving the way for a `tradeRoutes` refactor, this PR makes the `getDefaultPair` callback a pure function.
Small, no logic changes.
If default assets still load when connecting to a wallet, loading a new page etc we are 🛍️ 
If default assets still load when connecting to a wallet, loading a new page etc we are 🛍️ 
N/A
=> refactor: make `getDefaultPair` a pure function & rename

src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
Fixes a bug where we'd have a `TradeAsset` object with no `Asset` on it. 
This state fails the inverted boolean check (`!(buyTradeAsset || sellTradeAsset)`) and so does not correctly set the default assets on the initial load.
Minimal.
When refreshing the app the default assets should now load first time, every time.
When refreshing the app the default assets should now load first time, every time.
N/A
=> fix: load default assets on refresh

src/components/Trade/TradeRoutes/TradeRoutes.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
DRY out asset selection logic as part of the broader swapper refactor.
Risk that changing assets via the buy and sell buttons in the trade buttons breaks because I accidentally changed the logic.
- Ensure changing between assets works as it always did.
- Check UTXO account selection still works as expected.
See top-level testing notes.
See top-level testing notes.
N/A
=> refactor: consolidate and simplify asset click logic

src/components/Trade/TradeRoutes/TradeRoutes.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts, src/components/Trade/services/useDefaultAssetsService.ts, src/hooks/useEvm/useEvm.ts
Simplifies the default asset setting logic, and turns it into a dedicated service, which inadvertently fixes all known related bugs.
- Switches `getUsdRate` calls to RTK query, cutting network calls to this endpoint by ~70% vs current production build
- Fixes `useEffect` logic so it only fires once, instead of multiple times, which is causing default assets for a connected wallet to be overwritten by default assets (ETH/FOX)
- Correctly resets `ethNetwork` between wallet reconnections
Note, this fixes the bugs across both V1 and V2 swapper.
Closes https://github.com/shapeshift/web/issues/2446
Closes https://github.com/shapeshift/web/issues/2627
Touches default asset setting in the trade component. There is a risk these will not be set correctly.
Default assets are no longer overwritten: …
=> fix: default asset pair issues

src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
This PR consolidates `getAddress` calls within the FOX-ETH Farming/LP DeFi hooks into the `FoxEthProvider` context provider, making it a single-source-of-truth across hooks.
Note: `useFoxEthLiquidityPool` receives `connectedWalletEthAddress` to avoid circular dependencies.
- contributes to https://github.com/shapeshift/web/issues/2609
- contributes to https://github.com/shapeshift/web/issues/2610
None, this reuses the existing `connectedWalletEthAddress` by consuming it from the context.
- All steps of the FOX-ETH Farming/LP modals should still work with no regressions
- No console errors should be emitted from the FOX-ETH Farming/LP modal
- Same as the engineering testing steps
=> feat(foxEth): consolidate getAddress() calls in FOX-ETH LP/farming hooks

src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx, src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
This PR consolidates `getAddress` calls within the FOX-ETH Farming/LP DeFi components into the `FoxEthProvider` context provider, making it a single-source-of-truth across components.
Note: There are still two remaining calls in `useFoxFarming` and `useFoxEthLiquidityPool` which haven't been lifted up yet for performance reasons and will be tackled in a follow-up PR, ~~as we do *not* want to consume the `useFoxEth()` hook there.~~
^ These two calls will still be authored in a follow-up PR to keep things atomic, but consuming `useFoxEth()` is fine since this really just exposes a context provider, which is there either way. We will have to refactor things a bit to avoid circular dependencies, however.
- contributes to https://github.com/shapeshift/web/issues/2609
- contributes to …
=> feat(foxEth): consolidate getAddress() calls in DeFi components

src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/components/Overview/Overview.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/FoxEthLpManager.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx
This adds initial support for account selection in the FOX-ETH LP modal.
The current logic makes it so it *is* possible to handle accounts change, however, we still need the current logic until https://github.com/shapeshift/web/issues/2615 is implemented, so this is an intermediary, hybrid address-getting step which is needed for now.
This does **not** remove the `accountNumber` hardcoding yet.
- tackles https://github.com/shapeshift/web/issues/2609
Reconciliation could be wrong and rug the FOX-ETH LP feature, test accordingly.
- FOX-ETH LP and Farming cards/rows should still be displayed in the DeFi overview/earn sections both with the MultiAccount flag on and off 
- FOX-ETH LP and Farming modals should show no regressions both with the MultiAccount flag on and off 
- Refer to the …
=> feat: account selection FOX-ETH LP 

src/components/Modals/Send/Send.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/Modals/Send/utils.ts, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/hooks/useSwapper/utils.ts, src/context/AppProvider/AppContext.tsx, src/state/slices/assetsSlice/selectors.ts, src/state/slices/portfolioSlice/utils.ts
Renames the usages of the `Cosmos` CHAIN_NAMESPACE to be `CosmosSdk` following https://github.com/shapeshift/lib/pull/1008
⚠️ Merge as a stack from Graphite since this requires CAIP version bump and will break unless all CHAIN_NAMESPACE changes are updated at once
N/A - relates to mutli-account M2 https://github.com/shapeshift/web/milestone/31
None
- CI is happy
- None, as long as this is PR has a green tick, we are good here
=> feat: rename CHAIN_NAMESPACE.Cosmos -> CHAIN_NAMESPACE.CosmosSdk

src/components/AccountAssets/AccountAssets.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/Modals/Send/utils.ts, src/components/Trade/hooks/useSwapper/useSwapper.ts, src/components/Trade/hooks/useSwapper/utils.ts, src/context/AppProvider/AppContext.tsx, src/hooks/useEvm/useEvm.ts, src/state/slices/assetsSlice/selectors.ts, src/state/slices/portfolioSlice/utils.ts
Renames the usages of the `EVM` CHAIN_NAMESPACE to be `Evm` following https://github.com/shapeshift/lib/pull/1007
⚠️ Merge as a stack from Graphite since this requires CAIP version bump and will break unless all CHAIN_NAMESPACE changes are updated at once
N/A - relates to mutli-account M2 https://github.com/shapeshift/web/milestone/31
None
- CI is happy
- None, as long as this is PR has a green tick, we are good here
=> feat: rename CHAIN_NAMESPACE.Ethereum -> CHAIN_NAMESPACE.Evm

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
This adds initial support for account selection in the FOX-ETH farming modal.
The current logic makes it so it *is* possible to handle accounts change, however, we still need the current logic until https://github.com/shapeshift/web/issues/2615 is implemented, so this is an intermediary, hybrid address-getting step which is needed for now.
This does **not** remove the `accountNumber` hardcoding yet.
- tackles https://github.com/shapeshift/web/issues/2610
Reconciliation could be wrong and rug the FOX-ETH farming feature, test accordingly.
- The multi-account selection dropdown should be displayed in the FOX-ETH Farming modal with the `MultiAccount` flag on
- FOX-ETH LP and Farming cards/rows should still be displayed in the DeFi overview/earn sections both with the MultiAccount flag on and …
=> feat: account selection FOX-ETH farming

src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx, src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
Renames the instances of `connectedWalletEthAddress` to `accountAddress` since effectively, this state field will not necessarily refer to the *connected* account anymore, but will refer to the selected account in the `<AccountDropdown />` component after we support multi-account derivation for Ethereum.
- relates to https://github.com/shapeshift/web/issues/2609
- relates to https://github.com/shapeshift/web/issues/2610
- None, this is a change of terminology
- If CI is happy, we are 🛍️  
- Refer to testing notes
- No user-facing changes
=> feat: rename connectedWalletEthAddress -> accountAddress

src/state/slices/portfolioSlice/utils.ts
Spotted while testing https://github.com/shapeshift/web/pull/2657
This adds all our supported UTXOs in `isAssetSupportedByWallet`.
This util is used by fiat ramp for wallet feature detection. As a result
of these being missing, it is currently impossible to buy/sell UTXOs we
support apart from BTC, since they're displayed as disabled.
N/A
None, this is only used in fiat ramps:
```shell
➜  shapeshiftWeb git:(fix_utxos_isAssetSupportedByWallet) rg  -g '**/**.ts' "isAssetSupportedByWallet"
src/state/slices/portfolioSlice/utils.ts
426:export const isAssetSupportedByWallet = (assetId: AssetId, wallet: HDWallet): boolean => {
src/components/Modals/FiatRamps/hooks/useFiatRampCurrencyList.ts
6:import { isAssetSupportedByWallet } from 'state/slices/portfolioSlice/utils'
44:              disabled: …
```
=> fix: add all UTXOs in isAssetSupportedByWallet

src/assets/translations/en/main.json
Noted by mogie - replace `.` here with `?` to fix the grammar.
N/A - noticed by mogie.
When setting up a new wallet we'll now see a `?` instead of a `.` when verifying seed phrase.
See above.
See above.
N/A
=> fix: recovery phrase grammar

package.json, src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx, src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/yearn/components/YearnManager/YearnManager.tsx, src/state/slices/portfolioSlice/selectors.ts, yarn.lock
This adds multi account support for Yearn DeFi opportunities:
- Overview
- Deposit
- Withdraw
closes https://github.com/shapeshift/web/issues/2605
Yearn modal should be fully regression tested - in theory, this brings no changes for now and uses programmatic accountNumber vs. hardcoded accountNumber, but this requires a breaking(ish) change in the lib PR.
- With the `MultiAccounts` flag on, the account dropdown should be present in Yearn opportunities Overview, Deposit, and Withdraw steps
- With the `MultiAccounts` flag off, there should be no user-facing changes nor regressions with the current flow
- Refer to the top-level testing notes
- `console.log` or debug `accountNumber` props in components to ensure the right account number is passed down
- Refer to the top-level testing notes
- …
=> feat: yearn multi account

src/features/defi/components/Deposit/PairDeposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx
This adds initial support for account selection in the FOX-ETH deposit/withdraw steps of the LP modal.
Note: Syncing won't work in the current state as this requires `<AccountDropdown />` to be optionally controlled, which currently isn't the case.
- closes https://github.com/shapeshift/web/issues/2609
Reconciliation could be wrong and rug the FOX-ETH LP feature, test accordingly.
- The multi-account selection dropdown should be displayed at deposit/withdraw steps of the FOX-ETH LP modal with the `MultiAccount` flag on
- FOX-ETH LP and Farming cards/rows should still be displayed in the DeFi overview/earn sections both with the MultiAccount flag on and off (this implies `FoxFarming` and `FoxLP` flags on as Fox Farming and LP opportunities will never be displayed otherwise)
- FOX-ETH LP …
=> feat: fox LP deposit/withdraw account selection

.git-blame-ignore-revs
Add #2691 hash to git blame ignore revs.
N/A
N/A
N/A
=> chore: add #2691 hash to git blame ignore revs

src/components/Layout/Header/NavBar/NavBar.tsx, src/components/Layout/Header/SideNavContent.tsx
For mobile users we need to close the drawer when the user clicks on a navbar item.
closes #2681 
closes #
No risk
On mobile devices, when you open the drawer and click on a navbar item. The drawer should auto close.
N/A
On mobile devices, when you open the drawer and click on a navbar item. The drawer should auto close.
N/A
=> fix: close the drawer when an item is clicked in the navbar

src/assets/translations/en/main.json
Change to balance threshold tooltip to "On dashboard and charts, hide balances below this value"
closes #2692 
No risk
n/a
n/a
Confirm the tooltip has the updated value
=> fix: update balance threshold tooltip

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx, src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx
This hotfixes the `onAccountIdChange` not to be programmatically passed down depending on feature flags.
This is a relic from the initial `<AccountDropdown />` logic, which now handles feature flagging properly for EVM chains:
https://github.com/shapeshift/web/blob/c43bb3fdcd34983135ad5cf63108c2153f805b06/src/components/AccountDropdown/AccountDropdown.tsx#L251-L252
This fixes FOXy claims not working, and by extension, other DeFi opportunities claims.
Hotfix, N/A
All DeFi modal steps will now get passed `onAccountIdChange` properly, which could theoretically produce regressions in the account being used for Txs while fixing claims. Test accordingly. 
- Test all steps for all DeFi modals, including the flagged Osmosis, FOX-ETH LP/Farming but excluding Cosmos and Osmosis. This includes …
=> fix: always pass onAccountIdChange down

src/components/AssetHeader/AssetDescription.tsx, src/components/Card/Card.theme.ts, src/components/Delegate/StakingOpportunities.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseModal.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx, src/components/NestedList.tsx, src/components/StakingVaults/StakingTable.tsx, src/components/TransactionHistoryRows/TransactionDate.tsx, src/components/TransactionHistoryRows/TransactionGenericRow.tsx, src/context/WalletProvider/NativeWallet/components/NativeTestPhrase.tsx, src/pages/Accounts/components/AccountEntryRow.tsx, src/pages/Accounts/components/AccountNumberRow.tsx, src/pages/Accounts/components/ChainRow.tsx, src/plugins/foxPage/components/Layout.tsx, src/plugins/foxPage/components/MainOpportunity.tsx, src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx, src/plugins/foxPage/foxPage.tsx
- Wrap the seed phrase words when they are too long
- Fix sizing of the staking opportunity for cosmos
- Reduce padding of cards
- Reduce padding of tx history rows
- Remove lines for accounts on mobile
- Fix fox page cards to fit better on mobile
n/a
Small risk, no new functionality added --- just styling.
n/a
n/a
Confirm everything looks good on mobile and nothing is running into each other, and scrolling off the screen.
=> fix: mobile styles

src/components/BalanceChart/BalanceChart.tsx, src/components/Button/Button.theme.ts, src/components/Layout/Header/NavBar/NavBar.tsx, src/components/Layout/Header/SideNavContent.tsx, src/components/Modals/Send/TxFeeRadioGroup.tsx, src/components/PriceChart/PriceChart.tsx
- Remove extra padding on charts
- Make the gas selection stack correctly on mobile
- Make the secondary links in the navbar smaller
n/a
no risk, all styles
The gas selector on the send modal should stack.
n/a
When on mobile --- the send modal's gas selector should stack and you should see 3 rows for reach selection.
=> fix: update styles of chart and gas fee selector

src/components/Trade/hooks/useSwapper/utils.ts
[This change](https://github.com/shapeshift/web/pull/2632/files#diff-0f315d183697744fb9d565e7d8f222eb50a96ee74a2ba513081de2fe5295f54b) in https://github.com/shapeshift/web/pull/2632 broke default asset setting for UTXOs.
This PR reverts the part of the PR that broke it.
N/A
Something else breaks that the change was meant to support.
With the `ThorSwap` flag enabled, select a UTXO asset (e.g. BTC), and note that the default trade pair is now ETH:BTC instead of the fallback ETH:FOX.
As above.
As above.
=> fix: default UTXO assets

src/assets/translations/en/main.json, src/components/AccountDropdown/AccountDropdown.tsx, src/components/Modals/Send/views/Confirm.tsx, src/plugins/cosmos/components/modals/Send/views/Confirm.tsx
- Reuse our new `AccountDropdown` component to display what account you are sending from
n/a
this should pose no risk
Confirm that the account that is displayed is accurate
Implemented this the same way we do for the details view, so should act in the same way.
On the confirm screen of send, verify that the account shown is the correct account.
=> feat: add send from to the confirm send screen

src/state/slices/portfolioSlice/selectors.ts
fixes specifically the chart lines for account pages for cosmossdk based chains
note - **this does not fix** the total fiat balance number, staked amount number, just the line itself. future PRs will fix other issues.
closes #2613
* ensure my logic changes are sane
* please read PR description thoroughly
* have a cosmos account with a staked balance
* create a new cosmos account
* send a small amount into the new cosmos account, don't stake an amount yet
* go to the **account** page for the newly added account, note that the balance chart line will now be correct for the account, showing only the newly transferred amount, compared to prod which will show the raw balance of the new account, plus the staked amount from all accounts
before - note the account has a single $0.10 tx in, but is …
=> fix: multi account cosmos balance charts

src/components/AssetHeader/AssetChart.tsx, src/state/slices/portfolioSlice/selectors.ts, src/state/slices/portfolioSlice/utils.ts
fixes fiat and crypto amounts on asset and account pages, see screenshots
does not close but related to #2614
* fiat or crypto total amounts may be incorrect on asset or individual account pages
* check my logic for filtering by optional account and asset ids, given we use the
`PortfolioBalancesById` type we can reuse the same generic reduce logic across multiple selectors
* follow the same testing steps as #2731, but this applies to the fiat and crypto balances show in
the screenshots below
* please note the *staked amount* will still be incorrect, this fixes the fiat and crypto totals
shown
* check that the asset pages aggregates the fiat and crypto amounts across all accounts correctly
* check that the account pages show the individual fiat and crypto amounts correctly
**after** …
=> fix: asset account totals

src/assets/translations/en/main.json, src/assets/translations/id/main.json, src/assets/translations/ko/main.json, src/assets/translations/zh/main.json
Removing a duplicate key `modals.stake` in the translation files and its currently unused strings.
Closes #2747
None.
The changes in these files relate to unused strings, nothing to test.
The changes in these files relate to unused strings, nothing to test.
The changes in these files relate to unused strings, nothing to test.
=> chore: remove translation dupe key and strings

src/components/DeFi/components/AssetInput.tsx, src/components/Trade/Trade.tsx, src/components/Trade/TradeConfirm/ReceiveSummary.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useDefaultAssetsService.ts, src/components/Trade/hooks/useSwapper/useSwapperV2.ts, src/components/Trade/hooks/useSwapper/utils.ts, src/components/Trade/hooks/useTradeQuoteService.ts, src/components/Trade/types.ts
Additional improvements to `swapperV2`:
- Adds and propagates trade slippage (manually set at 0.2% until advanced trade settings are implemented)
- Refactors TradeState initial values
- Fixes protocol fee value display
- Allows for both sell and buy account selection for UTXOs
Minimal to anything not feature-flagged.
- We can now select both the buy and sell asset accounts for UTXOs (`ThorSwap` must be enabled)
- Shows trade slippage with default 0.2% applied
N/A
N/A
=> feat: swapperV2 improvements

src/components/AccountDropdown/AccountDropdown.tsx, src/components/DeFi/components/AssetInput.tsx, src/components/Delegate/StakingOpportunities.tsx, src/features/defi/components/Deposit/Deposit.tsx, src/features/defi/components/Overview/Overview.tsx, src/features/defi/components/Withdraw/Withdraw.tsx, src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts, src/features/defi/providers/cosmos/components/CosmosManager/Claim/CosmosClaim.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Claim/components/Confirm.tsx, src/features/defi/providers/cosmos/components/CosmosManager/CosmosManager.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/CosmosDeposit.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Confirm.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/WithdrawCard.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/CosmosWithdraw.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Withdraw.tsx, src/pages/Defi/hooks/useCosmosSdkStakingBalances.tsx, src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx
closes https://github.com/shapeshift/web/issues/2606
Full regression test needed with the flag off, logic has been revamped to account for multi-account.
- Add a Cosmos account and send some ATOM to it
- Open the Cosmos overview modal for a validator you're currently delegating to on account #0, select account #1 and click "Deposit"
- Notice account #1 is pre-selected at Deposit step, with the right amount to deposit 
- Deposit some ATOM - ATOM should be deposited from account #1
- Disconnect and reconnect wallet, then reopen the Cosmos overview modal and select withdraw with account #1 selected
- Notice account #1 is pre-selected at Withdraw step, with the right amount available to withdraw
- Withdraw some ATOM - ATOM should be withdrawn from account #1
- Disconnect and reconnect wallet, …
=> feat: cosmos DeFi opportunity modals multi-account support

src/components/StakingVaults/AllEarnOpportunities.tsx, src/components/StakingVaults/EarnOpportunities.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/FoxyManager.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimRoutes.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimStatus.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyDetails.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx, src/pages/Defi/hooks/useEarnBalances.tsx, src/pages/Defi/hooks/useFoxyBalances.tsx, src/plugins/foxPage/components/MainOpportunity.tsx, src/plugins/foxPage/foxPage.tsx, src/state/apis/foxy/foxyApi.ts
- Overview
- relates to the closed https://github.com/shapeshift/web/issues/2611
- relates to https://github.com/shapeshift/web/issues/2615
- relates to https://github.com/shapeshift/web/issues/2730
- closes https://github.com/shapeshift/web/issues/2758
Tested with MetaMask (which has only account 0 support) but this could bring regressions forFOXy modal for single accounts, test accordingly
- Add an Ethereum account and send some ETH and FOX
- Stake in some opportunity (or skip this step if already staked in FOXy), reload the app (websocket is currently borked) and click on the opportunity card for it
- Select account 1 and click deposit
- Notice account 1 is pre-selected at Deposit step, with the right FOX amount to deposit 
- Deposit some more of FOX, sign and broadcast it - it should …
=> feat: foxy opportunities full multi-account support

src/components/StakingVaults/EarnOpportunities.tsx, src/features/defi/components/Deposit/PairDeposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/FoxEthLpManager.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Status.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/FoxFarmingManager.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Status.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx
- Overview
- relates to the closed https://github.com/shapeshift/web/issues/2609
- relates to the closed https://github.com/shapeshift/web/issues/2610
- relates to https://github.com/shapeshift/web/issues/2615
- relates to https://github.com/shapeshift/web/issues/2730
Tested with MetaMask (which has only account 0 support) but this could bring regressions for the FOX/ETH modal for single accounts, test accordingly
- Enable the FOX/ETH LP / Farming flags as well as MultiAccount
- Add an Ethereum account and send some ETH and FOX to it
- Stake some FOX into FOX LP, reload the app (to avoid websocket shenanigans) and open Fox Farming from the DeFi earn section
- Select account 1 and click deposit
- Notice account #1 is pre-selected at Deposit step, with the right amount to deposit 
- Deposit …
=> feat: fox/eth full multi account support

.env.app, .env.private
Production ethereum coinstacks have stabilized post merge, so we can switch back to pointing to them for app and private
closes #
None
- Ensure ETH/ERC20s and portfolio load properly
See  above
See  above
=> chore: revert to using prod eth endpoints

src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx
This uses FOXy as an assetId in the FOXy withdrawal modal, ensuring we display FOXy balances consistently vs. FOX/FOXy balances
- relates to the closed https://github.com/shapeshift/web/issues/2611
- Ensure FOXy is used as an asset in the FOXy withdrawal modal
- See top-level testing notes
- See top-level testing notes
=> fix(foxy): use FOXy assetId instead of FOX

src/pages/Trade/Trade.tsx
- Background was running over causing the view to scroll horizontally on mobile
n/a
none
On mobile screen size there should be no scrolling left or right on mobile sizes
n/a
Go to trade page on mobile and confirm the screen doesn't scroll left and right
=> fix: side scroll trade screen

src/context/WalletProvider/Portis/config.ts
We haven't tested portis on the mobile app and it doesn't seem to be working at first glance, so we should remove it and can worry about adding it back in at a later date (just like wallet connect)
closes #
That this change removes portis from more than just the mobile app
Confirm that the portis wallet stills hows up as an option for mobile web and normal desktop web, but does not show up for the mobile app
=> fix: removes portis from mobile app

src/components/Trade/Components/TradeAssetInput.tsx, src/components/Trade/TradeInputV2.tsx
This PR passes the `accountId` prop down both for buy and sell accounts in the `<AssetInput />` of SwapperV2
closes https://github.com/shapeshift/web/issues/2857
- Ensure no regressions with the `MultiAccounts` flag off
- With the `MultiAccounts` flag off, asset input balances in SwapperV2 should show no regressions
- With the `MultiAccounts` flag on, asset input balances in SwapperV2 should show the balance of the selected account number/type, both for buy and sell accounts
- Refer to top-level testing notes
- Refer to top-level testing notes
Develop:
This diff:
=> feat: pass accountId to AssetInputLoaded

src/components/Trade/TradeConfirm/TradeConfirm.tsx
- fix spacing on the gas exceeds message on trade
n/a
no risk
n/a
n/a
when you do a trade and get the gas exceeds % of trade. The alert icon should be spaced correctly on both trade page and trade widget.
=> fix: spacing of the alert message

src/components/Graph/RainbowChart/RainbowChart.tsx
- remove the min/max on the rainbow chart
n/a
no risk
n/a
n/a
turn on rainbow, see the min/max values are gone.
=> fix: remove high low values on rainbow

src/components/Zendesk/zendesk.css
the mobile webview doesn't respect the restricted areas, e.g. notches on iphones.
without this the minimize button ends up hiding behind battery/clock/wifi icons.
this 71px matches the app header height so it looks natural.
this also makes the widget shorter vertically on desktop, but no one cares.
n/a - discovered in develop on mobile
purely isolated to rendering of the zendesk widget when it's open. it can't possibly be worse than
it was.
* point mobile app at `develop`
* open zendesk
* you should be able to close it now!
before/after left/right respectively
before
after what it *should* look like on mobile
=> fix: zendesk maximized on mobile

src/components/Trade/hooks/useSwapper/utils.ts, src/components/Trade/hooks/useTradeAmounts.tsx
Fixes a bug in `setTradeAmountsRefetchData` where we'd get the fee asset of the _buy_ trade asset instead of the _sell_ trade asset.
This was causing gas display issues when trading to assets on different chains.
Closes https://github.com/shapeshift/web/issues/2875
Small - only touches the fee asset in one path of the trade amounts computation.
Get a quote a Cosmos-SDK asset as the sell asset, and an ERC20 asset as the buy asset.
The gas fee should be sane.
As above.
As above.
=> fix: get the correct `feeAssetId` in `setTradeAmountsRefetchData`

src/components/Layout/Header/NavBar/FiatRamps.tsx
Add a subtle shine animation to the buy button
n/a
no risk
n/a
n/a
On the top right buy/sell button you should see it shine.
=> feat: subtle buy button animation

src/context/WalletProvider/KeepKey/components/Connect.tsx, src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts, src/context/WalletProvider/Keplr/components/Connect.tsx, src/context/WalletProvider/MetaMask/components/Connect.tsx, src/context/WalletProvider/NativeWallet/components/EnterPassword.tsx, src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx, src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess.ts, src/context/WalletProvider/Portis/components/Connect.tsx, src/context/WalletProvider/TallyHo/components/Connect.tsx, src/context/WalletProvider/WalletConnect/components/Connect.tsx, src/context/WalletProvider/WalletProvider.tsx, src/context/WalletProvider/XDEFI/components/Connect.tsx, src/context/WalletProvider/actions.ts
Remove `SET_IS_DEMO_WALLET`. Change `SET_WALLET` to set the `isDemoWallet` state.
The only place that `SET_IS_DEMO_WALLET` was called was immediately after a `SET_WALLET` call, so I don't see any reason why it should be a separate action.
Changing `SET_WALLET` ensures that we don't have this bug in the future by forgetting to call `SET_IS_DEMO_WALLET` for a new wallet pairing flow.
closes https://github.com/shapeshift/mobile-app/issues/68
Low - only affects wallet pairing
1. Pair the demo wallet
2. Switch wallets
3. Switch back to demo
Test web wallet pairing for regressions. Test mobile wallet pairing.
=> fix: wallet switching doesn't always turn off demo mode

.env.app, .env.dev, .env.develop, .env.private, package.json, src/components/Trade/hooks/useSwapper/swapperManager.ts, yarn.lock
Updates the `ThorchainSwapper` instance to use a `daemonUrl`.
Handles new shape of `ThorchainSwapper` `deps` in https://github.com/shapeshift/lib/pull/1039.
Keeping in draft until https://github.com/shapeshift/lib/pull/1039 is published.
Closes https://github.com/shapeshift/web/issues/2871
Small - if we can still get ThorSwap quotes we are likely ok.
1. Ensure the `REACT_APP_THORCHAIN_NODE_URL` in `.env` is set to `https://dev-daemon.thorchain.shapeshift.com`
2. Get a ThorSwap quote and observe requests to `https://dev-daemon.thorchain.shapeshift.com/lcd/thorchain/pools` via the network tab. They should be significantly faster (>500ms).
1. Get a ThorSwap quote - it should feel significantly faster than before.
Note, in the network tab, ensure the prefix to `/lcd/thorchain/pools` is …
=> chore: use thorchain daemon

src/components/Trade/TradeRoutes/TradeRoutes.tsx, src/components/Trade/hooks/useDefaultAssets.tsx, src/components/Trade/hooks/useSwapper/useSwapperV2.tsx, src/components/Trade/hooks/useSwapper/utils.ts, src/components/Trade/hooks/useTradeQuoteService.tsx, src/components/Trade/types.ts
Default assets broke when implementing `bip44Params` in https://github.com/shapeshift/web/pull/2877.
This PR fixes default assets and refactors the default asset logic into an explicit callback to give us better control over when it's called.
N/A
Small-medium. Touches default asset and account logic.
Default assets should populate properly again based on the wallet connected, and the current route.
Check ERC20, Avalanche, and UTXO assets across multiple wallets.
As above.
As above.
N/A
=> fix: default assets using `bip44Params`

src/components/Trade/hooks/useDefaultAssets.tsx
This PR fixes the routing between the asset pages of native EVM assets, where the default trading pairs do not get properly refreshed.
closes https://github.com/shapeshift/web/issues/2897
Tested UTXOs and Cosmos SDK default pairs on native wallet as a regression test and EVM default pairs on asset page navigation which all show no regressions, but this could technically break all default pairs, test accordingly.
- When navigating to AVAX or ETH asset from any page (e.g Dashboard), the default pair for that asset is displayed
- When navigating AVAX<->ETH (both directions) asset pages using asset search, the default pair for that asset is displayed
- Navigating from any asset (native / non-native) to any other asset (it can be on the same or on a different chain) page displays the correct …
=> fix: default pair refresh when navigating between native EVM asset pages

src/components/Modals/FiatRamps/views/Manager.tsx, src/components/Modals/FiatRamps/views/Overview.tsx, src/state/slices/portfolioSlice/utils.ts
This PR removes the `ChainIdType` type which was shoehorned for fiat ramps originally pre proper Chain Agnosticism and is now outdated as a type, and superseeded by `ChainId`.
N/A
None
- CI is happy
N/A
=> feat: remove ChainIdType

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/hooks/useTradeAmounts.tsx
This PR fixes the confirmed state for RUNE swapping, using the sell Txid / account data as a buy Txid, so we can react on it to display Tx confirmed state.
closes https://github.com/shapeshift/web/issues/2892
Thor detection logic could be borked and erroneously use the sell side data to serialize the buy Txid for swaps other than RUNE.
- Swaps from RUNE are shown as completed after on-chain completion
- Swaps to RUNE are shown as completed after on-chain completion
- Refer to top-level steps
- Thor detection logic looks sane
- Refer to top-level steps
- No swapper regressions are spotted for other Thor swaps
=> feat: rune swapping confirmed state

src/pages/Trade/Trade.tsx
- Replace the filter and show all transactions
n/a
no risk
Should just work
Go to trade page, and you should see the list of your recent transactions and not just trades.
=> fix: show recent txs instead of trades on trade page

src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx, src/components/Trade/hooks/useSwapper/utils.ts, src/components/Trade/types.ts, src/test/constants.ts
We are using `networkFee` as `networkFeeBaseUnit` in some places, and `networkFeeCryptoHuman` in others.
This PR properly types the difference by updating `DisplayFeeData` to reflect `web`'s  consumption of the gas fee (as crypto human balance) and ensures the values are set as such consistently across all chains.
This fixes the wildly high fee issue we currently have on `develop`.
**Outstanding issues before opening:**
N/A
Touches the consumption and transformation of `networkFees`, medium risk, though fairly quick to determine if it's working as expected.
Get quotes for `0x`, `Cowswap`, and `ThorSwap` and check values on both the quote screen and the trade confirm screen.
As above.
As above.
N/A
=> fix: gas fee base unit

package.json, yarn.lock
Bump swapper to 11.5.1 - this will fix the gas amount on the trade confirm screen for 0x trades.
N/A
Very small - fixes trade quote data.
Get to the confirm screen of a 0x trade - a gas fee should be shown.
As above.
As above.
N/A
=> chore: bump swapper to 11.5.1

src/components/Trade/TradeRoutes/TradeRoutes.tsx
This removes the `setDefaultAssets` dependency in `<TradeRoutes />`'s useEffect, so that we really only call it on routes mount.
Between broadcast and broadcasted step, it was called again setting default values (default asset pair), thus using ETH/FOX values in place of the completed swap's pair values.
The offender of this re-render would most likely be:
https://github.com/shapeshift/web/blob/814c56ac6450bcf78e871af6938c0857613afc14/src/components/Trade/hooks/useDefaultAssets.tsx#L160
Which we need for reconciliation across asset pages.
- tackles https://github.com/shapeshift/web/issues/2873
Default pairs could be borked across the app, test accordingly
- Default pairs show no regressions
- Swapper values (amount/fees etc) don't get updated to weird 0 / invalid values at confirm step …
=> fix: call setDefaultAssets only on `<TradeRoutes />` mount

src/assets/translations/en/main.json, src/components/AssetAccountDetails.tsx, src/components/AssetHeader/AssetChart.tsx, src/components/MaybeChartUnavailable.tsx, src/hooks/useBalanceChartData/useBalanceChartData.ts, src/hooks/useBalanceChartData/utils.ts, src/pages/Dashboard/Portfolio.tsx, src/plugins/cosmos/CosmosAssetAccountDetails.tsx
we can't draw balance charts for assets which we can't obtain an exhaustive tx history.
was waiting for the day we required this, and have a feeling this won't be a temporary feature, so
it's a little over engineered.
apply a ~~blacklist~~ list of color to these assets.
this excludes them from the portfolio chart, or makes the balance chart unavailable on an individual
asset/account page.
n/a - cowboy engineering
fairly small - mostly UI
* connect a native wallet or keepkey
* see there is a warning alert on the portfolio and native RUNE asset page
* note this does not apply to ERC20 RUNE
* this alert should not appear on other asset pages
* ensure there aren't any balance chart regression for other assets vs prod
* criticize my changes in `useBalanceChartData`
* see common testing steps …
=> feat: balance chart asset list of color

src/plugins/pendo/agent/types.ts, src/plugins/pendo/launcher.ts
tracks a visit once with a key of `mobile_app` based on the `isMobileApp` flag when pendo is ready
n/a
* low - look for `trackedVisit` and no errors in the console
* will only run if pendo is enabled
* pendo is enabled by default without consent in the mobile app, consent is required in the browser
* check my code looks sane, and you can see the `trackedVisit` trace log in the browser with pendo
enabled
n/a
=> feat: pendo track visits

src/components/AssetIcon.tsx
- Use the size passed in props to determine the size of the asseticon and network icon
n/a
no risk
no special steps
Icon should be the correct size throughout the app, and the chain icon should scale with the size of the icon.
=> fix: actually use the passed in size for the asset icon

src/assets/translations/en/main.json, src/components/Modals/Settings/SettingsList.tsx
- per IOS requirements, the user needs a way to delete their "accounts" and wallets.
- Added a new button that only shows up on mobile
- Once clicked should delete wallets, and disconnect them.
n/a
No risk to web users
I don't know if this fully works, needs to be tested on an actual mobile device with a wallet.
On the mobile app, open the settings modal. Click the delete accounts and wallet data button. You should see a confirm prompt. Once that happens you should be taken to the splash page.
=> feat: add delete accounts button to settings

src/components/Modals/Settings/SettingsList.tsx
- close the modal after deleting "accounts"
n/a
n/a
n/a
Modal should close now after the "accounts" are removed.
=> fix: close modal after delete

src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useGetTradeAmounts.tsx, src/components/Trade/hooks/useTradeAmounts.tsx, src/components/Trade/types.ts
When toggling assets in `swapperV2` there are a few UI issues that surface when a `useEffect` doesn't fire when expected, or a quote or rate request fails/takes a long time to return.
This can be observed with the gas fee or rate (1 ETH = 333 POO) where they will briefly flash an incorrect value when toggling assets. In some case the they will stay an incorrect value.
This PR clears values we know become stale when an asset changes so they are never shown to the user.
N/A - general swapper improvement.
Minimal - only clears swapper data that is stale.
With `swapperV2` enabled, notice that when toggling assets we don't get a flash of incorrect values in the rate or gas fields.
As above.
As above.
N/A
=> fix: clear stale values on asset toggle

src/components/Trade/Trade.tsx, src/components/Trade/hooks/useTradeAmounts.tsx, src/components/Trade/hooks/useTradeQuoteService.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.tsx
This PR ensures that quote and rates are cleared when assets are changed (as they are no longer valid at this time).
N/A - general swapper housekeeping.
Minimal - any bugs that are surfaced from this PR likely already existed, and are now exposed by it.
We should still always have quotes when we expect to.
That said, this PR likely exposes issues with quote data which may have been fixed down the graphite stack - before rejecting this PR, please check state at the bottom of the stack to see if they have been resolved (yes, in hindsight this PR should have been at the bottom of the stack - derp.
As above.
N/A
N/A
=> fix: clear quote & rates on failure or asset change

src/assets/translations/en/main.json, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useSwapperService.tsx, src/components/Trade/hooks/useTradeAmounts.tsx, src/state/apis/swapper/selectors.ts, src/state/reducer.ts
The `isLoading` property of an RTK query hook only returns the state of the instantiation in the current context.
As an RTK query can be called from anywhere in the app, we need to have a global way of knowing if we are waiting for a response from an endpoint.
By using the API's reducer we can query the global state of the API as a whole, or an individual endpoint.
N/A - swapper improvements.
Minimal - only affects loading state UI.
When we are getting a quote or rates, the swapper should show appropriate loading states.
The main improvement here is that we should no longer see the "Rate not available" show before getting a rate, as we now correctly understand when we are searching for rates.
In addition, trade quotes refresh when the trade amounts change, so an "Updating quote..." state …
=> feat: use selectors for swapperApi state

src/assets/translations/en/main.json, src/context/WalletProvider/MobileWallet/components/MobileImport.tsx
Forces mobile wallets being imported to have a nickname 
closes #2929 
Low risk - only should affect mobile flows 
- no changes to the optional nickname when importing a native wallet on desktop or mobile web
- requires a name for importing a native wallet on mobile app
=> fix: adds required wallet nickname for mobile wallets

src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseCommon.ts, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseModal.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphrasePassword.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseRouter.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseStart.tsx, src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx, src/context/WalletProvider/WalletProvider.tsx, src/context/WalletProvider/config.ts
See shapeshift/mobile-app#59
Change the BackupPassphrase flow (which is incorrectly named, it's not a passphrase) to support both Native and Mobile wallets
* Don't use `hdwallet-native-vault` except to read the mnemonic from a Native wallet
* Pass the mnemonic around in a RevocableWallet object
closes shapeshift/mobile-app#59
Low - only affects seed phrase backup of mobile/native wallets
1. Connect a web native wallet
2. Click on the menu
3. Click on the down arrow
4. Click Back up my wallet ("Backup"?)
5. Follow the flow
6. Repeat for mobile
Testing mobile requires Android and/or iOS simulator
See above
if applicable)
=> feat(mobile): support seed phrase recovery for the mobile app

src/components/Trade/TradeInputV2.tsx
- Added back the data-test tag for the new version of swapper preview trade
n/a
no risk
n/a
n/a
=> fix: missing pendo tag on preview trade v2

src/components/Trade/hooks/useTradeQuoteService.tsx
we were getting in a state where we had the option to throw, or return undefined, which was already
part of a valid type signature when hitting send max with a new quote
throwing would put us into an unrecoverable state where the send max button would remain disabled
returning early here allows the send max button to become enabled again when the dependencies of
this function are updated
n/a - noticed while testing
* this has an unintentional effect and makes things worse, isolated entirely to send max on swapper
v2
* you should not see the `Max` button on the sell asset get stuck in a disabled state after a new
quote is fetched, i.e. after you change a buy or sell asset or amount
* see common steps
* see common steps
=> fix: partially unrug max button

src/components/DeFi/components/AssetInput.tsx, src/components/Modals/FiatRamps/components/FiatRampButton.tsx, src/components/Modals/Receive/ReceiveInfo.tsx
- Move account dropdown out of QR code so its more visible
- Fix skeleton loading to keep the trade widget from jumping around
- Disable auto-complete on asset input's input field
n/a
no real risk, mostly just visual changes
n/a
With multi account flag on, go to receive and see that the account drop has been moved out of the QR code.
The trade midget should not jump around in a loading state now as well.
https://user-images.githubusercontent.com/89934888/193678507-10041b00-0d92-473b-9da0-32a31749ed52.mov
=> fix: update trade loading state and dropdown placement 

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useGetTradeAmounts.tsx
Now that ThorSwap fees are coming through correctly, we've exposed that the logic to display "beforeFees" is incorrect for ThorSwap quotes.
Calculating the `beforeFeesBuyAsset` value requires the context of the action, which we don't currently consider.
This PR adds a constant to compute a `beforeFeesBuyAsset` that is passed into the `beforeFees` prop of the `ReceiveSummary` component.
**Before:**
**After:**
The `ReceiveSummary` is now hidden is the sell amount is too small.
Closes https://github.com/shapeshift/web/issues/2963
Small, though there may be an impact to other swapper fee amounts if implemented incorrectly.
With ThorSwap enabled, enter sell amount. It's easiest to observe with a small value, such as with the "before" screenshot above.
The "beforeFees" should be correct, i.e. …
=> chore: fix ThorSwap beforeFees amount

package.json, src/components/Trade/Trade.tsx, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useSwapper/useSwapperV2.tsx, src/components/Trade/hooks/useTradeAmounts.tsx, src/components/Trade/hooks/useTradeQuoteService.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.tsx, src/components/Trade/types.ts, yarn.lock
Passes `sendMax` to `buildTrade` and `getTradeQuote`
Requires https://github.com/shapeshift/lib/pull/1046 to actually consume the value.
TODO: update swapper package once `lib` PR is merged.
Closes https://github.com/shapeshift/web/issues/2949
Minimal - only touches a flag on `buildTrade` and `getTradeQuote` args.
When using the "Max" button when getting a quote, we should be able to proceed to the confirm screen without error, and ultimately perform a trade.
Check both EVM and UTXO assets.
As above.
As above.
N/A
=> fix: pass `sendMax` to `buildTrade` and `getTradeQuote`

src/components/Trade/Trade.tsx, src/state/slices/portfolioSlice/selectors.ts
this array *should* have been stable but wasn't, causing an unnecessary render, and causing the
default assets to change on trade confirmation, and hence causing the swapper protocol to change on
the trade confirmation page
closes #2959
closes #2958 
* we break the default asset logic
* other parts of the app *don't* render when they should
* on the dashboard, ensure that the default pair is ETH/FOX, being routed via THORChain
* setup a trade, ensure it's routed via 0x, not THORChain, e.g. ETH -> UNI
* on the trade confirmation step, expand the expected amount section, ensuring the protocol is 0x
* confirm the trade, and wait for the trade to complete
* the protocol and other values should remain as 0x, and not switch back to THORChain once the trade is complete
* see common testing steps …
=> fix: memoize asset ids to avoid default asset rerender

src/assets/translations/en/main.json, src/components/MessageOverlay/MessageOverlay.tsx, src/pages/Dashboard/TradeCard.tsx
This PR hides the swapper under a message overlay when Keplr is connected, since there is no available swapping pair with the Osmosis flag off, and turning Osmosis on is currently broken for swapping in Keplr.
closes #2961
- Swapper could show the blurred state when it shouldn't
- Ensure connecting/switching to Keplr blurs the swapper
- Ensure switching to/connecting another wallet doesn't blur the swapper
- Refer to top-level notes
=> feat: disable swapper with message overlay for Keplr

src/components/Trade/TradeConfirm/ReceiveSummary.tsx
- change from `amountAfterSlippage` to `amount`
closes #2973 
very little risk
turn on thorchain
put in trade
the amount in the buy amount should match the expected amount
turn on thorchain
put in trade
the amount in the buy amount should match the expected amount
s (if applicable)
=> fix: use amount instead of amount after slippage

src/context/WalletProvider/WalletProvider.tsx
Fixes an issue where a user could decline or error out of biometrics and the app would hang due to no wallet being connected.
Low, only mobile app failure mode should be affected.
1. Pair a wallet to the mobile app
2. on the dashboard, pull down to refresh the app with the phone pointed away from your face
3. When asked to retry, click cancel
4. This should now take you back to splash screen
=> fix: return user to splash on failed pairing

src/components/Trade/TradeConfirm/ReceiveSummary.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useGetTradeAmounts.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx, src/components/Trade/hooks/useTradeAmounts.tsx
draft - needs a well rested set of eyes before merging
this fixes a lot of stale value bugs we've been seeing by more aggressively guarding against invalid
inputs to the `getTradeAmountConstants` function
without doing this, it was possible to get into two very broken states
1) we should never be able to display a "Before Fees", or a "Protocol Fee" amount, without having
either a buy or sell amount, i.e. you can't possibly be receiving an amount "Before Fees" if you're
not swapping anything
2) we could see conditions where we were displaying a protocol fee for 0x quotes, or no protocol fee
for thorchain quotes. both of these are wrong.
it's possible we can revert the changes to `ReceiveSummary` and `TradeConfirm`, but both are
probably worthwhile
* receive summary should be purely …
=> fix: trade amount constants and confirm

src/components/DeFi/components/AssetInput.tsx
- In the asset input field, we should show the placeholder when the value is 0
closes #2974 
Possibly could effect trade logic when loading rates. However, this is only presentational and should not effect state.
n/a
When coming to trade or DeFi modals, on first load you should see `0.00` in greyed out text. Once you click the input you should be able to type a value and it clears the 0.00.
This should also show the fiat placeholder value for USD ($0.00) and the same for other localized currency formats.
=> fix: use placeholder when value is zero

.github/workflows/pr-cypress.yml, cypress/support/e2e.ts, package.json, yarn.lock
Cypress CI got broken by https://github.com/shapeshift/web/pull/3006. 
This PR fixes CI, though not the underlying issue (ThorSwap-related requests failing in Cypress).
- Fix Cypress in CI by ignoring a `thorchainInitialize` error that is thrown due to a network request failing (a longer-term fix is to work out why it's failing and fix it)
- Bumps Cypress to `10.9.0`
- Fixes the `test:cypress:headless` script to match what runs in CI
N/A
Touches CI.
☝️ 
N/A
N/A
=> chore: ignore `thorchainInitialize` error to fix CI

src/components/AssetAccounts/AssetAccountRow.tsx, src/components/AssetHeader/AssetChart.tsx, src/state/slices/accountSpecifiersSlice/selectors.ts, src/state/slices/portfolioSlice/selectors.ts
fix: asset account allocations for cosmos
we were previously using the first account id everywhere, causing account > 0 to include staking balances from account 0. this updates selector usage to use the correct selectors with the correct account ids.
**note - this does *not* fix the staking section**
n/a - multi account related
* we should the wrong amounts for accounts on asset and account pages
* have a wallet with cosmos balances in more than one account
* with the multi account flag off - ensure the total shown on the cosmos asset pages matches what is displayed in the asset allocation row
* with the multi account flag on - navigate back to the cosmos asset page. the total shown above the chart, in both fiat and crypto human amounts, should match the sum of what is displayed in the in …
=> fix: cosmos asset account allocation

src/components/DeFi/components/AssetInput.tsx
This reverts commit d9a9932baa58015b34f6b944567994a969d39df9.
Reverts https://github.com/shapeshift/web/pull/2989.
This PR causes a number of issues with the swapper:
- When changing assets (using asset selection or toggling), the sell amount is not cleared, and the amounts aren't updated
- When fees are higher than the buy amount (easy to replicate with ThorSwap), and a sell amount is entered, the amounts to not update
- I suspect some other things get a bit dicky
It's probably a simple fix, though I haven't had time to look into it further and the feature isn't worth the bug.
Something probably expects a `'0'` and is now receiving a `null`.
https://user-images.githubusercontent.com/97164662/195052122-6e0f6c28-127c-47c1-9a27-b0876451207e.mov
N/A
Minimal, reverts a small and recent …
=> revert: fix: use placeholder when value is zero (#2989)

src/plugins/foxPage/components/AssetActions.tsx, src/plugins/foxPage/components/MainOpportunity.tsx, src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
This PR fixes:
- The Fox Page for demo wallet, using the "Connect Wallet" flow instead of the current demo wallet FOX/y / FOX/ETH LP/Farming balances flow, as discussed with @shapeshift/product
- The disabled state for wallets supporting ETH, which erroneously got broken in https://github.com/shapeshift/web/pull/2981/files#diff-dc299dddf3dc49cb7c52673353de768f670fb824a279931b461717bdcf50299cR147 - we should never end up in a disabled state
- relates to the closed https://github.com/shapeshift/web/issues/2980
FOX page could be borked for wallets, test accordingly
- FOX Page looks good with demo wallet / Keplr connected and shows a "Connect Wallet" instead of "Get Started / Manage"
- FOX Page with native wallet / MM shows no regressions, showing the "Get Started / Manage" copy depending on …
=> fix: fox page demo wallet / ready state checks

src/components/Trade/hooks/useSwapper/utils.ts
Currently, when "Max" is pressed when there is not enough of the sell asset to complete a trade, the `getSendMaxAmount` function will return a negative value.
This negative value is then used in the quote request, which fails.
This would sometimes cause the "Max" button to become disabled, with no way to re-enable it.
This PR updates `getSendMaxAmount` to return `'0'` if the max send amount is not positive.
N/A - discovered whilst messing with the swapper.
Very small - touches only the pure function that calculates the max send amount.
Click "Max" when there is not enough of the sell asset to perform the trade, but the balance is greater than `0`.
The sell amount should be, and stay `0`. The "Max" button should not become disabled.
Ensure that the quote requests are all returning `200`, …
=> fix: negative send max quote request

package.json, src/components/AccountDropdown/AccountDropdown.tsx, src/components/DeFi/components/AssetInput.tsx, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useAccountsService.tsx, src/components/Trade/hooks/useSwapper/useSwapperV2.tsx, yarn.lock
This PR locks the buy asset account ID to the sell asset account ID for 0x and CowSwap trades, as these protocols don't support sending to different receive addresses.
Closes https://github.com/shapeshift/web/issues/3019
Small, some risk that the `onChange` handler fires more than once, or some other useEffecty bug caused by the removal of `firstAccountId !== selectedAccountId`.
1. Enable the multi-account flag.
2. Connect a wallet that supports multiple EVM accounts, e.g. Native
3. Ensure a trade asset pair is selected such that 0x or CowSwap is used as the swapping protocol
4. The buy asset account should be disabled for selection, and locked to the selected sell asset account value
☝️ 
☝️
=> feat: lock buy account to sell account for 0x & CowSwaps

package.json, yarn.lock
Bumps swapper to the version that makes THORchain trades into ETH Mainnet accounts have a $50 minimum.
Ensures https://github.com/shapeshift/web/issues/3024 is resolved.
Small, see https://github.com/shapeshift/lib/pull/1056
1. Link branch to `web`
2. Ensure ThorSwap enabled in `web`
3. Get ThorSwap quote for any trade into the Ethereum Mainnet - the minimum amount of the sell asset should be approximately equal to $50
☝️ 
☝️
=> chore: bump swapper to 11.5.7

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
This PR fixes the `<PairDeposit />` fields not being synced for FOX/ETH LP, by not ignoring the accountId dependency in the StepConfig useMemo() deps.
Note, there is a flash of content happening when changing accounts from
pair deposit, but this is an optimization that's outside of the scope of
this bugfix.
closes #3022
None, this properly passes accountId down, which is the same as manually
syncing both previously.
- Enable MultiAccounts flag
- Add an Ethereum account
- In the FOX/ETH LP deposit modal, select either account 0 or 1 at
overview step
- Click deposit and in any of the pair deposit inputs, select your other
account
- Both pair deposit inputs should be updated to reflect the account
change
- Refer to top-level notes
- Refer to top-level notes
=> fix(fox-eth LP): sync PairDeposit AccountIds

src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Status.tsx
This updates the translations to be staking specific and not the generic deposit.
closes #3060 
no risk
n/a
When staking into cosmos you should now see "You have successfully staked your Cosmos."
=> fix: update cosmos staking translations

src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useAccountsService.tsx
When an asset is selected we clear the `accountId`. This is good, as it ensures we don't have stale account data.
When the selected asset has the same `accountId` as the previous asset, the `useEffect`s that set `sellAssetAccountId` and `buyAssetAccountId` do not re-run. This is bad, as we are stuck with an `undefined` `accountId`.
This PR ensures `sellAssetAccountId` and `buyAssetAccountId` is correctly re-set after it has been cleared.
N/A - raised by ops in a thread.
Small - though could affect account selection somehow.
With an already approved asset pair, say USDT -> ETH, attempt to trade by clicking "Preview Trade".
We should get to the confirm screen.
Note, it is important that the assets be selected manually, rather than via the asset route.
☝️ 
Sense check re-renders/useEffect …
=> fix: no `accountId` on asset select

src/pages/TransactionHistory/TransactionHistory.tsx, src/pages/TransactionHistory/TransactionHistoryFilter.tsx, src/pages/TransactionHistory/TransactionHistorySearch.tsx
- Allow user to clear search input when the filters are reset
- The clear button should always be enabled -- no real benefit to it being disabled or not.
closes #3038 
no big risk
To avoid controlled/uncontrolled field issue, used a ref to clear the field value.
When typing in a search string on the tx history, you should be able to clear it by clicking the "x" button connected to filters.
=> fix: reset input when clearing filters

src/features/defi/providers/cosmos/components/CosmosManager/LearnMore/CosmosLearnMore.tsx, src/plugins/cosmos/components/modals/Staking/views/GetStarted/GetStarted.tsx, src/plugins/cosmos/components/modals/Staking/views/GetStarted/LearnMore.tsx
- Remove max width to fill entire modal
closes #3073 
no risk visual
n/a
Go to cosmos asset, and click get started and then learn more. The modal should fill the entire space available and not be cut off.
=> fix: max width on cosmos learn more modals

src/components/Bridge/BridgeRoutes/Confirm.tsx, src/components/Delegate/StakingOpportunities.tsx, src/components/StakingVaults/AllEarnOpportunities.tsx, src/components/Trade/AssetAccountRow.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useAccountsService.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/WithdrawCard.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/idle/components/IdleManager/Claim/components/Status.tsx, src/features/defi/providers/idle/components/IdleManager/Deposit/components/Status.tsx, src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Status.tsx, src/pages/Defi/hooks/__snapshots__/useCosmosStakingBalances.test.tsx.snap, src/pages/Defi/hooks/useCosmosSdkStakingBalances.tsx, src/pages/Defi/hooks/useCosmosStakingBalances.test.tsx, src/state/slices/accountSpecifiersSlice/selectors.ts, src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/selectors.ts, src/state/slices/txHistorySlice/utils.ts
this should fix the issues described in #3062 and uhh deletes a bit of code along the way
the impetus for this was the insanity around the duplication of accountSpecifier and accountId terminology, this was essentially the minimum change that could be made to make the consumption of these selectors sane and bug free, and along the way managed to find a bunch of selectors that were redundant and their associated tests.
this also removes any selectors and filters using the old `accountSpecifier` terminology for future travelers benefits
closes #3062
pretty big around cosmos staking
* please test with multi account flag on
* if a wallet doesn't have any cosmos sdk staking balances, the get started CTA should appear on the asset, account, and defi pages
* if a wallet has a cosmos sdk staking …
=> chore: cosmos sdk selector rationalization

src/components/Modals/FiatRamps/config.ts, src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts
Don't pass the address to Mt Pelerin till we can figure out how to sign the message and pass them the hash.
n/a
possibly could cause an issue with the fiat ramp click
Eventually we will need to work out how to do this -- https://developers.mtpelerin.com/integration-guides/options#nodejs-code-with-ethers.wallet-as-signer
Then we can pass the wallet address correctly.
Select ETH from the fiat ramps, click on Mt Pelerin. You will be prompted to connect a wallet or to manually add address.
=> fix: remove address from the generated fiat url

src/components/AssetHeader/AssetHeader.tsx, src/components/Trade/SelectAccount.tsx, src/components/Trade/TradeInput.tsx, src/components/TransactionHistory/AssetTransactionHistory.tsx, src/context/FoxEthProvider/FoxEthProvider.tsx, src/pages/Defi/views/StakingVaults.tsx, src/plugins/foxPage/components/AssetActions.tsx, src/plugins/foxPage/hooks/useOtherOpportunities.ts, src/state/slices/portfolioSlice/selectors.ts
Currently, `selectAccountIdsByAssetId` is somehow unstable, despite the output being deeply equal.
https://github.com/shapeshift/web/blob/e69906f95940a3e3b8dffc7831875f4ec15db1e8/src/context/FoxEthProvider/FoxEthProvider.tsx#L89-L91
When called in `EthProvider`, this invalidated reference on every call causes `ethAccountIds` to invalidate, and the memoized callback to invalidate as a return in `refetchFoxEthLpAccountData` deps.
https://github.com/shapeshift/web/blob/e69906f95940a3e3b8dffc7831875f4ec15db1e8/src/context/FoxEthProvider/FoxEthProvider.tsx#L93-L108
Since we have an effect reacting on `readyToFetchLpData` and `refetchFoxEthLpAccountData` reference to fire refetch, this causes refetch to fire infinitely, causing an infinite XHR loop and performance issues.
This is a quick fix …
=> fix: make selectAccountIdsByAssetId call stable in FoxEthProvider

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimRoutes.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx, src/state/slices/foxEthSlice/selectors.ts
This PR adds the missing `accountAddress` param in the filter of `selectFoxFarmingOpportunityByContractAddress` in claim routes, fixing opportunities granularity.
Additionally, makes it required at selector-level and uses a memoized filter on all `selectFoxFarmingOpportunityByContractAddress` consumptions.
- relates to the closed https://github.com/shapeshift/web/issues/2447
None
- Open fox farming modal
- Click claim
- The claim step should be displayed, and you should be able to proceed with a claim
☝🏽 
☝🏽
=> fix: fox farming claims

src/components/StakingVaults/EarnOpportunities.tsx, src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/FoxEthLpManager.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Approve.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/FoxFarmingManager.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimRoutes.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx, src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
Currently, we use a single `accountId` in the FoxEth provider, both for farming and LP.
This desyncs them, so that selecting an account in one doesn't keep it selected for the other.
- relates to the closed https://github.com/shapeshift/web/issues/2447
The accountId logic should be the same as before, just now split so this is relatively low risk
- AccountId should be propagated everywhere on the LP/farming flow the same as before
- It should now be unsynced, meaning that selecting account 1 on the farming modal doesn't keep it as the selected one when opening the LP modal
- The highest balance autoselect should still take precedence i.e, when opening a FOX/ETH modal from DeFi cards/rows, the highest balance should be selected
- Split logic looks sane
☝🏽
=> feat: split fox/eth LP/farming accountIds

src/plugins/foxPage/FoxCommon.ts, src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx, src/plugins/foxPage/hooks/useOtherOpportunities.ts
This PR passes `highestBalanceAccountAddress` in the routing of ETH/FOX opportunities in the FOX page, making sure we always open the farming and LP modals with an actual account.
N/A
- On the FOX page, LP modal should open without an empty state, with the highest balance account
- On the FOX page, farming modal should open without an empty state, with the highest balance account
☝🏽 
☝🏽
=> feat: fox page highest balance accountAddress

package.json, yarn.lock
No longer show thorchain pools that are not in `Available` state
closes #
Low
- Sushi should not show as an available thorchain pool anymore (along with any others that aren't `Available` as described here: https://daemon.thorchain.shapeshift.com/lcd/thorchain/pools)
:point_up: 
:point_up: 
Left is after, Right is before
=> fix: only show available thorchain pools

src/state/slices/assetsSlice/selectors.ts, src/state/slices/foxEthSlice/selectors.ts, src/state/slices/marketDataSlice/selectors.ts, src/state/slices/portfolioSlice/selectors.ts
we uhhh should have done this a while ago
selectors have a memoization depth of 1 https://github.com/reduxjs/reselect#q-why-is-my-selector-recomputing-when-the-input-state-stays-the-same
re-reselect solves this problem and gives us an infinite cache size https://github.com/toomuchdesign/re-reselect
this PR gives us a two order of magnitude performance increase in terms of selector recomputation and subsequent react renders by giving selectors sufficiently unique cache key names
n/a - bug chasing got out of hand
* reasonably high - gives the app a good smoke test all around, looking for stale data
* things should feel considerably faster
=> chore: selector performance via cached selectors

src/components/Trade/TradeInputV2.tsx
The Send Max button is not currently disabled when there is not enough data to use it, or the API is loading (trade amounts don't populate until it's finished loading anyway).
This PR ensures it's disabled unless we are in a position to use it to populate trade amounts.
N/A
Very small.
Change assets to get a ThorSwap quote (slower, so easier to see).
a) Notice the "Max" button is disabled until we have a quote
b) The "Max" button disables whilst max is being calculated
☝️ 
☝️
N/A
=> fix: loading state for send max

src/components/Trade/Trade.tsx, src/components/Trade/TradeInputV2.tsx, src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.tsx
We are not correctly clearing the form state when assets change, which leaves us with stale values that are temporarily shown in the UI.
A prime example of this is gas fees being off, which in particular can be observed when getting a trade quote (all the way to the trade confirm screen) for ETH -> FOX, then backing out and getting a regular quote for BTC -> DODGE.
The cached `trade` value was causing the fee asset to be wrong, which broke the gas fee UI.
Closes https://github.com/shapeshift/web/issues/3107
Fairly small - only touches swapper form state values.
Try the example given in the description - there should be no more gas fee issues on the quote or trade confirm page.
☝️ 
☝️
N/A
=> chore: reset form state on asset change

src/components/AccountDropdown/AccountDropdown.tsx
This PR fixes the infinite AccountDropdown by narrowing the conditions under which `onChange()` should run.
The guts of this is using a poor man's componentDidUpdate for react hooks a.k.a `usePrevious`, which allows us to detect when the value of the `selectedAccountId` didn't actually change, and thus calling `onChange` would create infinite toggles back and forth.
closes https://github.com/shapeshift/web/issues/3095 - note this says swapper but the same issue is happening on FOX/ETH currently with the autoselected highest balance account
Account selection could be borked, test accordingly
- In swapper, select an account that is *not* the autoselected highest balance one for either the buy or sell asset
- Reselect the same buy or sell asset
- There should be no infinite toggle
- In the …
=> fix: infinite AccountDropdown toggle

src/components/TransactionHistoryRows/TransactionGenericRow.tsx, src/components/TransactionHistoryRows/TransactionMethod.tsx, src/components/TransactionHistoryRows/TransactionReceive.tsx, src/components/TransactionHistoryRows/TransactionSend.tsx, src/components/TransactionHistoryRows/TransactionTrade.tsx, src/components/TransactionHistoryRows/UnknownTransaction.tsx, src/components/TransactionHistoryRows/components/AssetTransfer.tsx, src/components/TransactionHistoryRows/components/AssetsTransfers.tsx, src/components/TransactionHistoryRows/constants.tsx, src/components/TransactionHistoryRows/utils.ts
This PR brings support for multiple inbound / outbound assets transfers as a `<transfersAmount> transfers` column in Tx history. 
closes https://github.com/shapeshift/web/issues/2428
We could wrongly parse Txs with a single transfer in/out as a many transfers Tx (see screenshot), and vice versa, which would indicate issues with unchained-client parsing
- Txs with a single inbound/outbound asset transfer should still be parsed as before
- Txs with multiple assets' transfers either inbound or outbound, should show `<x assets>` where x is the number of assets in the transfer type (send/receive), and the total fiat amount for said assets' value
=> feat: tx history assets transfers columns

package.json, yarn.lock
Bumps `@shapeshiftoss/unchained-client` to parse ETH TXs without yearn vaults.
Friends with https://github.com/shapeshift/lib/pull/1078.
N/A
Small - `lib` change isolated to Yearn parsing.
TX history should load.
☝️ 
☝️ 
N/A
=> chore: bump unchained-client

src/components/Modals/Send/views/Confirm.tsx
- On the send modal confirm, we should show the breakdown of the fee (Amount + Fee Amount)
no issue
small risk
Go to send, and on the confirm step you should see the Amount you are sending and the fee amount. With the combined total amount on top.
s (if applicable)
=> fix: show the fee crypto amount and send amount

src/components/DeFi/components/AssetInput.tsx, src/components/DeFi/components/PercentOptionsButtonGroup.tsx
Makes things more intelligible for the following-up stacked PRs.
Mostly a rename to match what this component actually is, although this bring two actual changes:
- a new optional `onMaxClick` prop to be passed down
- consumption of said prop - the regular percent buttons onClick will be used if `onMaxClick` is not defined so this won't bring any runtime changes for now.
- relates to https://github.com/shapeshift/web/issues/1966
- Ensure percent click buttons on IBC and EVM chains, including max, still react on click
=> feat: rename MaxButtonGroup -> PercentOptionsButtonGroup

src/components/Bridge/BridgeRoutes/BridgeInput.tsx, src/components/DeFi/components/AssetInput.tsx, src/components/Trade/TradeInputV2.tsx, src/features/defi/components/Deposit/Deposit.tsx, src/features/defi/components/Deposit/PairDeposit.tsx, src/features/defi/components/Withdraw/Withdraw.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx, src/stories/Forms.stories.mdx
Currently in the DeFi section we use `onMaxClick` as a catch-all method for all percent options click which is wrong.
This PR fixes the wrong terminology, and while at it, separates it into `onPercentOptionClick` - the current one, and `onMaxClick` which actually handles max clicks.
The latter is optional and provides chain-specific implementations, typically to subtract fees - in case this is not needed e.g unstaking from Cosmos where the full staking balance is used, then `onMaxClick` doesn't need to be passed down and we can rely on the current `onPercentOptionClick` implementation.
- relates to #1966
- Percent options / maxes could be borked, test accordingly
- See risks
=> feat(defi): sane max / percent click handlers

package.json, yarn.lock
Included changes:
- https://github.com/shapeshift/lib/pull/1074
- https://github.com/shapeshift/lib/pull/1079
- closes https://github.com/shapeshift/web/issues/3177
- Cosmos Tx history could be borked
- Yearn SDK update might rug us for everything Yearn
- AVAX featureset could be borked
- Cosmos Tx history looks good and also includes staking operations
- Cosmos account balance **and** staking data live updates on a staking operation - over the DeFi section overview, earn and DeFi modals / rows as well as in the accounts and assets pages
- AVAX data is still displayed across the app and we can broadcast AVAX Txs with both MM (native is still borked pending https://github.com/shapeshift/hdwallet/pull/583 merge)
- Yearn data is still displayed correctly and we can broadcast a Yearn Tx
- …
=> feat: bump @shapeshiftoss/chain-adapters

src/features/defi/components/Deposit/Deposit.tsx
This change keeps the correct precision when doing percentage math to ensure we pass an integer value to the build transaction functions
closes (https://github.com/shapeshift/web/issues/3065)
Low
Test staking at different percentage amounts. All options should work correctly and successfully broadcast a transaction
:point_up: 
:point_up:
=> fix: keep correct decimal precision on percentage math

src/features/defi/components/Deposit/Deposit.tsx
Layers on top of https://github.com/shapeshift/web/pull/3179 bringing more sanity
In the DeFi deposit step, we were doing amount * percentage / 100, which
does exactly this, gives us the result of this operation.
However, making such a division on human amounts will possibly reduce in
more precision than the initial one, which this PR fixes.
Expect more PRs on top of this to:
1. Use the abstracted `handlePercentOptionClick` from
https://github.com/shapeshift/web/pull/3171 everywhere across the
DeFi section, to ensure the bug is fixed consistently across deposit
and withdraws
2. Another PR to bring the crypto/human amount vernacular over the DeFi
section
- technically speaking, closes https://github.com/shapeshift/web/issues/3065, but this is not
strictly limited to staking as we use the …
=> fix(defi): deposit percentage precision

src/pages/Accounts/components/AccountNumberRow.tsx
fixes UTXO accounts dead click, using option two described in the issue. the UTXO account button now toggles the underlying accounts instead of doing nothing.
closes #2994
none
connect to a wallet that supports UTXO accounts (btc, ltc, bch), head over to accounts page.
click the arrow-down button on BTC/LTC/BCH, clicking the account row should toggle the underlying accounts.
see above
see above
n/a
=> fix: utxo-accounts dead click

src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx, src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/idle/components/IdleManager/Claim/IdleClaim.tsx, src/features/defi/providers/idle/components/IdleManager/Claim/components/Confirm.tsx, src/features/defi/providers/idle/components/IdleManager/Deposit/IdleDeposit.tsx, src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx, src/features/defi/providers/idle/components/IdleManager/Deposit/components/Confirm.tsx, src/features/defi/providers/idle/components/IdleManager/Deposit/components/Deposit.tsx, src/features/defi/providers/idle/components/IdleManager/IdleManager.tsx, src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx, src/features/defi/providers/idle/components/IdleManager/Withdraw/IdleWithdraw.tsx, src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx, src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Confirm.tsx
This PR fixes the `feeAssetBalance` to use a granular portfolio balance by AccountId, as opposed to selecting the aggregation over all accounts currently.
Accidentally brings multi account ish support over the Idle DeFi provider, although this only passes `AccountId` around for consistency and does not bring account bip44Params support yet, TBD in https://github.com/shapeshift/lib/issues/943
closes https://github.com/shapeshift/web/issues/3209
- Multi-account could be borked over the DeFi section, test accordingly
- Have an account, either 0 or another without enough ETH for gas, but either enough dust to deposit, staked amount to withdraw, or rewards to claim
- Have some ETH balance over your other accounts to total to a significant amount to cover gas
- Ensure when …
=> fix(defi): select feeAssetBalance by granular AccountId

src/components/Trade/hooks/useTradeAmounts.tsx
This PR fixes an issue where highlighting the trade input amount for the buy or sell asset and pressing delete would not actually delete the values.
On the second press, it would show the placeholder, but still not actually delete the values.
Closes https://github.com/shapeshift/web/issues/3185
Small, relates to the input values of a trade. 
1. On the trade modal, type in a value into the input asset
2. Highlight the value and press delete
3. Notice it now deletes the value as expected
☝️ 
☝️ 
N/A
=> fix: re-calculate values on NAN amount

src/components/Trade/hooks/useTradeQuoteService.tsx
Sometimes on route change the React Hook Form trade form instantiation would be torn down and re-initialized.
This would fire a `useEffect` that cleared the `quote`, and so we'd have no initial rate on a route change until the RTK query polled or an input changed.
This PR adds a `useEffect` that fires in this case to re-set the quote to the current `tradeQuote` value in `useTradeQuoteService`, ensuring it stays defined.
N/A
Small. Some risk of an infinite render, though I'm 99% sure I've mitigated it.
Navigate between the Dashboard and the trade page.
We should no longer have "No rate available" shown for a period of time, when it shouldn't.
☝️ 
☝️ 
N/A
=> fix: set quote on route change

src/assets/translations/en/main.json, src/pages/Accounts/components/AccountNumberRow.tsx, src/pages/Accounts/components/ChainRow.tsx
- Based on some user feedback, now when you click the rows they expand the items below it.
- Added a more button to expand account options e.g. (Show Account, Hide Assets)
closes #3216
closes #3207 
Small risk
When going to the accounts page, if you click a chain --- it will expand the accounts below it.
When you click on an account it should expand the assets below it.
If you click the (...) more button you should see a 2 menu items (VIew account, show/hide assets)
This should fix the other two issues as well.
=> fix: rework the way we handle clicking on accounts and expanding them

package.json, yarn.lock
- bump chain-adapters to fix broken cosmos-sdk sends on keepkey
- 
closes #
Low
- Ensure cosmos/osmosis/thorchain sends work on keepkey, and double check they still work on any other supported wallets
:point_up: 
:point_up:
=> fix: cosmossdk sends

src/components/Trade/TradeInputV2.tsx
Fixes `feeAssetBalance` to use the balance from the currently selected sell account.
Closes https://github.com/shapeshift/web/issues/2894
Very small.
When trading from an account that is not account #0, and the fee asset balance of that account is lower than the fee, it should now show "Not enough ${asset.symbol} to cover gas".
☝️ 
☝️
=> fix: show not enough fee asset for gas multi-account

src/lib/utils.ts, src/state/slices/foxEthSlice/foxEthCommon.ts, src/state/slices/foxEthSlice/foxEthSlice.ts, src/state/slices/foxEthSlice/selectors.ts
Type casting an empty object (don't do this!) caused a bug.
This PR:
- Improves the type of `FoxEthOpportunities` to account for the fact that it can indeed by `undefined`
- Adds explicit typing to `selectFoxEthLpAccountsOpportunitiesAggregated` and `selectFoxEthLpAccountOpportunitiesByMaybeAccountAddress`, handling the resulting complier errors, to further reduce the risk of bugs
- Improves `selectFoxEthLpAccountOpportunitiesByMaybeAccountAddress` return type. 
Closes https://github.com/shapeshift/web/issues/3210
Small. Touches opportunity logic, though in a small way.
I was able to replicate the bug described in https://github.com/shapeshift/web/issues/3210 by:
1. Starting a fresh incognito session
2. Connecting a Native wallet
3. Adding a new ETH account from the accounts page
4. …
=> fix: crash on empty account

src/features/defi/components/Approve/Approve.tsx
We aren't disabling the `Approve` defi component when we are loading (see screenshots below).
This PR fixes that.
N/A
Minimal.
Go through the defi approval flow. When clicking "Approve on wallet" we should now disable the button.
☝️ 
☝️ 
Before:
After:
=> fix: defi approval loading state

src/components/AssetHeader/AssetChart.tsx, src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts, src/components/Modals/FiatRamps/utils.ts, src/lib/utils.ts, src/pages/TransactionHistory/TransactionHistory.tsx, src/state/slices/foxEthSlice/selectors.ts, src/state/slices/portfolioSlice/utils.ts
There are two issues with the way we are currently using `.filter(Boolean)`:
1. Using it to filter out falsey values does not type guard the result. This has gone unnoticed because we have not been correctly typing values that can be `null` or `undefined`
1. In all current usages, it seems that the intention is to filter out `null` or `undefined`, not falsey values
This PR:
1. Updates the current type guard helper to accept `null` in addition to `undefined` types
1. Renames the helper from `isDefined` to `isSome`
1. Replaces all filter usages of `Boolean` with `isSome` which will assist with the in-progress type improvements throughout the codebase
N/A
The behaviour has changed slightly. There is a small risk that somewhere we were using a falsely value (`''` or `0`) when we should have …
=> chore: type-guard boolean filters

src/state/slices/foxEthSlice/selectors.ts
Using `Object.assign` over a spread results in significant performance improvements.
I clocked `4,377 ops/s` for `Object.assign` with 10,000 opportunities vs `578 ops/s` with spread.
[Perflink](https://perf.link/#eyJpZCI6IjQxanF0MmJnMGVvIiwidGl0bGUiOiJPYmplY3QuYXNzaWduIHZzIHNwcmVhZCBwZXJmb3JtYW5jZSIsImJlZm9yZSI6ImNvbnN0IGJhc2VMcE9wcG9ydHVuaXR5ID0ge1xuICBwcm92aWRlcjogXCJEZWZpUHJvdmlkZXJcIixcbn1cblxuY29uc3Qgb3Bwb3J0dW5pdGllcyA9IEFycmF5KDEwMDAwKS5maWxsKGJhc2VMcE9wcG9ydHVuaXR5KSIsInRlc3RzIjpbeyJuYW1lIjoiVGVzdCBDYXNlIiwiY29kZSI6Im9wcG9ydHVuaXRpZXMucmVkdWNlKFxuICAoYWNjLCBjdXJyZW50T3Bwb3J0dW5pdHkpID0%2BIChPYmplY3QuYXNzaWduKGFjYyA%2FPyB7fSwgeyB1bmRlcmx5aW5nRm94QW1vdW50OiBhY2M%2FLnByb3ZpZGVyID8%2FICcnIH0pKSxcbiAgdW5kZWZpbmVkLFxuKSIsInJ1bnMiOls0NDExLDQyMzUsNDI5NCw0Mjk0LDQ0MTEsNDI5NCw0NDcwLDQzNTIsNDQ …
=> chore: optimise selectFoxEthLpAccountsOpportunitiesAggregated

src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx, src/lib/utils.ts, src/state/slices/opportunitiesSlice/selectors.test.ts, src/state/slices/opportunitiesSlice/selectors.ts, src/state/slices/opportunitiesSlice/types.ts
When we attempt to access an object property with type `Record<T, U>` via dynamic bracket notation the resulting type is `U`, i.e. always defined - TS assumes that if our accessor expression matches type `T` then we get a result of type `U`.
This is not true at runtime. E.g.:
```ts
const opportunityMetadata = stakingOpportunities['notARealId'] // OpportunityMetadata
const opportunityMetadataAssetId = opportunityMetadata.assetId // Throws - attempted to access a property of undefined
```
This PR fixes the types in the Opportunities Slice by using a `PartialRecord` helper (that we should implement more broadly).
Now, continuing our example, when trying to access a property of `opportunityMetadata` the compiler will force us to handle the `undefined` case.
This fixes a whole host of bugs by …
=> fix: properly type partial records

src/features/defi/providers/idle/components/IdleManager/Deposit/IdleDeposit.tsx, src/features/defi/providers/idle/components/IdleManager/Withdraw/IdleWithdraw.tsx
This PR makes sure:
1. We have stable context provider value in Idle deposit/withdraw
components. Technically not the issue here, but makes things safer
2. We don't dispatch reducer actions in an infinite fashion. If we have
an opportunity/address already, everything else is a no-op and
re-dispatching is only going to invalidate the `state` field of the
reducer
- relates to https://github.com/shapeshift/lib/issues/943
None, Idle flag is off and the whole address logic is going to move
somewhere more sane with multi-account logic being implemented, vs.
address being fetched from the wallet with chain-adapters currently.
- Turn Idle flag on
- Open an Idle opportunity
- Click Deposit/Withdraw
- Notice how the app doesn't become unresponsive and it is still
possible to click stuff vs. prod …
=> fix(defi): unrug idle infinite deposit/withdraw loop

src/assets/translations/constants.ts
Removes Korean, Indonesian, and Chinese languages from the language selector as they are not yet supported by the Globalisation team.
CC @firebomb1.
Closes https://github.com/shapeshift/web/issues/3182
Minimal.
Korean, Indonesian, and Chinese languages should no longer be visible in the language selector.
☝️
☝️
=> chore: remove Korean, Indonesian, and Chinese languages from selector

src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/providers/fox-eth-lp/hooks/useFoxEthLiquidityPool.ts, src/plugins/foxPage/components/OtherOpportunities/FoxOtherOpportunityPanelRow.tsx
Fixes the LP routing from the FOX page, ensuring we pass the assetReference of the underlying AssetId (the LP token), not the one of the actual AssetId (the farming contract)
N/A
FOX/ETH LP could be broken from the DeFi page, tested both in FOX page and DeFi page 
- When opened from the FOX Page, ETH/FOX lp modal is able to continue with the deposit flow all the way to confirmation
- When opened from the DeFi Page, ETH/FOX lp modal is able to continue with the deposit flow all the way to confirmation
☝🏽 
☝🏽
=> fix: eth/fox lp fox page routing

src/context/AppProvider/AppContext.tsx, src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
Cleans up console error spew from the opportunitiesSlice, unless you have debug-level enabled in which case you'll still be able to see rejections but as nice and clean debug logs
N/A
None, we just change the place we handle rejections to be at query-level vs. in the awaited thunks. Might seem unsafe to have unhandled rejections but this is actually safer: our usage of thunks is not to consume the data, but only to ensure sequential executions, so consumers shouldn't be aware of resolution/rejection
- Set log level to info
- Console is happy without opportunitiesSlice spew
- Set log level to debug
- Queries rejections are logged to the console as debug logs
- None
=> feat: handle resolvers rejection at query-level

src/state/slices/opportunitiesSlice/resolvers/foxfarming.ts
Current implementation was using farming contract's totalSupply for ratios calculation in farming DeFi modals, which means they were effectively wrong since the totalSupply of the LP contract is what we should actually use for those calculations
closes https://github.com/shapeshift/web/issues/3300
- With an account with no staked LP tokens nor pooled ETH/FOX yet, stake some ETH/FOX e.g 10 FOX with the automatic prorate ETH tokens
- Stake your LP tokens
- Notice how the underlying tokens amount shown in the DeFi modal is the actual amount of tokens you have just pooled and staked
☝🏽
☝🏽
=> fix: incorrect farming ratio calculation

src/plugins/foxPage/components/Governance.tsx, src/plugins/foxPage/hooks/getGovernanceData.test.ts, src/plugins/foxPage/hooks/getGovernanceData.ts
Matching what Boardroom actually displays on their app so the data we display is consistent with it. The Boardroom API we currently use has the correct data under another JSON key named `indexedResult`.
Closes #
(I did report the issue to the bot on Discord but I don't think a Github issue has been created yet, I just wanted to try my hand on a small bug fix after finally setting up a dev env with WSL 😆).
Minimal/None
Unit tests updated to use the updated structure.
Verifying that the vote data displayed on Boardroom and the app are matching now.
Boardroom app:
Current (wrong) values: 
Fixed values:
=> fix: use indexed vote data from Boardroom API

src/components/Trade/TradeConfirm/AssetToAsset.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx
- Now that we have asset colors we can update the asset to asset component to match
closes #
no risk visual change
Going to trade confirm the line between to the two assets should be match the asset's colors.
=> fix: update the asset to asset component colors

src/state/slices/portfolioSlice/selectors.ts
Fixes a bug introduced during types refactor, where we early return from `selectStakingOpportunitiesDataFullByFilter` in case of `!defaultValidatorData`.
That's wrong, since `defaultValidatorData` is the default validator data for a given `ValidatorId`, however, if said `ValidatorId` is a non-default one, we will make selection a no-op, effectively meaning being staked in a non-default ShapeShift validator will select empty opportunity data.
Fixed by tightening the logic to check for the presence of `defaultValidatorData` before making more checks WRT early return and encapsulating this in its own if statement.
closes https://github.com/shapeshift/web/issues/3293
None?
- Have an account with default ShapeShift validator staking data only
- Have another account with non-default ShapeShift …
=> fix: only non-default validator data selection

src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx
Unrugs Idle overview modal with default bip44Params if the passed `accountId` prop is undefined - following the other modals we'd ideally use highest balance logic, however until the abstraction that's currently being written is finished, we are blocked WRT *clean* multi-account logic and being able to use selectors which do not exist yet.
- relates to the closed https://github.com/shapeshift/web/pull/3261
- None, we are currently rugged, this puts us back in a working place
- Idle modals open with MetaMask with account 0 selected initially
- Idle modals open with Native with account 0 selected initially
- It is still possible to select an account and switch away from account 0
☝🏽 
☝🏽
=> fix: idle overview getOrdefaultBip44Params

src/pages/Buy/Buy.tsx, src/state/apis/fiatRamps/fiatRamps.ts, src/state/apis/fiatRamps/hooks.ts, src/state/apis/fiatRamps/selectors.ts
we're beating up coingecko pretty hard w/ ~100 eager requests for market data and price history on app boot for the assets that have fiat ramp support
this defers loading this market data until the user navigates to the buy page where we display it
closes #3334
minimal - changes from eager to lazy loading of this data
* see that we're not making these spot and price history requests until the `<Buy />` component mounts
* refresh the page on the `/buy` route - the list of assets with prices and charts should load
=> fix: lazily load market data for fiat ramp assets

src/state/slices/opportunitiesSlice/selectors.test.ts, src/state/slices/opportunitiesSlice/selectors.ts
fixes a bug where users opportunities balances were getting mixed across wallets
discriminateing user staking and LP opportunities on wallet account ids fixes this.
https://discord.com/channels/554694662431178782/1042892249031262208/1042938918653403286
isolated to defi section selectors
* connect a wallet with fox/eth lp and/or farming balances
* connect to a different wallet, with or without lp and farming balances
* check that balances are not getting mixed between wallets
👆
👆
=> fix: fix lp balances getting mixed

src/features/defi/components/Withdraw/Withdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
This PR makes sure we:
- use the new `underlyingAssetId` (FOX) for FOX farming withdraws, unrugging the withdraw and claim flow
- brings a bit of safety in the withdraw and claim components WRT `assetId` being falsy - if it renders empty, we know why that is
N/A
None
- Have a position in an expired ETH/FOX farm
- Ensure you can withdraw and claim
☝🏽 
☝🏽
=> fix: use underlyingAssetId in fox farming expired withdraws

src/features/defi/components/Withdraw/Withdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
fix: use underlyingAssetId in fox farming expired withdraws (#3371)
=> chore: release v1.156.0 [DO NOT MERGE]

src/components/Trade/TradeConfirm/TradeConfirm.tsx
Uses the correct fiat buy amount on the confirm screen instead of incorrectly rolling our own inside the component.
Closes https://github.com/shapeshift/web/issues/3328
Small. All changes are limited to the confirm trade modal - only UI is affected.
Stage the same trade as Willy in the issue above (LTC to ATOM) or similar THORChain trade with.
The expected fiat amount should now correctly include the trading fee and match the value given on the trade quote page.
☝️ 
☝️ 
N/A
=> fix: use correct confirm amounts

react-app-rewired/headers/csps/bridges/axelar.ts, src/components/Bridge/BridgeRoutes/Confirm.tsx
`https://axelar-lcd.quickapi.com` no longer provides access control allow origin headers, and the `web` app doesn't accept responses that don't contain them.
Update the Axelar URL to one that does.
N/A
Minimal - feature flagged.
Quotes can be received again for Axelar bridges.
N/A
N/A
=> fix: use new axelar url

src/components/Trade/TradeConfirm/TradeConfirm.tsx
- Fixes a bug where we always render the `Flex` dom element to contain the trade warnings, even if there are none
- Refactors the `TradeConfirm` component to use better composition (the JSX is getting too hard to comprehend)
N/A
Small - mostly a refactor, with a small rendering logic change.
- The confirm change should show no changes or regressions
- We should still render trade warnings, e.g. when trading into RUNE
☝️ 
☝️ 
Before:
After:
=> fix: tradeConfirm render & composition

src/components/Modals/FiatRamps/views/Overview.tsx
On the Fiat Ramp form when users click on the copy icon we should copy the address and not the vanity address (Unstoppable Domains//ENS/etc.) as these ramps might not support vanity addresses yet but will always support simple addresses.
Vanity addresses are still displayed and can be manually copied from the input field if needed.
N/A
None.
Test copying the address with accounts which have and don't have Unstoppable Domains/ENS vanity addresses, it should always copy the address and not the vanity address.
=> fix: copy address not vanity address to clipboard

src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Withdraw.tsx
This PR:
- ensures we *display* the actual underlying asset amounts in Idle withdraw, vs. considering the Idle wrapped asset as a 1/1 peg token currently.
- ensures we *broadcast* the matching Idle asset amounts in Idle withdraw
Also adds TODOs on how to consolidate this in a follow-up PR, so that we don't have to do back and forth calculations which make us lose precision, on top of the already lost precision by not using base uni amounts.
This does *not* tackle the issue we have across all DeFi modals currently WRT loss of precision, which will be solved in a follow-up PR by using base unit values across DeFi modals.
This also does not tackle the overview showing the underlying asset assuming 1/1 peg, to be tackled in a stacked PR.
closes https://github.com/shapeshift/web/issues/3392
- …
=> fix(idle): unrug withdraw underlying asset amounts

src/state/slices/opportunitiesSlice/resolvers/idle/index.ts
This PR zero's out the previously staked Idle positions (which users now have a zero portfolio balance for) when upserting, instead of skipping them.
Note, this was specific to Idle, confirmed ETH/FOX LP/staking isn't affected and opportunities are successfully removed from the DeFi section on unstake.
closes https://github.com/shapeshift/web/issues/3400
See testing steps, rewards are the only risk, tested with best yield
- Ensure Idle.finance UI is matching ours, e.g removed cards/rows in DeFi earn/overview for the unstaked position should also be inactive on Idle's UI both for tranches and best yield
- The previously staked amounts should no longer be accounted for across the app (dashboard, account, asset and DeFi earn/overview pages)
☝🏽 
☝🏽
=> fix(idle): clear unstaked positions

src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx
This PR fixes idle overview top-right fiat amount to be the one from the underlying asset, vs. considering Idle asset to be 1/1 to the underlying asset currently
relates to https://github.com/shapeshift/web/issues/3392
N/A
- Idle overview modal top-right fiat amount matches the one of the underlying asset
=> fix(idle): overview fiat amount from underlying asset

package.json, src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx, src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Withdraw.tsx, yarn.lock
This PR:
- consumes https://github.com/shapeshift/lib/pull/1100 giving us reliable market data
- consistently uses Idle token amounts instead of underlying amounts in overview and withdraw
- as a result of both of the above, makes sure we have the same market data / Idle token amounts everywhere across the app
relates to https://github.com/shapeshift/web/issues/3392
If Idle XHR fails, we are in a borked state where we display 0$ positions - not much we can do except for lib Idle XHRs caching in investor-idle (`market-service` already caches requests)
- No need for a lib link, just run `yarn` which will install the gitpkg package
- Market data and asset amounts for Idle positions is the same in DeFi cards, rows, overview (top-right value), withdraw available amount
- The Idle token is used …
=> fix: idle market data / underlying token amounts

package.json, src/components/Trade/Trade.tsx, src/components/Trade/TradeConfirm/ReceiveSummary.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx, src/components/Trade/hooks/useTradeQuoteService.tsx, src/components/Trade/types.ts, src/constants/UsdcPrecision.ts, src/constants/constants.ts, src/features/defi/helpers/normalizeOpportunity.tsx, src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx, src/hooks/useSortedVaults/useSortedVaults.ts, yarn.lock
Uses the `recommendedSlippage` value provided by the trade quote when it's available, else uses the default value.
Requires https://github.com/shapeshift/lib/pull/1102 to be published.
Closes https://github.com/shapeshift/lib/issues/1094
Small/medium - worst case the `recommendedSlippage` doesn't work and our `limit` is slightly smaller than it should be, causing trades to fail.
Trades on swappers that utilise slippage values (currently 0x and THORSwap) should still go through correctly.
The bulk of the engineering review should have already taken place on https://github.com/shapeshift/lib/pull/1102.
☝️ 
N/A
=> feat: add dynamic slippage to trades

src/components/Promo/PromoCard.tsx
Makes promo banner text visible in light mode.
Closes https://github.com/shapeshift/web/issues/3429
Almost literally zero.
Promo banner text should be white, and visible, in light mode.
☝️ 
☝️
=> fix: promo banner light mode

src/components/Trade/TradeInput.tsx
Reverts the "Loading..." message on the Trade component. For wallets which do not support certain assets this message was always displayed instead of a more relevant error message.
This revert reintroduces the last issue described in https://github.com/shapeshift/web/issues/3083. We display errors while the assets are loading and the users should only be notified of these errors when the attempt to load the asset has actually failed/ is completed.
closes #
Error messages for the Trade card.
Try a wallet which doesn't support BTC for example MetaMask and select BTC in the trade page/component.
☝️ 
☝️
=> fix: revert trade error regression

src/components/TransactionHistory/TransactionsGroupByDate.tsx, src/components/TransactionHistoryRows/TransactionRow.tsx, src/hooks/useTxDetails/useTxDetails.test.ts, src/hooks/useTxDetails/useTxDetails.ts
Remove `assetId` filter on transfers array to show full transaction view on asset page.
closes #
Low
Ensure new transaction view on asset page looks correct/better @shapeshift/product 
:point_up: 
:point_up: 
*Before (Left) -> After (Right)*
=> feat: no transfers filter on asset page

src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useDefaultAssets.tsx, src/features/defi/components/Overview/Overview.tsx, src/features/defi/components/Overview/UnderlyingAssetsMenu.tsx, src/features/defi/components/Overview/UnderlyingAssetsTags.tsx, src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimRoutes.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx, src/features/defi/providers/idle/components/IdleManager/Claim/components/Confirm.tsx, src/features/defi/providers/idle/components/IdleManager/Claim/components/Status.tsx, src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx, src/features/defi/providers/yearn/components/YearnManager/Overview/YearnOverview.tsx, src/state/slices/common-selectors.ts, src/state/slices/opportunitiesSlice/constants.ts, src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts, src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts, src/state/slices/opportunitiesSlice/resolvers/idle/index.ts, src/state/slices/opportunitiesSlice/selectors.test.ts, src/state/slices/opportunitiesSlice/selectors.ts, src/state/slices/opportunitiesSlice/types.ts, src/state/slices/portfolioSlice/portfolioSlice.test.ts, src/state/slices/portfolioSlice/selectors.ts, src/state/slices/selectors.ts, src/state/slices/txHistorySlice/selectors.ts
Part 2 of base units refactor - DeFi still expects precision amounts within the abstraction, but those are now derived in-place at component-level.
This PR:
- removes the precision amounts that were marked as deprecated in https://github.com/shapeshift/web/pull/3409
- adds `precision` vernacular to the passed down props
- does the base unit to precision conversion in-place in components
This puts us in a sane place for a follow-up PR to 
- remove the in-place precision conversion
- have DeFi take base units
and use precision amounts as *display only*, while never doing back and forth conversion 
N/A
Low/medium - precision used could be the wrong one in some DeFi domain places
- DeFi modals amount show no regression, test all opportunities, all steps, test max withdraws are still working. …
=> feat: remove deprecated precision amounts

src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
This PR fixes FOXy approvals sometimes being passed to investor-foxy as floats, by ensuring we pass a stringified int-as-string vs. a float-as-string currently.
Note, this is only a temporary fix, and the incoming base unit refactor will allow us to have our cake (be safe from errors) and eat it (don't lose precision, by using base unit amounts retaining all precision instead of converting precision amounts to integers instead of )
closes https://github.com/shapeshift/web/issues/3428
A loss of precision which might affect max. amounts in particular, but it's not really worse than what we have currently with our precision amounts
- Open the FOXy deposit modal
- Enter a fiat amount e.g 5$
- Select approve exact amount
- Ensure the MM window pops up instead of an app/console error
☝🏽 
☝🏽
=> fix: foxy floating-point approvals

.env.develop
Enable `REACT_APP_FEATURE_OSMOSIS_SEND` on `develop`.
N/A
Small, should only affect "Send" functionality of Osmosis.
On develop.shapeshift.com, from the Osmosis asset page you should have able to use the "send" functionality for Osmosis.
No other Osmosis functionality should be enabled by turning on this flag.
☝️ 
☝️
=> chore: enable REACT_APP_FEATURE_OSMOSIS_SEND on develop

package.json, src/test/setupGlobalMocks.ts
Currently when attempting to run tests in an IDE we get an error due to the use of configuration not unsupported by Create React App:
```
These options in your package.json Jest configuration are not currently supported by Create React App:
• setupFiles
If you wish to override other Jest options, you need to eject from the default setup. You can do so by running npm run eject but remember that this is a one-way operation. You may also file an issue with Create React App to discuss supporting more options out of the box.
```
This PR removes the offending config, which wasn't used or needed anyway.
Tests running in an IDE are great again.
N/A
Small - if the tests pass we are 🛍️ 
☝️ 
☝️ 
N/A
=> chore: remove setupFiles config

src/Routes/RoutesCommon.tsx, src/components/AssetHeader/AssetActions.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/pages/Trade/Trade.tsx
- The assetIds have slashes in them so we needed to break that up into two params on the route.
- Update the breadcrumbs to filter out the chainId on trade page
- Was seeing the `Link` component would intermittently work so went ahead and just used `history.push()`
Note: we do not currently have a way to check if an asset is supported for buy/sell. Talked to @0xApotheosis about how we can abstract out that logic and use it in other places in the app. 
The other thing thats worth mentioning --- when clicking the trade button on an asset page you would expect it to fill the `sell` side of the trade and not the `buy` but we only support setting the default buy asset ATM. So at some point would be good to get the other side too.
closes #3482 
No more risk than the current deployment
Select an …
=> fix: rework the trade page routing

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Approve.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Approve.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx, src/lib/utils.ts, src/state/slices/opportunitiesSlice/constants.ts, src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts
- Use a type guard assertion to narrow to `FoxEthStakingContractAddress`
- Add a `getTypeGuardAssertion` convenience util to encourage more usage of this pattern moving forward
N/A - codebase quality.
Minimal - no run-time changes expected.
Not applicable - no runtime changes expected.
☝️ 
☝️ 
N/A
=> chore: add and use assertIsFoxEthStakingContractAddress type guard assertion and helper

src/assets/translations/en/main.json, src/components/AssetHeader/AssetActions.tsx
- Buy/Sell button in `AssetActions` only displayed for asset which are supported by our fiat ramps.
- Removal of the symbol in the button as it is implied by the context (with other asset actions). Not listed in the related issue but discussed/requested by @reallybeard
closes #3490 
None.
Verify the presence/absence of the `Buy/Sell` button on Asset and Account/Asset pages based on the support the asset has on our fiat ramps.
☝️ 
☝️ 
Asset supported by fiat ramp (note: no more symbol displayed in the button):
Asset not supported:
=> feat: buy-sell button only for supported assets

src/components/Trade/hooks/useSwapper/useSwapper.tsx
guard against possible missing account type when generating utxo account addresses
n/a - more paranoia/safety
very small, isolated to swapper - more safer receive address generation in swapper
* ensure we can get trade quotes when buying a utxo asset, and complete a small trade
👆
👆
n/a
=> fix: guard against possible missing account type before generating address

src/components/Trade/hooks/useDefaultAssets.tsx
Guard against possible missing account type when generating UTXO account addresses in default assets hook.
N/A - paranoia and safety.
Small, isolated to getting default assets.
Ensure default assets still work as expected, particularly for UTXO assets.
☝️ 
☝️ 
N/A
=> fix: guard against missing account type for UTXO buy account in default assets

package.json, yarn.lock
Fixes a bug where Avalanche trades on THORSwap were using a hard-coded (and incorrect) `AssetId`.
N/A
Small.
Perform an AVAX to DOGE trade (ensure it's using THORSwap). It should go through correctly, and DOGE should be received.
☝️ 
☝️
N/A
=> fix: use sell AssetId in getInboundAddressDataForChain

src/components/Trade/hooks/useDefaultAssets.tsx
Adds a similar guard as https://github.com/shapeshift/web/commit/080d71b0292d0a80b7dee467d5326a761ee41dd6, though the receive address here is not used when building transactions, so it's much less important.
This PR simply ensures we don't get false positives when checking for supported assets when selecting the defaults.
N/A
Small - limited to default asset computation.
Default assets should still show as expected.
☝️
☝️
N/A
=> chore: add additional default asset safety

package.json, yarn.lock
lib was still rugging us after the `toFixed()` change in web, this bumps `investor-foxy` to normalize the approve amount on exact approvals
closes #
low
- perform exact approval for foxy deposit with crypto value of >=1000
:point_up: 
:point_up:
=> fix: update investor-foxy package to fix exact approvals

src/components/StakingVaults/AllEarnOpportunities.tsx
This bug was only seen on wallets that had ATOM staking.  If no accountId was passed to useCosmosSdkStakingBalances then it would default validator information to ATOM.
Fix:
Pass accountId to useCosmosSdkStakingBalances so correct opportunity gets passed through.
closes #
Breaks Cosmos staking
Test that OSMO staking/unstaking works
Test that ATOM staking/unstaking works
Test that OSMO staking/unstaking works
Test that ATOM staking/unstaking works
=> fix: pass accountId to useCosmosSdkStakingBalances

src/state/apis/swapper/getBestSwapperApi.ts, src/state/apis/swapper/getTradeQuoteApi.ts, src/state/apis/swapper/getUsdRateApi.ts, src/state/apis/swapper/getUsdRatesApi.ts, src/state/apis/utils.ts
Part of some pre-factor work to handle THORSwap `halt` flags to better handle errors from `lib` and in our RTK query APIs.
- Improve error handling in the swapper API by returning an error object of the expected shape instead of throwing
- Ensure we always return a value on either the `error` or `data` keys of the RTK API response (a requirement of RTK query, but not enforced at a type level)
Contributes to https://github.com/shapeshift/web/issues/2925
Small. Whilst it touches swapper APIs, if everything feels right we should be 🛍️ 
A quick sense check that the trade widget still functions normally, though no changes are expected.
☝️ 
☝️ 
N/A
=> chore: improve API error handling

src/context/FoxEthProvider/FoxEthProvider.tsx, src/state/slices/opportunitiesSlice/selectors.ts
The current re/fetch on `<FoxEthProvider />` mechanism was a relic of the previous one which didn't use the opportunities abstraction:
- We should never select / re/fetch ETH/FOX LP userData. LP data is simply portfolio data, and the porfolio handles that as it should - the matching resolver is really just a check within the abstraction, *introspecting* portfolio balances for the LP token to check readiness, but not actually *resolving* it. Removed the relevant selector and its usage
- We should not call `fetchAllOpportunitiesUserData` when what we actually need is to only fetch *staking* data - `fetchAllStakingOpportunitiesUserData` is the guy, though still not optimized, we should make it fetch ETH/FOX staking data only in a follow-up PR
- We should not fetch opportunities data when …
=> feat(foxFarming): granularily refetch staking userData only

src/state/slices/opportunitiesSlice/opportunitiesSlice.ts, src/state/slices/opportunitiesSlice/resolvers/index.ts, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts, src/state/slices/opportunitiesSlice/resolvers/types.ts, src/state/slices/opportunitiesSlice/thunks.ts
This PR resolves and populates `DefiProvider.ThorchainSavers` opportunities.
Notes:
- APR cannot yet be fetched - to be fixed in a follow-up web PR after we upgrade our Midgard proxy:
https://github.com/shapeshift/web/blob/a369170145b78979ee9f9482664a50b75e5fe858/src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts#L103-L105
- Ethereum opportunity doesn't yet appear, figure out why and fix it in a follow-up web PR
- Tackles https://github.com/shapeshift/web/issues/3584
In theory, none given the resolver short circuits with the flag off right at entrypoint - in practice, see ops testing notes for actual risks given the slight refactor
- Toggle `REACT_APP_FEATURE_SAVERS_VAULTS`
- Ensure Thorchain Savers metadata is populated in store
- Logic has been slightly revamped …
=> feat: thorchain savers metadata resolver

src/features/defi/providers/cosmos/components/CosmosManager/Claim/components/Confirm.tsx
Precisely what the PR title says - the extra safety made the render loop with loading `assetId` crash the component, kicking the error boundary in
- closes https://github.com/shapeshift/web/issues/3588
N/A
- While having some active position with claimable amounts for ATOM, open the relevant card/row
- Confirm clicking Claim doesn't result in an errored state and it is possible to continue with the flow
☝🏽 
☝🏽
=> fix: don't throw in Cosmos SDK <Withdraw /> render while assetId is loading

package.json, src/assets/translations/en/main.json, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useIsTradingActive.tsx, src/components/Trade/utils.test.ts, src/components/Trade/utils.ts, src/state/apis/swapper/getIsTradingActiveApi.ts, yarn.lock
When a halt is placed on the THORSwap receiving pool of the outbound asset we'll still get quotes, but the "preview trade" button will be disabled, with a message informing the user of the halt.
- Prevents trades from being created whilst a THOR pool is halted.
- Adopts a fail-closed implementation. I.e. if we can't get confirmation from the THOR node that _an asset's pool is **not** halted_, we do not let the user create a trade.
- Adds a pure function consuming `getInboundAddressDataForChain`, which is consumed by an RTK query, which is consumed by a custom hook, which is consumed by the Trade component (React 🤯 )
TODO in a follow-up PR: make `getBestSwapper` logic aware of when a swapper can get a quote, but trading is disabled. This case requires some thought - do we just not include …
=> feat: handle THORSwap halts

src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
Untested: While trying to repro, the liquidity removal Tx actually went through despite the error in the render method
- closes https://github.com/shapeshift/web/issues/3589
N/A
- While having some liquidity in v4, open the v4 card/row
- Confirm clicking Withdraw & Claim doesn't result in an errored state
☝🏽 
☝🏽
=> fix: don't throw in <ExpiredWithdraw /> render while underlyingAssetId is loading

src/components/Trade/TradeInput.tsx
Possibly avoids a bug where we get a false negative "trade halt" message when we can't get a trade swapper.
I suspect we were hitting: 
```ts
if (!isTradingActiveOnSellPool && bestTradeSwapper.name === SwapperName.Thorchain) {
...
```
When we should have been hitting:
```ts
if (!bestTradeSwapper) return 'trade.errors.invalidTradePairBtnText'
```
Might fix https://discord.com/channels/554694662431178782/1062449976325718096/1062449979492413440
Small.
@0xdef1cafe do what you did to replicate the bug, and it should now show the `invalidTradePairBtnText` translation instead.
☝️ 
We should not show the trading halt message on the preview trade button for Osmo trades.
N/A
=> chore: tighten THORSwap halt errors

package.json, yarn.lock
Bumps swapper to 13.3.1
Fixes an Osmosis trade issue when building the transaction, and should now use the correct account number.
Small.
Osmosis trades should work.
☝️ 
☝️ 
N/A
=> chore: bump swapper to 13.3.1

src/components/Trade/TradeInput.tsx
Currently the "Preview trade" button flashes between different translation strings as network requests are made and state is computed.
This PR mInimises a lot of the visual text changes by displaying "Loading..." on the button if any swapper API requests are in flight.
N/A
Very small.
We should show "Loading..." whilst we get a quote (among other things).
The button text should settle on the final state once all swapper API requests are complete.
☝️ 
☝️ 
N/A
=> fix: improve trade button text

src/state/slices/txHistorySlice/utils.ts
Special case logic for thorchain was causing a "*" character to be unintentionally added to the serialized osmo trade txs.
This caused it to not detect "atom -> osmo" trades being completed because it couldnt match the string correctly
low risk bug fix
trade atom -> osmo and see it completes successfully
see testing
see testing
ble)
=> fix: completed atom to osmo trades

src/components/StakingVaults/AllEarnOpportunities.tsx, src/components/StakingVaults/EarnOpportunities.tsx, src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts, src/features/defi/helpers/normalizeOpportunity.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx, src/pages/Defi/components/OpportunityCard.tsx, src/state/slices/opportunitiesSlice/selectors.ts
First wire-up of Thorchain Savers metadata with functional overview modal.
Note, cap will need to bring a new concept of `opportunitySpecific` discriminated union a la `chainSpecific` - to be done in https://github.com/shapeshift/web/issues/3595.
closes https://github.com/shapeshift/web/issues/3584
Low given Thorchain savers metadata resolution is under flag, though the selectors logic has been slightly revamped, which could cause regressions.
- Enable the `SaversVaults` flag
- Ensure opportunity details is matching the one in https://app.thorswap.finance/earn / https://app.thoryield.com/savers
- This reads as sane code
- ☝🏽 
-☝🏽doesn't need to be tested since this is under flag
- Clear your cache and ensure opportunities still load as before (note intermittent node failures can happen in …
=> feat: wire up thorchain savers metadata/overview

package.json, yarn.lock
Get the Osmosis swapper caching from https://github.com/shapeshift/lib/pull/1161 in.
N/A - Osmosis support
Minimal
N/A
- Osmosis should still get quotes
- Less network requests should be made when using the Osmosis swapper
N/A
N/A
=> chore: bump swapper to 15.3.3

src/components/Trade/hooks/useAccountsService.tsx
A less nice, but less risky version of https://github.com/shapeshift/web/pull/3609.
> **Fixes `undefined` swapper on first render**
Fixes an issue where we would not get a swapper in the first render cycle if the asset pair's swapper supports cross-account trades. 
It's a multi-factorial bug with a simple fix. 
In summary: the bug is a side-effect from the account bug fix, where the early returning on the first render now leaves us with a receive address of `undefined`. This stops the first quote from firing, which stops us from getting a swapper now that getting the best swapper requires a quote - and if we don't have a swapper we show "Invalid Trade Pair". Phew.
N/A - known production bug.
Medium - small surface area, but it does relate to accounts, so we must tread with caution.
Things …
=> fix: undefined swapper on first render (concise)

src/components/Trade/hooks/useAccountsService.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx
- Add commentary on the `swapperSupportsCrossAccountTrade` util, as it's an important function that we do not want to use incorrectly
- Update `false` to be `undefined`. No runtime changes here, but semantically more correct - if we have no swapper, the disposition of a swapper can be neither `true` or `false`.
N/A
Almost 0.
N/A
☝️ 
☝️ 
N/A
=> chore: add swapperSupportsCrossAccountTrade commentary

src/components/Trade/TradeInput.tsx
When the "Preview trade" button is in the loading state it should be blue. This PR makes it so.
Closes https://github.com/shapeshift/web/issues/3620
As low as it gets.
When the swapper widget is in the "Loading..." state the button should be blue (not red).
☝️ 
☝️
=> chore: ensure preview trade loading button is blue

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts, src/state/slices/opportunitiesSlice/types.ts
Wire-up of THORChain opportunities caps, consuming current saver fill and max saver cap to display the ratio as a percentage
closes https://github.com/shapeshift/web/issues/3595
None, isolated to flagged THORChain savers feature
- Amounts/ratios look similar to https://app.thoryield.com/savers / https://app.thorswap.finance/earn
Note that numbers mightn't be the exact same because of discrepancies in the freshness of data from THORCHain API and the data in THORCHain UI / THORYield, as well as in the market data in those two UIs and ours
- Nothing to see here 🕵️
=> feat: wire-up THORChain opportunities caps

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx, src/state/slices/opportunitiesSlice/resolvers/idle/index.ts, src/state/slices/opportunitiesSlice/resolvers/yearn/index.ts
Rationale: We dispatch thunks in fetching all opportunities (LP/staking) user data in `<AppContext />`, one full run for each requestedAccountIds.
Currently that's not a lot of them given we only do so for ethChainId, but as we implement THORChain savers, that might be a lot of overfetching we could avoid.
N/A
None, if this causes regressions, we have bigger problems.
- Purge your persisted redux store
- Ensure opportunities meta/data is still fetched and displayed
- ^
- ^
=> feat: opportunities userData resolvers chainId safety

src/components/Bridge/BridgeRoutes/Confirm.tsx, src/components/Modals/Send/Form.tsx, src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx, src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx, src/components/Modals/Send/utils.ts, src/hooks/useEvm/useEvm.ts
This PR decouples the sending logic from `handleSend` to the view-layer stuff that's ran as part of it (toasts and modal close). Accidentally improves error-handling by making `handleSend` pure.
Required for THORChain savers deposits - since these are considered deposits from a UX perspective vs. sends, the DeFi modal will handle success and error states the toast would be handling.
Note, to keep this diff minimal, this does *not* give `handleSend` a better home yet, but I'll PR a follow-up on top of this after the quotes/deposit PR https://github.com/shapeshift/web/pull/3630 is ready, to move it from `src/components/Modals/Send` to `src/lib/send`.
N/A
Moderate - there should be no runtime change for actual sends, though the side-effects might be broken - tested with ATOM which …
=> feat: decouple handleSend and handleFormSend

src/plugins/pendo/agent/parse.test.ts, src/plugins/pendo/agent/parse.ts
fix: check if last line is empty on parse (#3647)
fix: update new line for pendo agent (#3646)
=> chore: release v1.194.0 [DO NOT MERGE]

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
This PR ensures we use either an arbitrary chosen address (the one with the most balance as accumulated UTXOs) or the previously deposited from address as `from`, meaning UTXOs will be filtered to be the one from it, and they will be used as a change address, see https://github.com/shapeshift/lib/pull/1168
This also brings the notion of either one or two Txs being broadcasted in the same block:
- At best, one Tx if the picked address has enough UTXO value
- At worst, a pre-Tx to send max to that address, and then the originally intended Tx
Notes:
- this only applies to UTXOs, since with other blockchains we support, the account *is* the address so we don't have such problem.
N/A
- None, isolated to savers
- It is possible to deposit into UTXO savers
- The change is sent to the address …
=> feat: use either savers previous address or highest balance xpub address as `from`

src/state/slices/opportunitiesSlice/selectors/lpSelectors.ts
* fixes LP opportunity fiat amounts that were previously shown multiplied by a factor of 10^{asset_precision}
closes #
None
* In both the prod and dev environments, start the application with the demo wallet attached. 
* Navigate to the defi overview page.
* Verify that the fiat balance shown for the ETH/FOX pool match 
Same as above.
Current state of the defi overview page in the develop environment:
Current state of the defi overview page in the production environment:
Defi overview page in local environment with fix applied:
=> fix: unbreak lp opportunity fiat amounts

src/features/defi/contexts/DefiManagerProvider/DefiManagerProvider.tsx, src/features/defi/contexts/YearnProvider/YearnProvider.tsx, src/state/slices/opportunitiesSlice/resolvers/foxFarming/index.ts, src/state/slices/opportunitiesSlice/resolvers/foxy/index.ts
Kills three birds with one stone:
- Doesn't throw on Yearn feature flag disabled. That's a developers' concern only, so outputs a debug log and early returns instead of throwing
- Handles `query.provider` not being defined in the context of `<DefiManagerProvider />` which made us loop over all providers in `renderModules` and eventually return `undefined`. The reason for that is as a provider, it's not only "rendered" when in the context of a DeFi module, but is rather *always*  rendered
- Adds missing early bail safety factor based on chainId checks for resolvers
N/A
None, though as a stretch this effectively touches the `<DefiManagerProvider />` logic, ensure DeFi modals still open
- DeFi modals still open
- Console is happier with debug level
- Console is even happier with …
=> feat: cleanup log spew

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/ThorchainSaversWithdraw.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.test.ts, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
This PR handles THORChain savers withdraws - memoless for the time being.
To be handled as stack on top of this one: 
- The status screen doesn't yet show dust/fees. We will need some additional routing logic for that: given at this point the Tx is already ongoing and the quote is final, we should *not* do the same quote-fetching logic we're doing here
- Confirmed working:
N/A
None, isolated to savers
- Withdraw a percentage of your position that's not close to the max (can be user-input or a percent option)
- Wait for the Tx to be confirmed on-chain
- Reload the app, wait for the position to refresh, and ensure funds are deducted from your DeFi position and back in your wallet
☝🏽 
☝🏽
=> feat: thorchain savers withdraw

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/WithdrawCommon.ts, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/WithdrawReducer.ts, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
Passes down the dust amount and network fee from the final quote as withdraw route params, so that we can consume them at status step.
N/A
- Do a withdraw up to the sign and broadcast step
- Click sign and broadcast, and confirm the values are matching the ones at confirm step
- ☝🏽 
- ☝🏽
=> feat(savers): pass dust amount / network fee in withdraw routes

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
Adds missing savers safety:
- Deducts gas from maxish sends when doing a reconciliation Tx - uses gas * 3 as safety factor and to keep gas away for future Txs
- Awaits a `setTimeout` of 5000ms to ensure the reconciliation Tx is seen on the mempool before the second gets broadcasted
N/A
This handles maxish sends, but smallish ones could be rugged if I got this wrong
- Deposit around max of any UTXO (max, or anything between max and the `fastFee` e.g 1 sat less than max)
- Ensure the deposit goes through and some dust is returned to you for future Txs
- ☝🏽 
- ☝🏽
=> feat(savers): maxish UTXO deposits / mempool seen safety

src/plugins/walletConnectToDapps/utils.ts
- `contractAddress` causes non obvious and incorrect changes to the transaction value. treat wallet connect request payload as explicit unsigned transaction params
closes #
Low
- Ensure gas estimation works for uniswap via wallet connect (fix test)
- Ensure standard eth and erc20 sends still work as expected via wallet connect (regression test)
:point_up: 
:point_up:
=> fix: remove contractAddress from getFeeData call

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
Fixes initial deposits for BCH, for which we're getting the highest balance account address and forgot to slap the `bitcoincash:` prefix in, making `utxoSelect` unable to select any UTXOs.
N/A
None
- On an account currently not deposited into BCH savers, do a first deposit
- The Tx should go through, vs. us errroring with a toast currently
- ☝🏽 
- ☝🏽
=> fix(savers): bch initial deposits

src/components/Modals/Send/utils.ts, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
With regular sends, sendMaxes are precisely that, combine all your available inputs and send it all, you will effectively send all of your balance and the receiving address will receive all your balance, minus the gas that occurs, using the `split` algorithm:
> Split - splits the input values evenly between all outputs, any provided output with .value remains unchanged
However, in savers context, sending max means we want to keep gas away for future deposit/withdraws, so we escape hatch from the sendMax split logic, send max minus some gas kept away, and let coinselect figure out the optimal algorithm.
closes #
=> feat(savers): don't sendMax UTXO sendMaxes

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
Spotted by @shapeshift/operations - the outbound fee is not inclusive i.e withdrawing the exact outbound fee is going to fail, and adding one sat/wei/uatom isn't enough as a safety factor.
Fixed by adding 5% to the outbound fee to ensure we are many many base units away from the outbound fee and minimum withdraws are going through.
Tested with AVAX, ETH, DOGE and ATOM.
N/A
=> fix(savers): minimum withdraws 5% safety factor

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/ThorchainSaversWithdraw.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
Adds some `AccountId` safety at status step, to ensure we serialize a Tx for the correct one.
N/A
None, if we have issues with this, it means a bigger problem as transactions serialization from messages would be wrong across the app
- Withdraw from any account > 0
- Ensure the Tx shows as confirmed after on-chain confirmation
- ☝🏽 
- ☝🏽
=> fix(savers): multi-account withdraw confirmed state

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
Does what this says on the box, effectively ensures we are calling THOR API with the right BPS, so that we can:
- withdraw the exact amount displayed (minus withdraw fees displayed at confirm step)
- withdraw actual max amounts and not off by whichever percent the rewards-including amount is off 
N/A
- Select a percentage withdraw value
- Ensure `getWithdrawBps` return value / network requests are matching said percentage
- Withdraw any value
- Ensure the amount you receive is equal to the amount requested to withdraw - network fees
=> fix(savers): include rewards in available withdraw amount

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
This PR is both a feature and a safety net:
- By using the 0th address index for UTXO deposits vs. the highest balance address previously, we ensure that we are consistent with THOR UIs (THORSwap, RUNE wallet) and deposits from the same address, meaning that positions from ShapeShift will be visible on other UIs, and vice versa
- Since unchained accounts for unconfirmed balances in addresses balances, and the highest balance account address may effectively change after a deposit (but while savers didn't yet process it, meaning this address doesn't appear on the savers list we get), there is a chance users might re-deposit. If they do so, and another address is used, we would effectively be in a situation where funds are "stuck", as we use xpubs as indexes and aren't able to display …
=> feat(savers): use 0th address index for UTXO deposits

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
Prerequisite for https://github.com/shapeshift/web/pull/3723 to go in - same issue as we had previously over DeFi modals and multi-account, we need an `AccountId` to render the deposit modal, but we won't have an `AccountId` until we are in the deposit modal, given we now have an empty screen without `onAccountIdChange()` logic, instead of the regular overview modal.
N/A
Low, routing could be borked over savers opportunities.
- THORChain savers routing still works
- Highest balance AccountId selection still works
- ☝🏽 
- ☝🏽
=> feat(savers): unrug overview default AccountId

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
Some assets (EVM and Cosmos assets, i.e any savers L1 that's not an UTXO) supposedly have a 0 dust_limit, which theoretically means 0 is the limit of dust to send for deposits/withdraws.
However, sending a value that's very close to zero will fail quote checks at "not enough fee".
Fixed by setting `outboundFeeCryptoBaseUnit` as a state field and checking if the current amount is lower than it, in addition to the dust amount checks.
Note that for UTXO assets, we set the outbound fee to 0, since the dust limit is enough to pass quote validation, resulting in smaller amounts being able to be deposited (e.g DOGE would be 1 DOGE dust limit but 15 DOGE outbound fee
N/A
- Minimum deposit amounts are the same as develop/prod for UTXOs
- Minimum deposit amounts are higher than develop/prod for …
=> feat(savers): minimum outbound fee for 0 dust_limit assets

src/components/AccountDropdown/AccountDropdown.tsx
- Sometimes depending on where its rendered the account dropdown will get cut off. So wrapping it in a portal so it renders outside of the relative position.
closes #
No risk
On the DeFi deposit screen for any opportunity you should see the full list of accounts and it will not be cut off.
Before: 
After:
=> fix: overflow issue on account dropdown

package.json, src/components/Trade/TradeConfirm/TradeConfirm.tsx, yarn.lock
- bump swapper package to fix zrx approve infinite amount
- use `toFixed()` over `toNumber()` to avoid scientific notation on fee amount
closes #
low
- zrx approve infinite should use correct `MAX_APPROVAL_AMOUNT` and not require re-approval on subsequent trades
- zrx trade network fee should be shown in crypto amount (not scientific notation)
:point_up: 
:point_up: 
Before:
After:
=> fix: correct zrx approve amount

src/components/Trade/hooks/useAvailableSwappers.tsx
Fixes a race condition between the trade form state and `useTradeQuoteService` custom hook state.
Side note, I think we need to rearchitect the way we store and mutate trade state (i.e. don't use a form to store global-ish state).
A proper reducer would likely solve a lot of these race conditions we need to guard against and keep us in a more reliable/consistent state.
@kaladinlight FYI, this fixes your Optimism bug.
- [ x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
N/A
Small, only adds a guard against setting `availableSwappersWithQuoteMetadata` when the trade form state is mismatched.
1. Hard refresh on dashboard
2. Navigate to ETH on Optimism
3. Click "Trade" and _don't_ see the halt error state
☝️ 
☝️ 
N/A
=> fix: race condition between form & custom hook state

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
Oddly specific PR name checks out:
We weren't passing the `from` param to `getFeeData`, which is actually fine for UTXO chainIds (UTXO adapters simply call `/v1/api/fees`) and Cosmos SDK chains for which the gas fee is an overestimated hardcoded fee.
What happens for EVM chains you might ask? We call the fees estimation endpoint with an empty string, which gets casted and eventually passed as the zero address as an Ethereum JSON-RPC arg.
Which in the Avalanche network means https://snowtrace.io/address/0x0000000000000000000000000000000000000000 (19.152396814393078034 AVAX  at the time of writing) and in the Ethereum world https://etherscan.io/address/0x0000000000000000000000000000000000000000 (11,532.471398198970121614 ETH at the time of writing).
tl;dr if you deposit > ~400$ AVAX or > …
=> fix(savers): estimate gas for deposits > 19.152396814393078034 AVAX/ 11,532.471398198970121614 ETH

package.json, src/components/Trade/utils.ts, yarn.lock
We currently enforce that all THORChain trades require confirmation that the sell asset's inbound asset in not halted.
We do this via the `inbound_addresses` endpoint, but this is not relevant for `RUNE` (it's a single hop trade, and does not have an inbound address, per se).
This PR adds a new, different, check on trades form `RUNE` against the `HALTTHORCHAIN` flag on the `mimir` endpoint to ensure that THORChain is not halted. 
This check is likely overkill, as the transaction, in theory, wouldn't even go through if the chain was halted, but safety first.
https://twitter.com/cryptoisnice/status/1621680381329129474
Small - well contained, though affects halt logic so if incorrect could incorrectly halt assets.
Ensure that:
1. Trading from RUNE is possible (not halted)
2. Using THORSwap …
=> fix: incorrect RUNE halt

src/components/Layout/Header/NavBar/Notifications.tsx
- fix: enable wherever widget for mobile wallet
wherever widget is explicitly enabled for `Native` and `KeepKey` `KeyManager`'s - but we missed `KeyManager.Mobile`. the mobile wallet is still the native wallet, the keys are just managed in the secure enclave of the device, and such it identifies itself differently. this was just a minor oversight and has no real risk associated with it.
n/a
minimal, isolated to wherever widget not appearing on mobile
wherever widget should appear on mobile
=> fix: wherever widget on mobile native wallet

.github/workflows/pr.yml
CI runs can now be triggered by PRs, or the merge queue
the PR title isn't available in the merge queue, so it immediately fails
this is a teething issue - if we fully adopt the queue we'll skip CI on the PR and only run it in the queue
n/a
CI is sad
send it and see
no app code changes/testing required
=> chore: skip commitlint in merge group CI invocation

package.json, yarn.lock
Updated Wherever widget version which includes padding top using `env(safe-area-inset-top)` to account for mobile notch
=> fix: bump wherever version to support mobile gap

src/components/Layout/Header/NavBar/ExpandedMenuItem.tsx, src/components/Layout/Header/NavBar/Native/NativeMenu.tsx, src/components/Layout/Header/NavBar/UserMenu.tsx, src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx, src/context/WalletProvider/config.ts
- Wallets can now add a `connectedMenuComponent` that will render within the wallet dropdown
- Native right now is the only wallet that will use this
- I also tidied up the KeepKey menu a little
closes #3829 
small risk
When connected to a native wallet you will now see in the wallet dropdown a "backup my wallet" menu item. And the header should be in a disabled state to signify that it has no sub menu.
This should not change the currently functionality for existing wallet sub menus e.g. KeepKey
=> fix: bring backup wallet out of sub menu

src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Deposit.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Confirm.tsx
* Updates the default slippage tolerance for Osmosis LP deposit/withdraw transactions to 2.5%. This matches the default settings used on app.osmosis.zone, and will improve the reliability of lp deposit/withdraw transactions.
closes #
None 
*From the DeFi section, select any Osmosis LP opportunity.
* Ensure that LP deposit and withdraw transactions are broadcast successfully, and that the shareOutAmount slippage does not exceed 2.5%.
See above.
=> fix: increase osmosis lp default slippage tolerance

src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Confirm.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx
* fixes zero amounts on Osmosis LP withdraw confirm modal
* automatically switches the osmosis lp withdraw receive amount precision on value entry
closes #
* Select an Osmosis LP opportunity from the DeFi earn page
* Initiate a withdrawal and verify that the amount field values are formatted in single-digit precision before a value is entered and six-digit precision after a value has been entered
* Click continue and verify that the confirm modal amount fields contain the correct values
=> fix: osmosis lp withdrawal confirm amounts

src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx
Spotted by ops in https://discord.com/channels/554694662431178782/1066088208905031681/1077736668167163904
> 2. still showing 0 osmo in the withdraw screen for token LP withdrawals
Fixes the wrong precision of asset 0 being used for asset 1 at withdraw step, which accidentally worked for the ATOM/OSMO LP since both have the same precision, but won't work for some IBC token / OSMO, since they might have any precision (18 for INJ), but OSMO only has 6 dp.
N/A
None
- Withdraw from any Osmo LP - test with a few different ones including ATOM/OSMO
- Ensure a crypto value is present both for asset 0 and asset 1
- ☝🏽 
- ☝🏽
=> fix: osmosis lp withdraw asset 1 precision

src/features/defi/components/Deposit/PairDepositWithAllocation.tsx
Spotted by ops in https://discord.com/channels/554694662431178782/1066088208905031681/1077736668167163904
> 5.Select USD amount still gives a higher balance of osmo than is in the account 
Fixes the wrong market data of asset "1" being used instead of the asset "2" one in https://github.com/shapeshift/web/pull/3890/commits/f40ffe833abff6103a4034e8cee12b05b533a999
~~Also consolidates the terminology from asset 1/2 to 0/1 in https://github.com/shapeshift/web/pull/3890/commits/295b4568c694ae4f1e47f776aef35db8bf0d1b22 to avoid such confusion in the future~~  split as a follow-up stack in https://github.com/shapeshift/web/pull/3892
N/A
None
- Deposit to any Osmo LP - test with a few different ones including ATOM/OSMO
- Ensure the fiat balance shown for the asset 1 (e.g OSMO in ATOM/OSMO) is …
=> fix: osmosis lp deposit asset 1 fiat balance

src/features/defi/components/Deposit/PairDeposit.tsx, src/features/defi/components/Deposit/PairDepositWithAllocation.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Deposit.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Deposit.tsx
This PR
- Consolidates the pair terminology from asset 1/2 currently to being consistent in referring to the first and second asset of a pair as asset 0/1, like how e.g Uniswap is referring to pair tokens as `token0` and `token1`
- Fixes the order of ETH and FOX in the ETH/FOX components.
N/A
Low, though scrutinize I didn't derp the rename, and ETH/FOX and Osmo LP deposits show no regressions
- Osmosis pair deposit shows no regressions
- ETH/FOX pair deposit shows no regressions
- ETH/FOX pair displays ETH as the asset 0 and FOX as the asset 1, matching the "ETH/FOX" pool order where ETH is the `token0` and FOX is the `token1`, not the other way around
- ☝🏽 
- ☝🏽
=> feat(defi): asset 1/2 -> 0/1 terminology

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx, src/state/apis/swapper/selectors.ts
Little UX improvement, spotted while testing LTC savers while the THOR LTC pool was halted.
Moves the halted check from the deposit step to the overview, ensures the modal is in a loading state while the active trading query is pending, and disables the deposit button if trading is halted.
N/A
- If testing while some THOR pools are halted, ensure the deposit button is disabled and the tooltip matches the one on the screenshot
- If all THOR pools we support as savers are live, there shouldn't be any flow change here
- ☝🏽 
- ☝🏽
=> feat: improve savers deposit halt flow

src/components/Approval/Approval.tsx, src/components/Trade/hooks/useSwapper/utils.ts
Brings some additional safety in `chainSpecific` being undefined - it shouldn't be, but if it is across render cycles, we will now gracefully handle it and log it at debug level.
See error spotted by @wesleygravess 
N/A
None, apart from this not fixing the root cause but it will at least give us some indication whether or not that's an actual upstream error, or only render cycles shaenanigans.
- Connect to the app with native or KK
- Go to Osmosis asset
- Wait ~30ish seconds
- Go back to dashboard and ensure the app doesn't crash
- Repeat, refresh, repeat again and ensure the app still doesn't crash with the error above
- Logging looks sane
- ☝🏽
=> fix: getFormFees crash

src/state/apis/types.ts, src/state/slices/txHistorySlice/txHistorySlice.ts
we'd previously keep paginating all tx history until we no longer had any pages to fetch from the backend
this change causes us to always at least fetch the first page of txs per account, which are ordered as newest first.
this means we'll always pick up latest txs on a fresh page load.
we then compare the fetch tx ids to the existing tx ids in the store. if there aren't any new txs, we stop paginating tx history for that accounts.
this means reduced network requests and better render performance for accounts with large tx history.
slightly inaccurate description, but closes #3928
isolated to tx history
* for a given wallet in prod, clear your application storage, then load up a chosen wallet. check the total tx ids length in redux.
* clear your application storage locally against this …
=> fix: don't refetch existing txs

src/context/FoxEthProvider/FoxEthProvider.tsx, src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/FoxEthLpManager.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/FoxFarmingManager.tsx
Does what it says on the box, see [spotted bug by @MBMaria](https://discord.com/channels/554694662431178782/1083140756652433428/1083149078365483008) in https://github.com/shapeshift/web/pull/3989:
> the account with the highest balance comes up when selecting eth/fox LP pre and post deposit. However, after i do a deposit or withdraw, the overview will default to account 0, even though my highest balance is account 1 🤔 
N/A
- This could actually unveil some deeper issue and rug the account selection altogether if we happen to do unmounts and remounts we shouldn't
- Have your highest LP/Staking staked balance on any account > 0
- Open the modal
- Ensure the highest balance account is still selected
- Select account 0 (or any account other than your highest balance one for that matter) and …
=> fix: hanging ETH/FOX LP/staking selected AccountId 

src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx, src/features/defi/providers/foxy/components/FoxyManager/useFoxyQuery.ts, src/features/defi/providers/idle/components/IdleManager/Claim/IdleClaim.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx, src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
Making sure we use the right selector - `selectStakingOpportunityByFilter` previously didn't exist and we had to select all opportunities then index by the LpId/StakingId. Now that we have an `id` field, we can use the byFilter selector to select opportunities.
N/A
Theoretically none, same thing better selector
- No need to broadcast an actual Tx for any of these, only ensure against prod that the displayed data looks sane
- THORCHain saver overview modal show no regressions
- FOXy flow (all modals) show no regressions
- Idle claim modal shows no regressions
- ☝🏽
- ☝🏽
=> feat: selectStakingOpportunities -> selectStakingOpportunityByFilter

react-app-rewired/index.ts
i hate everything about this
the app has become so large (again) that now some other webpack plugin within create react app is bitching about the size of generated assets being too large to be cached
this increases the cache size of the assets - if it works i simply don't care about this approach being nasty
n/a
like everything in life, it's a coin flip - it either works or it doesn't
pull branch and run the build locally
if you don't see
```
Compiled with warnings.
/static/js/30.fc1b3e4d.js is 7.19 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.
``` we're good
not testable by operations
=> fix: fix build cache limit issue

src/components/Trade/TradeConfirm/TradeConfirm.tsx
Fixes an issue where THORSwapper trade status was not updating once the trade was confirmed.
It needs to work around some interesting implementation decisions in `lib`, which are better tackled separately (wen monorepo?).
This makes trade status great again until then.
Closes https://github.com/shapeshift/web/issues/3621
Small, limited to trade status UI.
Trades using THORSwapper should now correctly show the "pending" and "completed" status.
☝️ 
☝️
=> fix: thorswapper trade status

src/components/EarnDashboard/components/PositionDetails.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Overview/OsmosisLpOverview.tsx, src/state/slices/opportunitiesSlice/resolvers/osmosis/index.ts, src/state/slices/opportunitiesSlice/selectors/lpSelectors.ts, src/state/slices/opportunitiesSlice/utils.ts
This PR:
- implements `underlyingAssetRatiosBaseUnit` which was wrong for Osmosis LP resolver
- removes `underlyingAssetsCryptoPrecision` and a bunch of associated effect/state fields fluff
- removes unused `underlyingToken0AmountCryptoPrecision` and `underlyingToken1AmountCryptoPrecision` for osmosis
- fixes `getUnderlyingAssetIdsBalances` logic which was dividing the final *LP amount * ratio* number by `underlyingAssetPrecision`, where this number should eventually be divided by the *lp* asset (the one which precision we originally start from, since we're starting from an LP token amount, not an underlying amount)
- fixes consumption of `getUnderlyingAssetIdsBalances` in  `selectUnderlyingLpAssetsWithBalancesAndIcons` where we passed what was intended to be`cryptoAmountBaseUnit` , but …
=> fix: osmosis underlyingAssetRatiosBaseUnit

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx, src/state/zustand/swapperStore/selectors.ts, src/state/zustand/swapperStore/types.ts, src/state/zustand/swapperStore/useSwapperStore.ts
We are not correctly using the dynamic slippage value from THORSwapper, and are instead using the default of `0.2%` for all trades.
This PR fixes that bug, and adds a selector on the zustand swapper store to access it, better normalising the state.
N/A, noticed a comment in #general: https://discord.com/channels/554694662431178782/554694662896615436/1086852480484253737
Small, only affects the slippage used in a trade. If it's too low (as it currently is for very large trades) the trade will simply not go through.
When performing a THORSwap trade we should see a dynamic slippage value instead of the default 0.2%.
☝️ 
☝️
N/A
=> fix: dynamic THORSwapper slippage

src/components/Approval/Approval.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useAccountsService.tsx, src/components/Trade/hooks/useFeesService.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx, src/state/zustand/swapperStore/selectors.ts
More swapper clean-up now that zustand is in - move some more logic to selectors so we can rely less on custom React hooks and select straight from the zustand state.
Improving architecture as we move towards swapper selection.
Small, no logic changes - just extracted Reactive code into pure selectors.
Swapper should work normally, in particular:
- Approvals
- Cross-account trade lock (e.g. 0x)
☝️ 
☝️ 
N/A
=> chore: use swapper selectors

src/state/slices/opportunitiesSlice/selectors/combined.ts
Fixes the `By Provider` view so that claimable rewards are only displayed in the columb header in case there are *akschually* *claimable* rewards for that provider
N/A
None
- With the new `DefiAggregation` flag enabled, open the `By Provider` view
- Ensure that, in the outer column for that provider, rewards are shown in case you have rewards, else `-`
- Ensure the inner columns (i.e the aggregated opportunities) are matching the outer column ones i.e no rewards for that provider should mean no rewards for individual opportunities
- ☝🏽 
- ☝🏽
=> fix: by provider claimable rewards column

src/components/Trade/hooks/useSwapper/getTradeQuoteArgs.tsx
Trading from a CosmosSDK asset is currently broken, as entering input amounts do not work.
This PR adds a missing check to update `tradeQuoteArgs` on input for CosmosSDK assets, fixing a regression caused in https://github.com/shapeshift/web/pull/3947.
N/A - production bug
Very small.
Input amounts when trading from CosmosSDK assets should work correctly.
☝️ 
☝️ 
N/A
=> fix: input when selling CosmosSDK asset

src/state/slices/opportunitiesSlice/selectors/combined.ts, src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
Brings up discrimination between the claimable and unclaimable rewards, so that we only display the ones that are actually claimable.
N/A
- Ensure the `DefiAggregation` flag is on
- Go to DeFi Earn
- With either the "By Provider" or "By Position" table selected, only the total of claimable rewards from opportunities with claimable rewards should be displayed, e.g THORChain should never have claimable rewards, but ETH/FOX staking rewards should always account for the total. If it appears on the individual rows, then it should account for the total of that provider
- This shouldn't bring regressions in the actual amounts e.g Net Worth
- ☝🏽 
- ☝🏽
=> fix: display claimable rewards only in defi aggregation table

src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx, src/state/slices/opportunitiesSlice/resolvers/foxy/index.ts, src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
Fixes the max delayed withdraws making the opportunity "disappear" for FOXy after the delayed withdraw is initiated.
closes https://github.com/shapeshift/web/issues/4103
I got the heuristics wrong and claimable after the completionTime isn't working, test accordingly
1. Percent withdraw FOXy with delayed withdraw
2. Ensure your position is still visible after the Tx completes and positions refetch - should also still be visible after a refresh
3. Hard refresh and repeat testing steps 1. and 2. 
- Rewards / pending claims heuristics look sane
- ☝🏽
=> fix: foxy max delayed withdraw

src/pages/Dashboard/Portfolio.tsx, src/pages/Dashboard/PortfolioBreakdown.tsx, src/pages/Dashboard/components/DashboardHeader.tsx
Following up on https://github.com/shapeshift/web/pull/4111, now that we have tabs showing the breakdown between wallet, earn, and reward balances, the total doesn't match up "Net worth" as the rewards are currently not included in that number.
This PR includes them - note that this only includes *claimable* rewards. Discussed this one out with @reallybeard and since we don't include unclaimable ones in the "Reward Balance"
N/A
Low/none, if we got this wrong, we got bigger problems
- Enable the `DashboardTabs` flag (to be consolidated into `DefiDashboard` in a follow-up PR, so if you're testing this as the follow-up as been merged, enable `DefiDashboard` instead)
- Ensure "Wallet Balance" + "Earn Balance" + "Reward Balance" equals to the net worth
- ☝🏽 
- ☝🏽
=> feat: include claimable rewards in net worth

src/assets/translations/en/main.json, src/components/Modals/Settings/SettingsList.tsx
requested by ops - a button in the settings modal to clear the redux cache and reload the app
this PR will
* clear the redux cache
* navigate the user back to the dashboard
* do a hard reload of the app
n/a
low - clearing cache is useful for support to triage issues
* hit the button
* notice the app reloads
* see wallet/earn/rewards balance repopulate
* see consent banner reappears (this won't mess with mixpanel tracking)
as above
as above
https://user-images.githubusercontent.com/88504456/228676635-92b5469a-d1ef-43ff-a466-cb0753a6466f.mov
=> feat: clear cache button

src/components/Layout/Layout.tsx
fix - don't show error/warning banner about not being able to fetch a chain if the flag is off and we don't have the chain name
we often have issues with chains shortly after we launch them
case in point - bnb node currently sad, and we're showing the error in screenshot below with an empty name, which isn't useful to the user
this is because of the plugin model and we don't have the chain adapter available, hence no chain name
n/a
basically zero - hiding a banner if we don't have useful info to display
ensure my early return is sane lmeow
unable to be tested by ops
prod currently
this diff
=> fix: don't show empty errored chain names

src/components/Trade/hooks/useAvailableSwappers.tsx
When multiple swappers are available, we want to show halted swappers last in the list (even if they have the best rate). The list order is also used to determine the initial (active) swapper selection, which should be the best non-halted swapper.
Contributes to https://github.com/shapeshift/web/issues/3468.
Small. If we are getting all expected swappers, all is well.
Enable the `REACT_APP_FEATURE_TRADE_RATES` feature and ensure swappers are shown in the correct order, and that all expected swappers are listed.
👆
You could monkey patch the halt flag to false is interested.
👆
N/A
=> feat: tail halted swappers

src/components/Trade/Components/TradeQuotes/TradeQuote.tsx, src/components/Trade/hooks/useIsTradingActive.tsx
Improves colors of swapper boarders to better reflect their status (see screenshots below). 
N/A
Small - isolated to one component, and visual-only.
Test each of the different quote states in the screenshot below and ensure that the UI looks as expected.
Additionally, ensure no happy-path regressions.
☝️
☝️
**No amounts entered**
**Valid quote, swapper not halted**
**Fees higher than sell amount**
**Swapper halted**
=> feat: context-specific swapper colors

src/assets/translations/de/main.json, src/assets/translations/en/main.json, src/assets/translations/es/main.json, src/assets/translations/fr/main.json, src/assets/translations/pt/main.json, src/assets/translations/ru/main.json, src/assets/translations/tr/main.json, src/assets/translations/uk/main.json, src/components/StakingVaults/PositionTable.tsx, src/components/StakingVaults/ProviderTable.tsx, src/state/slices/opportunitiesSlice/selectors/combined.ts, src/state/slices/opportunitiesSlice/types.ts
This PR tackles the APY displayed for DeFi providers/AssetIds tables - ensures we display top-level blended active APYs *only* (i.e, not the ones inactive), in case the user has an active staking for said asset/opportunity type.
Else, if the user has no active staking, ~~blends inactive APYs only~~ use the highest APY from the displayed opportunities (discussed with @willyogo).
Note, this does not contribute the APYs range. The reason for this is a range is not a number, thus:
- sorting wouldn't work anymore
- we wouldn't be able to use `<Amount.Percent />` and would have to resort to a bunch of hacks to get the same UI as the current one
closes https://github.com/shapeshift/web/issues/4117
=> feat: active blended APY by AssetId/Provider

src/assets/translations/en/main.json, src/components/Layout/Header/NavBar/UserMenu.tsx, src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
The current UI when a wallet is locked is a little rough on the user. 
As a user, if my Metamask wallet is locked, and I want to disconnect it or switch to another wallet, I have to first unlock my wallet to access the menu to do so. If the Metamask plugin is in a broken state, or I don't have my password available I'm now stuck.
This PR enables access to the menu whilst a wallet is locked.
Production:
This PR:
CC @shapeshift/product & @reallybeard.
N/A
Small
To replicate the state this PR aims to improve:
1. Connect to the Dashboard with Metamask
2. Lock the wallet
3. Refresh the dashboard
4. Notice that you can now disconnect/switch wallets
Also ensure that there are no regressions connecting to or disconnecting from other wallets.
☝️
☝️
As above.
=> fix: locked wallet UI

src/assets/translations/en/main.json
Tooltip copy update:
"Something about vault caps" -> "Current maximum capacity for this vault"
=> fix: update vault cap tooltip

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
This PR fixes the "days to break even" calculation for THORChain savers deposits.
Previously, we were using the slippage to calculate these, which led to wrong days to break even.
The slippage only occurs on large amounts and is only a part of the total fee, which also includes outbound fees on the THOR network.
Fixed the break-even calculation to accurately reflect the total fee for the deposit:
- if the deposit fee is lower than the daily amount to break even, we now show a value of 1 (instead of 0, which is what we would get by `toFixed()`ing the result). Unconfirmed with @reallybeard, happy to actually show 0 or a fraction of 1 if we deem it to be better UX.
- if the fee is higher and it may take more than a day to recoup, we now show the correct amount of days.
While at it, abstracts …
=> fix: thorchain savers deposit days to break even

src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx, src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
This PR removes the "days to break even" feature on THORChain savers withdraw. Fair dinkum, once you withdraw, you're not earning any more yield, so why talk about "breaking even"? It's like trying to teach a koala how to surf - it just doesn't make sense.
By ditching this feature, we're keeping it simple, like throwing another shrimp on the barbie. You've withdrawn your savers deposit, you've earned your crypto, and now it's time to enjoy your hard yakka. No more worries about breaking even - it's time to put your feet up and have a cold one with your mates.
So go ahead, withdraw those profits and enjoy your newfound riches. No more cobblers, just pure, unadulterated gains. I'm stoked to be making this change and hope you'll be chuffed too.
N/A
- There is no "Days to break even" shown …
=> feat: remove days to break even on savers withdraw

src/lib/math.ts
Extracted from https://github.com/shapeshift/web/pull/4152 as a separate PR given the high risk.
It seems that our very own contributor (yes ChatGPT, this is me ty) has been working harder than a Frenchman during Bastille Day to fix a sneaky bug that was causing some amounts to be rounded down faster than a Frenchman can say "ooh la la!"
The bug was caused by the use of `displayDecimals = 6` as the last argument of `fromBaseUnit()`, which resulted in some amounts being stripped down to zero faster than a Frenchman can finish a croissant!
But have no fear, this PR is here to fix this bug and restore the lost precision faster than a Frenchman can say "merci beaucoup!" So go ahead and use our product with the confidence of a Frenchman sipping a café au lait at a Parisian café!
N/A
High. Hold …
=> feat: full precision fromBaseUnit()

packages/swapper/src/swappers/thorchain/cosmossdk/getCosmosTxData.ts, packages/swapper/src/swappers/thorchain/evm/utils/getThorTxData.ts, packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.test.ts, packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts, packages/swapper/src/swappers/thorchain/types.ts, packages/swapper/src/swappers/thorchain/utils/getLimit/getLimit.test.ts, packages/swapper/src/swappers/thorchain/utils/getLimit/getLimit.ts, packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.test.ts, packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.ts, packages/swapper/src/swappers/thorchain/utxo/utils/getThorTxData.ts
This PR makes sure Thorchain's `getTradeRate` gives us the original trade rate (from the THOR quote), i.e the rate including fees and slippage, so we can deduct these later on.
We are currently getting a rate which is already fee-deducted, which results in us getting too low before/after fees amounts in https://github.com/shapeshift/web/pull/4217.
Since this consumes the THOR swap quote, this puts us in a very close place to reflect *akschual* swap quote amounts from THOR.
Coincidentally fixes a bunch of stuff that was just wrong in tests, fixes the signature of `getTradeQuote` naming `sellAmountCryptoBaseUnit` when it was actually a base unit, and LSP destructures to object args instead of arity insanity.
N/A
Fixed in 41043621a3996beb91113bad2a1b86738194ef8f
~~Now that we consume the …
=> fix(swapper): thorchain getTradeRate include fees and slippage

src/components/Trade/Components/TradeQuotes/TradeQuote.tsx, src/components/Trade/Components/TradeQuotes/TradeQuotes.tsx, src/components/Trade/TradeConfirm/ReceiveSummary.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useAvailableSwappers.tsx, src/components/Trade/hooks/useTradeQuoteService.tsx, src/state/zustand/swapperStore/actions.ts, src/state/zustand/swapperStore/amountSelectors.test.ts, src/state/zustand/swapperStore/amountSelectors.ts, src/state/zustand/swapperStore/testData.ts, src/state/zustand/swapperStore/types.ts, src/state/zustand/swapperStore/useSwapperStore.ts
This PR:
- Uses data from the quote responses to populate amounts shown to the user
- Updates the receive amount calculation to include the slippage amount, so the "you get" field accurately presents to the user what they can expect to receive
- Fixes "max" amount logic, whereby we now get an initial quote with some arbitrary value (instead of `0`) before computing the max send amount, giving us a more accurate send amount. Also backs off the total send amount by 1% as it was often failing due to how close it was to the limit
- Prevents the input of receive amounts (confirmed with product) - we'll add this logic when we bed down the current implementation and invest more time into getting it right, as it's non-trivial/risky
For reviewers:
- The main change here is addition and use of the …
=> feat: use receive amount data from quotes

src/lib/math.test.ts, src/lib/math.ts, src/state/zustand/swapperStore/amountSelectors.test.ts
Iterates on top of https://github.com/shapeshift/web/pull/4203, making sure we don't round down when unnecessary.
LLMgen'd description and tests
This pull request updates the fromBaseUnit() function to handle the displayDecimals parameter more safely and provides better control over the number of decimal places in the output. Previously, the function used the .decimalPlaces() method with the ROUND_DOWN mode, which could potentially cause loss of precision in certain cases.
The updated implementation of the fromBaseUnit() function checks if the displayDecimals parameter is provided and is a valid number. If it is, the function rounds down the result to the specified number of decimal places using the .decimalPlaces() method and then converts the resulting BigNumber to a string with exactly …
=> feat: don't round down in fromBaseUnit if displayDecimals are omitted

src/lib/utils.test.ts, src/state/slices/opportunitiesSlice/opportunitiesSlice.ts, src/state/slices/opportunitiesSlice/utils.ts
* fix - don't upsert opportunities against wrong account ids in `getOpportunityUserData`, i.e. don't upsert eth mainnet LP opportunities against cosmossdk/utxo accounts
* fix - add additional guards such that we can't do this in other places
* adds `opportunityIdToChainId` function which converts an `OpportunityId` to a `ChainId` w/ test coverage
n/a - noticed by @reallybeard
related to defi section
* ensure eligible opportunities still appear
* ensure all active opportunities are still appearing correctly (no need to do txs)
engineering only
before
after
=> fix: index opportunities against correct chains

packages/swapper/src/api.ts, packages/swapper/src/manager/testData.ts, packages/swapper/src/swappers/cow/getCowSwapMinMax/getCowSwapMinMax.test.ts, packages/swapper/src/swappers/cow/getCowSwapMinMax/getCowSwapMinMax.ts, packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts, packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts, packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts, packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.test.ts, packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts, packages/swapper/src/swappers/utils/test-data/setupSwapQuote.ts, packages/swapper/src/swappers/zrx/getZrxMinMax/getZrxMinMax.test.ts, packages/swapper/src/swappers/zrx/getZrxMinMax/getZrxMinMax.ts, packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.ts, src/lib/swapper/LifiSwapper/getTradeQuote/getTradeQuote.ts, src/state/zustand/swapperStore/testData.ts
Thanks to our friendly monorail service, this is now quick and easy.
Updates vernacular of min and max to include units.
N/A
Almost none.
Everything should work just as it did before.
☝️
☝️
N/A
=> refactor: re-name min max to show units

src/components/Trade/Trade.tsx, src/components/Trade/hooks/useDefaultAssets.tsx, src/hooks/useDeepOutputMemo/useDeepOutputMemo.ts
Changing network during trade confirmation results in the UI being zeroed out. 
This was caused by the network change to modify the wallet, which in turn triggered default asset logic to create duplicate objects with different memory addresses, forcing initialization of default assets to rerun --- which triggered trades to be zeroed out.
NA
Risk of breaking the default asset setting logic - please test accordingly.
- Create a trade and go to trade confirmation. 
- Change network on your wallet. 
- The numbers in the trade UI should  not get zeroed out, but rather the current trade values should persist unchanged.
- The trade should be executed with the correct values.
☝️
☝️
N/A
=> fix: trade confirmation UI zeroing out when changing network on wallet

src/components/Approval/Approval.tsx, src/lib/bignumber/bignumber.test.ts, src/lib/bignumber/bignumber.ts, src/lib/swapper/LifiSwapper/utils/cryptoLifiToUsdHuman/cryptoLifiToUsdHuman.ts, src/lib/swapper/LifiSwapper/utils/transformLifiFeeData/transformLifiFeeData.ts
This PR ensures `toHuman` returns a human amount (it was currently returning a precision amount) from a base unit, i.e an amount stripped to 6 dp (what we call a human amount), auto-rounded up/down by BigNumber.js' `.decimalPlaces()`.
While at it, renames it to `baseUnitToHuman` for clarity ~~Adds tests and JSDocs description and examples to make it clear this takes a base unit amount in as input.~~
N/A
Very small risk, consumption is isolated to:
- Li.Fi trade fee USD ~~though this is going to be mitigated in a follow-up by not using human amounts~~
- Li.Fi minimum USD fee ~~(not an actual issue since we're dealing with a `20` *integer*, not a float, so no loss of precision is going to happen)~~
Disregard my previous comments regarding the two above. We're now *akschually* displaying …
=> feat: toHuman should return a human amount

package.json, react-app-rewired/index.ts, yarn.lock
follow webpack build performance guide
https://webpack.js.org/guides/build-performance/
should get increment builds down from 10-12s to 5-7s
hot module reloading was disabled `:wat:?` and avoids browser reloads where possible
also bumps `react-scripts` to latest version with some tiny webpack niceties 
this also prevents a second lib compile by not watching src files in packages
we now get full hot module loading from packages through to the browser
n/a - we're big and fat
breaks local dev process - solution is to revert
try devving against this locally, see if it feels any faster
=> perf: webpack development perf

src/context/WalletProvider/NativeWallet/components/EnterPassword.tsx
A quick quality of life PR to update the native wallet password "Next" button to be disabled on invalid input.
N/A
Risk that the logic is incorrect and the user can't click "Next".
Enter an invalid input (a password not containing 8 characters) and see that the "Next button is disabled.
☝️
☝️
N/A
=> fix: disable next button on invalid password

src/plugins/foxPage/components/BondProtocolCta.tsx
https://app.bondprotocol.finance/#/market/1/70 has ended 
https://app.bondprotocol.finance/#/market/1/90 just went live
This change updates the URL in the "Buy FOX at a Discount" CTA to point to the latest market
=> chore: update bond protocol CTA to route to the latest market

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/state/slices/common-selectors.ts
we have a user in mixpanel with 39 billion dollars of eth
the only explanation is we were missing eth asset precision, so the balance is inflated by 10^18
n/a
low - safer than before
check my early return is in the right spot?
fiat balances should be the same as before
this trade makes no sense
=> fix: bail on calculating fiat balances without precision

src/lib/swapper/manager/SwapperManager.test.ts, src/lib/swapper/swappers/CowSwapper/CowSwapper.test.ts, src/lib/swapper/swappers/CowSwapper/CowSwapper.ts, src/lib/swapper/swappers/ZrxSwapper/ZrxSwapper.ts
This PR improved the performance of ZRX and Cow swappers to reduce app load time be ~1.24s, and reduces glitching during trade input.
NA
- Minor risk of asset filtering broken. This should would at worst display "invalid trade pair" or prevent assets being selected - would not break actual trades
- Automated tests updated. 
- Manually tested to check assets are being displayed as expected.
Performance before changes - 1240 milliseconds
Performance after changes - 74 milliseconds
- This is user facing
- Test that trade pairs are working as expected against production. Available assets and trade pairs should be identical to production.
=> perf: optimized asset filtering in zrx and cow swappers

src/state/slices/portfolioSlice/selectors.ts
closes https://github.com/shapeshift/web/issues/4328 implementing the best naive implementation - doesn't tackle `isDefi` yet which will be a bigger lift and needs to be discussed
Low/medium - see comment. If you have the *exact* same amount staked, to the base unit, this will produce regressions. Given this is only a temporary fix and you usually wouldn't have the same staked and wallet balance for a given asset across accounts/for an account, up to the smallest unit, that's probably a low enough risk until we tackle this holistically
- Go to an Idle asset you're staked in
- Ensure balances are matching the ones in Etherscan
- Ensure accounts page balance looks good
- Ensure there are no regressions across other opportunities in asset page i.e ETH/FOX LP, Osmosis LP
- ☝🏽 
- This diff
- …
=> feat: don't double count portfolio and staked amounts

src/state/slices/assetsSlice/assetsSlice.ts
this was taking ~800ms on app load to generate icons for LP pairs, that we never actually used
n/a - more perf things
LP pairs don't render correctly
check the earn section, see LP pairs appear as expected
no visual difference - LP pairs show both underlying asset icons side by side
=> perf: don't compute icons for dynamic LP pairs

packages/caip/src/adapters/thortrading/index.ts
Adds a THORChain pool mapping to `thorchainAssetId`, allowing trades into and out of RUNE to use the quotes endpoint. Currently they are falling back to the hacking pool size approximation to get quote data.
N/A, bug in production.
Small - changes quote source for RUNE quotes to a more accurate one.
With the network tab open, stage a THORChain trade to or from RUNE to the Trade confirm screen.
Observe that requests to the `lcd/thorchain/quote/swap` endpoint no longer have `undefined` as the `from_asset` or `to_asset`, and that the request now returns a quote instead of an error.
☝️
☝️
+ check that RUNE trades still work as expected.
N/A
=> fix: rune asset trades

src/state/slices/marketDataSlice/marketDataSlice.tsx, src/state/slices/opportunitiesSlice/opportunitiesSlice.ts, src/state/slices/portfolioSlice/portfolioSlice.ts
this has a dramatic improvement on performance
by batching actions together in reducers, redux only notifies subscribers (selectors) on a timeout
this means selectors don't recompute, and in turn, react renders a whole lot less
see screenshots - we only render once on market data changes instead of ~10
n/a - i'm on a performance arc
bigly - changes core state management reducers
ensure my logic changes in reducers doesn't cause regressions
a general smoke test of the app - switching wallets, checking market data, balances, and charts are correct.
before
after
=> perf: batch reducers

packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts, packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts, packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts, packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts, packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.ts, packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.test.ts, packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.ts, packages/chain-adapters/src/evm/utils.ts, src/components/Trade/hooks/useSwapper/utils.ts, src/features/defi/helpers/utils.ts, src/lib/swapper/api.ts, src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts, src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts, src/lib/swapper/swappers/ThorchainSwapper/utils/txFeeHelpers/evmTxFees/getEvmTxFees.ts, src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.test.ts, src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts, src/lib/swapper/swappers/ZrxSwapper/utils/constants.ts, src/lib/swapper/swappers/ZrxSwapper/zrxBuildTrade/zrxBuildTrade.test.ts, src/lib/swapper/swappers/ZrxSwapper/zrxBuildTrade/zrxBuildTrade.ts, src/state/zustand/swapperStore/testData.ts
- use `maxFeePerGas` as `gasPrice` for chains that support eip1559
- the above change allows us to remove zrx gas api and the average vs fast comparison logic
- add more constants for L1 gas limits to account for L1 fees on optimism (swaps/approvals)
- a little bit of type narrowing jank to access `l1GasPrice`
- remove `totalFee` which looks to be unused and irrelevant (correct me if I am wrong)
The L1 fee edge case is small and was also covered up by the arbitrary 50% gas limit buffer that existed before the eip1559 fee refactor.
https://discord.com/channels/554694662431178782/876953436908822568/1101532729859911765
Low/Med
- Test Zrx swap and approval flow on Optimism
- Sanity check defi interaction (fox-farming/univ2) and swaps (no gas limit/broadcast issues)
- The actual edge case will …
=> feat: optimism l1 fees

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/hooks/useDonationAmountBelowMinimum.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx
For low-value trades the affiliate fee we collect is lower than the gas fee requried to get it to our wallet.
For 0x it's included in the gas fee the user pays.
For THORChain we lose 0.02 RUNE worth of the affiliate fee to get it to our affilite wallet. Affiliate amounts lower than that are lost, so we shouldn't bother collecting them.
This PR hides the donation UX, and removes affiliate fees from THORSwaps where the affiliate fee collected would be at or below 0.02 RUNE.
N/A
Small.
Test that small THORTrades do not show the donation UI or include an affiliate fee in the memo.
Test that 0x donations are unaffected by this PR.
☝️
☝️
N/A
=> feat: ignore donation amounts below minimum

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/constants/treasury.ts, src/lib/swapper/swappers/OneInchSwapper/buildTrade/buildTrade.ts, src/lib/swapper/swappers/OneInchSwapper/utils/constants.ts, src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts, src/lib/swapper/swappers/ZrxSwapper/utils/constants.ts, src/lib/swapper/swappers/ZrxSwapper/utils/helpers/helpers.test.ts, src/lib/swapper/swappers/ZrxSwapper/utils/helpers/helpers.ts, src/lib/swapper/swappers/ZrxSwapper/zrxBuildTrade/zrxBuildTrade.ts, src/state/zustand/swapperStore/amountSelectors.ts, src/state/zustand/swapperStore/selectors.ts, src/state/zustand/swapperStore/utils.ts
Adds donations to 0x swapper.
~First TX: https://bscscan.com/tx/0x54b77347e57622fdea28e62c1251446975306a64abd2804288fdd0d5ed39ab7d 🥳~
TX to new BSC Safe using dynamic treasury addresses: https://bscscan.com/tx/0xdacc529214b48a2b73fbf4a24b734437a10ca1461aada8b65fb26edaa249514b
TODO before opening from draft: add affiliate addresses for swaps into assets not supported by the DAO treasury address.
@willyogo to confirm these addresses.
N/A
Small, though 0x trades should be tested/executed.
Perform a 0x swap both with and without the donation checkbox checked.
When checked, we should collect a 30bps fee from the receive amount, which we recive in the recive asset.
☝️
☝️
N/A
=> feat: 0x donations

src/context/AppProvider/AppContext.tsx, src/state/slices/txHistorySlice/txHistorySlice.ts
This PR:
- Doesn't await for FOXy rebase history in `getFoxyRebaseHistoryByAccountId`, making it resolve immediately
- Doesn't `forceRefetch` getFoxyRebaseHistoryByAccountId - currently being tested to ensure this doesn't break anything. The reason for that is there will currently be many query thunks being dispatched, always force refetching FOXy rebase history, making a ton of requests and the DeFi section / the app overall slower.
- Removes the assumption of "FOXy contract addresses". This is wrong and because of how the types were originally written in `investor-foxy`. There's only one contract - not only don't we need to `await Promise.all()`, we don't need to map over contract addresses at all since there's only one
N/A
FOXy data may be wrong/missing if we don't have FOXy as a …
=> feat: don't await foxy rebase history

src/lib/swapper/api.ts, src/lib/swapper/swappers/LifiSwapper/utils/getIntermediaryTransactionOutputs/getIntermediaryTransactionOutputs.ts, src/lib/swapper/swappers/LifiSwapper/utils/lifiChainIdtoChainId/lifiChainIdToChainId.ts
Fixes app crash when lifi swaps contain unsupported assets in the intermediary asset list.
NA
Little to no risk.
Check that reported pair works without crashing app.
See above
See above
=> fix: handle unsupported intermediary assets in lifi swapper

src/hooks/useHasAppUpdated/useHasAppUpdated.test.ts, src/hooks/useHasAppUpdated/useHasAppUpdated.ts
for users with large tx history, this fails to make a network request then erroneously marks the app as updated
this PR also simplifies the hook to use the `metadata.json` file including the commit hash rather than checking against the `manifest.json` of the built files and `.env.json` of environment variables
even an environment variable change will change the `metadata.json` file as the commit hash will change
n/a
low but annoying if i get this wrong - isolated to the app update notification
* deploy to your own ephemeral environment
* pair willywonka.eth via frame wallet
* see that we don't get errenous app update notifications after 1 min
* push an empty commit to your ephemeral branch such that the commit hash changes
* see that you get an app updated notification after 1 min of …
=> chore: simplify useHasAppUpdated hook

src/context/AppProvider/AppContext.tsx, src/context/FoxEthProvider/FoxEthProvider.tsx, src/context/TransactionsProvider/TransactionsProvider.tsx, src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimStatus.tsx, src/state/slices/opportunitiesSlice/opportunitiesSlice.ts, src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts, src/state/slices/opportunitiesSlice/resolvers/ethFoxStaking/index.ts, src/state/slices/opportunitiesSlice/resolvers/foxy/index.ts, src/state/slices/opportunitiesSlice/resolvers/idle/index.ts, src/state/slices/opportunitiesSlice/resolvers/index.ts, src/state/slices/opportunitiesSlice/resolvers/osmosis/index.ts, src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts, src/state/slices/opportunitiesSlice/resolvers/types.ts, src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts, src/state/slices/opportunitiesSlice/resolvers/yearn/index.ts, src/state/slices/opportunitiesSlice/thunks.ts, src/state/slices/opportunitiesSlice/types.ts
This PR:
- Makes the opportunity thunks accept a `ChainId` and call queries for the matching ChainIds
- Removes the current `ChainId` checks in resolvers, that were effectively achieving the same
- removes the `opportunityType` property in resolver inputs, which was effectively a duplicate of `defiType`
- While at it, stop fetching IDs and metadata in `<TransactionProvider />` for unknown transactions, in profit of userdata only
N/A
- This may bring back a bit of console spew, as we now have a general notion of opportunities by ChainId, but no way yet to know whether or not these are for an `opportunity` or `opportunities` resolver, resulting in no-ops if you have debug log level enabled
- Clear your persisted redux store
- Ensure opportunities are still loading and working (try a few …
=> feat: opportunity thunks by ChainId

src/components/AssetSearch/AssetSearch.tsx, src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx, src/components/Equity/EquityLpRow.tsx, src/components/Modals/FiatRamps/views/FiatForm.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx, src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx, src/features/defi/providers/idle/components/IdleManager/Claim/components/Confirm.tsx, src/features/defi/providers/idle/components/IdleManager/Claim/components/Status.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Confirm.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Status.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Confirm.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Status.tsx, src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx, src/features/defi/providers/univ2/components/UniV2Manager/Withdraw/components/Withdraw.tsx, src/hooks/useTxDetails/useTxDetails.ts, src/pages/TransactionHistory/DownloadButton.tsx, src/pages/TransactionHistory/TransactionHistory.tsx, src/pages/TransactionHistory/hooks/useSearch.tsx, src/state/apis/fiatRamps/selectors.ts, src/state/slices/assetsSlice/selectors.ts, src/state/slices/common-selectors.ts, src/state/slices/marketDataSlice/selectors.ts, src/state/slices/opportunitiesSlice/selectors/combined.ts, src/state/slices/opportunitiesSlice/selectors/lpSelectors.ts, src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts, src/state/slices/portfolioSlice/selectors.ts
This PR improves both performance and heuristics after https://github.com/shapeshift/web/pull/4428 got in, sorting market data IDs (and `byId` entries) by market cap descending:
- renames `selectMarketDataSortedByMarketCap` to `selectSelectedCurrencyMarketDataSortedByMarketCap`. The name doesn't make sense anymore: the market data is now already sorted by market cap. The only thing this is really doing is massaging the market data to the selected user currency
- simply returns the output of `selectCryptoMarketData` in case the selected currency is the default USD one
- doesn't iterate over the `Object.entries()` of `cryptoMarketData`, but over the `marketDataAssetIds` instead, which are sorted so we can simply do a more efficient reduce over the IDs
- switches the `.map().reduce()` call …
=> feat: market data refactor to handle sorted market data IDs

src/components/StakingVaults/EarnOpportunities.tsx, src/state/slices/portfolioSlice/selectors.ts
This PR:
- Memoizes `allRows` in [StakingVaults/EarnOpportunities.tsx](https://github.com/shapeshift/web/pull/4435/files#diff-0b963dadaf0975d79998a2e9abd8a23d3317e272fdb8f7bc3a4622e29d8ee69c) - I believe this shouldn't be a view-layer concern still, but lowest lift to fix the spotted regression in https://github.com/shapeshift/web/pull/4397#issuecomment-1535612679
- Opt-chain accessooors of `underlyingBalances[assetId]` in `selectAssetEquityItemsByFilter`. Same issue as spotted previously, this should not happen, but it looks like it may during loading states
N/A
None, more safety
- Go to assets
- Open an asset
- Asset properly opens, and opportunities are still displayed with no regressions after opportunities are loaded / reconciliated from persisted store (this should work with and …
=> feat: more selectAssetEquityItemsByFilter selectors safety

src/components/AssetHeader/AssetChart.tsx, src/hooks/useTimeframeChange/useTimeframeChange.ts, src/pages/Dashboard/Portfolio.tsx, src/plugins/foxPage/components/FoxChart.tsx, src/state/slices/preferencesSlice/preferencesSlice.ts, src/state/slices/preferencesSlice/selectors.ts, src/test/mocks/store.ts
The goal is to preserve the last timeframe a user has chosen in a chart to all the other current charts in the apps, and restore it also if they close the app, instead of resetting it to the default app value each time.
The rationale for applying it to all the charts: in my opinion users will generally check multiple charts with the same timeframe, be it their portfolio or different assets, having to reselect the timeframe each time they load a new chart/asset is tedious, this solves it.
- Adds a hidden keypair preference to remember the last timeframe used by the current user on charts.
- Uses this keypair and updates it for all the charts. By default it uses `DEFAULT_HISTORY_TIMEFRAME` if it is unset.
None.
Change the timeframe of a chart (e.g. on "My Wallet") and go to an "Asset" …
=> feat: remember charts timeframe

src/constants/Config.ts
Changes default time frame on dashboard from MONTH to DAY
Changes default time frame on dashboard from MONTH to DAY
Changes default time frame on dashboard from MONTH to DAY
Please check the default charts are defaulting to 1D, instead of 1M.
Please check the default charts are defaulting to 1D, instead of 1M.
Please check the default charts are defaulting to 1D, instead of 1M.
OLD:
NEW:
=> chore: change default time frame from MONTH to DAY

src/components/Trade/TradeConfirm/TradeConfirm.tsx
Fixes a bug where the donation toggle would become re-enabled after a trade TX completes.
Closes https://github.com/shapeshift/web/issues/4438
Small.
When a trade TX completes, the donation toggle should still be disabled.
☝️
☝️
=> fix: disable donation toggle on trade completion

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/state/zustand/swapperStore/amountSelectors.ts
Fixes a bug where the donation toggle would disapear on toggle for THORSwaps, as the expected donation amount fell below the minimum.
To fix this, we want to continue showing the donation toggle if the donation amount, assumming the default swapper bps is used, is above the minimum, regardless of the "active" donation amount. 
N/A
Small.
Toggle the donation amount for a THORSwap trade. The donation toggle should stay visible.
☝️
☝️
N/A
=> fix: always show donation if default donations > min

src/components/Trade/Components/TradeQuotes/TradeQuote.tsx
Hide the "Insufficient sell amount" label when no amount has been entered yet.
N/A
Small.
When no amount has been entered in the trade widget we should not show the "Insufficient sell amount" label.
☝️
☝️
As-is:
This PR:
=> feat: hide insufficient amount when no amount entered

src/components/Trade/Components/TradeQuotes/TradeQuote.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/state/zustand/swapperStore/amountSelectors.ts
feat: hide insufficient amount when no amount entered (#4447)
fix: always show donation if default donations > min (#4446)
fix: disable donation toggle on trade completion (#4445)
=> chore: release v1.309.0

src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts, src/lib/swapper/swappers/ThorchainSwapper/utils/getTradeRate/getTradeRate.ts
The THORSwap quote endpoints appears to no longer accept the `bitcoincash:` prefix on addresses, as quote requests containing it are now rejected.
This PR updates the logic inside THORSwapper (without touching any address logic outside of it, as this is a THOR-specific thing) to strip the prefix from the address when getting quotes and building trades for THORSwap trades.
Closes https://github.com/shapeshift/web/issues/4382
Higher than it seems, as this touches receive addresses for trades - we want to be super careful that this logic makes sense. Scrutinize the diff accordingly.
Do a THORSwap trade into BCH and confirm that the address in the request and response payloads look correct.
Execute the transaction and confirm the funds are received as expected in the BCH account.
TX I did to …
=> fix: receive address for BCH

src/components/Modals/Send/Form.tsx, src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx, src/components/Modals/Send/hooks/useSendFees/useSendFees.tsx, src/components/Modals/Send/views/Details.tsx
This PR:
- Adds support for amount parsing in the good ol' send button when clicking the QR scan icon
- Fixes the reactivity on amount/accountId over the send domain so that gas fees are now properly reacty and present on the last step of sends with amounts
- While at it, fixes the missing re-validation on `AccountId` change. Currently on prod, while account 0 has enough balance for gas/crypto but the newly selected account doesn't, no validation happens meaning that it will look as the newly selected account passed validation, while in reality no validation happened at all.
N/A
- Test both QRCode and send buttons end-to-end : all the way to Tx popup in MetaMask (without confirmation), and to an actual broadcast on native for cheaper UTXO/IBC chains
- Test both with an URL containing an …
=> feat: parse amounts on QR scan with regular send button

src/components/StakingVaults/WalletProviderTable.tsx
Smallish derp fix - since the skeletons are at the very end of opportunities, we've never noticed that they're always present, even after loading of opportunities is finished.
N/A
None
- Go to the DeFi section and scroll to the very end (or press G if you're a 10x vimium user)
- Ensure the skeletons disappear once all opportunities are loaded
- ☝🏽 
- ☝🏽
=> fix: show defi by provider skeletons only on actual load

src/assets/translations/en/main.json, src/components/Trade/Components/TradeQuotes/TradeQuotes.tsx, src/components/Trade/TradeConfirm/ReceiveSummary.tsx, src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/components/Trade/TradeInput.tsx, src/lib/swapper/api.ts, src/lib/swapper/swappers/LifiSwapper/utils/getIntermediaryTransactionOutputs/getIntermediaryTransactionOutputs.test.ts, src/lib/swapper/swappers/LifiSwapper/utils/getIntermediaryTransactionOutputs/getIntermediaryTransactionOutputs.ts, src/state/zustand/swapperStore/amountSelectors.ts
Fixes dead click when attempting trades with insufficient balance for protocol fees on receiving chain.
closes #4350
low risk of trades breaking.
- check trades are unaffected
- check fee amounts are still correct
- check general warnings about invalid trade states are still correct
- check 2nd protocol fee is correct for `any -> matic on polygon` trades
- check insufficient balance warning is correct for protocol fees on receiving chain
Note that this is as pragmatic a solution as I could push without boiling the ocean. When we support multi-hop we'll need to remove the concept of `buyAssetTradeFeeUsd` and `sellAssetTradeFeeUsd` and instead return an array of fees since there will be intermediary fees in other tokens. This will be a fairly heavy lift in thor swapper but is pretty …
=> fix: handle insufficient balance on receiving chain (for protocol fees)

src/components/Trade/TradeInput.tsx
Temporary patch to allow thor trades to go through. Currently users are unable to make trades with thor swapper if they dont have funcs on the receiving chain. The root cause will be solved in a follow-up PR.
NA
No change to swapper logic, so very low risk.
Check that it's possible to make trades with thor swapper without balance on receiving chain.
See above
See above
current issue
with fix
=> fix: patch insufficient (COIN) on (Network) for fees THORChain

src/hooks/useErrorToast/useErrorToast.ts
Prevents render loops due to the creation of an uncached function in the react render context.
NA
No risk, just wraps a function in useCallback
Check that error toast still works
See above
See above
=> fix: prevent render loops due to use of uncached useErrorHandler hook

src/assets/translations/en/main.json, src/components/Modals/Send/AddressInput/AddressInput.tsx, src/components/Modals/Send/views/Address.tsx, src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/useSwapper.tsx, src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts, src/lib/address/address.ts, src/state/zustand/swapperStore/selectors.ts
- Adds the ability to manually enter a receive address when trading into an asset that is not supported by the connected wallet (e.g. ETH into DOGE on MetaMask)
- Validates that the receive asset is valid on the receiving chain
- Supports yatt addresses when the receiving chain is ETH (not a case we currently require, but it's there nonetheless)
- Supports ENS/unstoppable domain resolution
First successful TX with manual receive address: https://viewblock.io/thorchain/tx/1C9A199669FCD8D21F2EE20EFA91A6A20D5183A84749A96795E8F54BCC2A6C57
Closes https://github.com/shapeshift/web/issues/2168
🌶️ Very high. 
It's a simple PR in many ways, but getting this wrong could mean loss of funds for the user if the funds are send to the wrong/invalid address.
- Test sending into assets not supported by …
=> feat: manual receive address

src/components/Trade/Components/RateGasRow.tsx, src/components/Trade/TradeInput.tsx
Fixes network fee appearing as several billion dollars when the sell asset is unsupported by the connected wallet. 
The fix was to simply NOT render any available swappers or network fees when the sell asset was unsupported since it was never possible to use them anyway.
closes #4499 
virtually no risk.
- check that unsupported sell assets do not display billion dollar network fees
- check that supported pairs display the correct network fee
This was caused by the `TradeInput` UI using the previous quote to display network fees with the precision of the selected network fee. In the examples shown, gas fee with ETH precision (18) was rendered using BCH precision (8).
See above
before fix
after fix
=> fix: dont render network fees for previous quote when current pair is unsupported

src/features/defi/providers/cosmos/components/CosmosManager/Overview/WithdrawCard.tsx, src/state/slices/opportunitiesSlice/opportunitiesSlice.ts, src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts, src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/utils.ts, src/state/slices/opportunitiesSlice/resolvers/types.ts
Tackles https://discord.com/channels/554694662431178782/1108429698494640188/1108429700386263071 - we were never invalidating old opportunities. This PR:
- adds a new `invalidateUserStakingOpportunity` action to `opportunities`, to handle one of the two hard things in software engineering
- adds paranoia `dayjs().isBefore()` checks in `<WithdrawCard />` and in Cosmos SDK resolver utils to ensure the current date is before the completion time i.e the undelegation is *actually* valid
N/A
Note this is untested as I couldn't reproduce this bug, would have to wait 21 days to do so.
User data resolution for Cosmos SDK opportunities might be borked, clear your persisted store and confirm you can still see your user data
- If you can repro this in prod, ensure you don't see your stale undelegation …
=> fix: invalidate stale cosmos SDK userStakingData

src/components/Trade/hooks/useSwapper/getTradeQuoteArgs.tsx, src/components/Trade/hooks/useTradeQuoteService.tsx, src/lib/swapper/api.ts, src/lib/swapper/swappers/CowSwapper/cowBuildTrade/cowBuildTrade.ts, src/lib/swapper/swappers/LifiSwapper/buildTrade/buildTrade.ts, src/lib/swapper/swappers/OneInchSwapper/buildTrade/buildTrade.ts, src/lib/swapper/swappers/OsmosisSwapper/OsmosisSwapper.ts, src/lib/swapper/swappers/ThorchainSwapper/buildThorTrade/buildThorTrade.ts, src/lib/swapper/swappers/ThorchainSwapper/utils/getLimit/getLimit.ts, src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts, src/lib/swapper/swappers/ThorchainSwapper/utils/getTradeRate/getTradeRate.ts, src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/makeSwapMemo.ts, src/lib/swapper/swappers/ThorchainSwapper/utxo/utils/getThorTxData.ts, src/lib/swapper/swappers/ZrxSwapper/zrxBuildTrade/zrxBuildTrade.ts
This PR fixes the THOR quotes that are currently rugged on missing manual receive addresses, see
https://discord.com/channels/554694662431178782/1109095039239462933/1110104478390165664
The reason why this was borked was because of our `if (receiveAddress)` check in `useTradeQuoteService`, never fetching a quote in case we don't have a receive address.
N/A
Theoretically medium/high, in reality, this brings more runtime safety in, throwing in case of undefined receive address whenever applicable.
- With MM connected, ensure you can get quotes to UTXOs without a receive address entered
- Ensure send max is working without a receive address entered
- Ensure the swapper is in an error-ed state, pending receive address input
- Ensure inputting a receive address allows to continue with the flow …
=> fix: quotes on missing receive address

src/components/Trade/TradeInput.tsx
Fix issue where "preview trade" button is permanently disabled (until reload) after manual receive address is rendered.
closes #4540
very low risk
See linked issue for testing
The fix is to force `react-hook-form` to revalidate after hiding manual receive address.
See #4540
=> fix: disabled trade button after manual receive address

src/components/Trade/TradeInput.tsx, src/components/Trade/hooks/useSwapper/swapperManager.ts, src/components/Trade/hooks/useSwapper/useSwapper.tsx
Fixes semmingly random issue where ETH mainnet was displaying as the only buyable chain in trade input.
closes #4547
Very low risk of app loading state causing asset selection being stuck disabled.
1. open app on trade page
2. while app is loading, try to open the buy asset selection
3. app will (possibly) render only ETH as the old available chain - this PR should fix that
This includes a few fixes - comments below
See able
Before fix:
All available chains rendered after fix:
=> fix: race condition rendering/loading sellable assets

src/components/Trade/TradeInput.tsx
Fixes UI assuming the protocol fee is always the buy asset. This allows the UI to display the correct warning.
There is a limitation of our UI where we can only display 1 error message at a time, so this fix will show the first known asset with insufficient balance. 
Low risk of this still being wrong
- Test that trades with protocol fees payable with insufficient balance are displayed in UI as a warning (remember that only 1 warning can be displayed at a time)
- Test that trades with sufficient balance for fees go through
See above
See above
prod:
with fix:
quote from lifi with actual fee highlighted, proving fix matches the quote data:
=> fix: incorrect asset reported for protocol fee insufficient balance warning

src/components/Trade/Components/TradeQuotes/TradeQuotes.tsx, src/constants/constants.ts, src/lib/swapper/api.ts, src/lib/swapper/swappers/CowSwapper/CowSwapper.test.ts, src/lib/swapper/swappers/CowSwapper/cowBuildTrade/cowBuildTrade.test.ts, src/lib/swapper/swappers/CowSwapper/cowBuildTrade/cowBuildTrade.ts, src/lib/swapper/swappers/CowSwapper/cowExecuteTrade/cowExecuteTrade.test.ts, src/lib/swapper/swappers/CowSwapper/cowExecuteTrade/cowExecuteTrade.ts, src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts, src/lib/swapper/swappers/CowSwapper/types.ts, src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.test.ts, src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.ts, src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts, src/lib/swapper/swappers/utils/test-data/setupSwapQuote.ts, src/state/zustand/swapperStore/selectors.ts, src/state/zustand/swapperStore/utils.test.ts, src/state/zustand/swapperStore/utils.ts
Fixes the value of `buyAmount`, which represents the minimum amount that we will accept, when executing a CoW Swap trade.
Previously, we were using the amount amount including fees as the minimum receive amount, which was always going to fail.
Now, we use the `buyAmount` return value of the CoW to estimate how much we can actually expect to get, and then deduct appropriate slippage (0.5%).
This PR also links the trade to the trade quote by passing through the `id`, which conforms with CoW Swap best practice, and gives us additional metadata on the CoW Swap explorer.
Closes https://github.com/shapeshift/web/issues/4497
Medium risk to CoW Swap trades, though the logic changes in this PR are contained to the CoW Swapper.
Perform a CoW Swap trade and:
1. Ensure that the amount that we show as …
=> fix: cowswap minimum amounts

src/plugins/walletConnectToDapps/components/header/DappAvatar.tsx, src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx, src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummaryV2.tsx
dApp icons can be an empty array for some dApps (e.g. https://thedapplist.com/).
This PR handles this, and displays a placeholder imaage instead of having our UI break.
N/A, raised by @firebomb1.
Very small.
Go to https://thedapplist.com/ and connect to ShapeShift via wallet connect.
We should now show our placeholder image instead of having our DOM break.
☝️
☝️
Before:
After:
=> fix: handle no image in DappAvatar

src/constants/constants.ts
Changes lifi default slippage to 0.5% (up from 0.2%) to reduce the likelihood of slow trade execution. 0.5% is the default specified in the the lifi API documentation.
See this thread for context:
https://discord.com/channels/554694662431178782/1111090473344442489/1111090475244470322
no risk
NA
See above
See above
=> chore: change lifi default slippage to 0.5%

src/components/TransactionHistoryRows/hooks.tsx
Fixes what I'm pretty sure is a copy pasta bug by using the correct `assetId` in the `findPriceHistoryByAssetId` dispatch call.
N/A, I just came across it in the codebase.
Small.
Asset price history in transaction rows should be no worse, and ideally slithgly better - we should now fetch sell asset data of a TX when it is missing.
☝️
☝️
N/A
=> fix: get sell asset price history when not defined

package.json, yarn.lock
Bump hdwallet-native to fix signing non-hex encoded payloaad strings.
N/A - related to mercle.
Small.
No ops testing needed, already tested on hdwallet side with engineering.
☝️
☝️
N/A
=> fix: bump hd-wallet to 1.50.1

src/components/Trade/TradeConfirm/TradeConfirm.tsx, src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
Fixes max trades when using lifi swapper. The lifi swapper had logic bypassing our max sell logic where it would change the sell amount to the sell asset balance rather than using the adjusted value from the existing logic.
Also includes a fix to "dead click" where errors are not displayed on trade confirmation error. Screenshot of it working below.
NA
Low risk
keep in mind optimism trades on lifi still broken see #4580
- Test normal lifi trades work
- Test max lifi trade works
See above
See above
Toast correctly displaying on trade confirmation error:
=> fix: max trades for lifi swapper sending whole balance instead of minus fees

src/lib/swapper/swappers/CowSwapper/getCowSwapMinMax/getCowSwapMinMax.test.ts, src/lib/swapper/swappers/CowSwapper/getCowSwapMinMax/getCowSwapMinMax.ts, src/lib/swapper/swappers/CowSwapper/utils/constants.ts
The required trade minimum for ETH on CowSwap is too high for Gnosis chain, as the cost of transactions is significantly lower. This PR keeps the minimum tx value for ETH as is (20$), while setting the minimum tx for Gnosis to 0.5$. 
We might not be handling CoW minimums correctly anymore, or may not be handling it correctly per chain
- Ethereum CoW swaps still have a 20$ minimum, both with the `CowswapGnosis` flag on and off
- Gnosis CoW swaps (assuming the flag is on) have a 0.01$ minimum
- ☝🏽 
- ☝🏽 
- Minimum not met
- Minimum met
- Minimum not met
- Minimum met
=> chore: use 0.01$ min. for CoW Gnosis trades

src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
In the opportunities slice, we index staking opportunities by `StakingId`. This value is often, though not always the same shape as an `AssetId`.
When it isn't the same shape, the app currently crashes, as we have a number of selectors that attempt to use the `id` as if it is an `AssetId`.
This PR updates those selectors to use the opportunity's `assetId` value, which actually _is_ an `AssetId`, and makes my test account load again.
Examples of keys that are not `AssetId`s: `0x24fd7fb95dc742e23dc3829d3e656feeb5f67fa0#1170050076`, `0x5274891bec421b39d23760c04a6755ecb444797c#240877749` etc.
N/A - current production issue.
Small.
Loading an account with a non-assetId stakingId, e.g. `eip155:1:0x32dbc9cf9e8fbcebe1e0a2ecf05ed86ca3096cb6`, should no longer crash.
This should be testable via …
=> fix: staking opportunities app rug

react-app-rewired/headers/csps/alchemy.ts, src/state/apis/nft/nftApi.ts, src/state/apis/nft/parsers/alchemy.ts, src/state/apis/nft/types.ts
https://github.com/shapeshift/web/pull/4639 (as https://github.com/shapeshift/web/pull/4646 in this stack) introduced the concept of a NFT refresh button and fetching the media from unchained, which we're able to do when we have an IPNS gateway URL, which unchained introspects to get the latest updated media.
This works when unchained is happy, but in case it isn't, what we thought was "graceful error-handling" i.e getting medias from alchemy's `medias` turns out to be *too* graceful: alchemy `medias` is rugged and often stale, and more often than not never updates and has the original media.
This means that when starting from fresh NFT media (which was gotten from unchained) and clicking the refresh button, it will revert to the original state of the NFT in case Alchemy is down.
This PR …
=> feat: fallback of the fallback for IPNS gateway URLs

src/lib/swapper/swappers/OneInchSwapper/getTradeQuote/getTradeQuote.ts
Patches one inch swapper to use non-eip-1551 gas estimation without l1 fees on optimism. This is because the initial implementation was incorrect and more work is required to provide this.
With this in mind, for 1inch trades, network fee estimation will be incorrect and gas estimation will be generally inaccurate until the follow-up fix is live.
NA
Low risk, no change to swapper logic aside from network fee calculation
Check 1inch swapper network fees are somewhat accurate keeping in mind description above.
See above.
See above.
=> fix: patch for 0 oneinch swapper network fee

src/lib/swapper/swappers/LifiSwapper/buildTrade/buildTrade.ts
Fixes lifi trades not executing due to missing metadata required to execute them.
https://discord.com/channels/554694662431178782/1115468766722142258/1115490314384310283
Very low risk to lifi trade execution only.
Test lifi trades to ensure they execute as expected.
See above.
This should introduce no change from production, it fixes a release candidate only.
successful trade execution
https://etherscan.io/tx/0x26f0104c27f7c31939c8025ed42859ef41b35ca0efdb2bf5d592f68f95e5583b
=> fix: lifi trades missing metadata to execute

react-app-rewired/headers/csps/plugins/walletConnectToDapps.ts
Gnosis Safe requires a websocket CSP whitelist to connect.
This PR adds that whitelist.
N/A - raised by @firebomb1.
Minimal.
Go to https://app.safe.global/ and connect via Wallet Connect, and ensure the pair completes.
As an added bonus, it looks like switch chain works flawlessly, too.
☝️
☝️
=> chore: add gnosis safe to CSP

src/components/EarnDashboard/components/PositionDetails/StakingPositionsByProvider.tsx, src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx, src/components/EarnDashboard/components/ProviderDetails/StakingOpportunitiesByAsset.tsx, src/components/EarnDashboard/components/ProviderDetails/WalletStakingByAsset.tsx, src/components/Layout/Header/GlobalSearch/StakingResults/StakingResult.tsx, src/components/StakingVaults/PositionTable.tsx, src/components/StakingVaults/StakingTable.tsx, src/state/apis/zapper/zapperApi.ts, src/state/slices/opportunitiesSlice/selectors/combined.ts, src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
And fixes the top-level asset for borrowed/supplied opportunities while at it.
Note: The negative APY for providers containing debt opportunities issue is known and will be tackled in a [follow-up](https://github.com/shapeshift/web/pull/4690).
N/A
Low to none, though the heuristics for "has active balance" have been changed from "greater than 0" to "not zero" to handle negative amounts. There shouldn't be any user-facing changes, but if we ever had a wrong negative amount for some opportunity, somewhere, this would unveil it.
- Ensure negative amounts are handled in the nav earn tab, and matching fiat amounts look sane
- Ensure negative amounts rows are shown in the earn dashboard tab
- None
=> feat: read-only opportunities negative amounts handling

src/components/Trade/hooks/useAvailableSwappers.tsx, src/hooks/useDebounce/useDebounce.tsx
Add 500ms debounce to trade quotes
N/A - should improve rate limiting in porduction.
Small, though touches trade quotes and values so we want to double check the logic
of what's happening.
Mash the input of a trade and you should only see one set of network requests (at most on per 500ms of mashing, at least).
The network  request should contain the `sellAmountBeforeFeesCryptoBaseUnit` value corresponding to the latest input value.
Sense check this limiting the update frequency of RTK query input args is a sane w
ay to implement rate limiting.
☝️
☝️
N/A
=> perf: add 500ms debounce to trade quotes

src/components/Modals/Settings/CurrencyFormat.tsx, src/components/Modals/Settings/FiatCurrencies.tsx, src/context/WalletProvider/KeepKey/components/Connect.tsx, src/context/WalletProvider/KeepKey/components/FactoryState.tsx, src/context/WalletProvider/KeepKey/components/Label.tsx, src/context/WalletProvider/KeepKey/components/Passphrase.tsx, src/context/WalletProvider/KeepKey/components/Pin.tsx, src/context/WalletProvider/KeepKey/components/RecoverySentenceEntry.tsx, src/context/WalletProvider/KeepKey/components/RecoverySentenceInvalid.tsx, src/context/WalletProvider/MobileWallet/components/MobileCreate.tsx, src/context/WalletProvider/MobileWallet/components/MobileStart.tsx, src/context/WalletProvider/NativeWallet/components/LegacyMigration/LegacyLogin.tsx, src/context/WalletProvider/NativeWallet/components/NativeCreate.tsx, src/context/WalletProvider/NativeWallet/components/NativeStart.tsx, src/context/WalletProvider/components/ConnectModal.tsx, src/context/WalletProvider/components/RedirectModal.tsx, src/pages/Accounts/AddAccountModal.tsx, src/plugins/walletConnectToDapps/v1/components/modals/callRequest/methods/SendTransactionConfirmation.tsx, src/plugins/walletConnectToDapps/v1/components/modals/callRequest/methods/SignTransactionConfirmation.tsx, src/plugins/walletConnectToDapps/v2/components/modals/CosmosSignMessageConfirmation.tsx, src/plugins/walletConnectToDapps/v2/components/modals/EIP155TransactionConfirmation.tsx
We recently updated Chakra to a version that dropped legacy support for the `disabled` prop on Buttons, which should now be `isDisabled`.
N/A - unblocks current release.
Small.
Ensure buttons are disabled when they are meant to be.
Side not, sanity check UI to ensure everything still looks and works the same in case there are any other breaking changes that we missed.
N/A
=> fix: replace deprecated disabled prop

src/state/apis/zapper/zapperApi.ts, src/state/slices/opportunitiesSlice/types.ts
Does what it says on the box - if an opportunity `appName` (i.e what we use as both an enum key and value as a dynamic `DefiProvider` of sorts / primary key for metadata by provider) is one of our *static* `DefiProvider` values, we should bail, since we have an akschual full-fledged opportunity that's going to be fetched a few seconds after.
N/A
None
- Ensure UNi-V2 and Idle are still fetched, parsed and upserted by our regular abstraction, not the read-only one. This can be verified by ensuring there's no external link icon on the opportunity row.
Note, you will have to clear your persisted store to test this. Didn't author a migration since this isn't live yet and we'd only see this in develop builds.
=> feat: handle opportunities dupes between read-only and current opportunities

src/state/slices/opportunitiesSlice/selectors/combined.ts
This PR zero's out the virtual fiat amount for negative amounts - if an opportunity has a negative (debt) fiat amount, we shouldn't take its fiat amount into account and sum it (effectively making the blended APY lower) but simply zero it out. That is because debt opportunities don't earn yield, so their APY is irrelevant and shouldn't be accounted for in the blended total.
N/A
None
- Blended APYs aren't accounting for negative fiat amounts i.e there are no negative blended APY totals. Test with frame injected willy's wallet and ensure Agave/Compound blended APYs are happy
See https://github.com/shapeshift/web/pull/4679 for current
=> fix: don't subtract APY from negative opportunities in blended APY

src/state/apis/zapper/zapperApi.ts, src/state/slices/opportunitiesSlice/types.ts
This PR improves our heuristics for "nested assets" in read-only opportunities:
- doesn't assume underlying assets are always two - they can be one, or more than two, this makes it programmatic
- upserts reward assets if non-existing. We do so for top-level/underlying asset, but in case the rewards assets aren't part of these two and we don't have them in store, we will miss them in the assets slice
Note that this doesn't produce any visible change for now. The reason for this is this guy here:
https://github.com/shapeshift/web/blob/da01ef7988613ff80e36b9403cab020db38d920a/src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx#L90-L98
We assume an opportunity row can have rewards nested asset rows, *or* underlying asset rows, not the two together. This was perfectly …
=> feat: read-only opportunities improve nested assets p1

src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx, src/components/MultiHopTrade/index.ts, src/components/MultiHopTrade/types.ts
Adds multi-hop component state logic.
Note, not wired up to any store, it currently just reflects the value hardcoded into the `tradeExecutionStatus` constatnt.
N/A
Small - all code changes behind a feature flag.
N/A
Woody: update `tradeExecutionStatus` to different states and confirm that the visual state matches the expected.
N/A
N/A
=> feat: multi-hop component state

src/state/apis/nft/nftApi.ts, src/state/migrations/index.ts
This PR makes `getNftUserTokens` more graceful in the way it checks for existing items in the `results.reduce<Record<AssetId, NftItemWithCollection>>()` acc.
We are currently doing triple-equality check on the acc's key (an `Assetid`):
https://github.com/shapeshift/web/blob/08611f1914603d637cf80dd87d5f1eaabdf41cf3/src/state/apis/nft/nftApi.ts#L141
This is fine if the data we get upstream is correct, but we can't assume all services will return us the correct standard (which in the case of Zapper, seems to assume ERC-721 for most). This means we're making multiple entries of what's actually one, since an `AssetId` contains an `assetNamespace` part and would effectively consider two of the "same" NFTs with diff asset namespaces different.
Fixed by checking in a more granular fashion for …
=> fix: handle upsertion more gracefully in getNftUserTokens

src/components/Trade/TradeConfirm/TradeConfirm.tsx
Adds the flag `hasUserOptedOutOfDonation` to the event data tracked by Mixpanel for confirmed/failed/successful trades, so we can track more than just the total of fiat that potentially could/could not have been donated to the DAO.
closes #4655
Low, no user facing change, just tracking data added for confirmed trades.
Make a transaction with/without a donation to ShapeShift and check the network traffic for the Mixpanel requests or check the Mixpanel events to confirm the `hasUserOptedOutOfDonation` flag is set appropriately.
N/A
N/A
=> feat: donation opt-out flag in mixpanel tracking
