- .github/PULL_REQUEST_TEMPLATE.md
- src/components/Trade/Trade.tsx
- src/components/Trade/hooks/useAvailableSwappers.tsx
- src/components/Trade/hooks/useDefaultAssets.tsx
- src/hooks/useDeepOutputMemo/useDeepOutputMemo.ts
fix: trade confirmation UI zeroing out when changing network on wallet (#4255)
fix: handle stale cached RTK queries (#4254)
chore: update pr template (#4252)
> chore: release v1.275.0

- src/components/Approval/Approval.tsx
- src/lib/bignumber/bignumber.test.ts
- src/lib/bignumber/bignumber.ts
- src/lib/swapper/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/LifiSwapper/utils/getAssetBalance/getAssetBalance.ts
- src/lib/swapper/LifiSwapper/utils/processGasCosts/processGasCosts.ts
- src/lib/swapper/LifiSwapper/utils/transformLifiFeeData/transformLifiFeeData.ts
Description:
This PR renames the precision parameter to exponent in BigNumber utility functions to improve clarity and understanding of the code. The change is reflected across various files including Approval.tsx, bignumber.test.ts, bignumber.ts, and getTradeQuote.ts.
Specifically, the following modifications have been made:
- In bignumber.ts, all instances of inputPrecision and outputPrecision have been replaced with inputExponent and outputExponent, respectively.
- In bignumber.test.ts, the test descriptions have been updated to reflect the new parameter names.
- In Approval.tsx and getTradeQuote.ts, the function calls have been updated with the new parameter names.
These changes aim to make the code more readable and easier to maintain.
N/A
None, only semantics
Renaming looks sane
- …
> feat: improve convertPrecision API

- .github/workflows/bootstrap.yml
- scripts/bootstrap-env.ts
inspired by yeet - we want to be able to have ops and product test long running feature branches/experiments on hosted environments
adds support for the following ephemeral environments
`['beard', 'juice', 'wood', 'gome', 'cafe']`
DNS has already been configured
n/a - dev QoL
minimal - CI will fail if i've fucked this up, no application code changes
* push your own branch, e.g. `git checkout -b wood && git push`
* configure an alias like `yeet`, e.g. 
```
➜  web git:(cafe) which yeet
yeet: aliased to git checkout -B yeet && git push --force
``` 
* `gh run watch` to watch the build progress
* see your shit appear at `yourname.shapeshift.com`
**note** - i have deliberately only figured builds to run on the `push` action into these branches to save on `size-bertha` costs - PRs against these …
> chore: more yeet

- .github/workflows/cloudflare.yml
missed this in the previous PR - pushes should actually build now
https://github.com/shapeshift/web/pull/4266
n/a
low - similar to previous PR
* should actually build on whitelisted branches
check this syntax is correct in this weirdo github DSL
> fix: build on ephemeral environments

- .env.dev
- .env.develop
eth nodes are sad because of dave shapella so we're pointing local dev/`develop`/`yeet` at happy prod eth nodes for now
n/a
minimal - should be seeing healthy eth nodes again
ops - check `develop.shapeshift.com` doesn't show degraded state for ethereum
👆
👆
> chore: point eth nodes in local and dev frontend at prod backend

- src/assets/translations/en/main.json
- src/components/Trade/TradeConfirm/TradeConfirm.tsx
- src/components/Trade/TradeInput.tsx
- src/components/Trade/hooks/useSwapper/utils.ts
- src/components/Trade/types.ts
- src/state/zustand/swapperStore/testData.ts
Minor UX enhancements for lifi swapper:
1. add slow swap title for lifi swapper
2. display `Amount too low or no route` when a lifi quote is below the $20 threshold to remove ambiguity between invalid trade pairs and quotes below the minimum amount
3. tiny type safety improvements around `tradeFeeSource`
NA
extremely low risk, should not affect logic or functionality at all.
-  get a quote with lifi swapper below the $20 minimum. Should display text "Amount too low or no route"
- get a quote with lifi swapper above the $20 minimum and preview trade. Should display "LI.FI trade This swap may take a few minutes to complete."
> feat: temporary ux enhancements for lifi swapper

- package.json
- scripts/countEnglishWordsSince.ts
An utility script the Globalization WS uses to count the English strings and words which were added/modified since a certain commit. Usually to find out the monthly count of words that have been requested for translation to our translators working for bounties over a period of time.
N/A
None.
None needed. If you want to observe the results you can test by entering this commit for example: 207ad7b99e2661e3202ffbccc8496032b87a41d9
The output will vary based on your current working copy state.
> feat: script to count english strings changes

- src/components/Modals/Send/views/Address.tsx
Fixes the QR code scanning not working after a QR code scan, and users needing to add/remove/change a char to trigger form validation and make the input valid.
Relates to https://github.com/shapeshift/web/issues/4206
Address validation could be borked when inputting/pasting an address. Tested locally and noticed no regressions there
- Scan a QR code (either a BIP-21 UTXO QR code with/without an amount, or an Ethereum EIP-681 QR code)
- Ensure the "Next" button is enabled
- ☝🏽 
- ☝🏽
> feat: validate scanned QR code on form mount

- package.json
- public/index.html
Which is now (since monorail) an alias for yarn build:packages a.k.a a breaking change from
our previous and expected behavior of building web. I may or may not
have been totally rugged by it and figured out let's avoid confusion.
N/A
- CI is happy
- ^
- None
> feat: remove yarn build script

- src/state/slices/portfolioSlice/selectors.ts
this was getting hit a bunch and computing more than the number of chain ids we have in the app (12)
n/a
very low - commonly used pattern
see the change is sane
see that highest balance account id logic still works
> perf: cache commonly hit selector

- .env.dev
- .env.develop
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.ts
- packages/chain-adapters/src/evm/utils.ts
- packages/unchained-client/openapitools.json
- use eip1559 gas fee estimations from unchained
- calculate `txFee` using highest gas price (legacy vs eip1559)
https://discord.com/channels/554694662431178782/1097663172942516284
- low
- ensure fox farming edge case is resolved
- validate the transaction broadcast is using a reasonable gas price
:point_up: 
:point_up:
> feat: unchained eip1559 gas fee estimations and dynamic tx fee

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/utils/index.ts
- src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
- src/features/defi/providers/univ2/hooks/useUniV2LiquidityPool.ts
- src/lib/swapper/swappers/ThorchainSwapper/evm/makeTradeTx.ts
- src/plugins/walletConnectToDapps/v1/useApprovalHandler.tsx
- src/plugins/walletConnectToDapps/v2/utils/EIP155RequestHandlerUtil.ts
Broke THORChain EVM swaps, reverting as I investigate this
N/A
None, brings back prod behavior
- THORChain swaps from EVM chains are happy again
> fix: revert feat: buildCustomTx stringified number value (#4287)

- src/components/Layout/Header/NavBar/UserMenu.tsx
- src/components/Trade/TradeInput.tsx
This PR:
- cleans up `getEnsName()` spew after https://github.com/shapeshift/web/pull/4304
- improves `<TradeInput />` to throw the full error instead of the not informative enough `error.message`
N/A
Console might be too happy
- Open your console
- Ensure no `getEnsName()` spew
> feat: cleanup console spew spew

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/utils/index.ts
- src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
- src/features/defi/providers/univ2/hooks/useUniV2LiquidityPool.ts
- src/lib/swapper/swappers/ThorchainSwapper/evm/makeTradeTx.ts
- src/plugins/walletConnectToDapps/v1/useApprovalHandler.tsx
- src/plugins/walletConnectToDapps/v2/utils/EIP155RequestHandlerUtil.ts
a.k.a the revert of the revert of https://github.com/shapeshift/web/pull/4317 - refer to the original PR for risks and testing steps
closes #
> fix: buildCustomTx stringified number value

- scripts/scrapeWalletConnectRegistry.ts
- src/plugins/walletConnectToDapps/registry-overrides.json
- src/plugins/walletConnectToDapps/registry.json
- Adds the ability to remove entries while scraping dApps data from WalletConnect. Any entry with its `category` property set as "exclude" in the overrides will be removed in the final listing.
- Updates the dApps listing with recent data.
- Adds an override for Polygon's URL (`https://matic.network` doesn't work).
- Adds an override for ShapeShift. I don't think it makes sense to list ourselves in the dApps list as you can't really connect the wallet to itself as far as I know 😄 
The last point should get Product approval I think.
None
- Check the list of dApps is still functional and the overridden entries worked, namely ShapeShift should not be in the list anymore and the link for Polygon should work now.
☝️ 
☝️
> chore: update dapps list and overrides

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/utils/index.ts
- scripts/scrapeWalletConnectRegistry.ts
- src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
- src/features/defi/providers/univ2/hooks/useUniV2LiquidityPool.ts
- src/lib/swapper/manager/SwapperManager.test.ts
- src/lib/swapper/swappers/CowSwapper/CowSwapper.test.ts
- src/lib/swapper/swappers/CowSwapper/CowSwapper.ts
- src/lib/swapper/swappers/ThorchainSwapper/evm/makeTradeTx.ts
- src/lib/swapper/swappers/ZrxSwapper/ZrxSwapper.ts
- src/plugins/walletConnectToDapps/registry-overrides.json
- src/plugins/walletConnectToDapps/registry.json
- src/plugins/walletConnectToDapps/v1/useApprovalHandler.tsx
- src/plugins/walletConnectToDapps/v2/utils/EIP155RequestHandlerUtil.ts
perf: optimized asset filtering in zrx and cow swappers (#4310)
chore: update dapps list and overrides (#4300)
fix: buildCustomTx stringified number value (#4319)
> chore: release v1.284.0

- src/state/slices/common-selectors.ts
we're still seeing randomly huge eth balances in mixpanel
a missing precision would explain things, this guards against a precision and returns a 0 fiat value rather than returning the base units without precision applied
n/a
low - returning $0 is better than megabillions
ensure this return is sane
> fix: guard against no precision when calculating balances

- src/features/defi/components/Deposit/PairDeposit.tsx
- src/features/defi/providers/univ2/components/UniV2Manager/Deposit/components/Deposit.tsx
- src/state/slices/marketDataSlice/marketDataSlice.tsx
- src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
- src/state/slices/portfolioSlice/portfolioSlice.ts
perf: batch reducers (#4342)
feat: don't rely on intermediary fiat values in <PairDeposit /> (#4355)
> chore: release v1.290.0

- src/components/AssetAccountDetails.tsx
- src/components/Layout/Header/SideNav.tsx
- src/pages/Accounts/AccountToken/AccountToken.tsx
- src/pages/Dashboard/WalletDashboard.tsx
- Reduce size of sidebar nav
- Reduce size of the sidebar for dashboard and asset/account details
closes #
small risk
No testing required.
> fix: responsive sizes

- src/pages/Dashboard/components/DashboardHeader.tsx
Allows the buttons Send/Receive/Trade to wrap while remaining centered on the Dashboard when needed (longer text buttons in translations).
closes #4376
None.
Check the buttons in various languages and low/high width resolutions to be sure they always display properly.
☝️ 
☝️ 
EN: <img width="311" alt="en" src="https://user-images.githubusercontent.com/88804546/235321642-d525aadd-2480-461b-8743-3ef8e53eef4e.png">
DE: <img width="311" alt="de" src="https://user-images.githubusercontent.com/88804546/235321641-56ef20e4-787c-4d0b-94cc-ae67780b05b2.png">
ES: <img width="311" alt="es" src="https://user-images.githubusercontent.com/88804546/235321644-4ce7d915-e729-4fdc-90ce-35923dd32d4e.png">
FR: <img width="311" alt="fr" src="https://user-images.githubusercontent.com/88804546/235321646-5c90dc30-8 …
> fix: allow dashboard buttons to wrap

- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.ts
- packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.test.ts
- packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.ts
- packages/chain-adapters/src/evm/utils.ts
- src/components/Trade/hooks/useSwapper/utils.ts
- src/features/defi/helpers/utils.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/txFeeHelpers/evmTxFees/getEvmTxFees.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.test.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/utils/constants.ts
- src/lib/swapper/swappers/ZrxSwapper/zrxBuildTrade/zrxBuildTrade.test.ts
- src/lib/swapper/swappers/ZrxSwapper/zrxBuildTrade/zrxBuildTrade.ts
- src/state/zustand/swapperStore/testData.ts
feat: optimism l1 fees (#4373)
> chore: release v1.296.0

- src/context/AppProvider/AppContext.tsx
rtk query was too smart for my ghetto refetch logic, and was maintaining a subscription to the object and not refetching
this PR
* removes my hand rolled subscription logic in the effect
* uses the `pollingInterval` key inside the `subscriptionOptions` to setup market data subscriptions for spot prices and price history
n/a - noticed by @willyogo
under or overfetching of market data
* see the browser making network requests every 2 minutes
* change `pollingInterval` to see this faster
* leave the app open on the dashboard for more than 2 minutes
* note the prices + charts update automatically again
no visual changes - expect prices and charts should update automatically again
> fix: subscribe to market data

- src/state/slices/txHistorySlice/txHistorySlice.ts
fixes tx overfetching by checking against a flat list of known tx ids for txs involving assets we can't yet parse, namely jaypegz
see my comment in code for how and when we can revert this change
closes #
possible slight performance regression checking against list of all known tx ids for all accounts for all wallets, instead of an index of txs by account
* connect a wallet with NFTs, use willywonka.eth via frame if ya want
* load page once, let all txs load
* reload page, see that we only make 1 network request per chain
* set breakpoint on line `291` and see that it doesn't get hit - i.e. after first page load we should persist a flat list of tx ids
* not testable by ops
> fix: check against flat tx index for existing txs

- src/components/Trade/TradeConfirm/TradeConfirm.tsx
fix: wrong mixpanel eventData buyAmount/sellAmount precision (#4410)
fix: only track confirmed trades after sign and broadcast (#4409)
> chore: release v1.301.0

- src/context/AppProvider/AppContext.tsx
bringing back market data polling caused unexpected high loads on our coingecko api limits. temporarily disable this until our market data proxy at markets.shapeshift.com is available to cache and reduce load
n/a - request from @0xean
minimal - reverting this that was added in recently
* see that i've removed the subscription options
* market data should not automatically update without refresh
> chore: disable market data polling

- src/state/slices/marketDataSlice/marketDataSlice.tsx
- src/state/slices/marketDataSlice/selectors.ts
This PR makes sure we sort the market data AssetIds by market cap at slice level, so selectors/components don't have to do additional
N/A
- By Asset table sorting could be broken, though realistically won't, tested a a sanity check. We apply our own sorting in addition to that so it doesn't matter whether we select assets sorted by market cap or not
- By asset inner tables could be broken, though something something same as above ^
- By provider shouldn't be touched by this diff, but as a paranoia check could be broken
- Ensure by provider table still looks good and sorts by value as a paranoia check
- Ensure by asset table Staking and LP inner rows still look nice and sorty as a paranoia check
- ☝🏽 
- ☝🏽
> feat: sort crypto marketData IDs by market cap

- src/components/Layout/Header/GlobalSearch/GlobalSearchButton.tsx
- Clears the search query after closing the modal
closes #4431 
Confirm the search value clears after clicking on an item and re-opening the search modal.
> fix: clear search query after closing modal

- packages/caip/src/adapters/coingecko/index.ts
- packages/market-service/src/coingecko/coingecko.test.ts
- packages/market-service/src/coingecko/coingecko.ts
- packages/market-service/src/foxy/foxy.test.ts
- packages/market-service/src/foxy/foxy.ts
- packages/market-service/src/idle/idle.ts
- packages/market-service/src/market-service-manager.ts
- packages/market-service/src/market-service.test.ts
- react-app-rewired/headers/csps/marketService/coingecko.ts
- src/config.ts
- src/state/slices/marketDataSlice/marketServiceManagerSingleton.ts
points coingecko requests at markets.shapeshift.com proxy
n/a
low - will be very obvious if market data is broken
* market data and charts should appear correctly without regressions
* we should not be seeing 429 rate limit or other errors
* see that network requests to go markets.shapeshift.com in network tab
* we **should** still be seeing requests to assets.coingecko.com for icons
* we **should not** be seeing requests to api.coingecko.com in network tab
> chore: point at market data proxy

- src/components/Trade/TradeConfirm/TradeConfirm.tsx
- src/lib/swapper/swappers/OneInchSwapper/buildTrade/buildTrade.ts
- src/lib/swapper/swappers/OneInchSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/OneInchSwapper/getUsdRate/getUsdRate.ts
- src/lib/swapper/swappers/OneInchSwapper/utils/types.ts
- src/state/zustand/swapperStore/selectors.ts
- src/state/zustand/swapperStore/utils.ts
Adds opt-out donations to 1inch.
N/A
Small
Ensure `REACT_APP_FEATURE_ONE_INCH` is enabled.
Test that donations work when using the 1inch swapper. Donated amounts should be received by the DAO treasury.
☝️
☝️
> feat: add 1inch donations

- packages/market-service/src/coincap/coincap.ts
- packages/market-service/src/coingecko/coingecko.ts
- packages/market-service/src/exchange-rates-host/exchange-rates-host.ts
- packages/market-service/src/utils/rateLimiters.test.ts
- packages/market-service/src/utils/rateLimiters.ts
- packages/market-service/src/yearn/yearn-tokens.ts
- src/context/AppProvider/AppContext.tsx
- src/state/slices/txHistorySlice/txHistorySlice.ts
remove redundant axios rate limiting so the app doesn't hang for a minute with wallets containing > 100 assets
isolate tx fetching to a single dispatch so we're not blocked on the slowest
n/a
low - check for 429s (rate limit errors) in network tab, and see that tx history is still fetched correctly
connect willawonka.eth with frame wallet and notice that it loads in ~20 seconds rather than ~90 seconds
no visual change just faster loading
> perf: remove rate limiting and isolate tx fetching

- packages/market-service/src/coincap/coincap.ts
- packages/market-service/src/coingecko/coingecko.ts
- packages/market-service/src/exchange-rates-host/exchange-rates-host.ts
- packages/market-service/src/utils/rateLimiters.test.ts
- packages/market-service/src/utils/rateLimiters.ts
- packages/market-service/src/yearn/yearn-tokens.ts
- src/components/AssetHeader/AssetChart.tsx
- src/constants/Config.ts
- src/context/AppProvider/AppContext.tsx
- src/hooks/useTimeframeChange/useTimeframeChange.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/pages/Dashboard/Portfolio.tsx
- src/plugins/foxPage/components/FoxChart.tsx
- src/state/slices/preferencesSlice/preferencesSlice.ts
- src/state/slices/preferencesSlice/selectors.ts
- src/state/slices/txHistorySlice/txHistorySlice.ts
- src/test/mocks/store.ts
perf: remove rate limiting and isolate tx fetching (#4441)
chore: add treasury address as integrator id for lifi swapper (#4442)
chore: change default time frame from MONTH to DAY (#4443)
feat: remember charts timeframe (#4444)
> chore: release v1.308.0

- src/hooks/useMixpanelPortfolioTracking/useMixpanelPortfolioTracking.tsx
As discussed with @thesmithdao the Globalization WS would like to track some data related to the language/locale of users who opt-in to tracking through Mixpanel in order to get richer data about our users' choices in the app.
- Adds `Selected Locale`, `Selected Currency`, `Selected Currency Format` as variable we track for Mixpanel, per portfolio.
Low.
None required, tracking only.
☝️ 
☝️
> feat: track some user prefs with mixpanel

- src/components/AssetSearch/AssetList.tsx
Fixes the scroll to top for the `AssetSearch` component.
Low.
Check that the asset list is scrolled a the top when loading the Assets page and in the asset list when Receiving/Sending assets.
Switch to different filters, it should scroll back at the top too after the filter is applied (whenever the list is updated).
Before (Assets page on load):
After:
> fix: asset search scroll to the top

- src/state/migrations/index.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
Guards against upstream rugs - theoretically `makeAsset` should make us valid, minimal assets for all UNI-V2 assets from Zapper, but upstream rugs can happen - this guards against it at resolver-level.
We should never populate opportunities for pairs we don't have valid asset slice data for.
https://github.com/shapeshift/web/issues/4456
None, this brings more safety in
- Run this diff and ensure grepping `undefined` in your browser in the earn section returns no matches
- ☝🏽 
- ☝🏽
> fix: guard against uni-v2 zapper assets with undefined symbols

- packages/investor-idle/src/IdleOpportunity.ts
- src/state/slices/opportunitiesSlice/resolvers/idle/index.ts
Handles contract reverts gracefully by continuing with the user data flow - those are actually perfectly valid as some contracts eventually get deprecated and stop yielding rewards.
closes #4214
None
Tested with frame-injected @MBMaria's account, against prod
- Ensure Idle opportunities are present in the Earn section
- Ensure the amounts are shown as "Staked Amount" when going to the matching asset's page
- Ensure the underlying asset balance looks sane for Idle opportunities
- Ensure withdraws show the correct deposited amount 
- ☝🏽 
- ☝🏽
> fix: continue resolving idle user data on getClaimableTokens revert

- src/hooks/useBalanceChartData/useBalanceChartData.test.ts
- src/hooks/useBalanceChartData/useBalanceChartData.ts
bignumber.js is slow
this makes the slow part of the balance chart calculation (finding the price at each bucket) twice as fast by doing less math to achieve the same thing
n/a
low - isolated to balance charts
ensure charts look the same as the same wallet in prod
👆
👆
no visual change
toggling between 1 week and 1 month with loaded market data
on gome.shapeshift.com (same as prod with instrumentation)
this PR (lower numbers are better)
> perf: less balance chart math

- src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
Brings back the previous `getValues().cryptoAmount` accessors in `useSendDetails`, vs. the current `useWatch()`. The latter should be more reactive, but somehow our forms are rugged and things become *less* reactive with a `useWatch()` in `useSendDetails`.
N/A, fixes a prod bug spotted by ops in https://discord.com/channels/554694662431178782/1105565906576355348/1105887510665633882
- Ensure inputting an integer amount triggers proper validation (i.e should be allowed if you have enough balance, error if you don't)
- Ensure inputting a decimal amount triggers proper validation with the same logic as the point above
- Ensure send maxes still work for crypto/fiat
- Ensure QR code and send buttons still work properly with an amount in the URL, and while setting amounts manually
- ☝🏽 
- ☝🏽
> fix: useSendDetails cryptoAmount reactivity

- src/Routes/RoutesCommon.tsx
- src/assets/translations/de/main.json
- src/assets/translations/en/main.json
- src/assets/translations/es/main.json
- src/assets/translations/fr/main.json
- src/assets/translations/pt/main.json
- src/assets/translations/ru/main.json
- src/assets/translations/tr/main.json
- src/assets/translations/uk/main.json
- src/pages/Dashboard/components/DashboardHeader.tsx
Changes the "Trade" copy in the main navigation on large/medium width resolutions into "Trade/Bridge" to indicate to users that this page can be used for both Trading and Bridging. Low resolution is unaffected due to the current design constraints.
The change was initially requested by @willyogo and discussed/approved by @reallybeard on Discord.
Translations updated based on the current translations of these two words.
Low.
Check the "Trade" menu item in the main nav, on large/medium resolutions it should be "Trade/Bridge" and on low resolution it should remain "Trade".
☝️ 
☝️ 
Large:
Medium:
Small:
> feat: change Trade into Trade/Bridge in large nav

- src/assets/translations/en/main.json
- src/components/Trade/Components/TradeQuotes/TradeQuotes.tsx
- src/components/Trade/TradeConfirm/ReceiveSummary.tsx
- src/components/Trade/TradeConfirm/TradeConfirm.tsx
- src/components/Trade/TradeInput.tsx
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getIntermediaryTransactionOutputs/getIntermediaryTransactionOutputs.test.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getIntermediaryTransactionOutputs/getIntermediaryTransactionOutputs.ts
- src/lib/swapper/swappers/OsmosisSwapper/OsmosisSwapper.ts
- src/lib/swapper/swappers/OsmosisSwapper/utils/helpers.ts
- src/state/zustand/swapperStore/amountSelectors.ts
fix: denominate osmosis swap fees with sell asset (#4401)
fix: handle insufficient balance on receiving chain (for protocol fees) (#4480)
> chore: release v1.314.0

- packages/investor-foxy/src/api/api.ts
- src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Overview/WithdrawCard.tsx
fix: foxy canClaimWithdraw satisfy getTimeUntilClaimable logic (#4481)
> chore: release v1.315.0

- .env.app
- .env.dev
- .env.develop
- .env.private
Point midgard back to unchained
Low
- Midgard endpoints should resolve like normal
:point_up: 
:point_up:
> chore: point midgard back to unchained backend

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
Increase cosmos gas limit to fix recent out of gas errors
https://discord.com/channels/554694662431178782/1108429698494640188/1108438487188901949
Low
Retest failing tx that it now succeeds
:point_up: 
:point_up:
> fix: increase cosmos gas limit for recent out of gas errors

- src/state/slices/opportunitiesSlice/resolvers/index.ts
Osmosis native staking was never added to `CHAIN_ID_TO_SUPPORTED_DEFI_OPPORTUNITIES` meaning that we stopped fetching user data since 700c72d213 - this underps it
N/A
None
- Osmosis user data is fetched - clear your persisted redux store to confirm
- ☝🏽
- ☝🏽
https://www.mintscan.io/osmosis/txs/3E31383ADEA62B6E74C9061D085181569D948B789220A3C1783B4C5241459840
> fix: resolve osmosis user data

- src/state/apis/zapper/validators.ts
- src/state/apis/zapper/zapperApi.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
This PR:
- Refactors the myzod schema for the Zapper endpoints to leverage the existing ones, adding a new `V2AppsBalancesResponse` schema. Note, many fields have been set to optional. The reason for that is that while the current schema worked for the current endpoints, the same schemas (e.g `ZapperAsset`, `ZapperToken`) end up having a lot of fields maybe undefined in `/v2/balances/apps`
- ~~Adds RTK queries to fetch read-only opportunities and massage them as minimal data. Note that in addition to the zapperApi, and `opportunitiesSlice` query/resolver pair has been added, effectively just a wrapper on top of the zapper RTK query. This is because of circular dependencies issues and will ensure we don't get any.~~
Note, this is *not* consumed yet and will be wired up in a follow-up PR. …
> feat: zapper validators revamp

- src/components/Trade/hooks/useDonationAmountBelowMinimum.tsx
Disables EVM donations (currently 1inch and 0x) on KeeyKey until https://github.com/shapeshift/web/issues/4518 is resolved.
THORSwap donations remail unaffected.
N/A
Small.
Trades above the new receive amount threshold of $500 USD should no longer show the donation option when trading on 0x or 1inch.
☝️
☝️
N/A
> fix: disable KK EVM donations

- src/state/apis/zapper/zapperApi.ts
- src/state/slices/opportunitiesSlice/types.ts
This PR adds support for staking rewards for Zapper read-only opportunities. It assumes claimable rewards for all that have the 'claimable' Zapper metatype.
N/A
None, the flag for Zapper read-only opportunities is currently off.
- Rewards from read-only staking opportunities should now be displayed with the flag on, and the assets/amounts should be matching the data from Zapper's UI, see screenshots
- Since LP is still WIP, the rewards tab might now be showing LP opportunities as active opportunities with rewards, which is expected until LPing is handled in a follow-up.
- ☝🏽 
- ☝🏽
> feat: zapper read-only opportunities staking rewards

- src/components/Trade/Components/TradeQuotes/TradeQuote.tsx
- src/components/Trade/Components/TradeQuotes/TradeQuotes.tsx
- src/components/Trade/TradeConfirm/TradeConfirm.tsx
- src/components/Trade/TradeInput.tsx
- src/components/Trade/hooks/useAccountsService.tsx
- src/components/Trade/hooks/useAvailableSwappers.tsx
- src/components/Trade/hooks/useDonationAmountBelowMinimum.tsx
- src/components/Trade/hooks/useIsTradingActive.tsx
- src/components/Trade/hooks/useSwapper/useSwapper.tsx
- src/components/Trade/hooks/useSwapper/utils.ts
- src/state/zustand/swapperStore/actions.ts
- src/state/zustand/swapperStore/amountSelectors.ts
- src/state/zustand/swapperStore/selectors.ts
- src/state/zustand/swapperStore/testData.ts
- src/state/zustand/swapperStore/types.ts
- src/state/zustand/swapperStore/useSwapperStore.ts
closes #4235
Risk of incorrect send amounts, especially after interacting with UI input amounts/asset selection/max send
Fixes a few issues, commented inline on this PR.
> fix: max send amounts incorrect

- src/lib/swapper/swappers/OneInchSwapper/OneInchSwapper.ts
This PR enables trading gnosis erc20 tokens on the unchained platform via the 1inch swapper
closes #
Swap an erc20 token on gnosis to another erc20 token on gnosis. 
Everything should work out of the box.
> feat: gnosis on 1inch

- src/context/WalletProvider/WalletProvider.tsx
- src/lib/web3-provider.ts
- src/plugins/walletConnectToDapps/v1/WalletConnectBridgeContext.tsx
- src/plugins/walletConnectToDapps/v1/WalletConnectBridgeProvider.tsx
- src/plugins/walletConnectToDapps/v1/bridge/types.ts
- src/plugins/walletConnectToDapps/v1/components/modals/callRequest/methods/SendTransactionConfirmation.tsx
- src/plugins/walletConnectToDapps/v1/components/modals/callRequest/methods/SignTransactionConfirmation.tsx
- src/plugins/walletConnectToDapps/v1/components/modals/callRequest/methods/hooks/useCallRequestFees.ts
Updates the wallet connect v1 implementation to support all EVM chains that Wallet Connect V1 and our Native wallet supports (Ethereum, Avalanche, BNB Chain, Optimism, and Polygon).
N/A, though it might prove useful as a fallback for foxatars on mercle, if needed.
We can't currently test this on https://app.mercle.xyz/shapeshift due to a wagmi
issue in their implementation.
It also seems the current state of their app is a partial implementation of Wallet
Connect V2, so it can't be tested right now anyway.
We can, however, use OpenSea to confirm this works:
1. Go to https://opensea.io/
2. Connect via WalletConnect (it'll use a WalletConnect V1 URI), which means we ca
n only have one chain connected at a time
3. It'll be connected to Ethereum by default. Clicke the wallet balance in the …
> feat: multi-chain walletconnect v1

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/types.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapMinMax/getCowSwapMinMax.test.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapMinMax/getCowSwapMinMax.ts
- src/lib/swapper/swappers/CowSwapper/utils/constants.ts
- src/plugins/walletConnectToDapps/v1/WalletConnectBridgeProvider.tsx
- src/plugins/walletConnectToDapps/v1/bridge/types.ts
- src/plugins/walletConnectToDapps/v1/components/modals/callRequest/CallRequestModal.tsx
- src/plugins/walletConnectToDapps/v1/components/modals/callRequest/methods/SignTypedDataConfirmation.tsx
- src/plugins/walletConnectToDapps/v1/useApprovalHandler.tsx
feat: handle eth_signTypedData_v4 wallet connect request method (#4619)
chore: use 0.01$ min. for CoW Gnosis trades (#4618)
> chore: release v1.336.0

- packages/caip/src/constants.ts
- src/assets/translations/en/main.json
- src/components/Modals/Nfts/NftModal.tsx
- src/components/Modals/Nfts/components/NftCollection.tsx
- src/state/apis/nft/utils.ts
Adds a "Customize FOXatar" link to the NFT modal, both within the collection tab and the jaypeg div.
N/A
None
- "Customize FOXatar" is displayed for FOXatars
- "Customize FOXatar" isn't displayed for other NFTs
- ☝🏽 
- ☝🏽
> feat: customize FOXatar

- src/plugins/walletConnectToDapps/registry-overrides.json
- src/plugins/walletConnectToDapps/registry.json
- Updates the dApps listing and fixes the broken icons. Few dApps have also been removed from the WalletConnect listing.
- Removes useless overrides (WalletConnect purged many apps)
N/A
None.
Check  the dApps listing, icons should be fixed.
☝️ 
☝️
> chore: update dapps listing

- src/context/TransactionsProvider/TransactionsProvider.tsx
- src/state/apis/nft/nftApi.ts
Does what it says on the box - refetches NFT user data on incoming NFT Tx (on FOXatar NFT only for now, but may be generalized to any NFT if we wish to in the future)
N/A
- Mint your FOXatar
- Ensure it is appearing on your NFT tab after mint
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/cdc553c1-50b4-4a23-ae3b-b21279902c77
> feat: refetch NFTs on foxatar incoming Tx

- src/components/Modals/Nfts/NftModal.tsx
- src/components/Nfts/NftCard.tsx
- src/plugins/avalanche/index.tsx
- src/plugins/bnbsmartchain/index.tsx
- src/plugins/ethereum/index.tsx
- src/plugins/gnosis/index.tsx
- src/plugins/optimism/index.tsx
- src/plugins/polygon/index.ts
- src/state/apis/nft/nftApi.ts
- src/state/apis/nft/parsers/alchemy.ts
- src/state/apis/nft/utils.ts
WIP as Polygon unchained is currently borked, so we can't test this yet
This PR:
- adds an NFT refresh button, getting a single NFT metadata from Alchemy
- if the NFT is a Polygon NFT *with IPNS meta* (not IPFS - we can only get meta, thus medias, from IPNS gateway links), we use our unchained media, which is refreshed on query
- is the NFT is an Optimism/Mainnet NFT, this uses the regular Alchemy parsing logic
While at it, exposes `http` in all ethereum plugins, to make things nice and reusable and not have to write wrappers over all `V1Api` method in chain-adapters
N/A
None, this is isolated as a new feature - work case scenario, this doesn't work (which it doesn't at the time of writing because of our Polygon node being down)
- Customize your FOXatar
- Click the refresh icon
- Ensure …
> feat: nft refresh button

- src/components/Modals/Nfts/NftModal.tsx
- src/components/Nfts/NftCard.tsx
- src/plugins/avalanche/index.tsx
- src/plugins/bnbsmartchain/index.tsx
- src/plugins/ethereum/index.tsx
- src/plugins/gnosis/index.tsx
- src/plugins/optimism/index.tsx
- src/plugins/polygon/index.ts
- src/state/apis/nft/nftApi.ts
- src/state/apis/nft/parsers/alchemy.ts
- src/state/apis/nft/utils.ts
This reverts commit 8871403a207e00bdb9fcde18f873374ef3318fd2.
https://github.com/shapeshift/web/pull/4639
> revert: "feat: nft refresh button (#4639)"

- src/components/Modals/Nfts/NftModal.tsx
- src/components/Nfts/NftCard.tsx
- src/plugins/avalanche/index.tsx
- src/plugins/bnbsmartchain/index.tsx
- src/plugins/ethereum/index.tsx
- src/plugins/gnosis/index.tsx
- src/plugins/optimism/index.tsx
- src/plugins/polygon/index.ts
- src/state/apis/nft/nftApi.ts
- src/state/apis/nft/parsers/alchemy.ts
- src/state/apis/nft/utils.ts
Re-opening for @gomesalexandre. It was merged, as it was working for me locally, but then we were having node issues and ops couldn't test: see https://discord.com/channels/554694662431178782/1115110431808299130 thread.
WIP as Polygon unchained is currently borked, so we can't test this yet
This PR:
- adds an NFT refresh button, getting a single NFT metadata from Alchemy
- if the NFT is a Polygon NFT *with IPNS meta* (not IPFS - we can only get meta, thus medias, from IPNS gateway links), we use our unchained media, which is refreshed on query
- is the NFT is an Optimism/Mainnet NFT, this uses the regular Alchemy parsing logic
While at it, exposes `http` in all ethereum plugins, to make things nice and reusable and not have to write wrappers over all `V1Api` method in chain-adapters
N/A …
> feat: nft refresh button (revert of the revert)

- src/assets/translations/en/main.json
- src/assets/translations/fr/main.json
- src/components/Layout/Header/NavBar/ChainMenu.tsx
The "Select a network" copy was hard-coded and thus untranslatable. This makes it translatable and adds the French translation as an example. The rest of the translations will be provided by Globalization translations during the next sync.
N/A
None.
Check that the copy at the top of the Network selector menu (visible for wallets that require network switching like MetaMask) is translated in French when it is the current user's language.
☝️ 
☝️ 
Before: 
After: (don't mind the Gnosis network icon, it's a merged but unreleased fix, the Before screenshot is from the app in production).
> fix: make select a network copy translatable

- src/components/EarnDashboard/components/ProviderDetails/NestedAsset.tsx
- src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx
Adds missing external link icon for read-only opportunities' rewards
N/a
None, this is under flag
- Read-only opportunities' rewards have an external link icon
- Non read-only opportunities don't
- None, this is under flag
> feat: read-only rewards external link icon

- src/Routes/RoutesCommon.tsx
- src/assets/translations/de/main.json
- src/assets/translations/en/main.json
- src/assets/translations/es/main.json
- src/assets/translations/fr/main.json
- src/assets/translations/id/main.json
- src/assets/translations/ko/main.json
- src/assets/translations/pt/main.json
- src/assets/translations/ru/main.json
- src/assets/translations/tr/main.json
- src/assets/translations/uk/main.json
- src/assets/translations/zh/main.json
- src/components/StakingVaults/EarnOpportunities.tsx
- src/pages/Dashboard/components/DashboardHeader.tsx
- src/pages/Defi/views/StakingVaults.tsx
Requested by big @reallybeard - now that we're going to handle debt, earn doesn't cut it as a terminology anymore.
N/A
I may have forgotten a earn route somewhere and this may be rugged
None, this only updates the label, not the route itself
- ^
- grep for `navBar.earn` and ensure my grep fu is strong
- ^
> feat: rename earn tab to DeFi

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
Placeholder UI to get some structured data flow executing and visible. Unblocks @0xApotheosis to allow development of execution state machine while @woodenfurniture continues with swapper integration.
NA
Near zero risk, not user facing at all.
See above
> feat: created placeholder multi-hop trade confirmation UI

- scripts/generateAssetData/overrides.ts
Coingecko has updated its list for Optimism assets today and FOX is now listed. Let's add it.
- Adds "FOX on Optimism" override following the current ones for our FOX token.
- Refreshes the full list of assets, I've rapidly checked removal and additions and have dome few manual checks for liquidity and info about some of the tokens added/removed and the changes seem sane (When I checked the timestamp earlier this morning on https://tokens.coingecko.com/optimistic-ethereum/all.json t
Note: The changes to the Osmosis pools which still happen when using the generation script (see mentioned in #4650) have been reverted before commit. This part of the generation process still need to be addressed upstream according to @gomesalexandre (thanks for the help).
Medium, the assets list is a central …
> feat: fox on optimism and regen assets list

- src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx
- src/state/apis/zapper/zapperApi.ts
- src/state/slices/opportunitiesSlice/selectors/combined.ts
- src/state/slices/opportunitiesSlice/types.ts
This PR removes the staking terminology as a user-facing one for read-only opportunities:
- brings in the concept of a ~~`label`~~ `group` i.e a user-facing group. From a view-layer perspective, that's different from the `version` which is to be used for the top-level heading, see `Farms` vs. `Chef-V2-Farm`
- brings in the app label as `version` i.e `Farms` and `XSUSHI` here:
This allow us not to display zapper read-only opportunities as "Staking" for all, but have actual user-friendly labels. Note `groupId` was chosen for the label, to distinguish from the top-level `version` heading, but we may want to remove this concept and reuse the `version` - ~~to be~~ confirmed by @reallybeard we're gucci
N/A
- Groups looking sane - note no transformation of the casing was done for now, will do as …
> feat: no Staking user-facing terminology for read-only opportunities

- src/pages/Accounts/AddAccountModal.tsx
Fixes a minor visual issue in the Add Account modal.
N/A
None.
Check the title isn't overlapping with the text in the Add Account modal (accessible on the "Wallet" page, for wallets which let the user add accounts).
☝️ 
☝️ 
Before:
After Browser:
After Mobile resolution:
> fix: add account modal title margin

- src/state/apis/nft/parsers/alchemy.ts
- src/state/slices/assetsSlice/utils.ts
- relates to https://github.com/shapeshift/web/issues/4703 - `https://github.com/shapeshift/web/issues/4703`
Theoretically none, but If our gateway is rugged, we're rugged
- NFT medias and asset image in wallet/assets/Tx history is still looking sane
- FOXatar refreshes are still happy
- ☝🏽 
- ☝🏽
> feat: replace ipfs URLs with self-hosted gateway

- src/state/apis/nft/parsers/alchemy.ts
- src/state/apis/nft/types.ts
Adds an optional `balance` property for ERC-1155 `NftItem`s, populated from Alchemy, which is our only reliable source as far as token standards are concerned. Note, since we don't upsert to portfolio/assets slice yes, this doesn't do anything yet.
When this is merged, 4712 will need a restack and we'll need to add the proper balance for 1155s to
https://github.com/shapeshift/web/pull/4712/files#diff-7ef9f6fd70f7be4faed5cc8c2702f7d46529689cf81962a71d88be8c46a23025R167
Relates to https://github.com/shapeshift/web/issues/4703 - `patches sends (accurate portfolio balances from nft api sources)`
None, not consumed yet
- None
> feat: add balance property to NftItem

- src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts
- onRamper changed their darkmode to themeName just updated this
closes #
no risk
onRamper should show up in the same darkmode/lightmode as the user settings.
> fix: onramper theme name

- src/components/Banners/YatBanner.tsx
related to/missing from https://github.com/shapeshift/web/pull/4747
we shouldn't include the demo wallet EVM address in the URL when linking out to y.at, such that they don't accidentally get associated with an address the user does not control
related to #4606
minimal
ensure my early return logic is sane
same testing steps as https://github.com/shapeshift/web/pull/4747 - but ensure that there is no address included in the URL the yat banner sends you to when using the demo wallet
see previous PR. no visual change.
> fix: don't track y.at purchases for demo wallet

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/hooks/useIsApprovalNeeded.tsx
- src/state/slices/swappersSlice/swappersSlice.ts
Adds approval check for multi hop trades. Includes tiny fixes to asset selection buttons in multi hop trade input.
closes  #4762
No risk - not user facing
This is tricky to test currently, but it might be possible if you can get a trade quote on a pair requiring erc20 approval.
See above
> feat: added approval checks for multi-hop trades

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.test.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
This PR ensures we handle the pseudo-halted state of savers hard cap reached, i.e a holistic hard cap across savers which effectively makes all deposits halted.
- closes https://github.com/shapeshift/web/issues/4752
- closes https://github.com/shapeshift/web/issues/4766
None
- Ensure "Deposit halted" shows in overview, and the deposit button is hidden while the hard cap is reached (which is the case at the time this is authored)
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: handle savers hard cap reached

- src/context/AppProvider/AppContext.tsx
- src/state/apis/nft/nftApi.ts
- src/state/apis/zapper/zapperApi.ts
- src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
fix: claimable assets as opportunities (#4765)
feat: upsert all NFTs in nftApi (#4754)
> chore: release v1.356.0

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/hooks/useAccountIds.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useHopHelper.tsx
- src/components/MultiHopTrade/hooks/useQuoteValidationPredicateObject.tsx
- src/components/MultiHopTrade/hooks/useSelectedQuoteStatus.tsx
- src/components/MultiHopTrade/types.ts
Adds quote validation to multi-hop swapper.
- Passes swap errors through to tooltip
- Handles network fees across hops
Closes https://github.com/shapeshift/web/issues/4728
Small - contained entirely within the multi-hop swapper.
TODO
> feat: multi-hop quote validation

- src/components/Menu/Menu.theme.ts
- src/components/Trade/Components/AssetSelection.tsx
- src/pages/ConnectWallet/ConnectWallet.tsx
- src/pages/Missions/Missions.tsx
- Small tweaks to fix the issues when we upgraded chakra
- Fix button color on splash page
- Fix button state on menu dropdowns
- Fix padding around the account dropdown on trade
closes #
no risk
> fix: update chakra issues after upgrade

- src/assets/translations/en/main.json
- src/components/Menu/Menu.theme.ts
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/hooks/useAccountIds.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useHopHelper.tsx
- src/components/MultiHopTrade/hooks/useQuoteValidationPredicateObject.tsx
- src/components/MultiHopTrade/hooks/useSelectedQuoteStatus.tsx
- src/components/MultiHopTrade/types.ts
- src/components/Trade/Components/AssetSelection.tsx
- src/pages/ConnectWallet/ConnectWallet.tsx
- src/pages/Missions/Missions.tsx
fix: update chakra issues after upgrade (#4774)
feat: multi-hop quote validation (#4763)
> chore: release v1.357.0

- src/state/slices/opportunitiesSlice/opportunitiesApiSlice.ts
This removes the console spew spew 🔫  from opportunitiesApi endpoints.
Sure, we don't log errors anymore but:
1. Most of them aren't actual errors and part of the actual flow
2. RTK endpoints are just actions, thus the rejected ones can be inspected with redux tools
N/A
None
- Spew spew is gone
- Nothing to see here
> feat: don't log opportunities api errors

- .env.base
- .env.dev
- .env.develop
gm
N/A
Medium - current opportunities might get rugged, and read-only ones might not be sane, test with multiple wallets
- Test with multiple frame-injected wallets and ensure this looks sane against Zapper (some opportunities are known to be flaky, and that's an upstream issue, ping me if that's so I can confirm and ping the Zapper team)
- Current opportunities list show no regressions and still work as before
- Ensure the fiat net worth doesn't double count opportunities in DeFi/as asset holdings
- ☝🏽 
- ☝🏽
> feat: enable read-only opportunities

- .env.base
- .env.dev
- .env.develop
feat: enable read-only opportunities (#4789)
> chore: release v1.360.0

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/hooks/useAccountIds.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- src/state/reducer.ts
- src/state/slices/swappersSlice/selectors.ts
- src/state/slices/swappersSlice/swappersSlice.ts
- src/state/slices/tradeQuoteSlice/helpers.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/test/mocks/store.ts
- Adds a tradeQuoteSlice to Redux to store selected trade quote state.
- Updates existing helpers to be consumed via selectors 
Closes https://github.com/shapeshift/web/issues/4771
Small - limited to scope behind the multi-hop flag.
Check that the new Redux slice contains the expected data upon retrieving a quote (auto-populating the best quote) and quote selection.
N/A
N/A
> chore: add tradeQuoteSlice

- src/components/MultiHopTrade/hooks/useHopHelper.tsx
- src/components/MultiHopTrade/hooks/useQuoteValidationPredicateObject.tsx
- src/components/MultiHopTrade/hooks/useSelectedQuoteStatus.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
Move useHopHelper logic into selectors where appropriate.
Closes https://github.com/shapeshift/web/issues/4792
Small - all functionality contained behind a feature flag.
Ensure flagged UI still displays as expected.
N/A
> chore: move hop-helper logic to selectors

- .env.base
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
tl;dr UNI-V2 subgraph is borked, meaning Zapper return us no UNI-V2 opportunities, meaning UNI-V2 LPs and ETH/FOX staking are borked. This makes them great again until the subgraph is fixed.
N/A
Conceptually none, we still have the old implementation's branching. Potentially will be spamming our JSON-RPC nodes in case users have cached data since it will fetch 600+ pools data from the contracts.
- Clear your persisted store
- Ensure ETH/FOX LP and staking are happy
- ☝🏽 
- ☝🏽
> feat: turn DYNAMIC_LP_ASSETS flag off

- .env.base
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
feat: turn DYNAMIC_LP_ASSETS flag off (#4800)
> chore: release v1.363.0

- src/components/MultiHopTrade/hooks/useQuoteValidationPredicateObject.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
Safety first. Add explicit return types to tradeQuoteSlice selectors.
N/A
Minimal, no un-feature flagged changes.
App should show no regressions, though nothing specific to test.
☝️
☝️
N/A
> chore: add explicit return types to tradeQuoteSlice selectors

- scripts/generateAssetData/ethereum/idleVaults.ts
- scripts/generateAssetData/ethereum/index.ts
- src/state/migrations/index.ts
This PR:
- uses `poolName` instead of `tokenName` to name Idle assets
- moves the idle assets spread first since `uniqby` keeps the unique by first match 
- removes the concept of fetching and populating underlying Idle assets altogether. This is drunk and rugs our own assets i.e USDC, USDT etc. All Idle underlyings are pretty much assets we have already, so there is no need to re-fetch them from Idle API instead.
- regenerates asset data
N/A, requested by Idle
None
- Idle assets/DeFi opportunities names are looking sane
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> feat: use poolName for Idle LP assets

- scripts/generateAssetData/ethereum/idleVaults.ts
- scripts/generateAssetData/ethereum/index.ts
- src/components/MultiHopTrade/hooks/useQuoteValidationPredicateObject.tsx
- src/state/migrations/index.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
feat: use poolName for Idle LP assets (#4804)
chore: add explicit return types to tradeQuoteSlice selectors (#4797)
> chore: release v1.364.0

- src/lib/swapper/swappers/ThorchainSwapper/cosmossdk/getCosmosTxData.ts
ROON trades are currently borked. The reason for that is we always try and introspect GAIA.ATOM inbound address for Cosmos SDK pools, which happens to be halted currently
https://github.com/shapeshift/web/blob/1b8b2449619c00108c6857c2baed70e4d0b3e16d/src/lib/swapper/swappers/ThorchainSwapper/cosmossdk/getCosmosTxData.ts#L53
We should only introspect GAIA.ATOM inbound address when trading ATOM, not when trading RUNE, which uses the pool module and isn't related to ATOM inbound address whatsoever.
N/A
None
- Trades from ROON are happy
- ☝🏽 
- ☝🏽
> fix: trades from ROON

- packages/chain-adapters/src/utxo/types.ts
- src/components/MultiHopTrade/hooks/useAllowanceApproval/helpers.ts
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useApprovalTx.tsx
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/LifiSwapper/LifiSwapper2.ts
- src/lib/swapper/swappers/ThorchainSwapper/ThorchainSwapper2.ts
First go at cleaning up after https://github.com/shapeshift/web/pull/4784 - note this doesn't tackle the TODOs about pending `from` plumbing
N/A
None, isolated to the new multi-hop swapper
- Ensure the broadcast consumption and types look sane
- Nothing to see here
> feat: multi-hop trade execution cleanup

- src/lib/swapper/swappers/ThorchainSwapper/buildThorTrade/buildThorTrade.ts
Does what it says on the box - plumbs `from` through `buildThorTrade` for UTXOs - Cosmos SDK was already handled, and EVM chains is the only one which will still need to be tackled and require quite a bit more lift.
N/A
None, multi-hop isolated
Nothing to see here
> feat: plumb from through UTXOs `buildThorTrade`

- src/lib/swapper/swappers/ThorchainSwapper/buildThorTrade/buildThorTrade.ts
- src/lib/swapper/swappers/ThorchainSwapper/evm/makeTradeTx.ts
- src/lib/utils/evm/index.ts
Does what it says on the box - same as https://github.com/shapeshift/web/pull/4827 for EVM chains
N/A
None, multi-hop isolated
Nothing to see here
> feat: plumb from through EVM `buildThorTrade`

- src/pages/Missions/Missions.tsx
- Update to new mission and dates
closes #
Small risk
Confirm clicking on the fox army mission takes you to the correct URL
> fix: update fox army mission cta and dates

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/Approval/Approval.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/useAllowanceApproval.tsx
Add approvals UI to new architecture using the non-multi-hop UI. Integrates our new execution hook for approvals.
closes #4834
not user facing - no risk
Check that approvals execute and work as exepcted when multi-hop feature flag is enabled
See above
> feat: implemented legacy approvals UI for exchange client

- src/lib/utils/evm/index.ts
Fixes broken trades where data is added to `contractData` instead of `data`
The origin of this issue appears to be here
https://github.com/shapeshift/web/commit/4c4a86e4e0b5c8a8b04ca10a0830b546a568726a#diff-e1c07bf5d2e33ec33ad78ade8314e7848cbf1db824b59fa82c040747b0a748b5R87
NA
Although this fixes complete broken trades and approvals and gas estimates, its high risk nonetheless. 
Check trades and gas estimates are working as expected.
See above. Please sanity check this with extreme paranoia.
See testing notes. This is high risk, although it fixes an issue of broken trades and gas estimates.
> fix: incorrect data field in transaction creation

- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/gnosis/GnosisChainAdapter.test.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.test.ts
- packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.test.ts
- packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.test.ts
- packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.test.ts
- packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.test.ts
- src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
- src/components/Modals/Send/utils.ts
- src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Confirm.tsx
- src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Deposit.tsx
- src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Confirm.tsx
- src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/investor/investor-foxy/api/api.ts
- src/lib/swapper/swappers/OsmosisSwapper/OsmosisSwapper.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/txFeeHelpers/utxoTxFees/getUtxoTxFees.ts
- src/lib/utils/evm/index.ts
- src/plugins/cosmos/utils.ts
- src/plugins/walletConnectToDapps/utils.ts
See https://github.com/shapeshift/web/pull/4843 for context - this avoids us being rugged similarly in the future.
N/A
Theoretically none, this doesn't produce any runtime change as long as my copy `di(kiconst getFeeDataInput =<esc>p` skills are strong (i.e this is indeed a pure copy and paste with added types)
- Ensure copy pastaroo is sane
- CI is passing
- None
> feat: strongly type getFeeData() consumptions' inputs

- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/LifiSwapper/LifiSwapper2.ts
- src/lib/swapper/swappers/ThorchainSwapper/ThorchainSwapper2.ts
Does what it says on the box - uses the correct available assets to buy/sell on the new THOR swapper.
Note, as agreed with @woodenfurniture , to keep the area of change minimal here and to *actually* make things stateless, the filter methods have been made async, so we can `thorchainSwapper.initialize()` on the original swapper.
This is subject to change, as we bring more of the original swapper behavior into the new one, but for now, this unbreaks things.
N/A
None with the flag off
- Enable the multi-hop flag
- Ensure the available assets to buy/sell are the same as with the flag off
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: new thorchain swapper available assets

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/state/apis/swappers/selectors.ts
- src/state/apis/swappers/swappersApi.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/test/mocks/store.ts
Remove quotes from the slice, as we can access them directly from the cache.
N/A
- Quotes should still work behind the multi hop flag
- Quote selection should work
N/A
N/A
> perf: remove quotes from slice

- src/components/MultiHopTrade/components/Approval/Approval.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- src/components/MultiHopTrade/helpers.ts
- src/components/MultiHopTrade/hooks/useActiveQuoteStatus.tsx
- src/components/MultiHopTrade/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
Selecting a selected swaper selector wasn't a great developer experience, lets use "active" instead.
N/A
CI should go green.
☝️
N/A
N/A
> chore: replace selected with active swapper vernacular

- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/constants.ts
Updates lifi integrator ID to donation-enabled identifier.
Needs to go in at 00:00 UTC today so our monthly tracking of fox missions is not disrupted.
NA
No risk
See above
> chore: update lifi integrator id for fox missions and dontations

- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/constants.ts
chore: update lifi integrator id for fox missions and dontations (#4868)
> chore: release v1.371.0

- src/components/Trade/hooks/useAccountsService.tsx
fix: initialise selectedBuyAssetAccountId & selectedSellAssetAccountId (#4870)
> chore: release v1.372.0

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/components/Trade/TradeConfirm/AssetToAsset.tsx
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/CowSwapper/CowSwapper2.ts
- src/lib/swapper/swappers/CowSwapper/endpoints.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/CowSwapper/types.ts
- src/lib/swapper/swappers/LifiSwapper/LifiSwapper2.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/OneInchSwapper/endpoints.ts
- src/lib/swapper/swappers/ZrxSwapper/endpoints.ts
- src/lib/utils/evm.ts
- src/state/apis/swappers/helpers/getCowTradeQuoteHelper.ts
- src/state/apis/swappers/helpers/getInputOutputRatioFromQuote.ts
- src/state/apis/swappers/swappersApi.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
Implements cow swapper for new exchange client. Includes several fixes, commented inline.
closes #4838
Low risk of something borked with cow swapper.
- Test user-facing cow swap is working
- Test user-facing cow quotes are still correct
Test the new cow swapper with multi hop flag on
See testing notes above. Should be no change from prod.
New cow swapper executing trades:
> feat: implemented cow swapper for exchange client

- src/lib/swapper/swappers/OneInchSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/getMinimumCryptoHuman/getMinimumCryptoHuman.test.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.test.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/utils/fetchZrxQuote.ts
- src/lib/swapper/swappers/utils/helpers/helpers.test.ts
- src/lib/swapper/swappers/utils/helpers/helpers.ts
`normalizeAmount` is an old implementation stemming from https://github.com/shapeshift/lib/pull/765/files#diff-6903517b56ea777f9301691a9a8b4801183fe6c04730ddb8e9d06d0c42fe5a8eR8, which was initially written for THOR swapper only and ended up being used in other swappers.
Following the implementation fix in https://github.com/shapeshift/web/pull/4894, this now removes it altogether.
We have the concept of base unit numbers, which are guaranteed to never contain decimal places - if they do, we have bigger problems. This makes this method redundant, thus the cleanup.
N/A, though relates to https://github.com/shapeshift/web/issues/4879 which will be closed when this goes in (we can also merge both as a stack to avoid double-testing)
Theoretically none - if our base unit numbers are wrong, we …
> feat: cleanup redundant normalizeAmount

- src/components/Trade/hooks/useSwapper/swapperManager.ts
- src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Deposit/components/Confirm.tsx
- src/features/defi/providers/osmosis/components/OsmosisManager/Lp/Withdraw/components/Withdraw.tsx
- src/lib/swapper/swappers/OsmosisSwapper/OsmosisSwapper.test.ts
- src/lib/swapper/swappers/OsmosisSwapper/OsmosisSwapper.ts
- src/lib/swapper/swappers/OsmosisSwapper/filterAssetIdsBySellable/filterAssetIdsBySellable.ts
- src/lib/swapper/swappers/OsmosisSwapper/filterBuyAssetsBySellAssetId/filterBuyAssetsBySellAssetId.ts
- src/lib/swapper/swappers/OsmosisSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/OsmosisSwapper/utils/constants.ts
- src/lib/swapper/swappers/OsmosisSwapper/utils/helpers.ts
- src/lib/swapper/swappers/OsmosisSwapper/utils/osmoService.ts
- src/lib/swapper/swappers/OsmosisSwapper/utils/types.ts
Refactors osmosis swapper to minimise lift when implementing new swapper for exchange client (#4837)
NA
Moderate risk of broken quotes and trades for osmosis/cosmos/atom
Test trades using osmosis swapper are still working as expected
See above
See above
> chore: refactor osmosis swapper in preparation for exchange client

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
- src/components/MultiHopTrade/hooks/quoteValidation/useActiveQuoteStatus.tsx
- src/components/MultiHopTrade/hooks/quoteValidation/useInsufficientBalanceProtocolFeeMeta.tsx
- src/components/MultiHopTrade/hooks/quoteValidation/useQuoteValidationErrors.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/types.ts
- Add additional validation states
- Increase quote polling interval to 20 seconds (because 10 was too annoying)
- Prevent negative amounts from showing in the "you get" section
N/A
Small and well contained, plus all affected code paths are behind a feature flag.
Check that validations (relating to fees, balances, wallet support) etc match production.
☝️
Hold off testing until exchange swapper is properly ready.
N/A
> chore: additional validation states

- src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx
- src/lib/investor/investor-idle/IdleOpportunity.ts
Does what it says on the box - uses the right contract address for Idle deposit approvals.
closes https://github.com/shapeshift/web/issues/4907
None, contract address was wrong
- Idle approvals go through without polling eventually failing
- After approving an Idle deposit, ensure you get routed to the next step and can proceed to deposit
- ☝️ 
- ☝️
> fix: idle deposit approvals

- src/components/MultiHopTrade/components/Approval/Approval.tsx
Does what it says on the box - pushing a new routes while the form submission hasn't completed, then reacting on `isSubmitting` (which will be false since submission never completed) in the following route's logic is going to cause us trouble.
Most likely the same issue with `handleBack` not resetting values.
Fixes 2, 3, and 10 in "Exchange Swapper Testing":
> 2. eth to btc - selecting preview trade went straight to broadcasting
> 3. eth to btc - transaction does not broadcast
> 10. usdc on gnosis approval went straight to broadcasting without being approved on wallet first. tx never broadcasted. it did ask to approve and completed the second time
N/A
None
This assumes multi-hop flag-on, no code paths touched with the flag off here
- Try and swap a token you need an approval for
- Approve …
> fix: wait for form submission before approve to confirm routing in multi-hop

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
Does it do, the box claims? Hmm, so it seems, yes.
N/A
The intent may have been to actually enable cross-account for ZRX and CoW all along, since the comment only mentions Li.Fi and 1inch. If so, we'll wrongly disable it for these swappers.
- Enable multi-hop flag
- Test cross-account trading (meaning different account number and/or different chains) properly works with THOR and Osmosis with the multi-hop flag enabled
- Ensure only THOR and Osmosis are available for cross-account trading (note, Osmosis isn't properly implemented for multi-hop yet)
- Nothing to see here, unless you're testing a build with multi-hop flag enabled
- Swappers with cross-account selection disabled
- Swappers with cross-account selection enabled (THOR, Osmosis)
> fix: disable account selection on no cross-account trade support for multi-hop <TradeInput />

- src/lib/swapper/swappers/LifiSwapper/LifiSwapper.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/constants.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getMinimumCryptoHuman/getMinimumCryptoHuman.ts
N/A
If I can't do a ternary proper, Li.Fi minimum for cross-chain is borked and is now 0
- Ensure cross-chain Li.Fi swaps still have a 20$ min.
- Ensure same-chain Li.Fi swaps have no minimum
- Ensure I know how to write a ternary
- ☝🏽
> feat: 0 minimum for same-chain Li.Fi swaps

- src/pages/Missions/Missions.tsx
- Re add fox army as ongoing mission
closes #
Clicking the fox army card takes you to postmint
> fix: readd fox army card as ongoing mission

- src/components/MultiHopTrade/MultiHopTrade.tsx
Ensuring we handle switching routes (e.g trade route to another route than back) without having stale data e.g selected assets
N/A
This may be dangerous in case we rely on swapperSlice values for multi-hop execution and have it happen in the background - in which case, we could e.g swap the wrong asset on the next hop, lose donation status etc.
To be confirmed by swappy boys
- Assumes multi-hop flag on
- Go to the trade page
- Select some asset
- Alternatively, select some asset **and** go to trade preview
- Switch pages
- Ensure assets are reset to the default ETH -> FOX
- Confirm this is safe
- ☝🏽
- Note, unless you are testing this with a build that explicitly turned the multi-hop flag on, nothing to see here as this doesn't touch current swapper's code paths …
> fix: clear swapperSlice on multi-hop trade router unmount

- src/lib/swapper/swappers/ThorchainSwapper/utils/getTradeRate/getTradeRate.ts
Handle calling THORSwapper's `getTradeQuote` on unsupported assets by using monadic error handling to gracefully catch.
See screenshots below for console errors.
N/A
Small risk to THORSwap quotes.
Ensure THORSwap quotes and trades still work as expected.
☝️
☝️
> fix: thorswap error handling

- src/lib/address/address.ts
See https://github.com/shapeshift/web/issues/2059 for reference. We previously had safeguards in place to avoid loss of funds for EIP-681, using the contract address in place of the `target_address`, and putting the actual address in `parameters.address`. Safeguards went away in https://github.com/shapeshift/web/commit/baf2b621944180dece06d77b378afd434cf1a6fe#diff-14ad33c87d46e8417b7708a7e24e20808c361c450f2dcae009d11ba3bda158c9L45- this restores them
N/A
None, we're being overly cautious again, as we should have
- Pasting an ETH URL with an `address` parameter in the global search bar doesn't resolve
- Scanning a QR code with an `address` parameter doesn't work
- ☝🏽 
- ☝🏽
> fix: don't parse eth URLs with address parameter

- src/lib/swapper/utils.ts
Add `url` and `method` properties to swapper mixpanel events.
Adds to https://github.com/shapeshift/web/issues/4941.
Very small.
Mixpanel should now show the new properties in the "Your properties" event tab on the mixpanel Dashboard.
☝️
☝️
> chore: add method & url to swapper mixpanel events

- src/lib/mixpanel/types.ts
- src/lib/swapper/swappers/LifiSwapper/LifiSwapper.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/LifiSwapper/executeTrade/executeTrade.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getLifiChainMap.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getUnsignedTx/getUnsignedTx.ts
- src/lib/swapper/utils.ts
Small tidy-up PR to use the MixPanelEvents enum.
N/A
Almost 0.
N/A
N/A
N/A
N/A
> chore: use MixPanelEvents enum

- src/lib/swapper/swappers/LifiSwapper/LifiSwapper.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/LifiSwapper/executeTrade/executeTrade.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getLifiChainMap.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getUnsignedTx/getUnsignedTx.ts
- src/lib/swapper/utils.ts
chore: do not track api requests via MixPanel (#4985)
> chore: release v1.386.0

- src/components/AssetAccountDetails.tsx
- src/pages/Dashboard/Dashboard.tsx
- src/pages/Dashboard/WalletDashboard.tsx
- src/pages/Defi/components/EligibleCarousel.tsx
- src/pages/Missions/Missions.tsx
- Makes the sidebar go full width when the direction is column
- Moved the chakra props out into const properties
closes #
No risk
> fix: width of sidebar on medium screens

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
fix: only fire fail/success events once (#5002)
> chore: release v1.389.0

- src/hooks/useBalanceChartData/useBalanceChartData.ts
we used to care about super accurate balance charts but haven't for a long time as it's pushing shit up hill catching every edge case
this got broken in a recent refactor and is showing all the time. get rid of it.
closes #
basically none, we haven't cared about this forever anyway
just removing debug logging
no testing required
> chore: remove debug charts error

- src/components/Modals/Settings/SettingsList.tsx
- Will prompt native wallet for password so it can be unlocked on cache clear and doesn't look like the app is stuck in an infinite loading state
- Will auto-reconnect connected MM
closes https://github.com/shapeshift/web/issues/5013
None, isolated to cache clear
- Clearing cache on native wallet connected prompts for the native password
- Clearing cache on unlocked MM connected will auto-reconnect MM
- Clearing cache on locked MM will redirect to the connect wallet page
- Clearing cache on mobile with gome endpoint set in settings prompts for wallet unlock
https://github.com/shapeshift/web/assets/17035424/292c6ecc-4ead-4230-9056-f22bfd095f7b
https://github.com/shapeshift/web/assets/17035424/43141249-f6e7-4be1-8220-80416aa6327a …
> feat: reconnect wallet on cache clear

- src/components/MultiHopTrade/MultiHopTrade.tsx
Makes us consistent with the default buyAsset in asset page
closes https://github.com/shapeshift/web/issues/5012
None
- When clicking trade from an asset page, the buy asset is matching the one from the page default trade pair
- ☝🏽 
- ☝🏽
> feat: parse multi-hop trade defaultBuyAssetId from route

- package.json
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getLifi.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getNetworkFeeCryptoBaseUnit/getNetworkFeeCryptoBaseUnit.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getUnsignedTx/getUnsignedTx.ts
- src/lib/swapper/swappers/LifiSwapper/utils/transformLifiFeeData/transformLifiFeeData.ts
- yarn.lock
Major version bump of LiFi SDK.
Seems to fix a bug we've been observing with step transaction request failures.
Probably closes https://github.com/shapeshift/web/issues/5039.
Medium risk that LiFi swaps are broken.
Do a full regression test on the LifI swapper and ensure it all functions as it should, including:
- Trades
- TX status updates
☝️
☝️
N/A
> fix: bump LiFi SDK

- package.json
- src/components/MultiHopTrade/hooks/quoteValidation/useActiveQuoteStatus.tsx
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getLifi.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getNetworkFeeCryptoBaseUnit/getNetworkFeeCryptoBaseUnit.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getUnsignedTx/getUnsignedTx.ts
- src/lib/swapper/swappers/LifiSwapper/utils/transformLifiFeeData/transformLifiFeeData.ts
- yarn.lock
fix: invert error logic (#5043)
fix: bump LiFi SDK (#5041)
> chore: release v1.396.0

- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/tradeExecution.ts
Adds type safety to event emitter for trade execution
NA
Extremely low risk of broken trades
Check trades still work - it will be very obvious if broken
See above
See above
Trades appear to be working still
> chore: make trade execution event emitter type safe

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/getQouteErrorTranslation.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
feat: expose monadic quote errors to the user (#5055)
> chore: release v1.400.0

- src/components/Drawer/Drawer.theme.ts
- Fixes background of the drawer
closes #
> fix: drawer background missing

- src/state/slices/opportunitiesSlice/resolvers/ethFoxStaking/index.ts
please note this is going into `release`
this part of the diff was missed in the previous PR https://github.com/shapeshift/web/pull/4134/files#diff-d6dfdac64a5c0d82314e76d8f05dc80caedb441002715e78fec6106867575c30L60
this is just a variable rename, and won't affect functionality, but should be done for posterity
n/a
related to fox farming https://github.com/shapeshift/web/pull/5070
test per #5070 
as above
as above
> chore: missed variable name in fox farming v7 implementation

- src/state/slices/opportunitiesSlice/constants.ts
missed this, it's obviously needed
n/a
isolated to defi section
doesn't need testing, i tested it, see screenshot
here's my tx depositing LP into the farm https://etherscan.io/tx/0x14bbc580e41a89d0e09f933458997064fb4979650c1b762df79859834bdd0f2a
> fix: add fox farming to staking contract list

- src/lib/investor/investor-idle/IdleSdk.ts
- src/lib/investor/investor-idle/idleService.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/state/slices/opportunitiesSlice/constants.ts
fix: add fox farming to staking contract list (#5078)
fix: lifi status polling broken due to caching in their sdk (#5077)
perf: cache idle responses (#5057)
> chore: release v1.404.0

- src/pages/Missions/Missions.tsx
Ends the PostMint mission as [the last campaign ended last week](https://x.postmint.xyz/community/64665c31a6c1394b3a35be58/64997a2a590fc8641c50f51a).
closes #
None.
The missions should now be listed under "Ended Missions".
☝️ 
☝️
> chore: end postmint mission

- src/components/TransactionHistoryRows/TransactionDate.tsx
- src/components/TransactionHistoryRows/TransactionGenericRow.tsx
- src/components/TransactionHistoryRows/TransactionTime.tsx
- src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx
- src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummaryV2.tsx
- Display the full date (no time) in the Transaction History for each day.
- Use localization for the dates and times
- Similar fix for the WalletConnect dApp connection date displayed in the WalletConnect menu once you're connected.
closes #5076
Low. Only display dates
- Check the transaction history for dates.
- Connect any dApp and check the date.
☝️ 
☝️ 
TX History Date English:
TX History Date French:
TX History Small Resolution Portuguese:
TX History Sidebar French:
dApp English:
dApp German:
> fix: tx history and dapp dates

- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
fix: filter sell assets by walletSupportsChain (#5088)
> chore: release v1.406.0

- packages/caip/src/constants.ts
- src/lib/market-service/market-service-manager.ts
- src/state/apis/zerion/zerionApi.ts
- src/state/slices/portfolioSlice/selectors.ts
i.e allows us to ensure we get market data for bridged assets, thus unrugging quotes for them
closes https://github.com/shapeshift/web/issues/5096
Low - this brings in *additional* data
Ensure the pairs in #5096 are happy 
- ☝🏽 
- ☝🏽
> feat: use market data from bridged assets if base asset data is unavailable

- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/CowSwapper/endpoints.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.ts
- src/lib/swapper/swappers/ThorchainSwapper/cosmossdk/getCosmosTxData.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getSignTxFromQuote.ts
- src/lib/swapper/tradeExecution.ts
- src/lib/swapper/types.ts
Removes market data from trade execution (currently used by CoW & THORSwap)
Unblocks slippage progress.
Closes https://github.com/shapeshift/web/issues/5099
Medium, touches receive amounts.
Ensure the receive amount for CoW looks correct.
☝️
☝️
N/A
> chore: remove market data from trade execution

- src/components/MultiHopTrade/components/TradeConfirm/ReceiveSummary.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
Sets affiliate fees to 25bps for thorchain swapper, with UI to display it.
Does not apply a fee if the donation is below the minimum (same as prod).
NA
Extremely low risk of broken trades due to changes to UI in trade input and trade confirmation.
* Check thor trades are including the fee where above minimum
* Check non-thor trades are not broken somehow
☝️
☝️
Thor - fee displayed in trade input
Thor - case where fee below minimum - no fee
Non-thor - fee is "free", donation displayed
Non-thor - donation disabled
> feat: thorchain swapper affiliate fees

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
Add an `isStreaming` boolean to the `quoteMeta` in the `Quotes Received` MixPanel event.
N/A
Small.
The `Quotes Received` MixPanel event will contain an additional `isStreaming` boolean in the `quoteMeta`.
☝️
☝️
> chore: add isStreaming to mixpanel

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
See https://github.com/shapeshift/web/pull/5118#discussion_r1299781537 for context
- relates to the closed https://github.com/shapeshift/web/issues/5109
None
- Ensure smallish THOR quotes only show regular THORChain quote as an option
- Ensure larger quotes show both regular (time-optimized) and streaming (price-optimized) quotes
- ☝🏽 
- ☝🏽
> feat: don't display streaming THOR quote when same as regular quote

- src/state/apis/zerion/validators/fungible.ts
Cleans up error spew in related assets for some
N/A
- Navigate to `/#/assets/eip155:1/erc20:0x420412e765bfa6d85aaac94b4f7b708c89be2e2b`
- Ensure no error spew is present in console
- ☝🏽 
- Nothing to see here
> fix: zerionApi schema nullable fields

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getSignTxFromQuote.ts
Adds logic to prevent executing trades that are below the recommended minimum.
Fixes trade refunding when sending ATOM -> ETH
NA
Virtually none.
Check thor trades work.
☝️
☝️
> feat: comply with thorchain minimum amounts when swapping

- src/state/helpers.ts
> fix: thorswap supports cross account trades

- src/components/MultiHopTrade/helpers.ts
THOR case untested as I don't have testing balance for a THOR swap, pls scrutinize
N/A
We get this wrong and stop tracking actual donations properly
- Initiate a THOR trade (i.e with a fee)
- Ensure fee is tracked as ShapeShift fee
- Initiate another swapper trade with/out a donation (doesn't matter as we 0 it out)
- Ensure fee is tracked as a donation
> feat: split THOR shapeshift donation/fee in Mixpanel

- src/lib/swapper/api.ts
- src/lib/swapper/swapper.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/OneInchSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ZrxSwapper/endpoints.ts
- src/lib/swapper/types.ts
- src/state/apis/swappers/swappersApi.ts
Removes dependency on market data inside the swappers, in preparation for SDK.
closes #5098 
closes #5086 
Low risk of broken donations in zrx and 1inch swappers.
Check donations are still working for zrx and 1inch swappers.
☝️
☝️
> chore: remove market data requirement from swappers

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- Use an accordion to show the routes, as the button no longer makes sense as it isn't co-located
- Adds loading skeletons to quotes
Extends upon a conversation in general to improve this display.
Small risk of a UI regression on the trade widget.
Confirm that we can still expand the quotes section and click between them.
☝️
☝️
> chore: improve route list

- src/components/Modals/QrCode/Form.tsx
- src/components/Modals/Send/Form.tsx
- src/components/Modals/Send/views/Address.tsx
- src/components/Modals/Send/views/Details.tsx
feat: hide URL params in scanned URL from send/QR form (#5155)
> chore: release v1.414.0

- src/components/MultiHopTrade/components/TradeConfirm/ReceiveSummary.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
fix: hide donation checkbox for cowswap, hide bps when fee is zero (#5172)
> chore: release v1.415.0

- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
Uses the correct limit for THORSwap streaming TXs.
N/A - production issue.
Small
Streaming swaps should display the correct limit in the memo.
☝️
☝️
N/A
> fix: thorswap streaming memo

- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
fix: thorswap streaming memo (#5182)
> chore: release v1.418.0

- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.ts
Adds an assertion to thor swaps to ensure the correct affiliate fee is applied.
NA
Very little risk
Check thor trades still work
> chore: assert the correct affiliate fee for thor swaps, if configured

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/constants/constants.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getSignTxFromQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
chore: assert the correct affiliate fee for thor swaps, if configured (#5180)
fix: dont refetch thor swapper quotes when building tx to prevent mismatch with UI (#5184)
fix: use default slippage value to display min expected after slippage (#5185)
> chore: release v1.419.0

- src/constants/constants.ts
chore: update thor slippage (#5189)
> chore: release v1.421.0

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
fix: thorchain streaming swaps quote (#5197)
> chore: release v1.423.0

- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/types.ts
fix: unrug custom receive address trades (#5227)
> chore: release v1.428.0

- packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.ts
The most recent bsc hard fork added EIP-1559 fees. We previously had logic to set the min fee for bsc to 3 gwei to account for the default metamask rpc endpoint (min gas limit configurable per node). Now that EIP-1559 is supported, we need to update this logic to account for `maxFeePerGas` and `maxPriorityFeePerGas`.
closes # https://github.com/shapeshift/web/issues/5211
- Low
- Confirm sends are working again
- Multiple wallets
- Native asset and tokens
:point_up: 
:point_up:
> fix: set min gas limit for legacy and eip1559 fees

- src/components/MultiHopTrade/helpers.ts
As requested by @shapeshift/product - allows to filter trades by chain either on the buy or sell side. 
N/A
None
- `buyAssetChain` and `sellAssetChain` appear on Mixpanel events
- ☝🏽 
- ☝🏽
> feat: add buy and sell chain to Mixpanel trade events

- src/components/Modals/Snaps/SnapConfirm.tsx
- src/components/Modals/Snaps/SnapContent.tsx
- src/components/Modals/Snaps/SnapIntro.tsx
- src/components/Modals/Snaps/Snaps.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ManualAddressEntry.tsx
- src/context/WalletProvider/MetaMask/components/MetaMaskMenu.tsx
- src/context/WalletProvider/MetaMask/components/SnapInstall.tsx
- src/lib/mixpanel/types.ts
- Adds a warning screen that user must agree to, in order to install the snap
- Adds mixpanel events for the snap 
closes #
Small risk
When connecting a MM wallet, and you see the snap screen. After clicking "add snap" you should see another screen with a warning and a checkbox. Once clicking the checkbox the "confirm & install" button becomes enabled. Once you click that you will get the install window in MM.
> feat: add warning for multichain snap

- src/components/Modals/Snaps/SnapConfirm.tsx
- Adds number hash to match the other places we write it out.
closes #
> chore: fix typo on warning list item

- src/components/Modals/Snaps/Snaps.tsx
Does what it says on the recording below - fixes the duplicate toast when installing a snap currently.
N/A
None
- Install the snap from any of the CTAs
- Ensure the snap installed toast only gets toasty once
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/c665bf05-0db5-4803-aef0-f9a8733fcc2a
> fix: duplicate snap installed toast

- .env.base
Rotate 0x API key.
TODO once this is deployed: delete existing key from 0x Dashboard.
N/A
Risk of 0x trades/quotes not working.
0x trades and quotes should still work as expected.
☝️
☝️
N/A
> chore: rotate 0x key

- react-app-rewired/headers/csps/wallets/walletConnect.ts
- src/assets/translations/en/main.json
- src/components/Modals/Snaps/Snaps.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/plugins/walletConnectToDapps/components/header/ConnectDapp.tsx
- src/plugins/walletConnectToDapps/components/header/DappAvatar.tsx
- src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx
- src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummaryV2.tsx
- src/plugins/walletConnectToDapps/components/header/Session.tsx
- src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
- src/plugins/walletConnectToDapps/utils.ts
- src/plugins/walletConnectToDapps/v2/WalletConnectModalManager.tsx
- src/plugins/walletConnectToDapps/v2/WalletConnectV2Provider.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/CosmosSignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/EIP155SignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/SessionProposal.tsx
- src/plugins/walletConnectToDapps/v2/eventsManager/useWalletConnectEventsManager.ts
- src/plugins/walletConnectToDapps/v2/hooks/useWalletConnectState.ts
- src/plugins/walletConnectToDapps/v2/types.ts
- src/plugins/walletConnectToDapps/v2/walletConnectReducer.ts
feat: allow users to connect multiple walletconnect client sessions to app (#5261)
fix: duplicate snap installed toast (#5259)
feat: gracefully handle savers not enough native asset for gas at input step (#5253)
fix: savers deposit precision issues (#5254)
> chore: release v1.433.0

- .env.base
> chore: release v1.434.0

- src/assets/translations/en/main.json
- src/components/Modals/Snaps/SnapConfirm.tsx
LLM-gen'd copy acting as a tacit agreement you as a user have saved your seed phrase and failure to do so means you will lose your fundus if you lose access to your MM installation.
N/A
None
- We are happy with the copy
- ☝🏽 
- ☝🏽
> feat: pinky swear seed phrase is backed up on snap warning modal

- src/components/Layout/Header/Header.tsx
- src/pages/Accounts/Accounts.tsx
a.k.a poor man's service worker
N/A
Low to none - ensure this doesn't run more than once putting a debugger in here - the check should run once when `walletAccountIds` is still empty, and a second time after the selector returns them, passing the checks and clearing the AccountIds.
- Connect to the app with MM and install the ShapeShift Multichain snap
- Close all your app tabs and uninstall MetaMask snaps
- Ensure re-opening the app clears your AccountIds, reloading only the EVM ones
- See risks
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/b4588e33-c9cc-48d2-858e-9212db31b5c4
> feat: clear wallet AccountIds when uninstalling MM snap outside of the app

- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
.. and ensures the minimum is set for USDT on Ethereum saver.
closes https://github.com/shapeshift/web/issues/5267
None
- Try and deposit into USDT on Ethereum saver
- Ensure you're not blocked at input step with "NaN USDT"
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> feat: add USDT on Ethereum as supported savers AssetId

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
Fixes the `Cannot unwrap Err value of Result.Ok` error at confirm step introduced in https://github.com/shapeshift/web/pull/5272
N/A
None
- Withdraw from savers
- Ensure confirm step works and you don't see the error in the screenshots
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: thorchain savers withdraw confirm

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
... a.k.a make Cosmos staking great again.
This sets a safe gas limit bound for delegations/redelegations/undelegations/claims.
We currently have *consistent* failures with the 300,000 limit for validator Txs, which can use anything from 350,000 to 650,000 gas with current network conditions.
Bumping the gas to 1M ensures a safe upper bound for those Txs, while the unused gas will still be unused.
closes https://github.com/shapeshift/web/issues/5250
None, staking Txs are *fully* borked currently, can't break what's broken
- Cosmos staking, unstaking and claims Txs are going through again
- ☝🏽 
- ☝🏽 
https://www.mintscan.io/cosmos/txs/23EB580F03091585422AC65BC41EE466008B1AA7819560497DD435280B141CBE
https://www.mintscan.io/cosmos/txs/ADD805B16C3216C084B3D8663C7175A5D376D2850E39C69C8E1C2EEB6A …
> feat: bump cosmos hardcoded gas limit to 1M

- src/components/Modals/Send/utils.ts
- src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx
i.e removes the assumption that Cosmos staking Txs are unsupported with MM, they *are* valid as long as the snap is installed.
N/A
None, same logic bit we have on sends, see OCD naming refactor there
- Cosmos native staking is happy with snaps
- ☝🏽 
- ☝🏽 
- Develop/Release/Prod
- This diff
> fix: multichain snap cosmos native staking

- src/context/I18nProvider/I18nProvider.tsx
- src/context/ModalProvider/ModalProvider.tsx
- src/context/PluginProvider/PluginProvider.tsx
Optimises re-rendering behavior in the following:
* I18nProvider
* ModalProvider
* PluginProvider
NA
Risk of broken:
* I18n
* Modals
* Plugins
Check no changes in functionality from previous commit for the following
* I18n
* Modals
* Plugins
☝️
☝️
> perf: optimise rerendering in providers

- src/context/WalletProvider/SelectModal.tsx
- src/context/WalletProvider/WalletViewsSwitch.tsx
Optimises re-rendering behavior in the WalletProvider
NA
Risk of broken wallets due to changes in WalletProvider
Check no changes in functionality from previous commit for wallets
☝️
☝️
> perf: optimise rerendering in wallet provider

- src/plugins/walletConnectToDapps/components/DappRegistryGrid.tsx
- src/plugins/walletConnectToDapps/components/ExplorationBanner.tsx
- src/plugins/walletConnectToDapps/components/PageInput.tsx
- src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummaryV2.tsx
- src/plugins/walletConnectToDapps/components/header/Session.tsx
- src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
- src/plugins/walletConnectToDapps/components/modals/connect/Connect.tsx
Optimises re-rendering behavior in walletConnectToDapps, which is the feature responsible for connecting shapeshift to other dapps as a wallet.
NA
Risk of (even more) broken walletconnect v2
NOTE: when testing, prefer you use https://react-app.walletconnect.com/ because most dApps have not implemented things on their side correctly which often throw testing off
NOTE: walletconnect v2 is known to be broken in several ways and this PR does not address that. Refer to #5285 for details.
* Check no changes in functionality from previous commit.
☝️
☝️
> perf: optimise rerendering in walletConnectToDapps provider

- src/plugins/walletConnectToDapps/v2/WalletConnectModalManager.tsx
Optimises re-rendering behavior in wallet connect v2 modal manager.
NA
Risk of (even more) broken walletconnect v2
NOTE: when testing, prefer you use https://react-app.walletconnect.com/ because most dApps have not implemented things on their side correctly which often throw testing off
NOTE: walletconnect v2 is known to be broken in several ways and this PR does not address that. Refer to #5285 for details.
* Check no changes in functionality from previous commit.
☝️
☝️
> perf: optimise rerendering in wallet connect v2 modal manager

- src/state/apis/abi/abiApi.ts
☝️
NA
Risk of broken abi api
Do a `eth_sendTransaction` with walletconnect v2 - you'll see an error message that is not `[object: Object]`
☝️
☝️
> fix: better error handling in abi-api

- package.json
- yarn.lock
Removes unused walletconnect packages, following https://github.com/shapeshift/web/pull/5316.
N/A
Small
Theoretically this should have no effect, as none of these packages were consumed.
Ensure everything re: wallectconnect looks fine.
☝️
☝️
N/A
> chore: remove unused walletconnect packages

- src/state/apis/nft/utils.ts
Fixes a weird, possibly non-deterministic error WRT NFT updates. Initially spotted by @MBMaria in https://discord.com/channels/554694662431178782/1153559221527400479/1153570537478557726 and I could repro in local develop, somehow remote develop was happy.
This gives us confidence that the reference we pass and are updating in `updateNftItem` is *not* a read-only object.
N/A
None
- NFTs are loading on demo wallet - and any other
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: nft borked update

- src/state/apis/nft/nftApi.ts
Follow-up of #5308, this time around filtering by term vs. explicit IDs.
tackles https://github.com/shapeshift/web/issues/5301
We might filter too much, which is better than the other way around
- Comment out `BLACKLISTED_COLLECTION_IDS` and clear your persisted store
- Ensure native still doesn't show scammy NFTs, thanks to the filtering by blacklisted terms
- ☝🏽 
- ☝🏽
> feat: nftApi blacklist NFT items by term

- src/components/Modals/Send/utils.ts
- src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx
tl;dr https://github.com/shapeshift/web/pull/5292 brought some naive, immediate checks unborking native Cosmos staking for snaps, which were superseeded by https://github.com/shapeshift/web/pull/5287 tightening the checks, in particular for MM impersonators which appear as `isMetaMask`.
Release mergy shenanigans ensued, and we lost the https://github.com/shapeshift/web/commit/04557416d20c20165482334a3620f540df299f5f diff by bringing https://github.com/shapeshift/web/pull/5292 *after* https://github.com/shapeshift/web/pull/5287. https://github.com/shapeshift/web/pull/5314 did fix things in some fashion, though without the tightened checks for Brave.
This diffes the diff to make the diff diffed again.
N/A
None, this was already stamped and tested
- Cosmos native staking is still working …
> fix: mergefix MM impersonator tightened checks

- package.json
- src/components/Modals/Send/utils.ts
- src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx
- src/state/apis/covalent/covalentApi.ts
- src/state/apis/nft/constants.ts
- src/state/apis/nft/nftApi.ts
- src/state/apis/nft/selectors.ts
- src/state/apis/nft/utils.ts
- src/state/apis/zapper/zapperApi.ts
- src/state/migrations/clearAssets.ts
- src/state/migrations/clearPortfolio.ts
- src/state/migrations/index.ts
- src/state/slices/assetsSlice/assetsSlice.ts
- src/state/slices/assetsSlice/selectors.ts
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/utils.ts
- src/state/slices/txHistorySlice/txHistorySlice.ts
- src/test/mocks/portfolio.ts
- yarn.lock
feat: nftApi initialState blacklist demo wallet spam NFTs (#5308)
fix: nft borked update (#5320)
feat: nftApi blacklist NFT items by term (#5309)
feat: nft blacklist improvements (#5310)
feat: clearNfts migration (https://github.com/shapeshift/web/pull/5319/commits/cf8c3b81b57810e8e8a526d51e2ad1dd7355e9a8)
feat: clearAssets migration (https://github.com/shapeshift/web/pull/5319/commits/0587ef251a9041aa8c14a328b55f7c9b3151bb16)
feat: clearPortfolio including portfolioApi (https://github.com/shapeshift/web/pull/5319/commits/110a135f97c651fc034b858eb61e03829e9a0ba2)
feat: add additional exclusion terms(https://github.com/shapeshift/web/pull/5319/commits/49a9244abc94badbe90fab64c80d6ba74cb138a0)
fix: mergefix MM impersonator tightened checks (#5321)
chore: remove unused walletconnect packages …
> chore: release v1.441.0

- src/components/Layout/Header/TxWindow/TxWindow.tsx
- This adds some padding to the top of the tx window to account for safe areas on mobile.
closes #
No risk
> fix: safe area for the tx window

- src/components/Modals/Snaps/SnapIntro.tsx
- src/pages/ConnectWallet/ConnectWallet.tsx
Ensures that:
- ETH icon doesn't appear twice, once for Ethereum, the second time for Optimism
- Gnosis *chain* icon is used over Gnosis native XDAI asset
N/A
None
- Snap intro modal looks saner
- ☝🏽 
- ☝🏽 
- Prod
- This diff
> feat: snaps intro modal prioritize networkIcon over icon

- src/components/Modals/FiatRamps/views/Overview.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/DonationCheckbox.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/context/WalletProvider/KeepKey/components/RecoverySentenceEntry.tsx
- src/context/WalletProvider/KeepKey/hooks/useKeepKeyVersions.ts
- src/context/WalletProvider/KeepKeyProvider.tsx
- src/lib/cryptography/login.ts
- src/lib/utils/index.ts
- src/plugins/walletConnectToDapps/hooks/useIsWalletConnectToDappsSupportedWallet.tsx
Reduces imports by checking wallet device type rather than via `instanceof`
NA
Low risk of incorrect wallet logic due to incorrectly identifying wallet type
Check each supported wallet type can transact
☝️
☝️
> perf: add wallet identifier helpers

- src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx
- src/context/WalletProvider/NativeWallet/components/NativeCreate.tsx
- src/context/WalletProvider/NativeWallet/components/NativeTestPhrase.tsx
- src/context/WalletProvider/WalletProvider.tsx
Removes * import of @shapeshiftoss/hdwallet-native to take advantage of treeshaking when supported by hdwallet exports
NA
Low risk of incorrect code imports
Check native wallet works for create, backup and transacting
☝️
☝️
> perf: remove * import of @shapeshiftoss/hdwallet-native

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
This was initially raised as part of a large refactor of star imports in unchained-client which is no longer happening. The commit was ready so may as well get it in.
NA
Very low risk to cosmos trades and cosmossdk chain behavior in the app generally
Check cosmossdk trades still work
☝️
☝️
> perf: remove * import from cosmos sdk base adapter

- src/Routes/Routes.tsx
Fixes this garbage
NA
Risk of broken routing in app
Check app path routing still works, including unusual cases, redirects etc
☝️
☝️
screenshotofnothing.jpg
> fix: dont pass route props to layout component

- react-app-rewired/headers/csps/wallets/walletConnect.ts
Fixes the following
NA
Low risk.
Check console error message above is no longer present.
☝️
☝️
> fix: add walletconnect domain to frame-src csp

- package.json
- react-app-rewired/headers/csps/snapshots.ts
- src/context/AppProvider/AppContext.tsx
- src/lib/fees/parameters.ts
- src/lib/fees/utils.ts
- src/state/apis/snapshot/snapshot.ts
- src/state/apis/snapshot/validators.ts
- src/state/reducer.ts
- src/state/store.ts
- src/test/mocks/store.ts
- yarn.lock
prereq for feeeez - get fox voting power from snapshot
* get the fox voting strategies from snapshot for the `shapeshiftdao.eth` space
* get the block height at the timestamp for fox discount delay
* get the voting power at this block height
this isn't consumed yet, just required for upcoming fee calcs
n/a
calculating wrong voting power causing users to pay higher fees than they deserve
* connect a wallet and see the logs in the console
* FOX voting power should be aggregated across all of your accounts according to snapshot strategies
👆
👆
> feat: snapshot api fox voting power

- src/lib/fees/model.test.ts
- src/lib/fees/model.ts
- src/lib/fees/parameters.ts
- src/lib/fees/utils.ts
implementation of fee model, not yet consumed
https://ipfs.io/ipfs/QmVsox8WdUhpWK35Pm3LvmSGGwtzSMFwwWojWJ7K8Dat7s
n/a
incorrect fee calcs, the fee boogeyman scares everyone away
see test cases, compare to curve in proposal for sanity
n/a
> feat: fee model implementation

- src/context/AppProvider/AppContext.tsx
- src/state/slices/opportunitiesSlice/mappings.ts
- src/state/slices/opportunitiesSlice/opportunitiesApiSlice.ts
- src/state/slices/opportunitiesSlice/thunks.ts
This reverts commit 4161c0b9013446a2b602883cc79369d463c48a06.
> revert: fetch all staking opportunities metadata in a single rtk query request (#5340)

- src/context/AppProvider/AppContext.tsx
Removes spurious log
NA
Low risk.
NA
> chore: remove spurious console log

- src/components/Layout/Layout.tsx
Was part of another task which was closed.
Breaks out object props into hardcoded values to reduce rerendering throughout the app.
NA
Little to no risk.
Check app loads.
☝️
☝️
> perf: break out chakra object props in Layout.tsx into hardcoded values

- src/pages/Dashboard/components/DashboardHeader.tsx
- This adds mobile header buttons
- Moves some media query objects out of the component
closes #
Small risk
Click the blue buttons at the top on mobile and they should open their respective modal/page.
> feat: add mobile header buttons

- src/assets/translations/en/main.json
- src/plugins/walletConnectToDapps/WalletConnectModalManager.tsx
- src/plugins/walletConnectToDapps/components/modals/SessionProposal.tsx
feat: enable optional chains for walletconnect (#5364)
> chore: release v1.445.0

- src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts
Fixes inability to trade via walletconnect.
closes #5285
Low risk.
Attempt a trade with 1inch via walletconnect. 
Note: dont use uniswap yet, a separate issue needs addressing as detailed here:
#5305
https://github.com/Uniswap/interface/issues/7086
☝️
☝️
trade sent
actual tx viewable here
uniswap approvals now working (though actual trades broken https://github.com/Uniswap/interface/issues/7086 )
> fix: send transactions with walletconnect

- src/assets/translations/en/main.json
- src/components/AssetAccountDetails.tsx
- src/components/AssetHeader/AssetActions.tsx
- src/components/AssetHeader/AssetChart.tsx
- src/components/AssetHeader/AssetDescription.tsx
- src/components/AssetHeader/AssetHeader.tsx
- src/components/AssetHeader/AssetMarketData.tsx
- src/components/Button/Button.theme.ts
- src/components/Card/Card.theme.ts
- src/components/Equity/Equity.tsx
- src/components/Graph/Graph.tsx
- src/components/Graph/MaxPrice.tsx
- src/components/Graph/MinPrice.tsx
- src/components/Graph/PrimaryChart/PrimaryChart.tsx
- src/components/Layout/Main.tsx
- src/components/PriceChart/PriceChart.tsx
- src/components/Radio/Radio.tsx
- src/components/RelatedAssets/RelatedAssets.tsx
- src/components/StakingVaults/EarnOpportunities.tsx
- src/components/StakingVaults/ProviderCard.tsx
- src/components/StakingVaults/WalletProviderTable.tsx
- src/components/TransactionHistory/AssetTransactionHistory.tsx
- src/lib/charts.ts
- src/pages/Dashboard/Portfolio.tsx
- src/pages/Dashboard/RecentTransactions.tsx
- Remove balance chart on asset page
- Make it look nice on mobile
closes #
Small risk
Asset details should work pretty much the same as it did before.
> feat: modify mobile version of screen

- src/plugins/walletConnectToDapps/hooks/useWalletConnectState.ts
- src/plugins/walletConnectToDapps/typeGuards.ts
- src/plugins/walletConnectToDapps/utils.ts
- src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts
fix: rarible not signing messages due to spurious empty string in their payload (#5374)
> chore: release v1.447.0

- src/context/WalletProvider/WalletConnectV2/components/Connect.tsx
- src/context/WalletProvider/WalletConnectV2/useWalletConnectV2EventHandler.ts
- src/context/WalletProvider/WalletProvider.tsx
- src/lib/utils/index.ts
Resolves the follow tickets - open them for details
- #5395
- #5396
closes #5395
closes #5396
Low risk of walletconnect v2 broken
See tickets linked for details
> fix: various issues switching wallet with walletconnect

- src/components/MultiHopTrade/components/TradeConfirm/ReceiveSummary.tsx
- Adds trade fee modal
closes #
> feat: trade fee modal

- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
Resolves issue where sell amount input gets replaced with '0' upon initial entry, but subsequent entries worked fine.
closes [5414](https://github.com/shapeshift/web/issues/5414)
1. First-time entry for sell amount should not replace input with '0'.
2. The behavior should be consistent across multiple attempts and refreshes.
> fix: prevent trade input resetting to 0 on initial input

- .env.base
- react-app-rewired/headers/csps/trmLabs.ts
- src/config.ts
- src/lib/swapper/swapper.ts
- src/lib/swapper/utils.ts
> chore: release v1.453.0

- src/context/WalletProvider/WalletConnectV2/config.ts
Ensures WalletConnect v2 is happy with Arbitrum
N/A
None
- Connect to the app with wc v2
- Ensure you can broadcast an Arbitrum Tx
- ☝🏽 
- ☝🏽
> feat: add arbitrum wc2 JSON-RPC endpoint

- .env.base
Fixes a merge conflict that has slipped into develop branch.
NA
Low risk.
☝️
☝️
> fix: merge conflict appearing in develop

- src/components/Modals/Send/utils.ts
- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
Ensures we pass the accountType when getting the `senderAddress` with adapter.getAddress().
Failure to do so will get the default UtxoAccountType (SegwitNative), which is wrong since:
1. The MM snap doesn't support SegWit Native (only Legacy for all UTXOs) and will throw
2. The address we'll get will be wrong, effectively checking the wrong address for sanction verification
closes https://github.com/shapeshift/web/issues/5473
None
- UTXO sends are great again on all UTXOs
- UTXO THOR trades are great again
- ^
- ^
> fix: mm snap UTXO sends/trades

- .env.app
- .env.dev
- .env.develop
- .env.e2e
- .env.private
- cypress/support/e2e.ts
- scripts/generateTradableThorAssetMap/generateTradableThorAssetMap.ts
- src/components/MultiHopTrade/hooks/useThorStreamingProgress/useThorStreamingProgress.tsx
- src/components/MultiHopTrade/utils.ts
- src/lib/swapper/swappers/ThorchainSwapper/ThorchainSwapper.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getInboundAddressDataForChain.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/thorService.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
Temporarily points prod thorchain endpoints at ninerealms while our nodes resync.
Dont revert this PR as it includes a fix to move the `lcd/` path into .env
NA
Risk of broken trades, sends, receives, etc for thor, utxo, evm
Check trades, sends, receives, etc for thor, utxo, evm
quotes working
trades working
> fix: [dont revert, patch] point prod thorchain endpoints at ninerealms

- .github/workflows/add-issue.yml
This was borked for some time after the `projectV2` breaking change of GitHub API:
https://github.com/shapeshift/web/actions/workflows/add-issue.yml
N/A
None, this is only related to the CI ran when creating issues. Will only be able to see whether or not this is happy after this is merged and when creating a new issue.
- None
- None
- None
> fix: add-to-project action

- .env.app
- .env.private
Rectifies incorrectly configured api endpoints for thorchain unchained api for app and private environments.
NA
Low risk.
Check thorchain tx history etc is working as intended.
> fix: incorrect thorchain api endpoints for .env.app

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
- This makes the work gomes added for ledger verify address on trade.
closes #
This feature is behind the ledger feature flag so has no impact on prod.
When you click preview trade with a ledger connected you'll see this screen that forces the users to verify the addresses of the buy and sell assets.
once you have verified both addresses you'll be able to move to the next screen (confirm).
> feat: verify address ui

- .github/workflows/cloudflare.yml
- fleek.config.js
feat: add fleek deploy (#5491)
> chore: release v1.462.0

- src/context/WalletProvider/config.ts
Makes us blazingly faster
N/A
If I got the imports copypasta wrong, somewallets could be broken
- Do a sanity test of wallets connection and ensure we're still looking good.
- Diff looks good
- ☝🏽
> perf: lazy load all wallet routes

- src/context/WalletProvider/MobileWallet/components/MobileLoad.tsx
- src/context/WalletProvider/MobileWallet/components/MobileSuccess.tsx
Makes the mobile password flow great again
N/A
None, this was absolutely derp
- Mobile password flow is happy again, tested by ops
- ☝🏽 
- ☝🏽
> fix: mobile password

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/context/WalletProvider/config.ts
- src/hooks/useIsSnapInstalled/useIsSnapInstalled.tsx
- src/pages/Dashboard/DashboardSidebar.tsx
This PR:
- makes trade routes components lazy
- doesn't fire snap installation checks unless we're in the context of a connected wallet, which isn't demo
- doesn't render the trade component unless n the context of a connected wallet, **or** demo wallet
N/A
- Snap installation checks may be broken
- Swapper may not render when it should
- Swapper may be borked
- Do a smoke test of MM snap installation checks
- Do a smoke test of swapper
- Ensure swapper doesn't render until wallet is connected (i.e shouldn't render on locked MM, nor when the wallet is in enter password state)
- ☝🏽 
- ☝🏽 
- Native password - no swapper
- Native unlocked - swapper happy
- Locked MM - no swapper
- Unlocked MM - swapper happy
- Snap installed
- Snap uninstalled while MM is connected
- Snap installation check …
> perf: lazy trade routes

- scripts/generateAssetData/generateAssetData.ts
- src/context/AppProvider/AppContext.tsx
Ensures we don't "fetch" (or rather, load from the build), the 5ish Mb `generatedAssetData.json` if the asset slice is already populated. If it is, it means we've fetched all assets, and shouldn't:
- re-"fetch" again, or in this case, rather instantiate `AssetService`
- upsert, since this is effectively going to be a no-op, but is still going to come as a performance cost
N/A
Ensure assets are still loaded, either on a refresh, or on a fresh session with no cache
- See risks ☝🏽 
- See risks ☝🏽 
- See risks ☝🏽
> perf: skip assets fetching if already in state

- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/context/AppProvider/AppContext.tsx
- src/lib/swapper/swapper.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/types.ts
- src/state/apis/swappers/swappersApi.ts
Same rationale as https://github.com/shapeshift/web/pull/5518 - avoids us instantiating AssetService, with the perf consequences of it, rather consumes state.
N/A
Swapper might be borked, do a sanity smoke test
- See risks
- ☝🏽 
- ☝🏽
> perf(swapper): don't instantiate AssetService

- src/state/slices/assetsSlice/assetsSlice.ts
Now that we're only getting assets once, this is definitely redundant, and introspecting cache is a useless run that could be done directly in `getAssets` body
N/A
Assets might be borked, test accordingly
- Assets are still loaded and displayed properly after a cache clear
- ☝🏽 
- ☝🏽
> feat: upsert in getAssets body vs. onCacheEntryAdded

- src/lib/investor/constants/erc20-abi.ts
- src/lib/investor/investor-idle/constants/idle-cdo-abi.ts
- src/lib/investor/investor-idle/constants/idle-strategy-abi.ts
- src/lib/investor/investor-idle/constants/idle-token-v4-abi.ts
- src/lib/investor/investor-idle/constants/ss-router-abi.ts
- src/lib/swapper/swappers/ThorchainSwapper/evm/routerAbi.ts
No runtime changes here, just fixing a relic from `lib` days by no longer `/* eslint-disable */`ing our ABIs.
N/A
Very small.
None required, if CI passes we should be good to go.
☝️
☝️
N/A
> chore: lint abis

- src/components/MultiHopTrade/hooks/quoteValidation/useQuoteValidationErrors.tsx
Fixes the "No receive address" errored state happening when attempting to get a quote in Ledger without the receive address app opened.
N/A
None, isolated to Ledger under flag
- With the Ledger flag enabled, get a trade quote on any cross-chain pair (e.g UTXO -> RUNE)
- Make sure that the app you have opened on your device is either none (app selection screen), or any app other than the receive asset one
- Ensure you can preview trade and don't see "No receive address for <asset>"
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: ledger "no receive address"

- scripts/release.ts
Handle special chars in release script.
N/A
Small
Releases with unsupported chars should no longer break the release script.
Nothing for ops to test.
☝️
☝️
N/A
> fix: handle special chars in release script

- src/state/slices/opportunitiesSlice/resolvers/thorchainLending/types.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainLending/utils.ts
This PR adds utils for:
- getting a loan opening quote
- getting a loan closing quote
- getting all lending positions
- finding a position for an AccountId/AssetId combination, introspecting all account addresses for UTXOs if necessary
N/A
None. This isn't consumed anywhere yet.
None
- Logic looks sane
- None
> feat: thorchain lending utils

- package.json
- src/AppProviders.tsx
- src/hooks/useRouteAssetId/useRouteAssetId.ts
- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/LendingPage.tsx
- src/pages/Lending/Pool/Pool.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainLending/types.ts
- yarn.lock
Does what it says on the box - wires up THORCHain lending "My Loan Info" section with actual data from THOR API:
- Collateral Balance
- Collateral Value
- Debt Balance
- Repayment lock in days
N/A
None as this is under flag
- With the lending flag on, ensure things are looking good in the "My Loan Info" section. Should zero out without a position.
- Open a loan from THORSwap and refresh the app, ensuring the loan data is displayed and looks sane
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/5d8230d0-f441-422d-a8a3-93e396188109
> feat: wire-up thorchain lending My Loan Info

- src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
- src/context/WalletProvider/Ledger/components/LedgerMenu.tsx
- src/context/WalletProvider/config.ts
Adds a Ledger connected menu to connect additional chains
N/A
None, isolated to Ledger under flag
- Connect Ledger
- Ensure clicking "Connect accounts" opens the Ledger accounts/chains selection menu again
- ☝🏽 
- ☝🏽
> feat: ledger connected menu

- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/test-data/responses.ts
- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainLending/utils.ts
Does what it says on the box - fetches the collateralization from THORChain /pool/<pool> endpoint and displays it as a percentage.
Additionally, and not directly related to this featureset, but kind of is:
- adds an Infinity stale time for the react-query queries for the time being, to avoid spamming the API during development. To be revisited (or not) once the wire-up is finished.
- adds new fields and updates wrong field types in `ThornodePoolResponse` to match the current response type
N/A
None
- With the lending flag enabled, CR looks good (compare against THORSwap UI)
- ☝🏽 
- ☝🏽
> feat: wire-up thorchain lending collateralization ratio

- src/components/TransactionHistoryRows/TransactionTrade.tsx
- src/components/TransactionHistoryRows/hooks.tsx
- src/state/slices/marketDataSlice/marketDataSlice.tsx
Fixes infinite loop and eventual app crash when booting the app on a page without tx history (i.e any page other than dashboard), and changing page.
The issue was caused by the tx history rows repeatedly dispatching price history requests which triggered re-load of the tx history rows, triggering re-request of price history and so on. The fix was to not fetch while an equivalent request was in flight.
NA
1. boot app on page other than dashboard (e.g http://localhost:3000/#/earn)
2. navigate to "My Wallet" (i.e http://localhost:3000/#/dashboard)
3. check app does not freeze and crash
> fix: app crash when changing page after booting from page without tx history

- fleek.config.js
Fixes the bad site slug that was used for fleek since they don't support the `.` in their slug names currently 
closes #
Very low, should not affect anything in production at the moment.
> fix: update slug for fleek

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainLending/types.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts
This PR:
- marks deprecated types from THOR swagger endpoints
- consumes their recommanded revamped version instead
- while at it, also does a tiny bit of consolidation, consuming `QuoteFees` in both savers and lending to keep things DRY. Domain unification still WIP as https://github.com/shapeshift/web/pull/5554 is in-flight, to avoid crazy merge conflicts.
closes https://github.com/shapeshift/web/issues/5555
None. The deprecated variants were somehow returning values that were totally off, so this will actually solve things, and doesn't introduce risks.
- Do a THORChain savers deposit/withdraw
- Ensure the shown slippage looks sane against THORSwap
- ☝🏽, though instead of THORSwap, we can also test that the slippage is equal to amount * (fees.slippage_bps / 10000)
- ensure the …
> feat: handle deprecated THOR types

- src/components/AccountDropdown/AccountChildOption.tsx
- src/components/AccountDropdown/AccountDropdown.tsx
- src/components/AssetSearch/AssetList.tsx
- src/components/AssetSearch/Chains/ChainCard.tsx
- src/components/AssetSearch/Chains/ChainList.tsx
- src/components/DeFi/components/PercentOptionsButtonGroup.tsx
- src/components/MultiHopTrade/components/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/AssetSelection.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
Improves rendering performance on tradeinput page.
progresses #5449
Low risk of broken UI and interactions for tradeinput.
> perf: more tradeinput rendering improvements

- src/assets/translations/en/main.json
- src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
- src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/context/WalletProvider/Ledger/components/LedgerMenu.tsx
Does what it says on the box - adds missing Ledger translations
N/A
None
- Ledger copies look good and @reallybeard is happy with the copies
- ☝🏽 
- ☝🏽
> feat: missing ledger translations

- src/components/Layout/Header/AppLoadingIcon.tsx
So this is actually displayed, nice and spinny *during* the event
closes #
> feat: extend doge day icon duration

- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/Borrow.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/LoanSummary.tsx
- src/pages/Lending/hooks/useLendingPositionData.tsx
- src/pages/Lending/hooks/useLendingQuoteQuery.ts
- src/pages/Lending/hooks/useLendingSupportedAssets.ts
closes #
- UTXO deposits are happy - note, you'll have to send to your 0th address as the reconciliation step hasn't been introduced yet
- selecting a different AccountId is working, and balance checks / deposits reflect said AccountId
- going from a happy quote to sad quote (e.g 0.001 BTC to 0.0001 BTC, adding a zero) doesn't keep stale values as quote as well as in loan summary
- ☝🏽 
Nothing to see yet
- gm UTXO deposits
> feat: thorchain lending improvements

- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/LoanSummary.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/hooks/usePoolDataQuery.ts
Because programmatic is better than hardcoded values - brings actual THOR data to the Available pools rows:
- Available lending pools
- Lending pools data
N/A
None - this is under flag
- Data looks the same in "Available Pools" and in the actual /pool/:pool route
- :point_up:
- :point_up:
https://github.com/shapeshift/web/assets/17035424/598a4d75-7434-44a7-a8d7-418992d6339e
> feat: wire-up thorchain lending Available Pools

- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/LoanSummary.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/usePoolDataQuery.ts
Because programmatic is better than hardcoded values - brings actual THOR data to the Your loans rows:
- Available lending pools
- Lending pools user data - note, this doesn't display the row in case the user data is 0 on said pool
Note: This doesn't yet render the header total, as we do not (yet) aggregate the balances over pools
N/A
None - this is under flag
- User data looks the same in "Available Pools" and in the actual /pool/:pool route
Note: Repayment lock is still hardcoded for now. The reason is this is *not* the pool repayment lock, but should be the user's repayment lock, which is effectively `open block height + LOANREPAYMENTMATURITY` converted to a unix timestamp using the 6.09s blocktime.
- :point_up:
- :point_up:
https://github.com/shapeshift/web/assets/17035424/a3378b4a-603 …
> feat: wire-up thorchain lending Your Loans

- src/components/Modals/Send/utils.ts
Pass input data in the correct field to allow for accurate gas estimation (EVM)
closes https://github.com/shapeshift/web/issues/5576
None
- Should be able to deposit native evm assets into thorchain savers
:point_up:
:point_up:
> fix: pass input data to gas estimation

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FirstHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/SecondHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/steps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/hooks/useLocaleFormatter/useLocaleFormatter.ts
Wires up ui elements of multi hop stepper to actual quote data.
NA
Includes very minor change to `useTradeExecution` hook which may present low risk of broken trade execution with multi hop toggled off.
Check the existing trade exectution (no multi hop)
☝️
☝️
> feat: wire up multi hop ui elements

- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/LoanSummary.tsx
- src/pages/Lending/Pool/components/Repay/Repay.tsx
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/hooks/useLendingCloseQuery.ts
- src/pages/Lending/hooks/useLendingQuoteQuery.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainLending/utils.ts
Does what it says on the box  - wires up the repayment part of lending.
N/A
None - this is under flag
- It is possible to select any THOR supported asset to repay debt
- Percentage slider is working and selects a percentage of debt, prorated to the selected asset 
- Slippage and gas fees are happy
This can be tested either with a monkey patch (will need to be slightly modified to accomodate your own loan's data) or with Frame.
- Monkey patch
- Revert and uncomment this guy d4d7c34ad1
- Frame
- Pick a debtful address which has reached maturity from `/pools/<pool>/borrowers` (the first in the list should do it) and connect it to Frame
- Test with any of the two solutions above
- Test with Frame
> feat: wire-up thorchain lending loan repayment

- src/state/apis/zapper/validators.ts
- src/state/apis/zapper/zapperApi.ts
Makes the schema great again, to ensure we're fetching UNI-V2 data
closes N/A
None
- Ensure no Zapper validator console spew 
- None
> fix: zapper spew

- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/LoanSummary.tsx
- src/pages/Lending/Pool/components/Repay/Repay.tsx
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/hooks/useLendingCloseQuery.ts
- src/pages/Lending/hooks/useLendingQuoteQuery.ts
- src/state/apis/zapper/validators.ts
- src/state/apis/zapper/zapperApi.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainLending/utils.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/utils.test.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/utils.ts
fix: replace viem getFilterLogs with getLogs (#5594)
fix: zapper spew (#5591)
feat: wire-up thorchain lending loan repayment (#5579)
> chore: release v1.474.0

- src/pages/Lending/components/LendingHeader.tsx
- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
Does what it says on the box - adds a query for your queries so we can query the aggregated queries. 
N/A
- Aggregated positions (debt/collateral) are matching the sum of individual ones
- ☝🏽 
- ☝🏽 
- Aggregated positions
- Individual positions
> feat: wire-up THORChain lending aggregated positions data

- packages/caip/src/adapters/banxa/index.ts
- packages/caip/src/adapters/mtpelerin/index.ts
- packages/caip/src/adapters/onramper/index.ts
Add arbitrum one on ramps with applicable assets where available
N/A
Low
- Should be able to buy arbitrum one and a handful of supported assets from our selection of fiat on ramps
:point_up:
:point_up:
> feat: add arbitrum one fiat on ramps

- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/tradeExecution.ts
- src/lib/swapper/types.ts
fix: thorchainSwapper check for EIP1559 support (#5613)
> chore: release v1.477.0

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FirstHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/SecondHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/steps.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/mockHooks.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
Actions code review feedback for the previous 6 PRs in this stack to reduce restacking effort and duplicate work (since at least one comment was resolved in a PR following).
Does not include any production facing chagnes.
NA
Low risk.
Not required.
> chore: action review feedback for multi-hop ui progression

- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useRepaymentLockData.tsx
This PR adds programmatic repayment lock for active positions - inactive ones / "Available Pools" routing still uses the network-defined repayment lock.
closes N/A
None, currently under flag
- With an active THORChain lending position, ensure the repayment lock looks sane in "Your loans" as well as clicking an active lending opportunity from "Your loans".
- Ensure clicking a lending opportunity from "Available Pools" shows the default (~30 days) lock.
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> feat: thorchain lending programmatic repayment lock

- src/assets/translations/en/main.json
- src/pages/ConnectWallet/ConnectWallet.tsx
- Updates copy on the splash page to align more
closes #
No risks
The copy has been updated on the splash screen.
> chore: update splash screen copy

- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
Smolish visual cleanups in lending:
- Removes the now useless input box that was used for demoing the view-layer
- Removes the assets swap icon - this isn't a trade pair and it isn't possible to swap direction here
N/A
None
- Things look good
- ☝🏽 
- ☝🏽
> feat: lending visual cleanups

- src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
Handles the case when a manual address doesn't require an on-device verification - still proceeds with the usual flow so users see their receive address at this stage (which is going to be shown at confirm step as yet another reminder), but clicking verify on the buy asset address in the case of manual receive address will instantly set it as verified, without on-device action needed.
closes https://github.com/shapeshift/web/issues/5633
Low - ensure address verification still behaves the same for other pairs
- Selecting ATOM as receive asset and entering a manual address doesn't break the receive flow, and the trade is able to go through as expected
- Other pairs (when using supported device assets) have their verification step behaving as usual i.e with on-device verification
- ☝🏽 
- ☝🏽
> fix: ledger verification when swapping to manual receive address

- src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
- src/components/Sweep.tsx
- src/features/defi/components/Deposit/Deposit.tsx
- src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/ThorchainSaversDeposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
- src/lib/utils/thorchain/hooks/useGetThorchainSaversDepositQuoteQuery.tsx
- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/Borrow.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowSweep.tsx
- src/pages/Lending/Pool/components/Repay/Repay.tsx
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/hooks/useGetEstimatedFeesQuery.ts
- src/pages/Lending/hooks/useIsSweepNeededQuery.ts
- src/pages/Lending/hooks/useLendingCloseQuery.ts
- src/pages/Lending/hooks/useLendingQuoteQuery.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
fix: thorchain limit account for liquidity fees (#5636)
fix: ledger verification when swapping to manual receive address (#5634)
feat: lending visual cleanups (#5629)
feat: abstract sweeper and use in thorchain savers deposit (#5614)
> chore: release v1.479.0

- .yarnrc.yml
`localhost` was giving ECONNREFUSED errors when verdaccio-ing, using `127.0.0.1` as a `npmRegistryServer` fixed it, this adds it to the unsafeHttp directive so we don't have to every time we verdaccio.
closes N/A
None
None
> feat: update .yarnrc unsafe directive

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
Fixes the multi-hop UI not rendering the incoming TX ID for a swap/bridge step in the multi-hop UI.
closes #5669
Low risk - behind feature flag
Not required.
> fix: render txids for multi-hop steps

- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
- src/pages/Lending/hooks/useLendingSupportedAssets.ts
vs. ETH and BTC only previously
closes N/A
The assets list might be broken in "Available Pools" and "Your loans"
- All THOR-supported assets are available as assets to borrow
- All THOR-supported assets are still available as assets to repay with
- ☝🏽 
- ☝🏽
> feat: lending support all thor-supported assets as borrow

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- scripts/generateAssetData/baseAssets.ts
- src/assets/translations/de/main.json
- src/assets/translations/es/main.json
- src/assets/translations/fr/main.json
- src/assets/translations/ja/main.json
- src/assets/translations/pt/main.json
- src/assets/translations/ru/main.json
- src/assets/translations/tr/main.json
- src/assets/translations/uk/main.json
- src/assets/translations/zh/main.json
- src/components/Layout/Header/Header.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/context/AppProvider/AppContext.tsx
- src/context/TransactionsProvider/TransactionsProvider.tsx
- src/lib/swapper/swappers/utils/test-data/assets.ts
- src/lib/utils/thorchain/lending.ts
- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
- src/pages/Lending/hooks/useLendingSupportedAssets.ts
- src/state/migrations/index.ts
- src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/portfolioSliceCommon.ts
- src/state/slices/portfolioSlice/selectors.ts
- src/state/slices/portfolioSlice/utils.ts
chore: update app translations (#5684)
fix: active step indicator for hops without allowance approval (#5671)
fix: only fetch transaction history once on load (#5673)
feat: lending support all thor-supported assets as borrow (#5675)
fix: lending close quote use repayment asset precision (#5667)
feat: gnosis blockscout urls (#5654)
> chore: release v1.482.0

- src/context/AppProvider/AppContext.tsx
fix: demo wallet and upsert (#5693)
> chore: release v1.483.0

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/AssetSummaryStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/DonationStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StreamingSwap.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/mockHooks.ts
- src/components/MultiHopTrade/hooks/useThorStreamingProgress/useThorStreamingProgress.tsx
Implements thorchain streaming swap progress UI with mock hook for testing and development
closes #5652
Low risk - behind feature flag
Not required, multi-hop is still work in progress
demo of streaming swap execution UI with example failed swap
completion summary renders final streaming swap status
> feat: implemented thorchain streaming swap progress for multi-hop ui

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- scripts/generateAssetData/baseAssets.ts
- src/lib/swapper/swappers/utils/test-data/assets.ts
- src/state/migrations/index.ts
The snowtrace.io dns change appears to have not gone through as described:
https://twitter.com/avax/status/1719005686196322525
https://twitter.com/ijaack94/status/1729130122547191922
Use the dev endpoint until things are resolved upstream
Low - no idea if/when they will shut down dev endpoint
- Avalanche links should resolve again
:point_up: 
:point_up:
> fix: update snowtrace domain

- src/components/Amount/Amount.tsx
- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/Borrow.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/LoanSummary.tsx
- src/pages/Lending/Pool/components/PoolStat.tsx
- src/pages/Lending/Pool/components/Repay/Repay.tsx
Add borrow/input dynamic components on quote.
Additionally, fixes the wrong debt update for borrows in `<LoanSummary />`
N/A
None
- Updated values on quote look sane
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/81649e45-e37d-4af1-929e-62fef5b5fba2
> feat: lending quote dynamic components

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- scripts/generateAssetData/baseAssets.ts
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/AssetSummaryStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/DonationStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StreamingSwap.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/mockHooks.ts
- src/components/MultiHopTrade/hooks/useThorStreamingProgress/useThorStreamingProgress.tsx
- src/context/AppProvider/AppContext.tsx
- src/features/defi/components/Deposit/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/ThorchainSaversDeposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/ThorchainSaversWithdraw.tsx
- src/lib/account/account.ts
- src/lib/swapper/swappers/utils/test-data/assets.ts
- src/state/migrations/index.ts
fix: update minimum transaction fee for cosmos network (#5698)
fix: savers fromAddress account type reactivity (#5696)
fix: update snowtrace domain (#5697)
fix: accounts/accounts metadata mismatch (#5695)
feat: implemented thorchain streaming swap progress for multi-hop ui (#5682)
> chore: release v1.484.0

- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.test.ts
Fixes unit tests failing due to import path attempting to use unmocked axios.create()
NA
Low risk - fixes unit tests only
Not required.
> fix: tests failing due to incomplete axios mocks

- src/assets/translations/en/main.json
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
... so users have an idea what that fee is about
closes N/A
None
- Tooltip is legible
> feat: thorchain lending consolidate tooltip

- src/components/FeeExplainer/FeeExplainer.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/context/AppProvider/AppContext.tsx
- src/context/TransactionsProvider/TransactionsProvider.tsx
- src/state/apis/snapshot/selectors.ts
- src/state/apis/snapshot/snapshot.ts
- src/state/reducer.ts
- src/state/store.ts
- src/test/mocks/store.ts
feat: optimistic voting power (#5747)
feat: refetch voting power on succesful swap Tx (#5746)
> chore: release v1.489.0

- src/assets/translations/en/main.json
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/components/LendingHeader.tsx
Requested by 9R after lending review - adds an empty state for "Your loans"
N/A
None
- When there are no active lending accounts (i.e empty "Your loans"), an empty state is displayed
- ☝🏽 
- ☝🏽
> feat: lending your loans empty state

- src/pages/Lending/hooks/useLendingSupportedAssets/index.ts
Avoids us showing Avalanche chain assets as available assets to borrow/repay with for KK , which does not support Avalanche.
N/A
None?
- Go to lending with KK
- Ensure Avalanche chain assets aren't available
- Switch to e.g MM and notice Avalanche assets are available
- Switch back to KK and notice they're not available once again 🎉 
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/d0032455-d040-482a-b45d-d702af600e9e
> feat: lending supported assets narrow by wallet supported chain

- src/components/Layout/Header/NavBar/NavBar.tsx
- src/components/Layout/Header/SideNavContent.tsx
Move secondary nav up and make the same size as the other nav items for mobile.
closes #5785 
Minimal risk
When opening the side nav on mobile you should see settings, feedback, and arkeo links right below the others and the same size.
> fix: rework sidenav for mobile

- src/pages/Dashboard/Portfolio.tsx
Discussed with @reallybeard  - ensures the dashboard chart makes it clear the charts are only wallet balance charts - earn (staked/rewards) is *not* included in charts and will never be. This currently produces a discrepency between the copy and amount shown, and the actual chart.
N/A
None
- Dashboard balance chart is shown as "Wallet Balance"
- Amount under "Wallet Balance" is only the wallet balance, *not* the net worth on top
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> feat: make dashboard "Net Worth" chart balance chart

- src/lib/market-service/idle/idle.ts
Makes the console great again
N/A
None
- Console is usable
- ☝🏽 
None
> chore: cleanup Idle log spew

- packages/caip/src/adapters/banxa/index.ts
Adds missing banxa assets from https://docs.google.com/spreadsheets/d/1KU6J1Hl4vxBTIWCwWdrFfSadNltuFheQRoJyPrd0LMQ/edit#gid=366537232 as an intersection of Banxa supported assets, our supported assets, and the ones that are actually not broken from that list (which is, not many).
closes https://github.com/shapeshift/web/issues/4283
None - tested all added assets
- DOGE, CAKE, YFI and RUNE are available as Banxa assets
- ☝🏽 
- ☝🏽
> feat: add missing banxa assets

- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
Fixes some shenanigans in repayment spotted with @0xApotheosis account - collateral AccountId wasn't passed, so highest balance AccountId would be used regardless of the account being selected in "Your Loans".
closes #
- This diff
Screen Recording 2023-12-07 at 11.31.26.mov
- Develop
https://github.com/shapeshift/web/assets/17035424/a7b3c7fe-8c18-495f-9e63-8e6242b277c2
> fix: collateral AccountId in "Your Loans"

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/mockHooks.ts
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowance.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useBlockNumber.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalNeeded.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/helpers.ts
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useApprovalTx.tsx
- src/lib/viem-client.ts
Implements ERC20 approval hooks for multi-hop UI. Includes a change to production facing approval checks which will require testing.
progresses #5653
Moderate risk of broken erc20 approvals (checking if they are required and executing them).
Check ERC20 allowance approvals are checked (i.e the app knows approval is required), and can execute an approval.
> feat: approval hooks for multi-hop trades

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/mockHooks.ts
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
Implements swap execution hook for multi-hop trades.
progresses #5653
Very low risk to production facing trades, but worth sanity checking in case something is broken.
Quick sanity check that old UI trades are still ok.
Tested single hop trade with approval on new UI using new hooks:
> feat: swap execution hook for multi-hop trades

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/TimeRemaining.tsx
Hides the multi-hop ETA countdown when it reaches 0.
NA
Low risk
Not required, not production facing
The 0 time ETA should be hidden:
> feat: hide multi-hop countdown timer when it reaches 0

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/lib/swapper/constants.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/state/slices/tradeQuoteSlice/types.ts
1. Fixes lifi status updates on second up resulting in trade UI not completing after funds arrive.
2. Adds status update messages to multi-hop UI so users can see what's going on with their funds
NA
Low risk - not production facing
Not required, testing for multi-hop will be completed separately when toggling on.
Single hop example of status message
Ackchyual multi hop trade with status messages:
https://github.com/shapeshift/web/assets/125113430/4acc6bce-0050-4595-8d38-939a777502d4
> fix: several multi-hop fixes and improvements

- src/components/Modals/NativeOnboarding/components/OnboardPager.tsx
Add missing key to `OnboardPager`.
N/A
Very low.
Console will no longer throw a key error during Native onboarding.
☝️
☝️
N/A
> fix: add missing onboarding key

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
Fixes inability to get quotes with rune as the sell asset
NA
Low risk.
Check can trade on rune as the sell asset.
> fix: unable to get quotes for rune

- src/lib/swapper/swappers/ThorchainSwapper/utils/longTailHelpers.ts
Correctly catch on trades to RUNE.
Current production issue.
Small.
We should be able to trade into RUNE again.
☝️
☝️
N/A
> fix: catch on trades to RUNE

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/longTailHelpers.ts
fix: unable to get quotes for rune (#5843)
fix: catch on trades to RUNE (#5849)
> chore: release v1.498.0

- src/components/MultiHopTrade/components/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/AssetSelection.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowance.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useBlockNumber.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalNeeded.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/helpers.ts
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Approve.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/swapper/swappers/ThorchainSwapper/utils/useRouterContractAddress.ts
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
fix: unable to trade on non-evm assets on multi-hop ui (#5847)
fix: thorchain savers borked withdraws (#5856)
fix: broken error message for savers withdrawls (#5855)
fix: add a loading state to the asset dropdown (#5846)
> chore: release v1.500.0

- package.json
- yarn.lock
chore: bump wagmi resolution to 1.4.12 (#5863)
> chore: release v1.502.0

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
Absolute derp
closes https://github.com/shapeshift/web/issues/5873
None, this was absolutely wrong.
- THORChain savers withdraw for native EVM assets (THOR, ETH, BNB on BSC) are happy
- ☝🏽 
- ☝🏽
> fix: thor native evm assets withdraws

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/AssetSummaryStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/types.ts
Adds translation wrappers for all hardcoded multi-hop text.
closes #5768
closes #4733
Low risk.
Check translations are wired up correctly in multi-hop UI, including swaps, bridges, approvals etc. Broken wiring will present as text with `%{XYZ}` percent symbol and braces
> feat: translation wrappers for multi-hop text

- src/lib/utils/thorchain/lending.ts
- src/lib/utils/thorchain/lending/types.ts
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/hooks/useLendingCloseQuery.ts
fix: make THOR repayments great again (#5898)
> chore: release v1.507.0

- src/lib/swapper/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/longTailHelpers.ts
Reduce longtail network calls by implementing local sorting on the pool assets, as per https://github.com/shapeshift/web/pull/5870#discussion_r1431247714.
https://github.com/shapeshift/web/pull/5870#discussion_r1431247714
Low
Perform a long-tail swap and ensure it still executes.
☝️
☝️
N/A
> perf: reduce longtail calls

- README.md
Update the README to include information on the developer workflow for MixPanel.
N/A
N/A
N/A
N/A
N/A
> chore: add MixPanel info to readme

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
gm, It's your classic "rugged by precision" PR.
closes N/A
None, this was rugged - ensure this displays consistently
- Type a small amount to withdraw that's valid (more than minimum) but small enough to trigger a dangerous withdraw warning. The amount should have a high number of significant digits e.g ETH 0.00123456789 withdraw
- Ensure the dangerous funds warning is displayed
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: dangerous withdraw warning precision rug

- README.md
For completeness, add reference to the `REACT_APP_FEATURE_MIXPANEL` flag.
N/A
N/A
N/A
N/A
N/A
> chore: more mixpanel readme info

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
Ensures we don't estimate fees too early, when we don't have an UTXO from address yet. This is not a runtime issue, but effectively means we currently have an error that may be misleading in case things fail, potentially hiding the real issue.
- relates to, but doesn't close https://github.com/shapeshift/web/issues/5807
None - if this is a problem, we have much bigger problems.
- UTXO deposits are still happy (tested with DOGE)
- ☝🏽 
- ☝🏽
> feat: cleanup savers deposit confirm error spew

- src/context/TransactionsProvider/TransactionsProvider.tsx
Fixes savers balances not updating after deposit/withdraw by actually awaiting the THOR status polling.
closes https://github.com/shapeshift/web/issues/5933
None, this was broken
- Deposit/withdraw from savers
- Ensure the balance updates after the deposit/withdraw is displayed as confirmed
- ☝🏽 
- ☝🏽 
- Initial savers balance
- Updated balance
https://github.com/shapeshift/web/assets/17035424/7b75c9c0-b93a-4e14-8f4b-35c429642025
> fix: savers balance not updating after THOR completion

- react-app-rewired/index.ts
Showing our headers and CSPs every time we start the app locally adds negative value.
rm?
N/A - DX.
Aw low as can be.
N/A
N/A
N/A
🙅
> chore: remove csp logs

- .yarn/patches/react-scripts-npm-5.0.1-d06bd2d5ad.patch
- package.json
- packages/caip/package.json
- packages/chain-adapters/package.json
- yarn.lock
Axios calls from workspaces or packages should work again
Low - should work again
- Try to swap and make sure the network requests are working
:point_up: 
:point_up:
> fix: patch react scripts to support cjs files

- src/lib/utils/thorchain/lp.ts
- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/YourPositions.tsx
- src/pages/ThorChainLP/hooks/usePools.ts
- src/pages/ThorChainLP/hooks/useUserLpData.ts
- Fetches pools and user data from THOR API and massages it.
Note for unclaimed fees, TVL, 24h and 7d volume, there may be some follow-ups needed to improve the math WRT:
- rebalancing of the pool since deposit
- using the same 24h window as THORYield
- contributes to https://github.com/shapeshift/web/issues/5939 , though rebalanced data will still need to be tackled as a follow-up
N/A
- Data looks sane against THORYield / THORSWap
- ☝🏽 
- ☝🏽
> feat: wire-up THORCHain pools

- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/YourPositions.tsx
- src/pages/ThorChainLP/hooks/useUserLpData.ts
[fix: return value when no pool position data](https://github.com/shapeshift/web/commit/5f66d4d762cf97f695eac52dd652560da1b59fd4)
[fix: use unique key for pool list items](https://github.com/shapeshift/web/commit/dd652dfc0497b43ee31e82ece12ce024a85a6d85)
[fix: skeleton keys](https://github.com/shapeshift/web/commit/6fea1d27bafc6bf5c00532c505a2c2bf43a088b8)
Fixes some small issues with the LP pages.
Small, everything touched is behind a flag.
The errors above should no longer appear in the console.
☝️
☝️
N/A
> fix: lp cleanup

- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/PoolsPage.tsx
... and adds TODOs for multi-account support.
- contributes to https://github.com/shapeshift/web/issues/5939 , though doesn't close it until redeemable fees are wired up
None given the TODOs, multi-account risks have been identified, to-be-discussed with @reallybeard 
- Clicking a pool (whether you're active or inactive in said pool) in "Available Pools" properly routes to it 
- ☝🏽 
- None for now
- Active user position pool
- Inactive user position pool
> feat: wire-up "Available Pools" pool details routing

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/lib/mixpanel/types.ts
- src/state/apis/swappers/types.ts
- src/state/slices/swappersSlice/selectors.ts
Updates mixpanel tracking to include metadata possible to identify unsupported trade pairs and also known errors from the swappers.
Includes a fix to mixpanel tracking where it was never fired by RTK query (see comment).
Created an example report here:
https://mixpanel.com/project/2939369/view/3463265/app/boards#id=6360116&editor-card-id=%22report-49500559%22
closes #5829
Low risk
Check mixpanel `Quotes Received` events are being transmitted to mixpanel when quotes arrive in the UI. This can done in the network panel of the browser, or in mixpanel itself.
Note fix to `currentData` previously being permanently `undefined` due to presence of skip token (see comment)
Events being received by mixpanel:
Example report can aggregate and group unactionable quotes: …
> feat: instrument quote requests where no quotes are actionable

- src/lib/utils/thorchain/lp.ts
- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/Pool/components/PoolInfo.tsx
Adds 24h change tags and data to TVL, volume, and fees.
closes https://github.com/shapeshift/web/issues/5939
Small, isolated to LP feature flag.
Check that the values look sane. Note the absolute values and percentages both currently differ from THORYield, but our data appears to match that which we are receiving from the API. To investigate further...
☝️
Not required.
> feat: lp pool daily change data

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
Updates trade execution UI to display all available tx links for a given trade.
closes #5888
Low risk.
Check that all available tx links for a given trade are dislpayed in the UI, e.g lifi cross chain swap should have a tx link for the sending chain and another for the receiving chain. 
Not all trades will have more than 1 tx link.
The second tx link will arrive some time after the first one, if it becomes available during the trade.
Cross chain trade initially displaying the sell chain tx link
And then once the receiving tx link is received (when the trade is completed in this case), its also displayed:
> feat: display all available tx links for a given trade

- .github/PULL_REQUEST_TEMPLATE.md
Updates the risk section of this template to help with high risk PRs and adds the high risk label so we know 2 reviewers are req.
closes #
NA
> chore: add risk comments

- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/state/apis/swappers/swappersApi.ts
- src/state/slices/common-selectors.ts
- src/state/slices/marketDataSlice/selectors.ts
Does the following:
- While market data is loading, the swapper asset list is sorted by name alphabetically
- After market data arrives, sorts assets the same way as in production (user balance, market cap, name)
- Corrects loading state in swapper such that loading state is true while assets are still being loaded
- No longer refetches swapper supported assets based on asset sorting
progresses #5975
> perf: simplify swapper asset sorting for faster boot times

- src/components/TransactionHistoryRows/TransactionDetails/TransferColumn.tsx
Fix regression on the transfer column title introduced in https://github.com/shapeshift/web/pull/5994
N/A
None
- Transaction row transfers should be titled `From` and `To` again
:point_up:
:point_up:
Prod:
Fix:
> fix: transfer column title regression

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
Fixes duplicate tx links in trade execution. Also fixes potentially incorrect defaultExplorerBaseUrl for the buy tx link.
NA
> fix: duplicate tx links

- .github/PULL_REQUEST_TEMPLATE.md
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/components/TransactionHistoryRows/TransactionDetails/TransferColumn.tsx
- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidity.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityConfirm.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquityStatus.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/DepositType.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/PoolSummary.tsx
- src/state/apis/swappers/swappersApi.ts
- src/state/slices/common-selectors.ts
- src/state/slices/marketDataSlice/selectors.ts
feat: wire-up confirmed "Add Liquidity" quote (#6030)
fix: transfer column title regression (#6036)
feat: standalone "Add Liquidity" (#6028)
perf: simplify swapper asset sorting for faster boot times (#6007)
chore: add risk comments (#6029)
feat: display all available tx links for a given trade (#6026)
feat: sym & asym add LP quotes input and calcs (#6027)
> chore: release v1.520.0

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/TradeConfirm/ReceiveSummary.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/lib/getTxLink.ts
- src/lib/swapper/swappers/ThorchainSwapper/constants.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getL1quote.ts
Add longtail tags in UI:
N/A - small swapper improvement.
Small, some regression risk with labels and TX links.
- Check that quotes for longtail swaps show the correct labels, and that the confirm/execute screens correctly show the trade source.
- Check that TX links still works as expected.
☝️
☝️
See description.
> feat: add longtail source UI

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
fix: receive amount on confirm screen (#6066)
> chore: release v1.525.0

- src/assets/translations/en/main.json
- src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx
Does what it says on the box - apprends an "Ended" tag instead of prepending the APR for expired opportunities
closes https://github.com/shapeshift/web/issues/6071, unless @reallybeard wants to oil some expiration time in here
None, if this looks good, we're good
- Connect using the demo wallet
- Ensure old FOX Farming opportunities are properly tagged as ended, with no APR shown 
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> feat: hide APY and show expired tag for expired opportunities

- .github/PULL_REQUEST_TEMPLATE.md
updates risk section per COE to prompt engineer about on chain interactions 
closes #
> chore: update risk section

- .github/PULL_REQUEST_TEMPLATE.md
- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/TradeQuoteContent.tsx
- src/pages/ThorChainLP/queries/hooks/useUserLpData.ts
chore: update risk section (#6099)
fix: lp data on refresh/direct navigation (#6092)
fix: completely borked quote percentage differences (#6090)
> chore: release v1.529.0

- scripts/generateAssetData/baseAssets.ts
- src/state/migrations/index.ts
Coingecko is drunk and doesn't differentiate between Beacon and Smart Chain, and happens to use the Beacon chain icon. Fixes this by using trustwallet/assets flavor, which has the correct icon for BSC. 
N/A
This regenerates assets fully, ensure everything still looks sane assets data wise.
None 
- BNB on BSC icon is happy and looks like the screenshots below
- Other assets still look sane
- ☝🏽 
- ☝🏽
> fix: bnb on BSC icon

- scripts/generateAssetData/baseAssets.ts
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/PoolSummary.tsx
- src/pages/ThorChainLP/components/LpType.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
- src/state/migrations/index.ts
fix: bnb on BSC icon (#6114)
feat: lp UI & UX improvements (#6111)
> chore: release v1.531.0

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getL1quote.ts
Corrects the processing of quoted thorchain receive amounts and protocol fees.
relates to https://github.com/shapeshift/web/issues/6120
This change is high risk. While the production amounts are currently inaccurate, we need to take extreme care to ensure that the fix is actually correct.
Check thorchain quoted amounts are correct, and the amounts received are in agreedment with the amounts quoted.
> fix: corrections to thorchain swapper receive amounts and protocol fees

- src/components/MultiHopTrade/components/TradeInput/components/RecipientAddress.tsx
Trims off whitespace when setting the recipient address.
NA
closes #
Low risk.
Check addresses with spaces or whitespace still get quotes.
> fix: trim whitespace when setting manual receipient address

- src/context/AppProvider/AppContext.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/pages/Accounts/AddAccountModal.tsx
- src/state/slices/portfolioSlice/portfolioSlice.test.ts
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/selectors.ts
Attempts to fix issue where multiple wallet balances appear for the currently connected wallet.
closes #6116
Moderate risk of incorrect account data such as balances for the currently connected wallet.
> fix: explicitly pass wallet device id when setting accounts

- src/assets/translations/en/main.json
- src/pages/ConnectWallet/ConnectWallet.tsx
- This removes an old translation that was showing on mobile
closes https://github.com/shapeshift/web/issues/6172
This only shows on the mobile app, so to see it you'll need to get to the connect wallet page on the mobile app. And there should be no reference to 100% free.
> chore: update copy for mobile connect page

- src/context/WalletProvider/WalletProvider.tsx
Ensures https://github.com/shapeshift/web/pull/6173 hotfix is present into develop until a new release is cut
closes #
> feat: merge remote-tracking branch 'origin/main' into develop

- src/components/MultiHopTrade/hooks/useIsTradingActive.tsx
- src/react-queries/index.ts
- src/state/apis/swapper/swapperApi.ts
And use the new `isTradingActive` query for consistency and freshness guarantees instead.
N/A
- Swapper halted checks could be borked, test accordingly
- Swapper halted checks are still working, i.e with DOGE halted at the time of writing and other pools being active
- ☝🏽 
- ☝🏽 
- DOGE pool is still detected as halted
- Other pools aren't wrongly detected as halted
> feat: remove swapperApi's getIsTradingActive

- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/longTailHelpers.ts
- src/react-queries/index.ts
Fixes thorchain longtail swap regressions from PRs:
- https://github.com/shapeshift/web/pull/6153 (wrong router address)
- https://github.com/shapeshift/web/pull/6167 (`isTradingActive` throw short circuit)
Adds explicit `aggregator` variable for longtail swaps and no longer throws on `isTradingActive`
https://discord.com/channels/554694662431178782/1206761097479200798/1206849965209550879
Medium
- All thorchain actions
- Extra focus on Longtail to L1 swaps (EVM)
- Ensure longtail to l1 swaps on thorchain are working again
- Regression test remaining thorchain feature set (l1 swaps, savers, lp, etc)
:point_up:
:point_up:
> fix: longtail swap regressions

- src/assets/translations/en/main.json
Removing a duplicate JSON key recently introduced in the English copies. "Available" was already available in the common strings 🤣 
Existing key:
https://github.com/shapeshift/web/blob/f612ccdc9ef87726798d8e6efb68de3500e0ad66/src/assets/translations/en/main.json#L54
No risk.
None.
The "Available" text for "Pools" should still be displayed as it was before.
☝️ 
☝️
> chore: remove duplicate available copy

- src/state/migrations/index.ts
Clears portfolio cache following https://github.com/shapeshift/web/pull/6156 - ensuring all clients have fresh unborked data. Reported by Tyler still encountering the bug due to stale cached data, whereas a fresh browser session would have the issue fixed.
N/A
Low, though technically high diff-wise since this touches portfolio, ensure everything looks good against prod - #6156 changes will be propagated to all clients
- Portfolio looks good against prod, without any stale portfolio shenanigans across wallets
- To be tested by Tyler who's currently experiencing this on prod
This diff (left) vs prod (right)
> feat: clear portfolio migration

- src/assets/translations/en/main.json
- src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
Disables FOXy deposits, while allowing users to claim/withdraw.
closes #6178
None
- FOXy deposits are now disabled.
- ☝🏽 
- ☝🏽
> feat: disable foxy deposits

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
NA
Low risk, only changes the value being displayed and no logic.
Check the rate being displayed is correct, especially for lifi multi-hop quotes
Issue:
Fixed:
> fix: incorrect rate displayed on trade quotes

- src/pages/ThorChainLP/Pool/Pool.tsx
See https://github.com/shapeshift/web/pull/6168#issuecomment-1947345126:
> Dead click when clicking Trade
N/A
Low to none
- Ensure clicking trade routes to a trade route with the pool's asset pre-populated on the buy side (from ETH for most assets, and from FOX for the specific case of ETH)
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/fd131986-714f-46a0-9ba6-0bf4f498319d
> feat: thorchain lp trade button routing

- .env.app
- .env.dev
- .env.develop
- .env.e2e
- .env.private
- react-app-rewired/headers/csps/chains/cosmos.ts
- src/config.ts
Use nownodes proxy endpoints for supported chains. Also remove unused `REACT_APP_COSMOS_NODE_URL`.
Affected Chains:
- Arbitrum
- BNB Smart Chain
- Ethereum
- Polygon
Unaffected Chains:
- Arbitrum Nova
- Avalanche
- Gnosis
- Optimism
- Thorchain
Low
- RPC calls to nownodes endpoints should still work
:point_up: 
:point_up:
> chore: point to nownodes for supported chains

- .env.app
- .env.private
Point to nownodes endpoints in prod environments.
Low
- Ensure rpc calls still work for all nownodes endpoints
:point_up: 
:point_up:
> chore: cut over nownodes prod

- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/utils/helpers/helpers.test.ts
- src/lib/swapper/swappers/utils/helpers/helpers.ts
- src/state/apis/swapper/helpers/validateTradeQuote.ts
1. Fixes issue where cowswap quote sell amounts are being rounded to 16 significant figures, resulting in sell amounts higher than user input.
2. ~~Also fixes issue where we were passing thru the sell amount rather than using the quoted sell amount which was bypassing validation on sell amounts.~~
With the above addressed, the threshold "fudge factor" for sell amount validation can now be removed 🍻
closes #6269
Low risk.
Affects cowswap quotes and validation
Ensure cowswap quotes come back as valid (no errors). The errors you'll see are "unable to fetch a trade quote", which indicates possibly one of the following:
* the quoted sell amount was higher than user …
> fix: remove rounding of cowswap sell amounts

- .env.develop
The dev thorchain coinstack is currently re-indexing midgard.  Use prod endpoint for https://develop.shapeshift.com as to not block LP testing until synced.
N/A
None
Thorchain endpoints will work again
:point_up: 
:point_up:
> chore: point develop to prod thorchain

- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/LpType.tsx
This PR:
- Makes "Add Liquidity" in pool page and asym side change happy again 
While reverting this as a last commit of https://github.com/shapeshift/web/pull/6278, this does bring back the two bugs noted in the PR, which should be tackled separately in a follow-up PR.
N/A
None, this reverts a broken part of a PR, and brings back two noted issues with the PR, to be tackled today as immediate follow-ups.
See https://github.com/shapeshift/web/pull/6278
- ☝🏽 
- ☝🏽
> fix: revert "use active opportunity on wallet switch"

- src/components/FeeExplainer/FeeExplainer.tsx
- src/components/FeeExplainer/FeeSliders.tsx
- src/components/MultiHopTrade/components/FeeModal/FeeBreakdown.tsx
- src/components/MultiHopTrade/components/FeeModal/FeeModal.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/context/AppProvider/AppContext.tsx
- src/context/TransactionsProvider/TransactionsProvider.tsx
- src/lib/fees/model.test.ts
- src/lib/fees/model.ts
- src/lib/fees/parameters/index.ts
- src/lib/fees/parameters/swapper.ts
- src/lib/fees/parameters/thorchainLp.ts
- src/lib/fees/parameters/types.ts
- src/lib/fees/utils.ts
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/state/apis/snapshot/selectors.ts
- src/state/apis/snapshot/snapshot.ts
- src/state/migrations/clearSnapshot.ts
- src/state/migrations/index.ts
- src/state/selectors.ts
- src/test/mocks/store.ts
This PR:
- splits votingPower in the slice into voting power by model
- adds and consumes fee curve parameters for THORChain LP
- fetches Snapshot API data with block params from THORChain LP fee curves parameters JIT
- contributes to https://github.com/shapeshift/web/issues/6179 - adds fee BPS logic for THORChain LP, but doesn't yet add the summary "ShapeShift fee" row. We will need to manually calculate this since we're not getting a THORChain quote. 
- FOX discounts are still happy for swapper
- FOX discounts are happy for THORChain LP
- Fully discounted
- No discounts
- No discounts
- Discounted
- Fully discounted
> feat: thorchain LP fee curve parameters

- src/assets/translations/en/main.json
- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/Pool/components/PoolChart.tsx
- src/pages/ThorChainLP/Position/Position.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/PoolSummary.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
- Fix the responsive table for the available pools list
- Combine the status and the APY into the tag
- Fix the divider showing on the collapse section when adding LP
- Fix the crypto amounts wrapping and causing weird layout shifts
- Added a coming soon section to the graphs on the pool page until we get those in.
closes #
Small risk
Things I outlined above, the LP section should be mostly good for mobile screen sizes.
> fix: responsive issues with lp pages

- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
closes N/A
None, this was obviously wrong
- Perform a THORChain symmetrical LP deposit for BCH
- Ensure the RUNE pairing Tx doesn't get refunded by THORSwap
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: thorchain lp RUNE BCH pairing Txs

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/test-data/responses.ts
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/hooks/usePoolDataQuery.ts
... and fix wrong condition for savers while at it, that made the Twitter CTA not display when it should
N/A
Low, as this *disables* lending and adds info div / Twitter CTA but could disable loans when actually not halted
- Both the ETH and BTC pools are currently showing a hard cap filled CTA
- It is impossible to continue with lending deposits when halted
- ☝🏽 
- ☝🏽
> feat: lending handle hard cap reached

- src/assets/translations/en/main.json
- src/lib/utils/thorchain/lp.ts
- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/Position/Position.tsx
- src/pages/ThorChainLP/YourPositions.tsx
- src/pages/ThorChainLP/components/PoolInfo.tsx
- src/pages/ThorChainLP/queries/hooks/useAllUserLpData.ts
- src/pages/ThorChainLP/queries/hooks/useUserLpData.ts
- src/pages/ThorChainLP/utils.ts
- Clean up and dry up user lp data hooks
- Add lp position type tag
- Clean up `getPoolShare`
- Fix `calculateEarnings` (now actually calculates earnings based on liquidity fees and block rewards though it is still averaged out across the entire position based on current pool share)
N/A
Med - refactors always bring a bit of extra risk due to amount of code moving around
- Ensure positions are still showing accurate data
- Note: the `Earnings` value will be different.
:point_up: 
:point_up:
Earnings display (Us|ThorYield)
LP Position Types
Balance and Pool Share (Us|RuneScan)
> refactor: thorchain lp positions

- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/components/AssetSelection/components/AssetChainDropdown/AssetChainRow.tsx
Improves readibility by explicitly displaying the asset symbol when different from the base implementation's.
closes https://github.com/shapeshift/web/issues/6300
Low to none
- W/ETH related assets are displayed with their respective symbol in swapper when different from the original implementation
- Other assets which have the same symbol on all chains are displayed as before
- ☝🏽 
- ☝🏽
> feat: improve swapper related assets UX

- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Does what it says on the box - ensures `0x` is stripped from Viewblock explorer link for EVM Txs.
N/A
None - only touches Tx history link
- Ensures viewblock link is happy for EVM Txs
- ^
- ^
> fix: thorchain LP deposit EVM Tx explorer link

- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Fixes two issues with EVM Txs fee estimation for THORChain LP deposit:
- One with missed base unit / crypto precision conversion
- Another with trying to estimate token deposits - we were assuming token *sends* (i.e `contractAddress` being defined) but at the same time doing a contract call, which produces invalid hex `data`. 
N/A
Low, this *fixes* fee estimation and cannot break things more as they were obviously wrong
- Fees estimation is happy for THORChain EVM *token* deposits at confirm step
- Fees estimation is happy for THORChain EVM *native assets* deposits at confirm step 
- ☝🏽 
- ☝🏽
> fix: thorchain LP evm fees estimation

- src/components/Layout/Header/DegradedStateBanner.tsx
- Use the network icon if available
closes #6337 
Low risk
When we are having troubling loading a specific network's data. The icon should should that network.
> fix: wrong network icon in degraded state banner

- .env.app
- .env.dev
- .env.develop
- .env.private
Nownodes ethereum nodes are back in sync. Point back to them for all environments
N/A
None
- Ensure ethereum rpc calls are using the nownodes endpoints again
:point_up: 
:point_up:
> chore: point ethereum back to nownodes endpoints

- src/state/apis/zapper/validators.ts
Update myzod schema to fix the console error when fetching zapper data
N/A
None
- Ensure there is no more console error from myzod related to zapper `blast` network
:point_up: 
:point_up:
> fix: zapper myzod schema error

- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
Does what it says on the box - sym withdraws are initiated with a RUNE Tx, so we need to add feature detection not to let wallets that do not support RUNE (e.g MM) continue with sym withdraws. 
N/A, spotted while testing THORChain LP.
Low, ensure sym withdraws are still available on native
- Sym withdraws are blocked on MM
- Sym withdraws are happy on native
- ☝🏽 
- ☝🏽 
- This diff
- Develop
> feat: thorchain LP RUNE wallet capability detection for sym withdraws

- src/components/Nfts/NftTable.tsx
- src/components/Nfts/hooks/useNfts.tsx
- src/components/StakingVaults/hooks/useFetchOpporunities.tsx
- src/context/AppProvider/AppContext.tsx
- src/pages/Dashboard/Dashboard.tsx
- src/pages/Dashboard/components/ProfileAvatar/AvatarSelectModal.tsx
Implements code review follow-up actions for #6327
relates to code review feedback from #6327
Low risk as this is just renaming things and wrapping `isLoading` into `{ isLoading }`
> chore: cleanup of useFetchOpportunities and useNfts hooks

- .env.app
- .env.dev
- .env.develop
- .env.private
There is currently origin headers on the nownodes rpc responses triggering cors errors. Point back to self hosted nodes until this can be resolved.
N/A
None
- Ensure avalanche rpc requests from web are working again
:point_up:
:point_up:
> chore: point avalanche back to self hosted nodes

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Discussed with @reallybeard, ensures fundus are safu until we support a proper UX for multi-account.
N/A
None
- Ensure it is not possible to select an account different than account 0 when depositing into THORChain LP
- ^
- ^
[uploading Screenshot 2024-03-06 at 19.52.49.png...]
> feat: thorchain LP disable account selection

- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Spotted during final LP testing https://github.com/shapeshift/web/pull/6344#issuecomment-1981969175
- Fixes the calldata for token withdraws to not try and intent a token transfer, which is obviously not valid for withdraws.
- Ensures we send some dust for token withdraws to ensure the withdraw Tx is seen by THOR
N/A
- Withdraw token Txs fees estimation is happy
- Withdraw token Txs broadcast fine
- Withdraw token Txs actually withdraw
- ^
- ^
- Sad fees estimation
- Happy fees estimation
- Happy Tx
- Happy Tx on the THOR side
> fix: thorchain LP token withdraws

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Two birds, one stone:
1. uses accurate gas estimation for THORChain LP deposits instead of relying on lending utils
2. fixes a bug where estimating gas for a token deposit would estimate the same value in native asset:
N/A, spotted during lending testing
Low, this theoretically makes gas *actually* accurate, though ensure gas estimation is still happy for EVM, UTXOs, and ATOM. RUNE is unaffected as it has its own gas estimation.
- Gas estimation is still happy for LP pool asset while depositing in THORChain LP
- `estimate` calls for token deposits have a 0-value
- ^
- Tokens deposits gas estimation is happy
- UTXOs gas estimation is happy
- ATOM gas estimation is …
> feat: thorchain LP accurate gas estimation

- .env.app
- .env.dev
- .env.develop
- .env.private
Cut back over to nownodes endpoints for avalanche now that the origin header issue has been resolved
N/A
Low
- Ensure rpc calls to avalanche are working as expected
:point_up: 
:point_up:
> chore: cut over to nownodes avalanche take 2

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Fixes a regression caused by #6375 where we early return if `!thorchainAccountId`, which is always going to be the case for MM.
closes https://github.com/shapeshift/web/issues/6395
None
- MM add liquidity is happy again
- ^
- ^
> fix: thorchain LP MM deposits

- src/pages/Lending/hooks/usePoolDataQuery.ts
Does what it says on the box - fixes missed THOR base unit conversion that's now obvious as the lending pools are active again.
N/A
None
- Lending caps look sane
- ^
- ^
THORSwap (left) against develop (up) and this diff (bottom)
> fix: lending vault caps

- src/components/EarnDashboard/components/PositionDetails/LpPositionsByProvider.tsx
- src/components/EarnDashboard/components/PositionDetails/StakingPositionsByProvider.tsx
- src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx
- src/components/Equity/EquityLpRow.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/AssetSummaryStep.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
- src/features/defi/providers/univ2/components/UniV2Manager/Withdraw/components/Withdraw.tsx
- src/hooks/useTxDetails/useTxDetails.ts
- src/lib/swapper/swappers/utils/test-data/cryptoMarketDataById.ts
- src/pages/ThorChainLP/queries/hooks/useAllUserLpData.ts
- src/pages/TransactionHistory/DownloadButton.tsx
- src/state/apis/fiatRamps/selectors.ts
- src/state/apis/swapper/helpers/getInputOutputRatioFromQuote.test.ts
- src/state/apis/swapper/helpers/getInputOutputRatioFromQuote.ts
- src/state/slices/assetsSlice/selectors.ts
- src/state/slices/common-selectors.ts
- src/state/slices/marketDataSlice/selectors.ts
- src/state/slices/opportunitiesSlice/selectors/combined.ts
- src/state/slices/opportunitiesSlice/selectors/lpSelectors.ts
- src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
- src/state/slices/portfolioSlice/selectors.ts
- src/state/slices/tradeInputSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/helpers.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/utils.test.ts
- src/state/slices/tradeQuoteSlice/utils.ts
Follow up on code review feedback to improve naming of market data around the app.
NA
Extremely low risk as this only renames things with zero changes to business logic.
General check of the app in case something totally unexpected happened in renaming.
Best to review commit by commit as its broken down logically
> chore: rename cryptoMarketData to marketData

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquityStatus.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
- src/pages/ThorChainLP/queries/hooks/useUserLpData.ts
- Disable back arrow on transaction broadcast
- Back arrow goes back one step (confirm), while go back button goes back to step one (input)
- Handle transaction error state
N/A
Low/Med - does update state management which can lead to edge case regressions
- Ensure thorchain lp deposits and withdrawals hide the back arrow after sign and broadcast and back arrow and go back button function properly
:point_up: 
:point_up:
> fix: handle back thorchain lp

- src/assets/translations/en/main.json
xDEFI is finicky so for now better words should help
resolves a bit of #6319 
low, is just copy.
- Yarn a local environment open
- click xDEFI
- make sure after pressing pair the modal is right
If someone wants to [help add line break](https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json?noredirect=1&lq=1), victory dance. Completely unecessary.
> chore: xdefi copy change

- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Fixed button load state after merge conflict regression in: https://github.com/shapeshift/web/pull/6402
N/A
None
- Sign transaction button should go to loading state after click for thorchain lp deposit and withdraw
:point_up: 
:point_up:
> fix: restore correct lp button loading state

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Does what it says on the box - ensures no stale fiat amounts on pool change.
closes https://github.com/shapeshift/web/issues/6412
Low 
- At THORChain Add liquidity input, change pool assets
- Ensure inputs get zero'd out and inputting a new value yields the correct market data
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/04276c2a-1d06-41f5-8222-97c74526b161
> fix: thorchain LP reset input amounts on OpportunityId change

- src/pages/ThorChainLP/components/PoolIcon.tsx
- relates to https://github.com/shapeshift/web/issues/6410?
None
- Token network icons are displayed across THORChain LP domain
- ^
- ^
[uploading Screenshot 2024-03-12 at 18.40.02.png...]
> feat: thorchain LP show token network icons

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Disable `Add Liquidity` button on empty amount. This was occurring after entering an amount and then deleting the amount, where the button would not go back to a disabled state.
N/A
Low
- Ensure `Add Liquidity` button is disable on empty amount (initial state or after deleting previous amount)
:point_up:
:point_up:
> fix: disable button on empty amount

- src/components/StakingVaults/Cells.tsx
- src/pages/Dashboard/components/AccountList/AccountTable.tsx
- Will truncate super long symbol names on the accounts table on dashboard
- Also fixes an issue with the name of assets, wrapping instead of truncating.
closes #
Low risk
Go to the Dashboard
The list of assets, should have symbols no longer than 6 characters. If they are longer than 6 characters they will be truncated.
Also names of assets in this same table should truncate if they are too long.
shots (if applicable)
> chore: truncate long symbol names

- src/components/Layout/Header/TxWindow/TxWindow.tsx
- src/components/TransactionHistory/TransactionHistoryList.tsx
- src/state/slices/txHistorySlice/selectors.ts
Does what it says on the box - adds skeletons if we don't have any Tx in store yet while Tx history is loading.
closes https://github.com/shapeshift/web/issues/6462
Low to none
- Ensure Tx history is properly shown as loading while loading
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/dccf7511-b048-44d6-b4fa-4a195e95a31b
https://github.com/shapeshift/web/assets/17035424/fa20ed4b-d2a1-49dc-a2c0-d9e6dc4ee4ba
> feat: tx history loading state

- src/components/StakingVaults/hooks/useFetchOpportunities.tsx
- src/react-queries/queries/opportunities.ts
- makes ETH opportunities great again
- fixes `enabled` and other options being defined in the wrong place and not working as they should
N/A, hotfix
None apart from a mild perf one in that we don't have an infinite gcTime anymore but the default 5mn. Given invalidation hasn't been explicitly made for this, this is a safety hatch rather than a risk but *does* carry an inherent perf one
- ETH opportunities are great again
- ☝🏽 
- ☝🏽
> fix: hotfix opportunities

- src/components/MultiHopTrade/components/TradeInput/getQuoteErrorTranslation.ts
- src/components/StakingVaults/hooks/useFetchOpportunities.tsx
- src/lib/swapper/swappers/CowSwapper/endpoints.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/react-queries/queries/opportunities.ts
- src/state/apis/swapper/helpers/validateTradeQuote.ts
- src/state/apis/swapper/types.ts
feat: cow fee model changes (#6455)
feat: thorchain LP handle fiat inputs (#6468)
fix: hotfix opportunities (#6471)
> chore: release v1.552.0

- src/pages/Dashboard/components/DashboardHeader/DashboardHeader.tsx
- src/state/slices/portfolioSlice/selectors.ts
We cannot get the math wrong either way:
- either we exclude earn opportunities from the assets/chains row which will inherently show a "wrong" balance (even more so if we also exclude earn dupes, which we can't because they *are* held assets), which will make the chains/asset rows "right" but the wallet total seemingly off and way lower
- or the other way around, we keep assets/chains rows as they are right now, and include staking amounts in the wallet total.
This is still off, but possibly the lesser of two evils as amounts will at least be totalling somehow correct?
The only downside to this is we're now back to square one where DeFi + earn is wrong.
closes https://github.com/shapeshift/web/issues/6038
More of a product one, see description
> What …
> feat: include defi opportunities in wallet total

- src/context/WalletProvider/MetaMask/components/Connect.tsx
- src/hooks/useIsSnapInstalled/useIsSnapInstalled.tsx
Does what it says on the box - ensures everything is nice and lazy to circumvent flaky `window.ethereum` injection in Android MM vs. iOS MM which is happy and seemingly stabler in that regard - see https://github.com/MetaMask/metamask-mobile/issues/3258 for more context.
closes https://github.com/shapeshift/web/issues/6334
Low - same flow as before but now lazy
**Note, this has been deployed to gome for ease of testing**
- Open the in-app MM browser in Android
- Ensure pairing works
- ☝🏽 
- ☝🏽 
- Prod
- This diff
> fix: pairing of MM in in-app Android browser

- src/lib/fees/parameters/swapper.ts
- src/lib/fees/parameters/thorchainLp.ts
- We need to update the threshold from 1M to 300k
closes #
high risk
This seemed like the correct place to change this. 
Open the fee modal on trade, you should see FREE once the FOX Holdings are over 300k.
applicable)
> fix: update fox discount threshold from 1M to 300k

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/types.ts
- src/components/Modals/Send/utils.ts
Handles missing L1 gas deduction in the send max branch of `buildSendApiTransaction`.
closes https://github.com/shapeshift/web/issues/6312
Low - if l1 gas limit and price is undefined, this will be a no-op against our current flow
- OP max sends are happy on MM and native
- ☝🏽 
- ☝🏽 
- MM
- Native
> fix: optimism max sends

- src/lib/swapper/swappers/CowSwapper/endpoints.ts
fix: make cow great again (#6514)
> chore: release v1.557.0

- src/lib/swapper/swappers/LifiSwapper/utils/getLifiChainMap.ts
Fixes the upstream call to `possibilities` Li.Fi endpoint.
- relates to https://github.com/shapeshift/web/issues/6485
None
- `possibilities` endpoint call is happy
- None
- develop
- This diff
> fix: lifi doesn't support arbitrum nova

- package.json
- src/lib/swapper/swappers/LifiSwapper/utils/getLifiChainMap.ts
- yarn.lock
Does what it says on the box - doesn't do anything in terms of fixing Li.Fi for token swaps, but always saner on a sane latest version.
- relates to https://github.com/shapeshift/web/issues/6485
Li.Fi, which is currently disabled in prod
- CI is happy
None
> feat: bump lifi sdk to latest

- src/pages/Lending/hooks/useLendingQuoteQuery.ts
Allows for lending deposits tracking.
N/A
Low but not none - if we get memos wrong, funds are at risk.
- THORChain lending deposits are still happy
- ☝🏽 
- ☝🏽 
- Memo is happy
- Tx is tracked on Runescan
> feat: thorchain lending deposits affiliate name memo

- src/state/apis/zapper/zapperApi.ts
closes #6487
None
- All demo wallet NFTs are fetched
- ^
- ^
Develop (right) vs. this diff (left)
> fix: zapper api filter out NFTs from unsupported networks

- src/context/WalletProvider/KeepKeyProvider.tsx
... by polling `wallet.getFeatures()`.
Note, that doesn't fix the race condition where the menu would be rendered while the pin is verifying on-device, however after fiddling with intercepting KK events and trying to modify our flow here, I didn't find any suitable event (except perhaps `PublicKey` which is emitted when unlocked, to be explored in a follow-up) that would work here.
Most likely what we'd need to fix the edge case above is be more lazy in what we render (i.e a subset of the current KK menu when loading, which consumes a subset of `useKeepKey` effects), in an effort to circumvent KK being derp and crashing if you ever try and attempt certain actions while the PIN is verifying. 
closes https://github.com/shapeshift/web/issues/6474
Low - at …
> feat: make kk menu more reliable

- packages/chain-adapters/package.json
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/arbitrum/ArbitrumChainAdapter.test.ts
- packages/chain-adapters/src/evm/arbitrumNova/ArbitrumNovaChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/gnosis/GnosisChainAdapter.test.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.test.ts
- packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/evm/routerAbi.ts
- yarn.lock
Follows-up on https://github.com/shapeshift/web/pull/6570, removing the dependency entirely now that we can rely on `viem` instead.
closes N/A
Low- if test fixtures are happy, we're most likely happy but sanity check EVM sends/swaps with native and MM as a paranoia check
- EVM sends and swaps are still happy with native and MM
- ☝🏽 
- ☝🏽
> feat: remove web3-utils from chain-adapters

- src/components/MultiHopTrade/components/SlippagePopover.tsx
Fixes a regression introduced by yours truly in https://github.com/shapeshift/web/pull/6584 - see https://github.com/chakra-ui/chakra-ui/issues/2843 for reference on why this doesn't work.
N/A
Low, this *is* a fix
- Slippage gear icon click is happy again for swapper
- Slippage gear icon hover is still showing a disabled tooltip for LP
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/6deac485-e9c2-47fd-9cc2-24c19c9792a5
> fix: swapper slippage popover trigger

- src/assets/translations/en/main.json
Updates two lines for the agree to terms on the snap. We were using account #1 should be account #0
closes #
When agreeing to the terms, it should say account #0 not account #1
> chore: update metamask terms

- src/components/Layout/Header/NavBar/KeepKey/ChangePin.tsx
Does what it says on the box - makes users able to change KK pin again.
closes https://github.com/shapeshift/web/issues/6484
None
- Clicking the PIN option in the KK menu is happy
- Changing the KK pin is happy
- ^
- ^
> fix: make KK pin change happy again

- scripts/release.ts
> chore: hotfix release v1.569.0

- scripts/release.ts
See https://github.com/shapeshift/web/pull/6594 for a sample PR.
This implements the hotfix path for release. For all intents and purposes it *is* similar to the regular release process so merging PRs is goign to be the same - simply merge release into main.
The opening part is what's different here. Note 1/2/3 which are different from the regular release PR process:
1. Have to be cleanly branched out off main. There is a first check that will check whether the branch is main (we *don't* want to ever run the risk of directly pushing main) and error if so, another that will ask devs to ensure they're cleanly branched off main (just a reminder here, nothing more), and a final sanity merge of origin/main into the current branch in case they weren't clean off it. All of these are additional …
> feat: hotfix release script

- src/state/migrations/index.ts
See https://discord.com/channels/554694662431178782/885616186623148062/1225164383982977125 for more details on the why of many migrations - tl;dr makes bigly wallets happy again and not crashy, at least for now.
N/A
None
- Do a little smoke test of the app as usual, though this literally just clears some slices and is akin to clearing your state before testing a PR
- ☝🏽 
- ☝🏽
> feat: many migrations

- src/lib/swapper/swappers/CowSwapper/CowSwapper.test.ts
- src/lib/swapper/swappers/CowSwapper/endpoints.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.test.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.ts
- adds CoW `getUnsignedEvmMessage` and `getFullAppData` tests to ensure we don't break things in the future there
- abstracts the affiliate fee and slippage deduction into common helpers since this is shared in both *our* quote and the second quote(ish) at message-building time
N/A
None - this actually adds tests to *avoid* regression risks 
- CI is happy
- ☝🏽 
- ☝🏽
> feat: cow quote/unsigned order build cleanup

- src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
Fixes non-deterministic issues with DeFi opportunities depending on the order of responses coming back - ensures we deep merge accounts so we don't end up in situations where one dispatch clears previous accounts entries.
- relates to https://github.com/shapeshift/web/issues/6608
Low - ensure DeFi user data shows no diff against develop after a cache clear - including Zapper read-only opportunities
- See risks
- ☝🏽 
- ☝🏽
> fix: deep merge opportunities accounts

- src/pages/Lending/Pool/components/LoanSummary.tsx
Fixes the Loan Summary's current repayment lock value, when repayment is unlocked.
closes https://github.com/shapeshift/web/issues/6641
None - encapsulated to the one place, and aligns logic to the position summary one on the pool page.
- Have an unlocked loan (or test with an injected address that has repayment unlocked, DM me for it)
- Ensure there is no negative number displayed as current repayment lock when getting a quote
- ^
- ^
- This diff (left) against develop (right) with an unlocked repayment
- This diff (left) against develop (right) with a locked repayment
> feat: lending loan summary repayment lock

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Does what it says on the box - we can't do the max thing so might as well disable it. See the closed https://github.com/shapeshift/web/pull/6643 for context
closes https://github.com/shapeshift/web/issues/6640
None
- Max option is disabled for THOR deposits
- ☝🏽 
- ☝🏽
> feat: thorchain lp disable max deposits

- src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositReducer.ts
- src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawReducer.ts
- src/state/slices/opportunitiesSlice/resolvers/foxy/index.ts
i.e makes it visible only if you do have an active opportunity
closes https://github.com/shapeshift/web/issues/6650
None - just adds an expired tag to FOXy
- After a full cache clear, test with an account that has active FOXy deposit and ensure you can see your position / the FOXy opportunity
- After a full cache clear, test with an account that  doesn't have a FOXy deposit and ensure you cannot see the FOXy opportunity
- ^
- ^
- No active FOXy opportunity
- Active FOXy opportunity
> feat: tag foxy as expired opportunity

- src/assets/translations/en/main.json
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/hooks/useLendingCloseQuery.ts
Adds allowance checks/step to THORChain lending repayments.
Note, since we refetch quotes often and asset ratios may fluctuate, a 5% buffer has been added to the amount to approve.
- relates to https://github.com/shapeshift/web/issues/6677, though doesn't add it for borrows just yet.
- Low, same old can't test unless you have a repay-able position (which I don't) meaning unless someone testing this can test it e2e, we're mostly interested in regressions testing here
- Ensure this brings no regressions to copies/confirm flow in THORChain lending - test with a frame-injected address  ensuring we can still go from input to preview for native assets
- If you have a …
> feat: thor repay approval step

- src/constants/chains.ts
Derp - diff is self-explanatory
N/A
None
- Arbitrum Nova chain selection option doesn't show as a placeholder FOX icon in buy asset chain selection
- ^
This diff against release (right)
> fix: arbitrum nova derp inverted flag check

- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
See https://github.com/shapeshift/web/pull/6676 / https://github.com/shapeshift/web/pull/6698
closes #
- See the original testing steps
- Ensure RUNE repayments click is happy and triggers a Tx (if you don't want to reset your repayment for the sake of testing this, test with snaps and ensure the Tx signing popup does pop up!)
> feat: revert of the revert of thor token repayments

- src/constants/chains.ts
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
feat: revert of the revert of thor token repayments (#6702)
fix: arbitrum nova derp inverted flag check (#6703)
> chore: release v1.576.0

- src/context/WalletProvider/Ledger/components/Chains.tsx
closes #6714
- Connect your Ledger to the app
- Click on this guy
- Ensure the "here" link opens in a new tab
- ^
- ^
> feat: open ledger thor instructions link in new tab

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
... since this would be hanging out forever otherwise.
closes https://github.com/shapeshift/web/issues/6712
Low to none
- Connect any chain/s in the Ledger connect modal, but *not* EVM
- Try to do either a sym (if you have RUNE connected too) or asym deposit
- Ensure the "Add Liquidity" button is *not* disabled
- ^
- ^
> fix: don't hang on voting power ready for wallets without eth support

- src/state/apis/zapper/validators.ts
Add `degen` to the zapper networks to silence current validation error.
N/A
- None
- Ensure there is no more console.error log
:point_up:
:point_up:
> chore: silence zapper validation error

- src/state/slices/txHistorySlice/txHistorySlice.ts
A regression was introduced by: https://github.com/shapeshift/web/pull/6501 where cached pending transactions were no longer updated to confirmed on subsequent app loads.
This restores that behavior to previous implementation and cleans up the upsert function(s)
N/A
Med - touches tx history state logic
- Broadcast a transaction and wait for the pending tx to show up
- Close the app to ensure the transaction doesn't get updated to confirmed and wait for the transaction to confirm on chain
- Reopen the app and note the existing pending transaction will get updated to confirmed correctly now
Note the edge cases listed in the code comment. This will not update ALL …
> fix: upsert transactions to invalidate pending state

- src/assets/translations/en/main.json
Correct  a small typo in "Trade of bridge your crypto" ("of" instead"or") in the new action menu for mobile.
None.
None
Check the "Trade or Bridge" menu entry description on mobile.
☝️ 
☝️ 
Before:
After:
> chore: typo in the action menu

- src/assets/translations/en/main.json
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
closes https://github.com/shapeshift/web/issues/6696
Low - ensure translations and copies look sane
- Try to repay your loan with any error getting a quote (amount too small, amount too small to return collateral, pool halted, repayment locked) and ensure the repay is now hidden vs. 0 previously
- Ensure hovering over the errored state button shows a longer explainer of the error
- ^
- ^
> feat: thor lending hide repay amount on error and add tooltip

- src/plugins/walletConnectToDapps/components/modals/connect/Connect.tsx
Does what it says on the box - gives us some visibility re: dApp connect errors
- relates to #6766
None
- Ensure Sentry is enabled for localhost with the appropriate Sentry.init monkey-patch
- Try and connect to an invalid wc url e.g wc:invalid@2
- Ensure pairing error is captured
- ^
- None
> feat: sentry capture wc dApps pair errors

- src/index.tsx
i.e uses HttpClient specific logic to configure targets, excluding Alchemy and Snapshot only for now.
While at it, also drops closed ws errors which are already quite spew-y.
N/A
- Ensure Alchemy failed XHRs do not go through
- Ensure other XHRs go through
- Ensure you do not see errors such as https://shapeshift-dao.sentry.io/share/issue/a5040ec1b10448ff8b5562f7cb95f617/
- ^
None
> fix: sentry actually deny URLs

- .github/workflows/sentry.yml
Adds a new `sentry` action with `getsentry/action-release@v1.7.0`, using the release PR title as the version.
See happy run: https://shapeshift-dao.sentry.io/releases/feat:%20sentry%20release%20action/?project=4507174994444368 / https://github.com/shapeshift/web/actions/runs/8971169980
N/A
Effectively low, technically high because this is an action for PRs to main, though if this is borked, releases are borked.
- Revert 4740cea46e02bde8c34240a61361ef124a1bfced and push the revert
- Ensure the CI runs to completion and the release is happy in Sentry
- None
> feat: sentry release action

- src/components/Layout/Header/NavBar/NavBar.tsx
Fixes massive red error in console related to incorrect props for Chakra stack in `NavBar`.
NA
Low-ish risk of incorrect layout in NavBar, though this likely resolved an existing issue with margin on the nav bar due to this being a regression.
Check the layout of the nav bar is correct.
> fix: incorrect stack props on NavBar

- .github/workflows/sentry.yml
a.k.a I should find a yaml plugin ASAP.
N/A
None
None - this doesn't include a monkey patch to test it, here goes nothing
> fix: sentry action syntax

- src/index.tsx
Does what it says on the box - see comment
N/A
None
- Errors are grouped in Sentry
- None
> feat: sentry disable custom fingerprinting

- src/context/WalletProvider/Ledger/components/Chains.tsx
Fixes dead click when connecting a ledger account.
NA
Low-ish risk, this was a missed case where we now have to enable accounts that are connected whereas we were disabling them previously.
Connect ledger wallet from initial app load.
> fix: ledger accounts not connecting

- src/components/ManageAccountsDrawer/components/SelectChain.tsx
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
- src/context/ModalProvider/types.ts
- src/context/TransactionsProvider/TransactionsProvider.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/context/WalletProvider/Ledger/constants.ts
- src/index.tsx
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/checkOutputTxConfirmations.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/parseThorBuyTxHash.ts
- src/pages/Accounts/Accounts.tsx
- src/state/apis/nft/utils.ts
feat: change 'add accounts' button to 'manage accounts' when account management is enabled (#6846)
fix: alchemy XHR error spew (#6852)
fix: no more thor tx status spam (#6856)
fix: use latest out tx for all checks (#6853)
feat: handle ledger account & chain management (#6847)
fix: ledger accounts not connecting (#6845)
feat: sentry disable custom fingerprinting (#6842)
> chore: release v1.591.0

- src/lib/utils/index.ts
- src/state/slices/opportunitiesSlice/mappings.ts
- src/state/slices/opportunitiesSlice/thunks.ts
See https://shapeshift-dao.sentry.io/issues/?query=fetchAllStakingOpportunitiesUserDataByAccountId&referrer=issue-list&statsPeriod=7d
N/A
- Staking opportunities still look sane
- ^
- ^
> feat: exhaustive CHAIN_ID_TO_SUPPORTED_DEFI_OPPORTUNITIES record

- package.json
- src/index.tsx
- src/utils/sentry/httpclient.ts
- yarn.lock
feat: sentry custom httpclient instrumentation (#6851)
fix: errorPredicate checks (https://github.com/shapeshift/web/pull/6873/commits/33f9d80da9f5c499cce6be9f5e42081bf8ca872f)
> chore: release v1.594.0

- src/components/Graph/PrimaryChart/PrimaryChart.tsx
- src/components/Graph/RainbowChart/RainbowChart.tsx
- src/pages/Buy/components/Sparkline.tsx
see https://shapeshift-dao.sentry.io/issues/245739/?query=is:unresolved&referrer=issue-stream&statsPeriod=30d&stream_index=22&utc=true
N/A
Low - this should *not* be a change at runtime, though not throwing could produce unintended results, test accordingly
- Do a sanity smoke test of dashboard total and rainbow charts, as well as the assets page sparklines and ensure things still look good
- ^
- ^
> feat: properly type chart accessors

- src/components/ManageAccountsDrawer/components/SelectChain.tsx
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
Disables the "Add a chain" button when all chains are added. Re-enables it when one is removed.
Note the "select chain" UI shows already added chains - this will be addressed separately.
NA
Low risk.
* "Add a chain" button is enabled until all supported chains are added
* "Add a chain" button is re-enabled when one is removed
Empty chains:
1 Chain added:
Transition when last chain is added:
https://github.com/shapeshift/web/assets/125113430/bc7e75da-b190-46a9-8237-a57a757734aa
Transition when a chain is removed:
https://github.com/shapeshift/web/assets/125113430/65425147-9a90-4e81-83db-f58e87ae3720
> feat: disable add chain button on account management when all chains are added

- src/components/ManageAccountsDrawer/components/SelectChain.tsx
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
Removes previously added chains from the "select chain" UI as a convenience to users.
NA
Low risk.
Check that adding a chain via account management hides it in the select chain UI.
Before
After
> feat: filter out added chains in select chain UI

- src/Routes/RoutesCommon.tsx
- src/assets/translations/en/main.json
- src/pages/rFOX/rFOX.tsx
- Adds the placeholder page for the new rFOX section.
closes #6894 
low risk
This is the placeholder for where we will have the component live for the time being. 
n/a
> feat: add placeholder page for rFOX

- scripts/generateTradableThorAssetMap/utils.ts
- src/AppProviders.tsx
- src/components/EarnDashboard/components/ProviderDetails/WalletStakingByAsset.tsx
- src/components/Graph/PrimaryChart/PrimaryChart.tsx
- src/components/Graph/RainbowChart/RainbowChart.tsx
- src/components/Layout/Header/GlobalSearch/GlobalSearchModal.tsx
- src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx
- src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx
- src/components/ManageAccountsDrawer/components/SelectChain.tsx
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
- src/context/WalletProvider/MobileWallet/components/MobileCreate.tsx
- src/context/WalletProvider/MobileWallet/components/MobileCreateTest.tsx
- src/context/WalletProvider/NativeWallet/components/NativeTestPhrase.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
- src/hooks/useInfiniteScroll/useInfiniteScroll.tsx
- src/index.tsx
- src/lib/globals.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.ts
- src/lib/utils/index.ts
- src/pages/Buy/components/Sparkline.tsx
- src/pages/ThorChainLP/utils.ts
- src/plugins/walletConnectToDapps/components/modals/connect/Connect.tsx
- src/state/slices/txHistorySlice/utils.ts
- src/utils/sentry/httpclient.ts
feat: filter out added chains in select chain UI (#6884)
fix: inability to withdraw expired fox farming (#6885)
feat: disable add chain button on account management when all chains are added (#6883)
feat: add handleClick safety to GlobalSearchModal (#6864)
feat: additional Array.prototype.split() safety (#6811)
feat: properly type chart accessors (#6875)
feat: fromOpportunityId additional error logging (#6865)
> chore: release v1.595.0

- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
Fixed the z-index so the related assets goes above the trade footer
closes #
small risk
When opening the chain dropdown on trade on desktop, the menu popover should go above the footer.
> fix: related asset going behind trade footer

- src/context/WalletProvider/MobileWallet/components/MobileLoad.tsx
- src/context/WalletProvider/MobileWallet/components/MobileSuccess.tsx
Since mobile doesn't support wallets other than native, meaning there is no wallet that could ever emit this, and consequently no provider that could ever remove these.
N/A, error spew
None
- Ensure connecting to a native wallet in the mobile app is still happy
> fix: don't try and remove accountsChanged and chainChanged events on mobile app

- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
Does what it says on the screenshot below.
closes https://github.com/shapeshift/web/issues/6922
None
- In THORChain lending repayments' asset selection row, unlocked collateral fiat amount is matching its crypto value
- ^
^
> fix: unlocked collateral asset selection fiat rate

- src/utils/sentry/httpclient.ts
To provide more context for debugging sentry events, add response body to event (which is now being returned with more detail from unchained)
N/A
Low
- Create a network error that returns a response body (ex. try to send more of evm asset than you have which will fail on gas estimation)
- Verify event is created in sentry with the response body attached (uncomment the localhost condition in `src/index.ts`)
:point_up: 
N/A
> chore: add response body to sentry event httpclient

- src/lib/utils/thorchain/memo/assertAndProcessMemo.test.ts
- src/lib/utils/thorchain/memo/assertAndProcessMemo.ts
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
i.e now that borrows are back for BTC, we wrongly enforce MinOut... but have no MinOut. This fixes it until we properly implement them i.e in https://github.com/shapeshift/web/pull/6753/commits/f5886b4293d28800f97291c7bb8d9a3907d3d8bb#diff-5e87973b126914e1aa408f3662707579b5c9f27a2a1bc58247627b5442f43f5e
closes https://github.com/shapeshift/web/issues/6945
Low - this *disables* MinOut checks so should make things safer (as in, being able to continue with a quote, not safer in terms of limit guarantees)
- Ensure you can proceed with BTC borrows e2e.
- ^
- ^
> fix: don't enforce minOut for borrows (yet)

- src/lib/utils/thorchain/memo/assertAndProcessMemo.test.ts
- src/lib/utils/thorchain/memo/assertAndProcessMemo.ts
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
Re-opened to target develop:
https://github.com/shapeshift/web/pull/6946
> Fix minout borrows

- src/assets/translations/en/main.json
- src/components/AmountSlider.tsx
- src/pages/RFOX/RFOX.tsx
- src/pages/RFOX/components/Unstake/Unstake.tsx
- src/pages/RFOX/components/Unstake/UnstakeConfirm.tsx
- src/pages/RFOX/components/Unstake/UnstakeInput.tsx
- src/pages/RFOX/components/Unstake/UnstakeStatus.tsx
- src/pages/RFOX/components/Unstake/components/UnstakeSummary.tsx
- src/pages/RFOX/components/Unstake/types.ts
Adds the unstake visual components for input, confirm and status.
closes #6897 
small risk
N/A just visual components no logic
> feat: add unstake visual components

- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
- src/components/StakingVaults/DeFiEarn.tsx
- src/pages/Accounts/Accounts.tsx
- src/pages/Accounts/AddAccountModal.tsx
- src/state/slices/common-selectors.ts
- src/state/slices/portfolioSlice/selectors.ts
Sorts the list of connected chains in the account management modal by usr currency balance and chain name. 
Replace `selectPortfolioChainIdsSortedUserCurrency` with a corrected version `selectWalletConnectedChainIdsSorted` which sorts the list of connected chainIds based on the sum of all account balances for a given chainId, rather than the most recently seen using a javascript `Set`.
closes #6926
Moderate risk as this replaces replace `selectPortfolioChainIdsSortedUserCurrency` with a corrected version `selectWalletConnectedChainIdsSorted` which attempts to do that same thing but handling multiple account balances for a given chain correctly.
> feat: sort account management list of connected chains by user currency balance and chain name

- src/components/AssetSelection/AssetSelection.tsx
- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
See https://jam.dev/c/161f8634-a56f-42ed-a152-441eee4751b1 for e2e walkthrough with full commentary.
This PR:
- Ensures related assets are properly narrowed down on lending borrows' collateral side
- Ensures related assets are properly narrowed down on lending repayments' repayment asset side
- Ensures disabled asset selection is reflected with its *related* asset selection fren also disabled. Note, the root cause has been tackled here so not only lending collateral unlocked is affected here, but also THORChain LP standalone "Add Liquidity" for the RUNE side. Though since there are no related assets for RUNE, this comes as no change.
closes https://github.com/shapeshift/web/issues/6913
Low - this makes things *less* dangerous.
Scrutinized `isReadOnly` …
> fix: thorchain lending narrow down/disable related assets

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- Fixes a bug where a Ledger would only ever fetch the first 2 accounts in the Account Management Drawer, regardless account activity
- Simplifies the account detection logic by using the `hasActivity` property, which is set:
- For EVMs: if the account has either fee asset balance or a nonce greater than 0.
- Fox UTXOs: if the balance, nextChangeAddressIndex, or nextReceiveAddressIndex is greater than 0.
- For Cosmos: if the balance or sequence is greater than 0.
N/A - discovered during pre feature flag enablement sanity checks.
Small - could bork ability for accounts with activity to be detected if implemented incorrectly, though accounts could still be added manually.
Adding wallet accounts via …
> fix: improve account detection logic

- src/assets/translations/en/main.json
- src/components/AmountSlider.tsx
- src/components/MultiHopTrade/components/TradeAmountInput.tsx
- src/pages/RFOX/RFOX.tsx
- src/pages/RFOX/components/Stake/StakeConfirm.tsx
- src/pages/RFOX/components/Stake/StakeInput.tsx
- src/pages/RFOX/components/Stake/StakeStatus.tsx
- src/pages/RFOX/components/Unstake/Unstake.tsx
- src/pages/RFOX/components/Unstake/UnstakeConfirm.tsx
- src/pages/RFOX/components/Unstake/UnstakeInput.tsx
- src/pages/RFOX/components/Unstake/UnstakeStatus.tsx
- src/pages/RFOX/components/Unstake/components/UnstakeSummary.tsx
- src/pages/RFOX/components/Unstake/types.ts
- src/pages/RFOX/types/index.ts
Does what it says on the box - e2e wire-up of RFOX unstaking.
closes https://github.com/shapeshift/web/issues/6898
Low - isolated to RFOX unstaking
- Unstaking is happy end-to-end
- The unstaking slider is originally set to 100%
- The min fiat amount is 0, and the max is your current balance
- Continuing with 0 unstaking is impossible
- Toggling between crypto and fiat is happy
- Not enough fee asset for Tx is correctly guarded against (kind of hard to test because of such low fees on Arb - the easiest is to stake, then send all your Arb ETH to another wallet using MM max send)
- New share of pool looks sane (i.e the more you increase the percentage, the lesser …
> feat: wire-up rfox unstaking

- .github/CODEOWNERS
See https://github.com/shapeshift/web/pull/2308 for reference, we should be able to just leverage the `Owners` group but:
This is a temp. workaround, to be reverted once seats shenanigans are tackled.
N/A
None
None
> feat: update CODEOWNERS

- src/state/migrations/index.ts
closes https://github.com/shapeshift/web/issues/7000
None
- Clearing the cache many times and refetching Zapper user data for the user in #7000 prompted zapper to force one of two hard things in software engineering.
Test with their Frame-injected wallet and ensure you cannot see any ghost DeFi balances anymore.
- ^
- ^
> feat: clearOpportunities migration

- .github/workflows/cloudflare.yml
- scripts/bootstrap-env.ts
- src/index.tsx
Does what it says on the box - @kaladinlight to confirm we don't need to manually configure Cloudflare subdomain
N/A
None
None
> feat: add neo env

- src/pages/RFOX/components/ChangeAddress/ChangeAddressStatus.tsx
- src/pages/RFOX/components/Shared/SharedStatus.tsx
- src/pages/RFOX/components/Stake/StakeStatus.tsx
- src/pages/RFOX/components/Unstake/UnstakeStatus.tsx
- Creates a new reusable status component for RFOX (stake, un-stake, and change address)
closes #6964 
mild risk
Confirm the status screens are correct on stake, un-stake and change address.
> feat: add re-usable status screen

- src/assets/translations/en/main.json
- src/components/AssetIconWithBadge.tsx
- src/components/TransactionHistory/TransactionTypeIcon.tsx
- src/pages/RFOX/RFOX.tsx
- src/pages/RFOX/components/Claim/Claim.tsx
- src/pages/RFOX/components/Claim/ClaimConfirm.tsx
- src/pages/RFOX/components/Claim/ClaimSelect.tsx
- src/pages/RFOX/components/Claim/ClaimStatus.tsx
- src/pages/RFOX/components/Claim/types.ts
Add rFOX claim scaffolding.
Contributes to https://github.com/shapeshift/web/issues/6899
Small, wiring only.
None
See video below - we should see a new "Claim" tab in rFOX. The components contain mocked values, and can be clicked through to the pending status.
☝️
☝️
https://github.com/shapeshift/web/assets/97164662/f36f492d-33b9-4065-9637-d4fbd596fc0f
> chore: add claim scaffolding

- packages/caip/src/adapters/junopay/index.ts
- packages/caip/src/adapters/mtpelerin/index.ts
- packages/caip/src/adapters/onramper/index.ts
- src/assets/translations/en/main.json
- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/context/WalletProvider/MetaMask/components/MetaMaskMenu.tsx
- src/lib/utils/time.test.ts
- src/lib/utils/time.ts
feat: add fiat ramp support for base network (#7035)
fix: show existing account ids in store (#7031)
feat: mm snaps multi-account management (#7023)
feat: formatSecondsToDuration handle sub-hour durations (#7016)
> chore: release v1.605.0

- src/pages/ConnectWallet/ConnectWallet.tsx
- src/pages/ConnectWallet/MobileConnect.tsx
Fixes connect buttons to allow multiline captions (for lower resolutions/longer texts).
closes #7061 
Low. Button formatting doesn't prevent their usage.
None.
Check the buttons on the connect page (mobile and non-mobile) and verify that they display without overflowing in all languages.
☝️ 
☝️ 
Multi line captions mobile
Multi line captions non-mobile (more extreme low width resolution example)
Single line works as before
> fix: connect buttons multiline

- src/pages/RFOX/components/Claim/ClaimConfirm.tsx
Use the new `useEvmFees` hook.
Relates to https://github.com/shapeshift/web/issues/6973 and https://github.com/shapeshift/web/issues/6803
Low.
Gas estimations for rFOX claims.
Check that gas estimates for rFOX claims still work as expected.
☝️
☝️
> feat: claim gas refactor

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/TimeRemaining.tsx
Ensures the app doesn't crash on undefined `dayjs.duration()` right after executing trade
closes N/A, spotted in develop as a regression introduced in https://github.com/shapeshift/web/pull/7093
None
- Trades *without* an ETA (e.g 0x) are still happy
- Trades *with* an ETA (e.g LiFi, THOR) are great again and don't crash the app
- ^
- ^
- Develop
- This diff
> fix: make swapper great again

- src/pages/RFOX/components/Claim/ClaimConfirm.tsx
- src/pages/RFOX/components/Claim/ClaimSelect.tsx
- src/pages/RFOX/hooks/useGetUnstakingRequestCountQuery.ts
- removes now useless `enabled` type-safety handled by `useEvmFees` itself
- adds new `useGetUnstakingRequestCountQuery` type-safe query hook
- contributes to https://github.com/shapeshift/web/issues/6965 (or closes, if we deem we don't need to refactor anything there, see https://github.com/shapeshift/web/issues/6965#issuecomment-2161642604)
- Ensure claim select is still happy
- ^
- ^
> feat: rfox claim cleanup

- src/assets/translations/en/main.json
- src/pages/RFOX/components/Faq/Faq.tsx
Does what it says out of the box, just updated the rFOX faq, check https://github.com/shapeshift/web/issues/6948#issuecomment-2163641487
partially #6948
Low risk
Just open the RFOX page and read the FAQ, please make sure every copies respect https://github.com/shapeshift/web/issues/6948#issuecomment-2163641487
n/a
n/a
> fix: update rfox faq

- src/assets/translations/en/main.json
- src/pages/RFOX/components/Claim/ClaimRow.tsx
- src/pages/RFOX/components/RewardsAndClaims/Claims.tsx
Tackles this guy: https://github.com/shapeshift/web/issues/7121#issuecomment-2164386811
>Claim modal says cooldown finished in 9 minutes when it should say "finishes in 9 minutes"
as well as the `THORChain` capitalization issue 
- closes #7121
None?
- Cooldown copy looks good in RFOX when cooling down, both on desktop and mobile
- `THORChain` is corectly capitalized in`You have successfully changed your THORChain Reward Address.` 
- ^
- ^
Tested against develop (right)
> fix: rfox cooling down period human

- src/lib/swapper/swappers/ThorchainSwapper/utils/longTailHelpers.ts
- Activate RUNE -> Ethereum Longtail swaps by adding a special case in `longtailHelpers`, RUNE isn't considered as a L1 so it needs it own case
Thanks @gomesalexandre for the hints to activate it
Here is a proof that it works: https://viewblock.io/thorchain/tx/EFC57AF8804ADFEA7BB472749F7785513BFF823BDFBA07D6D90508B17CF0DAF4
n/a
Not so risky, maybe medium as swap can be risky by nature?
Try to swap RUNE to SHIB for example
n/a
n/a
> fix: activate rune to longtail swaps

- src/pages/RFOX/components/Overview/Overview.tsx
- src/pages/RFOX/components/Overview/StatItem.tsx
- src/pages/RFOX/components/Overview/Stats.tsx
- src/pages/RFOX/hooks/useStakingBalanceOfQuery.ts
Implements this guy:
- relates to https://github.com/shapeshift/web/issues/6948
None?
- Total FOX staked balance looks sane
- ^
- ^
https://jam.dev/c/56b79992-e108-4ca0-98d2-4e3ca0b60057
> feat: rfox dashboard wire-up total staked

- src/assets/translations/en/main.json
- src/components/Acknowledgement/Acknowledgement.tsx
- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/context/WalletProvider/DemoWallet/DemoMenu.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/RFOX/components/Stake/StakeInput.tsx
- src/pages/RFOX/components/Unstake/UnstakeInput.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
fix: handle manage multi accounts for demo wallet (#7134)
fix: add streaming warning on stream swaps (#7165)
> chore: release v1.619.0

- src/components/Modals/NativeOnboarding/components/EasyToUse.tsx
Changes the import wallet flow route `/dashboard` to `/wallet`
Tested locally and it works out of the box.
closes  #7173 
Low risk
https://www.loom.com/share/cd88d1e7e414488c96cb2d846de14d35?sid=64e64a13-ec53-47a8-b280-91d205b077ba
Sanity check build if you want.
thanks @MBMaria
> fix: changing the route on the import wallet screen

- src/contracts/constants.ts
- src/pages/RFOX/hooks/useAffiliateRevenueQuery.ts
- src/pages/RFOX/hooks/useBlockNumberByTimestampQuery.ts
- src/pages/RFOX/hooks/useCurrentEpochRewardsQuery.ts
- src/pages/RFOX/hooks/useEpochHistoryQuery.ts
- src/pages/RFOX/hooks/useLifetimeRewardsQuery.ts
Implements the actual guts of `useEpochHistoryQuery` with actual block timestamps and affiliate revenue fetched from our affiliate index. Epochs are aligned with the logic described in the ticket (linked to DAO forum post).
closes #7170
Low risk as not production facing. Incorrect data from these hooks are a display concern only and and errors would eventually result in incorrect data being displayed only and would not affect user funds or application logic.
Currently untested and untestable.
Probably worth getting in untested to ease wiring of dashboard, which in turn will ease testing of these hooks.
> feat: implement useEpochHistoryQuery with actual epoch history

- src/components/DeFi/components/AssetInput.tsx
- src/components/Modals/NativeOnboarding/components/EasyToUse.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/contracts/constants.ts
- src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosEmpty.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingEmpty.tsx
- src/pages/RFOX/hooks/helpers.ts
- src/pages/RFOX/hooks/useCurrentEpochRewardsQuery.ts
- src/pages/RFOX/hooks/useEarnedQuery.ts
- src/pages/RFOX/hooks/useEpochHistoryQuery.ts
- src/pages/RFOX/hooks/useLifetimeRewardsQuery.ts
- src/pages/RFOX/hooks/useTimeInPoolQuery.ts
- src/pages/RFOX/types/index.ts
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
fix: infinit rerender loop on remove liquidity (#7184)
fix: changing the route on the import wallet screen (#7179)
fix: p tag descendants (#7176)
fix: swapper last step tag display quote receive address over wallet one (#7178)
refactor: simplify active trading (#7175)
feat: implement "my position" rFOX dashboard queries (#7162)
> chore: release v1.620.0

- src/assets/translations/en/main.json
- src/contracts/constants.ts
- src/features/defi/providers/cosmos/components/CosmosManager/Claim/CosmosClaim.tsx
- src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Claim/ClaimRoutes.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/ThorchainSaversDeposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/ThorchainSaversWithdraw.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/pages/RFOX/RFOX.tsx
- src/pages/RFOX/components/Claim/ClaimRow.tsx
- src/pages/RFOX/components/Claim/ClaimSelect.tsx
- src/pages/RFOX/components/RewardsAndClaims/Claims.tsx
- src/pages/RFOX/components/RewardsAndClaims/RewardsAndClaims.tsx
- src/pages/RFOX/hooks/useAffiliateRevenueQuery.ts
- src/pages/RFOX/hooks/useBlockNumberByTimestampQuery.ts
- src/pages/RFOX/hooks/useCurrentEpochRewardsQuery.ts
- src/pages/RFOX/hooks/useEpochHistoryQuery.ts
- src/pages/RFOX/hooks/useGetUnstakingRequestCountQuery.ts
- src/pages/RFOX/hooks/useGetUnstakingRequestQuery.ts
- src/pages/RFOX/hooks/useLifetimeRewardsQuery.ts
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/state/slices/opportunitiesSlice/selectors/selectors.test.ts
- src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
- src/state/slices/txHistorySlice/selectors.ts
fix: initial errored state on claims (#7182)
feat: staking deposit account improvements (#7177)
fix: first load lp deposit approval (#7190)
fix: dont display other wallet accounts in tx history degraded popover (#7188)
feat: rfox dashboard claim rows (#7150)
feat: implement useEpochHistoryQuery with actual epoch history (#7174)
> chore: release v1.621.0

- src/assets/translations/en/main.json
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/hooks/useLendingSupportedAssets/index.ts
- src/pages/Lending/hooks/usePoolDataQuery.ts
- Lending statuses were "Healthy" all the time, changed it to "Active" if the status is "Available" and "Halted" if the status is anything else!
- Also I added a filter functions on lending pools so we display every pools supported by the current wallet even if the status is halted, so we display more information to our users
partially #6836
Low risk, mainly presentational
- Just go to the lending page and see if the status is `Active` on most of the pools, even on the pool detail page
- If you are a dev, you can verify by monkeypatching that if the status is Halted it displays the pools!
n/a
n/a
> fix: handle lending statuses properly

- src/assets/translations/en/main.json
Adds a missing word in the English copy for the rFOX bridging process description.
None.
None.
Check that the copy is correct I guess 😆 
☝️ 
☝️
> chore: missing word rfox bridge copy

- src/assets/translations/en/main.json
- src/components/Acknowledgement/Acknowledgement.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/lib/swapper/swappers/ArbitrumBridgeSwapper/getTradeQuote/getTradeQuote.ts
Adds some warning/acknowledgements for Arbitrum Bridge deposits/withdraws in swapper.
See https://www.figma.com/design/IAtOWIGhClYAj7dxC4CzhJ/ARB-Bridge?node-id=75-3202&t=bSyZqQ7JyIQ0Revf-0
- contributes to https://github.com/shapeshift/web/issues/6979
Low - ensure existing ack are still happy visually
- Try to do an Ethereum -> Arbitrum swap using the Arbitrum bridge and ensure the warning is displayed for it (see screenshots)
- Try to do an Arb -> Ethereum swap using the Arbitrum bridge and ensure the ack is displayed for it (see Jam)
- ☝🏽 
- ☝🏽 
- Deposit Warning
- Withdraw warning
> feat: arb bridge swapper warnings

- .env.app
- .env.develop
- .env.private
hotfix: point all environments to dev midgard endpoint
> chore: hotfix release v1.626.0

- src/components/Amount/Amount.tsx
- src/hooks/useLocaleFormatter/useLocaleFormatter.test.tsx
- src/hooks/useLocaleFormatter/useLocaleFormatter.ts
By seeing potential `p` inside `p` semantic issues, I noticed that a lot of code in that part isn't used at all, let's remove it!
n/a
No risk, not used at all
This code was not used at all so, I guess you should just build the app to see if there are no errors
n/a
n/a
> feat: remove deadcode from useLocaleFormatter

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
If you're about to launch a THORChain streaming swap, it will display an acknowledgement warning
Displaying this for a swap taking a few seconds looks a bit weird, let's display it for swaps that are over 5 minutes of estimated execution time
n/a
Low risk
- Try to do a swap using THORChain streams (ETH to BTC for example)
- If the time is over 5 minutes, it should display the acknowledgement, if it's under, it shouldn't display this warning
For devs: you can monkey patch this streaming treshold to under 10 secs to verify that it's displayed
n/a
n/a
> feat: set stream acknowledgement threshold to 5 minutes

- .env.app
- .env.private
Midgard is back up in our prod cluster, cut back over in app and private envs.
closes https://github.com/shapeshift/web/issues/7205
Low
- Validate midgard endpoints are working and returning the expected data
:point_up:
:point_up:
> chore: cut midgard back over in prod

- src/assets/translations/en/main.json
- src/components/Acknowledgement/Acknowledgement.tsx
- src/components/Amount/Amount.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/hooks/useLocaleFormatter/useLocaleFormatter.test.tsx
- src/hooks/useLocaleFormatter/useLocaleFormatter.ts
- src/pages/RFOX/components/Stake/StakeConfirm.tsx
feat: make time of streaming acknowledgement human readable (#7253)
feat: set stream acknowledgement threshold to 5 minutes (#7252)
feat: remove deadcode from useLocaleFormatter (#7251)
fix: loss of precision in Amount.Crypto (#7246)
fix: rfox stake confirm handle not enough fee asset for gas (#7231)
> chore: release v1.628.0

- src/pages/RFOX/hooks/helpers.ts
Fixes bug in user pending rewards due to WAD division missing.
NA
Low risk - display concern only.
Check the pending reward amount on rFOX page is correct.
> fix: adjust user reward by WAD

- src/assets/translations/en/main.json
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
You shouldn't be able to add liquidity to a pool or repay a loan using the demo wallet, I blocked the buttons as a quickwin and it will be replaced by another button abstraction in a follow up
closes #7248
Low risk
n/a
n/a
> feat: liquidity input and repay guard using demo wallet

- src/pages/RFOX/hooks/helpers.ts
- src/pages/RFOX/hooks/useCurrentEpochMetadataQuery.ts
- src/pages/RFOX/hooks/useEpochHistoryQuery.ts
Ensures we display the correct RUNE amount distributed to stakers on rFOX dashboard.
See https://discord.com/channels/554694662431178782/886041582422356018/1256052603364573256
Low risk - display concern only.
Check the RUNE reward amounts are correct.
> fix: display correct distribution of affiliate revenue to stakers

- src/react-queries/helpers.ts
Fixes app crash when changing wallet and navigating to rFOX dashboard.
closes #
1. Connect native wallet and go to rFOX dashboard
2. go to trade page
3. Connect a different native wallet
4. go to rFOX dahsboard
5. app crash
Note the below state causing crash. Basically it led to "not pending" state when the state was in fact pending. The output was then returned as uindefined and we had `undefined + undefined = NaN` => `bigint / NaN` => crash
> fix: app crash due to incorrect logic in isPending state

- src/pages/RFOX/components/RewardsAndClaims/Claims.tsx
- src/pages/RFOX/hooks/useTimeInPoolQuery.ts
Fixes flaky time in pool due to incorrect approach to log fetching.
NA
Low risk, display concern only
Reload the rFOX dashboard multiple times to ensure the time in pool data loads consistently.
> fix: flaky time in pool due to incorrect approach to log fetching

- src/state/apis/zapper/validators.ts
You know the drill.
N/A
None
- Zapper opportunities are happy
- Zapper error spew is gone
- develop: spew spew
- This diff: no spew
> feat: make zapper opportunities great again

- src/components/Modals/Send/views/Details.tsx
- src/components/MultiHopTrade/components/TradeAmountInput.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
fix: handle crypto and fiat amounts properly instead of displaying NaN (#7297)
> chore: release v1.633.0

- src/assets/translations/en/main.json
- src/pages/Explore/Explore.tsx
- src/pages/RFOX/RFOX.tsx
- src/pages/RFOX/Widget.tsx
- src/pages/RFOX/components/RFOXHeader.tsx
Add rfox to explore page
add mobile header nav for rfox
update max width of the widget## Description
Also adds the SEO component to update the tab title.
closes #7319 
low risk
You can navigate to rfox from the explore page on mobile and get back by tapping the back button.
> feat: add rfox to explore page

- src/assets/translations/fr/main.json
Context translation error in French for "Change address" in the rFOX UI, only in French (other translations use the right context as far as I can tell). Since the next app translation sync will happen in couple of weeks and the feature is getting some attention/marketing I figure it's better to quick-fix this. 
None. Just translation.
None.
Check the translation with the French language selected. Show now show "Changer d'adresse".
☝️ 
☝️
> fix: rfox address change fr translation

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/hooks/useIsSmartContractAddress/useIsSmartContractAddress.ts
- src/lib/address/utils.ts
- src/lib/ethersProviderSingleton.ts
- src/lib/fees/utils.test.ts
- src/lib/fees/utils.ts
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/state/apis/swapper/helpers/validateTradeQuote.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
This reverts #7330 (commit 3e70f295e65bc9eedfd5fa714b53e4ecae2d1972).
closes #7355
Low risk as this is a revert of #7330
Check trades work in/out of RUNE for various pairs and wallets.
Can trade BTC <> RUNE 🎉
> fix: revert detect smart contracts for every evm chains

- src/config.ts
> chore: release v1.638.0

- src/pages/Flags/Debugging.tsx
- For easier testing we should use the isMobile from lib/globals instead of react device detect.
closes #
low risk
Go to the flags page on mobile, you should still see the env switch dropdown.
> fix: use correct ismobile on the flags page

- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/RecipientAddress.tsx
Only show either the `Recipient address` entry OR the forced manual `Receive Address` entry.
closes https://github.com/shapeshift/web/issues/7381
Low
- Ensure you are seeing the correct address entry depending on smart contract send or not
- Smart contract disabled should still show the same expected address entry
:point_up: 
:point_up: 
Cross Chain Swap:
Disabled:
Same Chain Swap:
Cross Chain Swap:
Disabled:
Same Chain Swap:
Cross Chain Swap:
> fix: only show one of recipient address or forced manual address

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useApprovalTx.tsx
Currently there is a race condition when switching to exact allowance in the swapper. The actual approval execution doesn't get updated immediately resulting in the ability to perform an unlimited approval even though you selected exact. This quick fix ensures there is a loading state when switching back and forth between exact and unlimited approvals ensuring the transaction payload brodcasted is accurate with the UI.
N/A
None
- Ensure the accurate approval amount after switching exact/unlimited and broadcasting (approve) as soon as able
:point_up:
:point_up:
Current Behavior:
https://github.com/user-attachments/assets/ad93b36c-972c-44cb-989e-fdf36210ad41
New …
> fix: allowance race condition

- src/components/Modal/components/DialogCloseButton.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
When submitting the trade form, we were not preventing the default behavior to happen, so the form was redirecting the current page to the submitted version with parameters in the url. To fix this, I just added an event `preventDefault` on the top of the submit handler
Also, there was an error in the console telling us that `fontsize` was not existing, fixed this at the same time as a quickwin.
closes #7340
closes #7384
Super low
- Launch the app
- Go to the swapper
- Do a very small amount trade using Thorchain (to show the acknowledgemnt component)
- The app should not be reloading anymore!
- Open the console, you shouldn't see the error about `fontsize` anymore after clicking on the asset modal …
> fix: app reboots after the first thorchain trade

- packages/swapper/src/constants.ts
- packages/swapper/src/swappers/PortalsSwapper/getPortalsTradeQuote/getPortalsTradeQuote.ts
- packages/swapper/src/swappers/PortalsSwapper/utils/helpers.ts
This PR implements best gas estimations for Portals quotes using a well-known, funded address hack:
Since Portals isn't able to return us a rough estimations of `gasLimit` (a la Li.Fi, ZRX etc), we're rolling our own best estimates using an address funded in native asset for each chain, as well as an arbitrarily chosen token, and using those mock params alongside an arbitrary amount (that the address *has*, and has approved the Portals proxy for).
- closes https://github.com/shapeshift/web/issues?q=is:issue+is:open+sort:updated-desc
- Try and get a Portals quote for an asset you don't have an approval for
- Ensure you can get some *rough* gas estimation (it may be …
> feat: portals best effort gas estimations

- .github/workflows/generate.yml
Does what it says on the box - see https://github.com/shapeshift/web/actions/workflows/generate.yml / https://github.com/shapeshift/web/pull/7458 for context
N/A
None
None
> feat: temp disable asset regen cron job

- src/pages/RFOX/constants.ts
Adds updated metadata hash for end of epoch #0 and pending rewards
NA
Low - somehow it could break the rFOX dashboard
load rfox dashboard using a wallet with no rFOX
load rFOX dasghboard using a wallet with rFOX, should see pending rewards
> chore: add epoch 1 metadata

- src/lib/market-service/portals/portals.ts
Does what it says on the box - leverages `getConfig()` to fix undefined Portals env vars in market-service in upstream develop and release:
closes N/A, spotted in release
None
- Portals requests are going through in gome
> fix: portals market-service env vars

- src/state/apis/zapper/validators.ts
Loosens Zapper schema some, removing some bits we're not concerned about, and allowing unknown keys.
closes N/A
- Zapper read-only opportunities are great again
- Zapper spew should be gone in the app
Develop: Missing zapper read-only opportunities and schema parsing spew
This diff: happy Zapper opportunities 🎉
> fix: make zapper akschually great again

- src/pages/RFOX/components/RewardsAndClaims/RewardTransactionList.tsx
- src/state/apis/snapshot/validators.ts
Pass through any unknown keys from snapshot to prevent future schema validation breaking changes. This is safe to pass through the strategy params as we are just passing them to `score.snapshot.org`. Also add unique key for `RewardTransactionList`.
N/A
Low
- Calls to `score.snapshot.org` should still work
:point_up: 
:point_up:
> chore: prevent future myzod break parsing snapshot

- src/assets/translations/en/main.json
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
We need to remove the underlying assets to be able to deliver runepool to production
partially #7302
Low risk
- Try to open the runepool overview while having some rune staked in and look at the underlying assets
> feat: temporary remove underlying assets for runepool

- src/components/TradeAssetSearch/components/GroupedAssetList/components/GroupedAssetRow.tsx
a.k.a "friggin types mang" - does what it says on the box and brings type-safety on the offending component so it's more polite.
N/A, see releae thread https://discord.com/channels/554694662431178782/1270062896906244197/1270155847971897388
None, this *brings* in type-safety
- Import a custom token import
- Ensure the app doesn't crash anymore right after pasting its addy
- ^
- ^
- release
https://jam.dev/c/f1874b26-f986-444e-a70c-bf7cc1d85664
- this diff
https://jam.dev/c/6d0c5953-1dcc-4755-b7be-9a494e97696c
> fix: custom asset imports regression

- src/components/StakingVaults/Cells.tsx
- src/pages/Defi/components/FeaturedCards/FeaturedCard.tsx
The opportunity cards containing more than one icons are not looking so good right now, let's show the first icons so it's sexier!
no sisue
Low risk, presentaitonal
Go to the earn page, look at the ETH/FOX opportunity, it should be displayed properly
n/a
n/a
Before:
After:
> fix: show first icon in opportunity cards

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
Currently there is a bug with cowswap signing when using MM (switch chain wallets) if not on the correct network. Add switch chain logic to `signMessage` and `signTypedData` to ensure switch occurs before sign action.
- closes https://github.com/shapeshift/web/issues/7507
Low
- Initiate a cowswap trade (which uses message signing) for a network that doesn't match the current wallet network and ensure the chain is switched and transaction succeeds
- Simple regression test against non switch chain wallets (native, kk, ledger) that signing still works as intended
:point_up:
:point_up:
https://github.com/user-attachments/assets/231772b6-09e7-487f-aba5-bff7d28fda7c
> fix: switch chain on evm sign actions

- .env.base
Update to use unchained proxy for zerion as API Gateway proxy is causing issues with various endpoints due to trailing slash concerns.
N/A
Low
- make sure you reinitialize the env vars for local testing (ex. `yarn env dev`)
- Import a custom token and verify unchained zerion proxy call is successful (`0xe7f4c89032a2488d327323548ab0459676269331` currently custom token for ref)
:point_up:
:point_up:
> feat: use unchained zerion proxy

- .github/PULL_REQUEST_TEMPLATE.md
Adds a checkbox for marking that a PR is behind a feature flag and doesn't require operations testing at the moment. Also minor copy updates to include more specifics about testing. 
closes #
> chore: adds feature flag and some copy updates to PR template

- .env.base
feat: use unchained zerion proxy (#7520)
> chore: release v1.656.0

- .env.app
- .env.private
Use the `/jsonrpc` endpoint for optimism daemon in production (nownodes infra)
N/A
Low
- Ensure rpc request are still working as intended and using `/jsonrpc` endpoint for optimism
:point_up:
:point_up:
> chore: point to optimism nownodes daemon prod

- src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts
Our on/off ramp partner MtPelerin has just added few items to their supported list of fiat currencies, updating this should provide more options to users.
Low, existing list of supported Fiat currencies is just extended. All the currencies listed are supported by the app (see `src/constants/FiatTypeEnum.ts`).
Off ramping through MtPelerin.
Check that when new Fiat currencies are selected on the Buy/Sell Crypto page, the MtPelerin option is available to users.
☝️ 
☝️ 
Before:
After:
> feat: update fiat support for mtpelerin

- react-app-rewired/headers/csps/chains/arbitrum.ts
- react-app-rewired/headers/csps/chains/arbitrumNova.ts
- react-app-rewired/headers/csps/chains/avalanche.ts
- react-app-rewired/headers/csps/chains/base.ts
- react-app-rewired/headers/csps/chains/bnbsmartchain.ts
- react-app-rewired/headers/csps/chains/ethereum.ts
- react-app-rewired/headers/csps/chains/gnosis.ts
- react-app-rewired/headers/csps/chains/optimism.ts
- react-app-rewired/headers/csps/chains/polygon.ts
- src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts
- src/lib/address/utils.ts
- src/lib/viem-client.ts
fix: hotfix graceful evm accounts derivation failure tolerance (#7549)
feat: update fiat support for mtpelerin (#7547)
> chore: release v1.659.0

- src/pages/RFOX/constants.ts
This will show anything under rFOX as pending --> complete and show the new epoch.
Low risk, should just update the pending rewards to finished. 
Plug in a wallet with some roon rewards and it should properly update.
> chore: fixing metadata for web

- src/lib/mixpanel/helpers.ts
- adds `name` property
- differentiates `assets` and `underlyingAssets` (i.e for RUNEPool, this makes things clearer)
closes #7566
None
- RUNEPool Mixpanel reporting looks gucci
- ^
- ^
> feat: improve mixpanel DeFi reporting

- src/pages/RFOX/components/AddressSelection.tsx
This PR ensures the default selected rewards account in RFOX stake is as-follow:
- current rewards AccountId if already staked *and* if available (i.e if using a custom receive addy, this address may not necessarily be present in portfolio accounts)
- matching AccountId if available (i.e if there *is* a matching RUNE account number for the selected staking account, which may not necessarily be the case)
- undefined if all above fail, meaning there is no `defaultAccountId` passed, meaning `<AccountDropdown />` will automagically select the first RUNE account
closes N/A, spotted in https://discord.com/channels/554694662431178782/1275658955833741342/1275694170841026570
Low to none
> What protocols, transaction types, wallets or contract interactions might …
> feat: rfox default rewards AccountId improvements

- package.json
- yarn.lock
Makes web great again - we still need this package since it's a peer dependency of many @visx packages e.g: 
https://github.com/airbnb/visx/blob/d920798cb9e750477342bbfface99e4399a2d5b8/packages/visx-react-spring/package.json#L41
N/A
N/A
- ^
- ^
- develop
https://github.com/shapeshift/web/actions/runs/10501536310/job/29091774012
- this diff
> feat: partially revert `perf: remove unnecessary dep #7593`

- src/pages/Accounts/components/AccountEntryRow.tsx
Noticed a few problems on wallet icons where icons had a background
Also, not showing at least the first icon is super weird, we want to atleast show the first icon and then aggregate the next icons.
No issue
- Make sure wallet asset icons are displayed properly without any bugs
n/a
n/a
> fix: wallet asset icons style

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/Claim/ClaimSelect.tsx
Shows status text when there are no available claims.
N/A
Low - just status text
- Ensure the status text shows when there are no claims available and/or pending
- Ensure the status text does not show during loading state or if there are claims
:point_up:
:point_up:
> feat: arbitrum bridge no claims status text

- src/features/defi/components/Overview/Overview.tsx
- src/features/defi/components/Overview/UnderlyingAssetsMenu.tsx
- src/features/defi/components/Overview/UnderlyingAssetsTags.tsx
Does what it says on the box - see screenshots
N/A
None
- In the overview of a token DeFi opportunity, the network icon is shown alongside the asset icon
- ^
- ^
Tested against develop (right):
> feat: show network icon in token DeFi overview

- src/pages/RFOX/constants.ts
- src/pages/RFOX/hooks/useLifetimeRewardDistributionsQuery.ts
Updates the hash for pending rewards for epoch #1 
Very low risk, could possibly mess up view only accounting, but nothing more. 
ensure rFOX dashboard is updated
> chore: update hash for epoch 1 pending

- src/assets/translations/en/main.json
- src/pages/Markets/MarketsHeader.tsx
- src/pages/Markets/MarketsPage.tsx
- src/pages/Markets/Recommended.tsx
Authors empty markets recommended page, alongside with tabs routing
- contributes to https://github.com/shapeshift/web/issues/7623
None
- None
> feat: recommended markets page boilerplate

- packages/caip/src/assetId/assetId.test.ts
Does what it says on the box - we already have the same test below:
https://github.com/shapeshift/web/blob/1751cc5e9cfca4755b222fe81e72055aba5a18a9/packages/caip/src/assetId/assetId.test.ts#L358-L367
And this didn't do anything Ropsten anyway (the code is exactly the same as the permalink above).
closes N/A
None
None
> feat: remove useless caip ropsten test

- src/assets/translations/en/main.json
Does what it says on the screenshot below.
N/A, spotted in https://github.com/shapeshift/web/pull/7525/files#r1754663828
None
- Claim pending copy looks happy, see screenshot below
- ^
- ^
- develop
- This diff
> fix: rfox claim pending copy

- src/pages/RFOX/constants.ts
Update to latest rfox ipfs metadata hash for completed epoch 1 distribution
N/A
None
- Validate rfox data is accurate and complete distribution is displayed
:point_up:
:point_up:
> chore: update rfox ipfs metadata hash

- package.json
- react-app-rewired/index.ts
- yarn.lock
Webpack bumped to current and associated dependencies/resolutions sorted.
closes https://github.com/shapeshift/web/issues/7682
Low - building locally both dev and production build
- Validate `yarn dev` is working
- Validate `yarn build:web` works
- Spot check to make sure nothing weird is happening after the upgrade
:point_up:
N/A
> chore: bump webpack and fix dependencies

- .github/workflows/generate.yml
Uses the new generate:all script instead of the previous multiple steps
closes N/A
None
- CI is happy
- None
> feat: cleanup regen script

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/RecipientAddress.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/lib/utils/thorchain/hooks/useSendThorTx.tsx
feat: disable taproot custom receive addresses in swapper (#7781)
fix: savers consistent withdraw dust amount (#7780)
> chore: release v1.681.0

- src/assets/translations/en/main.json
- src/pages/Markets/MarketsHeader.tsx
... and performs smolish cleanup while at it
closes N/A
None
- Categories tab is gone
> feat: markets page remove categories tab

- src/assets/translations/en/main.json
- src/pages/Markets/MarketsHeader.tsx
- src/pages/Markets/components/AssetsGrid.tsx
- src/pages/Markets/components/LpGrid.tsx
closes N/A
Low
- Empty state is happy for markets categories
- Empty state is happy for markets watchlist
> feat: markets page empty state

- src/state/slices/opportunitiesSlice/constants.ts
Enable the Evergreen FOX opportunity.
Relates to https://github.com/shapeshift/web/issues/7666
Medium. Code-wise it's low risk, but it adds a new contract (though one that has been well-tested).
Approvals/Deposits/Withdraws against the Evergreen staking contract: https://etherscan.io/address/0xe7e16e2b05440c2e484c5c41ac3e5a4d15da2744
The [Evergeen](https://etherscan.io/address/0xe7e16e2b05440c2e484c5c41ac3e5a4d15da2744) opportunity should show on the Earn page (with 0% APY for now):
Confirm that deposit and withdraw on this opportunity works.
☝️
☝️
> feat: add evergreen opportunity

- src/Routes/PrivateRoute.tsx
Implements markets as a *non*-private route, laying the fundations for ditching redirect in more and more places in a follow-up and implement a wallet connect modal instead.
- contributes to https://github.com/shapeshift/web/issues/7837
Low, do a sanity check of routing and ensure we still look good here
- markets routes are now accessible without a wallet (try and disconnect your wallet while on markets page, which should *not* kick you out of markets and to the splash page)
- ensure all routes are still happy with a wallet connected
- ^
- ^
> feat: hasta la vista markets private route

- src/pages/Dashboard/Portfolio.tsx
Hides balance chart to gauge user response before permanent removal. See #7872 for context.
Doesn't actually remove and code or change network requests yet.
progresses #7872
Extremely low risk.
Check balance chart is no longer viewable in the app.
> feat: hide balance history chart

- src/components/Layout/Header/Header.tsx
... since we can't have Txs without a wallet.
closes N/A
None
- Without a wallet connected, the Tx drawer button is hidden
- With a wallet connected, the Tx drawer button is displayed
- ^
- ^
- develop
- This diff
> feat: don't display Tx history button if wallet is disconnected

- packages/caip/src/adapters/coingecko/index.ts
See screenshots to see what this cleans up - these weren't errors but expected as part of our flow.
closes N/A
None
- Sanity check coingecko data is still fetched in markets page
- develop
- develop
- this diff
> chore: cleanup coingecko spew

- src/pages/RFOX/components/Stake/StakeConfirm.tsx
This could never work since we were waiting on an approvalTx, but can't introspect SAFE Txs in the app... as these don't exist in-app.
closes https://github.com/shapeshift/web/issues/7764
Low
- With a SAFE connected, approvals of FOX for RFOX staking aren't infinitely loading and allow to continue to stake e2e
- ^
- ^
https://jam.dev/c/8524f000-1b90-4962-adc7-2c99fbc4a3a5
> fix: rfox stake stuck at approval step with SAFE

- src/pages/Dashboard/Portfolio.tsx
This reverts commit ff1cdf2141f9a36d8bd00af239e21892a94fd8fd.
Further discussion required before progressing this. Reverting until we have more information.
reverts #7873
Low risk.
> feat: unhide balance history chart

- src/Routes/RoutesCommon.tsx
As discussed with @twblack88 this should be `FaChartsArea` https://discord.com/channels/554694662431178782/1291456695477731399/1291467875516940412
closes N/A
None
- Markets icon is now this one: https://fontawesome.com/v5/icons/chart-area?s=solid
Tested against release (right):
> feat: update markets page nav icon

- src/components/Acknowledgement/Acknowledgement.tsx
- src/components/MultiHopTrade/components/LimitOrder/LimitOrder.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/TradeAssetSearch/TradeAssetSearch.tsx
- src/components/TradeAssetSearch/components/CustomAssetAcknowledgement.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/RFOX/components/Stake/StakeInput.tsx
- src/pages/RFOX/components/Unstake/UnstakeInput.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Resolves full-width warning acknowledgement in trade input by migrating them to chakra-ui modals.
Also resolves the requirement for nesting when using these components in code.
closes #7946
Medium risk, affects ui layout only but the shanges to this component are extensive and this needs careful review.
Check all instances of the acknowledgement componets are working as expected, noting this is a modal now instead of an in-place overlay.
- custom asset input
- trade amount below minimum on trade input
- streaming swap warning on trade input
- arbitrum bridge warning on trade input
- slippage warning on trade confirm
- rFOX stake + unstake
- LP add …
> fix: migrate acknowledgement ui to modal to resolve layout issues

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
Adds a code comment to ensure we stay aware of a known issue that would need resolving should we make changes to the acknowledgements in the trade input UI.
NA
None. Code comment
Not required.
> chore: code comment for acknowledgement control flow

- src/hooks/useBridgeClaimNotification/useBridgeClaimNotification.tsx
Does what it says on the box - ensures we only ever keep one toat ref per walletId
closes https://github.com/shapeshift/web/issues/7947
None
- Have two wallets with Arb claims (e.g switching between two MM accounts with claims or going from one EVM wallet with claims to another)
- Ensure there is only ever a single toast displayed, and the previous one is dismissed when switching wallets (since not applicable anymore)
- ^
- ^
- develop
- this diff
https://jam.dev/c/17541973-4753-4928-b1fc-4a2723178106
> fix: duplicate arbitrum bridge toasts on walletId change

- src/components/StakingVaults/PositionTable.tsx
- src/components/StakingVaults/WalletProviderTable.tsx
- Inside earn, we are missing some empty states when selecting chains without active positions
n/a
Low
- Go to Earn
- Select BASE or Gnosis, see the empty states on both tabs
n/a
> fix: empty staking states

- src/components/AssetIconWithBadge.tsx
Refactors `AssetIconWithBadge` to make the component easier to reason about, in anticipation of changes needed to handle the new Limit Order UI.
Relates to https://github.com/shapeshift/web/issues/6206
Small
None
Ensure that all uses of the `AssetIconWithBadge` component show no regressions against production. Specifically, all icons in the transaction history and rFOX claims should be identical on both this branch and in production.
☝️
☝️
> refactor: component AssetIconWithBadge

- packages/chain-adapters/src/utils/validateAddress.ts
- src/pages/RFOX/constants.ts
Updates hash for pending reward hash 
closes #
Low - could potentially break dashboard
make sure rFOX dashboard looks happy with pending rewards shown
> chore: update latest epoch hash

- packages/caip/src/assetId/assetId.ts
- packages/caip/src/constants.ts
- packages/chain-adapters/src/utils/validateAddress.ts
- packages/swapper/src/swappers/CowSwapper/endpoints.ts
- packages/swapper/src/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- packages/swapper/src/swappers/CowSwapper/types.ts
- packages/swapper/src/swappers/CowSwapper/utils/helpers/helpers.test.ts
- packages/swapper/src/swappers/CowSwapper/utils/helpers/helpers.ts
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/pages/RFOX/constants.ts
- src/state/apis/limit-orders/limitOrderApi.ts
- src/state/apis/limit-orders/types.ts
- src/state/reducer.ts
- src/state/slices/opportunitiesSlice/resolvers/ethFoxStaking/index.ts
- src/state/store.ts
- src/test/mocks/store.ts
chore: update latest epoch hash (#8066)
fix: use fox as default asset on solana asset pages (#8063)
feat: wire up limit orders UI to RTK query (#8052)
> chore: release v1.702.0

- src/context/AppProvider/hooks/useAccountsFetchQuery.tsx
Pretty straightforward oneliner: we never reran the query when going from `null` `isSnapInstalled` (i.e loading) to `true`
closes https://github.com/shapeshift/web/issues/8096
None
- Have the snap installed and clear your cache
- Ensure non-EVM accounts are loaded again
- ^
- ^
https://jam.dev/c/905adb52-8ede-4d2a-bd58-8bedba33dd77
> fix: mm snap not deriving non-EVM accountIds

- package.json
- src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
- src/components/OrderDropdown/OrderDropdown.tsx
- src/components/SortDropdown/SortDropdown.tsx
- src/context/AppProvider/hooks/useAccountsFetchQuery.tsx
- src/pages/Markets/components/MarketsRow.tsx
- yarn.lock
fix: mm snap not deriving non-EVM accountIds (#8097)
fix: market filters going out of screen (#8091)
chore(deps-dev): bump happy-dom from 12.10.3 to 15.10.2 (#8089)
fix: lower a bit the market filters breakpoint (#8086)
fix: send revalidation not executed when going back and forth (#8078)
> chore: release v1.704.0

- src/state/apis/swapper/helpers/validateTradeQuote.ts
Rates are not properly checking the balances/amounts/fees deductions, introduced by https://github.com/shapeshift/web/commit/d8c2efeb5d3248e133cb70abd6c1df9d78de2e52#diff-11cff69592f70893ba71b1f145ba4691cf7452b1c8188088b9769e13fd055ed9R257-R282
As It's a wip, seen in private with gomes, we can remove these checks to fix those check and avoid letting a bug in production while the work is on going.
closes #8103
Low because revert medium because swapper
- Try to input every amounts in the swapper
- Try to input a fee asset of MAX amount, quotes should be erroring preventing you to go further
n/a
n/a
> fix: amounts checks on swapper

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/RateGasRow.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedSlippagePopover.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter/SharedTradeInputFooter.tsx
- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/components/MultiHopTrade/components/SwapperIcons.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/state/apis/limit-orders/limitOrderApi.ts
- src/state/apis/limit-orders/types.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
feat: limit orders quote wiring (#8095)
> chore: release v1.707.0

- src/pages/RFOX/constants.ts
Update rfox metadata ipfs hash to reflect the most recent epoch #3 reward distribution
N/A
Low to none
- Ensure november reward distribution is showing as complete and linked to on chain
:point_up: 
:point_up:
> chore: update rfox metadata ipfs for epoch 3 distribution

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/lib/utils/thorchain/balance.ts
> revert: "fix: use fee asset for dust amount conversion"

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/utils/thorchain/balance.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/index.ts
See: https://github.com/shapeshift/web/pull/8172
> fix: savers withdraw

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/LimitOrder/helpers.ts
Performs validation of user input and renders quote errors, if there are any. Prevents users from proceeding with invalid limit orders.
closes #8109
Low risk, this makes no changes to anything outside of limit orders, which is behind a feature flag and still work-in-progress.
Quick jam showing preview button disabled before quote, and balance validation:
https://jam.dev/c/b835bceb-9de3-4287-bfa7-57dc7f562007
> feat: limit orders input validation and quote error rendering

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/TradeQuoteCard.tsx
Fixes 2 issues with trade quote UI overflowing:
- Error tag too long -> fixed by makingit an icon with tooltip
- Swap source can be too long (though realistically never is) -> made it overflow with ellipsis
closes #8110
Low risk.
check the information is presented correctly and doesnt result in corrupted ui layout.
Demo of the fixes:
https://jam.dev/c/f2ad3ff6-1aef-4f35-ac69-d1aeadeb71fe
Torture test of overflow behavior
> fix: trade quote UI overflow

- src/theme/theme.tsx
I specially aimed the bottom right informational toasts as others are not really intended to stack
closes #8234
Low
- Force the toast to show by changing the conditions in `App.tsx` and `useBridgeClaimNotification` or have both toast shown on an specific account
- Verify that those toasts have the same size
n/a
n/a
> fix: uniform informational toast sizes

- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
The modal was blocking scroll from working inside the drawer. Moving it inside of the `<ModalContent>` allows the drawer to be scrolled.
closes #
low risk
Open the manage account drawer to a chain with multiple accounts, make the browser height smaller than the list of accounts you should be able to scroll to see all available accounts.
Same goes from when adding a chain, the selection menu of chains should also scroll.
> fix: scrolling inside the account drawer

- src/pages/RFOX/constants.ts
adds pending rewards for epoch #5
NA
very low 
Check that the rFOX dashboard shows the updated pending rewards
> chore: update ipfs hash for epoch #5 pending rewards

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeRates.tsx
Groundwork for https://github.com/shapeshift/web/issues/7979 - not a breaking change for now, but gives us a saner base to work with. 
- contributes to https://github.com/shapeshift/web/issues/7979
Medium - really just code moved from an IIAFE in an effect to react-query which *should* be safer but...
- Perform a lil sanity check of swapper e2e with and without a wallet connected and ensure it still works as expected
- ☝🏽 
- ☝🏽 
https://jam.dev/c/4b3d1f43-2706-454b-9305-f51884c2cf21
> feat: move tradeRateInput effect logic over to react-query

- src/components/MultiHopTrade/components/LimitOrder/components/CancelLimtOrder.tsx
- src/state/apis/limit-orders/limitOrderApi.ts
Actions review feedback in https://github.com/shapeshift/web/pull/8203#discussion_r1867042894
closes NA
Very low risk.
Check cancelling a limit order still works (you'll have to create on in swap.cow.fi because approvals arent implemented yet)
> chore: improve response type of cancelLimitOrder api endpoint

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/CancelLimtOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrder/hooks/useGetLimitOrdersForAccountQuery.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
feat: implement polling updates for limit order list (#8281)
fix: clear tradeQuoteSlice state on trade input mount (#8296)
> chore: release v1.718.0

- CONTRIBUTING.md
Ensures we have something nice to link to when closing spam PRs.
closes N/A
None
> feat: add no spam typo PRs section in CONTRIBUTING.md

- src/components/Modals/Nfts/NftModal.tsx
- src/components/Nfts/NftCard.tsx
NFT were not loading because Zapper is providing non reachable links and wrong informations
As a quickwin I added some error handling to those images so skeletons stops loading when images are erroring because links are unreachable
partially #8094
Low
Use `0x0301f6a8AcE9D9a649359BfFb1B90D4B66177784` as a watch address and wait for skeletons to disappear, also check for details modal
> fix: nft infinite skeletons

- src/components/MultiHopTrade/components/LimitOrder/components/CancelLimitOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderList.tsx
- src/components/MultiHopTrade/components/LimitOrder/helpers.ts
- src/lib/mixpanel/types.ts
- src/state/apis/limit-orders/limitOrderApi.ts
Add mixpanel event tracking for limit orders:
- Order submitted
- Order canceled
closes #6202
Very low risk.
None.
Check a mixpanel event is pushed when creating and canceling limit orders.
Placing an order:
https://jam.dev/c/0eadbb62-97fd-4f70-905a-603286685c07
Canceling an order:
https://jam.dev/c/a1cbd3c9-790c-440f-b59b-cba791c7ff90
> feat: add mixpanel event tracking for limit orders

- packages/swapper/src/cowswap-utils/index.ts
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useSignPermit2.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/plugins/walletConnectToDapps/utils/CosmosRequestHandlerUtil.ts
- src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts
Use `getBip44Params` as exposed by the chain adapter to create manual `addressNList` where applicable. This will ensure the correct `addressNList` with no required change to the current portfolio state. Once custom accounts go in, we will be able to do a full migration of portfolio to initialize correctly all the way through.
Replaces: https://github.com/shapeshift/web/pull/8352
closes https://github.com/shapeshift/web/issues/8351
Medium - we are dealing with derivation path changes so we will want to do a solid regression across all chains
- Ensure swap from cosmos and thorchain are working
- Ensure message signing is working for evm chains (cowswap, ZRX …
> fix: use getBip44Params for manual addressNList

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/LimitOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/AllowanceApproval.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/LimitOrder/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/StatusBody.tsx
Adds a simplified allowance approval flow for the limit orders feature.
- Deliberately does not tackle USDT allowance resets
- Avoids integrating the updated UI in #8192 
closes #8154
closes #8382 
Low risk. Introduces a new approval tx to limit orders, but is of minimal risk to users as this uses existing hooks already live in production.
Limit orders via cow protocol.
- Sufficient allowance - no approval needed
- Allowance needed, executed, order placed, successful execution
- Error handling good
- Insufficient balance for gas
- USDT allowance required, starting from 0 allowance - should work like other ERC20s
- USDT allowance required, starting from …
> feat: simplified allowance approval flow for limit orders

- packages/swapper/src/swappers/PortalsSwapper/types.ts
Disables Gnosis as a supported Portals chain until further notice, as currently broken upstream.
closes https://github.com/shapeshift/web/issues/8346
None
- Try and get a Gnosis rate
- Confirm Portals doesn't show up in the quotes list
- ^
- ^
> feat: portals disable gnosis

- packages/swapper/src/swappers/PortalsSwapper/types.ts
As this has been confirmed happy again by Portals team, and confirmed by testing.
closes N/A
Low - double-check Gnosis swaps with Portals are *actually* happy
- Gnosis swaps with Portals are *actually* happy
- ^
- ^
https://jam.dev/c/a0888907-50d0-4f89-a2ff-aede8b26e30a
> feat: revert "feat: portals disable gnosis (#8392)"

- packages/swapper/src/swappers/JupiterSwapper/utils/helpers.ts
Jupiter auto slippage was not working, they are telling us `autoSlippage` is the key to configure as quote api call but they are using `dynamicSlippage`, and it works...
Slippage should now be higher for most of the swaps making it successful in the end
spotted in https://discord.com/channels/554694662431178782/1316422691191918754/1319067331909128244
- Try any swaps from SPL token to Token2022 
- Try any swaps from SOL to USDC/USDT
https://explorer.solana.com/tx/HkcCiXNDQ4p5ddk45ZUVgYU8CD6yPSby1f5aQYmP67pLsdrNFT36kXexbJYis1rz95YE6FNjYmhwriTkDTDsHo7
https://explorer.solana.com/tx/3fQiVroxVrJ7AQNVaeEk91hVj41BnScYyiLNQqPP9ELfZCKMEQsB5z4162TKEyfM9i6yEEWaAokMHT …
> fix: jupiter auto slippage

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
Visual nitpick spotted by @neomaking in case users feel extremely optimistic about the price they're inputting.
closes N/A
None
Deltas greater or equal to 999% are shown as >999%
- ^
- ^
https://jam.dev/c/86a69c6a-22bb-40ae-a375-945f0f60771e
> feat: limit orders constraint delta to 999% max

- src/pages/RFOX/constants.ts
Updates rfox hash for pending rewards
closes #
Low 
Confirm that the rFOX dashboard displays correctly
> chore: add rfox pending reward hash for epoch #5

- packages/contracts/src/ethersProviderSingleton.ts
- packages/swapper/src/swappers/ArbitrumBridgeSwapper/utils/fetchArbitrumBridgeSwap.ts
- packages/swapper/src/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/ThorchainSwapper/getThorTradeRate/getTradeRate.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/checkOutputTxConfirmations.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getL1Rate.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getL1quote.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getLatestThorTxStatusMessage.ts
- packages/utils/src/chainIdToFeeAssetId.ts
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep/ApprovalStep.tsx
- src/state/slices/limitOrderInputSlice/helpers.ts
- src/state/slices/limitOrderInputSlice/limitOrderInputSlice.ts
When returning from a switch statement and using the `assertUnreachable` util, you must `return assertUnreachable(..)` for typescript's exhaustiveness checks to work correctly. This negates the requirement to add an additional assertion after the switch statement, and eliminates the red.
NA
Very low risk.
Not required.
> fix: broken exhaustiveness checks in switch statements

- packages/swapper/src/cowswap-utils/constants.ts
- packages/swapper/src/cowswap-utils/index.ts
- packages/types/src/cowSwap.ts
closes https://github.com/shapeshift/web/issues/8421
CoW
This one is a bit tricky to test given the current state of base (estimations often failing, Txs often not being picked). 
The best way to test is to try and sell a token that doesn't support permit2 approvals (e.g WETH), pre-approve it on CoW UI, then proceed with the swap in app, so you have only the actual Tx to estimate/sign.
- CoW Base swaps are happy
- ^
- ^
https://explorer.cow.fi/base/orders/0x1cf0b13b24b344038bc182c53feabd2355f01a5102f166f6f91f4e3abb35bc2b5daf465a9ccf64deb146eeae9e7bd40d6761c986677809d7?tab=overview
> feat: base on CoW

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx
The exact same as before, but for new swapper flow.
closes https://github.com/shapeshift/web/issues/8477
Low, isolated to new swapper flow but same logic as before
- Rate changed modal should appear on final quote whenever applicable (i.e Portals is consistent in yielding a final quote)
- ^
- ^
https://github.com/shapeshift/web/issues/8477
> feat: new swapper flow rate changed modal

- src/state/migrations/index.ts
Bumps asset data cache version to 35 to trigger re-fetch after revert.
NA
Low.
> fix: bump asset cache migration version to 35 to trigger re-fetch

- src/context/WalletProvider/WalletProvider.tsx
Clicking on import on the wallet modal was not working
closes #8554
Low
- Click on import on the wallet modal
- You should be redirected to the wallet select modal
n/a
n/a
https://jam.dev/c/3b00a67a-e182-488a-bc0e-4841dd0123c6
> fix: import dead click on wallet modal

- .env.develop
Turn on rfox lp feature in develop for testing
Reference: https://github.com/shapeshift/web/pull/8455
> chore: turn on rfox lp in develop

- react-app-rewired/headers/csps/wallets/coinbase.ts
Does what it says on the box - csp was missing for the walletlink endpoint, so the endpoint was silently failing and being displayed as perma-loading.
closes https://github.com/shapeshift/web/issues/8612
None
- Open a browser without Coinbase wallet installed (e.g incognito)
- Ensure the modal is happy
- ^
- ^
https://jam.dev/c/1dcdc71c-fd43-4909-aff9-21aa53d1eed8
> fix: coinbase qr code modal

- src/context/WalletProvider/config.ts
The import link on mobile app was a dead click, this PR fixes it
Spotted in https://discord.com/channels/554694662431178782/1330819141518495766/1330887330432548954
Low
- Click on Import wallet on mobile app
- then click again on "Import", you should be redirected to the import view
- Can be tested on `gome` env until it's erased by someone else
n/a
n/a
https://github.com/user-attachments/assets/eb29eac7-d284-45a1-96f3-59481b6f8b99
> fix: import dead click on mobile app

- src/assets/translations/en/main.json
- src/context/WalletProvider/NativeWallet/components/NativeImportSelect.tsx
- yarn.lock
Updates the copies relative to Keystore import to remove mentions of "upload" and reflect the local nature of this operation as discussed with @gomesalexandre while translating https://github.com/shapeshift-globalization/web/pull/398
Low, English copies only.
None.
Check the strings in-place in the Import wallet modal.
☝️ 
☝️ 
Before:
After:
> chore: change keystore import copy

- src/assets/translations/en/main.json
This PR adds a dot.
closes N/A
I mean... this adds a dot.
Dot looks good.
None
> feat: add dot

- src/assets/translations/en/main.json
i.e makes expected actions to recover from failure more obvious for users instead of just warning them about said failure.
closes N/A, spotted in [release](https://discord.com/channels/554694662431178782/1332058316892803072/1332085220916330526)
None, copy change only.
- Connect MM using WC wallet option
- Ensure the chain your MM is connected to is *not* the same as the sell asset's
- Notice copy tells you to manually try and switch chain in your wallet
- ^
- ^
> feat: improve chain switch failed copy

- src/assets/translations/en/main.json
Just cleaning up the first pass words into something that makes more sense and gives users the chance to learn about all the fox programs. 
N/a slightly related to #8589 
low
Built locally here and looks good.
Give her a once over. 
Extra credit, if you have any changes lemme know!
> chore: tightening foxwifhat copy

- src/context/WalletProvider/NewWalletViews/routes/MipdRoutes.tsx
- src/context/WalletProvider/NewWalletViews/sections/SavedWalletsSection.tsx
Fix 2 instances of missing and incorrect key usage.
QOL
Minimal
None
1. When the connect wallet screen renders we should not see the below
2. When a MIPD wallet is selected we should not see the below:
☝️
N/A
N/A
> fix: react key issues

- .github/workflows/generate.yml
> feat: update regen ci personal access token

- .github/workflows/generate.yml
- src/Routes/RoutesCommon.tsx
- src/assets/translations/en/main.json
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/pages/Defi/components/EligibleCarousel.tsx
- src/pages/Defi/components/EligibleSlider.tsx
- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/components/LendingHeader.tsx
- src/pages/Lending/hooks/useIsLendingActive.ts
- src/pages/Lending/hooks/usePoolDataQuery.ts
- src/pages/Markets/components/AssetGridWithData.tsx
- src/pages/Markets/constants.ts
- src/pages/Markets/hooks/useRows.tsx
fix: thorfi halted warning copies and improvements (#8681)
feat: update regen ci personal access token (#8690)
> chore: release v1.752.0

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeConfirm/components/ExpandableStepperSteps.tsx
- src/lib/coingecko/utils.ts
feat: add doge to markets (#8694)
feat: countdown timer during trade execution (#8687)
> chore: release v1.753.0

- src/pages/RFOX/hooks/useLifetimeRewardDistributionsQuery.ts
Filters out any zero value "distributions" for rfox lp genesis state
N/A
Low
- If you have staked in rfox lp, you can use this ipfs hash: `QmTYs3gHjUTHhLFNrqiDZ3zRLTc3XQG5FSDiuinqHpvC9u` to test. You should not see a pending reward for rfox lp
:point_up: 
See screenshots
> feat: filter out zero value rfox distributions

- src/components/Layout/Header/GlobalSearch/GlobalSearchModal.tsx
Fixes the ENTER keypress not closing the global asset search modal.
closes https://github.com/shapeshift/web/issues/8674
None
- Select an asset in global search modal and confirm pressing ENTER closes the modal
- Select an asset in global search modal and confirm clicking the button closes the modal
- ^
- ^
https://jam.dev/c/f723dbbb-2c2c-4826-91f1-d8b47e37aa24
> fix: global search enter keydown

- src/pages/RFOX/constants.ts
Update rFOX IPFS hash to display pending reward and updated burn/distribution rates now that LP staking is active.
N/A
Low
- Ensure pending reward is showing for FOX
- Ensure no pending rewards are showing for ETH/FOX LP
- Ensure correct estimated rewards, burn, and distribution amounts are showing
:point_up:
:point_up:
> chore: update rfox ipfs hash

- scripts/generateAssetData/base/index.ts
FOXWifHat logo is not displaying because I'm dumb and used a hold link without even noticing it was wrong so I'm just going to slap myself but thanksfully FWH is not released yet
n/a
Low
- FWH logo should be displayed properly
n/a
n/a
> fix: foxwifhat wrong logo link

- src/components/MultiHopTrade/MultiHopTrade.tsx
Solana swapper had an early return avoiding the swapper to pre-select solana assets and SOL because historically we didn't have any swapper for these assets
Now that we support bridge through chainflip and swap through jupiter, we can disable this security (and tbh I think we should probably never do it again, we should support bridge and swaps asap anyway)
https://discord.com/channels/554694662431178782/1336632858516656128/1336658160756195369
closes #8748
Low
- Go to SOL page, asset select should be SOL and ETH
- Go to any solana token, assets should be SOL and the token
- You can now share solana swap through the swapper URL
n/a
n/a …
> fix: allow solana assets to be default assets in swapper

- package.json
- src/assets/translations/en/main.json
- src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx
- src/components/MobileWalletDialog/MobileWalletDialog.tsx
- src/components/MobileWalletDialog/routes/DeleteWallet/Backup.tsx
- src/components/MobileWalletDialog/routes/DeleteWallet/Confirm.tsx
- src/components/MobileWalletDialog/routes/DeleteWallet/DeleteWallet.tsx
- src/components/MobileWalletDialog/routes/RenameWallet.tsx
- src/components/MobileWalletDialog/routes/SavedWallets.tsx
- src/components/MobileWalletDialog/types.ts
- src/components/Modal/components/Dialog.tsx
- src/components/Modals/Settings/SettingsList.tsx
- src/components/QrCodeScanner/QrCodeScanner.tsx
- src/context/WalletProvider/MobileWallet/components/MobileCreateTest.tsx
- src/context/WalletProvider/MobileWallet/components/MobileImport.tsx
- src/context/WalletProvider/MobileWallet/components/MobileLoad.tsx
- src/context/WalletProvider/WalletViewsSwitch.tsx
- src/pages/ConnectWallet/MobileConnect.tsx
- src/pages/ConnectWallet/components/WalletCard.tsx
- src/pages/ConnectWallet/components/WalletList.tsx
- src/pages/Dashboard/components/DashboardHeader/DashboardHeaderTop.tsx
- src/plugins/walletConnectToDapps/components/modals/connect/Connect.tsx
- src/plugins/walletConnectToDapps/components/modals/connect/ConnectContent.tsx
- src/state/slices/portfolioSlice/portfolioSlice.ts
- yarn.lock
This reverts commit 7f21d62d8fef0964d13a947e82077a71ebf21f58.
- This adds a new dialog that allows users to easily switch and manage their mobile wallets
- User can edit or delete wallets
- If the current wallet is active they cannot delete
- User can access settings from this new dialog
- Wallet connect modal is usable
- Disabled this system if it's responsive mode as it currently support mobile app only and wallet as vaults on mobile
partially #6440 
Maybe high as users might not access wallets from mobile? But medium because branching isn't so complicated
medium risk
See # Operations part
We will need to merge on develop, then it's testable on develop env using …
> feat: mobile wallet new flow 

- src/lib/market-service/portals/portals.ts
Makes things slightly less annoying while devv'ing.
closes N/A
None
None
> chore: cleanup portals spew

- src/components/MobileWalletDialog/routes/CreateWallet/CreateBackupConfirm.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/CreateSuccess.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/CreateWallet.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/KeepSafe.tsx
- src/components/MobileWalletDialog/routes/DeleteWallet/Confirm.tsx
- src/components/MobileWalletDialog/routes/ManualBackup/ManualBackup.tsx
- Remove dots if opening backup wallet from the wallet list
- Add more dots steps so it's containing all the actual steps for the create wallet flow
- Fix the delete wallet error
closes #8785
Low
- Create a wallet, check the header dots, it should be containing the right amount of steps on each steps
- Delete a wallet, you shouldn't have any errors
- Open the back up modal, steppers shouldn't be shown
n/a
n/a
And delete wallet is fine!
> fix: wallet mobile drawer create flow dots and delete error

- src/components/ManageAccountsDrawer/components/DrawerContent.tsx
- src/components/ManageAccountsDrawer/components/DrawerWrapper.tsx
- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/components/ManageAccountsDrawer/components/SelectChain.tsx
Best effort PR attempt at fixing account imports, adding safe area on top and bottom, reducing table size and change the column layout of the chain list
closes #8769
Low
- Open the manage account modal
- See the styles, it should look fine
- Open the add chain drawer
- Spacing should be good on top and bottom. columns should be fine
- Click on a chain
- Table should be smaller, toggle should be smaller, amount should be shown except if it's really big, you'll see a scroll bar (this is the best effort part)
n/a
n/a
https://jam.dev/c/9368a7a1-78e3-45c7-b9f2-0fcd5d4f3195
> fix: import account style on mobile

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/components/LendingHeader.tsx
Fixes THORChain Discord URL.
Closes https://github.com/shapeshift/web/issues/8814
Low
N/A
URL should point to THORChain Devs Discord.
☝️
☝️
> fix: discord url

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/components/LendingHeader.tsx
> chore: release v1.767.0

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/components/LendingHeader.tsx
fix: discord url that does not expire (#8817)
> chore: release v1.768.0

- src/components/MobileWalletDialog/MobileWalletDialog.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/CreateBackupConfirm.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/CreateSuccess.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/CreateWallet.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/CreateWalletRouter.tsx
- src/components/MobileWalletDialog/routes/ImportWallet/ImportRouter.tsx
- src/components/MobileWalletDialog/routes/ImportWallet/ImportSuccess.tsx
- src/components/MobileWalletDialog/routes/ImportWallet/ImportWallet.tsx
- src/components/MobileWalletDialog/routes/SavedWallets.tsx
- src/components/MobileWalletDialog/types.ts
- src/pages/ConnectWallet/MobileConnect.tsx
- src/pages/Dashboard/components/DashboardHeader/DashboardHeader.tsx
feat: new mobile wallet drawer import flow (#8810)
chore: remove new from nft tab (#8827)
> chore: release v1.770.0

- .env.base
- src/assets/translations/de/main.json
- src/assets/translations/en/main.json
- src/assets/translations/es/main.json
- src/assets/translations/fr/main.json
- src/assets/translations/ja/main.json
- src/assets/translations/pt/main.json
- src/assets/translations/ru/main.json
- src/assets/translations/tr/main.json
- src/assets/translations/uk/main.json
- src/assets/translations/zh/main.json
- src/lib/fees/model.test.ts
- src/lib/fees/parameters/swapper.ts
- src/lib/portals/utils.ts
- src/pages/Markets/components/LpGrid.tsx
- src/pages/Markets/hooks/usePortalsAssetsQuery.ts
- src/state/slices/tradeInputSlice/tradeInputSlice.ts
chore: removing native from the wallet modal (#8842)
chore: update alchemy polygon key (#8846)
chore: change default buy asset to btc (#8835)
fix: markets LP assets fetching (#8809)
fix: ci after fee bump (#8845)
chore: Update Fee Model to increase Max_Fee_BPS to 69 (#8825)
> chore: release v1.771.0

- packages/swapper/src/swappers/CowSwapper/constants.ts
- packages/swapper/src/swappers/CowSwapper/endpoints.ts
While at it, a little polish to make CoW status human-readable.
- relates to #8575
- closes https://github.com/shapeshift/web/issues/8850
None
- CoW status looks good
- ^
- ^
- Prod
- This diff
> fix: make CoW status human-readable

- src/pages/RFOX/hooks/useCurrentEpochRewardsQuery.ts
RFOX Rewards maths were wrong when you did unstake for more than 1 month, because the previous epoch is undefined, so it does: total rewards minus 0 which is then displaying total rewards 
We should do: total rewards minus first known epoch so it displays 0 because the total rewards is supposed to be the same than the first known epoch total rewards
closes #8584
Medium (display issue)
RFOX Pending rewards
- Try with a current active stake
- Try with a full unstake you just did
- Try with an unstake you did months ago (ask 0xean, he should have a pubkey to share to test this special state)
n/a
n/a
> fix: rfox rewards calculation after unstaking

- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
Makes limit orders confirm great again
N/A
None
- Limit doesn't crash on order submition
- ^
- ^
https://jam.dev/c/0f879f7f-849b-4420-9a54-e13f0b2c12df
> fix: limit orders crashing on confirm

- src/assets/translations/en/main.json
Just came across this guy!
N/A
Almost 0
None
None
N/A
N/A
N/A
> chore: rm duplicate key

- src/context/WalletProvider/NewWalletViews/sections/SavedWalletsSection.tsx
The "Add new wallet" button in the new onboarding flow should let its caption wrap text on multiple lines, the caption overflows in certain languages otherwise.
I've fixed similar issues in the past creating and using "sm-multiline" and "lg-multiline" styles in `ButtonStyles` but as this button uses `md` and it's the only case where we're having this issue I preferred to solve this with a property on this specific button.
@reallybeard I do think it would be a good idea to have word-wrapping (`whiteSpace: 'normal'`) on all buttons of all sizes maybe, even if in some cases the paddings/margins don't look as good, it's better than not being able to read the caption no? But I'm not comfortable making such broad changes to the theme, if you could look into it please it would be good?
> High …
> fix: add wallet button overflowing caption

- src/pages/RFOX/constants.ts
Update rFOX IPFS hash for Epoch #7 pending rewards.
N/A
Low
- Ensure pending rFOX rewards are showing for both FOX and ETH/FOX UniV2 LP positions
:point_up: 
:point_up:
> chore: update rfox metadata hash

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderCard.tsx
... instead of a swap icon.
closes https://github.com/shapeshift/web/issues/8752
None
- Chain icon is displayed on limit rows
- ^
- ^
> feat: limit order display chain icon

- packages/swapper/src/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/state/slices/portfolioSlice/utils/index.ts
fix: disable thorchain affiliate fees (#8991)
feat: re-enable KK P2TR (#8951)
> chore: release v1.787.0

- packages/swapper/src/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
> chore: revert "fix: disable thorchain affiliate fees"

- packages/swapper/src/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
chore: revert "fix: disable thorchain affiliate fees" (#8996)
> chore: release v1.788.0

- src/components/EarnDashboard/components/PositionDetails/StakingPositionsByProvider.tsx
fix: earn page redirect to rfox page if provider is rfox (#8994)
> chore: release v1.789.0

- .github/workflows/generate.yml
Regen once a day instead of twice a week on Monday and Thursday
closes https://github.com/shapeshift/web/issues/8783
Low to none, can be reverted in case of rate limits from Coingecko, though highly unlikely as this will be daily and rate-limits are typically rps or more global minute/hourly
- Test cron is correct in [Crontab.guru](https://crontab.guru/#0_9_*_*_*)
None
> feat: daily cron in regen ci

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
Fixes the wrong `isWalletReceiveAddressLoading` check:
`isWalletReceiveAddressLoading` is actually coming from `useReceiveAddress` which considers us loading when actually loading *or* initializing. Initializing however, is truthy when `!wallet`, and indeed, `wallet` is null when in a locked state.
Fixed by only exposing the raw `isLoading` and keeping `isInitialized` internal only, this way, `isLoading` means the receive address is *actually* loading.
closes https://github.com/shapeshift/web/issues/9003
Low
- Ensure there are no swapper receive skeleton on "half-ready" native wallet, play around with connected states and refresh many times over
- Perform …
> fix: swapper skeleton on half-connected wallet

- src/assets/translations/en/main.json
- src/components/HoverTooltip/HoverTooltip.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderCard.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderList.tsx
Limit order list was not really usable as cards were too big compared with all other interfaces, basically this PR implements https://www.figma.com/design/IBz3Fn75GGjXfm89FsymAL/Limit-Orders?node-id=680-7&p=f&t=xF2M9A2L9xvZeRIb-0
- Added a tooltip on status hover to see the expiration date
- I didn't add the menu button but a cross to cancel the order as we don't have any other actions for now
- Made the table header sticky so users can see it at any time
- Massaged responsive
- Added execution price vs price intent
closes #8429
Low
- Play with limit orders, with big lists specially, create a lot of pending limit orders, see history...
n/a
> feat: improve limit order list ux and ui

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
We didn't notice but we did hide the limit order list for no reasons!
Hot spotted
Low
Limit order list should be shown!
n/a
n/a
> fix: make limit orders list great again

- src/assets/translations/en/main.json
This updates the ShapeShift Wallet backup flow, to hopefully fix any confusion around us actually backing up their wallet for them.
closes #8873 
low risk only copy changes
n/a
n/a
Updated in figma here is what the copy was updated to:
https://www.figma.com/design/Ikx1qWAFxlL4TqRmhzkgqI/Mobile-UX?node-id=1095-6094&t=SaPOE6bFk4nAM6ko-0
> feat: update shapeshift wallet backup copy

- src/pages/RFOX/components/TxHistory/RewardTransactionList.tsx
- src/pages/RFOX/components/TxHistory/Rewards.tsx
- src/pages/RFOX/hooks/useLifetimeRewardDistributionsQuery.ts
Pending rFOX reward transaction across multiple staking contracts for the same account will now all display.
closes https://github.com/shapeshift/web/issues/8947
Low
- Ensure pending reward transaction for both FOX and UniV2 ETH/FOX show for accounts that are staked to both
:point_up: 
:point_up:
> feat: show correct pending rfox reward transactions

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputHeader.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/pages/Trade/StandaloneTrade.tsx
Precisely what it says on the box, no limit or claims there, KISS.
- contributes to https://github.com/shapeshift/web/issues/9024
Low
- Regular swapper is still happy
- Mini swapper only displays spot tab
- ^
- ^
https://jam.dev/c/8af8d838-afab-4461-a0a1-63c705dc77b4
> feat: only expose spot on mini swapper

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooter.tsx
- src/components/MultiHopTrade/components/TradeConfirm/components/TradeConfirmSummary.tsx
- src/components/RecipientAddressRow.tsx
Added recipient address at the transaction execution step
closes #9019
None
> feat: show receive address throughout the entire execution flow

- src/components/MultiHopTrade/components/LimitOrderV2/LimitOrderDetail.tsx
- src/components/MultiHopTrade/components/RateGasRow.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter/SharedTradeInputFooter.tsx
- src/components/MultiHopTrade/components/TradeConfirm/components/TradeConfirmSummary.tsx
Fixes some issue re: precision spotted in [release](https://discord.com/channels/554694662431178782/1350000686598717440/1350026531153645620)
closes N/A
Low
Play around with the rate toggle and ensure precision looks sane
- ^
- ^
Spot:
https://jam.dev/c/1a370059-eb02-42af-afe8-d32147f45679
Limit:
https://jam.dev/c/67d4811a-3f3f-47c4-839d-3e9e057fa64d
> fix: precision things

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderList.tsx
- src/theme/theme.tsx
We don't need to redo the scrollbar we have a class handling it already, let's consume it! (DRY)
Spotted myself
Low
- See order list, specially history one, scrollbar and style looks sane!
n/a
n/a
> fix: leverage scroll-container instead of homemade scrollbar on limit orders

- src/pages/RFOX/constants.ts
Update rFOX metadata IPFS hash for epoch #7 reward distribuiton.
N/A
Low
- Ensure March rFOX rewards are showing as distributed
:point_up:
:point_up:
> chore: update rfox metadata ipfs hash

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
Precisely what it says on the box, allows limit quotes to be displayed without a wallet connected, aligning with spot.
closes https://github.com/shapeshift/web/issues/9065
Low/none, loading state removal
- Able to get quotes without a wallet
- ^
- ^
- develop
- this diff
> feat: limit order quotes without a wallet connected

- src/pages/Trade/Trade.tsx
Another path that needs to be excluded from the rewrite url logic that was missed for the mobile view.
closes https://github.com/shapeshift/web/issues/9071
Low
- Ensure `View Orders` routes correctly for limit orders on mobile view
:point_up:
:point_up:
> fix: limit orders view order route mobile view

- src/components/Modals/Receive/ReceiveInfo.tsx
Add a loading state while receive address is loading in the receive modal
closes #8336
None
1. Connect native wallet
2. Go to Wallet Page
3. Open Receive Modal and select Bitcoin
4. Switch account and see loading skeleton while loading
> feat: add loading states while receive address loading in receive modal

- src/Routes/RoutesCommon.tsx
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/LimitOrder/LimitOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/LimitOrderV2/LimitOrderDetail.tsx
- src/components/MultiHopTrade/components/RateGasRow.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedRecipientAddress.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedSettingsPopover.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter/SharedTradeInputFooter.tsx
- src/components/MultiHopTrade/components/TradeConfirm/components/TradeConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/Protocol.tsx
- src/components/MultiHopTrade/types.ts
- src/context/AppProvider/AppContext.tsx
- src/pages/RFOX/constants.ts
- src/pages/Trade/StandaloneTrade.tsx
- src/pages/Trade/Trade.tsx
- src/pages/Trade/types.ts
- src/state/slices/limitOrderSlice/helpers.ts
- src/state/slices/limitOrderSlice/selectors.ts
- src/state/slices/marketDataSlice/marketDataSlice.tsx
- src/theme/styles.ts
feat: limit order quotes without a wallet connected (#9066)
chore: update rfox metadata ipfs hash (#9064)
feat: trade input fixes and tweaks (#9063)
feat: hide custom slippage input when auto is selected (#9058)
fix: reset sell amount on standalone swapper mount (#9055)
feat: prefill limit price mode and direction from the url (#9054)
feat: make limit order better (#9053)
> chore: release v1.793.0

- src/assets/translations/en/main.json
- src/assets/translations/fr/main.json
- src/components/Modals/Receive/ReceiveInfo.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/Text/Text.tsx
- src/pages/Trade/Trade.tsx
- src/state/slices/limitOrderSlice/helpers.ts
feat: support jsx elements instead of placeholders in the translated text component (#9075)
feat: add loading states while receive address loading in receive modal (#9077)
fix: limit orders view order route mobile view (#9072)
fix: make limit orders great again (#9074)
> chore: release v1.794.0

- src/components/MultiHopTrade/MultiHopTrade.tsx
Fixes some issue spotted by @neomaking during release, where sell amount wouldn't be reset when going back and forth between trade and other routes.
closes N/A
Low
- Ensure sell amount is still cleared when going from mini swapper to swapper and vice verse
- Ensure sell amount is now cleared when going from swapper to another page and back
- Ensure sell amount is now cleared when going from mini swapper to another page and back
- Ensure rehydration is still working
- Sanity check swapper e2e for any shenanigans as a paranoia
- ^
- ^
https://jam.dev/c/099211a6-883e-4966-84bd-4e1ef486957f
> fix: swapper sell input/routing shenanigans

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
Simply add another prop `extraContent` to `TradeSuccess` and move the fee discount logic markup one level upper inside `TradeConfirm` instead of sharing it for both scopes
closes #9048
Low
- As OPS: try a trade not involving FOX without having enough fox power (so have fees), see the success screen "could have saved"
- As OPS: try a trade not involving FOX with having enough fox power (so have fees), see the success screen "you saved" with confettis
- As OPS: try a limit order after having selected a quote involving fees from the regular swapper, shoudln't show anything related to fees in success screen
- As engineer: same but you can monkeypatch to do …
> fix: remove could have saved and saved from limit order success

- .github/workflows/bootstrap.yml
- .github/workflows/cloudflare.yml
As noted here: https://github.com/github/docs/issues/15319
And in the github doc here: 
And also confirmed in our CI:
ref_name works for commits, head_ref works for pull requests, we need to use an additional head_ref to trigger the proper  build mode in release
spotted in https://discord.com/channels/554694662431178782/1352448188078100510/1352473093440012359
Low
That's super hard to test without releasing but fix process is pretty straightforward and without risks
n/a
n/a
> fix: release using prod build

- src/pages/Dashboard/components/DashboardHeader/DashboardHeader.tsx
- src/pages/Dashboard/components/DashboardHeader/EarnBalance.tsx
- src/state/slices/portfolioSlice/selectors.ts
What this PR does:
- Aligns things so that all components rely on the same source of truth re: amounts
What this PR does not:
- Dedupe. We've stopped doing this a long time ago, precisely for the purpose of amounts making sense when summed up. This is a forever discussion we've been having, see DM below:
> Ok so update on the DeFi balances thing: I was wrong, we stopped doing deduping for a long time already precisely for the purpose of these two adding up to net worth (though we had a smol bug, fixed it).
> 
> Going forward, if we want to make this actually nice  we gotta rethink this as it now looks right after the bugfix but is still super wrong. Not a concern of https://github.com/shapeshift/web/issues/8559 though, as the ACC is The numbers shown all make intuitive sense!, we should …
> fix: net worth sum of wallet and defi

- src/assets/translations/en/main.json
- src/components/StakingVaults/EarnOpportunities.tsx
does what it says
closes #9141
- Go to any asset page and see the defi section
- No redirect link should be present
> fix: remove see all links in defi part of asset page

- src/AppProviders.tsx
This reverts commit c9b32ad994570c472d7fce5c6a470efc2e70e0cb.
Unblocks release: https://discord.com/channels/554694662431178782/1354288214088745082/1354310448215752765
> revert: fix: global qr code button WCV2 crash (#9137)

- src/assets/translations/zh/main.json
While restoring the functionality of our Gitlocalize platform after the outage, I've noticed that I've missed applying the Chinese translation changes during our last sync when doing it manually. My apologies and thanks in advance for reviewing/merging this out-of-workflow PR to include these translations.
None. Only translations.
None.
> chore: update zh translations

- src/components/FoxWifHatBanner.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/hooks/useSharedHeight.tsx
This reverts commit 934c2233cf58d114b9d7cf2b838d1d03863bac74.
The static width did implement a bug on the asset page with mini swapper
Just spotted
Low
The introduced bug is not here anymore
> revert: fix: auto resize limit order with flex

- package.json
- src/components/Modals/Send/AddressInput/AddressInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/MaxSlippage.tsx
- yarn.lock
fix: address validation inversion (#9262)
feat: thorchain streaming swaps ux fast follows (#9221)
feat: turn the address input on send into a textarea (#9207)
> chore: release v1.807.0

- src/assets/translations/en/main.json
- src/plugins/walletConnectToDapps/components/modals/SessionProposal.tsx
Confirmed with product we're happy with this flow for simplicity's sake, one less click :tada:
closes https://github.com/shapeshift/web/issues/9198
Low to none
- Still able to connect individual accounts to dApps 
- Able to click "Connect All Accounts", which will... well, connect all accounts!
- ^
- ^
https://jam.dev/c/784691e0-d5be-4952-a8f5-5f1e591b66d3
> feat: wc dApps "Connect All Accounts" button

- src/AppProviders.tsx
- src/context/AppProvider/AppContext.tsx
- src/hooks/useTransactionsSubscriber.ts
As discussed in https://github.com/shapeshift/web/pull/9266/files#r2036883873, no reason to keep this a component!
closes N/A
Low, exact same logic, now living as a hook. Paranoia me would say medium, just in case, because of Tx history, though testing this is fairly straightforward.
- Import a fresh wallet and ensure your Tx history still is populated
- Ensure incoming Txs are still coming in
- ^
- ^
https://jam.dev/c/0aee2f07-31a2-4048-ad73-07d9377d7992
> feat: make TransactionsSubscriber.tsx -> useTransactionsSubscriber.ts

- src/AppProviders.tsx
- src/components/Layout/Header/NavBar/NavBar.tsx
- Fixes routes with subpaths being broken in mobile navbar (i.e not the main navbar, but the one under wallet) 
- Reintroduces https://github.com/shapeshift/web/pull/9255, which was wrongly removed in https://github.com/shapeshift/web/pull/9266
closes N/A, spotted in release
Low, the first one is a blatant mistake and the second one is a diff rug
- Navigate to all the nav routes in mobile and ensure we're gucci
- ^
- ^
https://jam.dev/c/52a58d85-412a-4381-87c5-4852e856ced2
> fix: mobile routing fixes

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/StandaloneMultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
This PR:
- fixes dead quotes list routing in standalone swapper 
- fixes borked style in quotes list in regular swapper against prod
closes https://github.com/shapeshift/web/issues/9328
- Quotes List click is working in standalone swapper
- Quotes List (i.e make your viewport smaller to see it) is looking the same as in prod in regular swapper 
- ^
- ^
https://jam.dev/c/10052886-f786-4834-b921-16a3cbe2dfee
> fix: swapper quotes list fixes

- src/AppProviders.tsx
Smol diff regression from https://github.com/shapeshift/web/pull/8924/files#diff-642b012440aeafd61512683e8b249ef64289ae5a0e38ff6a5c0143c4c3b23484R8-R11, bringing in a second react-query provider on top of the existing one.
closes N/A, spotted by large @kaladinlight
Low, that's an obvious dupe
- None really, this was a double provider, but proceed with a very smol app smoke test for the sake of paranoia
https://jam.dev/c/94e3f8d9-83e3-42b4-8932-38b6d94bfaea
> feat: remove double QueryClientProvider

- packages/swapper/src/swappers/JupiterSwapper/endpoints.ts
- packages/swapper/src/swappers/RelaySwapper/RelaySwapper.ts
- packages/swapper/src/swappers/RelaySwapper/constant.ts
- packages/swapper/src/swappers/RelaySwapper/endpoints.ts
- packages/swapper/src/swappers/RelaySwapper/getTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/RelaySwapper/utils/filterRelayAssetIds.ts
- packages/swapper/src/swappers/RelaySwapper/utils/getRelayAssetAddress.ts
- packages/swapper/src/swappers/RelaySwapper/utils/getRelayDefaultUserAddress.ts
- packages/swapper/src/swappers/RelaySwapper/utils/getRelayPsbtRelayer.ts
- packages/swapper/src/swappers/RelaySwapper/utils/getTrade.ts
- packages/swapper/src/swappers/RelaySwapper/utils/relayTokenToAssetId.ts
- packages/swapper/src/swappers/RelaySwapper/utils/types.ts
- packages/swapper/src/types.ts
- src/AppProviders.tsx
- src/components/MultiHopTrade/components/SpotTradeSuccess/SpotTradeSuccess.tsx
- src/hooks/useIsSnapInstalled/useIsSnapInstalled.tsx
fix: you saved negative amounts (#9346)
feat: support bitcoin with relay (#9222)
feat: shared isSnapInstalled polling (#9307)
feat: remove double QueryClientProvider (#9347)
fix: jupiter getSolanaTransactionFees not working and fee estimation to signing time (#9344)
> chore: release v1.815.0

- src/components/Layout/Header/Header.tsx
Unblocks release, actually use the `NotificationCenter` flag.
https://discord.com/channels/554694662431178782/1362188788482179112/1362203943828193391
> fix: use NotificationCenter flag

- .github/workflows/cloudflare.yml
I'm not sure it will fix it but as the old CI is deprecated, I'm pretty sure it broke by itself
Verified it's using the same tokens as the old CI so it shouldn't change, let's try to see if the next release CI is working!
n/a
Low
Nothing to test 
Can't test without publishing a new release
> fix: attempt at fixing fleek ci by using the new cli version

- .github/workflows/cloudflare.yml
- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/types.ts
- packages/swapper/src/swappers/RelaySwapper/utils/getTrade.ts
- packages/swapper/src/thorchain-utils/memo/assertAndProcessMemo.test.ts
- packages/swapper/src/thorchain-utils/memo/assertAndProcessMemo.ts
- src/lib/utils/thorchain/hooks/useSendThorTx.tsx
fix: relay swap impact (#9416)
fix: attempt at fixing fleek ci by using the new cli version (#9426)
feat: handle THOR.TCY MsgDeposit (#9420)
feat: handle tcy memos (#9419)
> chore: release v1.825.0

- src/context/PluginProvider/PluginProvider.tsx
- src/state/migrations/index.ts
That's embarassing... Really don't know how I missed that one :face_palm:
closes https://github.com/shapeshift/web/issues/9429
Low
- Ensure mayachain is actually turned off when the feature isn't enabled (no asset visisble, no network requests, no interaction)
:point_up: 
:point_up:
> fix: honor mayachain feature flag for supported chains list

- src/lib/utils/thorchain/index.ts
- src/pages/TCY/components/Claim/ClaimStatus.tsx
- src/pages/TCY/queries/useTcyStaker.tsx
Waits for THOR to say success to assume we're happy (i.e if we're too fast to invalidate, then we won't see updated TCY staking balance as we'll invalidate before TCY balance has been updated).
While at it, fixes `useTcyStaker` query crashing the app with an active TCY stake.
closes N/A
Low
- Do a TCY claim Tx
- Ensure your balance updates after claim
- ^
- ^
https://jam.dev/c/254bfce2-157c-4f7e-8afe-df0aa4b6f98a
> fix: tcy thor indexing shenanigans

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- src/pages/TCY/components/Overview.tsx
- src/pages/TCY/queries/useTcyStaker.tsx
- fixes tcy asset parsing in THOR branch
- fixes `tcy_staker` query crash
closes N/A
None, both obvious mistakes
- TCY wallet balance is shown
- Both TCY wallet and staked balance are updated on stake
- ^
- ^
https://jam.dev/c/53fbf53e-5123-41fc-a6a5-8c4fa7a3c13d
> fix: tcy eoa balance

- src/assets/translations/en/main.json
- src/components/ReusableConfirm/ReusableConfirm.tsx
- src/pages/TCY/components/Claim/ClaimConfirm.tsx
- src/pages/TCY/components/Stake/Stake.tsx
- src/pages/TCY/components/Stake/StakeInput.tsx
- src/pages/TCY/components/Unstake/UnstakeInput.tsx
- Adds a notice to let users know the claim will automatically stake
- Small clean up on the other footers of stake/unstake
closes #
low risk
Don't have any claims to actually view this, used a different component to render.
> fix: add tcy claim notice

- src/lib/market-service/market-service-manager.ts
- src/lib/market-service/market-service.test.ts
- src/lib/market-service/tcy/tcy.ts
- src/lib/market-service/tcy/tcyMockData.ts
Adds actual market-data and market-cap. Note, this does not add volume just yet.
closes N/A
Low to none
- THOR.TCY price looks sane against https://indexer.thorchain.shapeshift.com/v2/pool/THOR.TCY `assetPriceUSD`
- Market-data looks sane against https://indexer.thorchain.shapeshift.com/v2/pool/THOR.TCY (note, assetDepth is in RUNE notation and you need to remove 8dp when calculating `assetDepth` * `assetPrice`)
> feat: tcy market-data

- src/pages/TCY/components/Claim/ClaimConfirm.tsx
Title says it all - if trying to claim an underlying token position, said token balance is currently used to check against tx fee + dust which is obviously wrong and will cause wrong errored states.
closes N/A, spotted in release
None
- Try and claim with a token underlying position (reedz has one he is testing for in release, tested this one as well with that seed) 
- Confirm you can continue to claim
- Code looks sane
- ^
- ^
> fix: tx fee checks over native balance vs. asset balance

- .env.development
Dev endpoints currently sad, temporarily reverting to prod
closes N/A
None
- THOR XHRs are happy with default dev server dev MODE (minus the obvious expected failures e.g 404s)
- None, touches dev endpoints only
https://jam.dev/c/958d350e-b795-4994-b418-9e9f065a94dd
> feat: use prod thorchain endpoints in dev env

- src/assets/translations/en/main.json
Unblocks release https://github.com/shapeshift/web/pull/9511, achieves what https://github.com/shapeshift/web/pull/9510 should have.
> fix: tcy claimed amount, fr

- src/assets/translations/en/main.json
- src/pages/TCY/components/ReusableStatus.tsx
fix: tcy claimed amount (#9510)
> chore: release v1.833.0

- src/components/MultiHopTrade/components/SpotTradeSuccess/components/YouSaved.tsx
This PR updates the `YouSaved` component on the trade success screen with an animated gradient background (blue/pink), adds a bolt icon, and adjusts text colors for better visibility.
closes #9335 
Low Risk. UI changes are isolated to the `YouSaved` component. No impact on core logic or transactions.
>
> None.
1.  Complete a trade that shows the "You Saved" card.
2.  Verify the new animated gradient background, bolt icon, and text color changes.
3.  Ensure the confetti animation and component responsiveness are unaffected.
To test:
1.  Perform a trade resulting in savings.
2.  On the success screen, check the "You Saved" card for:
*   Animated blue/pink gradient background.
*   Lightning …
> fix: trade fee ui update

- src/context/WalletProvider/NewWalletViews/NewWalletViewsSwitch.tsx
Fixes the left menu responsive width and adds some spacing around the modal so it never touches the border of the viewport
closes #9365
Low
- Try to look at the wallet modal on responsive (not on mobile app)
- Try to look the wallet modal using the ipad mini responsive breakpoint
- Try to look the wallet modal on desktop breakpoints
All the view should be properly displayed!
n/a
n/a
https://jam.dev/c/10169d2e-1147-4a11-b4e8-2fad6ce455ee
> fix: tablet wallet modal layout

- src/components/Modals/FiatRamps/FiatRampsModal.tsx
- src/components/Modals/FiatRamps/views/Overview.tsx
Add a header with title + close button in the fiat ramp modal
Also make it full screen size on mobile as the user should be focused on it (it's a common practice, we should do the same for the swapper bits at some points I think)
And make it normal size on desktop
closes #9300
Low
- Go to the FOX ecosystem page
- Click on the buy button
- Test both mobile and desktop views
n/a
n/a
> fix: onramp modal width and close button

- .env.development
Revert of https://github.com/shapeshift/web/pull/9496, just so that we don't forget to!
closes N/A
None
- dev server THOR calls are happy with the dev endpoints
- None
> feat: use dev thorchain endpoints in dev env

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
The same as https://github.com/shapeshift/web/pull/9539, but for LP.
closes N/A
Low
- Hard to test since no chain is currently halted (only pools are), but ensure you can still deposit/withdraw from enabled LP pools
- ^
https://jam.dev/c/3a34e4af-d69e-4111-b6a5-147e9bf1099f
> feat: thorchain LP chain halt checks

- vite.config.mts
Kick chakra from the ui chunk:
- Chakra might have circular dependencies/hoisting issues
- or the import order is not working as expected if it's extracted into it's own chunk
This fixes the latest build issue we had after reown PR passed, as chakra is inside the main bundle the order is preserved as expected
Consequences: it adds around 2mb of sourcemaps into the mainchunk but js code isn't so big, I didn't see a big bump for the main chunk so, it should be safe
Spotted while trying to release (initially we wanted to revert https://github.com/shapeshift/web/pull/9589)
Medium
- The app should work as expected, specially when using `yarn preview:prod` and …
> fix: add back chakra to the main chunk to preserve import orders

- src/context/WalletProvider/NewWalletViews/NewWalletViewsSwitch.tsx
- src/context/WalletProvider/NewWalletViews/sections/InstalledWalletsSection.tsx
What the box says, this does.
closes https://github.com/shapeshift/web/issues/9604
None
- Wallet modal with mipd wallets installed should still display installed wallets
- Wallet modal without mipd wallets installed (e.g incognito) should not dispaly the "Installed" section altogether
- ^
- ^
- Incognito
- mipd wallets installed
> feat: don't display installed wallets section when none are installed

- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
Make TCY max sends actual maxes and not random amounts.
closes https://github.com/shapeshift/web/issues/9631
- TCY max sends are actual max sends
- ^
- ^
- This diff
https://jam.dev/c/33f80a80-4c09-49f7-974f-a122c05e18dd
- develop
https://jam.dev/c/5e566ab0-9010-425b-bae2-be34de6a51c9
> fix: tcy max sends

- packages/swapper/src/swappers/RelaySwapper/utils/getTrade.ts
Relay protocol had some cases were it shouldn't be added:
- If you are swapping from one chain to another chain it should never add any fees as protocol fees, the only usecase is if you are swapping on the same chain but sellAsset is not the native currency, as relay use the native currency for the fees outside of the swap, in this case we should verify the balance
closes #9640
Medium
- Try to swap from UNI on Ethereum to USDC on Solana without having any USDC on Ethereum, you should be able to swap
- Smoke some other swaps if you want
- 
https://jam.dev/c/ead69868-d5a0-47ac-8835-ce977eed6934
> fix: wrong relay protocol fees

- src/plugins/walletConnectToDapps/components/header/ConnectDapp.tsx
- src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
Adds overflow hidden + textOverflow ellipsis to a few spots to stop the dApp button from leaking text everywhere on small or resized screens.
closes #9691 
Risk that the dApp button might render weirdly.
Test resizing the window and observing the behaviour of the "connect to dApp" button on both mobile and desktop. Test with 0, 1, 2 and 3 dApps connected.
https://jam.dev/c/33f347d0-89c4-45bc-a31d-16c361eb24ce
https://jam.dev/c/6e726db5-8547-4211-b87c-962ec999cdbc
https://jam.dev/c/a36d7c4c-3eca-4a4c-be41-c6faedea923a
> fix: dApp button getting squished and text leaking out

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/QuoteList/QuoteList.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/QuoteSortSelector.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedSettingsPopover.tsx
- src/components/MultiHopTrade/components/WithBackButton.tsx
- src/components/StakingVaults/hooks/useFetchOpportunities.tsx
- src/pages/Dashboard/components/DashboardHeader/WalletBalance.tsx
- src/plugins/walletConnectToDapps/components/header/ConnectDapp.tsx
- src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
- src/react-queries/queries/opportunities.ts
- src/state/slices/tradeQuoteSlice/hooks.ts
fix: dApp button getting squished and text leaking out (#9730)
feat: improve the swap quote sort UI (#9639) (#9685)
feat: show net worth progressively with dynamic chains loaded tooltip (#9692)
> chore: release v1.854.0

- src/pages/RFOX/components/Stake/Bridge/hooks/useRfoxBridge.ts
RFOX bridges are borked because we are sending HEX value which should be a decimal
We can fix this by using the exact same workflow as we do in the swapper which is effectively working as intended
closes #9772 
Low
- Try to bridge from Eth to Arb using the RFOX widget on the rfox page
> fix: bridge from ethereum to arbitrum with rfox

- packages/swapper/src/thorchain-utils/getL1RateOrQuote.ts
- src/pages/RFOX/components/Stake/Bridge/BridgeStatus.tsx
- src/pages/RFOX/components/Stake/Bridge/hooks/useRfoxBridge.ts
fix: bridge from ethereum to arbitrum with rfox (#9773)
feat: rfox bridge max dp in "Send <amount> FOX" (#9771)
fix: thorchain utxo Tx use fast sats/B (#9769)
> chore: release v1.858.0

- packages/swapper/src/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/utils/test-data/setupSwapQuote.ts
- packages/swapper/src/types.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteOrRateInput.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/pages/RFOX/components/Stake/Bridge/hooks/useRfoxBridge.ts
Found this leftover from https://github.com/shapeshift/web/pull/8350 following Li.Fi removal - see PR description for what it solved back then - which isn't consumed anymore.
closes N/A
Low to none - dead code
- For paranoia purposes, do a smol sanity check of any swapper of your choosing and ensure you can still execute a trade
- ^
- ^
> feat: swapper cleanup originalRate

- packages/swapper/src/constants.ts
Another dead one re: swapper chains support, wasn't used before the predicates removal, and still isn't, not sure if it ever was?
closes N/A
None, dead code
- CI is happy
- ^
- ^
> feat: remove swapper supportedChainIds

- packages/swapper/src/swappers/ButterSwap/endpoints.ts
- packages/swapper/src/swappers/ButterSwap/swapperApi/getTradeQuote.test.ts
- packages/swapper/src/swappers/ButterSwap/swapperApi/getTradeQuote.ts
- packages/swapper/src/swappers/ButterSwap/types.ts
- packages/swapper/src/types.ts
Address non-functional feedback from initial butter review.
N/A
Minimal
None
Butter swapper should continue to work, no functionality changes here.
👆
N/A
> chore: more butter fixes

- src/pages/RFOX/constants.ts
- src/pages/RFOX/hooks/useCurrentApyQuery.ts
Update rFOX metadata IPFS hash and improve the apy calculation to use better variable naming and ensure no 0% apy edge case at the start of the new epoch and before the IPFS hash is updated.
N/A
Low
- Ensure pending rfox rewards are displayed
- Ensure apy is showing again
:point_up:
- Test apy calc with previous epoch with the following patch:
```
--- a/src/pages/RFOX/constants.ts
+++ b/src/pages/RFOX/constants.ts
@@ -13,7 +13,7 @@ export const withdrawEvent = getAbiItem({ abi: RFOX_ABI, name: 'Withdraw' })
export const IPFS_GATEWAY = 'https://gateway.pinata.cloud/ipfs'
-export const CURRENT_EPOCH_IPFS_HASH = …
```
> chore: update rfox ipfs hash and apy calc

- packages/swapper/src/cowswap-utils/constants.ts
- packages/swapper/src/cowswap-utils/index.ts
- packages/types/src/cowSwap.ts
~~closes N/A, @twblack88 you snooze you looze~~
closes https://github.com/shapeshift/web/issues/9896
Low/None
- Able to place limit orders on Avalanche/Polygon with CoW
- Able to do swaps on Avalanche/Polygon with CoW
- ^
- ^
- Spot
https://jam.dev/c/5f98b136-3d40-426b-b336-267b22c94573
- Limit
https://jam.dev/c/c32bc881-1642-4531-b224-e72e205cac37
> feat: cow support avalanche and polygon

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderList.tsx
The limit order history list was not taking the full height of the mobile, fixed that as well as adding some safe area to it so it doesn't go under the bottom bars
closes #9900
Low
- Go on mobile limit history tab and see the height is taking the whole space of the mobile
- Also verify that the last elements are accessibles
n/a
n/a
> fix: limit orders history mobile height

- src/Routes/RoutesCommon.tsx
- src/components/AccountDetails.tsx
- src/components/AccountHeader/AccountHeader.tsx
- src/components/Equity/EquityAccountRow.tsx
- src/pages/Accounts/AccountToken/AccountBalance.tsx
- src/pages/Accounts/AccountToken/AccountToken.tsx
- This adds a new route for mobile that removes the dashboard header
closes #
low risk
Switch to Mobile View: Shrink your browser to mobile size.
Navigate: Go to the Wallet page.
Select Asset & Account: Tap on an asset, then choose an account.
Verify UI:
You should see:
A back arrow
The balance
Action buttons
Test Back Navigation: Tap the back arrow — it should return you to the asset page.
Check Desktop: On desktop size, everything should look the same.
Note on Resizing: If resizing from desktop to mobile, ignore visual glitches — media queries don’t reset cleanly mid-session.
shots (if applicable)
> fix: remove tabs on account mobile for mobile

- src/pages/Dashboard/components/DashboardHeader/MobileUserHeader.tsx
This adds a chevron to the wallet header so user know they can tap it to open the wallet switcher.
closes #
low risk
On the mobile app or mobile web, at the top of the screen you'll see a chevron next to the wallet name.
> fix: add chevron to the wallet header

- src/components/MultiHopTrade/components/LimitOrder/hooks/useLimitOrders.tsx
- src/components/MultiHopTrade/components/TradeInput/components/Claim/hooks/useArbitrumClaimsByStatus.tsx
- src/context/AppProvider/AppContext.tsx
- src/context/AppProvider/hooks/useAccountsFetch.tsx
- src/hooks/useBridgeClaimNotification/useBridgeClaimNotification.tsx
- src/pages/RFOX/hooks/useGetUnstakingRequestsQuery/index.ts
Reverts two adjustments to the market network requests to fix markets page not fetching on fresh incognito.
Revert of https://github.com/shapeshift/web/commit/0d09e991ae2835c4037208c9219cd2016374bbb5
Revert of  https://github.com/shapeshift/web/commit/a2536a4d7c6a2251258adb4c29ad03427e8a82a4
Flagged in pre deploy testing here
https://discord.com/channels/554694662431178782/1395305058396274691/1395543848847151125
closes #
To test:
1. In develop branch, open the markets tab in incognito with no wallet connected to confirm it does in fact show zeroes across the board.
2. Check out this branch and refresh, should fetch markets data
3. Try closing and …
> fix: revert markets change

- src/components/AccountDetails.tsx
- src/pages/Accounts/AccountToken/AccountBalance.tsx
Removed the flaky logic where we can replace the current goBack path, by leveraging `navigate(-1)` everywhere so users go back to the previous page they were on
As well as removing the header which is now a duplicate considering we have a normal back behavior
closes #10003 
Low
- Go to an asset page, click on the account button, on account page you should be able to click on the "go back" button and then it should go back to the previous page you were on
https://jam.dev/c/61427ae3-8e26-491d-af30-8650ebf20261
> fix: go back behavior on account page and account list page

- src/hooks/useActionCenterSubscribers/useSwapActionSubscriber.tsx
This change ensure's we're using the correct txlinks on our swap action cards in the action center. Particularly on arbitrum bridge swaps (which are currently broken in prod).
closes #9996 
Low - medium, could break tx links on swaps in the action center.
Test a variety of different swaps on different protocols in different directions. Ensure that whenever you click "view transaction" in the action centre it's taking you to the "freshest" transaction. That means the buy transaction if it's finished, or the sell transaction if it's pending.
:point_up:
:point_up:
https://jam.dev/c/54c2db1c-ae41-423b-a81d-ea97e5afac28
> fix: ensure we use the correct tx link in action center swap action cards

- src/components/Layout/Header/NavBar/DrawerWallet.tsx
- src/components/ReactTable/InfiniteTable.tsx
- src/pages/Home/WatchlistTable.tsx
- src/state/slices/marketDataSlice/selectors.ts
- src/state/slices/portfolioSlice/selectors.ts
fix: stop the asset icons from flashing when you expand related assets (#10540)
feat: optimise the wallet drawer so it's smooth (#10508)
> chore: release v1.914.0
