shapeshift/web

- src/components/Trade/TradeConfirm/TradeConfirm.tsx
- src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Approve.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Approve.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Overview/Claim/ClaimStatus.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx
- src/features/defi/providers/univ2/components/UniV2Manager/Deposit/components/Approve.tsx
- src/features/defi/providers/univ2/components/UniV2Manager/Withdraw/components/Approve.tsx
- src/hooks/usePoll/usePoll.tsx
- src/lib/poll/poll.test.ts
- src/lib/poll/poll.ts
We've identified an issue regarding the polling mechanism used to fetch updates during transaction execution. In the current implementation, polling continues to take place even after the associated React component has been unmounted, resulting in shenanigans such as error toast and page redirects where for trades that exceed the maximum attempts. 
This issue was identified during testing today where a thorchain trade took longer than 50 minutes to execute. MBMaria was setting up a different trade and an error toast appeared, falsely indicating an error on the current page.
Two fixes are implemented in this PR:
1. cancel polling on unmount. This is abstracted with a hook
2. allow infinite polling for tx updates
NA
Moderate risk for all pages using polling.
Test usages of poll around the …
> fix: cancel polling on component unmount

- src/state/apis/zapper/zapperApi.ts
- src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
This PR refactors the read-only opportunities to bring in the concept of claimable assets, which exist as their own asset e.g claimable TOKE, which exists as its own asset, and thus, opportunity, see:
https://etherscan.io/address/0x79dd22579112d8a5f7347c5ed7e609e60da713c5
- Upserts claimable assets as a wrapped asset into the portfolio if applicable
- Fixes incorrect `underlyingAssetId` for these, which were making us ditch these assets in `selectAggregatedEarnUserStakingOpportunitiesIncludeEmpty` `uniqBy`, since we use the wrong underlying AssetId for these i.e the one of their wrapped asset, which may also exist as its own opportunity
- While at it, improves the `activeResults` / `inactiveResults` heuristics in `selectAggregatedEarnUserStakingOpportunitiesIncludeEmpty` to consider …
> fix: claimable assets as opportunities

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useHopHelper.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
- src/state/slices/swappersSlice/selectors.ts
- src/state/slices/swappersSlice/swappersSlice.ts
- src/test/mocks/store.ts
Wire up receive address for new swapper architecture.
Removes `receiveAddress` from the store, as there is no value gained by putting it into a slice and then getting it back out again.
N/A
Small - does not affect any non-feature flagged code paths.
We should now get quotes again with the multi hop flag on.
N/A
N/A
> chore: wire up receive address

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeQuotes/TradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useAccountIds.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useHopHelper.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
- src/components/MultiHopTrade/hooks/useSelectedQuoteStatus.tsx
- src/state/slices/portfolioSlice/selectors.ts
- src/state/slices/portfolioSlice/utils.ts
- src/state/slices/swappersSlice/selectors.ts
- src/state/slices/swappersSlice/swappersSlice.ts
- src/state/slices/tradeQuoteSlice/helpers.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/test/mocks/store.ts
Fixes broken trade quotes in the new exchange client UI. Root cause of issue was circular dependency between the following:
- account ids
- receive address
- trade quotes
Account ids are moved into redux with high-risk logic contained in actions, with defaults contained in selectors. Zero logic relating to account ids in hooks.
Removed duplicate calls to fetch trade quotes.
NA
Not user facing -> zero risk
BUT @engineers please review account ID logic and overall approach as this will need to be fit for purpose at a high level.
Trade quotes fetch with multi-hop flag enabled.
See above, RE account ID logic.
No action required.
> fix: broken trade quotes in exchange client

- src/components/MultiHopTrade/hooks/useTradeExecution.ts
- src/components/MultiHopTrade/hooks/useTradeExecution/helpers.ts
- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/LifiSwapper/LifiSwapper2.ts
- src/lib/swapper/swappers/ThorchainSwapper/ThorchainSwapper2.ts
Re-adds useTradeExecution hook for new swapper architecture. Currently a placeholder implementation while we implement a ui to make this testable.
Includes updates to `checkTradeStatus` which were identified when building the trade confirmation UI. Again, not testable yet and not user facing.
closes #4776
no risk, not user facing
Not testable currently, this needs to be merged to facilitate building the UI to test this :P
See above
See above
> feat: added useTradeExecution hook for new Swapper2

- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/LifiSwapper/LifiSwapper2.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/ThorchainSwapper2.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/state/apis/swappers/lifiSwapperApi.ts
- src/state/apis/swappers/thorSwapperApi.ts
Separate swapper API methods to avoid the otherwise impending circular dependancies we'll get when we move these into a single RTK endpoint for API consolidation and end-state representation.
N/A
Small - no logic changes, and all changes are behind a flag.
Swapper behind flag should still get quotes.
☝️
☝️
N/A
> refactor: separate swapper api methods

- package.json
- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- yarn.lock
Fixes trade status polling in new implementation of exchange client.
Current implementation is using a timstamp as the txid when fetching the trade status. 
This PR introduces the ability to use either txId or tradeId when fetching trade status from the api. This is because lifi requires trade ID to fetch a preformed request from the database, while thor requires a txid to fetch from the api. The client shouldnt know which is used as this is swapper specific. Instead, both are submitted and the swapper will use one to fetch the status.
NA
no risk, not user facing
Check thor trades complete in new exchange client (multi hop enabled)
See above
new swapper thor trades confirming in UI (dont mind the borked UI will fix in follow up)
> fix: thorchain transaction status polling for exchange client

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/components/MultiHopTrade/types.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/state/apis/swappers/helpers/getInputOutputRatioFromQuote.ts
- src/state/apis/swappers/helpers/getLifiTradeQuoteApiHelper.ts
- src/state/apis/swappers/helpers/getThorTradeQuoteApiHelper.ts
- src/state/apis/swappers/index.ts
- src/state/apis/swappers/selectors.ts
- src/state/apis/swappers/swappersApi.ts
- src/state/apis/swappers/types.ts
- src/state/helpers.ts
- src/state/slices/tradeQuoteSlice/helpers.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/test/mocks/store.ts
Consolidates swapper endpoints into one.
- Handles race conditions by adding a `lastRequestStartTime` property to the `tradeQuoteSlice`, and checking/updating it's value in the `setQuotes` action. This is handled "client-side" and left out of the RTK endpoint to be more end-state ready.
- Stored quotes in the slice for now, will experiment with pulling directly from the cache in another PR.
N/A
No risk to production, medium risk to the exchange architecture flagged code paths.
N/A
Ensure we still get quotes as expected, and that the `tradeQuoteSlice` stores quotes under the `quotes` key.
Ensure that the race-condition handling functions as expected.
N/A
N/A
> chore: consolidate swapper endpoints into one

- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/getTradeTxs/getTradeTxs.ts
Reimplements `checkTradeStatus` for thorchain `Swapper2` to resolv circular dependincy caused by original implementation importing rest of legacy swapper.
Opted to create a fresh implementation based on ThorChainSwapper class method to ensure zero change to production facing code. 
Monads not used as they are for user facing error messages in quotes, and this has special error handling inside the poller.
NA
No risk, not user facing
Check thor trades complete (green check mark) using new swapper
See above
> fix: reimplement checkTradeStatus for thorchain swapper

- src/components/Trade/hooks/useAccountsService.tsx
Fixes the "no receive address" bug in production.
Issue is caused by the `updateSelectedSellAssetAccountId` and `updateSelectedBuyAssetAccountId` reducers not firing again after being cleared by changing assets.
Closes https://github.com/shapeshift/web/issues/4850
Small surface area, but this impact of us getting anything related to accounts wrong is substantial.
Attempt to trade into ETH by switching assets on initial load. It should no longer say "no receive address".
Check that the seleted account id values in the redux swapper store are _always_ what we expect when changing assets, swappers etc.
☝️
N/A
> fix: initialise selectedBuyAssetAccountId & selectedSellAssetAccountId

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
Wire up some of the missing/hardcoded fields in the exchange API.
- Gas for the selected swapper in the unexpanded view
- Fiat amount for the "You get" section
- Rate for the selected swapper in the unexpanded view
N/A
Very small - all changes are behind the "multi-hop" feature flag.
None needed by ops.
With the multi-hop flag enabled, we should now show:
- Gas for the selected swapper in the unexpanded view
- Fiat amount for the "You get" section
- Rate for the selected swapper in the unexpanded view
N/A
> feat: wire up exchange UI

- src/lib/swapper/swappers/utils/helpers/helpers.test.ts
- src/lib/swapper/swappers/utils/helpers/helpers.ts
Fixes `normalizeAmount` rounding inputs up and making ZRX XHRs potentially fail on ERC-20s send maxes, since, depending on the actual balance for that address, the sellAmount we might be requesting might be off by a few weis from the actual balance of the address.
Note, at this point, `normalizeAmount` doesn't do much anymore and the new tests have been added to validate the implementation - we might want to ditch it entirely.
closes https://github.com/shapeshift/web/issues/4879
None, does the same thing the original implementation intended to, minus the rounding.
- ZRX quotes are happy, including with max. trades
- 1inch quotes are happy, including with max. trades
- ☝🏽 
- ☝🏽 
Postman replays have been redacted to keep only the `sellAmount` - note how the failing one on the current …
> fix: normalizeAmount should not round amounts up

- src/lib/swapper/swappers/LifiSwapper/executeTrade/executeTrade.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getNetworkFeeCryptoBaseUnit/getNetworkFeeCryptoBaseUnit.ts
- src/lib/utils/evm.ts
lifi fees were broken upstream and lifi swapper has not been update to use common evm utils, update and use our own gas estimations
https://discord.com/channels/554694662431178782/1124366018337320990/1124366021407559803
Med
- validate working lifi swaps across supported evm chains (no stuck txs)
- verify the estimated gas shown on the trade confirm screen is close in value to the gas shown on the broadcasted transaction in etherscan
- ensure eip1559 fees are being used now if the wallet supports it
:point_up: 
:point_up:
> feat: lifi use common evm utils

- src/assets/translations/en/main.json
- src/components/Modals/FeedbackSupport/FeedbackSupport.tsx
Now that canny.io has some traction this PR adds it to the feedback modal.
Click link and make sure it goes to canny.
> chore: adding canny link to support modal

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ManualAddressEntry.tsx
- src/components/MultiHopTrade/hooks/useActiveQuoteStatus.tsx
- src/components/MultiHopTrade/hooks/useQuoteValidationErrors.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
- src/state/apis/swappers/selectors.ts
- src/state/slices/swappersSlice/selectors.ts
- src/state/slices/swappersSlice/swappersSlice.ts
- src/test/mocks/store.ts
Adds manual receive address functionality to the new exchange swapper.
It's functionality is intended to match that in the production implementation.
Closes https://github.com/shapeshift/web/issues/4841
Super high. Something going wrong here can mean user funds ending up at an address that they do not control. Test accordingly 🙏
Ensure that the `manualReceiveAddress` value in the `swappersSlice` is always exactly what it is expected to be.
Play with supported and non-supported receive assets for the wallet.
Not needed yet - will be tested as part of the full suite of testing for the new exchange swapper.
> feat: add manual receive address to exchange swapper

- src/components/LanguageSelector.tsx
- src/pages/ConnectWallet/ConnectWallet.tsx
- Adds a language selector dropdown menu on the top right of the Connect page. For cases where the language detection fails/is not accurate, allows the user to choose their language from the start.
- Adds tracking for that language selector under the `Click` event element `Language Selector` and records the selected language in the `selectedLanguage` property.
N/A
Low. Adds an element on the Connect page, so test for visual changes.
- Access the Connect page as a first time user or existing user and verify that the default language or user's lanague is selected.
- Attempt to change the language and connect, language must be preserved based on the user's selection. 
☝️ 
☝️ 
Desktop resolution:
Mobile (default detection to French (Français):
Mobile while changing language:
Mobile after …
> feat: language selector on connect page

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
- src/state/slices/swappersSlice/swappersSlice.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
This fixes:
- If the input amount is 0, the 'you get' amount will now also be 0. This accommodates swappers that do an initial dummy quote to get the rate when no amount is entered.
- Send max button is now removed, as approved by Product. It's tricky and not a necessary problem to solve right now.
- Handles the same asset being selected for both the buy and the sell assets, gracefully swapping them in such cases.
- Fixes the crypto amount miner fee on the trade confirm by fixing the logic in `selectNetworkFeeRequiresBalance`
N/A
Ensure the scenarios listed in the PR description above are no longer issues.
☝️
No testing needed at this time, this is all behind the multi-hop feature flag.
N/A
> fix: various exchange swapper fixes

- src/pages/Missions/Mission.tsx
Minor tweak for the Missions cards for longer copies (translations), likely better if @reallybeard checks these changes visually.
- Fixes the overflowing texts to go on multiple lines and align correctly in the Mission cards.
- Use the user's locale in `dayjs` to display the correct language for duration of ongoing missions in Mission cards.
Low. Only minor visual fixes and correct usage of the user's language for duration.
Check the visual rendering of mission cards throughout the app in the supported languages. The should either be on a single line when the copy is short enough or span on multiple lines and not overflow above other elements if they are long.
☝️ 
☝️ 
Before (CTA in the right colum):
Before Missions page (problem circled in red)
After CTA (French)
After CTA (English) …
> fix: mission cards overflowing copies and duration locale

- src/components/AssetIcon.tsx
- src/components/Layout/Header/GlobalSearch/AssetResults/AssetResult.tsx
- src/components/MultiHopTrade/components/Approval/Approval.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
- src/components/StakingVaults/Cells.tsx
- src/components/TransactionHistoryRows/components/AssetTransfer.tsx
- src/features/defi/components/Approve/PairIcons.tsx
- src/features/defi/components/PairIcons/PairIcons.tsx
- src/lib/swapper/swappers/LifiSwapper/LifiSwapper.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/constants.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getMinimumCryptoHuman/getMinimumCryptoHuman.ts
- src/pages/Missions/Mission.tsx
- src/pages/Missions/Missions.tsx
- src/state/slices/swappersSlice/swappersSlice.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
fix: mission cards overflowing copies and duration locale (#4935)
feat: add network icons (#4933)
fix: readd fox army card as ongoing mission (#4932)
feat: 0 minimum for same-chain Li.Fi swaps (#4928)
fix: disable account selection on no cross-account trade support for multi-hop <TradeInput /> (#4929)
fix: wait for form submission before approve to confirm routing in multi-hop (#4927)
fix: various exchange swapper fixes (#4924)
> chore: release v1.379.0

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/constants.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/test/mocks/store.ts
This PR brings execution of multi-hop trades i.e keeping track of the current active step, and incrementing it as one step completes.
Note, this is a first implementation so we can toggle the multi-hop flag. Added a bunch of comments / renames to make it clearer we're currently missing the concept of step granularity, which we won't necessarily need for the exchange client, but will need for the fully fledged multi-hop swapper.
i.e `buyTxHash`, `sellTxHash`, and `status` (renamed to `tradeStatus`) currently refer to the first/last hop Txs, and status refers to the hollistic trade status, *not* the step one, see this bit:
https://github.com/shapeshift/web/blob/361912babf1f8e25a226259863ab81ce24ba9876/src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts#L158-L172
- Last …
> feat: multi-hop trade execution

- src/components/MultiHopTrade/MultiHopTrade.tsx
bug was introduced here https://github.com/shapeshift/web/pull/4921
clicking the confirm button on the trade input screen would route to `?#/trade` causing a page refresh
this fixes it and correctly routes to `#/trade/confirm` (note the lack of `?`)
we're not really sure why this fixes it, but a key shouldn't be necessary on an only child component, as they don't have to compete with their siblings for their parents love.
closes #
isolated to multi hop swapper
1. fresh load of the page, go to the trade route
2. setup a trade and click confirm
3. note the page does not refresh and the url takes you to `/trade/confirm`
👆
👆
n/a
> fix: remove key causing crash on confirm

- src/lib/swapper/swappers/OsmosisSwapper/utils/helpers.ts
Handle calling Osmosis's `getTradeQuote` on unsupported assets by using monadic error handling to gracefully catch.
See screenshots below for console errors.
N/A
Small risk to Osmosis quotes/trades.
Osmosis swapper should still get quotes and execute trades as expected.
We were only throwing when the multi-hop flag was on. The console errors should now be gone.
Osmosis swaps should work as expected.
> fix: osmosis error handling

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
_Actually_ fixes the router rug on clicking trade preview.
tl;dr, chrome thinks the form submission is a GET request if the `onSubmit` isn't wrapped in it's special helper.
N/A, but fixes what https://github.com/shapeshift/web/pull/4947 tried to fix.
Small.
With the multi-hop flag on, select a non-fee EVM asset, get a quote, and click "Preview Trade". It should no lnoger change routes and re-render.
☝️
☝️
N/A
> fix: chrome router hijack rug

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
We currently show that something is "-x% more expensive". The negative here doesn't make sense.
Note, this is only applicable to the swapper behind the multi-hop flag.
N/A
Very small.
Get a quote from multiple swappers with the multi-hop flag on, note that there is no longer a minus sign in front of the percentage symbol.
☝️
Nothing to test yet.
> fix: invert "more expensive" label

- src/components/AccountDetails.tsx
- src/components/AssetAccountDetails.tsx
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/pages/Accounts/AccountToken/AccountToken.tsx
- src/pages/Dashboard/DashboardSidebar.tsx
- src/plugins/foxPage/components/AssetActions.tsx
Add exchange swapper to all routes (though still behind a feature flag).
This means that when the multi-hop fuature flag is enabled, all instaces of the existing swapper will be replaced by the exchange version.
Still do to:
N/A
Small
Check all places that the swap widget is shown, and ensure it looks and behaves as expected.
- Dashboard sidebar
- Account details
- Asset account details
- Account token
- Trade page
- Fox page
☝️
N/A
N/A
> chore: add exchange swapper to all routes

- src/components/AssetHeader/AccountLabel.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/state/slices/portfolioSlice/utils.ts
Fixes the Breadcrumbs string for Accounts Transaction History pages so they display the chain name. Previously they displayed the fee asset name (which can be different from the chain name) and also it had been broken (see before screenshot below) since #4339 (when the path to `/accounts/` changed to `/dashboard/accounts/`).
N/A
Low.
Check the full transaction history for specific accounts on various chains. These pages are accessible only for assets which have a long enough history of transactions, you can access them by going in the Dashboard, then Wallet, then choose a chain, then expan the accounts, then click on the "..." icon and "View account" (or simply on the account for UTXO chains), then on the Account page scroll down to the Transaction History. If there are enough transaction …
> fix: accounts breadcrumbs with chain name

- src/components/AccountDetails.tsx
- src/components/AssetAccountDetails.tsx
- src/components/AssetHeader/AccountLabel.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/lib/address/address.ts
- src/lib/swapper/swappers/OsmosisSwapper/utils/helpers.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getTradeRate/getTradeRate.ts
- src/pages/Accounts/AccountToken/AccountToken.tsx
- src/pages/Dashboard/DashboardSidebar.tsx
- src/plugins/foxPage/components/AssetActions.tsx
- src/state/slices/portfolioSlice/utils.ts
- yarn.lock
fix: don't parse eth URLs with address parameter (#4953)
fix: accounts breadcrumbs with chain name (#4951)
chore: add exchange swapper to all routes (#4926)
chore(deps): bump word-wrap from 1.2.3 to 1.2.4 (#4949)
fix: invert "more expensive" label (#4948)
fix: chrome router hijack rug (#4950)
fix: thorswap error handling (#4945)
fix: osmosis error handling (#4944)
fix: remove key causing crash on confirm (#4947)
> chore: release v1.380.0

- src/Routes/RoutesCommon.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/hooks/useRouteAssetId/useRouteAssetId.ts
tl;dr /asset/<assetId>transactions (both for regular and NFT assets) got rugged since:
https://github.com/shapeshift/web/blob/0f969a3376d505347c8428c5485aa5057d6836ed/src/hooks/useRouteAssetId/useRouteAssetId.ts#L11
The reason for that is the path above is conflicting with `/:chainId/:assetSubId/transactions` subroute:
https://github.com/shapeshift/web/blob/999c31553b3bf684bc0487b86d0ff20bc5dc437a/src/Routes/RoutesCommon.tsx#L64
We cannot have transactions as a nested route anymore and need to lift it up as top-level routes for both the assetId and nftId flavors 
None, but see https://discord.com/channels/554694662431178782/1131323172369743884/1131336866315108554
/asset routing may be borked
- asset pages are happy
- account asset pages are happy
- asset transactions pages are happy
- …
> fix: asset transaction history

- packages/caip/src/assetId/assetId.ts
- packages/caip/src/chainId/chainId.test.ts
- packages/caip/src/chainId/chainId.ts
- packages/caip/src/typeGuards.ts
- packages/caip/src/utils.ts
- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/components/Trade/hooks/useSwapper/useSwapper.tsx
- src/lib/swapper/api.ts
- src/lib/swapper/manager/SwapperManager.test.ts
- src/lib/swapper/manager/SwapperManager.ts
- src/lib/swapper/swappers/CowSwapper/CowSwapper.test.ts
- src/lib/swapper/swappers/CowSwapper/filterAssetIdsBySellable/filterAssetIdsBySellable.ts
- src/lib/swapper/swappers/CowSwapper/filterBuyAssetsBySellAssetId/filterBuyAssetsBySellAssetId.ts
- src/lib/swapper/swappers/OsmosisSwapper/filterBuyAssetsBySellAssetId/filterBuyAssetsBySellAssetId.ts
- src/lib/swapper/swappers/ThorchainSwapper/ThorchainSwapper.ts
- src/lib/swapper/swappers/utils/filterAssetIdsBySellable/filterAssetIdsBySellable.ts
- src/lib/swapper/swappers/utils/filterBuyAssetsBySellAssetId/filterBuyAssetsBySellAssetId.ts
- src/state/slices/assetsSlice/selectors.ts
- Optimises caip helpers to improve UX around the app.
- Some of the assertions in the `fromAssetId` and `fromChainId` utils have been removed as they seem to be duplicates of the `assertIsXyz` utils in `packages/caip/src/typeGuards.ts`, and the compute of re-checking everything affects performance quite a lot
- Swapper asset filtering has been changed to accept `nonAftAssetIds` to minimum duplicate compute.
NA
High risk, this changes some of the most fundamental code in our platform, which means the impact of things being wrong is extremely high. 
This affects caip, which means everything relating to asset processing, trades, quotes, nfts, staking etc could be impacted.
Check everything that uses assets and chain IDs. Be thorough, as this is a high risk change.
See above
Please do a full …
> perf: optimise caip helpers and their usage

- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
We were contacted by lifi to notify us of 100 req/s with zero sell amount. They have requested that we dont request quotes with a zero amount, which makes sense to prevent.
NA
Low risk
Check lifi quotes still work
See above
See above
> fix: dont request lifi quotes with 0 amount

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
Add the `TradeConfirm` Mixpanel event to the exchange swapper.
N/A
Very small.
`Daily Trade Volume (before currency tracking)` and `Daily Trade Donation Volume ($USD)`, among other reports that relied on the TradeConfirm JSON, should be great again.
☝️
☝️
N/A
> chore: add TradeConfirm event to exchange swapper

- src/plugins/walletConnectToDapps/utils.ts
- src/plugins/walletConnectToDapps/v2/components/modals/EIP155TransactionConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/typeGuards.ts
- src/plugins/walletConnectToDapps/v2/types.ts
Makes WalletConnect transaction confirmation modal happy again, though the actual broadcasting still seems to be broken, with no error nor failed (or successful) XHR 
tl;dr is we were too strict/not accurate on what makes a transaction a transaction, and throwing at `isTransactionParams` time.
tackles https://github.com/shapeshift/web/issues/4976
Transaction detection and gas params may be broken, though WalletConnect to dApps seems to be entirely broken at the moment so can't make it more broken?
- Connect to Uniswap through WalletConnect to dApps
- Initiate a transaction
- The confirm modal should be shown, vs. the app previously crashing
- ☝🏽
- The broadcast not working may or may not be caused by local shenanigans - if you managed to actually broadcast the transaction, change the …
> fix: borked walletconnect v2 send transaction confirmation

- src/lib/swapper/swappers/LifiSwapper/LifiSwapper.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/LifiSwapper/executeTrade/executeTrade.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getLifiChainMap.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getUnsignedTx/getUnsignedTx.ts
Add URL and method event data for Mixpanel events triggered by the LiFi SDK.
N/A
Very small.
Mixpanel events for `Swapper API request` where the swapper is LiFi should now have `method` and `url` properties. 
☝️
N/A
> chore: add LiFi SDK-specific mixpanel request data

- src/lib/swapper/swappers/LifiSwapper/LifiSwapper.ts
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/LifiSwapper/executeTrade/executeTrade.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getLifiChainMap.ts
- src/lib/swapper/swappers/LifiSwapper/utils/getUnsignedTx/getUnsignedTx.ts
- src/lib/swapper/utils.ts
API tracking in Mixpanel is costly us a motza (Over $140 a day to track 1m+ requests). It's the wrong tool for the job.
Comments the logic out for now so we can pause and re-assess without totally removing the code. 
N/A
Almost 0.
`SwapperApiRequest` mixpanel events should stop being reported.
☝️
☝️
> chore: do not track api requests via MixPanel

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/quoteValidation/useActiveQuoteStatus.tsx
- src/components/MultiHopTrade/hooks/quoteValidation/useQuoteValidationErrors.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes.tsx
- No longer fetches quotes when the sell amount is 0, and updates UI to hide related elements when this is the case
- Updates polling for the `tradeQuoteQuery` to only poll if the window is currently in focus
Note to devs, we won't poll quotes now if you're focused on dev console.
Closes https://github.com/shapeshift/web/issues/4989
- Risk that we don't get quotes whne we should
- Risk that we show/don't show UI when we should/shouldn't
Check swapper for all combinations of:
- when a 0 sell amount is entered, and not entered
- when window is focused, and not focused
☝️
☝️
N/A
> perf: api request optimisations

- src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseStart.tsx
- src/components/Layout/Header/NavBar/Notifications.tsx
- src/components/Layout/Header/NavBar/UserMenu.tsx
- src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
- src/context/WalletProvider/Coinbase/components/Connect.tsx
- src/context/WalletProvider/KeepKey/components/Connect.tsx
- src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
- src/context/WalletProvider/Keplr/components/Connect.tsx
- src/context/WalletProvider/MetaMask/components/Connect.tsx
- src/context/WalletProvider/MobileWallet/components/MobileLoad.tsx
- src/context/WalletProvider/MobileWallet/components/MobileSuccess.tsx
- src/context/WalletProvider/NativeWallet/components/EnterPassword.tsx
- src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
- src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts
- src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess.ts
- src/context/WalletProvider/WalletConnect/components/Connect.tsx
- src/context/WalletProvider/WalletProvider.test.tsx
- src/context/WalletProvider/WalletProvider.tsx
- src/context/WalletProvider/WalletViewsSwitch.tsx
- src/context/WalletProvider/XDEFI/components/Connect.tsx
- src/context/WalletProvider/actions.ts
This is both a performance optimization and a bug fix.
Recent performance improvements exposed a bug, that can actually be fixed by yet more performance improvements.
The bug (and perf issue): the KeepKey event handler would subscribe to events no matter what type of wallet was connected.
In one edge case it would cause MetaMask's connection event to fire KeepKey's `handleConnect` listener, which would update the wallet state's `type` value to `KeepKey`, which would break the connected wallet routing.
The fix is two-fold:
1. Only subscribe to KeepKey events if a KeepKey is connected (additionally, I applied the same logic to the Native event hook for good measure).
2. Decouple the "connected wallet" state from the "model flow type" (names are hard). The second bug that this fixes is, for …
> perf: conditional keyring event listeners

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
Fixes an issue where MixPanel trade success and fail events were being fired more than once due to reactivity of their containing useEvent.
Set a one-way switch to ensure this event is only fired once.
N/A, related Discord discussion: https://discord.com/channels/554694662431178782/885616186623148062/1134582539844067449
Very small.
When performing a trade, see that the TradeSuccess event is only being fired once if the trade is successful, or that the TradeFailed event is being fired only once if the trade is not successful.
☝️
☝️
N/A
> fix: only fire fail/success events once

- src/context/ModalProvider/ModalContainer.tsx
- src/context/ModalProvider/ModalProvider.tsx
This fixes the send modal currently not closing after successful Tx.
short tl;dr:
This guy isn't defined and makes us throw, meaning the next line will never be evaluated, thus we will never close the modal.
https://github.com/shapeshift/web/blob/4dfb467f4a5886e33e1716c904066fdc298bc46d/src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx#L73
Long tl;dr:
https://github.com/shapeshift/web/pull/4971 brought a refactor of modals, where in addition to perf. improvements, we nest all modal providers inside each other.
This theoretically works, but doesn't if you try and use `useModal()` twice within the same component, with two different modals. The reason for that is actually a missing key in `<Provider />`, meaning that each provider isn't properly identified, and calling …
> fix: send modal close

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
The Osmosis swapper does not conceptually support slippage, and so the new slippage popover has no effect.
This PR hides the slippage button when the Osmosis swapper is selected. 
N/A
Very small.
Get a quote that can be performed by the Osmosis swapper. When this swapper is selected the button to open the slippage settings should not show.
☝️
☝️
> feat: hide slippage for osmosis swapper

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
Fixes the logic used in `useGetTradeQuotes.tsx`.
We can't use `selectTradeSlippagePercentageDecimal` because it relies on us having already selected a swapper, which can't occur until the quotes come back (quotes coming back was causing a active swapper update, triggering another network request).
We now instead handle this inside the swappers themselves when they are fetching quotes.
The current logic was causing us to double fetch qoutes when the first lot of quotes came back with a new best swapper, causing another network request to be triggered with the actual quote value.
Note, more changes are needed to support user selectable slippage, but this fix unrugs release with the flag off.
Unblocks release `1.394.0`.
Small.
Slippage values in all network requests should be the swapper …
> fix: use swapper default slippage

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/getSwapperSupportsSlippage.ts
CoW Swap doesn't support slippage via their API, as swaps are MEV protected.
Orders are already submitted with a 0.1% spread on chain.
The CoW Swap app's UI does have a concept of slippage, but they handle this at a client level by resubmitting a user's order if marked conditions change (a paradigm we do not have).
Also extracts related logic to a helper function.
N/A
Small.
The slippage opion should only be shown on the quotes screen if the selected swapper supports slippage.
☝️
☝️
N/A
> fix: hide CoW Swapper slippage

- src/components/MultiHopTrade/hooks/quoteValidation/useActiveQuoteStatus.tsx
Fix a very silly logic error 🤦‍♂️ where `hasUserEnteredAmount` was not inverted when it should have been, causing us to never validate quote inputs.
Small.
Quote validation input should be great again.
☝️
☝️
N/A
> fix: invert error logic

- src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
- src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts
Brings back always-on event listeners, as we can't rely on values set in the React event loop to conditionally listen to events, as it causes some events to be missed.
Closes https://github.com/shapeshift/web/issues/5045
Small.
Refreshing on Native wallet should prompt for the password modal again, and KeepKey connections should be great.
☝️
☝️
N/A
> fix: always listen to events

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/getQouteErrorTranslation.ts
- src/lib/swapper/api.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
We implemented monadic errors for trade quotes, but didn't finish propagating them to the user.
This PR implements that (for a limited set of error codes - we can expand these cases at Product's discretion).
N/A
Medium regression risk to the display of available swappers.
Get a set of trade quotes, and see that we now show swappers (though greyed out and unselectable) when their quotes have the following error codes:
1. `SwapErrorType.TRADING_HALTED`
2. `SwapErrorType.UNSUPPORTED_PAIR`
☝️
☝️
> feat: expose monadic quote errors to the user

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/PriceImpact.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
feat: handle moderate price impact at input/confirm step (#5033)
feat: warn against high price impact at confirm step (#5032)
> chore: release v1.399.0

- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
Fixes infinite spinner for lifi trades. The issue turned out to be due to caching in their SDK, which I've bypassed for status polling.
closes #5049
Extremely low risk, practically 0 as this only touches code for status polling for a spinner
Do a same-chain swap with lifi
See above
See above
Lifi trade lifecycle working as intended
spinner show while status is not completed:
Green tick appears when status is complete:
> fix: lifi status polling broken due to caching in their sdk

- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
Removes the hacky 0-amount quote we get when we are below the minimum for 0x and instead returns a monadic error.
Still to do (not in this PR) is display this on the interface.
This also fixes the data pollution in MixPanel where we were getting 0x quotes with a receive amount of 0, which made them "100% worse than the best trade".
N/A
Small.
See the screenshots below for the intended effect.
☝️
☝️
Prod:
This PR:
> feat: handle 0x minimums monadically

- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
Filter sell assets by those supported by the connected wallet.
Current production issue.
Risk that we don't show sell assets when we should.
When connecting with MetaMask we should now correctly filter out the unsupported assets (UTXO).
We should also be unable to get into the state with stale quotes.
☝️
☝️
N/A
> fix: filter sell assets by walletSupportsChain

- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/state/slices/swappersSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- Updates logic to only update the user's specified slippage amount on popover close
- Fixes "auto" slippage setting
- Shows slippage button when no quotes are available to prevent getting stuck in a bad state, unable to change slippage
N/A
Small - all code paths are behind a feature flag.
Not required at this time.
☝️
☝️
N/A
> feat: slippage improvements

- src/lib/market-service/market-service-manager.ts
- src/state/apis/swappers/swappersApi.ts
Does what it says on the box - ensures we don't bail out on missing market data, making us currently unable to get quotes except for the initially fetched market data assets.
N/A
We might be overfetching market data, though if we do, we have bigger problems - market-service should be cached
- Open Chrome devtools network tab
- Select an asset that is not included in the originally fetched set i.e FOX on Optimism, as either buy or sell asset
- Input some amount to fire a quote
- Ensure the network request/s are going through for said asset market data
- ☝🏽 
- ☝🏽
> feat: fetch market data at quote time

- src/lib/swapper/api.ts
- src/lib/swapper/swappers/ThorchainSwapper/evm/utils/getThorTxData.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
Adds error handling to thorchain swapper route generation such that one failed route wont prevent successful routes from being displayed.
closes #5110
Low risk of broken quotes for thorchain swapper.
Test thor quotes are correctly generated.
Recommended to review with whitespace off 🍻
☝️
> chore: add error handling to thorchain swapper route generation

- src/components/MultiHopTrade/helpers.ts
Add `isStreaming` to `TradeSuccess`, `TradeFailed`, and `TradePreview` MixPanel events.
N/A
Small
`TradeSuccess`, `TradeFailed`, and `TradePreview` MixPane
l events should now have an `isStreaming` boolean.
☝️
☝️
N/A
> chore: add more isStreaming to MixPanel

- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.ts
Adds logic to allow different memo lengths depending on the sending chain. Fixes invalid memo length assertion when sending from cosmos chain.
NA
Low risk of broken thor trades.
Check trades for each chain type (utxo, evm, cosmos sdk).
☝️
☝️
> fix: handle various memo lengths per chain family for thorchain swapper

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
Fix to display positive percentage differences on trade quotes
NA
None
Check positive percentage values appear on trade quotes as green.
NA
See above
> fix: display positive percentage differences on trade quotes

- src/lib/getTxLink.ts
- src/lib/swapper/swappers/ThorchainSwapper/constants.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
Fixes tx links for thor trades when streaming swap.
Issue was due to us missing streaming swap in switch statement, but I've simplified the tx link logic such that thor trades always link to https://viewblock.io/thorchain/tx/ for consistency. It also provides a better summary of the thor trade because it includes links ot the receiving transaction and streaming tag where applicable. 
NA
Low risk of tx links still broken.
Check the tx link for thor trades (streaming and non-streaming) work.
NOTE remember that the link will be broken for the first couple of minutes while their website finds the tx also.
☝️
☝️
Streaming swap:
Send tx link generated by our app:
https://viewblock.io/thorchain/tx/9202c07011c70de8393a62f965ba73a73dce0529787a860dd7e043a9277553fe
Receive tx link generated by our …
> fix: thorswap supports cross account trades

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- Auto-expand routes in the trade widget
- Move the "Confirm" button, and associated rendered info to be _above_ the routes
As per conversation here: https://discord.com/channels/554694662431178782/554694662896615436/1144042614522380368
Small risk UI doesn't work as expected.
When fetching trade quotes, the "routes" toggle should be expanded by default.
The Confirm button, and associated info should now sit above the list of routes.
☝️
☝️
> feat: auto-expand routes

- src/components/MultiHopTrade/components/TradeInput/components/DonationCheckbox.tsx
- src/lib/swapper/swappers/LifiSwapper/endpoints.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/state/apis/swappers/helpers/getIsDonationAmountBelowMinimum.ts
- src/state/apis/swappers/swappersApi.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
Enables opt-out donations for lifi trades. Uses same minimum donation logic as zrx and 1inch swappers to minimise wastefulness when donating on ethereum network.
Fixes incorrect donation amounts for thorchain quotes (showing 30bps when thorchain is 25).
NA
Risk of incorrect or broken lifi trades.
Check lifi trades are still working. We need to contact lifi to check donations are working but if trades are not broken by this we should do it async to releasing this.
☝️
☝️
> feat: enable opt-out donations for lifi swapper

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/constants/constants.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
Fixes incorrect amount displayed in UI for "min expected after slippage".
Previously we were subtracting the thor "recommended slippage" from the expected receive amount in the UI, which resulted in a different value appearing on the tx.
The issue:
NA
Risk of broken thor trades
Test thor trades
amount in memo includes 0.2% as expected
test tx proves the memo is correct
https://viewblock.io/thorchain/tx/8c1ba9b49bb00f0b927cf0d733dce3c9d1b49a2a806387e2dbc808f897e79b7d
min amount in tx matches UI now
> fix: use default slippage value to display min expected after slippage

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getSignTxFromQuote.ts
Fixes issue where cosmos SDK and UTXO trades re-fetch the quote when executing the trade, resulting in the limit not matching the quote confirmed by the user.
NA
Risk of broken thor swapper trades.
Check thor swapper trades work on EVM, UTXO, cosmos SDK.
☝️
☝️
> fix: dont refetch thor swapper quotes when building tx to prevent mismatch with UI

- src/components/LanguageSelector.tsx
Noticed a warning on the welcome/connect page about the Language Selector, it should use `defaultValue` on the `<select>` instead of directly setting the `selected` value on `<option>`.
This fixes it.
N/A
Low.
Verify that the default (detected) language is reflected correctly in the Language selector on first visit (you can use the Clear Cache feature after adding different languages in the browser settings).
☝️ 
☝️ 
First load with French in browser settings:
First load with an unsupported language (e.g. nl) in the browser settings, default to English in localstorage settings and UI:
> fix: better language selector default value

- src/constants/constants.ts
Update the THORSwapper slippage from 0.2% to 1%.
This is to ensure streaming swaps go through when there is a small amount of market volatility.
We now have advanced slippage turned on, so our users can adjust this value if they choose.
N/A - improve UX of streaming swaps and thorswap trades
Small.
The max slippage (min amount received) should be using 1% (not 0.2%).
☝️
☝️
N/A
> chore: update thor slippage

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
`expected_amount_out` and `expected_amount_out_streaming` does not include the expected slippage amount.
This PR deducts the expected slippage amount so we show the user what they can reasonably expect to get. Showing an amount too high was setting the limit too high, so THORChain would refund large trades, as they wouldn't get the slippge-free trade they were promised.
N/A - prod
High, as it touches memos.
Do a thorswap that will incur slippage (`slippage_bps`/`streaming_slippage_bps` !== `0`).
That slippage amount should:
- be factored into the "you get" amount (`expected_amount_out` - slippage amoamount calculated from `slippage_bps`
- be factored into the amount after slippage, which will be this new amount (shown in "you get" minus the 1% THORSwap slippage amount
- be factored into …
> fix: expected_amount_out 👏 does not 👏 include slippage

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
fix: expected_amount_out 👏 does not 👏 include slippage (#5195)
> chore: release v1.422.0

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
The recent thorchain upgrade introduced breaking changes to the api resulting in the inability to get both a swap and streaming swap quote in the same quote. We will now fetch two quote, one regular swap quote and one streaming swap quote to fix the missing streaming swaps currently
closes #
- Low: swaps should work as they were before the thorchain upgrade
- Ensure streaming swap quotes are displaying
- Spot check accurate display of amount/fees in the modal
:point_up:
:point_up:
> fix: thorchain streaming swaps quote

- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/swappers/CowSwapper/CowSwapper.ts
- src/lib/swapper/swappers/CowSwapper/endpoints.ts
- src/lib/swapper/swappers/CowSwapper/types.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.test.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.ts
- src/lib/swapper/tradeExecution2.ts
- src/lib/swapper/types.ts
Migrates cow swapper to wallet-agnostic pattern. Since cowswap uses an atypical execution flow with message signing and post to cow api, a separate interface to the common evm was created to prevent casting and generic hell.
Additionally as part of this, message creation for signing was moved into `executeTrade` such that only the cow order needs to be passed around (instead of the order to sign and the arrayified order to sign).
progresses #5024 (but doesnt close it)
High risk of broken swappers, especially cowswap. Specifically trade execution.
* Check all swappers still work
* Check cowswap trades still work
There should be no change from production whatsoever - this is intended to be a completely transparent change.
☝️
☝️
Successful cow trade
> feat: make cow swapper wallet agnostic

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/hooks/useThorStreamingProgress/types.ts
- src/components/MultiHopTrade/hooks/useThorStreamingProgress/useThorStreamingProgress.tsx
This adds a progress bar to thorchain streaming swaps. 
Includes progress bar and ability to convey the concept of partial fulfilment with reasons for each failure - a value add over viewblock and other interfaces.
closes #5191
Risk of broken trade confirmation UI
* Test streaming swaps and ensure progress bar appears and works as expected
* Test non-streaming swaps and ensure progress bar does not appear
☝️
☝️
Before confirmation
On confirmation
On streaming data loaded
On send tx confirmed
Progress increasing, matches viewblock
Streaming complete
> feat: thorchain streaming swap progress bar

- src/Routes/Routes.tsx
- src/assets/translations/index.ts
- src/constants/LanguageTypeEnum.ts
I've noticed that we are actually serving incomplete translations for languages that aren't actively maintained (e.g. `id`/Indonesian and `ko`/Korean). I always assumed those were loaded but unused, but after testing as a new user with their browser default language as one of these I am being served incomplete translations (and a lot of untranslated English strings). We also currently display an empty option in the Settings as seen here: 
This PR:
- Disables the unused languages until they are (maybe in the future) actively maintained, it also avoids loading these unmaintained language files.
- Corrects the disabled/unused locales in user Settings to the default `en` locale (for users who had one set prior to this fix).
- Will help us track the language used in Mixpanel more accurately, …
> fix: disable unused languages

- package.json
- yarn.lock
Fixes log spew when running `yarn dev`, which started when we updated to TS5.
Achieves this by overriding the `react-dev-utils/fork-ts-checker-webpack-plugin` resolution, setting it to a minimum of `6.5.3`.
See https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases/tag/v6.5.3.
N/A
Small, no runtime changes.
N/A
Running `yarn dev` should no longer spam the console with errors relating to `TypeError: Cannot set property mark of #<Object> which has only a getter`.
Nothing to test.
This is gone:
> fix: yarn dev log spew

- src/components/MultiHopTrade/hooks/useTradeExecution/useTradeExecution.ts
- src/lib/swapper/types.ts
Looks like we've forgot to remove now unused fields in recent refactors - `quoteSellAssetAccountId` and `quoteBuyAssetAccountId` are now unused.
Directly related to the above, `buyAssetAccountId` wasn't used within `useTradeExecution` - checking for it would result in failures in case of a custom receive address.
This removes the now unused fields in `TradeExecutionInput` and doesn't throw on missing `quoteBuyAssetAccountId` anymore. This may look weird but is correct, a custom receive address is *not* an AccountId at least by our vernacular, since it isn't part of the portfolio. 
closes https://github.com/shapeshift/web/issues/5226
Low since this was actually unused, but safety never hurts, do a smallish smoke test on cheap swaps
- THOR swaps with custom receive address are happy
- THOR …
> fix: unrug custom receive address trades

- src/lib/swapper/swappers/ThorchainSwapper/constants.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getThresholdedAffiliateBps/getThresholdedAffiliateBps.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/getThresholdedAffiliateBps/getThresholdedAffiliateBps.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/thorService.ts
Thorchain swapper - Updates affiliate fee logic to check the outbound fee of the inbound pool rather than the outbound pool. Since affiliate fees are sent to us from the inbound pool in RUNE, we need to compare the potential affiliate fee of the RUNE outbound fee denominated in the sell asset, in thor precision.
The approach used here is to pull the sell asset pool information and do the calculations before getting the quote.
Unit tests included.
NA
Very low risk of broken thorchain trades.
Check thorchain trades are still working
☝️
☝️
> fix: use the outbound fee of the sell asset pool to decide whether to include affiliate fee

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
This revamps our savers logic for detecting minimum for withdraw being met or not.
We were previously dealing with native assets only, meaning these were exclusively sends, hence the only thing that mattered in successfully getting a withdraw quote was the outbound fee for said *chain* being met. However, we're now dealing with token withdraws as well, which have an outbound fee denominated in a token.
This isn't exposed by the regular endpoints we would use to get an outbound fee, since inbound addresses data relates to chains and their *native assets*, not tokens.
This makes things more graceful by using a 100% withdraw quote as a way to get the outbound fees:
https://github.com/shapeshift/web/blob/b2af6922c22df7c5374806081df522887b35e839/src/features/defi/providers/thorchain-savers/comp …
> feat: savers handle not enough fee for withdraw

- react-app-rewired/headers/csps/wallets/walletConnect.ts
- src/assets/translations/en/main.json
- src/plugins/walletConnectToDapps/components/header/ConnectDapp.tsx
- src/plugins/walletConnectToDapps/components/header/DappAvatar.tsx
- src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx
- src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummaryV2.tsx
- src/plugins/walletConnectToDapps/components/header/Session.tsx
- src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
- src/plugins/walletConnectToDapps/utils.ts
- src/plugins/walletConnectToDapps/v2/WalletConnectModalManager.tsx
- src/plugins/walletConnectToDapps/v2/WalletConnectV2Provider.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/CosmosSignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/EIP155SignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/SessionProposal.tsx
- src/plugins/walletConnectToDapps/v2/eventsManager/useWalletConnectEventsManager.ts
- src/plugins/walletConnectToDapps/v2/hooks/useWalletConnectState.ts
- src/plugins/walletConnectToDapps/v2/types.ts
- src/plugins/walletConnectToDapps/v2/walletConnectReducer.ts
Implements multi-session for walletconnect v2. 
Features include:
* multiple sessions supported with UI to display them
* ability to delete sessions
* ability to reconnect stale sessions
closes #5236
* Risk of broken existing basic single session walletconnectv2 functionality
* Risk of broken new walletconnect v2 functionality
* Connect/disconnect individual sessions
* Data displayed about sessions works
* Address explorer links work
* Reloading page reconnects sessions
* Expired sessions can be reconnected (requires engineers to monkey patch if you dont want to wait 7 days)
☝️
☝️
Single dapp connected:
Multiple dapps connected:
Ability to "connect another dapp":
Display of stale and connected dapps (monkey patched):
> feat: allow users to connect multiple walletconnect client sessions to app

- src/pages/Accounts/Accounts.tsx
This PR fixes the memoization of the account routes - currently, we're using a loading state to show skeletons, however, the route itself doesn't have a `key`, hence will lazily re-render childrens.
This is fine-ish for most cases, but being in the accounts route itself and having the `loading` reference/value (same thing since it's a boolean) change won't give us guarantees things will rerender e.g when un/installing snaps, meaning we can end up in a state of stale skeletons, which never disappear and are also weirdly reconciliated in the virtual DOM, meaning you get to see both skeletons rows *and* actual accounts rows, despite the logic being either one or the other is rendered.
This PR fixes it by giving the accounts route a composite key made of the current `WalletId` and the …
> fix: account route memoization

- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
More reliability, relying on the `stages` data from the THOR midgard endpoint.
In effect, this allows us to really introspect THOR swaps status up to the most granular bits.
Note:
1. THOR granularity stops at the signed outbound Tx, which may not mean you have the funds in your wallet, and may not mean a withdraw has been updated on the THOR side either. We would be able to take over from there and introspect the outbound Tx, but this is out of the scope of this PR.
2. THOR node is extremely slow picking stage changes up. This is unfortunately the state of affairs and we're trading unreliable completion status for reliable, but slow status updates.
closes https://github.com/shapeshift/web/issues/5245
1. Things might get too slow, which is unavoidable here
2. As a result of the former, …
> fix: more reliable savers completion update p2

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
Effectively the part 2 of https://github.com/shapeshift/web/pull/5253. https://github.com/shapeshift/web/pull/5253 made the function signatures more sane and pave the way for things being done lazy vs. eager, which this PR is now doing. More context below.
Currently, the withdraw form validates input based on state values reactively.
This reactive approach results in validation being the earliest process triggered on input change.
Asynchronous operations that lead to state field updates (i.e `maybeOutboundFeeCryptoBaseUnit` and `maybeWithdrawGasEstimateCryptoBaseUnit`) happen subsequently, with the callbacks already having been executed by the time they complete. This premature execution causes potential inconsistencies and inefficiencies, and a deterministic failure of the first percent …
> feat: move from reacty to lazy savers withdraw input step

- src/assets/translations/en/main.json
- src/components/Layout/Header/Header.tsx
- src/components/Modals/Snaps/SnapConfirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/pages/Accounts/Accounts.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
fix: thorchain savers withdraw confirm (#5275)
feat: move from reacty to lazy savers withdraw input step (#5272)
feat: add USDT on Ethereum as supported savers AssetId (#5271)
feat: clear wallet AccountIds when uninstalling MM snap outside of the app (#5257)
fix: more reliable savers completion update p2 (#5255)
feat: pinky swear seed phrase is backed up on snap warning modal (#5260)
> chore: release v1.435.0

- src/hooks/useIsSnapInstalled/useIsSnapInstalled.tsx
Gets reacty on `wallet` so that we don't run the `useIsSnapInstaller` effect altogether if the current HDWallet isn't a MM HDWallet.
This avoids:
1. Browsers without MM installed getting crazy console spew
2. Browsers without MM running an effect/interval they don't need to
closes #
- The snap installation detection might not run when it actually should. Test accordingly.
- Without MM installed, there is no snap installation checks console spew
- With MM installed, installation detection still works i.e:
- Connecting the app to a MM with the snap installed detects the snap installation
- Connecting the app to a MM without the snap installed correctly detect the snap isn't installed and prompt to install it
-  Snap un/installation detection is still working
- Connecting MM with the snap …
> fix: isSnapinstalled console spew

- src/plugins/walletConnectToDapps/v2/walletUtils.ts
Ensures walletconnect v2 singletons are only instantiated once.
NA
Risk of (even more) broken walletconnect v2
NOTE: when testing, prefer you use https://react-app.walletconnect.com/ because most dApps have not implemented things on their side correctly which often throw testing off
NOTE: walletconnect v2 is known to be broken in several ways and this PR does not address that. Refer to #5285 for details.
* Check no changes in functionality from previous commit.
☝️
☝️
> fix: walletconnect singletons should be instantiated once

- src/plugins/walletConnectToDapps/v2/WalletConnectV2Provider.tsx
- src/plugins/walletConnectToDapps/v2/utils/clearAllWalletConnectToDappsSessions.ts
Clears walletconnect v2 sessions when switching wallet.
closes #5269
Risk of (even more) broken walletconnect v2
NOTE: when testing, prefer you use https://react-app.walletconnect.com/ because most dApps have not implemented things on their side correctly which often throw testing off
NOTE: walletconnect v2 is known to be broken in several ways and this PR does not address that. Refer to #5285 for details.
1. connect walletconnect v2 session(s) https://react-app.walletconnect.com/
2. check refreshing page does not clear your sessions
3. check switching wallets clears your sessions
☝️
☝️
> fix: clear walletconnect v2 sessions when switching wallet

- src/plugins/walletConnectToDapps/components/modals/AddressSummaryCard.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/CosmosSignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/EIP155SignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/EIP155SignTypedDataConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/components/modals/EIP155TransactionConfirmation.tsx
- src/plugins/walletConnectToDapps/v2/walletUtils.ts
Fixes explorer links for walletconnect v2.
NA
* risk of (still) broken walletconnect v2 explorer links
1. connect wallet connect to https://react-app.walletconnect.com/
2. click `eth_sendTransaction`
3. in the modal in web, click the explorer link - it should link to the correct explorer for the chain
☝️
> fix: correction to walletconnect modal explorer links

- src/state/slices/portfolioSlice/selectors.ts
What may have been an edge case before, i.e having portfolio balances, but no matching asset data, is now a common occurence with NFTs blacklist/filtering.
This PR ensures that when the matching asset data is missing for a given portfolio balance, we don't parse it in `selectPortfolioAccountsUserCurrencyBalancesIncludingStaking`, and consequentially don't display it as a wallet asset row.
contributes to the closed https://github.com/shapeshift/web/issues/5301
When developing e.g new chains, we might not be able to see portfolio asset rows until the integration is done e2e, including assets support.
- Ensure blacklisted jaypegs don't appear as empty wallet holdings (i.e rows with no name/symbol) under wallet.
- ☝🏽 
- ☝🏽 
- This diff
- Release
> feat: don't display portfolio balances if no asset data

- src/state/apis/nft/constants.ts
- src/state/apis/nft/nftApi.ts
This PR filters NFTs which have spammy domains medias, to avoid encountering the Chrome red security screen when images are fetched for NFTs/assets.
contributes to the closed https://github.com/shapeshift/web/issues/5301
None
- Apply the diff below to disable the current filtering of spammy NFTs
```diff
diff --git a/src/state/apis/nft/constants.ts b/src/state/apis/nft/constants.ts
index 85d1454752..a7e3eb8170 100644
--- a/src/state/apis/nft/constants.ts
+++ b/src/state/apis/nft/constants.ts
@@ -4,26 +4,7 @@ import type { NftItem } from './types'
// Try to be as broad as possible vs. specific here to accommodate for diff. TLDs and subdomains
const NFT_DOMAINS_BLACKLIST = ['ethercb']
-const NFT_NAME_BLACKLIST = [
-  'voucher',
-  'airdrop',
-  'giveaway',
-  'promo',
-  'airdrop',
- …
```
> feat: filter NFT spammy domains

- src/pages/ConnectWallet/ConnectWallet.tsx
Move key to top-level element, preventing React unique key error from logging.
N/A
Very small.
This should have no impact, with nothing to test.
☝️
☝️
> fix: move key prop to top-level element

- package.json
- src/components/TransactionHistoryRows/hooks.tsx
- src/context/AppProvider/AppContext.tsx
- src/hooks/useFetchPriceHistories/useFetchPriceHistories.ts
- src/lib/account/account.ts
- src/lib/market-service/coincap/coincap.test.ts
- src/lib/market-service/coincap/coincap.ts
- src/lib/market-service/coingecko/coingecko.test.ts
- src/lib/market-service/coingecko/coingecko.ts
- src/lib/market-service/config.ts
- src/lib/market-service/exchange-rates-host/exchange-rates-host.test.ts
- src/lib/market-service/exchange-rates-host/exchange-rates-host.ts
- src/lib/market-service/foxy/foxy.test.ts
- src/state/apis/fiatRamps/hooks.ts
- src/state/slices/marketDataSlice/marketDataSlice.tsx
- src/state/slices/marketDataSlice/types.ts
- yarn.lock
Improves local app performance by minimizing the number of redux state updates during app boot.
NA
Moderate risk change affecting how asset price history is loaded during app boot.
Clear cache and check that asset prices are loaded correctly.
☝️
☝️
The following shows performance improvement locally. Please note that the performance improvement in production will be far less noticeable.
Develop (local) - 1.43s:
This Pr (local) - 0.75s:
> perf: only upsert once when fetching asset price history

- src/context/AppProvider/AppContext.tsx
- src/hooks/useMixpanelPortfolioTracking/useMixpanelPortfolioTracking.tsx
- src/state/apis/fiatRamps/hooks.ts
- src/state/apis/swappers/swappersApi.ts
- src/state/slices/marketDataSlice/marketDataSlice.tsx
- src/state/slices/marketDataSlice/selectors.ts
- src/state/slices/marketDataSlice/types.ts
- src/test/mocks/store.ts
Improves local app performance by minimizing the number of redux state updates during app boot.
NA
Moderate risk change affecting how asset prices are loaded during app boot.
Clear cache and check that asset prices are loaded correctly.
☝️
☝️
The following shows performance improvement locally. Please note that the performance improvement in production will be far less noticeable.
Develop (local) - 1.43s:
This PR (local) - 0.04s:
> perf: only upsert once when fetching asset market data

- src/context/AppProvider/AppContext.tsx
- src/state/slices/opportunitiesSlice/mappings.ts
- src/state/slices/opportunitiesSlice/opportunitiesApiSlice.ts
- src/state/slices/opportunitiesSlice/thunks.ts
Fetches all related staking opportunities in a single RTK query request to improve performance of app in local environments.
NA
Risk of broken fetching of staking and LP opportinities.
Check staking and LP opportunities load correctly
☝️
☝️
Main local:
this PR local:
> perf: fetch all staking opportunities metadata in a single rtk query request

- package.json
- yarn.lock
Bumps the WalletConnectV2 HDWallet package to fix ethSign, which fixes CoW Swap signing.
N/A
Small.
Connect to a wallet via WalletConnect V2 and confirm that a CoW swap order can be signed.
☝️
☝️
> fix: cow signing via wc2

- react-app-rewired/headers/csps/wallets/walletConnect.ts
- src/context/WalletProvider/WalletProvider.tsx
- src/plugins/walletConnectToDapps/WalletConnectV2Provider.tsx
Handles refreshing the app whilst connected to a WC2 wallet by re-triggering the QR code modal.
Also prevents session clearing rug from wcToDapps logic.
N/A
Small
Refresh the screen when connected, to a WCV2 wallet and the modal should re-appear for reconnection.
☝️
Don't worry about testing this yet, it's behind a flag.
N/A
> fix: handle wcv2 refresh

- src/assets/translations/en/main.json
- src/plugins/walletConnectToDapps/WalletConnectModalManager.tsx
- src/plugins/walletConnectToDapps/components/modals/SessionProposal.tsx
Implements UI and connectivity for wallectconnect optional chains.
Includes the following:
* exclude required chains from optional chain list
* visually disable the"confirm" button when required chains are not approved by user (previously looked enabled)
* change warning text to success when user approves required chains
* info text for optional chains so user knows they are optional
* add scrolling for walletconnect modals
* filters out unsupported optional chains
closes #[5313](https://github.com/shapeshift/web/issues/5313)
Risk of broken walletconnect for required or optional chains
* Check user can connect, disconnect, trade etc from required chains only (i.e regression test from prod)
* Check user can connect, disconnect, trade etc with optional chains
* Generally check UI …
> feat: enable optional chains for walletconnect

- src/plugins/walletConnectToDapps/hooks/useGetAbi.tsx
- src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts
There was a TODO in the code comments: `TODO: add additional proxy methods.` I happened to need support for this popular proxy method when trying to mint domains using the UnstoppableDomains dApp + web + KeepKey. I tested this out with KeepKey and it works as intended; the only blockers are what other users have reported with invalid hash value errors thrown from the dApp side when it receives our final, signed `eth_sendTransaction` payload. You can tell from the screenshots below that the data we are sending them might need some tweaking, but that is an existing bug that I'm sure you all are aware of.
Hope this helps! I mostly did this just for fun and KeepKey Desktop will eventually need this functionality too!
closes #5054
Zero immediate user impact, because the full user flow is still …
> fix: handle EIP-1967 proxy contracts in useGetABI for WalletConnect to dApps

- src/plugins/walletConnectToDapps/hooks/useWalletConnectState.ts
- src/plugins/walletConnectToDapps/typeGuards.ts
- src/plugins/walletConnectToDapps/utils.ts
- src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts
Fixes inability to sign disclaimer on zapper login due to an additional `''` in the params array sent by rarible.
closes #5306
Low risk.
Check can log in to rarible and sign disclaimer
☝️
☝️
can sign disclaimer and log in
> fix: rarible not signing messages due to spurious empty string in their payload

- src/assets/translations/en/main.json
- src/components/AssetAccountDetails.tsx
- src/components/AssetHeader/AssetActions.tsx
- src/components/AssetHeader/AssetChart.tsx
- src/components/AssetHeader/AssetDescription.tsx
- src/components/AssetHeader/AssetHeader.tsx
- src/components/AssetHeader/AssetMarketData.tsx
- src/components/Button/Button.theme.ts
- src/components/Card/Card.theme.ts
- src/components/Equity/Equity.tsx
- src/components/Graph/Graph.tsx
- src/components/Graph/MaxPrice.tsx
- src/components/Graph/MinPrice.tsx
- src/components/Graph/PrimaryChart/PrimaryChart.tsx
- src/components/Layout/Main.tsx
- src/components/PriceChart/PriceChart.tsx
- src/components/Radio/Radio.tsx
- src/components/RelatedAssets/RelatedAssets.tsx
- src/components/StakingVaults/EarnOpportunities.tsx
- src/components/StakingVaults/ProviderCard.tsx
- src/components/StakingVaults/WalletProviderTable.tsx
- src/components/TransactionHistory/AssetTransactionHistory.tsx
- src/lib/charts.ts
- src/pages/Dashboard/Portfolio.tsx
- src/pages/Dashboard/RecentTransactions.tsx
- src/plugins/walletConnectToDapps/hooks/useGetAbi.tsx
- src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts
- yarn.lock
feat: modify mobile version of screen (#5369)
fix: handle EIP-1967 proxy contracts in useGetABI for WalletConnect to dApps (#5368)
fix: send transactions with walletconnect (#5372)
chore(deps): bump get-func-name from 2.0.0 to 2.0.2 (#5370)
> chore: release v1.446.0

- src/plugins/walletConnectToDapps/components/Account.tsx
- src/plugins/walletConnectToDapps/components/AccountSelectionByChainId.tsx
- src/plugins/walletConnectToDapps/components/ChainReferenceCard.tsx
- src/plugins/walletConnectToDapps/components/modals/ContractInteractionBreakdown.tsx
- src/plugins/walletConnectToDapps/components/modals/CosmosSignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/components/modals/EIP155SignMessageConfirmation.tsx
- src/plugins/walletConnectToDapps/components/modals/EIP155SignTypedDataConfirmation.tsx
- src/plugins/walletConnectToDapps/components/modals/EIP155TransactionConfirmation.tsx
- src/plugins/walletConnectToDapps/components/modals/SessionProposal.tsx
- src/plugins/walletConnectToDapps/components/modals/connect/ConnectContent.tsx
- src/plugins/walletConnectToDapps/hooks/useCallRequestEvmFees.ts
- src/plugins/walletConnectToDapps/hooks/useGetAbi.tsx
- src/plugins/walletConnectToDapps/hooks/useIsInteractingWithContract.ts
- src/plugins/walletConnectToDapps/hooks/useWalletConnectState.ts
- src/plugins/walletConnectToDapps/typeGuards.ts
Implements a loading state for WalletConnect modals to address the current issue where modals do not provide user feedback upon confirmation, leading to user confusion.
* Includes some rendering performance tweaks
* Includes a fix where components were consuming the output of `src/plugins/walletConnectToDapps/hooks/useIsInteractingWithContract.ts` as a `string|null` there it was outputting an object
closes #5377
Low risk of walletconnect modals unable to confirm or reject.
* Check all walletconnect requests are able to confirm and reject
* Check users cannot click reject while confirm is loading
☝️
☝️
note loading state while fees are fetching
> feat: use loading state on all modal submit buttons

- src/plugins/walletConnectToDapps/WalletConnectModalManager.tsx
- src/plugins/walletConnectToDapps/components/modals/SessionProposal.tsx
- src/plugins/walletConnectToDapps/types.ts
Resolves the issue where closing a WalletConnect modal leaves a pending request, which prevents subsequent requests from appearing in the application.
solves first part of #5378 
Risk of walletconnect requests (sessions, transactions etc) broken
The application should automatically reject a pending request when:
The user closes the modal by clicking the close icon
The user closes the modal by clicking outside of it
☝️
☝️
> fix: walletconnect should reject requests on modal close

- src/plugins/walletConnectToDapps/WalletConnectModalManager.tsx
Reloading the app while an active wallet connection request in the WalletConnect modal leaves a lingering connection request at app boot. This disrupts the flow of new requests to connect and use the wallet via WalletConnect within the wallet app. This PR tackles this issue by automating the rejection of pending wallet requests when users disconnect from a WalletConnect modal.
closes #5378 
Risk of inability to connect or disconnect wallet via WalletConnect or receive and approve incoming WalletConnect requests.
1. Connect a WalletConnect dApp to the wallet to inaugurate a WalletConnect-connected state (ensuring a supported wallet is used to connect, since WalletConnect only supports connecting to specific wallets)
2. Execute a WalletConnect wallet request to the connected wallet app …
> fix: ensure wallet connected when wallectconnect receives a request

- src/context/WalletProvider/WalletConnectV2/config.ts
Currently, the web3 modal does not work in the Native ShapeShift app (though it does when using a mobile browser).
Update the wallet configuration accordingly.
N/A
The WalletConnect wallet option should no longer appear as a wallet option in the native app.
☝️
☝️
N/A
> fix: set wcv2 wallet mobile support to browser-only

- src/context/WalletProvider/WalletProvider.tsx
Clear wallet connect wallet state on wallet switch.
- Closes https://github.com/shapeshift/web/issues/5397
- Closes https://github.com/shapeshift/web/issues/5408
Small - new code path only executes when switching from a wallet connect wallet.
- Switch from a connected wallet connect wallet to any other wallet, and see that the previously connected wallet connect wallet (e.g. Trust) correctly receives the disconnect event (the wallet connect session should disappear).
- Switch from a connected wallet connect wallet to ShapeShift native wallet and see that the previously connected wallet connect wallet does not appear as a wallet connect connected dApp in the connected dApps dropdown.
☝️
☝️
N/A
> fix: clear wc state on wallet switch

- src/assets/translations/en/main.json
- src/components/Modals/Snaps/SnapConfirm.tsx
- src/components/Modals/Snaps/SnapIntro.tsx
- src/components/Modals/Snaps/Snaps.tsx
- src/state/slices/preferencesSlice/preferencesSlice.ts
Clicking Don't ask again and then closing the modal by clicking the X will result in the modal re-appearing on next app boot. This PR addresses this issue.
Includes translation fix, performance improvements.
closes #5418
Low risk.
1. App should remember your request to not ask again about adding a snap, even if you choose not to install it
> fix: dont show snaps modal after user requested not to show it

- src/context/AppProvider/AppContext.tsx
- src/state/slices/opportunitiesSlice/mappings.ts
Makes sure BSC savers references are added everywhere, so that BSC user staking data is properly fetched - it accidentally works on deposit/withdraw currently, as we use `<TransactionProvider />` user-data fetching introspecting THOR Tx, but won't fetch the user staking data when importing a wallet.
closes https://github.com/shapeshift/web/issues/5415
None
- Have a wallet with a savers BNB active position (can use e.g a diff env for that, or deposit then clear your localForage)
- Savers user staking data for BNB on BSC is fetched on wallet import, without needing to do a deposit
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> fix: bsc savers user staking data

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/types.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- src/assets/translations/en/main.json
- src/components/Icons/LedgerIcon.tsx
- src/components/Modals/Receive/ReceiveInfo.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
- src/components/MultiHopTrade/types.ts
- src/context/WalletProvider/Ledger/components/Chains.tsx
With a new `pubKey` param - indicating public key should be used to fetch the address from unchained and bypass wallet fetching.
This allows us to effectively unrug cross-chain trades (can't have two apps open at the same time to get each address) as well as make the UX smoother, not requiring users to open the relevant app when they're getting an address i.e receive modal, trade etc. If we have xpubs / address identifiers, we can use those to either do an Identity on them (return self), or for xpubs, use unchained to get the receive address.
closes #
Moderate/high, but effectively close to zero given this is isolated to Ledger. 
**Ensure that all code paths related to this are guarded against wallets other than ledger**. This param should *never* be passed to `adapter.getAddress()` for …
> feat: chain-adapters `getAddress()` from unchained

- package.json
- react-app-rewired/index.ts
- src/lib/swapper/swappers/CowSwapper/CowSwapper.ts
- src/lib/swapper/swappers/CowSwapper/endpoints.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/CowSwapper/utils/constants.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.test.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.ts
- src/lib/swapper/types.ts
- yarn.lock
This PR uses the https://github.com/cowprotocol/app-data package to generate proper CoW AppData, in an effort to fix CoW trades (probably failing because of slippage), as well as making sure we are up-to-date on the CoW AppData version and are able to use the additional metadata fields programatically in the future.
This is as opposed to CoW's previously provided appdata (https://github.com/shapeshift/lib/pull/956) which referenced a static IPFS CID with no metadata.
As for why we're doing this weird `appData` / `appDataHash` dance, this is by design with CoW, see:
https://api.cow.fi/docs/#/default/post_api_v1_quote
https://github.com/cowprotocol/cowswap/blob/a11703f4e93df0247c09d96afa93e13669a3c244/apps/cowswap-frontend/src/legacy/utils/trade.ts#L236
tl;dr here is
- CoW *endpoints* …
> fix: make CoW great again

- src/context/WalletProvider/WalletProvider.tsx
Fixes redundant initialization - we already do this in the `load()` method.
This is only a performance bottleneck for most wallets, however, for Ledger, this means we attempt pairing the device without explicitly having Ledger as a selected wallet.
- relates to https://github.com/shapeshift/web/issues/5445
- Wallets pairing might be broken, test with all wallets. Tested with Ledger, Native, KK, MM and WCV2
- Ensure wallet pairing is still happy against prod for all wallets
- ☝🏽 
- ☝🏽
> fix: don't initialize wallet in state.keyring effect

- src/context/WalletProvider/Coinbase/config.ts
- src/context/WalletProvider/DemoWallet/config.ts
- src/context/WalletProvider/KeepKey/config.ts
- src/context/WalletProvider/Keplr/config.ts
- src/context/WalletProvider/Ledger/config.ts
- src/context/WalletProvider/MetaMask/config.ts
- src/context/WalletProvider/MobileWallet/config.ts
- src/context/WalletProvider/NativeWallet/config.ts
- src/context/WalletProvider/WalletConnectV2/config.ts
- src/context/WalletProvider/WalletProvider.tsx
- src/context/WalletProvider/XDEFI/config.ts
- src/context/WalletProvider/config.ts
i.e technically lazy loads said packages, but doesn't effectively do so for now, because of this bad boy:
https://github.com/shapeshift/web/blob/a5839be885a1f0aa8d35d7dda94d7a80e8f78de7/src/context/WalletProvider/WalletProvider.tsx#L767-L783
This however, puts us in a better position to get wallet adapters lazy loaded as a follow-up, the intent being to only populate (and by extension, import the npm packages) adapters when clicking on a wallet option.
- tackles https://github.com/shapeshift/web/issues/5445
- Moderate. Theoretically, the surface area brings huge regression risks for all wallets. In effect, the flow is effectively the same for the time being.
- All wallets are still displayed as option
- Wallet pairing still work
- ☝🏽 
- ☝🏽
> feat: lazy load hdwallet adapter modules part 1

- src/context/WalletProvider/Coinbase/components/Connect.tsx
- src/context/WalletProvider/KeepKey/components/Connect.tsx
- src/context/WalletProvider/Keplr/components/Connect.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/context/WalletProvider/Ledger/components/Connect.tsx
- src/context/WalletProvider/MetaMask/components/Connect.tsx
- src/context/WalletProvider/MobileWallet/components/MobileLoad.tsx
- src/context/WalletProvider/MobileWallet/components/MobileSuccess.tsx
- src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
- src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts
- src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess.ts
- src/context/WalletProvider/SelectModal.tsx
- src/context/WalletProvider/WalletConnectV2/components/Connect.tsx
- src/context/WalletProvider/WalletConnectV2/config.ts
- src/context/WalletProvider/WalletConnectV2/constants.ts
- src/context/WalletProvider/WalletContext.tsx
- src/context/WalletProvider/WalletProvider.test.tsx
- src/context/WalletProvider/WalletProvider.tsx
- src/context/WalletProvider/XDEFI/components/Connect.tsx
- src/context/WalletProvider/config.ts
Yo dawg, we heard you like wallets, so we put some lazy wallet loading in your wallet loading, so you can transact while you transact! 🚀 Welcome to our super-duper PR where we're turning sloth-mode ON to hit you up with the snazziest, laziest import of hdwallet npm packages that you've ever seen. 
Why, you ask? Because ain't nobody got time to wait for those hefty hdwallet bundles to load! 😴 By incorporating a luxuriously lazy loading mechanism, we make sure your user experience is smoother than a fresh jar of peanut butter. 🥜✨ Now you can keep your transactions and crypto dealings as swift as a ninja, all while our code does the heavy (or should we say, light?) lifting in the background.
In a nutshell:
- Maximize efficiency 🚀
- Minimize loading times ⏲️
- Optimize your chill while we …
> feat: actually lazy load hdwallet adapter modules

- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
Fixes one of two hard things in software engineering, i.e us being too heavy on the memoization side of things and never getting a new receive address for UTXOs when the receive index changes.
N/A, spotted by ops
None
- Click receive on a UTXO account
- Make a send to your account
- After the Tx is confirmed, and without refreshing the page, click "Receive" again
- Ensure the receive address you're getting is a new one
- Put a breakpoint in `getReceiveAddress` body
- Ensure it is always ran when clicking receive for the same account - except for Ledger, with which it will be memoized
- Current receive index
- Next receive index
- Current receive index
- Next receive index, notice how this stays the same and vails verification
> fix: bust getReceiveAddress cache for wallets other than Ledger

- src/components/Banners/YatBanner.tsx
- src/components/Layout/Header/AppLoadingIcon.tsx
- src/components/Layout/Header/DegradedStateBanner.tsx
- src/components/Layout/Header/GlobalSearch/GlobalSearchButton.tsx
- src/components/Layout/Header/Header.tsx
- src/components/Layout/Header/NavBar/ChainMenu.tsx
- src/components/Layout/Header/NavBar/MainNavLink.tsx
- src/components/Layout/Header/NavBar/MobileNavBar.tsx
- src/components/Layout/Header/NavBar/MobileNavLink.tsx
- src/components/Layout/Header/NavBar/NavBar.tsx
- src/components/Layout/Header/NavBar/Notifications.tsx
- src/components/Layout/Header/NavBar/UserMenu.tsx
- src/components/Layout/Header/SideNav.tsx
- src/components/Layout/Header/SideNavContent.tsx
- src/components/Layout/Header/TxWindow/TxWindow.tsx
- src/index.tsx
- src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
Enhances rendering performance for low-compute mobile devices, specifically focusing on the sidebar opening and closing rendering performance on mobile devices.
closes #5470
Low risk of broken UI in mobile layout
You can test these changes with chrome devtools rather than waiting for a mobile build:
- Improved in rendering performance of sidebar open/close on low-compute devices.
- No degradation in user experience or functionality.
Sidebar opening before improvements (6x throttling on m2 mac) - 0.95s
Sidebar opening after improvements (6x throttling on m2 mac) - 0.47s
> perf: improve rendering performance of mobile sidebar

- src/context/AppProvider/AppContext.tsx
- src/pages/Buy/Buy.tsx
Fiat ramps take a long time to fetch over the network. This happens right when loading the app at the default dashboard route with a locked native wallet.
Not only are we making useless network requests, but there's also the upsertion happening, all of which we don't need until actually going to the fiat ramps page. This PR defers the fetching to the fiat ramps page.
- relates to https://github.com/shapeshift/web/issues/5451
- Fiat ramps page is still happy
- ☝🏽 
- Ensure the XHRs to fiat ramps (e.g onramper) aren't fired until going to the fiat ramps page
- ☝🏽
> perf: defer fiat ramps fetching to fiat ramps page

- src/components/Graph/Graph.tsx
- src/components/Graph/PrimaryChart/PrimaryChart.tsx
And consequently, all imports of `<PrimaryChart />` and `<RainbowChart />` including the heavy @visx packages will be lazily *ran* (not loaded).
Relates to https://github.com/shapeshift/web/issues/5445
Low, if balance and rainbow charts load in dashboard, we're gucci
- Balance chart still loads in dashboard
- Switching back and forth from primary to rainbow chart is working
- When the balance chart is in a loaded state for the first time, the chunk for `<PrimaryChart />` is lazily loaded over the network
- When the rainbow chart is in a loaded state for the first time, the chunk for `<RainbowChart />` is lazily loaded over the network
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/3a2278ac-91f5-4b26-a69e-d704e730ed72
> perf: load primary/rainbow chart components lazily

- src/components/Layout/Header/NavBar/Notifications.tsx
Inspired by @gomesalexandre #5477 this makes wherever package load lazy so parsing is delayed until the user connects their wallet.
NA
Risk of broken wherever notifications
Check wherever notifications load and behave as intended.
https://github.com/shapeshift/web/assets/125113430/8f9affeb-2508-4e44-867d-ac4252c6fd5a
> perf: make wherever notification imports lazy

- package.json
- src/state/apis/snapshot/getVotingPower.ts
- src/state/apis/snapshot/snapshot.ts
- yarn.lock
Enhances app boot time for low-compute mobile devices by removing unused packages. In this instance, removes `@snapshot-labs/snapshot.js` and replaces it with an axios request.
closes #5482
risk of fox voting power fetch broken
check fox voting power is fetch when wallet is connected:
> perf: replace snapshot.js sdk with an axios request

- src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Overview/WithdrawCard.tsx
Ensures the "Claim Now" as well as the "Claim" button are in a loading state while `canClaimWithdraw` is loading
- relates to https://github.com/shapeshift/web/issues/5484
None, this only adds a loading state
- Ensure FOXy "Claim" and "Claim Now" buttons aren't clickable with a withdraw in "Pending" loading state. Note, since FOXy doesn't work locally, this has been deployed and tested in gome.
- ☝🏽 
- ☝🏽
> feat: foxy canClaimWithdraw loading state

- src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
Does what it says on the box - ensures we don't consider 0-amount undelegations as valid claims, see prod:
- relates to https://github.com/shapeshift/web/issues/5484
- We might not be allowing legit claims
- Test release against prod, ensuring the claim button is disabled in case of 0 amount to claim. Deployed to gome for testing against prod, since localhost is rugged with FOXy
- ☝🏽 
- ☝🏽 
No withdrawal to claim
Withdraw to claim
> feat: foxy claim handle 0-amount delegations

- src/context/WalletProvider/KeepKey/components/Connect.tsx
- src/context/WalletProvider/WalletProvider.tsx
While this was previously benign spaghetti code which wouldn't cause any harm except for the eyes, the refactor of `WalletProvider` to only have one adapter per KeyManager makes the `try { firstAdapter.pairDevice() } catch () { secondAdapter.pairDevice() }` flow wrong and inherently borked for KK, since calling `getAdapter()` on the first adapter will set it in state and keep it cached.
https://github.com/shapeshift/web/blob/06dd95458aa699bcce94682b48fcaea7506cbfcd/src/context/WalletProvider/WalletProvider.tsx#L360-L361
This untangles the KeepKey `<Connect />` spaghetti and ensure we never attempt getting the first KeepKey rest adapter in case we have no `sdk`, meaning we're not the context of KK desktop, and don't need this adapter at all.
N/A, though relates to the recent hdwallet perf. …
> feat: untangle the KK spaghetti

- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
Won't cut it for us unfortunately - this rugs the next receive address, and consequently, verification in receive modal / trade verify  steps, see https://discord.com/channels/554694662431178782/1164367653767479336/1164369144230199328
N/A
None, this was only used with Ledger, and we're safu to remove this as we're not hitting the device, instead passing `xpub` and getting the address at the next receive address from unchained
1. For full paranoia testing, have two instances of prod opened alongside this diff on a third: one with native, one with the same seed imported on Ledger
2. Have the receive modal for said UTXO opened on all 3 builds
3. Eventually after a few minutes, the receive address will change on native (need to close and reopen the receive modal)
4. Confirm the new receive …
> feat: remove getReceiveAddress caching

- src/state/migrations/index.ts
Ensures we don't end up with borked FOXy state - see #5484
contributes to https://github.com/shapeshift/web/issues/5484
None
@shapeshift/operations to test https://github.com/shapeshift/web/issues/5484
```
I managed to repro the claim state on your account, but it went away after a few seconds of state reconciliation, this is what I can see now. I believe if the user was fast enough to click it, that could've happened 
```
- Ensure there is no pending withdraw mistakenly shown for FOXy when it is not actually possible to withdraw (i.e the claim Tx would go through but nothing would be withdrawn)
- ☝🏽 
- ☝🏽
> feat: clear opportunities migration

- src/state/apis/zapper/validators.ts
Makes `statsItems` of `ZapperDisplayPropsSchema` `.nullable().optional()`.
Fixes the console error:
N/A
Small 
We shouldn't see the error above in the console..
☝️
☝️
N/A
> fix: const ZapperDisplayPropsSchema

- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/state/apis/swappers/swappersApi.ts
Switching between pages and trade page triggers re-fetch of supported assets due to lack of caching as components unmount and remount. Each page switch was causing all swappers to fetch their supported asset list, resulting in 4 api calls made each time the trade input remounted.
This PR moves the concern of fetching supported assets into an RTK query endpoint so we can take advantage of caching.
Relates to (but doesnt close) #5449
Risk of incorrect supported asset list in trade input
Check asset list is correct between different page changes and different page reloads.
> perf: move supported asset fetch into rtk query endpoint

- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/state/apis/swappers/swappersApi.ts
Improves trade page load/switch time by around 700ms on desktop (benched on m2 mac). Issue was O(n^2) filtering of supported assets, now O(n logn) through use of sets while avoiding serialization cost of passing complete asset structs into rtk query.
closes #5449
Low risk of incorrect supported asset list on trade page (the asset list dropdowns).
Check supported assets are still correct.
Develop branch - 789ms
This PR - 12ms
> perf: better asset filtering for faster page load on trade page

- src/components/MultiHopTrade/hooks/useAllowanceApproval/helpers.ts
- src/contracts/contractManager.ts
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Approve.tsx
- src/features/defi/providers/univ2/hooks/useUniV2LiquidityPool.ts
- src/lib/utils/evm.ts
- src/lib/viem-client.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/utils.test.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/utils.ts
Fixes broken ERC20 allowance approvals for non-eth EVM chains. 
closes #5571
closes #5573
closes #5574
Risk of approvals still broken for EVM chains
Check approvals work for all EVM chains
Note that this includes a fix to use the viem public client per chain, and I've hardcoded all other uses of the function to use ETH mainnet. Please double check this is correct for all cases where i've hardcoded it.
FOX/ETH LP appearing also
> fix: approvals failing for non-eth EVM chains

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FirstHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Footer.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/SecondHop.tsx
- src/state/slices/swappersSlice/swappersSlice.ts
- src/state/slices/swappersSlice/types.ts
Added draft footer component to multihop trade ui so we can interact with it during development. Behavior mirrors design to disappear when clicked to enable to execution flow.
Design can be found here
https://www.figma.com/file/OHbVrAVaV2xQWUsq0nKzGm/ShapeShift-Library?type=design&node-id=4645-14984&mode=design&t=CEw93wbn4uFvFCJe-0
NA
Extremely low risk as is behind feature flag, however there are minor changes to redux slices so a quick test of trades may be pragmatic.
☝️
☝️
☝️
The design
Implemented - not exactly as designed which is fine for now
> feat: added draft footer for multihop trade confirm

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
- src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
- src/components/Modals/Send/utils.ts
- src/lib/address/address.ts
- Handle `signTransaction` response payload more explicitly, and allow error to bubble up and only log once. This prevents attempting to broadcast an empty payload on metamask sign error and reduces console error spew.
- Reduce log spew when parsing standard addresses with qr code decoding logic
N/A
Low - should still see relevant errors
- Send EVM or Utxo with metamask snap
- Notice no errors in console upon inputting a regular address
- Reject the transaction in metamask and note only seeing sign transaction error (no attempt to broadcast)
:point_up:
:point_up:
EVM (old):
EVM (new): 
UTXO (old):
UTXO (new):
> chore: cleanup signtx error handling

- src/state/slices/opportunitiesSlice/resolvers/uniV2/utils.test.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/utils.ts
Use `getLogs` instead of `getFilterLogs` to fetch. This avoids the scenario where an event filter is created on one of many replicated nodes and the subsequent fetch for filtered logs is not routed to the same node that contains the event filter.
We are able to get the exact same data in a single call to the node when using `getLogs` instead.
This PR can replace https://github.com/shapeshift/web/pull/5592.
closes: https://github.com/shapeshift/web/issues/5574
Low - should behave the same without needing to worry about network routing
- Should see the correct price and apy for uniswap v2 positions
- Should not see any network errors surrounding `eth_getLogs`
:point_up: 
:point_up:
> fix: replace viem getFilterLogs with getLogs

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FirstHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/SecondHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/steps.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useExecuteAllowanceApproval.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/useAllowanceApproval.tsx
- src/components/MultiHopTrade/types.ts
- src/state/slices/swappersSlice/swappersSlice.ts
More changes to progress the implementation of multi hop trade UI WIP.
Includes changes to the `useAllowanceApproval` hook to output a `TxStatus` which is not used outside of multi-hop trades.
NA
Changes to `useAllowanceApproval` though minor, pose a slight risk of broken allowance approvals and/or trades.
Ensure ERC20 allowance approvals and trades work as expected with multi-hop ui disabled.
☝️
☝️
> feat: multi hop ui progression

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FirstHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/SecondHop.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/hooks/useHopHelper.tsx
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/LifiSwapper/utils/lifiTokenToAsset/lifiTokenToAsset.ts
- src/lib/swapper/swappers/LifiSwapper/utils/lifiTokenToAssetId/lifiTokenToAssetId.ts
- src/lib/swapper/swappers/OneInchSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
- src/lib/swapper/swappers/utils/test-data/setupSwapQuote.ts
- src/lib/swapper/types.ts
- src/state/apis/swappers/helpers/testData.ts
Wires up multi hop quotes to the new multi hop ui. 
Includes a change to make execution time estimates per-hop so we can display the time estimate on each hop. Should not affect single hop trades as the total and the individual estimate is the same value.
Note that multi-hop quotes are still WIP because the app currently uses the wrong account for balances checks on the second hop.
NA
Low risk - may affect single hop trades and time estimates.
Check single hop trades and existing ui is unaffected.
☝️
☝️
> feat: wire up multi hop quotes to trade UI

- src/hooks/useRouteAssetId/useRouteAssetId.ts
- src/pages/Lending/LendingPage.tsx
- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
This PR adds multi-account support for THORChain lending, i.e the opportunity for opportunities over multiple accounts to be reflected as individual entries, as well as the pool page being programmatic and displaying the right position - or the first account one if there's no current position.
closes N/A
None, under flag
- Multi account selection for the collateral asset shows no regression in lending
- Having lending positions over multiple AccountIds is reflected with multiple entries
- Clicking said position in "Your Loans" will automagically select the right account when lending
- Clicking a non-yet active lending opportunity in "Available Pools" uses default AccountId
- ☝🏽 
- ☝🏽 
- Develop
- This diff
> feat: wire-up thorchain lending multi-account

- src/components/MultiHopTrade/components/Approval/Approval.tsx
- src/components/MultiHopTrade/components/AssetSelection.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FirstHop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/SecondHop.tsx
- src/components/MultiHopTrade/components/TradeAmountInput.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/quoteValidation/useInsufficientBalanceProtocolFeeMeta.tsx
- src/components/MultiHopTrade/hooks/useAccountIds.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useApprovalTx.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useExecuteAllowanceApproval.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useIsApprovalNeeded.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/useAllowanceApproval.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useHopHelper.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
- src/pages/Lending/Pool/components/Borrow/Borrow.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/state/slices/portfolioSlice/selectors.ts
- src/state/slices/swappersSlice/selectors.ts
- src/state/slices/swappersSlice/swappersSlice.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
Adds new selectors to automatically select the correct account ID for multi-hop trades.
---
Single hop trades have the following account flow (existing in prod):
`account A -> account C`
Multi hop trades have the following account flow - Note that account B is used twice, once for receiving on first hop, and again when sending on the second hop:
```
account A -> account B
account B -> account C
````
Our UI supports selecting the buy and sell accounts, but the intermediary account must be inferred.
To solve this for multi-hop trades, we assume account B could be on a different chain to account A, but will always flow through the same account number as account A. Hence the following was implemented:
**first hop buy account ID**
1. if this is a single hop trade, return the last hop buy …
> feat: handle multi hop account ids automatically

- src/components/AssetSearch/helpers/filterAssetsBySearchTerm/filterAssetsBySearchTerm.ts
- src/components/Nfts/NftTable.tsx
- src/components/StakingVaults/PositionTable.tsx
- src/pages/Dashboard/components/ProfileAvatar/AvatarSelectModal.tsx
- src/state/slices/assetsSlice/selectors.ts
Fixes search bars returning irrelevant results. We're using https://www.npmjs.com/package/match-sorter for searching, which defaults to `SIMPLE MATCH`:
The fix is to change the threshold to `CONTAINS`, which will only returns results containing your search term. This was already implemented in a few cases, so this PR updates the remaining instances to align with those.
closes #5630
Risk of (still) broken searching across app.
Check search boxes operate as expected, noting the change in functionality above.
"BCH" now returning no results (expected as i have no BCH trades)
"BNB" now returning results containing "BNB":
"B" returns all results containing "B":
> fix: search on substring, not simple match

- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
- src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.ts
Does what it says in the title - accounts for the liquidity fees before deducting the affiliate bps, so that the limit we get is actually reliable. It previously working was mostly out of luck because the network state was not so crazy and liquidity fees were less than currently, but we absolutely need to account for it.
closes https://github.com/shapeshift/web/issues/5635
None?
- THOR Txs are going through and aren't refunded
- ☝🏽 
- ☝🏽 
- Do an ETH -> RUNE swap and ensure it is not refunded
- Do an FOX -> ETH swap and ensure it is not refunded
- Failed Tx
https://runescan.io/tx/4D43F7A16A02CF549FC6918F872884BBB13CE28F85A01C47FB5498BC70DCCA2F notice how there's ~0.2 ROON missing in the outbound, resulting in a refunded Tx
- Happy Tx …
> fix: thorchain limit account for liquidity fees

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hops.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/TwirlyToggle.tsx
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
Implements the trade success ui for multi hop trades.
NA
Low risk as no production-facing code is changed.
Not required.
Successful trade with details expanded - note the success ui shows the user BALANCE, not the amount that was received during the trade (cc @reallybeard)
Successful trade with details hidden
> feat: implemented trade success ui for multi-hop trades

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
Fixes issue where a trade is completed, the summary is rendered without all of the metadata that was generated during execution. This pr addresses the issue by rendering the UI in a div and passing it around the the various components as required such that no state is lost.
https://github.com/shapeshift/web/assets/125113430/013eafdb-a948-43b9-bdef-c5690e980b3e
A note has been added with next course of action should this approach become unmaintainable. 
closes #5668
Low risk, not user facing.
Not required.
Trade metadata, e.g txids now appearing on the completion summary:
Before the fix:
> fix: maintain multi-hop metadata and state to render in completion summary

- src/lib/utils/thorchain/lending.ts
Fixes 0 amount being passed for lending close quotes
N/A
- Repayments (at any percent) requests are not sent using 0 amounts
- None
> fix: lending close quote use repayment asset precision

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
Fixes the blue border missing on the step indicator in the multi-hop UI for a swap/bridge step when there is no ERC20 token approval required.
closes #5670
Low risk, behind feature flag.
Not required.
> fix: active step indicator for hops without allowance approval

- src/context/AppProvider/AppContext.tsx
Fixes a regression caused in https://github.com/shapeshift/web/pull/5673 where `dispatch(portfolio.actions.upsertAccountMetadata(accountIdsAndMetadata))` was never actually called due to early returns in the above `forEach` loop.
This was observed and easily replicated on the demo wallet, where no accounts were shown once the cache is cleared. I'm not sure of the impact outside of the demo wallet though I suspect it caused issues there, too.
Note, this is not as performant is the original PR intended, as it calls `upsertAccountMetadata` for every account number (but not every account! 🙏 ).
Noted in release thread after release had hit production: https://discord.com/channels/554694662431178782/1178487848312242216/1178546667583193158
Medium - touches account loading.
Confirm all accounts …
> fix: demo wallet and upsert

- src/context/AppProvider/AppContext.tsx
- src/lib/account/account.ts
- src/state/slices/portfolioSlice/selectors.ts
Fixes a bug introduced in https://github.com/shapeshift/web/pull/5693 which fixed a regression introduced in https://github.com/shapeshift/web/pull/5693 but brought a smolish mismatch 🤯 
tl;dr:
- the accounts metadata now has *too many* accounts, including for accounts without Tx history
- the accounts slice however, has just the right amount of accounts. This results in this guy never returning anything else than `loading`:
https://github.com/shapeshift/web/blob/4a36aa55527500bc7863ae93c325dd4d8eabf54d/src/state/slices/portfolioSlice/selectors.ts#L137-L143
This is explained by l.130 here:
https://github.com/shapeshift/web/blob/4a36aa55527500bc7863ae93c325dd4d8eabf54d/src/state/slices/portfolioSlice/selectors.ts#L123-L130
Given we react on a different `accountsById` and `accountMetadata` …
> fix: accounts/accounts metadata mismatch

- src/features/defi/components/Deposit/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/ThorchainSaversDeposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/ThorchainSaversWithdraw.tsx
... and updates the signature of `onChange` in the reusable `<Deposit />` to be sane. 
Two birds one stone:
1. This fixes the reactivity of `fromAddress` to handle `accountId` (thus, `accountType` changes) when getting the first/active THOR savers address. Currently, there is a `if (fromAddress) return` early return, meaning that changing your account type at overview/deposit input/withdraw input step will still yield your first/active address from your previously selected accountType. This means the consolidation step would send your funds to a different accountType, making you unable to continue with the deposit after the reconciliation
2. `onChange` signature was rugged in the shared `<Deposit />` component. There was no notion of "isFiat" in the `onChange` prop `<ReusableDeposit />` …
> fix: savers fromAddress account type reactivity

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
The global minimum transaction fee was recently increased to `0.05 atom`. Update to allow successful broadcasts of cosmos transactions.
closes https://github.com/shapeshift/web/issues/5683
closes https://github.com/shapeshift/web/issues/5690
None
- Should be able to send/claim/etc on cosmos again
:point_up: 
:point_up:
> fix: update minimum transaction fee for cosmos network

- src/state/slices/portfolioSlice/selectors.ts
Ensures we requested AccountIds as a loading state vs. complete state currently, ensuring we don't run effects reacting on `portolioLoadingStatus` unless we *actually* have a loaded portfolio
closes N/A
- None from a functional standpoint
- Put breakpoints in `<AppContext />` effects relying on `portfolioLoadingStatus` and ensure those don't load until we actually have `requestedAccountIds` i.e this guy:
https://github.com/shapeshift/web/blob/1eaa190ef658cf48337fdcaa76503befbb331f4e/src/state/slices/portfolioSlice/selectors.ts#L127
None
> fix: portfolio empty loading state

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/utils/thorchain/index.ts
Relies on Midgard for failure and success detection in conjunction to our current `/tx/status` checks.
This allows us to more reliably detect success Txs when enforcing outbound checks by ensuring we have a succesful `out` Tx, as well as properly detect refunds, both succesful and failed.
closes https://github.com/shapeshift/web/issues/5702
- THOR Tx status detection is still happy for Txs skipping outbound checks (e.g savers deposits or loan repayment if available for your collateral)
- THOR Tx status detection is still happy for Txs enforcing outbound checks (e.g savers withdraws)
- ☝🏽 
- Remove the minimum checks in savers withdraw
https://github.com/shapeshift/web/blob/680c55051da5cb6db26340c2909027c924a37272/src/features/defi/providers/thorchain-savers/components/ThorchainSaversManage …
> feat: improve thorchain Txs failure detection

- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useRepaymentLockData.tsx
Fixes non-deterministic issues with repayment lock data.
As it currently stands, the repayment lock is dependant on a few things:
- `mimir` being fetched, to get `LOANREPAYMENTMATURITY`, used as `repaymentMaturity` i.e the number of blocks before repayments are unlocked, as set by the network, and independant on the current asset/position
- `position` and `blockHeight` being fetched, *only* in the case of fetching a *specific position*'s repayment lock
Same issue as the PR under this one, the reactivity was wrong here resulting in non-deterministic errors. Depending on how fast each request gets to respond, you may end up with the query running with or without the above.
While `mimir` and `blockHeight` tend to be fast to be fetched and I haven't noticed errors in getting the network's …
> fix: repayment lock queries reactivity

- src/pages/Lending/AvailablePools.tsx
- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
- src/pages/Lending/hooks/useLendingSupportedAssets/index.ts
- src/pages/Lending/hooks/useRepaymentLockData.tsx
Fixes the data fetching bits of lending page on the first load, at "Available Pools" default route:
- adds some additional dependency to the `accounts` memoized constant in `useAllLendingPositionsData`, for the precise reason mentioned in the comment, avoiding having no `availablePools` on first render, thus no available pools and no position data
https://github.com/shapeshift/web/blob/5076849d5708562270fc638edbc9cdc86571878a/src/pages/Lending/hooks/useAllLendingPositionsData.tsx#L37-L40
- consumes `useAllLendingPositionsData({assetId})` in `<LendingPoolButton />`, improving loading state while position(s) data is loading
- adds some extra `enabled` safety to `useLendingSupportedAssets` to not run the query when there are no `availablePools`. Since queries are cached for 60 seconds, early …
> fix: lending first render

- src/pages/Lending/Pool/Pool.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/Lending/hooks/useLendingCloseQuery.ts
Actioned following review with @reallybeard:
- fixes wrong asset used as "Receive" asset for repayments
- fixes wrong asset used to calculate collateral decrease
- makes the borrows/repay spin as soon as the confirm button is clicked, *not* on Tx broadcasted, which produces a delay between the click and the spin when using native, and nothing until you confirm the Tx if using MM
- doesn't hide the collateral amount in `<AssetInput />` when withdrawing 100%
N/A
None
- Frame-inject a position that has repayment unlocked (ask beard for the address)
- Ensure the "Receive" asset in repayment confirm is your collateral
- Ensure the collateral deduction (see screenshots) looks good when repaying 100%
- Ensure the confirm button starts spinning on click (you obviously won't be able to sign the …
> feat: lending touchups

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StreamingSwap.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/mockHooks.ts
- src/components/MultiHopTrade/hooks/useThorStreamingProgress/useThorStreamingProgress.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/state/slices/tradeQuoteSlice/types.ts
Stores the state of streaming swaps in redux to allow rendering across different UIs (i.e during trade execution, and the summary after the trade is completed), without re-executing requests.
closes #5710
Not production facing, low risk.
Not required
Demo of trade completion summary with 2 mocked hops as streaming swaps
Demo of trade completion summary with 2 mocked hops as streaming swaps, including 1 failed swap each
> feat: store streaming swap state in redux for multi-hop ui

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/types.ts
This PR fixes:
- broken protocol fees for withdraws, as `expected_amount_deposit` is incorrect for withdraws. There is some inconsistency in the THORNode API currently, where `expected_amount_out` is to-be-deprecated in favor of `expected_amount_deposit`, so we use the latter - however this is inconsistent with withdraws still using `expected_amount_out` with no sign of future deprecation. This means the protocol fees were always 0 for withdraws
- "insufficient funds" sometimes happening for EVM assets, as we try to estimate sweep + fees for them
While at it, also improves the protocol fee calculation for withdraws: if the `expected_amount_out` is `""`, then there is nothing being withdrawn, and the whole amount being withdrawn *is* effectively the fee. This surfaces it at view-layer.
- …
> fix: thorchain savers shenanigans

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Footer.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StatusIcon.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/mockHooks.ts
- src/state/slices/tradeQuoteSlice/constants.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/state/slices/tradeQuoteSlice/types.ts
- src/state/slices/tradeQuoteSlice/utils.ts
- src/test/mocks/store.ts
Refactors the state management of multi-hop trade execution to remove duplicate and redundant states and the resulting logic required to keep them aligned. As a result, there is less responsibility of the view layer to manage and know about the working of trades at a higher level and allows them to dispatch narrow-context actions to redux.
- State is deduplicated to ensure state is unique and purpose specific
- State is nested to ensure the scope of each layer of nesting is easy to track and optional parts of trades (e.g the second hop and approvals) can be skipped without convoluted logic
- callbacks to track error states of hooks owned by child components are now removed
- state changes are dispatched on a per-step basis rather than using blanket incrementation, which simplifies logic …
> chore: refactor multi-hop state tracking to avoid duplicate states and associated logic

- package.json
- yarn.lock
Removed `@shapeshiftoss/hdwallet-ledger-webhid` as a dependency, as it was unneeded.
N/A - QOL.
Small.
Everything should work just as it did before.
☝️
☝️
N/A
> chore: remove hdwallet-ledger-webhid dep

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
- src/lib/utils/thorchain/index.ts
THOR Txs for which we enforce outbound checks (e.g 100% loan repayments, borrows, savers withdraws) can take a very long time to complete. We currently poll every 60 second, 60 times, i.e for a total of 1 hour.
This changes the heuristics of polling by making us polls less, and less frequently, when enforcing outbound checks. Enforcing outbound checks means that those Txs will inherently take a lot longer to complete, hence polling every 60 seconds is guaranteed overfetching, and having a max polling time of 1 hour isn't going to necessarily cut it.
N/A
Low - this makes things *more* reliable for outbound checks enforced, but doesn't change anything when they're skipped
- Ensure outbound checks skipped are still happy e.g savers deposit are still reflected fast
- Ensure outbound checks …
> feat: increase thor polling delay when enforcing outbound checks

- src/config.ts
Fixes error in console due to missing TRM labs url (which is no longer in our project)
NA
Very low risk as this is only cleaning up an unused line of code.
Check the app boots.
> fix: remove unused trm labs url validation

- src/plugins/arkeo/StakingCard.tsx
Note the 0.00% APY as Tokemak APR is sad: https://app.tokemak.xyz
closes https://github.com/shapeshift/web/issues/5706
None
- FOXy token holders is happy
- ☝🏽 
- ☝🏽
> fix: foxy holders arkeo page loading state

- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
see testing thread starting at https://discord.com/channels/554694662431178782/1174550133770301480/1182073567333072967
We're currently getting quotes with a buffer of 1% for THORChain lending 100% repayments, for the precise case of 100% not being 100% because of THOR market data discrepencies.
However, we do not use that amount when building the actual send input, resulting in collateral repayments not being triggered, and only a small amount of dust left in the loan instead.
N/A
None, this was inconsistent and wrong previously
- None if you don't have repayment unlocked
- If your repayment is unlocked, ensure you get your collateral back when doing a 100% repayment
- ☝🏽 
- ☝🏽
> fix: lending use safe buffer at repay confirm step

- src/lib/swapper/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
The PoC implementation of longtail to L1 only supports swapping from longtail on Ethereum assets.
This PR ensures that we only get a longtail to L1 quote if the sell asset is on Ethereum.
N/A
Small, this feature is still behind a flag, and this should only make the flagged feature safer.
Nothing specific required at this time, only testing as part of the general release is fine.
☝️
☝️
N/A
> chore: enforce eth-only longtail to L1

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Footer.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowance.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
- src/state/slices/tradeQuoteSlice/constants.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/state/slices/tradeQuoteSlice/types.ts
Fixes ability to proceed with a trade while approval requirements are still being fetched by applying a loading state to the button until everything is initialized.
NA
Not production facing - low risk.
Not required.
Loading state while approvals are being checked
Once approvals are loaded, loading state is cleared
> feat: use loading state on multi-hop trade confirm button

- src/AppProviders.tsx
- src/context/AppProvider/AppContext.tsx
Refetches market data every 15 minutes, *if* the window/tab is active only.
See https://stackoverflow.com/questions/69982787/refetchintervalinbackground-does-not-stop-a-query-with-refetchinterval-from-refe for what it means for a window to be active according to react-query's `FocusManager`'s:
```
we use the provided focusManager, which listens to the visibilitychange and focus events of the browser. The browser emits those if you switch to a different tab. But I've seen these events not being emitted when I have two windows next to each other and I just focus the other window, because then it's not in the "background".
```
i.e only switching to a different window/tab while still having the app tab opened will *not* toggle the background state to true, it's only triggered when you have …
> feat: refetch market data at interval

- src/lib/utils/thorchain/lending/types.ts
- src/pages/Lending/Pool/components/Repay/Repay.tsx
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/hooks/useLendingCloseQuery.ts
... and `repaymentPercentOrDefault` as well.
See https://github.com/shapeshift/web/pull/5795 for context. 
5798 ensured we use the proper buffer at confirm step too, but there's still a slim chance the amount we *eventually* send could change if the market data refetches. We do *not* refetch market data at interval currently but we will eventually do so:
https://github.com/shapeshift/web/blob/2f3f96b4e936a60bdae328c293bb97efecaf6fdd/src/context/AppProvider/AppContext.tsx#L251-L254
Having new market data would result in either higher or lower crypto amounts than the one we originally sent to get a quote. This ensures we use *locked* values instead.
While at it, also adds some extra paranoia safety WRT repaying 100/101% but not having a collateral decrease.
N/A
- None until we can test this …
> feat: use locked quote repayment amount on confirm

- src/lib/swapper/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
For longtail to L1 swaps, passes through the error returned from `getL1quote`, if it exists, instead of returning a generic error.
This results in us correctly alerting the user that the sell amount is too low for longtail swaps.
N/A
Small.
When quoting a longtail swap we should now show the "Amount too small" error when the sell amount is not large enough.
☝️
☝️
> fix: show thorchain error on longtail to l1

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowance.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalNeeded.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useThorStreamingProgress.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useApprovalTx.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useExecuteAllowanceApproval.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/hooks/useIsApprovalNeeded.tsx
- src/components/MultiHopTrade/hooks/useAllowanceApproval/useAllowanceApproval.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
Decouples approval tx completion from trade progression by allowing the trade to proceed if an allowance approval was executed external to this app (i.e approval was needed, and user did the approval elsewhere). Loading state is preserved while executing an approval, but is not required for the trade to progress as long as adequate allowance was found on-chain.
closes #3331
Risk of allowance approvals broken in single-hop and multi-hop UIs.
Check allowance approvals are working for the existing single-hop trade UI. Multi-hop approvals will be tested in an upcoming pre-release test.
On the left, the multi-hop ui is waiting for the user to execute the allowance approval, but is also checking on-chain in case the user approves in a different app. On the right, we're using prod to execute the …
> feat: automatically progress trades when approvals are executed externally

- src/lib/swapper/swappers/OneInchSwapper/endpoints.ts
- src/lib/swapper/swappers/OneInchSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/OneInchSwapper/utils/fetchOneInchSwap.ts
- src/lib/swapper/swappers/OneInchSwapper/utils/types.ts
- src/state/helpers.ts
Enables cross-account trading for 1inch.
Cross-account 1inch transactions created from this branch:
1. Fee asset account 0 to ERC20 account 1: https://snowtrace.dev/tx/0x93dea99cfa2663635a6314e0340fd890404ed3d999c04862520e83dbbacdf95f
2. Approval from non-0 ERC20 account: https://snowtrace.dev/tx/0xff2c18378bd4fff274d471841a7d28d5d188d86c84866f420aa4677e52ec213b
3. ERC20 account 1 to fee asset account 0: https://snowtrace.dev/tx/0xa9b8cca119c09f3bd6c96f1b9eaea31b0119a71b537b7d592164154cde79c695
Closes https://github.com/shapeshift/web/issues/4966
Medium. It's a small change, but as always, touching account selection is risky as mistakes can mean lost funds.
Confirm that 1inch quotes now show up when trading between accounts, and that they and sent and received from the correct accounts …
> feat: add cross-account trading for 1inch

- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/state/helpers.ts
Add cross-account trading to LifI.
Cross-account LiFi transactions created from this branch:
- https://snowtrace.dev/tx/0x686bc6eb039a38b9c0fd5a5e8d03307a8256cffad042a82fe2128c31a73921d0
Relates to https://github.com/shapeshift/web/issues/4966
Medium. It's a small change, but as always, touching account selection is risky as mistakes can mean lost funds.
Confirm that Li.Fi quotes now show up when trading between accounts, and that they and sent and received from the correct accounts when executed.
Sanity check logic.
☝️
> feat: enable lifi cross-account trades

- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
Adds a special case when calculating the network fees for DOGE to fallback on a hardcoded `satoshiPerByte` value that is high enough to go through (the number is a little over double the current "fast" value).
Note, https://api.dogecoin.shapeshift.com/api/v1/fees seems to be working fine now, so it won't actually change behaviour right now.
Closes https://github.com/shapeshift/web/issues/5822
Small - user could pay more DOGE in transactions fees if this is not implemented correctly.
Not currently possible without intercepting the response to https://api.dogecoin.shapeshift.com/api/v1/fees
Sanity check logic.
DOGE sends should work.
N/A
> feat: add fallback doge transaction fee

- src/components/MultiHopTrade/components/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/AssetSelection.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
Fixes the ability to open the asset selection modal/dropdown while assets are still being loaded, resulting in an empty list. The solution was to trigger the build-in loading state to the button while assets are loading.
NA
Low risk.
check asset selection still works
check loading state stops when app is loaded (this may happen too quickly to see if your internet connection is fast)
Loading state look like this
> fix: add a loading state to the asset dropdown

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
Fixes broken error message for savers withdrawals where insufficient fee asset for gas.
NA
Low risk
Check error message on savers withdrawals is working as expected.
Reported issue:
> fix: broken error message for savers withdrawls

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Approve.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/swapper/swappers/ThorchainSwapper/utils/useRouterContractAddress.ts
We do *not* want to exclude halted pools when getting inbound addresses for withdraws, as halted pools can still be withdrawn from.
While at it, also ~~introduces a loading state so we do not react too early on missing inbound address for chain and throw~~ makes `useRouterContractAddress` expose a cached react-query, so we can leverage loading states and fire in a non-hook fashion in callbacks, ensuring we await the data.
closes N/A, see https://discord.com/channels/554694662431178782/1184599011349516418/1184599056815755294
Can't break this more than it was, i.e none
- Open an EVM token savers overview page and click withdraw
- Select an amount and ensure we do not see a `No router contract address found for feeAsset: {asset}` error
- ☝🏽 
- As an added bonus, note *inbound_addresses` XHRs …
> fix: thorchain savers borked withdraws

- package.json
- yarn.lock
Bump `wagmi` resolution for the `@wherever/react-notification-feed` package to `1.4.12`.
https://github.com/wevm/wagmi/releases/tag/wagmi%401.4.12
N/A - improve security.
Small, minor bump.
Wherever should still work as expected.
☝️
☝️
N/A
> chore: bump wagmi resolution to 1.4.12

- src/plugins/walletConnectToDapps/WalletConnectV2Provider.tsx
Ensures we clear connected WalletConnect to dApps session when connecting a wallet via WalletConnectV2 wallet provider.
closes https://github.com/shapeshift/web/issues/5408
WCV2 wallet connection may be broken, test accordingly
- Connect to native or KK
- Connect to Uniswap as a dApp (preferred, as not all dApps seem to handle disconnections gracefully which can give false positives for testing this)
- Notice the dApp is connected in the WC dApps header menu, and your wallet EVM address displays as connected in Uniswap's header WC menu
- Connect a wallet via WalletConnect
- Ensure the wallet is properly shown as disconnected in Uniswap
- Reconnect to the same native wallet and notice dApp connection is gone
- ☝🏽 
- ☝🏽 
- Native connected, no dApp connection to Uniswap just yet
- Connected …
> fix: disconnect all wc dApps sessions on wcv2 connect

- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
closes https://github.com/shapeshift/web/issues/5818
Swapper input may be borked under certain scenarios?
- Dot notation input is happy as a first input
- Dot notation input is happy when inputting an integer/float *not* in the dot notation (i.e 0.1 or 1, but not .1), selecting all text, and inputting a dot notation number instead
- Input doesn't wrongly change to the wrong notation when the input loses focus (i.e click outside of swapper)
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/4598325c-dbb4-43af-9621-ef5a66b63611
> fix: swapper dot-first notation input

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StatusIcon.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/state/slices/txHistorySlice/txHistorySlice.ts
- src/state/slices/txHistorySlice/utils.ts
- src/state/store.ts
- src/state/subscriptionMiddleware.ts
Ooh wee this was a tricky one. 
We want to show the users balance immediately after a trade was completed. About half the time, the app sees the tx before blockbook, causing us to render the old balance. Result would be "WHERES MY MONEY" in discord.
- In the txHistory slice transactions are indexed by account ID, txhash, address and (in thorchain case) memo. We don't care about any of that (thankfully), we only need to know that a tx was transmitted to the app via WS so we are safe to call a tx complete. 
- The thunk resolves when the txhash exists in the slice.
- If a multi-hop trade has an intermediary asset that is not supported by our stack, the tx hash will never arrive. In this case we skip awaiting it because we cant show balance for an unsupported asset anyway. …
> fix: await tx indexing before completing a trade

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccessTemp.tsx
Temporarily patches the multi-hop "trade success" ui to not display balances. This sidesteps the race condition currently present where our app renders a successful trade summary before blockbook is able to index the transaction, resulting in "you now have 0 BTC in your wallet" text.
NA
Low risk.
Check multi-hop trades complete.
https://github.com/shapeshift/web/assets/125113430/70dc7b8c-bcb5-45c7-860a-e2192ca1af8f
> fix: temporarily patch UI to avoid showing balance on trade completed ui

- src/lib/swapper/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/longTailHelpers.ts
Adds UniswapV3 pool optimization to long-tail swaps, enabling more assets and better rates.
This PR adds the ability to search all fee ranges for a given asset pair's available pools, get a quote for each, and transact against the contract resulting in the best rate. In particular, we'll get better rates for assets with tight liquidity pools.
Also adds support for additional assets that did not have pools for the `3000` fee range of UniswapV3.
An example to see this working: compare the rate between this branch and prod for LINK to DOGE.
Closes https://github.com/shapeshift/web/issues/5878
High risk to long-tail swaps - we'll want to test these again, as messing up the contracts here (e.g. using a non-whitelisted  contract) could lead to funds landing in a black hole.
Perform longtail …
> feat: search entire UniswapV3 fee range for longtail swaps

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
... a.k.a have your cake and eat it.
The follow-up of https://github.com/shapeshift/web/pull/5839. See this comment from @0xApotheosis:
> Re-tested and confirming the previous debounce issue is resolved.
> It seems a bit bizarre to me though that we can't fix the additional request for the old quote whenever we start trying to get a new quote? That seems pretty wild...
This was caused by rugged debouncing. Fixed by only debouncing the sell amount instead of the whole input. By asking ourselves the question "Why are we debouncing?" (i.e, to avoid spamming endpoints as users are inputting a sell amount), the fix becomes a lot more straightforward: debouncing the whole input, as a non-immediate operation that requires some ms of computing becomes the obvious cause of previous quotes firing. …
> feat: swapper safe debouncing

- src/state/slices/txHistorySlice/selectors.ts
Two birds one stone:
- ensures we only select *wallet* Tx history
- ensures we honor the order of `txIds` instead of relying on unordered `txs` , making the results sane and ordered
closes https://github.com/shapeshift/web/issues/4589
None?
- Global search Txs do not leak cross-wallets
- Global search Txs are properly ordered, including when searching i.e latest come first. No search input means most recent transactions displayed, similar to the Activity tab.
- ☝🏽 
- ☝🏽 
Three wallets connected: Two MM ones, and an empty native one
- MM wallet 1
- Native empty wallet
- MM wallet 2
> fix: global search leaking Tx history

- src/lib/utils/thorchain/lending.ts
- src/lib/utils/thorchain/lending/types.ts
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/hooks/useLendingCloseQuery.ts
a.k.a accommodates for the new `repay_bps` param breaking change in THORNode 1.125.0 swagger document.
While at it, now that sane `repay_bps` are expected vs. an amount, which can have some market data discrepencies between us and THOR, removes the concept of "repayment percent or default" (i.e 100 or 101%).
closes https://github.com/shapeshift/web/issues/5897
None, this tackles a breaking change upstream.
- THOR repayment quotes are happy again
- ☝🏽 
- ☝🏽
> fix: make THOR repayments great again

- src/assets/translations/en/main.json
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
Simple few LoC low hanging fruit warning against users thinking their funds are lost because they can't withdraw, by explaining that the quoted fees would eat their withdraw amount.
N/A
- This could be displayed when it shouldn't, and vice-versa, test accordingly
- When the protocol fee *is* the amount being withdrawn, the warning is displayed
- When the protocol fee is anything else (i.e fees don't eat the whole amount), the warning isn't displayed
- Ensure this only displays when the quoted expected_amount_out is `""`
- ☝🏽
> feat: savers withdraw where is my money safeguard

- src/state/apis/swappers/swappersApi.ts
Fixes issue where missing market price data for some assets makes it impossible to get a quote for them. Fixed by moving the line that hydrates the price data above the error 🤡
closes #5922
Risk of broken quotes.
Check quotes for WETH as the sell and buy asset are working.
Note there is an error being thrown by the thorchain swapper for WETH but is unrelated to this task.
> fix: unable to get quotes for weth

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
This should be set in the `useEffect` as well - this PR fixes it.
closes N/A
None, this feature is a smallish UX touchup and doesn't bring regression risks
- When applicable, the dangerous withdraw warning consistently displays, regardless of the asset/amount
- When *not* applicable (i.e a non-zero amount would be withdrawn), the warning does *not* show up
- ☝🏽 
- ☝🏽
> fix: consistently display THOR dangerous withdraw warning when applicable

- packages/chain-adapters/src/utxo/utxoSelect/index.ts
Ensures change is consistently sent to the `from` address is passed - regardless of whether or not the utxoSelect result outputs contain an `OP_RETURN_DATA` or not.
closes https://github.com/shapeshift/web/issues/5925
- Low to none. Changes the heuristics for change output detection to... actually detect the change output. Hardcoding it to first index was a mistake, so this is the same, but safer and consistently working.
- Savers UTXO deposit Txs have their change sent back to the same address
- Savers UTXO withdraw Txs *still* have their change sent back to the same address
- Lending UTXO loan open Txs have their change sent back to the same address
- ☝🏽 
- ☝🏽
> fix: send change back to from address when outputs contain OP_RETURN_DATA

- packages/swapper/src/types.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/types.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/OneInchSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
- src/lib/swapper/swappers/utils/test-data/setupSwapQuote.ts
Reverts to the original behavior of https://github.com/shapeshift/web/pull/4539, disabling affiliate fee for 0x, 1inch, and Li.Fi (@woodenfurniture to confirm the latter).
tl;dr of this is we lost the granularity of disabling EVM KK donations (now affiliate fees) with https://github.com/shapeshift/web/pull/5403, so this brings it back.
To be followed-up with:
- Removing the donation feature entirely and its flag to keep things simple and make debugging easier without the donation/FOX discounts branching
- A draft PR removing the monkey patch entirely, to be opened after extensive testing and confirming with operations EVM "donations" (affiliate fees) aren't affected by this bug anymore on KK
closes https://github.com/shapeshift/web/issues/596
Theoretically low to none but effectively …
> fix: revert donations bandaid for 0x, 1inch, and LiFi

- packages/caip/package.json
- packages/chain-adapters/package.json
- yarn.lock
We have a webpack build issue with external `.cjs` packages that are used in workspace packages.
The recently updated `axios` package in https://github.com/shapeshift/web/pull/5943 exposed this issue.
This PR is a bandaid until we can work out how to support `.cjs` packages in our build pipeline.
N/A - release blocker.
Medium - affects sends and swaps.
Sends and swaps should be great again.
☝️
☝️
> fix: lock axios to older, none esm version

- src/lib/utils/thorchain/lp.ts
- src/lib/utils/thorchain/lp/types.ts
Adds additional THORChain LP logic, including fns needed for `estimateAddThorchainLiquidityPosition`, which will then support `addThorchainLiquidityPosition`.
Relates to https://github.com/shapeshift/web/issues/5960
Small - logic isolated to a helper file.
N/A - if CI is green we are good to go.
☝️
Add to `PoolsPage.tsx`
```ts
useEffect(() => {
const testAdd = estimateAddThorchainLiquidityPosition({
runeAmountCryptoThorPrecision: '100000000', // 1 RUNE asym deposit
assetId: btcAssetId,
assetAmountCryptoThorPrecision: '0',
})
;(async () => {
console.log('xxx testAdd', await testAdd)
})()
}, [])
```
☝️
> chore: thorchain lp add/remove logic

- packages/swapper/src/types.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/types.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/OneInchSwapper/getTradeQuote/getTradeQuote.ts
- src/lib/swapper/swappers/ZrxSwapper/getZrxTradeQuote/getZrxTradeQuote.ts
- src/lib/swapper/swappers/utils/test-data/setupSwapQuote.ts
Removes monkey patch logic fixing broken trades on keepkey when donations were enabled. See original issue https://github.com/shapeshift/web/issues/4518
Verified this is no longer required by deploying this branch to `wood` and getting ops to test trades with fees on keepkey. Trades succeeded and fees appear to be received in our treasury address.
closes #5988
This has already been tested, but still may be some risk of broken trades on keepkey where an affiliate fee is payable.
Check trades are working (with and without affiliate fees) while connected to keepkey.
> fix: broken fees on keepkey evm trades

- src/lib/utils/thorchain/lp.ts
Makes sure we use the same reference data points for base (a.k.a absolute, current, now), making data more accurate, and consequently percent change as well.
follows-up closed https://github.com/shapeshift/web/issues/5939
Overfetching, which will need to be tackled holistically
- Base and percent change values for pools still look sane
- ☝🏽 
- ☝🏽 
- THORYield
- Develop
- This diff - note how 24h volume now matches THORYield's one very closely because of the same *actual* 24h window used vs. "since midnight"
> feat: thorchain lp consistent base values over percent change

- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
Fixes broken trades from atom due to incorrect message type being attached to the transaction.
closes #5995
Risk that trades from atom are still broken
Check trades from atom are working
Send request at start of transaction was successful (was http 500 previously):
Trade succeeded:
> fix: atom trades using incorrect message type

- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidity.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityConfirm.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquityStatus.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/DepositType.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/PoolSummary.tsx
This PR does a basic wire-up of THORCHain LP add liquidity - also brings the notion of handling sym/asym differently at view-layer time by displaying one or both assets.
Note, this does not yet wire-up the standalone "Add Liquidity" component, which will be slightly different because of the notion of pool selection.
This also does *not* wire-up amounts, as these will be coming from confirmed/quote from react-query, which we don't have yet.
- contributes to https://github.com/shapeshift/web/issues/6018
None, this isn't live yet, and many things are either unknown or very likely to change here
- Wiring up of displayed assets looks sane
- Discrimination of sym/asym looks sane at view-layer time, with the right components displayed depending on the a/sym type i.e either one, the other, or …
> feat: basic add liquidity wire-up

- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/PoolSummary.tsx
- Wires up input and fiat fields for both symmetrical and asymmetrical LP quotes
- Adds the following add liquidity "quote" calculations to the UI:
- Slippage (in RUNE)
- Rune per asset
- Share of the pool
Contributes to https://github.com/shapeshift/web/issues/6019
Small - isolated to LP flag code paths.
Play with the "Add Liquidity" inputs and see the data populate.
Not yet required.
> feat: sym & asym add LP quotes input and calcs

- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/DepositType.tsx
Wires-up "Add Liquidity" as a standalone page.
- closes https://github.com/shapeshift/web/issues/6018
Low - ensure everything behaves as expected. This is under feature-flag, however something something caution consider PR as if it was to land in prod
- The "Add Liquidity" component looks sane both on click, and on page refresh
- It is possible to select any supported pool asset
- The component behaves the same as in the pool view except for two differences:
- The pair selection is only possible when in standalone mode
- The "Deposit Amounts" radio options are only displayed when in standalone mode
The reason for these two discrepancies is in a pool page view, you're already in the context of an asset + a/sym and can't change it
- ☝🏽 
- ☝🏽
> feat: standalone "Add Liquidity"

- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidity.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityConfirm.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquityStatus.tsx
Wires up the quote in confirm and status screens, bringing in the notion of "confirmed quote".
closes #6019
None
- Ensure the confirmed quote data is propagated over confirm and status screens
- ☝🏽 
- ☝🏽
> feat: wire-up confirmed "Add Liquidity" quote

- src/state/apis/swappers/helpers/validateTradeQuote.ts
Fixes a bug introduced in https://github.com/shapeshift/web/pull/5971/files#diff-b6f4d6672824399e71740531e3b09efe3ad3fabeb3ad6c4ce0763969f9d39ab7R104, where we try and select `selectSellAmountCryptoBaseUnit(state)`, which yields `undefined` because `firstHop` is undefined at that time:
Fixed by
1. using the correct `local` quote and running the same selector logic against it, instead of introspecting the not-yet-defined hop state
2. as a paranoia check, not assuming dangerous amount if `!sellAmountCryptoBaseUnit` which should not happen anymore, but in case it does, we are safu.
closes https://github.com/shapeshift/web/issues/6037
This isn't high risk - while it *does* touch quote validation, it is moderate to low risk as we had all the logic baked in already for a long time and stable, …
> fix: dangerous small amount warning

- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
I added this in https://github.com/shapeshift/web/pull/6052/commits/3c5c907403bda0f1fe7547a3eda5942c08de5ee3, but it's actually redundant and already covered by the line:
```ts
assert(amountOutMin > 0n, 'expected expectedAmountOut to be be a positive amount')
```
Related to https://github.com/shapeshift/web/issues/6017
Low
THORChain quotes and error messages for longtail and non-longtail should still work as expected.
☝️
☝️
N/A
> chore: remove redundant throw

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
Fixes "Stream Status" progress bar being displayed for *all* swaps instead of streaming swaps only
N/A, this wasn't captured as an issue but spotted in https://github.com/shapeshift/web/pull/6051
- Low to none - we can ensure streaming swaps still have "Stream Status" displayed as a paranoia check, though if we can't test this because of funds required for streaming swaps testing, this has effectively 0 risk
- Non-streaming swaps do *not* have "Stream Status" displayed at swap progress and complete steps
- ☝🏽 
- ☝🏽
> fix: stream status displayed for non THOR streaming swaps

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
Fixes the receive amount on the confirm screen showing the _before_ fees receive amount, instead of the _after_ fees receive amount we show on the quote screen.
Closes https://github.com/shapeshift/web/issues/6065
Small
For all swaps, particularly those using THORChain, the amount shown on on the quote screen should match the amount shown on the confirm screen.
☝️
☝️
Note that the values now match:
> fix: receive amount on confirm screen

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
Derp - `subscribeTxs` *has* to take a pubKey for Ledger, as we won't be able to derive the account address when susbcribing Txs otherwise, hence we will never subscribe to Txs.
N/A
None, this was an obvious ommission
- Do a self-send on account 0 and 1 and ensure the Tx is properly detected
- Do a send across accounts and ensure balances the Tx is properly detected on both accounts
- ☝🏽 
- ☝🏽 
- Accounts
- Susbcription
src="https://github.com/shapeshift/web/assets/17035424/d41481b2-a23a-4cfd-b1cb-6ebb6397aa19">
- Self-send on account 1
- Send account 0 -> 1
> fix: cosmos ledger ws

- src/lib/getTxLink.ts
Fixes wrong Txid link for long-tail THOR Txs, following up on https://github.com/shapeshift/web/pull/6067
Relates to https://github.com/shapeshift/web/issues/6017
None
- Long-tail Tx links are happy i.e aren't prefixed with the EVM `0x` prefix
- ☝🏽 
- ☝🏽 
- Develop
- This diff
Happy Tx link 🎉
> fix: long tail explorer Tx link

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
Reduces the number of state changes on the preview button on the trade input component.
closes #6076
Moderate risk of incorrect text, loading state or error states being rendered on the preview trade button.
Moderate risk of selected trades being different to what you execute - pay special attention to issues like this when testing and reviewing.
Check that trade input, quotes and loading state works correctly on the trade input.
https://github.com/shapeshift/web/assets/125113430/9dc55a45-4551-4f48-a8f2-48519e9a3e31
> fix: reduce preview trade button state changes during load

- src/state/apis/swapper/helpers/validateTradeQuote.ts
- src/state/apis/swapper/swapperApi.ts
Spotted in https://github.com/shapeshift/web/pull/5971/files#diff-b6f4d6672824399e71740531e3b09efe3ad3fabeb3ad6c4ce0763969f9d39ab7R210
see:
https://github.com/shapeshift/web/blob/3b9b81e29859ae6f60c2f21e7efc4ee0a527591c/src/state/apis/swappers/helpers/validateTradeQuote.ts#L210
vs. previous implementation:
https://github.com/shapeshift/web/blob/658137910d7d0e2d4ffae29aea16b256a50adaa4/src/components/MultiHopTrade/hooks/quoteValidation/useActiveQuoteStatus.tsx#L47-L53
This means that we effectively do *not* validate on the sell side anymore, but on the receive side instead, which is an extremely high-risk regression.
This however is mitigated by the fact we have a similar and correct check in-place at input step:
https://github.com/shapeshift/web/blob/255d8b7f4806b906365ec301ce2f4cb793eea08 …
> fix: regression of smart contract sell address checks on validateTradeQuote

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
Fixes the quote loading state so we don't show "No rate available" while we are still looking for quotes.
Develop:
https://github.com/shapeshift/web/assets/97164662/fec4b0c0-f810-4328-a73f-5e88b6d9fc30
This branch:
https://github.com/shapeshift/web/assets/97164662/a6e6016b-8efb-4bc2-af58-ba44ca8cb265
Note, we still get a small flash of "No rate available", but that is not intended to be fixed in this PR.
N/A
Small
The issue usually occurs when fetching the first quote after a refresh/initial load.
Get a quote and confirm the loading state shows for the rate whilst the quotes are loading.
☝️
☝️
N/A
> fix: quote loading state

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/TradeQuoteContent.tsx
Fixes completely incorrect percentage difference values on quotes:
1. should not show 0.00% differences
2. should show the percentage difference between rendered receive amounts on quotes
NA
Low risk as this was broken to start with.
Check that the reported percentage differences are correct compared to the best quote.
Develop:
This PR:
> fix: completely borked quote percentage differences

- src/pages/ThorChainLP/queries/hooks/useUserLpData.ts
Fixes `liquidityProviderPosition`'s `assetId` key, which was passed a hardcoded string instead of the assetId.
Closes https://github.com/shapeshift/web/issues/6091
Small - change is behind a feature flag.
Navigating directly to an LP position (e.g. `/pools/poolAccount/eip155:43114:0x32dbc9cf9e8fbcebe1e0a2ecf05ed86ca3096cb6/eip155:43114%2Fslip44:60*asset`) is great again.
☝️
N/A
N/A
> fix: lp data on refresh/direct navigation

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
This reverts commit 04574b89276b3fc23c736e62edf9c5ef1520d7a0 (https://github.com/shapeshift/web/pull/6088) due to it causing an undesirable side effect when quotes refresh.
It will be re-implemented in @woodenfurniture's upcoming PR that holistically deals with quote loading state.
N/A
Small
The inverse of https://github.com/shapeshift/web/pull/6088.
☝️
☝️
N/A
> revert: quote loading state

- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/AddLiquitity/components/PoolSummary.tsx
- src/pages/ThorChainLP/components/LpType.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
This PR makes a number of improvements to the LP UI and UX:
- Moves the symmetrical radio box to be the middle option, with each asymmetrical option now on either side of it
- Fixes the symmetrical radio box highlighting so that it can now be checked (selected with a border) and is set as the default option on component load
- Adds loading skeletons for consumers of the async `estimateAddThorchainLiquidityPosition` function
- Fixes "NaN" from rendering when the opposite crypto field when the input amount is removed (i.e. becomes an empty string)
- Adds keys to `TradeAssetInput` to clean up console sadness when rendering `AddLiquidityInput` and `RemoveLiquidityInput`
- Hides `PoolSummary` when no input value is entered
Broadly contributes to https://github.com/shapeshift/web/issues/5940 …
> feat: lp UI & UX improvements

- src/state/apis/nft/constants.ts
- src/state/apis/nft/nftApi.ts
- src/state/migrations/index.ts
Makes the NFT tab great again. It is currently detecting all NFTs as spam.
N/A, spotted in https://github.com/shapeshift/web/pull/6118
Low, but now that we don't detect empty text as spammy anymore, Tx history / wallet NFTs may be a bit more spammy, give me a bit of a regression test
- Test both with demo wallet and frame-injected address of a known NFT degenerate fren
- NFTs in NFT tab are now happy and not too spammy
- Tx history / assets list still isn't too spammy
- ☝🏽 
- ☝🏽 
- Develop
- This diff
- Develop
- This diff
Note the additional N/A assets, which are not present in develop
> fix: missing NFTs in NFT tab

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/hooks/useAccountIds.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
- src/state/slices/tradeInputSlice/selectors.ts
Does what it says on the box - when the swapper originally mounts, the `buyAssetAccountId` should be synchronized with the `sellAssetAccountId`'s account number, *if* there is a matching account on that index on the buy side.
closes https://github.com/shapeshift/web/issues/6121
Theoretically low, effectively medium in terms of domain touched. While this technically brings back the behavior that was intended (see the removed/reworded comment), if we got this wrong, there is a risk of funds ending up in the wrong account
None
- Have a balance of buy asset that is higher on any 1+ account than on your 0th account
- On swapper original mount, ensure that the buy …
> fix: synchronize buyAssetAccountId to sellAssetAccountNumber on swapper mount

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/RecipientAddress.tsx
- src/state/slices/tradeInputSlice/selectors.ts
- src/state/slices/tradeInputSlice/tradeInputSlice.ts
- src/test/mocks/store.ts
Follows-up on https://github.com/shapeshift/web/pull/6072, tackling the issue spotted by @0xApotheosis in https://github.com/shapeshift/web/pull/6072#pullrequestreview-1863934445:
> 🤔 Probably not a blocker, as we no longer crash in this state, but we still don't ensure the "Preview Trade" button is disabled whilst manually editing the address
- relates to https://github.com/shapeshift/web/issues/5883
Low to none, ensure it's still possible to continue to trade confirm both with the flag on and off
- See risks
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/dca1faab-12a8-4a07-a99b-fbaf3f92857a
> feat: disable trade preview while custom recipient is editing

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeAmountInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
- src/state/slices/tradeInputSlice/selectors.ts
- src/state/slices/tradeInputSlice/tradeInputSlice.ts
- src/test/mocks/store.ts
Prevents clearing trade input state when previewing a trade and clicking "back".
Includes changes to manage input sell amounts in redux.
closes #6109
Moderate risk as this changes the behavior of trade input state between routes for trade input/preview/execution.
All trades.
Check trade input behaves as expected
Ensure clicking "back" when previewing a trade maintains the previous input state
Ensure there is no way of somehow executing a trade with stale quotes or incorrect input data
> fix: dont nuke trade input state when backing out of a trade preview

- src/pages/ThorChainLP/components/LpType.tsx
Fixes the current shenanigans WRT radio selection, where selecting an asym side then switching assets would select sym as a default under the hood, but whatever was the previously selected radio option will stay selected.
N/A
- Go to "Add Liquidity" page
- On the default pool, select either the AVAX or RUNE sym side
- Select another pool
- Ensure the radio selection is reset to the default sym side
- develop
https://github.com/shapeshift/web/assets/17035424/649cf46f-6f37-4561-817b-71aa29b11828
- this diff
https://github.com/shapeshift/web/assets/17035424/e490f7e5-3169-4db6-a831-b2ce85085895
https://github.com/shapeshift/web/assets/17035424/8aa083ca-e52b-4fcf-bc10-3 …
> fix: thorchain LP add liquidity radio shenanigans

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
i.e something something hooks not singletons, only the last stepper's step needs `receiveAddress`, but all instances were calling it, resulting in very slow swapper confirm step, each step fetching the receive address and being effectively loaded sequentially.
Moved the last step's tag to its own component consuming said hook and while at it, added a skeleton while `receiveAddress` is loading.
closes https://github.com/shapeshift/web/issues/6142
- Swapper confirm step is great again
- ☝🏽 
- ☝🏽 
Spot the 4 differences, can you guess which one is develop and which one is this diff?
https://github.com/shapeshift/web/assets/17035424/db56eaf9-8a30-4121-98f5-dcfc8cd79e10 …
> fix: fire useReceiveAddress() hook only on last step stepper

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/context/AppProvider/AppContext.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/pages/Accounts/AddAccountModal.tsx
- src/state/slices/portfolioSlice/portfolioSlice.test.ts
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/selectors.ts
fix: explicitly pass wallet device id when setting accounts (#6156)
fix: fire useReceiveAddress() hook only on last step stepper (#6144)
> chore: release v1.535.0

- src/Routes/Routes.tsx
- src/Routes/RoutesCommon.tsx
- src/components/Layout/Header/AppLoadingIcon.tsx
- src/components/Layout/Header/Header.tsx
- src/components/Layout/Header/SideNavContent.tsx
- src/components/Layout/Layout.tsx
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/context/ModalProvider/ModalProvider.tsx
- src/context/ModalProvider/types.ts
- src/utils/makeSuspenseful.tsx
Adds lazy loading to all pages and modals, with spinner so app doesn't look broken during load (as is currently with trade page).
Improves script eval marginally for faster time to interactive which is something that desperately needs improving for mobile devices.
NA
Low/moderate risk of pages or modals not displaying at all, or the spinner somehow appearing in an unexpected way.
Check all pages and modals are loading and initially displaying as intended. Also check wallet connect dapps drop-down is loading. 
There will be a spinner on the first load which is expected - the idea here is we're moving the load time to when a page is first viewed rather than …
> perf: lazy load all pages

- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.test.ts
- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
Paranoia PR, honoring the THORChain deposit memo as-is from THOR, instead of adding `::ss:0` ss affiliate and 0 bps
See https://discord.com/channels/838986635756044328/929872517794000986/1205168906738597928 for more details:
```
Potential Loss of Funds for Savers Deposit w/ Affiliate Fee
If your UI is taking an affiliate fee on savers deposits, please continue reading. This is very important and could result in loss of customer funds.
A user makes a deposit and there is a thorname + affiliate fee set, e.g. +:BSC/BNB::mydex:10 : if you did not register an alias for that chain on your affiliate thorname, the affiliate fee is unable to be paid out. This will cause the transaction to fail, and due to some other bug in THORChain, the users funds will be swallowed. We hope to address the root …
```
> feat: remove thorchain deposit memo monkey patch

- src/components/MultiHopTrade/components/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/AssetSelection.tsx
Removes useless zerion request from asset selection.
Accounts for about ~50% of zerion reqs (probably) so $1500 a month for data we never use.
relates to #6154
Extremely low risk.
Check asset selection is working.
> chore: dont needlessly fetch related assets from zerion in asset selection

- src/lib/utils/thorchain/lp.ts
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidity.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
Wires up "Remove liquidity" logic, including:
- pre-populate removal amount as 50% of position
- wire up sym and asym user inputs
- wire up percent slider and buttons
- wire up removal slippage
Still to do as follow-up PRs:
Contributes to https://github.com/shapeshift/web/issues/5960
Small - only UI things behind a feature flag.
THORChain LP.
TODO
Play around with the percentage options (the slider and the buttons) and ensure it feels right.
N/A
> chore: remove liquidity wiring

- src/context/WalletProvider/WalletProvider.tsx
tl;dr:
- #6156 brought over some changes in portfolio upserting, in particular having `walletId` in its `accountMetadataByAccountId` payload
- the `walletId` was gotten from `walletState`, i.e `walletState.deviceId`, this guy:
https://github.com/shapeshift/web/blob/fce52949f6b05ea3d24aa56d29a0eb892dd8c538/src/context/WalletProvider/WalletProvider.tsx#L120
- `SET_WALLET` action was setting `deviceId` in `walletInfo`, but not as a root property:
https://github.com/shapeshift/web/blob/fce52949f6b05ea3d24aa56d29a0eb892dd8c538/src/context/WalletProvider/WalletProvider.tsx#L183-L196
- Eventually,`selectWalletChainIds` wasn't able to detect the added account since the wrong `deviceId` was upserted while upserting portfolio:
https://github.com/shapeshift/web/blob/fce52949f6b05ea3d24aa56d29a0eb892d …
> fix: broken ledger chains connect

- src/components/MultiHopTrade/components/FeeModal/FeeBreakdown.tsx
Fixes issue where we display fee breakdown data in the fee explainer for quotes that actually have no fee (cowswap quotes > $1000)
Changes include:
- Display fox power in fee explainer in all cases
- Hide "FOX Power Discount" row in fee explainer if the quote fee is 0 and the expected fee is not 0 (i.e the theoretical fee is some value but cowswap swapper forced it to 0)
closes #6180
Low risk, does not affect actual trades.
Check the fee breakdown when clicking the fee in the trade input is correct in various situations:
- cowswap <$1000
- cowswap >$1000
- non-cowswap <$1000
- non-cowswap >$1000
The above with and without fox holdings.
Prod
This PR
> fix: dont display incorrect fee values for cowswap quotes in the fee explainer

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
1inch swapper has recently been toggled off, but loading state is still appearing for it. This PR addresses the issue by improving the logic in the redux selectors to exclude swappers that have been disabled.
NA
Low risk of broken trades or swappers not being enabled when they should be.
Get a quote and ensure that 1inch swapper is not appearing in the quote list. Also check that other swappers do appear, and that trades and state is not somehow broken.
Release:
This PR:
> fix: dont render loading placeholders for disabled swappers

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/LpType.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
- src/react-queries/index.ts
- src/state/apis/swapper/swapperApi.ts
This PR brings in improvements in JIT halted state fetching for savers
- uses the new `isTradingActive` react-query in the PR underneath this one in the stack to ensure fresh halted data at
- overview
- confirm *component*
- confirm *signing* (i.e with a refetch)
Most importantly, this fixes some found "issue" (apparently a feature, though the types didn't reflect this) found within `@lukemorales/query-key-factory`: it only returns `queryFn` and `queryKey` - all other defaults defined in the queries will be ommitted.
This effectively meant we were ditching all the options of `isTradingActive`, such as `gcTime`, which is the guts of `isTradingActive` always getting fresh data. In other words, we thought we were getting fresh data everytime with this hook, but were really using the default …
> feat: improve thorchain savers JIT halted checks

- scripts/generateTradableThorAssetMap/utils.ts
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
This PR supersedes the original approach used in https://github.com/shapeshift/web/pull/6211 and instead copies the 2 duplicate constants and helpers to reduce the diff and keep THORChain specific logic out of the `@shapeshiftoss/types` package.
N/A
Small - at runtime this only changes imports.
- Running `yarn generate:thor-asset-map` should work again
- Perform a general regression test on the app, specifically thorchain swapping.
☝️
☝️
N/A
> fix: generate:thor-asset-map, min diff

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
closes #6074
Moderate impact since it affects trades, though an extremely simple cleanup task and probability of being broken is low.
Check trades from EVM, Cosmos SDK and UTXO assets are working
> chore: remove eip-1559 related flags from cosmos-sdk trade quote args

- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
See this review comment: https://github.com/shapeshift/web/pull/6168#issuecomment-1947345126
N/A
Very low
- Confirm `inbound_addresses` is called at "Confirm and Deposit" step (only once, not refetched on click since there this isn't the proper signing step per se)
- For additional paranoia testing, do the usual monkey patching
N/A, untestable by ops
> feat: lp halted check at "Confirm and Deposit" step

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/pages/Lending/hooks/useGetEstimatedFeesQuery.ts
- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
- src/react-queries/hooks/useIsTradingActive.ts
See https://github.com/shapeshift/web/pull/6168#issuecomment-1947345126:
> ❓ Non blocking, but
>
>  - Polling halted state continues after tx has been submitted
> - Gas rate polling continues after tx has been submitted
N/A
Low
- Ensure estimate and inbound_addresses calls are still going through at LP deposit Tx sign step
- Ensure polling stop once we have a Txid
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/44a746c6-8b3c-41ab-bcd1-b545acae430e
> feat: thorchain LP useIsTradingActive / useGetEstimatedFeesQuery stop polling on Txid

- src/hooks/useIsSmartContractAddress/useIsSmartContractAddress.ts
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
This PR introduces smart contract checks for THORChain LP deposits.
closes https://github.com/shapeshift/web/issues/6107
Low from a theoretical perspective, high as we should ensure that 
1. this works (obviously) and doesn't let smart contract wallets proceed
2. this doesn't block non-smart contract wallets from continuing
3. there is no flow other than LP deposits affected by this
THORChain smart contracts
- Smart contract wallets are blocked from depositing into LP
- Other wallets are happy with LP depositing
- 👆
- 👆
- SC wallet
> feat: thorchain lp disable smart contract deposits

- src/state/apis/swapper/swapperApi.ts
Use the _actual_ swapper name when checking if trading is active.
N/A - fixes regression caused by https://github.com/shapeshift/web/pull/6168.
Small
In theory all swappers are affected by this change - we need to ensure we can still trade with them without misleading halted flags.
- Halt flags should only apply to THORChain
- The current issue in release where 0x quotes on Arbitrum are showing as halted should be resolved
☝️
☝️
N/A
> fix: do not hardcode thorchain on trading active check

- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
Shaves off one request off daemon.* calls, mostly here for posteriority - since the `resolvers/univ2` is evaluated on splash screen, this means there is effectively a network request to the daemon while still in splash screen, which could be avoided.
Stretching the idea some more, as we get more and more lazy with loading, we should ensure there are no requests being made to endpoints at module-scope level.
relates to #6193
Low to none
- Ensure `getBlockNumber` initiator doesn't fire daemon.* requests at splash-screen level, but only after that
None
> feat: don't initialize ethersProvider in module scope

- src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
- src/components/Modals/Send/utils.ts
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useApprovalTx.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
- src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
- src/lib/investor/investor-foxy/api/api.ts
- src/lib/utils/evm.ts
- src/react-queries/index.ts
Disables EIP-1559 for keep key across the app to resolve issues interacting with EVM chains.
closes #6246
Moderate risk of broken EVM functionality for keep key wallets interacting with EVM chains across the app.
Ensure EVM interactions with keep key across the app are working as intended.
> fix: temporarily disable eip-1559 for keepkey

- .env.app
- .env.dev
- .env.develop
- .env.e2e
- .env.private
- react-app-rewired/headers/csps/chains/cosmos.ts
- src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
- src/components/Modals/Send/utils.ts
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useApprovalTx.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
- src/config.ts
- src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/hooks/useIsSmartContractAddress/useIsSmartContractAddress.ts
- src/lib/investor/investor-foxy/api/api.ts
- src/lib/utils/evm.ts
- src/pages/Lending/hooks/useGetEstimatedFeesQuery.ts
- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
- src/react-queries/hooks/useIsTradingActive.ts
- src/react-queries/index.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
fix: temporarily disable eip-1559 for keepkey (#6248)
feat: don't initialize ethersProvider in module scope (#6222)
chore: point to nownodes for supported chains (#6050)
feat: thorchain lp disable smart contract deposits (#6177)
feat: thorchain lp trade button routing (#6234)
feat: thorchain LP useIsTradingActive / useGetEstimatedFeesQuery stop polling on Txid (#6233)
feat: lp halted check at "Confirm and Deposit" step (#6232)
> chore: release v1.542.0

- src/components/MultiHopTrade/components/TradeInput/getQuoteErrorTranslation.ts
- src/state/apis/swapper/helpers/validateTradeQuote.ts
- src/state/apis/swapper/swapperApi.ts
- src/state/apis/swapper/types.ts
Prevents a quote being marked as valid (and therefore executable) when the sell amount isn't exactly the same as the sell amount the user inputted.
closes #5723 specifically point `create sanity check that we never ask a user to sign a transaction that is larger than what a user input`
Low risk as this prevents invalid trades. This check failing or being incorrectly implemented could have 2 possible outcomes
- Prevent valid trades going through. Simple to check and validate by testing trades
- Allow invalid quotes with bad sell amounts though. Very unlikely these quotes ever appear at all after resolving the other issues detailed in #5723. Testable with a monkey patch by eng team
> What protocols, transaction types or contract interactions might be …
> chore: add validation for quotes with incorrect sell amount

- __mocks__/ethers.ts
- packages/caip/src/adapters/yearn/utils.ts
- packages/unchained-client/src/evm/bnbsmartchain/parser/bep20.ts
- packages/unchained-client/src/evm/ethereum/parser/uniV2.ts
- packages/unchained-client/src/evm/ethereum/parser/weth.ts
- packages/unchained-client/src/evm/parser/erc20.ts
- packages/unchained-client/src/evm/parser/index.ts
- packages/unchained-client/src/evm/parser/nft.ts
- scripts/generateAssetData/ethereum/yearnVaults.ts
- src/lib/ethersProviderSingleton.ts
- src/lib/investor/investor-foxy/api/api.ts
- src/lib/investor/investor-foxy/foxycli.ts
- src/lib/market-service/foxy/foxy.test.ts
- src/lib/market-service/foxy/foxy.ts
- src/lib/market-service/market-service-manager.ts
- src/lib/market-service/market-service.test.ts
- src/plugins/walletConnectToDapps/hooks/useGetAbi.tsx
- src/state/apis/foxy/foxyApiSingleton.ts
- src/state/slices/marketDataSlice/marketServiceManagerSingleton.ts
... and inject it to `MarketServiceManager` and `investor-foxy`, to avoid multiple instantiations that trigger calls to `eth_chainId`.
No batching, but less requests in the end, which means things are effectively faster *and* more performant.  
- relates to https://github.com/shapeshift/web/issues/6193
- Compare network tab against develop
- Ensure we don't spam `eth_chainId` payloads aymore
- 113 daemon.ethereum XHRs
- Chatty `eth_chainId`
And many, many more
- 95 daemon.ethereum XHRs
- Not-so-chatty `eth_chainId`
Now only called once by `BaseTransactionParser`
> feat: switch ethers JSON-RPC provider to StaticJsonRpcProvider

- src/hooks/useIsSmartContractAddress/useIsSmartContractAddress.ts
Fixes a production issue that prevents users from trading UTXOs.
Regression in https://github.com/shapeshift/web/pull/6177.
Summary of the issue:
- An `isAddress(address)` check was added to the `isSmartContractAddress` query enabled logic
- For UTXOs, this will return `false`, and so the `isSmartContractAddress` query will not fire
- This means the `data` returned from the `useIsSmartContractAddress` hook is `undefined`
- Because we fail _closed_ (intentional, for safety) in downstream logic consuming smart contract checks (i.e. if we can't confirm it isn't a smart contract, we assume it is), we thus fail on `undefined` (UTXO "addresses")
Closes https://github.com/shapeshift/web/issues/6258
Medium - getting the wrong prevents users from trading, though …
> fix: thorchain swapper

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalNeeded.tsx
Fixes an issue in release which prevents trading from native assets or UTXOs.
Regression from https://github.com/shapeshift/web/pull/6217
Problem summary:
- `useIsApprovalNeeded` was returning `undefined` if `selectAllowanceCryptoBaseUnit` evaluated to `undefined` (which happens in the case of native fee assets or UTXOs
- This caused `isApprovalNeeded` to be `undefined` for these assets, causing the `isLoading` condition of `isApprovalNeeded === undefined` to be met
N/A - current release blocker.
See https://github.com/shapeshift/web/pull/6257#issuecomment-1953403818.
Medium. A small change, but does affect the approval checks of transactions.
Any transaction that …
> fix: trades from native assets & utxos

- src/state/apis/swapper/helpers/validateTradeQuote.ts
Fixes issue where quotes with a sell amount LOWER than user input are marked as invalid (namely cowswap quotes). We need to allow this case, and only mark quotes selling an amount HIGHER than the user inputted value as invalid.
NA
Low risk of broken trade qutoes.
Check quotes are working generally
Check CowSwap quotes are working (e.g FOX -> ETH $30)
Before fix
After fix
> fix: allow quote sell amounts to be lower than user input sell amount

- src/lib/utils/thorchain/lp.ts
- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/Position/Position.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidity.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
- src/react-queries/hooks/useQuoteEstimatedFeesQuery.ts
- Adds gas fees for remove liquidity estimates
- Uses the `AssetInput` component to display current LP asset balance
What this does not do:
- Handle clicking "Remove liquidity", and any subsequent flows
Contributes to https://github.com/shapeshift/web/issues/5960
Small/medium - mainly UI related work, though has some account-related logic (primarily the derivation of account from quote params + lp pool data).
Related to THORChain LP withdrawal transactions, though does not execute them yet.
For an existing position, enter an amount to remove and ensure that:
a) the gas fee value calculates correctly
b) the calculated fee is similar (the same as?) to that calculated in "Add Liquidity".
☝️
☝️
> chore: add 'remove liquidity' fees

- src/assets/translations/en/main.json
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidity.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
Wires up the confirm page UI for remove liquidity.
Contributes to https://github.com/shapeshift/web/issues/5960
Small - UI only.
THORChain LP withdrawals.
From an existing LP position, click the "Remove Liquidity" tab, get a quote, then click "Remove Liquidity".
You should be taken to a new route with the removal quote details.
☝️
☝️
> chore: wire remove liquidity confirm page

- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
Update the LP confirmed quote types so we can discriminate on the keys.
Actions feedback given here: https://github.com/shapeshift/web/pull/6266#discussion_r1496769959
Small - more of a refactor.
THORChain LP deposit and withdrawals quotes.
We should still get quotes for LP deposits and withdrawals (as before), and we shouldn't throw attempting to access a field that doesn't exist on a confirmed quote.
☝️
☝️
N/A
> chore: use quote-specific terminology in types

- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/components/MultiHopTrade/components/TradeAssetInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/CountdownSpinner.tsx
- src/state/slices/assetsSlice/selectors.ts
- src/state/slices/portfolioSlice/selectors.ts
Reduces the amount of repeat work done in the trade input, namely within the related asset selectors and the rendering around the trade input components in general.
Two insights when debugging performance issue on trade input:
1. selectors using a parameter e.g `const xyz = useAppSelector(state => myselector(state, myParam))` will recompute on every access even if the selector was implemented with `createDeepEqualOutputSelector`. Instead, `createCachedSelector` is required.
2. `{ propA, propB, ...rest } = props` pattern for props causes re-render on every parent component render. We should avoid this and instead pass the rest as field in the props. Example is instead of `type MyProps = { propA: number } & BoxProps`, we should do `type MyProps = { propA: number; boxProps: BoxProps }`
NA
> …
> perf: address rendering performance issues on trade input page

- src/assets/translations/en/main.json
- src/lib/utils/thorchain/lp/types.ts
- src/lib/utils/thorchain/lp/utils.ts
- src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidity.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
- Improves loading state when adding and removing liquidity
- Wires up Remove Liquidity status, which shows after confirming a withdrawal (though do not press "Sign Transaction" on the withdrawal flow - it just uses existing logic for now and will currently do a deposit instead of withdraw)
- Adds input amount validation to the withdrawal "quote" step (moving the slider all the way to 0 will disable the confirm button)
- Fixes a bug where the Confirm screen was showing an incorrect withdrawal amount (exactly half of what was expected)
Contributes to https://github.com/shapeshift/web/issues/5960
Low risk, mainly UI changes.
THORChain LP deposit and withdraw.
Give …
> chore: lp improvements

- src/components/Modals/QrCode/Form.tsx
- src/components/Modals/Send/Form.tsx
- src/components/Modals/Send/SendCommon.tsx
- src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
- src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
- src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
- src/components/Modals/Send/utils.ts
- src/components/Modals/Send/views/Confirm.tsx
- src/components/Modals/Send/views/Details.tsx
- src/components/Sweep.tsx
- src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/utils/thorchain/balance.ts
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
- src/react-queries/hooks/useQuoteEstimatedFeesQuery.ts
Mitigate confusion by renaming `cryptoAmount` to `amountCryptoPrecision`, aligning with our internal practice of specifying the units/precision in naming.
N/A
Small, rename only.
None.
A general regression test of sends, fee and gas estimates should show no changes.
☝️
☝️
N/A
> chore: rename cryptoAmount to amountCryptoPrecision

- src/components/Layout/Header/GlobalSearch/GlobalSearchButton.tsx
- src/components/Layout/Header/GlobalSearch/GlobalSearchModal.tsx
- src/components/Layout/Header/GlobalSearch/SearchResults.tsx
Prevents the global search modal from pulling large amounts of state from redux unless the user is actually searching. This improves boot time, especially on larger wallets.
Saves ~0.5s of boot time on large wallets locally. This time saving is much less on desktop prod builds, but is comparable on mobile devices.
relates to #6252
Low risk, as this is merely moving existing code into separate components without changes to business logic
Ensure global search is working and loading as intended
> perf: dont process global search selectors when not searching

- src/components/AssetHeader/AssetHeader.tsx
- src/components/MultiHopTrade/components/QuoteList/QuoteList.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/CollapsibleQuoteList.tsx
- src/components/MultiHopTrade/components/TradeInput/components/HorizontalCollapse.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ManualAddressEntry.tsx
- src/components/MultiHopTrade/components/TradeInput/components/WithLazyMount.tsx
- src/components/MultiHopTrade/components/TradeInput/components/WithLazyRender.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/components/TransactionHistory/AssetTransactionHistory.tsx
- src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts
Adds a higher order component in specific locations in the trade input to avoid mounting heavy components until they are required. The aim here is to speed up boot time and offload mount cost to when a component is needed.
Includes a cleanup of `useWalletSupportsChain` to accept individual props rather than an object which was causing rerendering to occur.
closes #6307
Moderate risk of something breaking in the trade input interface, though this doesn't modify business logic.
Ensure the trade input and quotes are working as intended.
> perf: conditionally mount trade input components

- src/components/AccountDropdown/AccountDropdown.tsx
- src/components/AssetSelection/AssetSelection.tsx
- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/QuoteList/QuoteList.tsx
- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/components/MultiHopTrade/components/TradeInput/components/WithLazyMount.tsx
General performance improvements to rendering for the trade input components:
* Add `isLazy` prop to menus to prevent them being rendered while closed
* Memoize `...rest` prop creation where applicable
* Wrap `memo()` around components where applicable
NA
Low risk of broken trade input. This PR doesn't modify business logic at all, so functionality should be unchanged.
Ensure trade input and quotes are working as intended. This includes related asset dropdown, slippage popover, quotes, etc.
Recommend reviewing the code with whitespace disabled
> perf: general rendering improvements for trade input

- src/components/Modals/FiatRamps/views/FiatForm.tsx
Ensuring the cached AccountId's address is used, so users don't have to open the app, similar to swapper
closes https://github.com/shapeshift/web/issues/6318
Low to none, ensure fiat ramp receive address is still happy regardless of wallet being connected
- Connect Ledger to chain/s of your choice
- Ensure fiat ramp displays a receive address and doesn't error with an infinite loading state
- ☝🏽 
- ☝🏽
> fix: don't derive address on Ledger in Fiat Ramp

- src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Show the pool asset amount for symmetrical withdrawals.
We currently only show the RUNE amount.
This view might need some beard oil down the line.
N/A
Small
None.
Get to the signing view of a symmetrical withdrawal and confirm that both the expected RUNE and pool asset amounts (+ symbol and icons) are shown correctly.
☝️
☝️
Develop
This branch
> chore: show both sym withdraw amounts

- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Clean things up a bit and explicitly define value inline for clarity. Also catch a bug with rune withdraw using `amountCryptoPrecision` instead of dust
> chore: thor suggestions

- src/components/MultiHopTrade/components/TradeInput/components/RecipientAddress.tsx
Fixes application crash when attempting to enter a custom receive address.
Closes https://github.com/shapeshift/web/issues/6350
Medium. Relates to receive address, but changes no underlying logic.
All trades.
- Using a custom receive address should now work
- Using the default receive address should still work
☝️
☝️
N/A
> fix: handle undefined SendFormFields.Input

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
A user will pay for the outbound fee to withdraw from an LP position (excluding asym rune). Display this value as the protocol fee.
N/A
Low
Thorchain LP withdrawal (Symmetric and Asym Asset)
- ensure the protocol fee is being displayed on withdraw for symmetric and asym asset withdraw
- ensure the protocol fee is $0 for asym rune withdraw
:point_up: 
:point_up: 
Asym Rune (no protocol fee)
Asym Asset (protocol fee)
> chore: display outbound fee lp withdraw

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
Always allow account selection, instead of only when we have a quote from a swapper that supports cross-account trades.
Ensures we do not get cross-account quotes from swappers that do not support cross-account trades as `getEnabledSwappers` will only return swappers that can handle the requested quote.
Closes https://github.com/shapeshift/web/issues/6262
Small risk. Swappers that do not support cross-account trading are not enabled, and won't give a quote when a cross-account receive account is selected.
Swapping on all swappers.
We should be able to _always_ select a receive account regardless of whether or not we:
a) have a valid quote
a) have selected a …
> chore: always allow account selection

- src/lib/fees/utils.test.ts
- src/lib/fees/utils.ts
These changes make a few improvements:
- Dynamic average block time seconds based on 1k block range
- Explicit unix timestamp math only (no dayjs and possible timezone edge cases)
- Use latest block timestamp as the starting point instead of current timestamp (this will ensure we can at least get an out of date fox discount block even if the node is behind by a bit worst case instead of fail)
- Use the block 1 block before the target timestamp instead of before OR after the target timestamp
- Add unit tests
N/A
Low/Med - this does change behavior slightly (block before timestamp only) and updates average block time and timestamp math, but unit tests provide confidence in change
> What protocols, transaction types or contract interactions might be …
> feat: fox discount block improvements

- src/plugins/walletConnectToDapps/typeGuards.ts
- src/plugins/walletConnectToDapps/types.ts
- src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts
Does what is says on the box:
- handles payloads with `maxFeePerGas` and `maxPriorityPerGas` but none of the other, as well as explicitly checking against undefined (some fields may be present but null, which is still valid as far as payloads go towards directing the gas scheme to be used) - https://github.com/shapeshift/web/pull/6364/commits/5b559ef049e7204ca672dcc3fd73a95d2ebe2822
- non-null assertion operator doesn't work on empty strings - meaning this guy would never work in case both `customTransactionData.gasLimit` and `sendTransaction.gasLimit` are empty strings:
https://github.com/shapeshift/web/blob/aff5d29808ff1bf29a9967c32d97f048319ff0d5/src/plugins/walletConnectToDapps/utils/EIP155RequestHandlerUtil.ts#L100
closes https://github.com/shapeshift/web/issues/6034
> High Risk PRs …
> fix: eip155 wc isTransactionParams checks / gasLimit short-circuit

- src/pages/ThorChainLP/Position/Position.tsx
Spotted in https://github.com/shapeshift/web/pull/6373#pullrequestreview-1923174916:
> Withdraw succesful ✅ though noted that after a 100% withdraw, the pool page is gone and we're left with a big dark screen of void 😢 because we refetch user data, which is now none. Will tackle in a follow-up to handle 0'd out values on pool position page
N/A
None, only handles no position as valid and adds skeletons while at it
- Exit fully from a position
- After the Tx completes, ensure the position goes to a 0-value position instead of becoming empty
- ^
- ^
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a …
> fix: thorchain LP handle 0-value position page

- src/components/MultiHopTrade/components/TradeAmountInput.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Since multi-account is disabled, we should not auto-select highest balances, but only assume account 0 for now to avoid deposits from account 1 for the time being.
Since the underlying `<TradeAmountInput />` component always passed `autoSelectHighestBalance` down to `<AccountDropdown />`, this was impossible to achieve - fixed by making optional, but defaulted to true to ensure we keep the previous behavior.
N/A
Low since we keep the previous behaviour by defaulting to true when destructuring- though as a paranoia test, check trade amount account selection is still happy
- THORCHain LP Add Liquidity input doesn't autoselect accounts 0+
- ^ 
- ^
> feat: thorchain LP deposit don't autoselect highest balance

- src/lib/fees/model.test.ts
- src/lib/fees/model.ts
- src/lib/fees/parameters/swapper.ts
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Updates fee model following DFC decision:
- Swapper fee model is now bumped from 29 to 49 max bps
- We no longer default to free trades if failing to get voting power from snapshot, but rather default to the max bps as a static value
- Removes `votingPower` checks in THORChain LP to properly handle the case of undefined vp, which is now valid
N/A
Low, though ensure min amount before fees is still honoured, and bps are still happy when snapshot is happy
- When snapshot is happy, the current fee model is still used. 
- When snapshot is sad, we default to the max 49 bps (for swapper) or 50 (for LP).
- ☝🏽 
- ☝🏽 
- Swapper
- THORCHain LP
- Swapper
- THORCHain LP
- …
> feat: update fee model

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquityStatus.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
Add back button to the `ReusableLpStatus` component (the confirm step of an LP deposit/withdraw).
Contributes to unblocking https://github.com/shapeshift/web/pull/6344.
Low
None
Ensure the back button renders, and works, on both the deposit and withdraw confirmation.
☝️
☝️
See description for the expected state.
> chore: add back button to ReusableLpStatus

- src/components/ChainMenu.tsx
- src/components/Layout/Header/NavBar/ChainMenu.tsx
- src/hooks/useEvm/useEvm.ts
In preparation for #6289, this PR breaks out the UI components of the chain menu used for metamask chain selection so we can reuse it for the asset selection modal.
Relates to #6289
Moderate risk as this could potentially break the ability to switch chain on metamask.
This should have no functional change from production.
* Ensure switching chain on metamask is working
* Ensure Native wallet doesnt show this menu
* Ensure metamask cannot connect to invalid chains (e.g UTXO without snap installed)
This includes a change to the menu to use actual caip chain IDs rather than chain references, which is the mostly likely part of this to break.
> chore: break out chain menu component from metamask chain select

- src/components/FeeExplainer/FeeExplainer.tsx
- src/components/FeeExplainer/FeeSliders.tsx
- src/components/FeeModal/FeeBreakdown.tsx
- src/components/FeeModal/FeeModal.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FeeStep.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ReceiveSummary.tsx
- src/lib/utils/thorchain/lp/types.ts
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Does what it says on the box - uses USD amounts for FOD discounts everywhere, or almost: note the receive summary fee is still denoted in user currency to be consistent with other amounts.
This is threefolds:
1. ensures USD amounts everywhere means proper calculation of the FOX discounts, without user currency used as USD for the calculation and vice-versa
2. ensures we never display USD amounts as user-currency
3. ensures visual consistency as well as consistency with our communication of the FOX discount in USD
closes https://github.com/shapeshift/web/issues/6390
Low - ensure amounts still look sane both in USD and user currency (should now be the exact same, …
> feat: fox discounts use USD everywhere

- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
Partial thorchain lp withdrawals were not being picked up correctly with no dust provided. This adds 1 rune dust threshold to use for thorchain withdrawal txs to ensure they are picked up by thorchain and complete successfully.
https://discord.com/channels/554694662431178782/1204066015261098044/1216839201807667331
Low
- Ensure partial lp withdrawals succeed
:point_up: 
:point_up:
> fix: add thorchain dust threshold to support partial withdrawals

- src/components/MultiHopTrade/components/TradeAmountInput.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
Does what it says on the box - avoids confusion for users who set a custom receive address, where the account selection may be confusing and not reflect the actual receive address.
N/A
Low - this is only visual - as long as the account dropdown still shows up without a manual receive address, we're good
- When user set a manual receive address, receive account selection is hidden
- Receive account selection is still shown without a manual receive address
- ^
- ^
> feat: hide receive account selection when manual address is set

- src/lib/swapper/swappers/CowSwapper/endpoints.ts
Reported by CoW directly:
> Are you not subtracting the slippage tolerance from the quote in your code? If not, this leads to effectively 0 slippage being applied which can lead to orders taking a very long time to settle or not settling at all.
closes https://github.com/shapeshift/web/issues/6365
Low - ensure slippage is deducted in the buy amount in the quote to-be-signed
- The minimum buy amount in CoW is correctly slippage-deducted (both with default 50bip and custom slippage tolerance)
- CoW orders fill much faster 🎉 
- ^
- ^
Note, quote with slightly different rate since I tested this after, but just a sanity check while at it to ensure custom slippage UI …
> feat: cowswap honor slippage in signed order

- src/components/MultiHopTrade/components/TradeInput/components/ReceiveSummary.tsx
Uses the correct selector to ensure we show the receive summary fee in the user's selected currency.
Fixes https://github.com/shapeshift/web/pull/6424 release blocker noted here https://github.com/shapeshift/web/pull/6424#issuecomment-1992928368.
Small - UI only.
UI only, but related to trading.
The "ShapeShift fee" should be in the user's selected currency.
☝️
☝️
> fix: trade quote fee currency

- src/components/MultiHopTrade/components/TradeInput/components/ReceiveSummary.tsx
Fixes the `affiliateFeeAmountUsd` input to `FeeModal`, which should be a USD amount.
Fixes current release blocker: https://discord.com/channels/554694662431178782/1217256377030938754/1217310573667155979
Small.
None.
The Fee summary modal total should make sense when a user currency is selected.
☝️
☝️
See testing notes.
> fix: fee modal input should be usd

- src/components/AssetSearch/AssetRow.tsx
Show balances on the `assets` route when connected to the demo wallet.
Closes https://github.com/shapeshift/web/issues/6240
Small
None.
- The demo wallet should show balances on the `assets` route
- Other wallets should be unaffected by this change
☝️
☝️
> fix: demo wallet balances

- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
Fixes a regression that caused the LP removal percentage slider's debounce to break.
Closes https://github.com/shapeshift/web/issues/6422
Small
None.
Network requests should only fire once the slider is released, but the UI should still be buttery smooth whilst sliding.
☝️
☝️
Network requests are found in the network tab.
N/A
> fix: slider debounce

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- Only reset the input amount state on asset change (no longer reset on lp type selection change)
- Reset state to empty value instead of `0` value to represent initial state
N/A
Low
- Ensure input values are not reset when changing between lp types
- Ensure input values are reset to empty (not `0`) on asset change
:point_up:
:point_up:
> fix: reset input on asset change only and use empty state instead of 0

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- Disable gas estimation if approval is required. The estimation will always revert if there is no allowance, so prevent this to allow user to perform the approval successfully and in turn, perform the rest of their deposit.
- Fix disable state regression related to undefined fee data (MM will never get rune fee data which was resulting in perma disable state)
closes https://github.com/shapeshift/web/issues/6441
Low/Med - affects enable/disable states so we want to make sure we got this right and don't get stuck in any flows
Thorchain LP deposits
- Ensure thorchain lp deposit approvals work for tokens and subsequently the rest of the deposit flow works as expected …
> fix: disable gas estimation if approval is required

- src/pages/ThorChainLP/queries/queries.ts
Does what it says on the box - we *do* refetch thorchainLp queries. However, queries themselves fetch others, using `queryClient.fetchQuery` which leverages the default `staleTime` (0, which is fine) and `gcTime` (5mn garbage collect time, which is not fine as results will be returned from the cache first i.e stale-then-fresh, however since this is an escape-hatched single function call, this is really just stale).
Fixed by applying a `gcTime` of 0 to those calls.
N/A
None
- Do an LP deposit
- Ensure your balance gets updated after completion 
~~Note: Given the current borked nature of position page for adding liquidity, and the optimistic nature of withdraws, …
> fix: thorchain lp actually refetch underlying queries

- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
Show the "Pool Halted" error when attempting to withdraw from a halted pool.
We currently just disable the button with no explanation as to why, which is not ideal.
No ticket.
Small.
LP withdraw UI.
Attempt to withdraw from a halted pool.
The button should be both disabled, in the error state, and show "Pool Halted".
☝️
☝️
Develop:
This branch:
> fix: show "Pool Halted" on withdraw

- src/lib/mixpanel/types.ts
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityConfirm.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityConfirm.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Adds MixPanel tracking to THORChain LP transactions:
```
LP Deposit Confirm,
LP Deposit Initiated,
LP Deposit Success,
LP Deposit Failed,
LP Withdraw Confirm,
LP Withdraw Initiated,
LP Withdraw Success,
LP Withdraw Failed,
```
Contributes to https://github.com/shapeshift/web/pull/6344
Small
In the domain of LPs, though nothing should be directly affected.
Ensure events show up in MixPanel for both LP deposits and withdrawals.
☝️
☝️
See testing notes.
> feat: add mixpanel tracking to LP

- src/components/Layout/Header/Header.tsx
- src/components/Layout/Page.tsx
- src/hooks/useInfiniteScroll/useInfiniteScroll.tsx
- src/pages/Dashboard/Dashboard.tsx
When you are on a larger screen, the infinite loader would not trigger, because it never went beyond the viewport. 
So to fix this, we've increased the amount of items we show per page on the infinite scroll from 10 to 20. This should give us lots of room for most normal sized monitors.
closes #6463 
Minimal risk
With a wallet connected, and on a larger size screen as you scroll the transaction history and the assets table on the dashboard should load in 20 rows at a time until it can't load anymore.
> fix: infinite scroll for larger screens

- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
Ensures we properly set minimums for token withdraws.
The outbound fee coming from the `inbound_addresses` endpoint is the outbound fee for the *chain*, not the asset - in other words, it represents the native asset gas fee for the outbound fee.
N/A
None, this was obviously wrong
See screenshots - minimums should be properly detected
- Inspect the `inbound_addresses` call in the network requests tab
- Note the inbound address for the chain and convert the precision from THOR precision, by shifting the decimal point 8 digits, e.g 1649190 -> 0.01649190
- You now have the outbound fee for the pool asset chain, i.e 0.01649190 AVAX ~= 1 USD here
- Try to do either an …
> fix: thorchain LP withdraw outbound fee is denominated in outbound fee asset

- package.json
- packages/chain-adapters/package.json
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/types.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- src/state/slices/txHistorySlice/txHistorySlice.ts
- yarn.lock
Improves boot performance of the application by limiting network concurrency of tx history to 2.
Context here
https://www.notion.so/shapeshift/Transaction-History-d656eb2ea4e244699fecb4c68eebfa45
Relates to #5676
Low risk, this only changes orchestration of tx history requests without logical changes.
* Check tx history loads on a fresh connect (it will be slightly slower)
TX history loaded after cache clear
> perf: use a request queue and a concurrency of 2 to fetch tx history

- src/context/WalletProvider/KeepKey/components/Passphrase.tsx
As a follow-up to https://github.com/shapeshift/web/pull/6482, this PR makes KeepKey passphrases _actually_ actually work.
Currently we'll correctly reset and show the correct accounts/balances when initially enabling and disabling the passphrase functionality on a KeepKey, but subsequent connections will always initially show the empty passphrase state after a passphrase is entered.
Closes https://github.com/shapeshift/web/pull/6482
Low
Connectivity and accounts relating to KeepKey's with passphrase enabled.
Connect a KeepKey with a passphrase enabled, and enter a passphrase. Ensure that we load and show balances and accounts corresponding to the passphrase, and …
> fix: clear previous wallet data on kk passphrase entry

- src/components/FeeModal/FeeBreakdown.tsx
- src/components/FeeModal/FeeModal.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FeeStep.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ReceiveSummary.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Does what it says on the box - consumes the `feeUsd` property holistically and removes dupes, which were resulting in a discrepancy between the total trade fee in the fee modal.
closes https://github.com/shapeshift/web/issues/6429
None
- Total trade fee is the same in both tabs of the fee modal
- ☝🏽 
- ☝🏽 
Develop (right) vs this diff (left)
> fix: consistent total FOX discounts model fee

- src/lib/swapper/swappers/utils/constants.ts
We currently have our "unlimited" approvals hardcoded to `100000000000000000000000000`, which is actually not the maximum possible value that can be spent, and so, is not unlimited.
Unlimited approvals for ERC20 tokens should be the maximum value that can be stored as a `uint256`.
Closes https://github.com/shapeshift/web/issues/6497
Small.
All ERC20 token approvals, and their subsequent trades.
Perform an unlimited approval on an ERC20 token and confirm, using a block scan UI for simplicity, that the approval was indeed unlimited.
E.g. https://snowtrace.io/tokenapprovalchecker?search=0x32DBc9Cf9E8FbCebE1e0a2ecF05Ed86Ca3096Cb6 shows that approvals done before this …
> fix: unlimited erc20 appovals

- src/components/FeeModal/FeeBreakdown.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FeeStep.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ReceiveSummary.tsx
- src/components/MultiHopTrade/helpers.ts
- src/lib/fees/model.ts
- src/state/slices/common-selectors.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
Fix the discrepancy between the ShapeShift fee shown by the `ReceiveSummary` component and the fee modal.
They are using different calculations to derive the values. This PR unifies the calculation logic by putting the `calculateFees` logic into a selector (`selectCalculatedFees`), and then consuming that in all of the `FeeBreakdown` modal logic, the `FeeStep`, and the `ReceiveSummary` components.
Fixes release-blocking regression caused by https://github.com/shapeshift/web/pull/6493 in https://github.com/shapeshift/web/pull/6499.
Medium. Should just be UI changes (so small), but if I broke something that causes us to stop charging fees that's bad (so medium).
Trades and LP deposits.
Ensure that:
- …
> fix: unify affiliate fee calculations

- src/lib/swapper/swappers/ZrxSwapper/endpoints.ts
Current estimations from the node are not providing enough gas padding for `total gas used` even though it is enough to cover `actual gas used`. This change takes the higher gas limit value provided by either the node or api, while still estimating our own gas in every instance to catch any evm state errors (not enough allowance, etc) and still leverage eip1559 fees while ensuring tx doesn't revert on chain.
https://github.com/shapeshift/web/issues/6247
Low - can't make things worse by taking the more aggressive gas limit. there may still be issues with actual estimation that we can look into next and see if we want to short circuit our node estimation entirely.
- …
> fix: use higher gas limit node vs zrx api

- src/components/AssetSearch/AssetSearch.tsx
- src/components/Modals/FiatRamps/views/FiatForm.tsx
Fixes issue where users can select assets which are unsupported by the wallet on the fiat page.
NA
Low risk.
Check that only assets supported by the wallet are able to be selected on the fiat page (e.g all assets for native, only EVMs for metamask without snap)
> fix: hide unsupported assets in fiat page asset search

- src/hooks/useIsSnapInstalled/useIsSnapInstalled.tsx
Simplifies the logic to react on the `MetamaskMobile` user-agent.
Note, this doesn't mean MM mobile will *always* be happy on Android. This now makes the *detection* accurate (i.e show Pair instead of Open) but `window.ethereum` injection is inherently unreliable on Android MM build. All we care about is MM mobile in-app browser being detected, but at this stage we can't do anything more if `window.ethereum` is rugged on a specific system.
closes https://github.com/shapeshift/web/issues/6334
None - `MetamaskMobile` is the latest user-agent from MM on in-app browser both in iOS and Android
- MM option shows "Pair" both on iOS and Android in-app MM browsers
- ☝🏽 
- …
> feat: make MM in-app mobile detection happy again (again) (again)

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/arbitrum/ArbitrumChainAdapter.test.ts
- packages/chain-adapters/src/evm/arbitrumNova/ArbitrumNovaChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/gnosis/GnosisChainAdapter.test.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.test.ts
- packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.test.ts
- packages/chain-adapters/src/evm/types.ts
... and `buildEstimateGasRequest` too.
Fast follow of https://github.com/shapeshift/web/pull/6505 - we should have never gotten into a bug like https://github.com/shapeshift/web/issues/6312 in the first place. We already have the fee-deducted value, but are still deducting the value from the full balance, which is not only fluff, but also bugs prone if we get the logic wrong WRT fees, which we did for Arbitrum.
While at it, also removes `sendMax` tests which aren't valid anymore for EVM chains - first of all, there is no notion of `sendMax` anymore for EVM chains, but we're also more dumb now in taking an input and building signed calldata out of that - balance checks are now effectively a consumer, not chain-adapters concern.
- relates to the closed #6312
> High Risk PRs Require 2 …
> feat: cleanup fluff sendMax logic in EVM buildSendApiTransaction

- src/components/TransactionHistory/TransactionHistoryList.tsx
- src/hooks/useInfiniteScroll/useInfiniteScroll.tsx
- src/pages/Dashboard/RecentTransactions.tsx
Allow "Load more" button to work on the "My Wallet" route, "Overview" tab.
We were previously passing the first n transactions (`8`), which limited the size of the list that could be "loaded".
Now with incremental load we can let this component work like the "Activity" tab, using the full TX history in the store.
Closes https://github.com/shapeshift/web/issues/6546
Low
None.
On the "My Wallet" route, "Overview" tab, the "Load more" button should now be enabled, and actually load more transactions.
☝️
☝️
> fix: allow load more recent txs on wallet overview

- src/lib/swapper/constants.ts
- src/lib/swapper/swappers/CowSwapper/filterAssetIdsBySellable/filterAssetIdsBySellable.ts
- src/lib/swapper/swappers/CowSwapper/filterBuyAssetsBySellAssetId/filterBuyAssetsBySellAssetId.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/CowSwapper/utils/constants.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.ts
- src/lib/swapper/swappers/LifiSwapper/utils/constants.ts
- src/lib/swapper/swappers/OneInchSwapper/utils/constants.ts
- src/lib/swapper/swappers/ThorchainSwapper/constants.ts
- src/lib/swapper/swappers/ZrxSwapper/utils/constants.ts
- src/lib/swapper/types.ts
Pushes the responsibility of knowing what specific assets are supported to the swppers at query time, and instead uses a combination of a static list of supported chains (for buy and sell side) with the wallet supported chains (for sell side).
For the sake of performance gains in the trade interface, it's now possible to select pairs which are not supported by swappers, although in production this should already already the case. We do still filter based on wallet support though.
closes #6328
Moderate risk of broken trade quotes.
All swappers affected.
Should not introduce a functional change to the app, and should match production.
Check the asset list on the …
> perf: make supported asset list use static list of chains

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
~~Note, I wasn't able to repro https://github.com/shapeshift/web/issues/6581 after many many swaps so this PR is mostly paranoia - we're mostly concerned about approval step still being displayed for swappers when there *was* one, rather than hiding it when there *wasn't*~~
Disregard the above - the root cause was us being overly reactive in `useIsApprovalInitiallyNeededForHop`. As the name suggests, the intent of this hook is to detect *initial* allowance requirements and to never mutate said value after during its lifecycle (i.e until it's unmounted, since hooks aren't singletons, a new mounted instance on a diff swap will be a new reference and start again from `undefined` initial state, as it should).
As we were being overly reactive, we were detecting the newly-approved status of the …
> fix: borked approval swapper step

- src/assets/translations/en/main.json
- src/pages/ThorChainLP/YourPositions.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
closes https://github.com/shapeshift/web/issues/6613
Low - ensure we don't wrongly detect the "disable sym after RUNE" state and disable things
- The Add Liquidity button is in disabled state, with a warning alert when trying to deposit sym when having a RUNE deposit for that pool already
- The warning alert should not be shown in any other case
- ☝🏽 
- ☝🏽 
- Develop vs this diff
- Trying to deposit sym after ROON deposit in develop, confirming this should be disabled
> feat: disable sym deposits after RUNE

- src/lib/swapper/swappers/ZrxSwapper/utils/fetchFromZrx.ts
Collect trade surplus from 0x trades.
Any positive slippage amount will be sent to the buy assets corresponding treasury address (the same address that the affiliate fees are sent).
See https://0x.org/docs/0x-swap-api/guides/monetize-your-app-using-swap#option-2-collect-trade-surplus
N/A
Low - additional arg on 0x quote requests.
0x trades.
- Quotes from 0x should include a `feeRecipientTradeSurplus` key in the request payload.
- 0x quotes and trades should succeed
☝️
☝️
N/A
> feat: collect 0x trade surplus

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/arbitrum/ArbitrumChainAdapter.test.ts
- packages/chain-adapters/src/evm/arbitrumNova/ArbitrumNovaChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/gnosis/GnosisChainAdapter.test.ts
- packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.test.ts
- packages/chain-adapters/src/utils/validateAddress.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.test.ts
- packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.test.ts
- packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.test.ts
- react-app-rewired/headers/csps/addressValidation.ts
- react-app-rewired/headers/csps/shapeshiftProxy.ts
- react-app-rewired/headers/csps/trmLabs.ts
Use proxy address validation endpoint.
N/A
High - getting this wrong could inadvertently prevent all transactions.
All transactions within the app. This sounds scarier than it is though, we are using a single hook to manage address validation, so if it works for one type it should work for all.
Ensure we can still trade, interact with savers and LPs, and send assets.
Check against both EVM and UTXO assets.
☝️
☝️ 
N/A
> feat: use proxy validation endpoint

- src/state/slices/txHistorySlice/selectors.ts
Fixes issue where the "Transaction history degraded" acocunt list will display accounts for a previously connected wallet.
NA
Low risk, the issue is very easily reproducible and simple to identify issues with.
1. Open app on a large wallet. Let it load until there are some failed requests (gnosis will fail since the node is down)
2. Switch wallet. Let it load also.
3. Open the "Transaction history degraded" popover. There should be only accounts for the currently connected wallet listed.
Develop:
This PR:
> fix: dont display degraded balance history accounts for other wallets

- src/components/AccountDropdown/AccountDropdown.tsx
- src/components/DeFi/components/StepRow.tsx
This removes the portal around the account dropdown.
The [original PR](https://github.com/shapeshift/web/pull/3730) that added the portal was because of the collapse component having an overflow hidden.
Because of that i've removed the collapse component in favor of just showing or hiding the step content when its active.
I went through all the occurrences of the account dropdown and removing the portal didn't seem to have any effect on things covering it up.
Now that the portal is removed, you can select the account dropdown from within the new dialog component.
closes #
mild risk, although this won't effect user funds. Removing the portal could cause for it to appear behind something. 
I've removed the collapse component for the StepRow component, …
> fix: remove portal on account dropdown

- src/lib/swapper/swappers/CowSwapper/endpoints.ts
- src/lib/swapper/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- src/lib/swapper/swappers/CowSwapper/types.ts
- src/lib/swapper/swappers/CowSwapper/utils/helpers/helpers.ts
This PR:
- Calculates the amount after fees including affiliate fees
- Ensure the buyAmount in appData is *first* affiliate-fee deducted (if applicable) before being slippage deducted
- Constructs appData with recipient and bps as a percentage (0-100) according to CoW's AppData spec
closes https://github.com/shapeshift/web/issues/6610
Low, though if we get this wrong, solvers won't process the order and it may be stuck forever
- CoW orders are still happy without affiliate fees
- CoW quotes now have affiliate fees if applicable (higher than the minimum no-fees threshold, and not enough FOX held for full fees waiving)
- Fees are deducted at receive amount time …
> feat: cow affiliate fees

- src/state/apis/zapper/validators.ts
- src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
By calling `uniqBy` by `id` `first`, we effectively fix the issue with opportunities having a wrong amount displayed - the issue was that multiple assets *can* have the same `assetId` / `contractAddres` (e.g `ethAssetId`), which means we would pick the first opportunity we find for said asset, which could yield unpredictable results.
- closes https://github.com/shapeshift/web/issues/6608
- Low - ensure opportunities meta/user data still looks sane
- Opportunity metadata still looks sane against develop
- Testing with willy's wallet, https://github.com/shapeshift/web/issues/6608 cannot be repro'd in this diff.
- ☝🏽 
- ☝🏽
> fix: defi aggregated opportunities uniqBy id first

- package.json
- src/components/SimpleChart.tsx
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/Pool/components/PoolChart.tsx
- src/react-queries/queries/midgard.ts
- yarn.lock
Brings charts to THORChain LP using tradingview's `lightweight-charts`.
closes https://github.com/shapeshift/web/issues/6022
Chart data being off mostly
- LP charts data looks sane
- LP charts look good 
- ☝🏽 
- ☝🏽 
https://github.com/shapeshift/web/assets/17035424/0b15b61f-afdc-4519-885c-a6710f8f3337
> feat: thorchain LP charts

- src/pages/ThorChainLP/YourPositions.tsx
- We did an early return when is empty, this can cause users to be stuck on the page
- This now will return in the content keeping the navigation and header
closes #
low risk
If you go to pools, and your positions and you have none. You'll see the empty message under the tabs and header.
> fix: empty my position pools page

- src/components/Modals/QrCode/Form.tsx
When we have the standalone QR code scanner open (i.e. when it is not a part of the send form, or otherwise) we want the back button to close the modal and go back to the Dashboard.
Unblocks current release.
See https://discord.com/channels/554694662431178782/1227752157919580170/1227766068882309151 in the current release thread.
Small
None.
- Ensure that when the QR code scanner is opened from the Dashboard that the back button now closes the modal and we don't end up in an irrecoverable state.
- Ensure that all other instances of the QR code scanner go back to the expected screen, e.g. when in the send asset flow.
☝️
☝️
> fix: qr back button

- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
Handles token repayments using `depositWithExpiry()`.
Note this is an immediate "fix the bug and make this work" fix, and is to be *directly* follow-up on top of this stack with
1. approvals handling - this will not work in and by itself without calling approve() first
2. correct estimations, vs. estimations with the wrong send input previously
3. handling tokens at borrow time too - which is currently unsupported, but we should be prepared for it as things will similarly fail there
Once the 3 above are tackled, a final PR should be expected with a proper switch case on Tx type, similar to THORChain LP:
https://github.com/shapeshift/web/blob/c4c9f4f5433aab7582561a0ec1e0a1984003acfe/src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx#L466
N/A for this specific issue, but …
> fix: thor token repayments

- src/components/Modal/components/DialogBackButton.tsx
- src/components/Modals/Receive/ReceiveRouter.tsx
- src/components/Modals/Send/Form.tsx
... regardless of context, since asset selection is always the initial route for
- Sends (dashboard/asset page)
- Receives (dashboard/asset page)
Note, QRCode asset selection is a different variant which isn't affected by the removal of the button here, hence still keeps its back functionality unbroken. 
closes https://github.com/shapeshift/web/issues/6665
- Back button is gone from send modal asset selection step, both in dashboard and asset page
- Back button is gone from receive modal asset selection step, both in dashboard and asset page
- Back button is still present in the QR code variant of the asset selection step in dashboard e.g after scanning an EVM …
> fix: don't render back button on modals initial routes

- packages/unchained-client/openapitools.json
Use the `cosmos` unchained branch to source the cosmos swagger file.
Looks necessary based on comment in https://github.com/shapeshift/unchained/pull/980, and the changes in https://github.com/shapeshift/unchained/pull/980/commits/dc4e5d44453daee76b7f31f0a1dee62a0145d044 to remove the cosmos directory.
Unblocks current release.
Small
Cosmos chain.
Cosmos-related functionality should work as expected.
☝️
☝️
N/A
> fix: use cosmos branch

- packages/types/src/base.ts
- src/components/Modals/Snaps/SnapIntro.tsx
- src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
- src/components/TradeAssetSearch/TradeAssetSearch.tsx
- src/constants/chains.ts
- src/context/AppProvider/AppContext.tsx
- src/lib/address/address.ts
- src/pages/ConnectWallet/ConnectWallet.tsx
- src/pages/Lending/hooks/useLendingSupportedAssets/index.ts
- src/plugins/walletConnectToDapps/components/modals/SessionProposal.tsx
- src/state/migrations/index.ts
... i.e without ChainIds that are currently flagged off. This is in response to the following from @MbMaria https://github.com/shapeshift/web/pull/6667#issuecomment-2058170776:
> This is fixed on the trade from asset drop down but the icon still appears in the trade to menu
And indeed, with the current assumptions that KnownChainIds is static, and the many many consumptions of it, it's not sane to expect tackling all the feature-flags detection.
By having a static knownChainIds array that checks whether the feature-flag is enabled/disabled for it at module evaluation time, we ensure *all* consumoors don't run the chance of exposing ChainIds which
are currently flagged off.
For completeness, added all chains that we currently have flags for.
- relates to the closed …
> feat: move from Object.keys(KnownChainIds) to safe knownChainIds array

- src/assets/translations/en/main.json
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
Add the `WarningAcknowledgement` component to the LP withdraw flow, replacing the existing `Alert` component.
Note, we still have the `incompletePositionWithdrawAlert` shown as an alert - awaiting input from @shapeshift/product on how to best handle multiple warnings (sequential acceptance?).
Contributes to https://github.com/shapeshift/web/issues/6707
Medium - getting it wrong could impact LP withdraws,  but the component pattern is well tested and in production already.
LP withdraws.
Attempt to withdraw a small LP position and confirm that on click of "Remove liquidity" the `WarningAcknowledgement` is shown, and can be accepted.
☝️
☝️
See description above.
> feat: warning ack for dangerous withdraw

- package.json
- src/setupVitest.ts
- src/types/module-alias.d.ts
- yarn.lock
Fixes tests failing due to ethers version conflict between web and hdwallet.
NA
Low risk.
Run `yarn test` -> all tests should pass.
> fix: override hdwallet ethers version in vitest

- src/Routes/Routes.tsx
- src/components/LanguageSelector.tsx
- src/context/AppProvider/AppContext.tsx
Improves few aspects of the current way we handle language selection:
* The current language is now set in the `lang` attribute of the `<html>` tag to improve accessibility, as suggested in #5474
* The `lang` URL parameter gets removed once the desired language is applied in the app. This also fixes a bug as it was not possible to change language from the one specified this way in the URL previously. Still defaults to "en" (English) if the language is not supported.
* Only load the locale formatting if the selected locale exists in `LanguageTypeEnum`, avoiding an bug ("Oops" error) if someone tries to use an invalid `lang` URL parameter.
* The value of the current language in the LanguageSelector is now set through `value` instead of `defaultValue`, so it gets updated when …
> feat: improved lang selection and param

- src/components/Layout/Header/NavBar/Notifications.tsx
Does what it says on the box - as soon as we have `useWallet().state.wallet` (i.e on Ledger connect click) the `<Notifications />` component becomes reactive and attemps fetching Ethereum address,
which it can't, as the wallet doesn't support Ethereum right out the gate without it being explicitly added as a chain.
closes #6713
Low - this brings *more* safety, ensure notifications feed still work properly for native
- Ensure notifications feed still work properly for native
- ^
- ^
> fix: ledger notifications feed error spew

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/lib/utils/thorchain/balance.ts
- src/pages/Lending/hooks/useGetEstimatedFeesQuery.ts
This PR improves the loading state of savers at both deposit and withdraw steps.
This makes things more reliable, without the flash of loading states that was especially obvious in deposit, and makes the continue button click reliable.
closes https://github.com/shapeshift/web/issues/6750
Low - Really only touches loading states
- Savers deposit don't have a weird flash of loading/disabled state anymore with dead clicks
- Savers withdraw don't have a weird flash of loading/disabled state anymore with dead clicks
- ^
- ^
- AVAX
https://github.com/shapeshift/web/assets/17035424/af5d2a0f-49d2-4bd5-9dfc-5efefbc567ea
- DOGE …
> fix: savers unreliable loading state

- src/lib/utils/thorchain/memo.ts
Disables the `minOut` check for lending, as it's an optional value in the memo response from THORChain.
See https://dev.thorchain.org/concepts/memos.html#open-loan and https://dev.thorchain.org/concepts/memos.html#repay-loan.
This PR only aims to address the immediate blocker for the current release (https://github.com/shapeshift/web/pull/6804) introduced in https://github.com/shapeshift/web/pull/6791.
> fix: disable minOut check

- src/lib/utils/thorchain/memo.ts
Fixes regression in https://github.com/shapeshift/web/pull/6755 where `undefined` was present in the memo for savers withdraws and deposits, which cannot be parsed by THORChain.
N/A
Theoretically high as it touches memos, but practically low as it fixes a known issue.
Thorchain savers deposits and withdraw.
Complete a savers deposit or withdraw and confirm that the `minOut` field of the memo is an empty string and not `undefined`.
☝️
☝️
N/A
> fix: nullish coalescing in savers memo

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/react-queries/queries/accountManagement.ts
- src/state/migrations/index.ts
- src/state/slices/common-selectors.ts
- src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/portfolioSliceCommon.ts
- src/state/slices/portfolioSlice/selectors.ts
- src/test/mocks/store.ts
Incremental progress on wiring up account management. This PR implements:
* Enabled accounts automatically appear as "toggled on" in the import accounts drawer
* Add and remove accounts and have them persist across page reloads
* Ability to toggle on accounts and click cancel and not have it persist
* Display all added accounts including disabled ones in between enabled ones
Fixes:
* Using `wallet.deviceId()` promise as a key in react query -> uses string from context instead
Excludes:
* Proper loading state for "Done" click where app is hydrating portfolio for imported accounts
* Anything wallet specific
* Anything feature specific outside of adding and removing accounts inside of account management (e.g probably broken for trades etc)
* Correct account balances for accounts yet to be …
> feat: more account management wiring

- src/lib/utils/thorchain/memo.ts
- tsconfig.json
We've been burned in `assertAndProcessMemo` by `String.prototype.split()` returning an array of strings, while it's really returning `(string|undefined)[]`, see e.g https://github.com/shapeshift/web/pull/6809.
While adding `noUncheckedIndexedAccess` isn't a reasonable option (i.e `Found 556 errors in 119 files.`), we can at least add it temporary and add the required strictness to the offenders here, which this PR does.
N/A
Low, though being more strict comes with its own risks - confirm the checks are sane
- Do a sanity pass of THOR Txs and confirm they are happy (no need to broadcast - set a breakpoint in`useSendThorTx`'s `executeTransaction` at the very first …
> feat: assertAndProcessMemo leverage noUncheckedIndexedAccess strictness

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/components/ManageAccountsDrawer/components/SelectChain.tsx
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
- src/react-queries/queries/accountManagement.ts
- src/state/slices/portfolioSlice/selectors.ts
* Fixes "Wrong account count in account management modal on UTXO chains" #6788 by displaying various UTXO account types, making it clear the account count is in fact correct.
* Displays all UXTO accounts (segwit native, segwit, legacy) #6789
* Loads native asset balances for all accounts so new ones are not zero if they have funds #6797
closes #6789
closes #6788
closes #6797
Low risk.
None of the above.
* Check the account count on the manage accounts modal matches the number of accounts in the import accounts drawer. Note that it's very tricky to tell the difference between in inactive account and an active one if there is zero native asset balance on that …
> feat: account management wiring progression

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/state/slices/portfolioSlice/portfolioSlice.ts
Refactor to make the import accounts drawer use toggle functions instead of setters. No functionality changes with this PR.
NOTE: A bug was identified while implementing this where the toggle state from a previous chain being managed appears on the current one - this will be fixed in a follow-up PR (https://github.com/shapeshift/web/pull/6817) as it's unrelated to this.
closes #6815
Low risk.
Check account import toggles in the account management drawer functions as it did previously (including the toggle state bug identified above)
> chore: make account management toggles use toggle functions instead of setters

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/components/ManageAccountsDrawer/helpers.ts
- src/react-queries/queries/accountManagement.ts
Addresses several state corruption issues related to import accounts drawer in account management, namely state being rendered for the previously opened chain.
Key changes:
1. Migrates the account import queries to `useInfiniteQuery` in order to simplify state management
2. Resets component state when a different chain is being managed
3. Uses an actually unique key for account rows (instead of account number which is shared across different chains)
NA
Low risk.
Check that navigating to different chains in the "import accounts" drawer renders the correct toggled state of the accounts. 
Demo showing corrected state where toggles are actually representative of chain …
> fix: state corruption of import accounts drawer

- src/components/Layout/Header/NavBar/Native/NativeMenu.tsx
- src/components/Layout/Header/NavBar/UserMenu.tsx
- src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
- When you opened a sub menu item the drawer would not collapse on native wallets
- This adds the onClose callback to the nested menu items
closes #6617 
mild
When on mobile, open the drawer and expand the wallet dropdown. 
Select the backup my wallet
Enter password
You should be able to scroll the modal vertically to see the buttons and your full seed phrase.
> fix: close sidenav drawer when sub menu item clicked

- src/state/slices/portfolioSlice/utils.ts
Updates the account label for cosmos and thorchain accounts to be the shortened "first four, last four" address, as is done with EVMs. This change was triggered by #6837 and expanded to be app-wide since it has actual utility UX-wise (see screenshots)
closes #6837
Low risk, only related to account labels which are presumably already wired up correctly.
Check account labels around the app are correct and that displaying thorchain and cosmos account labels as a shortened address makes sense. So far all known occurrences or thorchain and cosmos account labels DO make sense to be displayed as an address (see screenshots).
Import accounts, borked account label:
Updated …
> fix: display thorchain and cosmos account label as the shortened address

- src/assets/translations/en/main.json
- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
- src/context/AppProvider/AppContext.tsx
- src/pages/Accounts/AddAccountModal.tsx
- src/state/migrations/index.ts
- src/state/slices/common-selectors.ts
- src/state/slices/opportunitiesSlice/selectors/selectors.test.ts
- src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap
- src/state/slices/portfolioSlice/portfolioSlice.test.ts
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/portfolioSliceCommon.ts
- src/state/slices/portfolioSlice/selectors.ts
- src/test/mocks/store.ts
This PR includes the following changes:
1. Fixes issue where importing an account via account management requires 2 attempts in order for the new account to persist in redux.
2. A simplification of state management where we track `enabledAccountIds` rather than `hiddenAccountIds`, negating the need to check the existence of an account in state management before fetching it and toggling it (which created a race condition).
3. Improved handling of no accounts yet connected in the UI (see screenshots below)
Not included known issues to be followed up on:
* loading state during initial wallet connection briefly shows empty "add a chain to get started" 
* loading state of import accounts drawer borked, which is already raised in upstream PR and will be resolved
* loading state when clicking …
> fix: import accounts requiring 2 attempts for account to persist

- src/components/ManageAccountsDrawer/components/SelectChain.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/context/WalletProvider/Ledger/constants.ts
Allows new chains and accounts to be added for Ledger via the new account management workflow.
Closes https://github.com/shapeshift/web/issues/6807
Small, though could botch the ability to connect a Ledger chain.
Ledger connectivity.
Connect a Ledger, and see the screenshots section for the expected states.
☝️
☝️
The key change, all available Ledger chains will now show here, regardless of whether they've actually been connected to or not:
This component should show all chains with accounts:
The current (outgoing) connection flow should remain unaffected, showing all base chains, as before:
> feat: handle ledger account & chain management

- .github/workflows/sentry.yml
- src/assets/translations/en/main.json
- src/components/Layout/Header/NavBar/Native/NativeMenu.tsx
- src/components/Layout/Header/NavBar/NavBar.tsx
- src/components/Layout/Header/NavBar/UserMenu.tsx
- src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/components/ManageAccountsDrawer/components/SelectChain.tsx
- src/components/ManageAccountsDrawer/helpers.ts
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
- src/context/AppProvider/AppContext.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/parseThorBuyTxHash.ts
- src/pages/Accounts/AddAccountModal.tsx
- src/react-queries/queries/accountManagement.ts
- src/state/migrations/index.ts
- src/state/slices/common-selectors.ts
- src/state/slices/opportunitiesSlice/selectors/selectors.test.ts
- src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap
- src/state/slices/portfolioSlice/portfolioSlice.test.ts
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/portfolioSliceCommon.ts
- src/state/slices/portfolioSlice/selectors.ts
- src/state/slices/portfolioSlice/utils.ts
- src/test/mocks/store.ts
fix: import accounts requiring 2 attempts for account to persist (#6819)
fix: sentry action syntax (#6841)
fix: incorrect stack props on NavBar (#6838)
fix: display thorchain and cosmos account label as the shortened address (#6839)
fix: close sidenav drawer when sub menu item clicked (#6831)
fix: state corruption of import accounts drawer (#6817)
chore: make account management toggles use toggle functions instead of setters (#6816)
feat: account management wiring progression (#6798)
fix: parse buy txid from midgard actions (#6813)
> chore: release v1.590.0

- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
- src/lib/swapper/swappers/ThorchainSwapper/types.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/checkOutputTxConfirmations.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/parseThorBuyTxHash.ts
Follow up on: https://github.com/shapeshift/web/pull/6813
`checkOutboundTxConfirmations` was still using `out_txs[0]` instead of `latestOutTx`, so this change ensures everything is using the same out tx for status checks.
N/A
Medium - changes logic surrounded status updates for swaps
Thorchain
See https://github.com/shapeshift/web/pull/6813
:point_up: 
:point_up:
> fix: use latest out tx for all checks

- src/context/TransactionsProvider/TransactionsProvider.tsx
Currently, we are polling thorchain for tx status on any tx detected over websocket on savers supported chains. To reduce this spam, we can now check the tx metadata and only poll on savers transactions. This is reliable for all savers transactions made through the app. If there is no memo on an external savers transactions (via walletconnect), we would miss the update.
N/A
Low - worst case a refresh is needed for savers opportunity update
- Perform a savers deposit and validate opportunity updates on confirmation
- Perform a savers withdraw and validate opportunity updates on confirmation
:point_up: 
:point_up:
> fix: no more thor tx status spam

- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
- src/context/ModalProvider/types.ts
- src/pages/Accounts/Accounts.tsx
Changes the 'add account' button to 'manage accounts' when account management feature is flagged on.
Context: https://discord.com/channels/554694662431178782/885616186623148062/1237300175907590165
Very low risk.
* When account management is DISABLED, clicking "add account" show behave same as prod
* When account management is ENABLED, the button should say "manage accounts" and should open the manage accounts drawer when clicked
* Note ledger support is still WIP with feature flag enabled
* Only affects multi-account supported wallets and metamask should not show the button at all (prod and this PR)
> feat: change 'add accounts' button to 'manage accounts' when account management is enabled

- src/components/ManageAccountsDrawer/components/LedgerOpenApp.tsx
Addresses feedback from @woodenfurniture on https://github.com/shapeshift/web/pull/6847, where the Ledger app detection component does not have a loading state, and so can appear glitchy when jumping between screens on app detection.
> We could use some kind of spinner or something while it's auto-detecting, otherwise it looks like a glitch as it jumps page quickly (I was about to raise it as a bug)
>
> https://github.com/shapeshift/web/assets/125113430/06c4b6f6-8950-4190-9cd7-9bee56ad6cf4
N/A
Very small.
None.
When connected to a Ledger, navigate through the chain add workflow, both with and without the app already open.
It should look a little less jank with the loading spinner now in place.
☝️
☝️ …
> feat: add ledger app detection loading spinner

- src/context/WalletProvider/Ledger/components/Connect.tsx
- src/context/WalletProvider/Ledger/components/LedgerMenu.tsx
When the `AccountManagement` and `AccountManagementLedger` feature flags are enabled, use the new drawer flow for Ledger connection.
Closes https://github.com/shapeshift/web/issues/6808
Medium - could bork Ledger connection if Implemented incorrectly.
None.
Test connecting to a Ledger with both with and without the feature flags enabled.
- When they are disabled, we should use the existing flow upon connection.
- When they are enabled, upon connection we should open the new account management modal showing the currently connected accounts and chains, and allow adding more via the drawer flow.
☝️
☝️
N/A
> chore: use drawer flow for ledger initial connection

- scripts/generateTradableThorAssetMap/utils.ts
- src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx
- src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx
- src/context/WalletProvider/MobileWallet/components/MobileCreate.tsx
- src/context/WalletProvider/MobileWallet/components/MobileCreateTest.tsx
- src/context/WalletProvider/NativeWallet/components/NativeTestPhrase.tsx
- src/lib/globals.ts
- src/lib/swapper/swappers/ThorchainSwapper/utils/makeSwapMemo/assertIsValidMemo.ts
- src/lib/utils/index.ts
- src/pages/ThorChainLP/utils.ts
- src/state/slices/txHistorySlice/utils.ts
- src/utils/sentry/httpclient.ts
follows-up on https://github.com/shapeshift/web/pull/6810 - since we can't do the `noUncheckedIndexedAccess` dance without having 500+ errors, this at least brings strictness for the specific
case of `Array.prototype.split()` returning `(string | undefined)[]` vs. `string` with our current compiler options.
Note that this aims to be a non-breaking change - while the strictness is now present, all type violations have been tackled in a way that should be non-breaking, with either:
- nullish coalescing to `''` (i.e no different than before, since we were assuming a string)
- throwing exceptions when applicable, for the specific cases where this doesn't change the flow and things would already fail as-is
N/A, follows-up on https://github.com/shapeshift/web/pull/6810 
> High Risk PRs Require …
> feat: additional Array.prototype.split() safety

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
Adds loading state to account import in the manage accounts drawer.
closes #6849
Moderate risk. This is intended to prevent getting into invalid app state during account import, when opening and closing the account management drawer.
Check that it's not possible to corrupt the state of the app by importing an account and opening/closing the account management drawer, and also rapidly adding/removing accounts. 
Original issue:
https://github.com/shapeshift/web/assets/125113430/c3dea3d3-b6cb-4cbc-9981-9e29ac882efa
Fixed:
https://github.com/shapeshift/web/assets/125113430/623aa190-9c89-410b-af76-566fd57028e0
> feat: loading state for account import

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
Fixes non-ledger wallets (e.g native) unable to load any accounts in "import accounts" in account management.
closes #6906 
Low risk.
Check non-ledger wallets can load accounts in import accounts drawer in account management (metamask excluded)
https://github.com/shapeshift/web/assets/125113430/26670856-1690-44ca-a7b7-7464f4982ec0
> fix: non-ledger wallets unable to import accounts

- src/components/AssetSelection/AssetSelection.tsx
- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/RelatedAssets/RelatedAssets.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/state/selectors.ts
- src/state/slices/assetsSlice/selectors.ts
- src/state/slices/portfolioSlice/selectors.ts
- src/state/slices/related-assets-selectors.ts
Only displays related assets for chains that are currently connected to the app, except for LP add liquidity which shows all available chains for the selected asset.
closes #6905 
~~Marking this as high risk, as it makes minor changes to asset selectors. ~~
After discussion, this is actually moderate risk and should not require multiple reviewers.
The change is largely lift-and-shift with the addition of conditionally filtering on wallet connected chains for related assets. The selectors were moved into a different file due to circular deps.
* Only related assets on chains currently connected to the app appear in trade input chain dropdown
* Only related assets on …
> fix: only display wallet connected chains in related asset selection

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/ManualAddressEntry.tsx
Improve UI and UX when attempting to trade into a non-connected chain.
This affects Ledger specifically by showing the correct "add account" copy, which brings up the Account Management modal, and also improves copy for non-MetaMask wallets by _not_ prompting for a Snap installation unless MetaMask is connected.
Closes https://github.com/shapeshift/web/issues/6914, specifically via the approach mentioned in https://github.com/shapeshift/web/issues/6914#issuecomment-2116265947.
Small - copy change and link to an existing modal.
None.
When connected to MetaMask and attempting to trade into a missing chain, the UI should look and behave as it currently does:
When connected to a Ledger and attempting to …
> feat: prompt add ledger account

- src/assets/translations/en/main.json
- src/context/WalletProvider/Ledger/components/Connect.tsx
- src/context/WalletProvider/Ledger/constants.ts
- src/context/WalletProvider/components/ConnectModal.tsx
- src/state/slices/portfolioSlice/selectors.ts
Adds temporary user flow to detect and handle the case where a user may connect a different ledger device.
- If the app detects a previously connected ledger, UI prompts the user to either proceed with the current device, or to connect a new device.
- If the user proceeds with the current device, the portfolio cache is used to maintain their configured chains
- If the user decides to connect a new device, the portfolio cache is nuked and the user can configure their new ledger without fear of cache corruption.
Note this workaround is temporary until we can follow up with solution yet to be determined in https://github.com/shapeshift/web/issues/6814
relates to #6814
Moderate risk, if cache clearing is borked or missing in a user flow its possible for …
> feat: temporary workaround to handle multiple ledger devices

- src/pages/Dashboard/components/DashboardHeader/DashboardDrawer.tsx
Opening modals while the menu drawer is opened on mobile cause scrolling issues inside modals
- fixes the wallet connect issue mentioned here: https://github.com/shapeshift/mobile-app/pull/96#issuecomment-2118309758
Not so risky but you can scroll the content while the menu drawer is opened now, we might wan't to grain fine this fix but for now it fixes some issues with modals
See https://github.com/shapeshift/mobile-app/pull/96#issuecomment-2118309758
- Enable responsive (on a small enough device e.g iPhone SE a.k.a 375 * 667)
- Note, the default behavior of devtools while in responsive is it disables your desktop's native scroll and you have to swipe, similar to mobile instead. If that's weird for you and you want to scroll the usual way, you can always change the behavior by 
- …
> fix: enable scroll when menu drawer is opened

- src/state/slices/common-selectors.ts
- src/state/slices/portfolioSlice/selectors.ts
Fixes bug in `selectPortfolioUserCurrencyBalancesByAccountId` selector where user currency balances default to crypto base unit values when fiat prices are missing for a given asset.
NA
High risk. While the change resolves a severe issue in balance tracking, the impact of getting this wrong is high.
Check fiat balances and functionality relating to fiat balances (e.g sorting of accounts based on fiat balance etc).
Check app to ensure there is no change from production, or if there is, it resolves an issue stemming from incorrect user balances.
Before:
After:
> fix: dont default user currency balances to crypto amounts when fiat pricing is not available

- .github/workflows/generate.yml
I noticed the color map was being generated after the asset data. While not a huge problem, the correct flow is to generate the color map first which will be used in the subsequent asset data generation.
N/A
None
- Asset data will include newly generated colors if there are changes
:point_up: 
N/A
> fix: generate color map before asset data

- src/components/ManageAccountsDrawer/components/DrawerWrapper.tsx
- src/components/Modals/ManageAccounts/ManageAccountsModal.tsx
Improve UX when the account management drawer is open.
Before:
After:
N/A - UX improvement prior to feature launch.
Low
None.
When the account management drawer is open, we should now set the "Add Chain" button to a loading state, and disable the "Done" button.
This states should revert when the drawer is closed.
☝️
☝️
N/A
> chore: improve UX when account drawer is open

- src/pages/RFOX/components/Stake/StakeConfirm.tsx
Tackles the jumpy issue spotted by @0xApotheosis in https://github.com/shapeshift/web/pull/6925#pullrequestreview-2075415898:
- relates to the closed https://github.com/shapeshift/web/issues/6737
- Using MM, fire click either the approve or stake button depending on whether or not an approval is needed
- Wait something like 15-30s before confirming the Tx in wallet (node is currently turbo slow so things can take a v. long time to respond back)
- Ensure the gas fee is not refetched after you clicked the confirm button in app 
- Ensure the fas fee is still not refetched after confirming in MM, and before we route to status
- ^
- ^ …
> feat: don't refetch approval/stake fees when mutation is pending

- src/lib/utils/thorchain/memo/assertAndProcessMemo.test.ts
- src/lib/utils/thorchain/memo/assertAndProcessMemo.ts
- src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
Ensures we benefit from automagical streaming loan closes, so that users don't end up with reverts and get the best rate possible on their collateral refund.
N/A, spotted in https://discord.com/channels/554694662431178782/876953436908822568/1244772064590561280
Low, we now honor the THOR-returned memo. If something is wrong here, then something is wrong in the quote.
- Test with either your own loan or a frame injected known borrower
- Get a quote for 100% repay and note the memo in the `close` request (see screenshots)
- Ensure that the actual memo in the calldata (either on the on-chain Tx, or in frame if testing with Frame) is the same as the quote one, except …
> feat: remove MinOut safety from THOR repays

- src/assets/translations/en/main.json
- src/pages/RFOX/components/Claim/ClaimSelect.tsx
Fetches claims from rFOX contract showing them in the claims tab.
Note, this PR is not expected to populate the claim confirm flow when a `ClaimRow` is selected - only to show available claims.
Also note, the UI is a little borked with respect to the flex end alignment. Wasted a decent chunk of time trying to fix, will address as a follow-up.
Contributes to https://github.com/shapeshift/web/issues/6899
Small, contract reads and UI only.
rFOX contract reads.
- Loading the "Claim" rFOX tab should show all available claims for the connected account, and unavailable claims greyed out. On hover, the relative cooldown period should be shown in a tooltip.
- Connecting to an account with no available claims …
> feat: fetch claims from rFOX contract

- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
Fixes an issue where existing accountIds in the store (that have been enabled) would not show in the new account management "add account" drawer if the previous account did not have a balance.
E.g. if account 0 has no balance, but accounts 0 and 1 have been added for a chain, only account 0 would show in the drawer:
N/A - discovered whilst testing.
Small
None.
See example of when this bug occurs in the description.
☝️
☝️
See above.
> fix: show existing account ids in store

- src/components/HelperTooltip/HelperTooltip.tsx
- src/components/Layout/Header/NavBar/ManageAccountsMenuItem.tsx
- src/components/Layout/Header/NavBar/Native/NativeMenu.tsx
- src/components/TooltipWithTouch.tsx
- src/context/WalletProvider/DemoWallet/DemoMenu.tsx
- src/context/WalletProvider/KeepKey/components/KeepKeyMenu.tsx
- src/context/WalletProvider/Ledger/components/LedgerMenu.tsx
- src/context/WalletProvider/MetaMask/components/MetaMaskMenu.tsx
- src/pages/RFOX/components/ChangeAddress/ChangeAddress.tsx
- src/pages/RFOX/components/ChangeAddress/ChangeAddressConfirm.tsx
- src/pages/RFOX/components/ChangeAddress/ChangeAddressStatus.tsx
- src/pages/RFOX/components/Stake/Stake.tsx
- src/pages/RFOX/components/Stake/StakeConfirm.tsx
- src/pages/RFOX/components/Stake/StakeStatus.tsx
- src/pages/RFOX/components/Unstake/Unstake.tsx
- src/pages/RFOX/components/Unstake/UnstakeConfirm.tsx
- src/pages/RFOX/components/Unstake/UnstakeStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
- src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
fix: make tx status great again on lp deposits (#7045)
fix: make multi accounts menu item reusable and consume it in every related menus (#7032)
fix: rfox invalidate queries on Tx confirm (#7017)
fix: add touchable tooltip component (#7050)
> chore: release v1.607.0

- src/context/AppProvider/AppContext.tsx
- src/state/migrations/index.ts
Ensures the chainIds available in the app include the feature-flagged chainIds from 
closes #
Fixes https://discord.com/channels/554694662431178782/1247718768558477323/1247741645886062602
Moderate risk - getting this wrong would mean its possible to interact with chains that are not toggled on (e.g base chain), but this should actually improve things rather than break them.
Test available chains in the app are as expected.
See `src/context/PluginProvider/PluginProvider.tsx` for origin of `const { supportedChains } = usePlugins()`:
> fix: use feature-flagged chainIds to determine use in the app

- src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
- src/pages/Lending/Pool/components/Repay/RepayInput.tsx
Reverts behavior introduced in #7029 of lending asset selection when a wallet chain is disconnected. Basically we were being "too helpful" to the point the behavior was somewhat confusing and not really of use to a user.
The behavior now is to do nothing in borrow/repay asset selection when the wallet disconnects the chain for the currently selected asset, and its now up to the user to select the correct one.
Addresses feedback in
https://github.com/shapeshift/web/pull/7029/files#r1622050051
and
https://github.com/shapeshift/web/pull/7029/files#r1622042222
Low risk, this actually brings us back to behavior that was already in production and not flagged as broken. …
> feat: dont be too smart handling asset selection when wallet disconnects a chain

- src/pages/RFOX/components/Claim/ClaimSelect.tsx
- We are claiming, not unstaking on the claim list - updates text accordingly
- Conveniently fixes the alignment issue
`develop`:
This PR:
N/A - rFOX fix.
Very small.
None.
See screenshots above of expected state.
☝️
☝️
See above.
> fix: translation & claim alignment

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/TimeRemaining.tsx
- src/pages/RFOX/components/Claim/ClaimSelect.tsx
Raised by @firebomb1 at https://discord.com/channels/554694662431178782/1249691190987722764
Using `dayjs` allows us to use existing translations, so this PR refactors the claim usage to use it.
Also removes all explicit uses of the transient `date-fns` package.
https://discord.com/channels/554694662431178782/1249691190987722764
Small
None.
- When hovering over a claim in the claim view the relative time should still show
- The "time remaining" UI of a trade should continue to work as expected
☝️
☝️
> chore: swap date-fns with datejs

- src/assets/translations/en/main.json
- src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
This improves two bits in the send flow:
1. Initial flash of "Insufficient funds" error state on max send, caused by `amountCryptoPrecision` not being casted as 0 by bignumber.js in:
https://github.com/shapeshift/web/blob/1eb71c3c109d2c7febfe0a2ef2746f7769ba1b60/src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx#L156
2. Failed XHR errors being wrongly surfaced to the user
closes https://github.com/shapeshift/web/issues/7084
Low
1. Let BTC `fees` request fail for a max send (it's currently failing often enough to test this)
2. Ensure the network fetch error isn't surfaced to the user but "Error getting fees" is instead
1. Click max send on BTC
2. …
> feat: improve send modal flow

- src/pages/RFOX/components/Shared/SharedMultiStepStatus.tsx
- src/pages/RFOX/components/Shared/TransactionRow.tsx
- The circle progress on the top margin top spacing was a big too big
- Made the elements wrapping under if there are not enough space on the tx statuses rows of the bridge modal
- Added some spacing on the continue button
n/a
Low risk
- Try to bridge using the rfox bridge
- Or monkey patch like I did in [bee0db4f231c49c1a70a1ff54711ba6ae223eed6](https://github.com/shapeshift/web/commit/bee0db4f231c49c1a70a1ff54711ba6ae223eed6)
n/a
n/a
> fix: transaction row overflowing in rfox bridge status modal

- package.json
- src/components/DeFi/components/AssetInput.tsx
- src/features/defi/components/Deposit/Deposit.tsx
- src/features/defi/components/Deposit/PairDeposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- yarn.lock
Fixes validation being triggered, but not surfaced on percent option click for deposits (spotted with THORChain savers deposits)
closes https://github.com/shapeshift/web/issues/7105
Low - ensure validation still works on input, and now properly works on percent option change for THORChain savers deposits.
- THORChain savers deposits validation is now happy on percent option click
- THORChain savers deposits validation is still happy on input
- ^
- ^
https://jam.dev/c/234119a4-be46-4ed6-9f7f-6a1ba96c0ade
> fix: deposit rugged validation on percent option click

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
- src/state/slices/tradeInputSlice/tradeInputSlice.ts
Persists the trade input state when previewing a trade, and then going back. Includes fixes:
* Clicking the same sell asset as the current one was causing the quotes to disappear
closes #7026
* Low risk of state corruption leading to incorrect input amounts, with high impact.
* Moderate risk of state corruption leading to general jankiness in the trade input, with low impact.
* Check use can set up a quote, preview it and click back and have their input state persist
* Check sell amount interactions combined with changing buy/sell assets consistently gives correct sell amounts and correct state without state corruption or incorrect quotes
* Ensure. sell amounts …
> feat: dont clear trade input when previewing and going back

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/pages/ThorChainLP/AvailablePools.tsx
- src/pages/ThorChainLP/Pool/Pool.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
- src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
- src/react-queries/hooks/useIsTradingActive.ts
This PR:
- removes the assetId type-narrowing from consumers (i.e `enabled={assetId}`)
- makes `useIsTradingActive` itself handle the undefined `assetId` case, ensuring we don't run the mimir query if there's no need to (i.e no `assetId` means we can't get inbound address data, hence can't select trading active alongside with mimir)
- loosely contributes to https://github.com/shapeshift/web/issues/6996
Low - ensure trading active checks are still happy across the app (swapper, savers, LP...)
- Trading active checks are still happy across swapper, savers and LP
- ^
- For paranoia purposes, trading inactive can also be tested with this diff
```diff
diff --git …
```
> feat: type-safe useIsTradingActive

- react-app-rewired/index.ts
This PR tackles RFOX unchained-client parser not working after https://github.com/shapeshift/web/pull/7158 went in, by fixing a long-lasting issue with env vars not being available outside of web in builds.
See debugger in current unchained-client, after setting `REACT_APP_FEATURE_NFT_METADATA` to true for context.
I've turned the env var expression into a var and console.logged it for debugging purposes, since local scope tends to be borked in builds.
- When running the app with webserver, this guy is defined
- However, when building the app and serving it, it immediately becomes rugged:
Same goes for RFOX proxy contract address env vars:
- When running the app with webserver, this guy is defined
- However, when building the app and serving it, it immediately becomes rugged:
closes N/A, …
> feat: make env vars great again in builds

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
We already know about the trading halt status in the trade quote scope as the `validateTradeQuote` is called by the `swapperApi` upstream, which in turn already calls the `inboundAddresses` endpoint.
This PR ensures we have one source of truth, the `swapperApi`, for when a quote is valid and not halted.
Closes https://github.com/shapeshift/web/issues/7154
Medium - there should be no behaviour change here, though getting it wrong could mean allowing a user to execute a trade on a halted pool.
Swaps. Specifically, THORChain swaps.
Get some quotes and ensure that both THORChain and non-THORChain quotes can be moved to the confirm step.
Monkey patch the inbound address response processing logic to make …
> refactor: simplify active trading

- src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosEmpty.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingEmpty.tsx
Fixes console spew in the DeFi section when clicking opportunities in the carousel (see video below).
The cause was `div` and `p` tags appearing as descendants of a `p` tag (`Text`, imported as `CText`).
N/A
Small
None.
Click an opportunity in the carousel, as per the video below, and observe no log spew 😌 
☝️
☝️
https://github.com/shapeshift/web/assets/97164662/b735360e-d9b5-4569-93eb-65985030a6e4
> fix: p tag descendants

- src/components/DeFi/components/AssetInput.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
[This guy](https://github.com/shapeshift/web/commit/0e553d83624d68578e9fe947bc3fe369d761c232#diff-225bad65687ba44270edf5d0d7e3b1edb8d8fcc7a17f263552c5d608f0f47001R145-R147) introduced an infinit rerender loop on LP withdrawals
As it fire the `handleChange` everytime the value changes (including the initial render), it ends up infinitely changing the value again and then rerendering and 💥 
This PR act as a quickwin to make liquidity withdrawals great again but it might be worth investigating how to refactor this part in `RemoveLiquidityInput`, like maybe we could avoid the effect or find a different pattern
closes #7181
High as LP withdrawals could be strange but it's a hotfix so it should do the contrary
- Try to withdraw some LP like AVAX/RUNE pool
n/a
n/a
> fix: infinit rerender loop on remove liquidity

- src/state/slices/txHistorySlice/selectors.ts
Fixes `ErroredTxHistoryAccounts` popover displaying previously connected accounts.
closes #6971
Low risk - a display concern only.
As this issue is only visible while one of our nodes is degraded, testing best done locally by engineers with monkey patch (see PR comment for exactly how).
Monkey patch was applied to display all accounts as errored.
Issue reproduced with money patch:
Fix with monkey patch:
> fix: dont display other wallet accounts in tx history degraded popover

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Fixes the "Approve" button being greyed out for LP deposits on first quote request.
A 2-liner fix with a slightly longer explantation on what was going on:
We are skipping the query to get `estimatedPoolAssetFeesData` if an approval was required (makes sense - wait until we need to do the query before making it).
https://github.com/shapeshift/web/blob/481de89af6188c1642a95826e06f1c8e3b370fef/src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx#L528-L532
This means that `isSweepNeeded` is (rightly) equal to `undefined` when an approval is required on first quote request, as on first load we do not have a value for `txFeeCryptoBaseUnit` (we haven't yet done a request to get `estimatedPoolAssetFeesData.txFeeCryptoBaseUnit`), and so the `isGetSweepNeededInput` check fails, …
> fix: first load lp deposit approval

- src/features/defi/providers/cosmos/components/CosmosManager/Claim/CosmosClaim.tsx
- src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Claim/ClaimRoutes.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Overview/FoxyOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/ThorchainSaversDeposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/ThorchainSaversWithdraw.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
- src/state/slices/opportunitiesSlice/selectors/selectors.test.ts
- src/state/slices/opportunitiesSlice/selectors/stakingSelectors.ts
When opening the savers overview we currently select the account with the highest staked balance.
If the user has no staking balance for any accounts for that `assetId` we'll select the last account in the list (from `selectUserStakingOpportunitiesById`).
This is perhaps counter-intuitive to a user.
This PR selects the account with the highest balance if the user has no opportunities for that asset.
Closes https://github.com/shapeshift/web/issues/7167
Small
THORChain savers.
Click on a UTXO with multiple derivations (e.g. LTC, BTC).
- If the wallet has opportunities for the asset, the account with the highest balance opportunity should be selected.
- If the wallet does not have opportunities for the …
> feat: staking deposit account improvements

- src/index.tsx
- src/pages/Flags/Debugging.tsx
Creates and stores a unique anonymous user ID to allow ops to find events generated by a specific user.
Initially the built-in session ID `sid` from sentry was used however this renews every page reload, so a user with an application crash would be reporting a different `sid` to the one which experienced the crash.
closes #6843
Very low risk.
* Check user ID is presented in the "Debug" section in settings, next to feature flags (non-local envs only)
* Check a new user ID is generated when totally clearing the cache (e.g via incognito mode)
* Check any errors you experience are available in sentry by searching `user.id:your-user-id-here`, in the sentry "Discover" …
> chore: attach unique user id for sentry support assistance

- packages/chain-adapters/src/types.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
hotfix: utxo thorchain vault address validation
> chore: hotfix release v1.623.0

- src/assets/translations/en/main.json
Updates the copy shown when no claims are available to make the action intent more clear.
Closes https://github.com/shapeshift/web/issues/7218
Very low.
None.
When connected to a wallet with no claims available ensure the button shows as expected with "Unstake To Claim FOX" (see screenshot below).
☝️
☝️
> chore: unstake copy change

- src/pages/RFOX/components/Claim/ClaimRow.tsx
Fixes the claim cooldown text spacing issue by only showing it outside the tooltip when rendered inside the "Claims" component.
Closes https://github.com/shapeshift/web/issues/7219
Small
None
See screenshot below.
- Claim status should be shown in the Claim tab, with the cooldown shown as a tooltip
- Claim cooldown should be shown in the Claims component
☝️
☝️
> fix: claim cooldown spacing

- src/pages/ConnectWallet/ConnectWallet.tsx
- Fixed the very small mobile language selector going over the text, it might add a scroll bar but on very small mobile I feel like it's a nice trade off and the scrollbar isn't so big
- Also changed the margin of the login component
closes #7062
Low risk
- Inspect and open the homepage with a really small mobile view like `iPhone SE`, the lang selector should not be over the text anymore
- The margin of the login component should be equal from left to right
n/a
n/a
> fix: language selector on very small mobiles and homepage margin

- src/pages/RFOX/hooks/useCurrentEpochRewardsQuery.ts
- src/pages/RFOX/hooks/useLifetimeRewardsQuery.ts
- src/react-queries/helpers.ts
Refactors rFOX hooks (where required) to consume other queries using `useQueries` along with `combine` to ensure the result is reactive and will respond to changes upstream where appropriate. Refer to #7171 to details of the issue.
closes #7171
Low risk, actually fixes a theoretical issue where the data fetch by these hooks would no trigger when upstream dependencies change.
Not possible without a monkey path or several days staring at the page (see below) - engineers please sanity check as you see fit.
Only affects `useCurrentEpochRewardsQuery` which fetches the current rewards for the user. Ensure the current rewards are appearing correctly, and that staking …
> chore: refactor rFOX hooks to consume reactive queries appropriately

- src/assets/translations/en/main.json
- src/components/Acknowledgement/Acknowledgement.tsx
- src/pages/RFOX/components/Stake/StakeInput.tsx
Improves the rFOX bridging acknowledgement by replacing "I understand" with "Yes", which makes more sense in the context on the warning.
Also adds (and uses) an `InfoAcknowledgement` component, which has a yellow (instead of red) icon, and a blue button.
Production:
This PR:
None - fast-follow rFOX stuff.
Small
None.
Ensure `InfoAcknowledgement` shows as expected (as per the screenshot above) when bridging in the rFOX flow).
☝️
☝️
See above.
> feat: infoAcknowledgement for rFOX bridge

- src/pages/RFOX/hooks/useEpochHistoryQuery.ts
Adds simple logic to ensure that #7224 does not result in a production issue if it doesn't get actioned exactly on time for any reason.
The logic is as follows:
* If we are testing rFOX staking prior to `2024-07-01T00:00:00Z`, we us the start of the current month for the first epoch start date.
* If we are post-launch, the application will use the real start date of `2024-07-01T00:00:00Z`
This allow us to to be as late as we want in actioning #7224 without consequences.
realtes to #7224
Low risk, in fact it reduces risk of the current implementation.
Engineers test this with a monkey patch.
> chore: de-risk RFOX_FIRST_EPOCH_START_TIMESTAMP todo

- src/assets/translations/en/main.json
- src/components/Acknowledgement/Acknowledgement.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
The time was displayed using seconds, we know use a human readable sentence
n/a
Low risk
n/a
n/a
> feat: make time of streaming acknowledgement human readable

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Fixes a recent regression (possibly from https://github.com/shapeshift/web/pull/7246) where we no longer gracefully handle switching to fiat input before a value has been entered (i.e. when the crypto and fiat values are `undefined`.
The only place this seems to have an impact is the LP add liquidity component, which has been fixed in this PR.
Closes https://github.com/shapeshift/web/issues/7266
Small.
LP quote input.
Ensure that when selecting a fiat amount on initial LP quote component load we get 0 instead of N/A for the crypto amount.
See the ticket that this closes for the sad case.
☝️
☝️
We now load with an actual value pre-filled (0) instead of a placeholder resulting from an `undefined` …
> fix: undefined LP input

- src/lib/utils/index.ts
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Fixes this issue in the current release (and prod, so not a regression) found by @MBMaria: https://jam.dev/c/2fae7632-7e26-40a5-b271-8f1a6805dcd1, where the crypto amount gets set to `NAN` on asset change due to the `cryptoAmount` being set to an empty string `''` on asset change.
N/A, noted in current release thread: https://discord.com/channels/554694662431178782/1257135461030170669/1257148185231491192
Small
LP deposit input amounts.
See the jam and ensure the flow doesn't result in a `NAN` showing.
1. Select fiat input
2. Change asset
3. Ensure `0` crypto amount is shown
☝️
☝️
N/A
> fix: empty string LP input

- src/pages/RFOX/hooks/useEpochHistoryQuery.ts
Removes the temporary hack to make rFOX reward calculation work for testing prior to rFOX launch.
closes #7224
Low risk as this should have zero impact on calculations.
Ensure lifetime rewards on rFOX dashboard are identical to production.
> chore: cleanup rfox epoch start timestamp

- src/components/Modals/Send/views/Details.tsx
- src/components/MultiHopTrade/components/TradeAmountInput.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
Sometime we still send an empty string to the `Amount` component, resulting to a display of NaN instead of a proper number. Identified a few parts by searching: 
- Inside the Send modal thanks to https://github.com/shapeshift/web/issues/7266#issuecomment-2205014022
- Inside the swapper crypto value
- Inside the slippage of the withdraw component of the THORChain savers
closes #7266
Low risk
- Go to the Send modal, switch the value to USD and see that the value of the crypto component is not NaN anymore but 0
- Go to the swapper, remove the 0, switch to USD value, see that the crypto value is !== than NaN
- Go to any thorchain savers, click withdraw, wait for the slippage to display, its not NaN anymore
n/a
n/a
Notice the `NaN ETH`
Notice the `NaN ATOM`
Notice the `NaN USDC`
> fix: handle crypto and fiat amounts properly instead of displaying NaN

- scripts/generateAssetData/generateRelatedAssetIndex/generateRelatedAssetIndex.ts
Fixes related asset indexes generation, currently `require()`ing `generatedAssetData.json`.
However, as we already require it before in the lifecycle of this script, the current `require()` will yield an older, cached version (before regenerating assets data), 
effectively overwriting the newly-generated asset data with its old version, producing no diff.
closes N/A
Low - run asset generation and ensure we are still happy - can't break what's already borked
- `yarn generate:asset-data` is happy
- ^
- ^
> fix: two hard things in software engineering

- src/components/MultiHopTrade/MultiHopTrade.tsx
Fixes major state corruption due to quote polling during trade execution. Solved by unmounting the `useGetTradeQuotes` hook for trade UI routes that dont require quote polling.
closes #7347
Moderate risk of this introducing a new issue which could break trades, though the fix here is very obvious and greatly reduces the impact to users.
The key to reproducing this issue is to be fast at previewing the quote, and slow at confirming it.
1. Get a trade quote on metamask wallet
2. Immediately click "preview trade" with no wait
3. click "confirm" and click "sign transaction"
4. In metamask, dont actually sign the transaction, and instead wait.
5. Quote polling will …
> fix: corrupted trade execution state due to incoming quotes during trade execution

- src/config.ts
Disables the `REACT_APP_FEATURE_RFOX_MOCK_REWARDS_TX_HISTORY` feature flag added in https://github.com/shapeshift/web/pull/7308 as it breaks the ability to fetch TX history app-wide.
N/A - production issue.
Small
TX history.
TX should load. Easiest way to test this is to clear TX history cache and see it re-fetch.
☝️
☝️
N/A
> fix: tx history

- src/plugins/walletConnectToDapps/components/modals/connect/Connect.tsx
The parent modal cross was under the dialog header of the qr scanner dialog component, by adding a zIndex 1 to it, it will be over because it's older in the tree
closes #7334
Low risk
Try to scan a QR code to connect with wallet connect on mobile, then hit the close cross, it should work
n/a
n/a
https://jam.dev/c/c2e4b25f-f1d0-409e-90ef-f89a6d7bf9f6
> fix: modal cross deadclick on wallet connect mobile scan

- src/components/Modals/Settings/ClearCache.tsx
- src/context/WalletProvider/WalletProvider.tsx
I'm not so used to the complexity of the WalletProvider for now but as the state is cleared when the cache is cleared, it's not anymore set to "mobile", meaning that `load` will be rerun because of an effect contained in `WalletProvider` but with `localWalletType` !== than `mobile`, and so the password prompt will be shown
By disconnecting the wallet before, we ensure that the user won't trigger this load effect and ensure he will need to connect the wallet again
closes #7333
Low
- You can test on `gome` using the mobile app, selecting the `gome` environment
- Try to clear the cache, you shouldn't be prompted to enter a password
n/a
n/a
> fix: disconnect wallet before clearing cache on mobile to avoid pw prompt

- src/components/Modals/Nfts/components/NftCollection.tsx
- src/components/Modals/Nfts/components/NftOverview.tsx
Sanitize hyperlinks in nft descriptions.
N/A
Low
See screen shot. I just hacked an example in place locally to prove it out. You can see the same component being used for asset descriptions (ex. Bitcoin) to view the sanitized links yourself elsewhere.
:point_up:
:point_up:
> fix: sanitize nft descriptions of hyperlinks

- src/components/ClaimRow/ClaimRow.tsx
- src/pages/RFOX/components/Claim/ClaimRow.tsx
- src/pages/RFOX/components/RewardsAndClaims/Claims.tsx
Fixes a regression where we a hover state is rendered on available claims with no click handler, resulting in dead click (when clicked).
NA
Low risk.
* Check pending claims are not clickable
* Check available claims on the main dashboard list are not clickable
* Check claim flow on right widget works the same as prod
https://github.com/user-attachments/assets/20d10f4a-7702-4ff6-ba93-37c5b35fddda
> fix: dont show render hover state for avilable claim rows with no click handler

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/ManualAddressEntry.tsx
Fixes no account copy.
Closes https://github.com/shapeshift/web/issues/7487
Very low
None.
When connected to a wallet that is missing an account that is not MetaMask:
When connected to a wallet that _is_ MetaMask with snaps available:
☝️
☝️
See above.
> fix: no account copy

- src/components/AssetSelection/components/AssetMenuButton.tsx
Fixes regression in https://github.com/shapeshift/web/pull/7491 causing asset symbols to always truncate.
**Production**
**This PR**
Closes https://github.com/shapeshift/web/issues/7499
Small
None.
Ensure the asset symbols on the trade component only truncate when necessary even by zooming to 67% or 110% or any other zoom level
☝️
☝️
See above.
> fix: symbol truncation regression

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversEmpty.tsx
On light mode, the runepool checkbox was hard to see, I changed its background to white on light mode and kept transparent on dark mode
No issue
Open the runepool overview page if you don't have any liquidity in it and look at the checkbox using both light and dark mode, checked and not checked
n/a
n/a
Before
After
> fix: runepool checkbox visibility using light mode

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowanceApproval.tsx
- src/hooks/queries/useApprovalFees.ts
Fixes an regression in https://github.com/shapeshift/web/pull/7392 that prevented us from signing approvals/resets on Ledger devices.
The new `useEvmFees` hook was periodically firing the `evmFees` query which hijacked the Ledger adapter's call to `adapter.signTransaction` whilst we were waiting for the user to confirm the TX on their Ledger.
This PR disables the offending query once the signing request has been initiated so no more calls are made to the adapter until the transaction is signed.
Closes https://github.com/shapeshift/web/issues/7537
Medium - relates to fees and signing.
Signing approvals and resets with a Ledger.
- With a Ledger connected ensure that both resets and approvals …
> fix: ledger approval signing

- src/components/Modals/Send/views/Address.tsx
- src/components/Modals/Send/views/Details.tsx
This is impossible to click on the cancel button using the QRCode modal
Previously we were using the `send` modal context, but we are actually using the `qrCode` modal context, we should execute both depending on the context
closes #7511
Low
- Use the QR code button in the wallet page
- Scan a QR code 
- Click the cancel button, the modal should close
n/a
n/a
See the issue, do the same process! I don't have access to jam on the browser I'm testing the QR code scan... 🙏
> fix: deadclick on qrcode modal

- src/components/ChainMenu.tsx
Since we migrated our AssetIcon to be LazyLoaded, we have some places where icons are not really well size-adapted
The network icon is one of these places, I basically changed some properties to use the properties we usually use to size the icon, boxSize is prefered over width with a height: auto for this place
No issue, discovered it while fixing another thing
Very low
n/a
n/a
After
Before
> fix: network icon size

- .env.app
- .env.private
hotfix: failover to dev thorchain endpoints in prod
> chore: hotfix release v1.660.0

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Footer.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hops.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StreamingSwap.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useThorStreamingProgress.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/state/slices/tradeQuoteSlice/constants.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/state/slices/tradeQuoteSlice/types.ts
- src/test/mocks/store.ts
This PR updates the `tradeExecution` state in the `tradeQuoteSlice` to be keyed by the trade id (`Record<TradeQuote['id'], TradeExecutionMetadata>`).
All components in the context of a confirmed trade now use the `id` of the confirmed trade ensuring there is no state corruption in the UI during the execution flow.
This PR lays the groundwork, though does not implement, the ability to resume a multi-hop trade, view past trades (so long as the Redux slice state persists, at least) etc
Closes https://github.com/shapeshift/web/issues/7161
High - touches the `tradeQuoteSlice` which directly affects the swapping flow.
All trades.
- Swaps should work as expected …
> fix: swapper state corruption

- src/assets/translations/en/main.json
- src/pages/TransactionHistory/DownloadButton.tsx
Fixes the incorrect output address appearing in the CSV export. 
Also adds label for `transactionRow.parser.thorchain.swap` as `Trade` to match rest of the swaps in the export.
closes #7260
Low risk. No risk to user funds.
Specifically to the issue reported:
- Check `trades` have the same input and output address (unless a manual receive address was used)
- Check `sends` show the wallet address as the input address, and show the destination wallet address as the output address
- Check `receives` show the senders wallet address as the input address, and show the wallet address as the output address
Also check that thorchain swaps are labelled as `Trade` …
> fix: use correct address in outputAddress in csv export

- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Fixes an issue where the "is fiat" state was not in sync between RUNE aysm input and the asset asym and sym inputs.
Closes https://github.com/shapeshift/web/issues/7433
Low
LP input.
Confirm that the behaviour in this video is no longer occurring (input state should stay in sync):
https://github.com/user-attachments/assets/17ece723-35e9-453c-87bc-518360722ba2
☝️
☝️
N/A
> fix: lp fiat toggle

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/helpers.ts
- src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
- src/features/defi/providers/univ2/hooks/useUniV2LiquidityPool.ts
- src/hooks/mutations/useApprove.ts
- src/hooks/queries/useApprovalFees.ts
- src/hooks/queries/useEvmFees.ts
- src/lib/utils/evm/index.ts
- src/pages/RFOX/components/ChangeAddress/ChangeAddressConfirm.tsx
- src/pages/RFOX/components/ChangeAddress/ChangeAddressInput.tsx
- src/pages/RFOX/components/Claim/ClaimConfirm.tsx
- src/pages/RFOX/components/Stake/Bridge/hooks/useRfoxBridgeApproval.tsx
- src/pages/RFOX/components/Stake/hooks/useRfoxStake.tsx
- src/pages/RFOX/components/Unstake/hooks/useRfoxUnstake.tsx
- src/react-queries/queries/common.ts
Ensures pubKey gets passed to `adapter.getAddress()`, so that Ledger signing is still borked, but borked correctly.
Read: Things will now be happy up to signing time and won't get rugged earlier at fees estimation time, meaning we now have the groundwork ready to properly add Ledger "Open App" gate at signing time.
- closes https://github.com/shapeshift/web/issues/7567
- closes https://github.com/shapeshift/web/issues/7575
Low/Medium - this should only affect fees estimation for Ledger and be a no-op diff for all others.
**Test the below with a Ledger connected, but without the relevant app open (i.e for the sake of simplicity, don't have any app open)
- …
> feat: don't derive address on-device when estimating Ledger fees

- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
Does what it says on the box - consistently displays a warning when bridging into a token.
closes https://github.com/shapeshift/web/issues/7282
None
- When *bridging* into a token, `Make sure you have <native asset> in your <chain> account, you’ll need it for transactions` is displayed at quote time
- For all other quotes, this warning is not displayed
- ^
- ^
- Same chain native asset -> token
- Same chain token -> native asset
- Native asset -> token bridge
- Token -> token bridge
- Native asset -> native asset bridge
> feat: swapper generalize native asset required warnings

- src/pages/RFOX/components/ChangeAddress/ChangeAddressConfirm.tsx
- src/pages/RFOX/components/Claim/ClaimConfirm.tsx
- src/pages/RFOX/components/Overview/Overview.tsx
- src/pages/RFOX/components/Overview/StakingInfo.tsx
- src/pages/RFOX/components/Stake/Bridge/BridgeConfirm.tsx
- src/pages/RFOX/components/Stake/Bridge/BridgeStatus.tsx
- src/pages/RFOX/components/Stake/StakeConfirm.tsx
- src/pages/RFOX/components/Unstake/UnstakeConfirm.tsx
When signing briding, stack, unstake, claim and changing address using rFOX, if you don't have the ledger app enabled, the ledger ACK flow should be opening.
Also, if you didn't add the arbitrum chain, every informations should be zeroed out instead of having an infinit loading
I also noticed that `Unstake` and `Change address` are loading if the chain is not supported, it was not included in the initial ticket and would require another decision, happy to fix it in a follow up if it's really needed (users should have understand that the chain is not supported at this point considering the fact that the default view is `Stake` telling it)
closes #7374
For …
> feat: use ledger ack for every rfox action and avoid infinit skeletons

- src/components/DonutChart/DonutChart.tsx
- src/pages/Lending/components/LendingHeader.tsx
Fixes the lending donut, which in production currently uses mock data.
Closes https://github.com/shapeshift/web/issues/7591
Small
None
Ensure that the lending donut now correctly reflects the collateral to debt ratio of lending positions.
☝️
☝️
Production:
This PR:
> fix: lending donut

- src/pages/RFOX/components/Claim/ClaimSelect.tsx
Adds keys to the `Skeleton` components in the `ClaimSelect` component for best practice and to avoid log spew.
N/A
Very small.
None.
Check the console when selecting the claims tab on the rFOX route, we should no longer see the above warning.
☝️
☝️
See above.
> fix: claim skeleton keys

- .github/PULL_REQUEST_TEMPLATE.md
Proposing we remove the "Pull Request Type" template from the PR template, as it's redundant: we already specify the PR type in the PR title (chore, perf, feat, etc).
N/A - quality of life.
Tiny.
None.
None.
N/A
N/A
N/A
> chore: remove PR type section from template

- package.json
- src/components/Graph/MaxPrice.tsx
- src/components/Graph/MinPrice.tsx
- yarn.lock
Removes an unnecessary dependency, `@react-spring/web`.
The `MinPrice` and `MaxPrice` components don't need animation on the y coordinate text baseline, as they don't actually move.
N/A, raised by @woodenfurniture in https://github.com/shapeshift/web/pull/7582#pullrequestreview-2252187061.
Low
None.
Navigate to the wallet page, change between time spans on the balance chart, and confirm that the Min and Max text looks sane.
☝️
☝️
> perf: remove unnecessary dep

- src/state/apis/zapper/validators.ts
- src/state/apis/zapper/zapperApi.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
Fixes zod types for the `https://api.zapper.xyz/v2/balances/apps?addresses` endpoint.
Token decimals can be either a `string` or a `number` in the response data.
N/A
Small
None.
When loading the "Earn" page we should no longer get the above zod type error.
☝️
☝️
See above.
> fix: zapper zod types

- src/pages/Lending/Pool/components/LoanSummary.tsx
Fixes a bug where we are passing an unrecognised prop, `collateralDecreaseAmountCryptoPrecision`, to a DOM element.
N/A
Very small.
None.
Console warning should no longer show when opening a lending position.
☝️
☝️
See above.
> fix: unrecognised collateralDecreaseAmountCryptoPrecision

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Status.tsx
Since we did switch to PairIcons, there are a few bugs showing up
This one is about the asset icon when depositing to savers, we need to center it through the circle progress component
closes #7577
Low
Try to deposit in a thorchain saver and see if the asset icon is right placed in the circle process loader
n/a
n/a
> fix: wrong icon position when depositing to savers

- src/components/FeeModal/FeeModal.tsx
Fixes the dead click on the fee explainer close modal, likely caused by the Chakra package bump due to our incorrect usage (or lack thereof) of `<ModalBody>.
Closes https://github.com/shapeshift/web/issues/7610
Low
None
Ensure that the fee explainer can be closed using the close button (not just clicking the background).
☝️
☝️
See above.
> fix: fee explainer modal close button

- src/pages/RFOX/components/Stake/StakeInput.tsx
As a follow-up (and inspired by) to https://github.com/shapeshift/web/pull/7600, this PR ensures we show the `<ChainNotSupported />` component when connected to a wallet that does not support arbitrum.
This PR:
`develop`:
When attempting to stake FOX on Arbitrum without an Arbitrum account connected:
When attempting to stake FOX on Ethereum without an Arbitrum account connected (the bridge can never complete because there is no account to sign or pay gas on Arbitrum):
Follow-up of https://github.com/shapeshift/web/pull/7600
Small
rFOX staking.
- Ensure that rFOX staking works as it does in production when an Arbitrum account _is_ connected.
- Ensure that the `<ChainNotSupported />` …
> chore: show chain not supported on rFOX claim

- src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
- src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Approve.tsx
- src/features/defi/providers/univ2/hooks/useUniV2LiquidityPool.ts
- src/lib/utils/thorchain/hooks/useSendThorTx.tsx
- src/plugins/cosmos/hooks/useStakingAction/useStakingAction.tsx
This PR implements Ledger over all DeFi section signing actions.
closes https://github.com/shapeshift/web/issues/7579
Low to none
- Ensure all signing actions across the DeFi section (deposit, withdraw, claim) are properly guarded by the Ledger Open App gate, i.e pop up a modal to open the relevant Ledger app if no/wrong app is opened
- Test this over:
- ETH/FOX (UNI-V2)
- FOX Farming
- FOXy
- THORChain savers
- Cosmos SDK
- ^
- ^
- UNI-V2
- FOX Farming
- FOXy
- THORChain Savers
- Cosmos SDK
> feat: defi section ledger open app gate

- src/components/Modals/LedgerOpenApp/hooks/useLedgerAppDetails.tsx
- src/hooks/useLedgerOpenApp/useLedgerOpenApp.tsx
Pushes a prompt to the ledger device to open the correct app, allowing them to confirm and have it open immediately without having to navigate to it on the device. This is the same behavior we see in ledger live.
The user must be on the home page on the device for this prompt to appear.
relates to #6814
Low risk. If the request fails the device ignores the prompt.
When getting prompted to "Open the XYZ App" on ledger, check the device displays the same notification on the device.
The user must be on the home page on the device for this prompt to appear.
This should work when:
- managing accounts
- verifying addresses
- signing transactions
> feat: prompt user to open ledger app on device with single click

- src/features/defi/providers/cosmos/components/CosmosManager/Overview/WithdrawCard.tsx
Fix filtering of undelegations to ensure utc seconds are compared against utc seconds.
closes https://github.com/shapeshift/web/issues/7608
Low
- Make sure you have a pending undelegation and ensure it is shown in the cosmos staking position overview
:point_up:
:point_up:
> fix: show cosmos pending undelegation

- src/components/MultiHopTrade/components/TradeInput/components/Claim/ClaimConfirm.tsx
Does what it says on the box, see screenshots
N/A, spotted in Arb flag toggle PR i.e https://github.com/shapeshift/web/pull/7637#pullrequestreview-2266232738
None - previous branch is still here.
Though I've spotted that `convertPrecision` loses precision while implementing this, so if we ever hit the very edge case of an asset having different precision in its Ethereum Mainnet and Arbitrum One, with a smol withdraw, then the bug would still be here... but this branch will realistically never be hit.
- Have a smol Arbitrum Bridge withdraw available (or eng. test with the monkey patch below)
- Ensure it doesn't show up as 0 in confirm step
- Test with the …
> fix: arbitrum bridge confirm precision loss

- src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Status.tsx
- src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Status.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Status.tsx
- src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
I fixed this bug for THORChain deposits but I noticed it was everywhere in the earn section (foxy, cosmos and thorchain savers...)
The asset icon was not centered in the loader
The actual bug: https://jam.dev/c/db8d6aee-40ee-44e6-a55d-4aef9116c7c7
No issue
Low risk
Mainly for Cosmos, FOXy and THORChain savers:
- Try to deposit, the asset icon should be centered properly
- Try to withdraw, the asset icon should be centered properly
n/a
n/a
https://jam.dev/c/23628c9f-2160-4337-87eb-255d21ff0cc2
> fix: icon alignment in earn withdraw and deposit statuses

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/context/AppProvider/AppContext.tsx
- src/pages/RFOX/components/Stake/StakeInput.tsx
- src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap
- src/state/slices/portfolioSlice/portfolioSlice.ts
- src/state/slices/portfolioSlice/portfolioSliceCommon.ts
- src/state/slices/portfolioSlice/selectors.ts
- src/test/mocks/store.ts
- I added a prop to the portfolio slice: `isAccountLoading`
- This prop is turned to true at the start of the account discovery effect, then turned false when it ends
- Consumed it in the swapper and rfox to disable the button and adapt the text if we are actually running account discovery
closes #7419
Let's say high risk because swapper button is disabled in case this is buggy
- Go to Swapper (and rFOX)
- Clear you chrome cache manually and refresh the page
- Import a native wallet
- check the button of the swapper and stake component of rFOX, it should be disabled and showing `Loading Accounts`
n/a
n/a
rFOX …
> feat: handle accounts loading gracefully

- src/components/RelatedAssets/RelatedAssets.tsx
- src/state/slices/related-assets-selectors.ts
Filters out related assets that we don't have in our asset store, fixing the render of `null` table rows.
Closes https://github.com/shapeshift/web/issues/7432
Small
None
Ensure that he related asset section no longer has empty rows (Ethereum is a good asset to use for testing).
☝️
☝️
N/A
> fix: empty related assets

- src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
- src/components/Modals/Send/utils.ts
- src/components/Sweep.tsx
- src/lib/utils/thorchain/hooks/useSendThorTx.tsx
- src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
- src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Does precisely what you'd expect it to do based on its box content, minus deposit/withdraw execution bits (implemented in `useSendThorTx` as part of https://github.com/shapeshift/web/pull/7628)
closes https://github.com/shapeshift/web/issues/7580
- THORChain LP approval displays the Ledger Open App ack
- THORChain LP deposit displays the Ledger Open App ack
- THORChain LP withdraw displays the Ledger Open App ack
- ^
- ^
- Approve
- Add Liquidity
- Remove Liquidity
> feat: thorchain lp ledger open app ack

- src/lib/utils/thorchain/hooks/useSendThorTx.tsx
- src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
Fixes the case where there *is* a RUNE position address for a withdraw (i.e, it's a sym position), but no RUNE account in the portfolio (i.e, withdrawing asymmetrically on the asset side, while having accounts for the asset connected)
closes https://github.com/shapeshift/web/issues/7634
Low to none
Ensure asym asset withdraws of a sym position correctly guard against RUNE chain not supported
- ^
- ^
> fix: thorchain LP sym withdraw RUNE support detection

- packages/swapper/src/swappers/ThorchainSwapper/utils/getL1quote.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getQuote/getQuote.ts
- packages/utils/src/basisPoints.ts
- packages/utils/src/bignumber/bignumber.test.ts
- packages/utils/src/bignumber/bignumber.ts
- src/lib/bignumber/bignumber.test.ts
- src/lib/bignumber/bignumber.ts
- src/state/apis/swapper/helpers/validateTradeQuote.ts
- src/state/slices/tradeQuoteSlice/utils.test.ts
Removes some spotted useless utils:
N/A
Low
- proceed to a paranoia test of bps and quote amounts and ensure things still look good amounts-wise: no extra 0s or super low precision
- ^
- ^
> feat: lib utils cleanup

- packages/swapper/src/swappers/PortalsSwapper/getPortalsTradeQuote/getPortalsTradeQuote.ts
Ensures Portals fees are denominated in sellAsset, vs. buyAsset previously.
closes https://github.com/shapeshift/web/issues/7651
Low
- Portals protocol fees look sane (and mostly on par with other swappers for non-LP pairs, since they use 0x and the like under the hood for these)
- ^
- ^
- develop
- this diff
> fix: portals fees denominated in wrong asset

- packages/swapper/src/constants.ts
- packages/swapper/src/swappers/PortalsSwapper/getPortalsTradeQuote/getPortalsTradeQuote.ts
- packages/swapper/src/swappers/PortalsSwapper/utils/fetchPortalsTradeOrder.ts
- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/components/MultiHopTrade/components/TradeInput/components/MaxSlippage.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
Use Portals auto-slippage by omitting the `slippageTolerancePercentage` param from the request.
Portals will then find the best route with the optimal slippage (up to 2.5%), and return that value - we then consume that value in our quote for execution.
Note, this still allows for manual override via the slippage popover.
In the below image we see that the auto slippage provided by Portals in the quote response for this trade is 1.04%, which we then populate in the UI.
Partially addresses https://github.com/shapeshift/web/issues/7650 by using automated slippage for quotes that can be validated.
Medium
- Portals swap quotes and execution
- Slippage …
> feat: use portals auto slippage

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
Fixes a regression introduced in https://github.com/shapeshift/web/pull/7697/files#diff-ae33f6e4021508ebc3b64c4a8885e8ab7332e8ef8fda4b21ed5bc1961db38e88 - we absolutely do not want to `ethSwitchChain()` on every getAddress() calls, as `subscribeTxs()` and a few other places will call it with various chainIds.
closes https://github.com/shapeshift/web/issues/7718
None, reverts offending line to previous behaviour.
- Connect to MM
- Ensure you can actually use the app without infinite switch chain MM popups.
- ^
- ^
- develop
jam.dev/c/59860845-5b28-4185-a792-56b540a07156
- This diff
https://jam.dev/c/aad4c72a-b1f5-4c4b-882a-a26f55f1db9d
> fix: mm infinite switch chain loop

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- src/assets/translations/en/main.json
- src/components/Modals/QrCode/Form.tsx
- src/components/Modals/Send/Form.tsx
- src/components/Modals/Send/SendCommon.tsx
- src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
- src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
- src/components/Modals/Send/views/Details.tsx
- src/components/Modals/Send/views/Status.tsx
- src/pages/RFOX/components/Shared/SharedStatus.tsx
Does what it says on the box - adds a new status step in send modal, following the status UX across the app, and preparing for SAFE status detection in sends.
closes https://github.com/shapeshift/web/issues/7696
Medium - both send and QR modal could be borked, test accordingly
- In send modal, the new status step is happy with status detection working 
- In QR code modal, the new status step is happy with status detection working 
- ^
- ^
- Send Modal
https://jam.dev/c/67262476-c922-473d-ade4-3a1d52ba933a
- QR code modal 
https://jam.dev/c/14ce90aa-7256-4741-867c-410088cab4ee
> feat: send modal status step

- src/assets/translations/en/main.json
- src/components/Modals/Snaps/SnapConfirm.tsx
- src/hooks/useIsSnapInstalled/useIsSnapInstalled.tsx
- src/utils/snaps.ts
As it turns out, we *can* do this, but the snap adapter itself is borked, as it early returns if the snap is already installed:
Decided *not* to go with updating checks there, and rather implement the JSON-RPC call in web, as this is where such methods should live (or in hdwallet/chain-adapters) anyway.
N/A, though relates to the closed https://github.com/shapeshift/web/issues/7725
Low
- Install the old version of the snap (eng., this can be done by monkey patching `snapVersion` to `1.0.0` in `enableShapeShiftSnap` and installing the snap (don't forget to revert this change and refresh the page before continuing here): …
> feat: single click MM update CTA

- src/components/EarnDashboard/components/ProviderDetails/OpportunityRow.tsx
Fast-follow of https://github.com/shapeshift/web/pull/7678, which borked onClick handlers for natively supported DeFi opportunities:
https://jam.dev/c/44cff944-f6df-488b-804d-09cb6a2e10d9
closes N/A
Low, immediate fix of an introduced bug
- Natively supported DeFi opportunities are clickable and route to the correct place
- Frankenstein opportunities (read: technically read-only as we don't have first-class DeFi modal for them, but we actually support them in Portals) route to swapper
- RFOX still route to RFOX page
- Actual read-only opportunities if held (e.g Idle) route to dApp page
- ^
- ^
https://jam.dev/c/85a2e92c-6e9c-491c-b35f-f622e464da16
> fix: onClick borked in non-read only DeFi opportunities

- package.json
- yarn.lock
Removes `express` as an explicit import.
Inspired by https://github.com/shapeshift/web/pull/7726, noticed we don't actually need this package to be explicitly imported, it's already a peer dependency of `webpack-dev-server`.
N/A - maintenance
Small.
In theory, none.
The app should should build and have no regressions.
☝️
☝️
N/A
> chore: remove express dep

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ManualAddressEntry.tsx
- src/components/MultiHopTrade/components/TradeInput/components/RecipientAddress.tsx
- src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeInputBody.tsx
- Added some loaders while loading accounts on both inputs and invert assets
- Added a loader in the button of the swapper while loading accounts so it attracts user's eyes to the button, attracting them to read the text
- Brang down the `isAccountsMetadataLoading` one level deeper in `ManualAddressEntry` because there is a world where the component is lazyloaded but accounts are loading afterwhile (see issue's case)
closes #7740
High because swapper but medium regarding the scope
- Go on the swapper using a native wallet or any big account
- Clear your cache
- Connect again to the wallet
- Look at the gracefully handled accounts loading flow
n/a
n/a …
> fix: gracefully handle swapper account loading

- src/lib/utils/thorchain/lending.ts
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
- src/pages/Lending/hooks/useLendingSupportedAssets/index.ts
Does precisely what it says on the box.
NOTE: While this fixes displaying positions, repays still can't be done because of close endpoint shenanigans: https://discord.com/channels/838986635756044328/1283906886051172427/1284230662517424254
closes N/A
Low - ensure "Available Pools" is still displaying no pools
- "Available Pools" is still empty
- With a frame (or rather, Rabby watch-only address as Frame MM injection is currently borked following upstream changes) and a known borrower from the borrowers endpoint (https://paw.pt/i39K7GP3), lending positions are displayed
- ^
- ^
- develop
- this diff
> fix: display lending positions post-hardfork shenanigans

- src/lib/utils/thorchain/lending.ts
- src/pages/Lending/YourLoans.tsx
- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
- src/pages/Lending/hooks/useLendingSupportedAssets/index.ts
fix: display lending positions post-hardfork shenanigans (#7747)
> chore: release v1.678.0

- src/components/AccountCard.tsx
Fixes text overflow of asset label in send input.
Adds a ellipsis for overflow with tooltip.'
Opted to use `trimWithEndEllipsis` intead of CSS ellipsis so we can predictably and simly detect an overflow render the tooltip accordingly.
closes #7720
Low risk - display concern only.
Check normal length asset names are rendered correctly without a tooltip.
Check very long asset names are truncated with an ellipsis and have a tooltip with the full asset name.
https://github.com/user-attachments/assets/02d9119a-5301-42a4-b0d8-33bf28a15cc8
> fix: handle long asset names in send input

- .github/workflows/cloudflare.yml
- .github/workflows/pr.yml
- package.json
- yarn.lock
Force `react-scripts` to use the same version of `workbox-webpack-plugin` to ensure we can properly override the `maximumFileSizeToCacheInBytes` config on the `InjectManifest`
N/A
N/A
- See: https://github.com/shapeshift/web/actions/runs/10907989420/job/30273267091#step:13:1157
:point_up:
N/A
> fix: broken build post webpack upgrade

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/RecipientAddress.tsx
closes https://github.com/shapeshift/web/issues/7779
Low to none
- BTC taproot (bc1p-prefix addresses) custom receive addresses are disabled for THOR Swapper
- Other custom receive addresses (e.g SegWit native bc1q-prefixed addies) are happy
- ^
- ^
- bc1p
- bc1q
> feat: disable taproot custom receive addresses in swapper

- src/pages/Lending/hooks/useAllLendingPositionsData.tsx
Properly handles no loan state.
`develop`:
This PR:
This change is needed as we can still have `data` on a position without an actual loan:
N/A, discovered by @gomesalexandre in a recent review: https://github.com/shapeshift/web/pull/7753#pullrequestreview-2306156963
Low
None
- When connected to a wallet with no loans, the placeholder component is shown as in the screenshot above.
- When connect to w wallet with loans, the loans are still shown
☝️
☝️
See above.
> fix: empty loan state

- src/assets/translations/en/main.json
- src/components/AssetHeader/AssetHeader.tsx
- src/components/AssetHeader/WatchAssetButton.tsx
- src/components/TabMenu/MenuTab.tsx
- src/pages/Markets/MarketsHeader.tsx
- src/pages/Markets/MarketsPage.tsx
- src/pages/Markets/Watchlist.tsx
- src/pages/Markets/components/AssetCard.tsx
- src/pages/Markets/components/AssetsGrid.tsx
- src/pages/Markets/components/CardWithSparkline.tsx
- src/pages/Markets/components/LpCard.tsx
- src/pages/Markets/components/LpGrid.tsx
- src/pages/Markets/components/MarketsRow.tsx
- src/state/slices/preferencesSlice/preferencesSlice.ts
Adds watchlist tab / icon to the markets page.
closes https://github.com/shapeshift/web/issues/7685
Low
- Asset page on desktop now has a star button that adds to watchlist
- Markets Page has a watchlist button in cards
> feat: markets page watchlist

- src/lib/address/address.ts
Updates the `validateAddress` util to return invalid for BTC Taproot addresses.
A stop-gap to improve user experience relating to https://github.com/shapeshift/web/issues/6761 until we decided how to proceed/unblock that ticket.
Relates to https://github.com/shapeshift/web/issues/6761, but does not close it.
Low
BTC sends
Ensure BTC sends to Taproot addresses (e.g. `bc1pxk2u9kjszfzxqmsrcctvst32dn2pqrlptsw0e7wqumhlq9cl35ks9v5kh2` are invalidated):
Ensure no other sends are affected.
☝️
☝️
See above.
> fix: invalidate taproot addresses for sends

- packages/swapper/src/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
Received a heads up from the LiFi team that stargate V1 is being deprecated, and that we should add `stargatev2` if we wish to continue blocking stargate.
Small
LiFi trades
Ensure we do not see any quotes from Stargate via LiFi.
☝️
☝️
N/A
> chore: deny stargateV2

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/state/slices/tradeQuoteSlice/selectors.ts
Resolves state issue in trade UI where lack of non-errored quoted is treated as loading state, resulting in infinite spinner when all swappers failed to return a quote.
closes #7789
Low risk, though considering the massive usage of the swapper feature we should review it with added caution.
Affects quotes and loading state.
The easiest way to test this is by trying to get a quote with assets which are THOR only (e.g UTXOs, or  UTXO<->ATOM would work too), and then blocking the `swap*` domain.
To do so, proceed as follow:
- Try and get a first quote, which should go through
- Then, filter network requests by `thor swap`. You'll notice request/s matching …
> fix: dont display loading state when completed quote request has no results

- package.json
- src/components/Steps.theme.tsx
- src/components/VerticalStepper/VerticalStepper.tsx
- yarn.lock
Bumps `chakra-ui-steps` to fix a bug caused by the previous version of this package using a deprecated version of `framer-motion`.
Note a small visual change from prod due to the library now using an updated version of Chakra.
As an aside, I don't know why we even use this library - we should be able to do the same thing with native Chakra? Not for this PR, but TODO.
Closes https://github.com/shapeshift/web/issues/7843
Small
None.
Click the FOX reward and confirm no crashy.
☝️
☝️
See above.
> fix: bump chakra-ui-steps

- package.json
- react-app-rewired.config.js
- react-app-rewired/index.ts
- yarn.lock
Adds a `yarn analyze` script, which creates a build and uses `webpack-bundle-analyzer` to start a webserver showing bundle size information.
Relates to https://github.com/shapeshift/web/issues/7768
Low
None
- `yarn dev` should work as expected
- `yarn build:web` should work as expected
- `yarn analyze` should build web and then start a local webserver to analyze the bundle
☝️
No ops testing required.
> feat: bundle analyzer

- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
- src/components/MultiHopTrade/components/TwirlyToggle.tsx
Fixes the twirly toggle arrow direction.
Closes https://github.com/shapeshift/web/issues/7804
Low
None
On the trade completion success model the arrow should be pointing down when its closed, and point up when open.
☝️
☝️
> fix: twirly toggle

- src/pages/RFOX/components/ChangeAddress/ChangeAddress.tsx
- src/pages/RFOX/components/Claim/Claim.tsx
- src/pages/RFOX/components/Stake/Stake.tsx
- src/pages/RFOX/components/Unstake/Unstake.tsx
- src/utils/makeSuspenseful.tsx
There was a big content shift on rfox tabs because the makeSuspensful box returns a box with a height of 100vh which is correct for most of our usage but incorrect for rFOX as it's not using on a whole view but on small components parts
I added a parameter to the makeSuspenful function to push custom style to this box and fixed it in every rFOX components
None
Low
- Load the rFOX page directly, you should see the loader shouldn't be too big but the regular widget height
- Also switch to any other tabs and the height should be the same
n/a
n/a
> fix: big content shift on rfox tabs

- src/lib/coingecko/utils.ts
- src/pages/Markets/hooks/useRows.tsx
Narrows down Coingecko categories (i.e all except the two last LP ones) to Coingecko supported ChainIds, which we were missing as a concept. This effectively removes the ghost chain (Arbitrum Nova) from the list. 
closes https://github.com/shapeshift/web/issues/7885
Low
- Coingecko categories chain drop down does not have a ghost option
- THORChain LP and Portals categories chain dropdown is the same as in release
Tested against release (right)
- Coingecko categories
- Portals category
- THORChain LP category
> fix: markets page ghost chains in dropdown

- src/Routes/PrivateRoute.tsx
- src/Routes/Routes.tsx
- src/Routes/RoutesCommon.tsx
- src/pages/Dashboard/Dashboard.tsx
Brings back splash page for trade and wallet routes following https://github.com/shapeshift/web/pull/7848, which went too deep in exposing previously private routes and feels weird for wallet and trade routes, especially for the latter.
closes https://github.com/shapeshift/web/issues/7837
Low - this brings back previous behaviour.
- Connecting to the app root route (i.e release.shapeshift.com if testing this in release or localhost:3000) routes to the splash page
- Disconnecting your wallet from wallet or trade route routes back to the splash page 
- Trying to access `/#/trade` or `/#/wallet` directly routes back to the splash page
- Going to any other …
> feat: bring back splash page

- src/assets/translations/en/main.json
Updates the RUNEPool lockup copy from `90` to `30` days.
Closes https://github.com/shapeshift/web/issues/7884
Small
None
Ensure copy updated as expected.
☝️
☝️
N/A
> chore: update agreeRunePool string

- packages/swapper/src/swappers/PortalsSwapper/types.ts
Removes the duplicated `ArbitrumMainnet` entry in the `PortalsSupportedChainIds` constant, which was causing the chain to appear twice in filters.
Closes https://github.com/shapeshift/web/issues/7890
Small
None
On the markets page ensure that when then filter is selected for the "One click DeFi assets" section that the Arbitrum one chain is only shown once.
☝️
☝️
> fix: remove duplicate arbitrum entry

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- src/App.tsx
- src/assets/translations/en/main.json
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/Claim/Claim.tsx
- src/components/MultiHopTrade/components/TradeInput/components/Claim/ClaimSelect.tsx
- src/components/MultiHopTrade/components/TradeInput/components/Claim/hooks/useArbitrumClaimsByStatus.tsx
- src/components/MultiHopTrade/types.ts
- src/hooks/useBridgeClaimNotification/useBridgeClaimNotification.tsx
Triggers a one-off toast if ready arbitrum claims are detected. Includes changes to trade page routing (necessary for deep redirect) and improvements transition animations (nice to have).
~Additional effort was made to negate reliance on tx history per #7872 (i.e dig up stupid https://www.youtube.com/watch?v=b97zJxKEqAk )~ Nope we cannot do this yet.
closes #7835
Moderate risk, changes to trade page routing should be the main focus when reviewing.
- Can trade without issues
- Can initiate a bridge without issues
- Can claim without issues
- Notification works and button redirects you to the clam page
- Notification only fires once per page load …
> feat: notify users when arbitrum bridge claim is ready

- src/Routes/RoutesCommon.tsx
- Now that we have the markets page we don't need the assets page. Its only hidden we because we use that route to route to the asset details page
- Updated the markets icon to be something more inline with the style of our other icons
closes #7918 
Minimal risk
When you navigate to the app, there will no longer be an assets page on the navbar.
The markets icon should now match the rest of the icons.
> fix: hide assets page and change markets icon

- .env.develop
- src/assets/translations/en/main.json
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/LimitOrder/LimitOrder.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputHeader.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/types.ts
- src/config.ts
- src/state/slices/preferencesSlice/preferencesSlice.ts
- src/test/mocks/store.ts
Adds a placeholder UI to enable multiple contributors in the development of limit orders.
Includes a feature flag.
Progresses #6218
Unblocks #6206
Low risk
Mostly not required. A sanity check of trades would be wise.
> feat: placeholder ui for limit orders development

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/AssetSummaryStep.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
Updated copies inside `TradeSuccess`, made it agnostic so we could change it if we have another specific bridge in the future
Also added a button prop to `StepperStep` so we can pass a button as a prop that will be shown on the right
closes #7894
- Verify a regular swap that is not an arbitrum swap (verify the TradeSuccess screen copies and buttons)
- Do an arbitrum withdraw, check copies and click on the claim button to see if you are redirected to the claim view
- Ensure Arbitrum deposits (ETH -> ARB direction) do not display the claim CTA nor the Arbitrum withdraw specific copies
n/a
n/a
> fix: arbitrum bridge withdraw status copies and button

- src/components/MultiHopTrade/components/LimitOrder/LimitOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderStatus.tsx
- src/components/MultiHopTrade/components/LimitOrder/types.ts
- src/components/MultiHopTrade/components/StatusBody.tsx
- src/components/MultiHopTrade/components/TradeInput/components/Claim/ClaimStatus.tsx
Adds some minimal interactive scaffolding as a placeholder for limit orders UI flow, ahead of some incoming design changes. The UI here is intended to anchor discussion and provide a way to rapidly view parts of the limit orders UI and transitions between the routes.
Progresses #6218
Low risk, UI only
Arbitrum bridge claim status UI.
Sanity check of Arbitrum bridge claim status UI, check the correct status is rendered (circular progress, green check, red alert icon).
Limit orders are behind feature flag, but please test arbitrum bridge claims UI as this is impacted.
> feat: ui scaffolding for limit orders pending design changes

- src/components/MultiHopTrade/components/TradeInput/components/ReceiveSummary.tsx
Renders the full "swap source" in the receive summary so users are more aware of differences between us and other apps. See https://discord.com/channels/554694662431178782/1299080339322306680/1299080343059693608 for example of why this is needed.
closes NA.
Very low risk.
Get some quotes and check the UI is behaving itself
> feat: display swap source instead of swapper name in receive summary

- packages/swapper/src/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
Disables `Stargate V2 (Economy Mode)` bridge in lifi swapper. Stargate should have been disabled due to incompatibility with our fee calculations, but economy mode seems to have slipped through the cracks.
See https://li.quest/v1/tools for list of bridges:
Added a comment with some context.
closes #7988
Very low risk.
Check Stargate routes are not available in the app.
> fix: deny stargateV2Bus in lifi swapper

- src/assets/translations/en/main.json
- src/components/AssetToAssetCard/AssetToAssetCard.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderBuyAsset.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderStatus.tsx
- src/components/MultiHopTrade/components/PriceImpact.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputBody.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter/SharedTradeInputFooter.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter/components/ReceiveSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/MaxSlippage.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ReceiveSummary.tsx
- src/pages/RFOX/components/Stake/Bridge/BridgeConfirm.tsx
Implements the limit orders ui layout fully, excluding the order history. This is placeholder UI only and ZERO functionality has been added in this PR.
Some effort has been made to minimise code duplication and complexity:
- Broke out `AssetToAssetCard` from rFOX for re-use in limit orders
- Created a `LimitOrderBuyAsset` which avoids the megalithic dumpster fire that is `TradeAssetInput`. No need to strap on more complexity for what is essentially a couple of drop-downs
- Simplified `LimitOrderStatus` component
closes #6218
Moderate risk as this has refactored some user-facing components.
- Check the Trade input UI still works as expected
- Check the …
> feat: full limit orders ui layout

- src/assets/translations/en/main.json
- src/components/AssetSelection/AssetSelection.tsx
- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/components/AssetSelection/components/AssetMenuButton.tsx
- src/components/AssetSelection/helpers.ts
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
Actions feedback on the limit orders input UI.
- Breaks out the menu buttons for asset and chain selection for re-use in limit orders
- Fixes minor deviations from the product spec
- Adds interactions to set the limit, and to swap the price
- Updates the expiry dropdown items to match the design
All data is placeholder and is not wired up to anything meaningful.
NA
Low risk
Check the chain and asset menus in the trade input are still styled correctly.
Check the chain and asset menus in the trade input are still styled correctly.
https://jam.dev/c/c4c2efd2-9cfa-41cf-bd3c-b21d2c901a5c
> feat: action beard feedback on limit orders ui

- src/components/TransactionHistoryRows/TransactionGenericRow.tsx
in The TX history when we have multiple symbols, we should truncate it down to a max width of 200px.
closes #7926 
You'll need a cosmos claim to see this. Inside activity or recent transactions the right side of the row should truncate showing ...
> fix: truncate the symbols when there are multiple

- src/context/WalletProvider/SelectModal.tsx
- src/lib/mipd.ts
As expected, MM rdns is different on mobile, see desktop vs. mobile rdns with 10x dev debugging in the DOM:
This caused MM to appear both - once as the static option we have, and a second time with its actual rdns. Fixed by never displaying static mipd providers on mobile since unapplicable.
closes #8024
Low to none
- Using MM dApp browser on mobile (currently deployed in gome for testing with the 10x dev debugging log, which is removed from this PR), there is only a single, working MM option
- ☝🏽 
- ☝🏽
> fix: mm mobile duplicate MM option

- packages/caip/src/adapters/banxa/index.ts
- packages/caip/src/adapters/onramper/index.ts
Add supported solana assets to banxa and onramper
closes https://github.com/shapeshift/web/issues/8015
Low
- Ensure supported solana assets are listed under buy/sell crypto
- Ensure you can interacted with the supported providers
:point_up:
:point_up:
> feat: add supported solana assets to banxa and onramper

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/TradeAmountInput.tsx
Adds some state management to the limit orders input, in prep for making requests to the RTK query.
This is an incremental change intended to minimise review surface area/noise, and increase focus on important changes once RTK query is wired up.
- Adds translations where needed
- Implements the ridiculous logic on input handling for limit price, combined with preset values etc
progresses  #8032
Low risk.
Not required at this stage.
Quick demo of the clicky fun times.
https://jam.dev/c/fb7ae4d3-9124-47a1-87f8-af2fa5b39afb
> feat: implemented ui state management in limit orders input

- packages/caip/src/adapters/banxa/index.ts
Fixes an issue with Banxa onramp logic not correctly parsing `AssetId`s. 2 issues:
- `AssetId`s are case sensitive, and so `toLower` causes the key match in `AssetIdToBanxaTickerMap` to fail
- We were checking the `ChainId` against `solAssetId` instead of `solanaChainId` 💀 
Closes https://github.com/shapeshift/web/issues/8053
Small
Banxa onramping.
Ensure we can instigate a Banxa onramp flow for Solana, and ensure other assets still work as expected.
☝️
☝️
> fix: solana banxa fiat onramp

- src/assets/translations/en/main.json
- src/components/OrderDropdown/OrderDropdown.tsx
- src/components/OrderDropdown/types.ts
- src/components/SortDropdown/SortDropdown.tsx
- src/components/SortDropdown/types.ts
- src/lib/coingecko/utils.ts
- src/pages/Markets/Category.tsx
- src/pages/Markets/components/AssetGridWithData.tsx
- src/pages/Markets/components/LpGrid.tsx
- src/pages/Markets/components/MarketGrid.tsx
- src/pages/Markets/components/MarketsRow.tsx
- src/pages/Markets/constants.ts
- src/pages/Markets/hooks/useCoingeckoData.ts
- src/pages/Markets/hooks/usePortalsAssetsQuery.ts
- src/pages/Markets/hooks/useRows.tsx
- Coingecko assets are using the API sorting parameters so we get new data for the Market Cap and Volume categories
-- Other are using sorting on the already fetched data
- Portal assets and Thorchain pools are using the same sorting thing inside effects, minus the price change, plus APY sorting as it's cleaner for our users to be able to sort by APY
-- Portals is refetching using the API sorting if it's using APY or Volume so we get a bigger chunk of data
closes #7919
Low
- Play with filters on every pages of the market page, filters should work accordingly
- Base categories should display assets as expected without showing the filters
- Thorchain and …
> feat: add market page filters and sort

- packages/caip/src/assetId/assetId.ts
- packages/caip/src/constants.ts
- packages/swapper/src/swappers/CowSwapper/endpoints.ts
- packages/swapper/src/swappers/CowSwapper/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- packages/swapper/src/swappers/CowSwapper/types.ts
- packages/swapper/src/swappers/CowSwapper/utils/helpers/helpers.test.ts
- packages/swapper/src/swappers/CowSwapper/utils/helpers/helpers.ts
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/state/apis/limit-orders/limitOrderApi.ts
- src/state/apis/limit-orders/types.ts
- src/state/reducer.ts
- src/state/slices/opportunitiesSlice/resolvers/ethFoxStaking/index.ts
- src/state/store.ts
- src/test/mocks/store.ts
Wires up part of the limit orders ui to RTK for limit order quotes. Note that the quotes provide a market rate only and do not actually return any relevant info in terms of limit orders.
Also note that receive address will have to be implement as a separate task as it's likely much more involved than estimated in this ticked.
Further wiring to come in follow-ups.
closes #8032
Very very low risk, not user facing.
Check that a limit order quote (or an error) appears in the terminal per the console logs when getting a quote.
> feat: wire up limit orders UI to RTK query

- src/components/MultiHopTrade/MultiHopTrade.tsx
Another case where solana assets were showing in the trade input component. Use FOX as the default buy asset when on a solana asset page.
closes https://github.com/shapeshift/web/issues/8016
Low
- Ensure solana assets are showing in the trade input component when on a solana asset page
- Ensure default buy asset behavior is not changed for non solana assets
:point_up:
:point_up:
> fix: use fox as default asset on solana asset pages

- src/components/AssetIconWithBadge.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderCard.tsx
Adds an optional `secondaryAssetId` prop to the `AssetIconWithBadge` component such that if a `secondaryAssetId` is provided we render the `secondaryAssetId` icon pealing off the `assetId` icon.
This is required for the limit order UI (see screenshot below).
Contributes to https://github.com/shapeshift/web/issues/6206
Small
None
- ensure that icons, particularly those in the transaction history, show no regressions
With the limit order flag on ensure that in the order history the icons render correctly (sell asset icon pealing off the buy asset icon).
Only a regression check on the icons needed.
> feat: limit order asset icon support

- src/components/MultiHopTrade/components/LimitOrder/LimitOrderList.tsx
Makes the limit order list scrollable.
Contributes to https://github.com/shapeshift/web/issues/6206
Small
None
Ensure that the hardcoded limit order list is scrollable.
☝️
Not required.
> chore: make limit order list scrollable

- src/assets/translations/en/main.json
- src/components/OrderDropdown/OrderDropdown.tsx
- src/components/SortDropdown/SortDropdown.tsx
- src/pages/Markets/components/MarketsRow.tsx
I forgot the responsive dropdown component for the market page filters, implementing it there
Pretty simple: under XL, wrap every filters into another dropdown
closes #8060
Low
- Go to any market category page
- Resize to < XL and see the dropdown appearing
n/a
n/a
> fix: market page filters responsive

- src/components/MultiHopTrade/components/TradeInput/components/CollapsibleQuoteList.tsx
Fix the width of the `CollapsibleQuoteList`, currently broken in `release`:
This PR;
N/A - current release issue
Small
None
The `CollapsibleQuoteList` should be the correct width again, with rounded corners and a full-width scrollbar.
☝️
☝️
See above.
> fix: collapsibleQuoteList width

- src/components/OrderDropdown/OrderDropdown.tsx
- src/components/SortDropdown/SortDropdown.tsx
- src/pages/Markets/components/MarketsRow.tsx
Market chain selector is going out of screen on mobile
closes #8090
Low
Open market category page on mobile
Select the avalanche chain, it should be displayed properly without any bugs
n/a
n/a
> fix: market filters going out of screen

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/RateGasRow.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedSlippagePopover.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter/SharedTradeInputFooter.tsx
- src/components/MultiHopTrade/components/SlippagePopover.tsx
- src/components/MultiHopTrade/components/SwapperIcons.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/state/apis/limit-orders/limitOrderApi.ts
- src/state/apis/limit-orders/types.ts
- src/state/slices/tradeQuoteSlice/selectors.ts
Wires up the limit order quote query to the input and config UIs to display the result of the quote in the UI.
Includes:
- Wiring up estimated affiliate fee and fee modal
- Wiring up custom slippage
- Wiring up quoted market price to UI
- Resets limit orders config when assets change (i.e resets the rate, expiry and `%` input - not the input UI). Config is not reset when amounts or quote changes to avoid annoying users during polling (polling yet to be implemented)
- Adds loading state to limit orders input, config, and receive summary
Excludes the following which are coming in follow-ups:
- Submission of limit orders
- Error handling or display (will be done in https://github.com/shapeshift/web/issues/8109)
- Reset of amount and receive address state on asset change (will be done in …
> feat: limit orders quote wiring

- src/components/FeeExplainer/FeeExplainer.tsx
- src/components/FeeExplainer/FeeSliders.tsx
On the `fox` route:
- Ensures the FOX power value updates as the value in the store updates
- Prevents the FOX power value from refreshing if the `FeeSliders` have already been interacted with (i.e. once you interact with it you're in override mode)
- Adds a loading skeleton on the amount input when the `selectIsSnapshotApiQueriesPending` selector returns `true`
- Improves the naming inside the component
Closes https://github.com/shapeshift/web/issues/8123
Small (UI changes only)
None
- Whilst connect to a wallet with some FOX, load the `/fox` route with a fresh cache. The FOX Power value should have a loading skeleton whilst it is doing so. Once a value is fetched the value should be shown …
> fix: fox discount ux

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/lib/utils/thorchain/balance.ts
Use `feeAsset` to convert dust amount to ensure the correct amount of dust sent for savers withdrawal transactions.
https://discord.com/channels/554694662431178782/886041582422356018/1309237779984551997
Low - savers withdrawals should succeed again (usdc/usdt)
- Ensure you can withdraw usdc and usdt positions on ethereum
- Ensure the correct dust amount fee is displayed to the user
:point_up:
:point_up:
https://etherscan.io/tx/0x3b9976d9770edd28de241588cfb0f1af258b5c9c8fcb284261664fcc187ea56b
https://viewblock.io/thorchain/tx/3b9976d9770edd28de241588cfb0f1af258b5c9c8fcb284261664fcc187ea56b
https://indexer.thorchain.shapeshift.com/v2/actions?txid=3b9976d977 …
> fix: use fee asset for dust amount conversion

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/hooks/useGetSwapperTradeQuoteOrRate.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/state/apis/swapper/swapperApi.ts
The one big risk we were affraid of for Li.Fi *did* produce a regression. Tyvm @0xean for your bad luck with web and encountering those bugs in place of users.
Commentaries repeated code should be pretty self-explanatory, but writing this in the PR as well:
Li.Fi is a flaky one, and making the exact same request to its routes endpoints a sec later may yield very different routes. Some may be missing from previous call, new ones may be present, and you may even end up with no routes at all. 
This is an issue with the rates vs. quotes split, as we would otherwise fetch a final quote at pre-signing time, but we absolutely can *not* do that, as, depending on the underlying Li.Fi tool used, you're more than likely to not see the same route a few seconds later. Examples of routes that almost …
> fix: unrug Li.Fi trades

- packages/unchained-client/src/cosmossdk/parser/index.ts
- packages/unchained-client/src/cosmossdk/thorchain/parser/__tests__/mockData/thorchainRunePoolDeposit.ts
- packages/unchained-client/src/cosmossdk/thorchain/parser/__tests__/mockData/thorchainRunePoolWithdraw.ts
- packages/unchained-client/src/cosmossdk/thorchain/parser/__tests__/thorchain.test.ts
- packages/unchained-client/src/parser/thorchain.ts
Does what it says on the box - ensures RUNEPool Txs are parsed as such.
Note the amount being off for withdraws is not a concern of this PR, this isn't necessarily the "amount being deposited/withdrawn" but the "Tx value" (in tokens or native asset) which is not a concern of this PR and happens holistically across Txs e.g savers withdraws for tokens:
closes https://github.com/shapeshift/web/issues/8182
None
- Ensure RUNEPool deposits and withdraws are tagged as "RUNEPool" and displayed as "Deposit" and "Withdraw Requested"
- ^
- ^
- develop
- This diff
> feat: unchained-client runepool Txs parsing

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Status.tsx
Ensures RUNEPool withdraws do not spin for eternity.
closes https://github.com/shapeshift/web/issues/8181
None
- RUNEPool withdraws correctly go to complete state.
- ^
- ^
- develop
- this diff
> fix: runepool withdraws status detection

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hops.tsx
This PR fixes two things:
1. The approval step disappearing at preview/execution time when a final quote is refetched
2. The approval step disappearing from trade complete step
closes https://github.com/shapeshift/web/issues/8191
Low
Note: If testing Portals Txs with small amounts, ensure you bump slippage up (e.g 10% Portals max) or things will fail at quote time, not introduced by this PR
- Get rates for a swapper which gets a final quote after approvals e.g Portals
- Ensure that after you have granted the approval and a final quote is fetched (i.e rate changed modal), the approval row is still present
- Ensure that after Tx completion, the approval row …
> fix: approvals disappearing on Tx complete

- packages/swapper/src/swappers/CowSwapper/utils/helpers/helpers.ts
- packages/types/src/cowSwap.ts
- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/LimitOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/CollapsibleLimitOrderList.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderCard.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderList.tsx
- src/components/MultiHopTrade/components/LimitOrder/hooks/useGetLimitOrdersForAccountQuery.tsx
- src/components/MultiHopTrade/components/LimitOrder/types.ts
- src/state/apis/limit-orders/limitOrderApi.ts
Fetches all limit orders for all connected accounts, and renders them in the appropriate list.
closes #8170
Low risk. Isolated to limit orders aside from a types package version bump.
TIP: Head over to the [cowswap app](https://swap.cow.fi/#/) to create some limit orders to test.
- Quick sanity check to ensure cowswap spot trades arent broken, as types package version on an import was bumped.
- Local sanity check of limit orders list loading, data etc.
Demo of limit orders list loading etc.
https://jam.dev/c/fab8042c-b947-44df-89f1-88657e82ad00
> feat: fetch and render limit orders list

- src/context/AppProvider/hooks/useAccountsFetchQuery.tsx
Fixes issue where accounts that were disabled by a user were being automagically re-enabled when entering the trade page. Root cause was falsey comparison of `boolean | null`.
closes #8105 
Low risk.
1. open app with metamask with snap enabled
2. go to "my wallet" page
3. disable ethereum in account management
4. go to "trade" page
5. wait a few seconds - the account was being re-added, now it remains disabled
Disabled account is still disabled 🎉
> fix: dont refetch accounts that were disabled

- src/AppProviders.tsx
The keepkey provider was under the ModalProvider, meaning that keepkey modals couldn't access the keepkey provider states, making the app crash
just found it
Maybe low? as it was completely crashing the app
- Try to wipe your device
- In general if you can, try every keepkey features...
n/a
n/a
> fix: keepkey provider order making kk feature crashing

- src/components/Layout/Header/NavBar/SubmenuHeader.tsx
Small fix to KeepKey's menu margins.
Before:
After:
None, noticed whilst testing KeepKey PRs.
Tiny
None
Ensure KeepKey sub-menu's look sane.
☝️
☝️
See description.
> fix: keepkey menu margin

- src/components/Layout/Header/NavBar/KeepKey/ChangeLabel.tsx
- src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
Fixes the KeepKey label UI in the submenu - it currently shows `walletinfo.name`, which is incorrect (always "KeepKey'). The label path is `walletInfo.meta.label`.
None, noticed whilst testing Neo's KeepKey PR.
Small
None
Connect a KeepKey with a label (or set one). The current label should show in the UI.
☝️
☝️
See above.
> fix: keepkey label ui

- packages/utils/src/historyTimeframe.ts
- packages/utils/src/index.ts
- src/components/TransactionHistoryRows/utils.ts
- src/hooks/useBalanceChartData/useBalanceChartData.test.ts
- src/hooks/useBalanceChartData/useBalanceChartData.ts
- src/lib/market-service/exchange-rates-host/exchange-rates-host.ts
- src/state/slices/marketDataSlice/marketDataSlice.tsx
- src/state/slices/marketDataSlice/selectors.ts
- src/state/slices/marketDataSlice/types.ts
- src/state/slices/marketDataSlice/utils.ts
Fixes corrupted price charts caused by price samples spanning times outside of the selected timeframe. For example for the 24 hour time period, data prior to 24 hours ago was being displayed, resulting in corrupted charts in the UI. The solution was to trim price history data when it's upserted in redux, and also when it's read from redux.
NOTE: It's possible there is still chart corruption occurring due to incorrectly sorted price history samples. If this is the case, let me know and I'll add sorting to the selector. However if this is not the case we'd be best off avoiding the additional compute.
closes #8093
Low risk, this affects display of price charts only, which is already broken.
> What protocols, transaction types, wallets or contract …
> fix: remove price history data that is out of bounds of a given timeframe

- src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts
Ensures we do not fire the `WalletActions.NATIVE_PASSWORD_OPEN` action when on the native mobile app when the `NativeEvents.MNEMONIC_REQUIRED` event is observed.
Closes https://github.com/shapeshift/web/issues/8257
Medium - small code change, but ignoring this event when we shouldn't could cause problems!
- Mobile wallet connection
- Native wallet connection
Point the mobile app at `juice` to test this PR.
On the mobile app, once you've authenticated using the device's native auth (e.g. FaceID), ensure the native password entry modal does not display.
Also confirm the following works as expected
- creating a wallet on mobile
- switching between saved …
> fix: mobile app login flow

- packages/swapper/src/swappers/PortalsSwapper/getPortalsTradeQuote/getPortalsTradeQuote.ts
Portals protocol fees can be in either the buy asset or the sell asset.
This diff accounts for that and makes portals protocol fees great again.
Closes https://github.com/shapeshift/web/issues/8266
Small - UI only.
Portals trade quotes.
Ensure the protocol fee on Portals trade quotes looks accurate.
☝️
☝️
Production
This PR
> fix: portals protocol fee

- src/state/slices/txHistorySlice/selectors.ts
One-liner, fixes degraded history popover displaying accounts not connected to wallet.
closes NA.
Before:
After:
> fix: degraded history popover displaying accounts not connected to wallet

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
Removes a pointless "learn more" button from limit order confirm. It didn't do anything so we're commenting it out until we have a URL to point at.
closes NA
Virtually no risk, though I won't ever discount the possibility of everything breaking.
Preview a limit order and confirm the "learn more" button is now gone.
Prod:
This PR:
> fix: remove pointless button from limit order confirm

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Hop.tsx
Fixes the duplicate tooltip issue by only showing one.
If we have no gas or protocol fee, show the "continue swapping" tooltip, else show the explanation tooltip.
Closes https://github.com/shapeshift/web/issues/8250
Small
Portals quote UI.
Get a Portals quote. Observe that no gas value is available before clicking "Confirm and Trade", and that only one tooltip shows: the "continue swapping" one.
☝️
Anticipates change coming in https://github.com/shapeshift/web/pull/8287 and preemptively adds a tooltip for the `undefined` case there.
☝️
> fix: portals tooltip overlay

- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
This PR ensures that we never have stale final trade quotes when going back from an unfinalized quote back to swapper.
closes https://github.com/shapeshift/web/issues/8291
Medium, theoretically low, but reset could be wrong and come back biting us, see testing steps
- Ensure going back and forth to an uncompleted Portals trade where final quote was fetched back to input, then going for a Portals trade with the same input doesn't keep the previous final quote as stale.
This can be confirmed by `(unknown)` being back, vs. the previous behaviour being the previous final quote still being present, which can be seen with the presence of a network fee.
- Going …
> fix: clear tradeQuoteSlice state on trade input mount

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/state/slices/common/tradeInputBase/createTradeInputBaseSlice.ts
- src/state/slices/limitOrderInputSlice/constants.ts
- src/state/slices/limitOrderInputSlice/helpers.ts
- src/state/slices/limitOrderInputSlice/limitOrderInputSlice.ts
- src/state/slices/limitOrderInputSlice/selectors.ts
- src/state/slices/tradeInputSlice/tradeInputSlice.ts
- src/test/mocks/store.ts
Fixes issue where custom limit price input is lost when navigating back to limit input from preview step.
Moves `presetLimit` into redux and moves the reset of limit order config on asset change into redux, so component mount doesn't trigger a reset.
Includes an improvement to `createTradeInputBaseSlice` to allow us to compose redux actions (needed for this PR).
closes #8216
Low risk. Review redux changes with care though.
Check limit orders config is only reset when changing assets.
Worth giving spot trades a test in case the are broken for some surprise reason.
Demo:
https://jam.dev/c/d1b1416d-d0d8-48f4-b6d2-c162a7801dc2
> fix: limit order custom limit price state lost

- CONTRIBUTING.md
- packages/chain-adapters/src/solana/SolanaChainAdapter.ts
- packages/swapper/package.json
- packages/swapper/src/swappers/JupiterSwapper/idls/referral.ts
- packages/swapper/src/swappers/JupiterSwapper/swapperApi/getTradeQuote.ts
- packages/swapper/src/swappers/JupiterSwapper/swapperApi/getTradeRate.ts
- packages/swapper/src/swappers/JupiterSwapper/utils/constants.ts
- packages/swapper/src/swappers/JupiterSwapper/utils/helpers.ts
- src/components/Modals/Send/AddressInput/AddressInput.tsx
- src/components/Modals/Send/views/Address.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedRecipientAddress.tsx
- src/state/apis/swapper/helpers/validateTradeQuote.ts
- src/state/slices/common/tradeInputBase/createTradeInputBaseSlice.ts
- src/state/slices/limitOrderInputSlice/constants.ts
- src/state/slices/limitOrderInputSlice/helpers.ts
- src/state/slices/limitOrderInputSlice/limitOrderInputSlice.ts
- src/state/slices/limitOrderInputSlice/selectors.ts
- src/state/slices/tradeInputSlice/tradeInputSlice.ts
- src/test/mocks/store.ts
- yarn.lock
fix: limit order custom limit price state lost (#8299)
feat: add no spam typo PRs section in CONTRIBUTING.md (#8308)
fix: custom receive address overlay on long addies (#8284)
feat: handle shapeshift fees for jupiter and rate balance check (#8267)
> chore: release v1.719.0

- packages/swapper/src/swappers/LifiSwapper/endpoints.ts
- packages/swapper/src/swappers/LifiSwapper/utils/getNetworkFeeCryptoBaseUnit/getNetworkFeeCryptoBaseUnit.ts
Does what it says on the code comments, see release thread https://discord.com/channels/554694662431178782/876953436908822568/1315820902285574144
closes N/A
Low to none, only brings *back* weird double `toString()` in Li.Fi's `getUnsignedEvmTransaction()`, and in the newly added Li.Fi estimates in `getNetworkFeeCryptoBaseUnit` 
- Li.Fi token sells with a token allowance granted for the token do not fail with either `Failed to estimate network fees` (locally development server) or `Failed to execute 'json' on 'Response'` (upstream builds)
- Li.Fi native asset sells do not fail with either `Failed to estimate network fees` (locally development server) or …
> feat: unrug lifi in release

- packages/swapper/src/swappers/JupiterSwapper/swapperApi/getTradeRate.ts
I didn't understand what 🐐 @gomesalexandre did learn me while talking about rate and quotes and it seems that I missed the fact that I was pushing the receiveAddress in the rate, which shouldn't be the case, it was disabling the sign button as the quote was never fetched because of this
Low
- Try to swap using jupiter, or at least get a quote, the `Sign transaction` should not be disabled anymore and you should be able to sign the TX
https://jam.dev/c/d127a1bb-bcd3-4aa2-be3c-1bca8d36ed93
> fix: jupiter quote is never fetched

- packages/swapper/src/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/LifiSwapper/utils/types.ts
- packages/swapper/src/types.ts
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteInput.ts
This PR ensures that we properly populate allowed bridge (as gotten from rate time as `[bridge]` at rate time), under the *bridges* allowedlist for Li.Fi, vs. us erroneously doing so under the `exchanges` umbrella previously.
This means that all bridges were guaranteed to fail at quote time, as bridges and exchanges are two different notions / schemas, and passing one in the other would fail validation upstream.
closes https://github.com/shapeshift/web/issues/8344
Low, small risk of regular trades broken but easily regression testable
- When attempting a Li.Fi bridge, you're not getting a blank screen at final quote time
- Well, there is one ramification …
> fix: lifi bridges final trade quote

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
So cowswap has this:
And now so do we 🎉
progresses #8217 (Specifically https://github.com/shapeshift/web/issues/8217#issuecomment-2506997136 )
Very low risk, this is a client side validation change and we are protected by the cowswap API validation.
- Trying to order with zero balance should be prevented (not supported by cow api)
- Trying to order with non-zero, but insufficient balance should be allowed
Full demo:
https://jam.dev/c/55da139f-a5b5-40f0-b2fd-1d995046fc49
Trying to order with zero balance should be prevented (not supported by cow api):
Trying to order with non-zero, but insufficient balance should be allowed:
> feat: allow users to submit limit orders with insufficient balance

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderCard.tsx
Adds some polish to the amounts displayed on the limit order cards:
- Handles bigly amounts with ellipsis
- Add tooltip for amounts (in case of overflow - though always enabled for simplicity)
- Reduces font size from `xl` to `lg` for better layout and more space for large amounts
- Uses 'merican spelling for `canceled`
prep for #8217
Very low risk, display of existing limit order amounts only.
Before
After
With ellipsis in action
> feat: limit orders card amounts polish

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/FeeStep.tsx
This PR ensures that the ShapeShift fee at quote confirm time is displayed in user currency, vs. Frankenstein user currency symbol, but USD value currently.
closes https://github.com/shapeshift/web/issues/8360
None
- Select a non-USD user currency and get a trade rate
- Ensure that the amount at confirm screen time is matching the one at rate time
- ^
- In case you have to low of a balance to get fees (lower than the minimum in the fee curve), you can apply the monkey-patch below to disable balance checks:
```diff
diff --git a/src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx …
```
> fix: trade confirm ShapeShift fee handle user currency rate

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderCard.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderList.tsx
We want 2 warnings when an order is "unable to be filled"
- Insufficient balance
- Insufficient allowance
closes #8217
Very low risk - display only.
- Check open limit orders without sufficient balance are warned as such
- Check open limit orders without sufficient allowance are warned as such
- Check open limit orders with enough of both dont have a warning
- Check historical limit orders dont have warnings
Demo of both cases (monkey patched)
https://jam.dev/c/91883077-b719-457f-9d37-bfc18c4d76f3
One with a warning, one without
> feat: add warnings to open orders when order cannot be filled

- packages/swapper/src/swappers/ChainflipSwapper/endpoints.ts
The whole reason why this was working before was because of sheer luck.
The `from` param in `buildSendApiTransaction` and similar `UTXOBaseAdapter` methods acts as a directive to filter UTXOs by that address only, which comes handy when sending THOR Txs, where all inputs need to be from a single address.
Since this was present in Chainflip's `getUnsignedUtxoTransaction`, this means that sends would only be working if you had enough on your sending address, which could be the case if you 
- use Phantom, which does address 0 reuse so using `from` and filtering UTXOs will always work since you're using a single address
- use native or Ledger but have explicitly self-sent all your funds to your next receive address
closes N/A, spotted in Chainflip DCA testing thread
> High Risk PRs Require 2 …
> fix: chainflip UTXO sends don't narrow UTXOs by senderAddress

- src/components/MultiHopTrade/components/LimitOrder/LimitOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/PlaceLimitOrder.tsx
When a limit order is placed, a simple ui appears showing a spinner for 1 second followed by a green check. The "view order" button takes the user to the order list (on the input page if not in a compact view).
The UI width is also no longer slenderman thin boi, but a thicc 500px as it should be.
closes NA
Low risk.
None.
Place an order and click "view order":
- On mobile
- On wide desktop
- On narrow desktop
Wide desktop
https://jam.dev/c/6985ff5e-0d19-48e5-85c6-b01226371826
Narrow desktop
https://jam.dev/c/6da704b2-3ab8-4df1-9783-8eeef825de72
> feat: polish and cleanup of limit order confirmation ui

- src/components/MultiHopTrade/components/LimitOrder/components/CancelLimitOrder.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowanceReset.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useSignPermit2.tsx
- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Approve.tsx
- src/hooks/useErrorToast/useErrorToast.tsx
- src/plugins/walletConnectToDapps/components/modals/EIP155TransactionConfirmation.tsx
Fixes an issue where error toast appears merely as `c` 🗿
Includes mental health renaming of `useErrorHandler` to `useErrorToast`.
closes #8372
Very low risk.
None
Begin a trade with metamask, and reject it before signing. The error message should be real readable text, not trollworthy `c`.
`c` 🗿
https://jam.dev/c/9b9344da-c771-4fc8-b905-041025b8a6a8
Fixed:
https://jam.dev/c/9045bdc7-f18b-43ac-ae8a-4dcfcbff9e11
> fix: error toast copy appearing as c

- packages/swapper/src/swappers/ZrxSwapper/getZrxTradeRate/getZrxTradeRate.ts
We were not returning `allowanceContract` previously, which meant that the allowance query would never run without a spender, and would never be in a loading state.
As soon as a final quote arrived, things would get fetched and loading states would work, but if you were to click "Confirm and Trade" before the final quote arrived and brought in the allowanceContract and eventually triggered allowance checks, then the allowance step would never get triggered despite being needed.
closes https://github.com/shapeshift/web/issues/8401
None, blatant mistake
- Get a ZRX rate at input time for an asset you haven't granted allowance for to the Permit2 contract, or …
> fix: zrx broken allowance checks

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
Does what it says on the box, see screenshots.
Also tackles a fix wrt the delta showing with broken NaN% when there's no sell amount/limit price yet.
closes https://github.com/shapeshift/web/issues/8411
None
- Get a limit quote
- Input an amount below market
- Notice you see the warning in addition to the delta
- Notice you don't see the delta anymore (nor the delta) on default state without a sell amount/limit price populated yet
- ^
- ^
> feat: limit orders display warning when selling lower than market

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
i.e either limit price from quote (shouldn't happen but it may in case of errors) *or* user set limit price.
- closes https://github.com/shapeshift/web/issues/8415
None
- Get a limit quote
- Input 0 as limit price
- Notice preview button is disabled
- Clear input altogether (empty string)
- Notice preview button is still disabled
- ^
- ^
> fix: limit orders don't let users preview with zero'd out limit price

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderBuyAsset.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/state/slices/limitOrderInputSlice/selectors.ts
Does what it says on the box, confirmed with product this was an actual ommission in mocks.
closes https://github.com/shapeshift/web/issues/8413
Low, literally swapper/shared component across the app (`<TradeAssetInput />` code reuse
- Get limit rates for USDC <-> FOX (both ways, USDC <-> FOX is always the preferred pair to test with to ensure there is no precision conversion issues)
- Ensure that buy amount crypto looks sane
- Ensure that buy amount in fiat looks sane
- ^
- ^
https://jam.dev/c/87566594-df46-4614-ab61-fe9691b23575
> fix: limit orders display buy amount

- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
- src/components/MultiHopTrade/components/SlideTransitionRoute.tsx
After the new year, hide the THOR Swap free fee banner, as fees will be applied again (didn't add it as early return of the component itself for easier understanding purpose
closes #8422
Low
- I personally spoofed it with a chrome extension (Time Travel), but as your own discretion!
> fix: hide thorswap free fee banner after 2024

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/StepperStep.tsx
- src/components/MultiHopTrade/components/SharedConfirm/SharedConfirmFooter.tsx
- src/components/MultiHopTrade/components/TradeConfirm/EtaStep.tsx
- src/components/MultiHopTrade/components/TradeConfirm/ExpandableStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/ExpandableTradeSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmBody.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooter.tsx
- src/components/MultiHopTrade/components/TradeConfirm/helpers.ts
- src/components/MultiHopTrade/components/TradeConfirm/hooks/useStepperSteps.tsx
- src/components/Stepper.theme.ts
Adds more improvements to the new swapper:
1. Refactor and code improvements from review comments in https://github.com/shapeshift/web/pull/8408
2. Update TradeStep vernacular to StepperStep to better disambiguate between the concepts
3. Fix the error indicator state for inner steps
Contributes to https://github.com/shapeshift/web/issues/8118
Low
None
Quick sanity check of the error state (easy to simulate by blocking connections after trade preview):
See above.
> chore: more new swapper tweaks

- src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TxLabel.tsx
Ensures the correct base URL is used:
- Tx explorer link for approval Txs
- Tx explorer link *or* swapper link (e.g CoW explorer) for actual swap Txs or message signing, leveraging existing `getTxLink` logic
closes https://github.com/shapeshift/web/issues/8458
Low - this logic already exists throughout the app and we're only passing the `name` prop down to `getTxLink` which allows this
- Initiate a CoW swap with the new swapper flow 
- Ensure the explorer link is CoW's, not etherscan or etherscan likes
- None, this is still under flag
- develop
- this diff
> fix: new swapper flow incorrect Tx link base URL

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooterContent/TradeConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/helpers.ts
- Unifies protocol fee display between trade input and trade preview/confirm screens by adding fiat amounts. Includes a bonus bug fix where multiple fees in the same currency would show twice - the amounts are now aggregated.
- Show both fiat and crypto tx fee amounts on the trade input summary
https://github.com/shapeshift/web/issues/8460
Small - UI changes only.
N/A
With the `REACT_APP_FEATURE_NEW_TRADE_FLOW` feature enabled, ensure that:
- At trade input with show both fiat and crypto amounts for all fees (network and protocol)
- At quote confirm time we show network fees in both crypto and fiat. Confirm that multi-hop trades show as 2 separate lines)
**Multiple protocol fee display …
> chore: display both fiat & crypto amounts throughout trade flow

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
Buy asset market data price looks like it's a purely derived value as a product of the *input* buy amount and sell amount, however, it is derived from the *quote* buy and sell amounts.
A quote however, is RTK query data, and stale RTK query data will stil be present when:
- fetching 
- current query is errored, but previous (stale) one was happy
This was producing odd bugs where failures in getting a CoW quote (i.e inputting too low of am amount) would return the previous stale quote, however, the previous quote was for an entirely different asset, and possibly a different precision, which will lead to amounts being off.
Fixed by zero'ing amounts out when fetching/errored. 
closes https://github.com/shapeshift/web/issues/8414
> What protocols, …
> fix: limit order never keep stale values for buy asset market price

- src/components/MultiHopTrade/components/TradeConfirm/TradeFooterButton.tsx
Ensures we only show the price impact warning when we are in the preview stage. Once accepted at this stage we should not show it again.
Closes https://github.com/shapeshift/web/issues/8439
Small
None
Do a high impact trade (I did Eth on Arb One to Black Angus on Arb One for cheap testing) and ensure the high impact trade modal only shows once when pressing "Confirm and Trade", and at no other time.
N/A
> fix: only show warning ack when previewing

- src/components/Stepper.theme.ts
Fixes a regression from https://github.com/shapeshift/web/pull/8437 that broke the `innerStep` Stepper styling.
N/A, fixes regression.
Small
None
With the `REACT_APP_FEATURE_NEW_TRADE_FLOW` flag enabled:
Success and failure inner step indicators should be small and non-throbbing again.
See above.
> fix: inner step styling

- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooter.tsx
Ensures that dynamic fees estimations are always done with the current hop, vs. only first hop previously.
closes N/A, see  https://github.com/shapeshift/web/pull/8432/files#r1903360919
Low, new swapper flow only, and isolated to fees estimation react-query query
- Perform a multi-hop swap
- Ensure fees look good for both sides
- ^
- ^
> fix: multi-hop fees estimation

- src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx
Better handles trade failure status in inner steps (new trade flow):
We now show the error icon instead of the "active blue circle".
Addresses review comment: https://github.com/shapeshift/web/pull/8192#discussion_r1889896655
Small
None
Ensure new trade flow is active (`REACT_APP_FEATURE_NEW_TRADE_FLOW`).
Cause a trade error during the confirmation flow - an easy way to do this is decline a transaction on Metamask etc.
Confirm step shows error icon.
See description.
> chore: handle holistic trade failure status in inner steps

- packages/swapper/src/swappers/ThorchainSwapper/endpoints.ts
- packages/swapper/src/swappers/ThorchainSwapper/types.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getCallDataFromQuote.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getL1ToLongtailQuote.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getL1ToLongtailRate.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
- packages/swapper/src/swappers/ThorchainSwapper/utils/getLongtailRate.ts
Makes `longtailToL1ExpectedAmountOut` and `L1ToLongtailExpectedAmountOut` serializable so they can be passed into React Query land and not crash the app.
Note, I'm not sure when this regression was introduced, but longtail is indeed broken rn.
Closes https://github.com/shapeshift/web/issues/8488
Medium
Longtail swaps
Ensure longtail swaps are great again.
Note, I was able to successfully perform an L1 to longtail swap, though I was having gas estimate issues for longtail to L1 swaps for what I believe is a different reason.
https://viewblock.io/thorchain/tx/3806cb6b24abe0eac3b7edd747c14ab8c8d5d702d8c181bdbbdb1b6343a5c46c
https://viewblock.io/thorchain/tx/179B6E6950039C7455C57A46C5DB472AAE9DB …
> fix: make longtail data serializable

- src/components/MultiHopTrade/components/LimitOrder/hooks/useGetLimitOrdersForAccountQuery.tsx
Fixes issue where orders in the list appear to be in random order.
https://discord.com/channels/554694662431178782/1324596242394644571/1325626856069660756
Create some limit orders, note what order you did them in.
Wait for them to execute, or cancel them.
View the historical orders
See https://discord.com/channels/554694662431178782/1324596242394644571/1325626856069660756
Created a fresh order for AIDOGE. Should appear at top of liste.
develop:
this pr:
> fix: limit order list sorted by creation date

- src/components/MultiHopTrade/components/TradeConfirm/hooks/useTradeButtonProps.tsx
Second hop Txs were broken with the new trade flow. The reason for that was the superfluous `isSignTxLoading` loading state directive.
This was being set to true on *trade* (not hop) initiation, and was never being set to false thereafter, meaning the second hop Tx would always be in a perma-loading state.
Fixed by removing `isSignTxLoading`. We actually have this guy which does what `isSignTxLoading` actually intended to:
https://github.com/shapeshift/web/blob/1b2fac1445ef5b49853957d1213cf4d1a9c4fee7/src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooter.tsx#L36
The difference being `hasClickedButton` actually resets to false on *hop* state changes, vs. being perma-set to true, so it achieves what the former intended to without breaking things.
- closes …
> fix: new trade flow multi-hop Txs

- src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TxLabel.tsx
Does what it says on the box - buy Tx hashes were producing a Tx link which was not matching prod i.e /orders/<hash> vs /tx/<hash>.
Fixed by ensuring we use the right txId / tradeId property depending on whether or not the current Tx is a buy Tx hash.
closes https://github.com/shapeshift/web/issues/8478
Low - CoW is the only one leveraging `isOrder` property and having different Tx links programmatic on txId / tradeId.
- Proceed with a CoW swap e2e
- Ensure both Tx links are valid 
- ^
- ^
- develop
https://explorer.cow.fi/orders/0x58e82e87cab4e04826bb621b5c3d14bfa7e0ec29935ce6d96b2ac5b0fef2dd34?tab=orders
- this diff …
> fix: new swapper flow cow buy Tx links

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
The swapper confirm screen was using the buyAsset of the first hop instead of the last hop
closes #8494
Low (presentational)
- Do a multihop swap (both new trade flow and old trade flow are affected, you can test both but the logic remain very similar)
- Confirm screen should show the correct buyAsset
n/a
n/a
w
> fix: confirm screen shows wrong buyAsset

- src/assets/translations/en/main.json
- src/plugins/walletConnectToDapps/components/modals/connect/ConnectContent.tsx
Adds an alert div with some text so people know on native wallet to be careful before they jeet out walletconnections.
Closes #5727  with text we aligned on. 
Low risk, is just a warning alert.
Spinup local, use native wallet to stare at coonect to Dapp button. 
Make sure it looks like this: 
Worked locally. 😅 
is above.
> chore: walletconnect out has helper text

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderBuyAsset.tsx
Fixes limit order buy asset chain drop-down having unsupported chain IDs.
https://discord.com/channels/554694662431178782/1324596242394644571/1325626856069660756
Very low. If this is wrong the cowswap API will prevent a quote coming back, so users are protected from any loss of funds etc.
Check limit orders buy asset chain drop-down only displays supported cowswap chain IDs
See https://discord.com/channels/554694662431178782/1324596242394644571/1325626856069660756
Before:
After:
> fix: limit order buy asset dropdown having unsupported chains

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeRates.tsx
Fix `getTradeRateInput` query returning `undefined` which causes console spew insanity on initial swapper load.
QOL.
Low risk.
N/A
Confirm initial load of swapper does not produce the console spew below.
☝️
☝️
> fix: undefined queryFn return

- src/components/AssetSelection/AssetSelection.tsx
- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/components/Modals/TradeAssetSearch/TradeAssetSearchModal.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderBuyAsset.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputBody.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/TradeAssetSearch/TradeAssetSearch.tsx
- src/components/TradeAssetSearch/components/SearchTermAssetList.tsx
Fixes theoretical issue where a user can select a supported asset on one chain, and then select a different chain, making the selected asset unsupported. No know examples of this, but an example:
1. Select xDAI on ethereum (doesnt exist but lets pretend it does)
2. Change chain "on" to gnosis
3. For limit orders, native sell assets are not supported so this would mean the user has selected an unsupported asset
https://discord.com/channels/554694662431178782/1324596242394644571/1325626856069660756
Check asset selection and chain selection in trade is still working fine.
> fix: prevent selecting chain if asset would become unsupported

- src/components/MultiHopTrade/components/TradeConfirm/ExpandableStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx
Improve padding on the new swapper flow to better handle small screens.
Progresses https://github.com/shapeshift/web/issues/8118
Small - style tweaks only.
N/A
Check new swapper flow still looks pretty when TX links render alongside streaming progress (monkey patch https://github.com/shapeshift/web/blob/0e0deca2747dfb3aaed49d1ffbdf4a10adc8da16/src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx#L334 by removing the conditional and hardcoding values if you'd like, or "trust me bro")
`develop`
This PR
> fix: handle small screens on new swapper flow

- src/components/MultiHopTrade/components/TradeConfirm/ExpandedStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/helpers.ts
Follows up on #8508 by *akschually* making the steps separate. 
While 8508 made sure we use nice copies for permit2 contract allowance / permit2 sign, this actually splits the two into separate steps.
Note, this is for new swapper flow only.
- closes https://github.com/shapeshift/web/issues/8505
Low
Test with new swapper flow flag on - effectively the same as https://github.com/shapeshift/web/pull/8508, except for the first case, where there should be two explicit steps.
- Infinite permit2 allowance grant step should be triggered, with sane looking copies that clearly explain what this is about
- Permit2 message signing step should be triggered, with sane …
> feat: actually make permit2 allowance/sign distinct steps

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
Does what it says on the box: we weren't guarding things well enough, and final quotes *could* potentially refetched (they shouldn't, but they may in rare conditions with THORChain streaming swaps, see https://github.com/shapeshift/web/pull/8526 for more context) after clicking sign and swap.
closes https://github.com/shapeshift/web/issues/8521
Medium - touches final quotes logic
- Add the monkey patch below for THOR streaming swaps
```diff
diff --git a/packages/swapper/src/swappers/ThorchainSwapper/utils/getL1Rate.ts b/packages/swapper/src/swappers/ThorchainSwapper/utils/getL1Rate.ts
index 7531cdba77..46f8e41e8d 100644
--- …
```
> fix: don't refetch final quotes after swap Tx has been initiated

- packages/swapper/src/swappers/ThorchainSwapper/utils/getL1quote.ts
A one-line diff with a *lot* that goes on it, let's decipher it:
Currently in develop, both `getTradeQuote` and `getTradeRate` for THOR use some filtering logic where, if the expected_amount_out is the same for streaming and regular THOR quotes, then we filter the streaming one out so as not to produce useless dupe quote:
https://github.com/shapeshift/web/blob/ebfd6f1c3dabb5969299ce22f195da18d572cd62/packages/swapper/src/swappers/ThorchainSwapper/utils/getL1quote.ts#L162-L167
This is all nice and well except when it isn't: THOR has a tendency to *non-deterministically* yield streaming quotes every once in a blue moon. This can be seen in the testing Jam, where I had to attempt many, many tries for that pair to get a streaming quote for $3100 ETH -> BTC same like @MbMaria did when …
> fix: thor trade quote don't filter streaming routes out

- src/components/Layout/Header/NavBar/UserMenu.tsx
Fixes ENS reactivity/reset issues by using a react-query, or rather using wagmi's `useEnsName` which does precisely that under the hood for us, cleaning things up a bit while at it.
closes https://github.com/shapeshift/web/issues/8535
Low
- ENS is happy for EVM wallets with ENS
- Going from an EVM wallet with ENS to a Ledger without ENS doesn't display a stale ENS
- ^
- ^
- This diff
https://jam.dev/c/56cda424-3f1b-4e4e-baad-c9a3a23e7f42
- develop
https://jam.dev/c/4635c6ea-dc26-4222-bec6-8c10f62345e1
> fix: wallet button stale ENS addies

- src/theme/theme.tsx
Use `nth-of-type` over `nth-child` selector to "improve SSR" - but that isn't super useful for us.
The main benefit here is to make the annoying console log spew go away by replacing it with a best practice equivalent selector.
Still target the same `div`:
and toasts still look good (tripled to test rendering):
QOL
Low
None
See description.
N/A
N/A
See above.
> fix: use nth-of-type selector

- src/components/ChainDropdown/ChainDropdown.tsx
- src/pages/Dashboard/components/DashboardChart.tsx
- src/pages/Dashboard/components/DashboardHeader/WalletBalance.tsx
- src/state/slices/portfolioSlice/selectors.ts
The logic in `selectPortfolioTotalUserCurrencyBalanceExcludeEarnDupes` appears to not do what it claims (it's possibly been rugged by upstream changes since it's inception).
The current logic to calculate the total portfolio balance filters out the balances of assets that _also_ exist as an opportunity on that wallet.
This is problematic, illustrated in a few cases below:
**UniswapV2 ETH/FOX Pool**
In this case, the $7.79 is ignored when calculating my balance, but the DeFi amounts are included. We actually want _all_ balances to be included.
**Sablier streams**
The presence of FOX as an opportunity causes the value of the FOX in the wallet to be ignored, causing the balances to be off.
Closes https://github.com/shapeshift/web/issues/8530
Medium - low …
> fix: count both defi & asset balances

- src/components/Modals/Settings/Settings.tsx
The currency dropdown didn't have enough place and was overflowing it's container
We can't fix it anyway else than reducing the font size (less readable) or increasing the modal size
I did choose the modal size increase so everything has more place and even if we reduce the font size, on specific languages, it could be overflowing!
closes #8485
- Open the Settings modal
- Play with it, go to currency selector
- Change the language and play with the whole component too
- Nothing should be overflowing the container
n/a
n/a
> fix: increase settings modal size

- src/App.tsx
- src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
- src/context/WalletProvider/KeepKey/components/Passphrase.tsx
- src/context/WalletProvider/KeepKey/components/Pin.tsx
- src/context/WalletProvider/Ledger/components/Chains.tsx
- src/context/WalletProvider/NativeWallet/components/EnterPassword.tsx
- src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
- src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts
- src/context/WalletProvider/WalletConnectV2/useWalletConnectV2EventHandler.ts
- src/context/WalletProvider/WalletProvider.tsx
- src/context/WalletProvider/WalletViewsSwitch.tsx
- src/context/WalletProvider/actions.ts
- src/pages/Accounts/AddAccountModal.tsx
Patch for state corruption in wallet provider when user backs out of switching wallet. See #7904 for context.
The fix here is a patch to prevent corrupt state by preventing "back-out" of native connect into corrupt state by forcing the previous wallet to first disconnect before the password prompt is displayed.
Previous issue in simplified terms:
1. User is connected to native wallet
2. User clicks "switch wallet"
3. User clicks different native wallet and is presented with password prompt
4. WalletProvider updates the `deviceId` with the new wallet device ID
5. User exits the password prompt without entering the password
6. WalletProvider now has the wrong `deviceId` until they reconnect the wallet
This PR:
1. User is connected to native wallet
2. User clicks "switch wallet"
3. User …
> fix: wallet state corruption round 4

- src/state/slices/tradeQuoteSlice/helpers.ts
Does what it says on the box: pushes quotes without network fees (effectively Portals) at the end of happy quotes list.
closes https://github.com/shapeshift/web/issues/8143
Low
- Get rates for a pair where Portals is an option (i.e EVM same-chain route)
- Notice Portals is pushed at the end of happy quotes
- In case of errored quotes (e.g not enough native asset for gas), note Portals is *before* the errored ones
- ^
- ^
See this diff (left) vs. develop (right):
> feat: deprioritize happy quotes without network fees

- src/context/AppProvider/hooks/useAccountsFetchQuery.tsx
Query functions need to return _something_. Fixes console spew when a Ledger is connected:
QOL
Minimal
N/A
The above console spew when connected to a Ledger should now longer show.
☝️
☝️
See above.
> fix: undefined useAccountsFetch queryFn return

- src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
Ensures the receiveAddress query does not return `undefined`, which can cause issues due to the way TanStack query handles query state.
Spotted by @NeOMakinG in https://github.com/shapeshift/web/pull/8543?new_mergebox=false#pullrequestreview-2546023848
Low
None
Ensure we no longer see the console warning.
☝️
☝️
> fix: ensure receiveAddress query -> string | null

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeNetworkFeeCryptoBaseUnit.tsx
What the box say, this precisely does.
- closes https://github.com/shapeshift/web/issues/8560
- relates to https://github.com/shapeshift/web/issues/8574
Low to none
- Ensure network fees still refetch at 15s interval (assuming your window/tab is active) while the Tx for the current hop hasn't been initiated
- Ensure fees are *not* refetched anymore after signing and broadcasting the Tx for the current hop.
- ^
- ^
https://jam.dev/c/76327510-a741-4d27-b786-24ae66c882fb
> feat: stop refetching network fees after hop execution

- packages/swapper/src/swappers/ThorchainSwapper/endpoints.ts
i.e instead of letting the API say we're done, assume done as soon as out Tx is seen (meaning it hit the mempool, and we have updated balances accordingly in app)
- relates to https://github.com/shapeshift/web/issues/8534
Low
- Confirm THOR status detection is still happy, and as soon as you can see the out Tx, swapper goes to trade confirmed state
- Confirm status detection of swaps to ROON are still happy
- ^
- ^
Non-ROON out
https://jam.dev/c/85ffba07-e940-4566-8fd6-de349fd7bf4d
ROON out
https://jam.dev/c/ef690eb4-da39-4583-beb1-fddf54087e7c
> feat: thor swapper simplify status detection

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeNetworkFeeCryptoBaseUnit.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooter.tsx
Tackles this guy https://github.com/shapeshift/web/pull/8570#pullrequestreview-2551108018:
> Suggestion: Architecturally I'd prefer to see this logic in `components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooter.tsx` and passed down in the `enabled` prop  of `useTradeNetworkFeeCryptoBaseUnit` so that the `useTradeNetworkFeeCryptoBaseUnit` hook doesn't concern itself with the current state.
closes N/A
Low - same logic, but now passed from the parent.
- Network fees should still stop fetching after sign and broadcast has been clicked
- ^
- ^
https://jam.dev/c/39d2fc16-becc-4b89-85ea-d14192fa664f
> feat: cleanup useTradeNetworkFeeCryptoBaseUnit

- packages/caip/src/adapters/coingecko/index.ts
- src/lib/coingecko/constants.ts
- src/lib/coingecko/utils.ts
Supports more assets/chainIds in the markets page: BTC, BCH, LTC and Solana.
- closes https://github.com/shapeshift/web/issues/8482
Low/none
- The aforementioned assets are surfaced in the markets page and available wherever relevant (i.e market data / volume should show most/all of them)
- Top Gainers / Losers will most likely show Solana tokens (double-check on Coingecko's https://www.coingecko.com/en/crypto-gainers-losers) since Solana shitcoins are all the rage these days.
- ^
- ^
> feat: markets page support more assets

- src/components/TradeAssetSearch/TradeAssetSearch.tsx
- src/components/TradeAssetSearch/hooks/useGetPopularAssetsQuery.tsx
- src/lib/market-service/market-service-manager.ts
Changes heuristics so that:
1. We display 6 quick-list popular assets instead of 1
2. The popular assets query used uses the market_cap_desc coingecko filter instead of volume_desc previously
closes https://github.com/shapeshift/web/issues/8141
Low
- The popular asset quick-list is a 6-count of Coingecko's assets sorted by market cap desc (i.e, the homepage of cg, which uses market cap desc as a default criteria). 
- Scrolling down from "My Assets" to "Popular Assets" also displays a sane list when comparing against cg
Note 1: the list may look slightly different depending on wallet support e.g Solana or non-EVM chains support
Note 2: BNB duplicates (or …
> feat: popular assets by market cap desc

- packages/swapper/src/swappers/CowSwapper/endpoints.ts
a.k.a if we have a buy Tx hash, we're done, else we're pending, easy as.
Makes it so we don't have to hit the status endpoint, which is simpler, more performant and potentially faster in case the API takes longer to reflect the status.
Cancelled, expired, pending and unknown were actually non-issues: we were checking for these after the buyTxHash checks. You could *never* end up there, since, if we have a buyTxHash, the swap is a success.
- relates to https://github.com/shapeshift/web/issues/8534
Low
- CoW status detection is happy
- ^
- ^
https://jam.dev/c/a4059902-80cf-4879-b250-1c4b08c49495
> feat: cow swapper simplify status detection

- packages/swapper/src/swappers/LifiSwapper/endpoints.ts
Or well, not exactly. More like being consistent with CoW and Chainflip by early returning on seen Txs - in effect, should be a no-op for the specific case of Li.Fi.
closes https://github.com/shapeshift/web/issues/8534
Low - seemingly a change of heuristics (early return on seen Tx vs. waiting for "DONE" status), though, in effect, both are true at the exact same time.
- Li.Fi status detection is still happy
- ^
- ^
https://jam.dev/c/67cdc603-08f1-4321-a648-e20439cc514d
> feat: lifi swapper simplify status detection

- src/assets/translations/en/main.json
- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
Fixes the chain dropdown appearing as empty when no wallet is connected.
But this PR includes a bunch of bonus features:
- If no wallet is connected, ALL chains are available to select from, allowing user to freely use our app without restrictions
- When the connected wallet supports a chain but doesn't have a connected account for that chain, the chain appears in the drop-down but with a disabled state and tooltip `This chain is not connected to your wallet. Connect %{chainDisplayName} to trade this asset.`
- When the connected wallet does NOT support a chain, the chain appears in the drop-down but with a disabled state and tooltip `This chain is not supported by your wallet. Switch to a different wallet to trade this asset.`
- If the currently selected chain is no longer …
> fix: empty chain dropdown when no wallet connected

- src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeNetworkFeeCryptoBaseUnit.tsx
Follows up on https://github.com/shapeshift/web/pull/8570 (the accidental, actual fix for https://github.com/shapeshift/web/issues/8574) with another paranoia fix for consistency, which, if we used in the first place, would *also* be an actual fix.
The reason why Ledger signing was borked was because of `useTradeNetworkFeesCryptoBaseUnit` calling `adapter.getAddress()` without a `pubKey` property, meaning we use on-device derivation to get the address.
This would *normally* be fine when we're able to get an address from the Ledger, we definitely should prefer that vs. using a pubKey we got somewhere from the app state, unfortunately, that's not always possible.
Unfortunately, in this precise case, it was not: making a device call to get the address while Tx signing is in-flight will …
> fix: swapper paranoia ledger signing fix

- src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
Staked amount wasn't accounting for PNL, hence trying to do a naive deposit amount - withdraw amount wouldn't cut it, as the former will be the *current* deposit amount, which can be lower (or higher) than the initially deposited amount.
When accounting for the pnl offset, we end up with 0 as expected e.g:
```json
{
"rune_address": "thor125dwsa39yeylqc7pn59l079dur502nsleyrgup",
"units": "0",
"value": "0",
"pnl": "60621268",
"deposit_amount": "734392497",
"withdraw_amount": "795013765",
"last_deposit_height": 18731307,
"last_withdraw_height": 19518011
}
```
734392497 - 795013765 = -60621268, which is precisely the pnl delta.
Note, this bug wasn't related to full withdraws per se. Full withdraws only made this obvious, but displayed amounts were wrong regardless.
closes …
> fix: runepool incorrect balance not accounting for PnL

- src/context/WalletProvider/NewWalletViews/sections/HardwareWalletsSection.tsx
- src/context/WalletProvider/NewWalletViews/sections/OthersSection.tsx
Spotted by @0xApotheosis in ttps://github.com/shapeshift/web/pull/8629#discussion_r1923078663:
> Is it feasible to have an enum of wallet id strings? Seems a little messy to have these string literals everywhere. 
It indeed is, here she is!
- relates to https://github.com/shapeshift/web/issues/8471
None
- Paranoia test that all wallet options are still happy with the `REACT_APP_FEATURE_NEW_WALLET_FLOW` flag on.
None
https://jam.dev/c/03eaa90e-afc9-4ef8-a670-a02b735c8262
> chore: new wallet flow dont use magic strings for selectedWalletId

- src/context/WalletProvider/NewWalletViews/NewWalletViewsSwitch.tsx
Tackles this spotted issue by @0xApotheosis on new wallet flow:
> Noticed one bug that is not a regression in these PR where Brave breaks the back button 
https://github.com/shapeshift/web/pull/8616#pullrequestreview-2563422890
And indeed, Brave (as well as other non-first-class MIPD wallets *do* have borked back button i.e not displaying.
Fixed back behaviour two ways:
1. Displays it for said mipd providers by changing the display heuristics
2. Ensures that the back button resets (i.e routes back to the native CTA) when needed, vs. doing a dumb history.back(), which may produce weird behaviour as you cycle through options.
- relates to https://github.com/shapeshift/web/issues/8471
> What protocols, transaction types, wallets or contract interactions …
> fix: new wallet flow back button shenanigans

- src/context/WalletProvider/NewWalletViews/NewWalletViewsSwitch.tsx
Tackles some smolish issues spotted by @NeOMakinG in https://github.com/shapeshift/web/pull/8635#pullrequestreview-2564782850, and some.
- relates to https://github.com/shapeshift/web/issues/8471
With the `REACT_APP_FEATURE_NEW_WALLET_FLOW` flag on:
- clicking back button and back to main intro should reset currently selected wallet 
- back button should not be clickable while pairing is in-progress
- errors from one mipd provider should be when selecting another mipd provider
- refreshing the app, native unlock route should have the wallet being unlocked as selected
None, all under flag 
- clicking back button and back to main intro should reset …
> fix: new wallet flow misc. UX shenanigans

- src/context/WalletProvider/WalletViewsRouter.tsx
Precisely what it says on the box.
- relates to https://github.com/shapeshift/web/issues/8607 - disables the feature there altogether until we agree on wat do with @shapeshift/product
Low/None
- Run with the mobile app set to localhost, or deploy me on your env (not gome as it will be used for final new wallet flow testing) and ensure the current wallet flow is used on mobile
None
> feat: new wallet flow disable for mobile app

- src/assets/translations/en/main.json
- src/context/WalletProvider/NewWalletViews/NewWalletViewsSwitch.tsx
- src/context/WalletProvider/WalletViewsRouter.tsx
feat: add dot (#8644)
feat: new wallet flow disable for mobile app (#8643)
fix: new wallet flow misc. UX shenanigans (#8640)
> chore: release v1.742.0

- src/components/ChainDropdown/ChainDropdown.tsx
Fixes the chain dropdown total balance by including staked balances, which the individual chain row balances already include. The total balance is now great (though not again, I don't think it ever was).
**Production**
**This PR**
None, found whilst working on the related https://github.com/shapeshift/web/issues/8530
Small
None
With a wallet connected that has staking balances, ensure the chain dropdown component (used on the Markets page) shows the correct total balance (the sum of all chain balances).
☝️
☝️
See above.
> fix: chain dropdown balance total

- src/lib/coingecko/utils.ts
Adds DOGE to the markets page, I'm not sure why that was never on the supported assets list as CoinGecko does indeed support it: https://api.coingecko.com/api/v3/asset_platforms
Closes https://github.com/shapeshift/web/issues/8691?reload=1
Minimal
Market page listings only.
Ensure DOGE is now avaiIable:
☝️
☝️
See above.
> feat: add doge to markets

- src/components/MultiHopTrade/components/TradeConfirm/components/ExpandableStepperSteps.tsx
The existing countdown logic did not handle longer durations such as bridges, which can take days.
This rectifies that, along with another bug where the seconds/hours would now show if they were 0 (happens once a minute and once an hour!)
Addresses @gomesalexandre review feedback here: https://github.com/shapeshift/web/pull/8687#pullrequestreview-2580837331
Small
N/A
Ensure countdowns work as expected, including longer bridges.
☝️
☝️
> fix: longer countdown durations with days

- src/Routes/RoutesCommon.tsx
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/pages/Trade/Trade.tsx
This PR brings pre-populated asset from the URLs, bonus adds a pre-populated amount from the URL as base unit
Here is the structure:
`/trade/buyAssetId/sellAssetId/amount`
closes #8624
High because swapper router
- Go to the swapper route
- Select any asset to any asset
- Copy the url and try to access directly from the URL, assets should be pre-populated
- Try to input an amount, test the same thing, amount should be prepopulated
- Try also with only a sellAssetId in the url, it should work as before
- Try to come from the arb bride claim route (to test deeplinks)
- Try to switch to differents tabs (limit tab, claims tab...)
- Try a swap, should work as …
> fix: pre-populated swapper assets url

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderCard.tsx
- src/components/MultiHopTrade/components/LimitOrder/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/LimitOrderV2/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrderV2/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/LimitOrderV2/hooks/useAllowanceReset.tsx
- src/components/MultiHopTrade/components/TradeConfirm/hooks/useAllowanceApproval.tsx
- src/components/MultiHopTrade/components/TradeConfirm/hooks/useAllowanceReset.tsx
- src/hooks/mutations/useApprove.ts
- src/hooks/queries/useApprovalFees.ts
- src/hooks/queries/useIsAllowanceApprovalRequired.ts
- src/pages/RFOX/components/Stake/Bridge/hooks/useRfoxBridgeApproval.tsx
- src/pages/RFOX/components/Stake/hooks/useRfoxStake.tsx
- src/react-queries/hooks/useAllowance.ts
The reason why we want to be granular is precisely becaus as soon as we set `isDisabled`, we were early returning, resulting in no stale data (which we want) but instead *no* data.
With the two explicitly split, this isn't a problem anymore.
Note one user-facing difference with this: we're now so fast in refetching approval fees that loading state *is* technically present but effectively lost.
closes https://github.com/shapeshift/web/issues/8702
Low
- For limit orders, approval fees should *not* go to zero after initiating the Tx
- For spot, approval fees should *not* go to zero after initiating the Tx
- For both spot and limit, refetching of approval …
> feat: allowance queries split query enabled and refetch enabled

- src/components/StakingVaults/hooks/useFetchOpportunities.tsx
- src/state/apis/portals/portalsApi.ts
- src/state/migrations/index.ts
- src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
We *technically* support all UNI-V2 opportunities as first-class, not just UNI-V2, but we *actually* don't because these are perf bottlenecks.
This ensures ghost opportunities are not upserted anywhere, resulting in ghost balances/eligible opportunities.
closes https://github.com/shapeshift/web/issues/8720
Low
- UNI-V2 DeFi balance only accounts for ETH/FOX
- No ghost UNI-V2 elligible opportunities are displayed
- ^
- ^
- Develop
- This diff
> fix: uni-v2 don't upsert ghost opportunities

- src/state/apis/portals/portalsApi.ts
- src/state/slices/opportunitiesSlice/resolvers/uniV2/index.ts
*Actually* does what it says on the box.
closes N/A
Low (read: the actual fix)
- UNI-V2 opportunities are *not* double-counted in the grand total for UNI-V2
- ^
- ^
> fix: uni-v2 opportunities double-counted in total (the actual fix for real this time 🙅🧢)

- src/components/AssetAccountDetails.tsx
- src/components/MultiHopTrade/MultiHopTrade.tsx
- src/pages/Accounts/AccountToken/AccountToken.tsx
I broke the buyAsset auto selection in asset pages, this PR bring it back but also improve the logic behind:
- If the buyAsset is selected, populate the sellAsset with the native asset of the selected buyAsset chain so we don't end up with things like ETH to LP WAVAX/PENDLE Joe on AVAX, using Native asset to token ensure we have a route for this default swapper config
- If it's a native asset, it auto populate it as sellAsset to ETH
- Did this for both account swapper, asset page swapper
I think before merging this, it would be cool to confirm with @shapeshift/product the behavior
n/a
Low
- Go to account details page, assets should be populated properly …
> fix: add default buy asset and set assets to inner swappers

- src/components/MultiHopTrade/components/LimitOrderV2/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
- src/components/TransactionHistoryRows/TransactionRow.tsx
- src/hooks/useTxDetails/useTxDetails.ts
Uses actual on-chain amounts (either in token or native asset) to display the final receive amount in trade complete.
Note: This only works for receive addresses for which accounts are in the store, and does *not* work for custom receive addresses, since we don't hold these ones in store.
closes https://github.com/shapeshift/web/issues/8719
Low
- Test swaps *without* a custom receive address display the actual on-chain received amount in trade complete
- Notice how swaps *with* a custom receive address display the same receive amount as originally quoted (which may or may not be a discrepancy)
- Ensure limit orders are still happy
- ^
- ^
- Custom receive …
> feat: swapper trade complete actual on-chain receive amounts

- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/solana/SolanaChainAdapter.ts
- src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
- src/components/TransactionHistoryRows/TransactionRow.tsx
- src/hooks/useTxDetails/useTxDetails.ts
Stretch on top of #8736, using similar logic but instead fetching for the network so we're able to fetch Tx data for external Txs (i.e the ones not existing in the Tx store since those are from manual receive address accounts)
- relates to #8736
Low/Medium
- Ensure trade complete step amounts still look sane without any weird flash of content
- ^
- ^
https://jam.dev/c/a2941074-961d-41f9-9281-71e6d05ec190
> feat: best effort fetch buy Tx amount for manual receive address

- src/components/FeeExplainer/FeeSliders.tsx
- src/components/FeeExplainer/common.tsx
Updates the FOX power graph to remove the amount of "dead space" in the FOX slider.
Production:
This branch:
Closes https://github.com/shapeshift/web/issues/7978
Small
None
Play with the FOX power chart and ensure it still makes sense.
☝️
☝️
See above.
> chore: update fox power graph params

- src/components/MobileWalletDialog/MobileWalletDialog.tsx
- src/components/MobileWalletDialog/routes/CreateWallet/CreateBackupConfirm.tsx
- src/pages/ConnectWallet/MobileConnect.tsx
Mobile home create wallet should be using the new dialog mobile drawer
- Import is not included in this PR as it's not down already in the new drawer, an issue has been created
closes #8774
- Go to the home page on mobile, create a new wallet, it should use the new drawer and working as expected
- Please be careful that the welcome modal is shown after creating a wallet
n/a
https://jam.dev/c/b97b9070-277d-4412-9ba4-68e923bc7597
> fix: add mobile dialog on mobile home page

- src/components/Modal/components/Dialog.tsx
By disabling input reposition for every behavior, full screen views was behaving weird, enabling it if it's a fullscreen view make the send modal great again
closes #8806
Low
- Try to use the send feature using a mobile with the keyboard working and see if everything is fine!
- Pushed on `gome` for easier testing
n/a
n/a
https://jam.dev/c/16301db0-7df8-48d6-a666-f9562775b3f5
> fix: enable drawer input reposition if isFullScreen

- src/components/Modal/components/Dialog.tsx
fix: enable drawer input reposition if isFullScreen (#8808)
> chore: release v1.766.0

- src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
- src/pages/Lending/Pool/components/PoolInfo.tsx
- src/pages/Lending/components/LendingHeader.tsx
A fast-follow to https://github.com/shapeshift/web/pull/8815, but this time we include a link that we know will never expire. The default is 7 days, this one is infinite:
Relates to https://github.com/shapeshift/web/issues/8814
Small
N/A
URL should point to THORChain Devs Discord.
☝️
☝️
N/A
> fix: discord url that does not expire

- src/components/MultiHopTrade/components/TradeConfirm/components/ExpandableStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/components/ExpandedStepperSteps.tsx
- src/components/MultiHopTrade/components/TradeConfirm/hooks/useHopProgress.ts
- src/state/slices/tradeQuoteSlice/constants.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
- src/state/slices/tradeQuoteSlice/types.ts
What this PR does:
- Brings in the notion of less dumb progress, currently heuristics-based
- a sell Tx contributes to 50% of a hop completion 
- an effective complete state for a hop is 100% (as the hop is... well, conplete?)
- Swaps consist of hops, and the holistic progress is the sum of both hops divided by 2 
- Wires up said notion 
- in the holistic progress bar 
- in each step, using circular progress with the current progress of a given hop 
- Removes the status messaging from the current hop and move it up top to the top-level swap view, so hops always reflect their name and don't flash status updates 
What this PR does not:
- bringing a best-effort parsing of different substeps to percent progress for a given hop for Li.Fi, THOR, Chainflip
- only partially tackles #8575 
> High …
> feat: hop/swap progress improvements

- src/components/Layout/Header/NavBar/MobileNavBar.tsx
- src/components/Modal/components/Dialog.tsx
Clicking outside the mobile drawer was not closing the drawer, fixed it by adding a click event on both overlays!
closes #8713
Low
- Open mobile drawer (on mobile app for example)
- Click outside of the drawer, it should close
- Use any thing inside, it should not close the drawer if it's not supposed to close it
n/a
n/a
https://jam.dev/c/d6993882-a87c-4b84-9c24-acce8c2fd640
> fix: close on click outside mobile drawer

- src/hooks/useHasFocus.tsx
Fixes the `useHasFocus` hook to actually set on `blur`.
Also adds support for `resume` for mobile applications, ensuring the state is correctly updated when unlocking the phone etc.
Inspired by https://github.com/shapeshift/web/issues/8731
Medium - risk that polling breaks and users can't get quotes.
Swapper quotes.
The easiest way to test this is to open the developer console. Navigate to the network tab and observe that whilst the developer pane is active we won't fetch quotes.
Then, click back into the app and we'll continue fetching (timer will reset, and we'll fetch a quote at the end).
Check mobile still works as expected - quotes poll, and resume …
> fix: useHasFocus

- src/state/slices/tradeQuoteSlice/selectors.ts
What it says on the box, literally. There was a bug in the selector that was reacting on data presence or lack thereof, which would not work on refresh and would consider quotes to be loading when they in fact aren't.
closes https://github.com/shapeshift/web/issues/8738
Low
- Get a quote for e.g ETH -> BTC
- Notice there are no loading swappers that shouldn't which are perma-loading (i.e unsupported ones for this pair which aren't actually loading)
- Wait for the auto-refresh 
- Note there *still* aren't any perma-loading
- ^
- ^
https://jam.dev/c/65aec27f-b8d8-4537-9053-56c91603188e
> fix: selectIsLoading swappers should select loading swappers

- src/lib/fees/parameters/swapper.ts
Changing max_fee_bps to 69 as per DFC vote 99: https://discord.com/channels/554694662431178782/920449863408287855/1331381886248812607
no issue
low-risk but needs testing.
needs testing
spin up wallet without any fox. makes sure fees are accurate. 
halp?
when ready, test fees please
no screenshots
> chore: Update Fee Model to increase Max_Fee_BPS to 69

- src/lib/fees/model.test.ts
Fixes CI after https://github.com/shapeshift/web/pull/8825.
N/A
Low
☝️
N/A
N/A
> fix: ci after fee bump

- src/state/slices/tradeInputSlice/tradeInputSlice.ts
Updates the default buy asset to BTC (replacing FOX).
Closes https://github.com/shapeshift/web/issues/8801
Small
N/A
On initial load the default asset pair should be ETH to BTC.
☝️
☝️
> chore: change default buy asset to btc

- .env.base
Updates the Polygon Alchemy key, as the old one has become inactive (I don't know who's account it was on, but the new key uses the current account):
N/A - prod issue
Low
Unstoppable domain resolution on Polygon.
- Unstoppable domain on Polygon should work
- Requests to `polygon-mainnet.g.alchemy.com` should be successful
☝️
See network tab, ensure requests are 200ing.
☝️
N/A
> chore: update alchemy polygon key

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
Allows users to click the selected quote as many times as they want without the second click reverting the selection back to active
closes #8841
None
- Go bananas clicking around in quotes 
- Clicking on a quote should always select it, or keep it selected if selected, no weird unselection
- ^
- ^
https://jam.dev/c/ab6be634-112e-46cb-883e-aeb21e566bf1
> fix: confusing quote un/select behaviour

- src/Routes/RoutesCommon.tsx
Spotted by @kaladinlight in https://github.com/shapeshift/web/pull/8898#discussion_r1964125746
Note, this removes the *route*, not the actual `<TransactionHistory />` component which *is* used in dashboard.
closes N/A
None
- Paranoia test activity routing is still happy
- ^
- Paranoia grep for `transaction-history` and ensure this route is indeed not used anywhere
- ^
https://jam.dev/c/bbeea339-945b-4b0f-a431-83112d9eed79
> feat: remove unused "nav" route

- scripts/release.ts
Makes 2 quality of life fixes to the release script:
1. Fetches _before_ we invoke `isReleaseInProgress`. If your local git state isn't up to date we can end up in a place where the script thinks it needs to create a new release, but one already exists
2. Creates the release diff using the range of commits _since the last release tag_. The fixes the issue of us creating a release containing commits/PRs that were hotfixed in the previous release (caused by different commit hashes in the cherry-picked hot-fix).
N/A - QOL
Low
Release script only.
Sanity check that the `yarn release` still does what we expect it to!
No testing needed here.
N/A
> fix: improve release script

- src/context/WalletProvider/NativeWallet/hooks/useNativeSuccess.ts
Aligns `useNativeSuccess` with `useMobileSuccess`, which *does* set the modalType properly on creation:
https://github.com/shapeshift/web/blob/cadb5617f96f1ec7407b54b547d4c551929002aa/src/components/MobileWalletDialog/routes/CreateWallet/CreateSuccess.tsx#L71
This meant that the `modalType` right after creation would either be none (no previous wallet connected) or the one of the previously connected wallet, which could produce a bunch of small bugs,
including that one.
After rehydration however, and when the `modalType` was reconciliated, then things worked as they should and users were able to backup their wallet.
closes #8879
None, this was a blatant bug.
> What protocols, transaction types, wallets or contract interactions might be affected by this …
> fix: modalType not set on native creation

- headers/csps/chains/arbitrum.ts
- headers/csps/chains/arbitrumNova.ts
- headers/csps/chains/avalanche.ts
- headers/csps/chains/base.ts
- headers/csps/chains/bitcoin.ts
- headers/csps/chains/bitcoincash.ts
- headers/csps/chains/bnbsmartchain.ts
- headers/csps/chains/cosmos.ts
- headers/csps/chains/dogecoin.ts
- headers/csps/chains/ethereum.ts
- headers/csps/chains/gnosis.ts
- headers/csps/chains/litecoin.ts
- headers/csps/chains/optimism.ts
- headers/csps/chains/polygon.ts
- headers/csps/chains/solana.ts
- headers/csps/chains/thorchain.ts
- headers/csps/chatwoot.ts
- headers/csps/defi/mtpelerin.ts
- headers/csps/fiatRamps/onRamper.ts
- headers/csps/plugins/foxPage.ts
- headers/csps/wallets/keepkey.ts
- headers/csps/wallets/walletConnect.ts
- headers/csps/wallets/walletMigration.ts
Continues on the work started in https://github.com/shapeshift/web/pull/8912 - only ~150 to go down from 300 when starting!
relates to #8909
Medium - this adds runtime checks for CSPs, ensure that both the dev build *and* actual build are not throwing on undefined CSPs
- Test *both* dev build and dist build and ensure things are looking gucci 
- You may see some CORS errors which are *not* related to this PR i.e those are actual upstream failures reflected as CORS, pretty easy to spot as the same URI works fine on other requests
- Do a smoke test of the app and ensure nothing breaks
- dev build: https://jam.dev/c/a0a1135e-e52d-4e0d-902e-20862185cab7
- …
> feat: don't non-null assert CSPs

- src/components/Modals/TradeAssetSearch/TradeAssetSearchModal.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderBuyAsset.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputBody.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
- src/components/TradeAssetSearch/TradeAssetSearch.tsx
- src/state/slices/common/tradeInputBase/createTradeInputBaseSelectors.ts
- src/state/slices/common/tradeInputBase/createTradeInputBaseSlice.ts
- src/state/slices/limitOrderInputSlice/limitOrderInputSlice.ts
- src/state/slices/limitOrderInputSlice/selectors.ts
- src/state/slices/tradeInputSlice/selectors.ts
- src/state/slices/tradeInputSlice/tradeInputSlice.ts
- src/test/mocks/store.ts
Precisely what it says on the box. Remembers the selected ChainId on a granular level:
- All instances (e.g limit and spot) have their own ChainId memory 
- Buy and sell AssetIds have independant ChainId memory
closes #8834
Low to none
- Play around with asset chain selection in spot and limit and ensure the selected chain is consistently remembered on selection
- ^
- ^
https://jam.dev/c/28d0ba53-7b82-4392-90c2-c5cb79c0560e
https://jam.dev/c/c5e7d075-c756-42f6-9091-f082586c18b2
> feat: asset selection remember selected ChainId

- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
Does what it says on the box, an unsupported swapper for a pair will never be, meaning it shouldn't be displaying refresh state.
closes https://github.com/shapeshift/web/issues/8833
Low
- Get into unsupported pair errored swappers (e.g ETH -> BTC or FOX -> BTC)
- Ensure there is no refresh countdown spinner 
- Get into a valid pair for the same swappers that were previously errored (e.g ETH -> FOX)
- Ensure those *do* display the spinner now
- ^
- ^
https://jam.dev/c/2f53eaef-4c9b-4f24-af8c-0a3ff12cd340
> feat: no rate refresh spinner on unsupported swappers

- src/components/Modals/Send/views/Confirm.tsx
Disabled the confirm buttons when fees are resolving
closes #8943
None
> fix: confirm button in send modal not disabled while fees resolving

- src/components/EarnDashboard/components/PositionDetails/StakingPositionsByProvider.tsx
Previously, with the byProvider view, we were redirecting to the RFOX page on click on the opportunity, this part was missing on the byAsset view, added it!
closes #8910
Low
- Go on the earn page
- Click on any RFOX opportunity/manage
- You should be redirected to the RFOX page
- Same on mobile
n/a
n/a
https://jam.dev/c/92a03d9b-cdcf-4b38-949d-3ceedf67186e
> fix: earn page redirect to rfox page if provider is rfox

- src/assets/translations/en/main.json
- src/components/Layout/Header/NavBar/Native/NativeMenu.tsx
- src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
- src/context/WalletProvider/Ledger/components/LedgerMenu.tsx
- src/context/WalletProvider/MetaMask/components/MetaMaskMenu.tsx
- src/context/WalletProvider/NewWalletViews/routes/NativeRoutes.tsx
- src/context/WalletProvider/NewWalletViews/wallets/native/NativeDelete.tsx
- src/context/WalletProvider/NewWalletViews/wallets/native/NativeRename.tsx
- src/context/WalletProvider/WalletProvider.tsx
- src/context/WalletProvider/actions.ts
- src/context/WalletProvider/types.ts
- Renamed Switch Wallet Provider to Switch Wallet
- Removed the chevron right in favor of a backup icon like on mobile
- Added Rename and delete buttons with icons
- Split between 2 groups and added a "Wallet action" header
- Added 2 new screens to the wallet modal so we can rename or delete the current wallet 
closes #8832
Low (was not existing before)
- Import multiple native wallets
- Try to rename them
- Try to delete them
n/a
n/a
https://jam.dev/c/e176c3c4-324a-4f75-a316-4f134ac9fe58
> feat: mobile and desktop wallet menu actions improvements

- src/lib/portals/utils.ts
Not sure what's happening here:
```
host-console-events.js:1 InvalidAddressError: Address "0x16344277b69bd724a92b9e06ba40f0ec5512bd8b6290b63862db757a8a94ba33" is invalid.
- Address must be a hex value of 20 bytes (40 hex characters).
- Address must match its checksum counterpart.
```
As the one addy which throws this seems to be correct according to https://app.uniswap.org/explore/pools/base/0x16344277b69bd724a92b9e06ba40f0ec5512bd8b6290b63862db757a8a94ba33), but is apparently not a valid ETH address for all checksum intents and purposes,
and is not visible on basescan either.
Either way, this fixes it!
closes https://github.com/shapeshift/web/issues/9022
None
> What protocols, transaction types, wallets or contract interactions might be affected by …
> fix: portals one-click defi assets

- src/context/WalletProvider/NativeWallet/components/NativeSuccess.tsx
Invalidate vault queries on success so any new creation flow won't use weird cache but new vault with new mnemonic
Only invalidate on success so if we get back using the routing, mnemonic and vault doesn't change
closes #8998
Low
- Create a native wallet
- Try to create another one
- And try to create another one
n/a
n/a
https://jam.dev/c/31c13673-9033-4695-8f80-2b39e44426c5
> fix: create multiple native wallets in a row

- src/components/Layout/Header/TxWindow/TxWindow.tsx
- src/state/slices/txHistorySlice/selectors.ts
- src/theme/theme.tsx
Remove tabs from the notification drawer, use only one, make sure pending TXs are always on top
leverage `.scroll-container` class to have a beautiful scrollbar instead of the system native one (don't worry windows user I'm here for you)
closes #8982
Low
- Open the notification drawer, it should be beautiful/working without tabs
- Try to do a swap (long swap like longtail with thorchain or rune to doge or BTC to ETH...)
- Pending TX should be on top of the list
- Bonus if you want you can do a fast TX after while waiting for the pending TX, the pending TX should stay on top of the list while the new completed TX should be under
n/a
n/a
> feat: single tx list in the notification drawer

- src/pages/RFOX/hooks/useCurrentApyQuery.ts
The rFox page, a key feature of the platform, has been incorrectly showing a 0% APY. The two APY display boxes are the highest contrast items on the page, which highlights their importance. File history suggests this bug has persisted since its inception 5 months ago, likely never working as intended. This fix corrects the container reference and order assumption to restore accurate APY display.
- `epochs[]` is sorted with the most recent first, so `previousEpoch` is at the start—not the end—breaking `closestRunePrice`. Adjusted to use the correct index.
- `closestFoxPrice` was pulling from `runePriceHistory` in `stakingAssetPriceHistory.find()`, likely a copy-paste error. Updated to reference the right data.
Tested locally—APY now displays accurately.
closes #9045 
> High Risk PRs …
> fix: rFox APY rate

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderBuyAsset.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
Users couldn't input 0 in limit orders inputs, it's particularly boring if you are dealing with high prices assets such as ETH
I used the ref in LimitOrderConfig to allow for user input, and added another state variable in `LimitOrderBuyAsset` to conditionally use the amount or the user-typed amount so we could allow users to type `0`, `0.` and other types of amounts
closes #9050
Low
- Try to play with the limit order inputs
- Try to empty the input, then type 0, then type 0.12, etc etc
- Try to switch between fiat amounts and crypto amounts
n/a
n/a
https://jam.dev/c/1192e012-ccf3-46cc-8017-6f0552b6aaee
> fix: allow users to type 0 in limit inputs

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputFooter/SharedTradeInputFooter.tsx
- src/context/AppProvider/AppContext.tsx
- src/state/slices/limitOrderSlice/helpers.ts
- src/state/slices/limitOrderSlice/selectors.ts
- src/state/slices/marketDataSlice/marketDataSlice.tsx
This PR:
- decouples loading state and quote fetching (only blocking confirm button now)
- ensures we refetch market-data at interval
- improves loading state so that things are reactive immediately, so long as we have market-data
closes https://github.com/shapeshift/web/issues/8999
Low
- Ensure there are now no loading states on inputs, relevant derived amounts, and rate/gas row
- Sanity check the EIP-712 data (by e.g using Rabby or MM) and ensure that the `buyAmount` and `sellAmount` are matching what we display
- ^
- ^
https://jam.dev/c/010a5c1b-de7f-4659-b2e9-1af603f173ee
> feat: make limit order better

- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
... precisely for the reason stated in the comment, unless a swapper pair/amounts reset happens (which does for e.g BTC), then the previous crypto sell amount will be used for the new default pair in standalone swapper.
closes https://github.com/shapeshift/web/issues/9047
Low/None
- Input some sell amount in regular swapper e.g 2 FOX on any chain
- Select another asset e.g USDC on Base/USDC on mainnet in asset search
- Ensure amount resets to zero on mini swapper
- ^
- ^
- develop
https://jam.dev/c/899f6aa4-662f-4ac6-8092-745e861b9119
- this diff
https://jam.dev/c/2401bfeb-7717-42c7-a6fb-d34d7b2b4658
> fix: reset sell amount on standalone swapper mount

- src/components/MultiHopTrade/components/SharedTradeInput/SharedSettingsPopover.tsx
Based on user feedback, we will be hiding the custom input field while auto is selected. This should avoid any confusion on what the slippage actually is for the trade.
closes #
Low risk
Go to the trade page.
Open the trade settings
Toggle auto to custom
You will see the custom slippage input appear
> feat: hide custom slippage input when auto is selected

- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderInput.tsx
- src/state/slices/limitOrderSlice/helpers.ts
Fixes issue where the limit ratio used for calculations is backwards: https://github.com/shapeshift/web/pull/9053#issuecomment-2731666028
Also ensures that `receiveAmountFormatted` is constant and does not change when `PriceDirection` changes.
N/A, blocking current release.
Low
Limit order quote UI.
Get limit order quotes and observe that the values make sense again (including fiat and price direction toggles).
👆
👆
See review comment above.
> fix: make limit orders great again

- src/state/slices/tradeQuoteSlice/helpers.ts
- src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
...in quotes sorting.
See [this comment](https://github.com/shapeshift/web/pull/9010#discussion_r1996051032):
> It's a bit of a confusing one and I was just as confused by it but yeah this is still needed!
There's kind of like two layers of errors:
"hard errors" meaning there was no quote gotten whatsoever, these go to "Unavailable"
"soft errors" (there was a quote but it's not actionable e.g not enough fundus, these get pushed at the end of the quotes list because they can't be actioned
This PR removes the logic pushing "soft-errored" quotes at the end of the list anymore, which doesn't play nicely with sorting. This also simplifies things as what we call errors are now actual 
errors and there's no mental overhead in trying to figure out an inherent and undocumented notion of "soft …
> feat: remove happy/error quotes buckets

- src/components/MultiHopTrade/components/LimitOrderV2/LimitOrderConfirm.tsx
- src/components/MultiHopTrade/components/LimitOrderV2/LimitOrderDetail.tsx
- src/components/MultiHopTrade/components/RateGasRow.tsx
- src/components/MultiHopTrade/components/SharedConfirm/SharedConfirmFooter.tsx
- src/components/MultiHopTrade/components/TradeConfirm/TradeConfirmFooter.tsx
- src/components/MultiHopTrade/components/TradeConfirm/components/TradeConfirmSummary.tsx
Gas row and footer spacing, background and style was off, this is some details but it makes it more professional!
See the before/after
None, on my own
Low, mainly visual
- Try swapper + limit and see if styles around the footer/confirm button/gas row is fine
- Also try to finish a swap and a limit and see if the style is fine
n/a
n/a
> fix: polish swapper footer and gas row style

- packages/swapper/src/swappers/ThorchainSwapper/endpoints.ts
- packages/swapper/src/thorchain-utils/memo/addLimitToMemo.ts
Precisely what it says on the box.
We were precisely checking for `out_txs` as our own only criteria for complete, however, a refund Tx *is* an out Tx.
This fixes it by:
- Checking for refund `planned_out_txs` (note, not in `out_txs` as refund data isn't present there as an explicit prop, only in the memo)
- Using the same buyTxHash we did above, but with error status for this specific branch. Note, `buyTxHash` could potentially be undefined if for any reason a planned out Tx cannot be sent, so this allows us to have our cake and eat it.
closes https://github.com/shapeshift/web/issues/9016
Low, relates to THOR refunds only
- Ensure THOR Txs still go …
> feat: thorchain swapper parse refund errors

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeRates.tsx
The `Quotes Received` event was sent even if there were no quotes, causing it to send useless event + sending an event on first render which is weird
closes #9079
Low
- I would suggest to make it tested by an engineer in local: monkeypatch to see when the user receive the quotes and compare with develop, the event shouldn't be sent until the user types some amount and receive quotes
- When releasing, check the network tabs, mixpanel quotes event shouldn't be sent until the user actually receive quotes
n/a
n/a
Hard to show but, no amount entered and no quotes fetch:
Amount entered and quote fetch:
> fix: send mixpanel quotes event only if the user receive quotes

- .env.development
- .env.test
- README.md
Fixes an issue where we use the wrong MixPanel project ID for the dev project.
N/A
Low
None
When locally devving with default dev env vars MixPanel events should work again.
👆
Retrosepcctively this will _probably_ backfill to develop.shapeshift.com(?)
See above.
> fix: use correct mixpanel dev project id

- src/components/Layout/Header/GlobalSearch/GlobalSearchModal.tsx
- src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
Moves the sell amount reset logic into `GlobalSearchModal `, so we don't have to rely on the life cycle of `TradeInput`
closes #9090
None
- Input any sell amount in mini swapper
- Choose another route
- Ensure the amount is not reseted
---
- Input any sell amount in regular swapper on any chain
- Select another asset on mainnet in asset search
- Ensure amount resets to zero on mini swapper
> fix: choosing a different swapper route in the mini swapper causes the input field to go to zero

- src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeRates.tsx
- src/lib/mixpanel/types.ts
Add a `RatesReceived` event to disambiguate the rates and quotes step. See the below flow chart for the current issue this PR will solve. The first event will be solved by https://github.com/shapeshift/web/pull/9091. The second by this PR:
N/A - general followup on helping the marketing team.
Low
None
Ensure the `RatesReceived` first when _rates_ are received.
👆
👆
See above.
> chore: add RatesReceived event

- src/AppProviders.tsx
Fixes the top-level QR code button (i.e the one on dashboard page, and in the app drawer menu on mobile) to not crash when scanning WalletConnect QR codes.
closes https://github.com/shapeshift/web/issues/8877
Low to none
- Top level QR code button is happy when scanning a WCV2 QR Code
- ^
- ^
- develop
- this diff
> fix: global qr code button WCV2 crash

- src/components/Modals/FiatRamps/views/Overview.tsx
Wraps the content in a box with minHeight so that content doesn't shift depending on the amount of providers (i.e default buy tab has one more than sell tab, which produced the content shift between the two).
closes https://github.com/shapeshift/web/issues/9140
None
- Fiat ramps buy/sell change doesn't shift content
- Things look the same as before on mobile
- ^
- ^
https://jam.dev/c/8c6ea211-3268-42ac-814e-f72d6b802bb3
> fix: fiat ramps content shift

- src/components/FoxWifHatBanner.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/components/HorizontalCollapse.tsx
- src/components/MultiHopTrade/components/TradeInput/hooks/useSharedWidth.ts
The current issue is when you're on the Trade/Bridge page on the limit section specifically and add or remove a number from the pay section you'll see some jitteriness when the order history side panel resizes (only on larger viewports like a desktop). 
This is because the current rendering strategy is to wait for the primary component to grow in height, detect that, then apply the same height to the side panel. This leads to an intermediary state where the primary component is larger or smaller than the side panel, before it then resizes to match the height. This leads to the flickering effect. 
Ideally all the components on the page would be auto resized with flex box. But that becomes fairly difficult with the Fox with hat component also sizing itself to match the width of the primary …
> fix: auto resize limit order with flex

- src/components/FoxWifHatBanner.tsx
- src/components/MultiHopTrade/components/LimitOrder/components/LimitOrderConfig.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInput.tsx
- src/components/MultiHopTrade/components/TradeInput/hooks/useSharedWidth.ts
This PR unreverts [this original change](https://github.com/shapeshift/web/commit/934c2233cf58d114b9d7cf2b838d1d03863bac74)
@NeOMakinG this PR has turned into a bit of a wild goose chase. If at any point you think this is too high risk for the potential payoff just let me know I'm more than happy to let this one go. I acknowledge that the issue this is fixing is potentially not worth it for potential broken layouts.
That being said i've fixed the known issues. Tested, found another issue and fixed that. And now hopefully all the bugs have been squashed. But considering the change here is a flexbox layout there could be a number of potential layouts and therefore edge cases that i've missed.
I've just added a condition not to hardcode the width if the shared trade input is standalone. I …
> fix: unrevert fix for limit order jittering when resizing 

- src/components/Modals/Send/AddressInput/AddressInput.tsx
Unblocks release by fixing an address validation boolean inversion caused by a bad merge of https://github.com/shapeshift/web/pull/9207.
Unblocks release https://discord.com/channels/554694662431178782/1357207369330982982/1357267075118403624 and closes https://github.com/shapeshift/web/issues/9251
Low
Address validation in send and manual reiceve address.
See ticket, valid address should not go red.
👆
👆
> fix: address validation inversion

- src/assets/translations/en/main.json
- src/components/MultiHopTrade/components/SpotTradeSuccess/SpotTradeSuccess.tsx
- Adds a 0.3 min surplus heuristic for displaying the surplus line
- Show as percentage instead of fiat (since displaying both the crypto, fiat, and percentage amount would be too much in one line)
closes https://github.com/shapeshift/web/issues/9193
Low
- Do a CoW trade 
- You will most likely not see the surplus line because of smol surplus, but if you do, it should only be a surplus greater than 0.3%
- Percentage surplus is displayed in surplus line
- Do a CoW trade
- If you see the surplus line, refer to testing steps above
- If you don't, comment out the min guard and let hot reload do its magic
- Comment it back and notice surplus line is gone again …
> feat: surplus improvements

- src/assets/translations/en/main.json
Removes the mention of the window auto-closing after importing a wallet (including for Ledger) as this feature is not used **on Mobile** and might confuse users. The user has to click the "View Wallet" button or close the modal to move on. On Desktop the modal usually displays so quickly that you can't read this, and if somehow it doesn't auto-close the instruction are still clear.
Translations will be invalidated during the next sync, the current translatons aren't harmful.
Approved/Requested by Product here: https://discord.com/channels/554694662431178782/1357702656227016887/1357773121553305672
None. Only English copies.
None.
Import a wallet / Ledger …
> chore: remove auto-close copy for import modals

- src/components/Modals/Send/AddressInput/AddressInput.tsx
- src/components/Modals/Send/views/Address.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedRecipientAddress.tsx
We need to adjust the padding for the trade custom address.
closes #9263 
low risk
When pasting or typing an address into the send modal or the custom recipient address, it should wrap and avoid the buttons to the right.
> fix: address runs into buttons on the trade form input

- src/components/MultiHopTrade/hooks/useIsManualReceiveAddressRequired.tsx
- src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts
This reverts commit 358a2af816c24520122b2bc12ecb035512bca368 merged in https://github.com/shapeshift/web/pull/9257.
https://discord.com/channels/554694662431178782/1358707166449500211/1358932611761700936
This breaks rFOX staking, and probably a bunch of other things:
I also get no EVMs on Mobile:
@gomesalexandre this line is super scary looking:
```ts
if (!isSnapInstalled) return null
```
What happens when the snap is not installed? We return `null` for any chain passed into `useWalletSupportsChain`?
> revert: "fix: mm snap flash of "Provide receive Address" (#9257)"

- src/components/Modals/FiatRamps/views/Overview.tsx
This fixes the not showing the empty state when there are no providers
Closes https://github.com/shapeshift/web/issues/9288
low risk
Go to the buy page, and select a currency other than USD. And if there are no providers you should see an empty state.
> fix: show empty state when no providers available

- packages/swapper/src/swappers/JupiterSwapper/endpoints.ts
- packages/swapper/src/types.ts
Jupiter fee estimation handler is not working
The signing tx is using the fees at quote time (that might be a reason why it was flaky at some point)
Now the fee estimation handler is working properly, returning gas fees estimations
We estimate fees again at signing time so it's closer to the TX, meaning it uses proper data (not outdated)
Caught while implementing relay
High but medium considering it was not working before
- Try to do some swap: SOL to any solana token, any solana token to SOL, SOL to solana tokens you never traded before...
- Fee estimations should be good at confirm time (often higher than at rate time)
n/a
n/a …
> fix: jupiter getSolanaTransactionFees not working and fee estimation to signing time

- src/components/MultiHopTrade/components/SpotTradeSuccess/SpotTradeSuccess.tsx
This PR ensures there is never a negative amount in `<YouSaved />`. If you do have a FOX savings, but a negative surplus delta, then the total amount can currently be negative.
closes https://github.com/shapeshift/web/issues/9322
- See eng/ops testing steps
- Hard to test as it requires real-world conditions, but can monkey patch things somehow e.g in `<SpotTradeSuccess`, monkey patching these, and playing around with values to ensure you have no/fee savings and no/extra delta:
```typescript
const buyAmountBeforeFeesCryptoPrecision = '47000000'
const buyAmountAfterFeesCryptoPrecision = '46000000'
const actualBuyAmountCryptoPrecision = '10000000'
const …
```
> fix: you saved negative amounts

- src/context/WalletProvider/NewWalletViews/sections/SavedWalletsSection.tsx
Aligns native with other wallets, where we `SET_WALLET` (and similar actions) on connect, regardless of first connection. Wallet state should always be set or re-set on connect, and we're currently missing on hitting a bunch of required state setters because of the `if (!initialized) initialize() else stateSetters()` logic.
This effectively fixes the backup passphrase modal early returning null, and a bunch of state issues that may exist but we may not know about with re: native and empty states.
closes https://github.com/shapeshift/web/issues/9340
Medium, touches wallet state, but really is just a logic alignment with other wallets, nothing fancy here
- …
> fix: always set native wallet state on re/connect

- src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
No idea how this works on desktop, but this definitely doesn't on mobile - this PR fixes wouting.
closes N/A, spotted by ops in release thread
Low/medium, risk of borked user menu, test accordingly
- User menu is happy on desktop and still opens
- User menu routes are still happy (test me with native and its many routes - note https://github.com/shapeshift/web/issues/9340 is still borked, fix pending merge in https://github.com/shapeshift/web/pull/9341)
- User menu is happy again on mobile
- ^
- ^
- Desktop
https://jam.dev/c/3789e620-b99d-42b5-83fe-4bdfafccccc5
- Mobile
https://jam.dev/c/5d61831b-e866-4a16-ac13-a108284840c4
> fix: user menu dead click on mobile

- .env
- .github/workflows/generate.yml
- docs/asset-generation.md
- headers/csps/marketService/coincap.ts
- packages/caip/src/adapters/coincap/generate.ts
- packages/caip/src/adapters/coincap/index.ts
- src/config.ts
- src/lib/market-service/coincap/coincap.test.ts
- src/lib/market-service/coincap/coincap.ts
- src/vite-env.d.ts
Updates the CoinCap implementation to use the new V3 API.
This API now requires an API key for all requests.
CLI run off this branch: https://github.com/shapeshift/web/actions/runs/14590765192/job/40925285964
Asset generation PR from this branch: https://github.com/shapeshift/web/pull/9375
Closes https://github.com/shapeshift/web/issues/9374
Low, no runtime code.
None
Asset generation should be great again, and CI should pass.
👆
👆
N/A
> fix: asset generation

- src/pages/RFOX/components/RFOXHeader.tsx
Nitpicky perf thing, spotted whilst reviewing [another PR](https://github.com/shapeshift/web/pull/9384#discussion_r2057580959) that copied this pattern.
Disabling the `react-memo/require-usememo` is incorrect in this context.
Having an object inside the memoization context means we unnecessarily recreate that object on every render of `activeAccountDropdown` (whenever any of  `accountIds.length`, `handleChange`, `selectedAssetAccountId`, `stakingAssetAccountId`, or `stakingAssetId` changes).
Tackling this nitpick so the pattern doesn't spread 🙏
N/A
Low
None
If we want to be pedantic, the rFOX header styles should show no regressions.
👆
👆
N/A
> perf: remove disabled rule

- src/context/WalletProvider/KeepKey/hooks/useKeepKeyVersions.ts
As we spew this guy inline on every render of `useKeepKeyVersions()`, it means that every hook render will call `sol_connect`, making Phantom "rate-limit" itself, despite `sol_connect` being an internal JSON-RPC call.
The reason is that `getDeviceId()` for PhantomHdWallet actually makes a `solanaGetAddress()` call to get a compooosite deviceId.
closes N/A, spotted by hpayne
Low to none
- Connect Phantom 
- Phantom accounts are derived
- ^
- ^
- This diff 
- Prod
> fix: getDeviceId() spew for non-keepkey wallets

- src/components/AssetSelection/components/AssetChainDropdown/AssetChainDropdown.tsx
- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputBody.tsx
Copypasta of message to product which sums up the current insanity pretty well:
> we have a lot of complex and inherently bug-prone logic related to default assets.
> We historically did a bunch of logic to do things like settings default pairs on wallet connect/change/disconnect/chains add and removal.
> This is inherently bug-prone and will produce weird flashes of "default" pairs changing.
> If you think about it, the whole intent of trying to be smart was to make UX better by preselecting them pairs that could be nice to them, but if trying to do that adds so much logic and is detrimental to the UX, then it's a negative value.
> Proposing we stop this madness and KISS by removing all this ugly logic since we're now driven by URL. Whatever you see in the URL (i.e the default pair when …
> feat: no smartsies on default pairs

- src/components/TradeAssetSearch/hooks/useGetPopularAssetsQuery.tsx
Thorchain and Mayachain are not in the top 100 market cap chains resulting in the asset not being discoverable on a wallet that has funds, but does not have a balance on those chains. This adds these assets to the popular assets so they are visible as the only asset on those chains at all times when filtering by chain.
https://discord.com/channels/554694662431178782/1366251876013576282/1366252257271746643
https://discord.com/channels/554694662431178782/1366251876013576282/1366254886710415360
Low
- Create a new wallet
- All assets should be shown by default
- Send an asset to the new wallet that is not rune or cacao
- Verify rune and cacao are shown in the …
> fix: show mayachain and thorchain as popular assets

- src/pages/Dashboard/components/AccountList/AccountTable.tsx
Truncates large asset balances to prevent the asset table's x-axis from growing unbounded.
Note we already have this on mobile, this adds it to the desktop view, too.
Before:
After:
Closes https://github.com/shapeshift/web/issues/9289
Small 
None
Monkey patch:
```diff
diff --git a/src/pages/Dashboard/components/AccountList/AccountTable.tsx b/src/pages/Dashboard/components/AccountList/AccountTable.tsx
index 925f96ce13..6e8f3dd044 100644
--- a/src/pages/Dashboard/components/AccountList/AccountTable.tsx
+++ b/src/pages/Dashboard/components/AccountList/AccountTable.tsx
@@ -75,7 +75,9 @@ export const AccountTable = memo(() => {
fontSize='sm'
whiteSpace='nowrap' …
```
> fix: truncate large asset balances

- src/assets/translations/en/main.json
- src/pages/TCY/components/Claim/ClaimStatus.tsx
- src/pages/TCY/components/ReusableStatus.tsx
- src/pages/TCY/components/Stake/StakeStatus.tsx
- src/pages/TCY/components/Unstake/UnstakeStatus.tsx
See this component from @0xApotheosis in https://github.com/shapeshift/web/pull/9462#discussion_r2073100404:
> This guy feels like it should become a generic component. We have a very similar src/pages/TCY/components/Stake/StakeStatus.tsx, and an also quite similar src/pages/TCY/components/Claim/ClaimStatus.tsx.
This does precisely that, but also:
- Adds missing dialog and dialog header for stake, unstake and claim status screens
- Adds missing "Go back" for stake and unstake
- Remove "Go back" for status (can't go back since once you claim a given claim, that's it)
closes N/A
Low, components abstraction "only"
- Go through the status flow for all …
> feat: tcy reusable status components

- src/pages/TCY/components/Unstake/UnstakeConfirm.tsx
Another day another precision issue, derp
closes N/A
None, blatant precision issue
- Able to unstake, with the correct bps applied
- Staking balances are updated after unstake
- ^
https://jam.dev/c/4355faea-c2bf-474f-8bd7-b3a005249307
> fix: thor unstake bps calcs

- src/pages/TCY/components/TCYHeader.tsx
Fixes buggy account selection component not properly controlling `<AccountDropdown />` and only working once, but then resetting back to account 0.
Fixed by properly making it controlled, passing `defaultAccountId`.
closes N/A, spotted while testing
None
- Account selection works properly in TCY account dropdown, even after selecting multiple diff ROON accoonts in a roo
- ^
- ^
https://jam.dev/c/4027e0cf-b3b5-4e20-850a-264e19f26a6d
> fix: tcy properly controlled account dropdown

- src/components/MultiHopTrade/components/TradeConfirm/TradeFooterButton.tsx
- src/components/MultiHopTrade/components/TradeConfirm/components/TradeConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/ConfirmSummary.tsx
- src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/TradeQuoteContent.tsx
- src/components/MultiHopTrade/hooks/quoteValidation/usePriceImpact.tsx
Positive price impact is a good thing - let's communicate that.
N/A, a quick fix of something that was bugging me.
Low
N/A
We show positive price impact (in the quotes list on the right) in green:
We show negative price impact in red/yellow (depending on severity), as we currently do:
Ensure all other price impact UI shows no regressions (trade confirm footer/summary etc).
👆
👆
See testing section above.
> fix: handle positive price impact

- src/lib/utils/thorchain/index.ts
- src/pages/TCY/components/Claim/ClaimConfirm.tsx
- src/pages/TCY/components/Claim/ClaimRoutes.tsx
- src/pages/TCY/components/Claim/ClaimSweep.tsx
- src/pages/TCY/queries/useTcyClaims.tsx
- src/pages/ThorChainLP/queries/queries.ts
This PR fixes missing claims for TCY claims with UTXOs twofolds:
1. Uses `getThorchainFromAddress` instead of `getThorchainSaversPosition`. The former is a superset of the latter, which passing in either savers position getter (`getThorchainFromAddress`), or its lending or LP variant to find an active address.
Most importantly, the former defaults to 0th address in case of no active position found, which we should *not* need since we're only interested in active ones, but accidentally needed since we were only introspecting savers, not lending.
2. Adds lending position getter too. That, alongside defaulting to 0th account_index addies should ensure that all claims are detected
I'm unable to test this one at runtime, since this affects users which don't have savers, but have *only* …
> fix: thorfi UTXO addies bits

- src/assets/translations/en/main.json
- src/pages/TCY/components/ReusableStatus.tsx
Fixes the translation string for showing the claimed amount, and removed an unused arg, `symbol`.
Closes https://github.com/shapeshift/web/issues/9507
Low
Ensure that when claiming we show the actual claimed amount value.
Note, it might not be worth wasting a claim to test this simple fix.
👆
👆
N/A
> fix: tcy claimed amount

- src/pages/TCY/components/Claim/components/ClaimAddressInput.tsx
Fixes TCY claim account selection. 
The issue is caused by us passing an _address_ to the `defaultAccountId` property (this should be an _account ID_).
Because the `defaultAccountId` is always invalid, the `AccountDropdown` component internally resets to the first index account ID on any property change, resulting in an account dropdown that will always reset to index 0.
Closes https://github.com/shapeshift/web/issues/9508
Low
THORChain account selection for TCY claims.
When multiple THORChain accounts are available they should be selectable.
👆
👆
See above.
> fix: make tcy claim account selection work

- src/pages/Dashboard/components/DashboardHeader/DashboardHeaderTop.tsx
Changed the mobile settings icon from a logout icon to a gear (⚙️) icon in the dashboard header. This change improves the UI by using a more intuitive and appropriate icon for the settings menu.
closes #9480
Low Risk - This is a simple UI change that only affects the icon displayed in the mobile view. No functionality changes were made, and the settings menu behavior remains the same.
None - This is a purely visual change to the UI.
1. Open the application in mobile view
2. Verify that the settings icon in the dashboard header shows a gear (⚙️) icon instead of the previous logout icon
3. Click the icon to verify it still opens the settings menu as expected
4. Verify the desktop view still …
> feat: 9480 setting icon

- src/components/StakingVaults/PositionTable.tsx
This button is displayed but we don't have any route anymore to redirect the user too, this is a deadclick currently, removing the button but keeping the API to display a button so in the future we could use it for something else
Found by polishing things, no tickets
Low
- Use a brand new wallet empty of positions
- Go to the defi tab in wallet page
- No button anymore!
> fix: remove start earning button when empty positions

- package.json
- yarn.lock
See https://github.com/browserify/browserify-sign/commit/9e2bf122b70970cb92f69d53e963f18299f14d66 for context - https://github.com/shapeshift/web/pull/9073 introduced a regression in localhost dev breaking KK pair click.
https://github.com/shapeshift/web/pull/9073/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L214-L215
As a result of the diff above, the version of `readable-stream` which is used is now the one from the transient `ndjson` dep, which is on an older/different version than previously that checks for the existence of `process.browser` to detect if we're in a browser environment, however, process is not a standard browser API.
Not sure by which bundler magic this is working on builds, assuming something in `builds.output` i.e this guy: …
> fix: kk borked on vite dev server

- src/assets/translations/en/main.json
- src/components/AssetHeader/AssetChart.tsx
- src/components/Equity/Equity.tsx
- src/pages/Accounts/AccountToken/AccountBalance.tsx
- src/state/slices/marketDataSlice/selectors.ts
- When we have no market data for an asset instead of displaying $0.00 we will display N/A with a tooltip telling the user that the market data is unavailable.
- Adds a new selector that returns null for market data if unavailable.
Note:
This only touches the account and asset details balance a price sections of the app. We could leverage this to all rows that display fiat value but that should be a follow up if needed.
closes #8686 
low risk
Go to an asset that we have no market data for, instead of $0.00 for the price and balance you should see N/A. If you hover over this value, you should see a tooltip that explains that this market data is …
> fix: add not available to price when we have no market data

- src/assets/translations/en/main.json
This fixes a copy snafu on the fox page now that 55 bps has been passed and merged. I checked with @firebomb1 and deleting the string isn't necessary on edits, there is a script to flag key changes that translators will fix. Hopefully is all good. Happy to delete the keys though if that's preferred.
closes no issue. just some spotted copy problem.
none
Fire up local and give it a read. 
At some point double check copy makes sense on a local build. 
Doubel check, dev matches local and words good.
> chore: fixing the discounts sentence on the fox page

- src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx
Fixes the fox farming deposit modal, which unblocks release https://github.com/shapeshift/web/pull/9578
We were checking if we had market data for the Evergreen staking contract (`0xe7e16e2b05440c2e484c5c41ac3e5a4d15da2744`), which we never will have. Since `selectMarketDataByAssetIdUserCurrency` can now return `undefined` (as of https://github.com/shapeshift/web/pull/9576), the following line was returning: 
https://github.com/shapeshift/web/blob/04da10e73aea59bc8fd00b84f7952375d061c827/src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx#L121-L127
This PR removes the market data check, as a) it never worked, and b) `src/features/defi/components/Deposit/Deposit.tsx` can handle `undefined` market data.
To cherry-pick into release.
- …
> fix: fox farming deposit

- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
- src/components/Modals/Send/utils.ts
Ensures tcy sends uses the `tcy` denom, failure to do so means RUNE will be sent instead, as it does currently
closes https://github.com/shapeshift/web/issues/9593
Low, only risk is RUNE sends being borked, though realistically v. low risk of that, test accordingly
- TCY sends actually send TCY
- RUNE sends are still happy
- ^
- ^
https://jam.dev/c/d9ee2520-a600-46d7-8751-0a9109072f10
> fix: tcy sends

- src/pages/Dashboard/Dashboard.tsx
Looks like we're not too fast, and local wallet loading (and eventually, `SET_IS_CONNECTED` true) will happen *after* the wallet modal has been fired. 
This fixes it by not firing the modal while the local wallet is loading.
closes https://github.com/shapeshift/web/issues/9291
Low
- Go to wallet page with a connected EVM wallet
- Refresh
- Ensure that the wallet modal doesn't pop up in the interim where the local wallet is loading (warning icon in wallet menu)
- ^
- ^
- develop
https://jam.dev/c/3481bc05-d366-4e21-b8ac-78dcffc8b491
- this diff
https://jam.dev/c/8debaf25-3c9c-4b00-8bce-ac60db364cc3
> fix: dashboard don't open wallet modal while local wallet is loading

- src/hooks/useIsSnapInstalled/useIsSnapInstalled.tsx
Fixes the very edge, but very valid case of connecting with snap installed, disconnecting, then uninstalling the snap while in disconnected state which produces a wrong "snap uninstalled" modal on reconnect.
The reason was despite us polling (good) we were also having garbage collect and stale time (wrong) which means that things could be wrong for a few seconds/render. Not an issue in most cases, but actually an issue here.
Fixed by making us go stale immediately (react-query's default) and having no garbage collect - this was effectively useless either way as we're not really concerned about caching/gc since we poll so often either way.
closes https://github.com/shapeshift/web/issues/9357
> What protocols, transaction types, wallets or contract …
> fix: useIsSnapInstalled go stale immediately

- packages/caip/src/constants.ts
- packages/caip/src/utils.ts
Fixes MAYA balance wrongly being detected as CACAO
closes https://github.com/shapeshift/web/issues/9609
None
- Test this while holding both MAYA and CACAO
- CACAO balance matches explorer
- ^
- ^
- develop
- this diff
> fix: don't display MAYA balance as CACAO

- src/state/slices/portfolioSlice/portfolioSlice.ts
We were not diffing assets when upserting to portfolio, for IBC chains, those assets are not returned from unchained, meaning we were not zeroing out unexisting balances from the portfolio slice
Check when upserting if the balance is existing in the actual slice, if it's existing but the asset is not returned by unchained, zero out this balance!
closes #9624
Medium 
This could involve risks of balances not updated or maybe some potential performances issues if we loop over a big list of balances for no reasons
- Try to do anything with your balances, unstake something stake something (tcy for example, stake some fox, play with your balance)
No regressions …
> fix: diff and zero out balances when upserting to portfolio

- src/pages/TCY/components/TCYCta.tsx
Fixes the label of the button for the TCY Claims CTA on lower resolutions to allow wrapping and better sizing (especially for more verbose translations).
@reallybeard could you please validate the change?  It's relatively local so it won't affect other parts of the app's styling.
Low.
None.
Check the button appearance and functionality in English and other languages.
☝️ 
☝️
> fix: tcy claim cta label wrapping

- src/components/MultiHopTrade/components/SharedTradeInput/SharedRecipientAddress.tsx
Revalidate address on change, it fixes two things:
- if you paste your address, the UX is way better as it's your address, it's instant validated and you don't have to click on anything
- If the user enter a wrong address, he can modify it and it will be revalidated, previously it was buggy as the validate button was disabled, now it's revalidated automatically
closes #8378
Low
- Past a manual receive address
- or type it manually
- It will be auto validated and ready to use!
n/a
n/a
https://jam.dev/c/e3dd108f-3e20-4ce8-880e-c3207048bae8
> feat: auto validate external address on input

- src/plugins/walletConnectToDapps/components/header/ConnectDapp.tsx
- src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
I've modified the width settings of both the dApp menu popover and the connect dApp button in order to prevent the overflow issue shown in the ticket.
closes #9565 
* Risk here is that in certain scenarios the dApp menu popover may render with a strange width. In particular there could be some specific dApps that render in certain ways that I don't know about that could generate some rendering edge case.
I've tested
* Small mobile screens
* Regular desktop screens
* Small desktop screens
* Zooming in and out in the browser to manipulate rem
* Please test connecting to a variety of dApps and checking that the popover menu works in both mobile and desktop …
> fix: dApp modal sizing issue (#9565)

- src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts
Conforms to latest Onramper [spec](https://docs.onramper.com/docs/supported-widget-parameters-offramp) for offramping, ensuring that the selected currency and selected assets are actually there when selling.
Currently in develop, sell works for the default BTC/USD selection, but trying to select any other asset/currency won't work.
- relates to the closed https://github.com/shapeshift/web/issues/9705
Low to none
- Ensure Onramper buys are still happy and still open a widget with the selected asset/currency
- Ensure Onramper sells are happy and now open a widget with the selected asset/currency
- ^
- ^
- develop: borked sell asset and currency selection …
> fix: onramper sells honor selected sell asset and currency

- src/plugins/walletConnectToDapps/components/modals/connect/Connect.tsx
Makes sure we consistently handle `session_authenticate` wc events as `session_proposal`, since the wc dApps feature is built around proposals and doesn't support authentication requests. In effect, the result is pretty much the same.
~~Note, this only *tackles* https://github.com/shapeshift/web/issues/9663 making things slightly less worse - since base is down on all endpoints, unable to test this, to be retested once base is up.~~
Disregard the above, this actually closes it, tested with https://appkit-lab.reown.com/library/ethers-siwe/
- closes https://github.com/shapeshift/web/issues/9663
None - `session_authenticate` is already unhandled, and other methods are still handled the same as before.
> What protocols, transaction types, wallets or …
> fix: wcv2 session_authenticate events

- src/state/slices/tradeQuoteSlice/helpers.ts
Fixes a bug in quote sorting where the best rate doesn't always rise to the top when sorting. The issue was that we were trying to pass BigNumber's to lodash for orderby.
I've modified the sorting algo to be a bit more standard and uniform and utilise BigNumber comparisons for both gas and best rate.
closes #9747
Medium risk. This is a substantial rewrite of the quote sorting algorithm. Risk here is that the sorting breaks (although it's already broken in some cases which is what this fixes)
Test that quote sorting still works as expected.
Test a variety of different coin pairings
I was able to replicate this issue using the trade that hpayne did. Try a …
> fix: dont feed lodash big numbers

- src/pages/Dashboard/components/DashboardHeader/WalletBalance.tsx
Prevent the "net worth" label from wrapping when the loader is being displayed and ruining alignment.
Went with absolute positioning here rather than simply preventing the label from wrapping so that the net worth label doesn't jump when the loader finishes.
closes #
Low risk
Test that the net worth loading spinner alignment and position looks reasonable on both desktop and mobile. As well as a variety of screen sizes.
Refresh your screen and connect a wallet whilst on the wallet page to see a spinner
Mobile - https://jam.dev/c/050d4bd7-28ce-4aae-be99-38acab4ac0f4
Desktop - https://jam.dev/c/2be77fba-e955-4f72-9dfa-29110a0db5dd
> fix: net worth wrapping and breaking alignment on mobile loading

- packages/swapper/src/constants.ts
- packages/swapper/src/cowswap-utils/constants.ts
- packages/swapper/src/swappers/ArbitrumBridgeSwapper/utils/constants.ts
- packages/swapper/src/swappers/ButterSwap/utils/constants.ts
- packages/swapper/src/swappers/ChainflipSwapper/constants.ts
- packages/swapper/src/swappers/JupiterSwapper/utils/constants.ts
- packages/swapper/src/swappers/MayachainSwapper/constants.ts
- packages/swapper/src/swappers/MayachainSwapper/utils/index.ts
- packages/swapper/src/swappers/PortalsSwapper/constants.ts
- packages/swapper/src/swappers/PortalsSwapper/types.ts
- packages/swapper/src/swappers/RelaySwapper/constant.ts
- packages/swapper/src/swappers/ThorchainSwapper/constants.ts
- packages/swapper/src/swappers/ThorchainSwapper/getTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/ThorchainSwapper/getTradeRate/getTradeRate.ts
- packages/swapper/src/swappers/ZrxSwapper/utils/constants.ts
- packages/swapper/src/types.ts
- src/pages/Markets/hooks/useRows.tsx
- src/pages/ThorChainLP/queries/hooks/usePool.ts
This one is an actual ommission from https://github.com/shapeshift/web/issues/9243, removes dead "chain supported" constants that literally redeclare the existing `<SWAPPER>_SUPPORTED_CHAIN_IDS` consts as the same on the buy and sell side i.e: 
```typescript
{buy: <SWAPPER>_SUPPORTED_CHAIN_IDS, sell: <SWAPPER>_SUPPORTED_CHAIN_IDS}
```
Which definitely validates the nuke, as this type/those constants didn't bring anything new to the table!
- relates to the closed https://github.com/shapeshift/web/issues/9243
None, also dead code
- CI is happy
- ^
- ^
> feat: rm SupportedChainIds types and consts

- packages/chain-adapters/src/cosmossdk/mayachain/MayachainChainAdapter.ts
- packages/swapper/src/swappers/CowSwapper/constants.ts
- packages/swapper/src/swappers/CowSwapper/endpoints.ts
- packages/swapper/src/swappers/CowSwapper/types.ts
- packages/swapper/src/swappers/MayachainSwapper/endpoints.ts
- packages/swapper/src/swappers/ThorchainSwapper/endpoints.ts
- packages/swapper/src/thorchain-utils/checkTradeStatus.ts
- packages/swapper/src/types.ts
- src/components/MultiHopTrade/components/TradeConfirm/hooks/useTradeButtonProps.tsx
- src/hooks/useActionCenterSubscriber/useSwapActionSubscriber.tsx
- src/lib/tradeExecution.ts
Fixes a handful of issues surrounding swapper trade status detection, failing transaction and notification center issues.
closes https://github.com/shapeshift/web/issues/9824 (https://github.com/shapeshift/web/commit/595c873f305f1729c84767fd19b519044f25d957)
closes https://github.com/shapeshift/web/issues/9822 (https://github.com/shapeshift/web/commit/9bf2b275aa4460f6aff8ab08ba968206303a5141 and https://github.com/shapeshift/web/commit/9f90d77c046cbd6189fb88ee47ac3fddfd9bdabd)
closes https://github.com/shapeshift/web/issues/9823 (https://github.com/shapeshift/web/pull/9872/commits/2d3684df295d3db86028a3fc6121c9c2bf1fc7d7)
Medium
- Ensure trades from CACAO …
> fix: swapper and notification center polish

- src/hooks/useTransactionsSubscriber.ts
Pretty much what it says on the box, this was there because of vp for swapper, which is not required anymore.
Only place we still use this is FOX Page FOX governance, which already does a force refetch on mount. 
The only "regression" would be if you stay on the FOX page and somehow have a Tx that increases/decreases your FOX VP, you wouldn't see it update in real time, which IMO is perfectly acceptable and not worth doing those heavy queries on every EVM Tx.
closes N/A
Low to none
- FOX Page FOX governance vp is still displayed
- ^
- ^
> feat: stop refetching vp on every EVM Tx

- src/components/Modals/Settings/ClearCache.tsx
Pretty staightforward fix - we did *not* need this, app already automagically redirects to the new mobile wallet connect screen on cache clear, by virtue of disconnecting.
closes https://github.com/shapeshift/web/issues/9893
- Confirm "Clear cache" button doesn't produce a crash
- Run this branch with web locally and with expo set to localhost
- Set mobile app env to release when you test this in release
> fix: mobile app clear cache tap

- src/components/MultiHopTrade/components/SharedTradeInput/SharedTradeInputHeader.tsx
Tabs buttons were submitting forms as they were defaulted to `type="submit"` sending to the confirm screen if the user clicks on the market tab
By changing the type to `button` it stops this behavior
closes #9899
Low
- use a big amount in the swapper on mobile
- Click on the "Market" tab button
- It shouldn't redirect to the confirm screen
https://jam.dev/c/67f25a4d-617e-4342-a687-1292456ab75a
> fix: dont submit the trade form on tab button touch

- src/pages/RFOX/RFOX.tsx
- src/pages/RFOX/components/Stake/StakeInput.tsx
We were lacking space because of that 4 x-padding (i.e 16px), which we can't do on base breakpoints else input will be sad and disappear. Still not optimal in terms of space, but at least the input is visible now.
Basically aligns with places like `<BorrowInput />` which use similar 100% vw for asset selection on mobile, though I think ideally, what we would like here is to move to a *real* mobile design similar to the new swapper one by large @neomaking
closes https://github.com/shapeshift/web/issues/9904
None
- Go to RFOX page on mobile 
- Ensure that the input is visible
- ^
- ^
https://jam.dev/c/c8ec4727-7a40-435b-b0fb-24067cb94273
> fix: rfox container remove px on mobile

- packages/swapper/src/swappers/ArbitrumBridgeSwapper/endpoints.ts
- src/lib/tradeExecution.ts
- src/pages/RFOX/components/Stake/Bridge/hooks/useRfoxBridge.ts
- src/pages/RFOX/components/Stake/StakeInput.tsx
One usage of `swapperCheckTradeStatus()` still existed directly as opposed to the new `fetchTradeStatus()` - this aligns it.
While at it, fixes 
- borked bridge final checks which were broken to start with. 
- wrong "Insufficient ETH.ARB" messaging when bridging
closes https://github.com/shapeshift/web/issues/9716
closes https://github.com/shapeshift/web/issues/9956
closes https://github.com/shapeshift/web/issues/9955
Low
- Status checks are still performed for RFOX bridge
- Status checks are now happy until success for RFOX bridge (and in swapper, too) 
- If you don't have ETH.ARB on your account, there is *no* insuficcient ETH.ARB error, fees checks are …
> feat: useRfoxBridge align fetchTradeStatus() usage

- packages/swapper/src/swappers/ButterSwap/swapperApi/getTradeQuote.test.ts
- packages/swapper/src/swappers/ButterSwap/swapperApi/getTradeQuote.ts
- packages/swapper/src/swappers/ButterSwap/swapperApi/getTradeRate.test.ts
- packages/swapper/src/swappers/ButterSwap/swapperApi/getTradeRate.ts
- packages/swapper/src/swappers/ButterSwap/test-data/routeQuote.ts
- packages/swapper/src/swappers/ButterSwap/utils/constants.ts
- packages/swapper/src/swappers/ButterSwap/xhr.ts
- Adds the `shapeshift` affiliate string to the Butter swapper
- Adds the `shapeshift` entrance
- Improves consistency by using the `convertDecimalPercentageToBasisPoints` helper
- Disables same-chain swaps on Butter, as we can't collect affiliate fees on them (yet)
Closes #9834.
Low
Butter swaps
Ensure Butter quote and rate requests both contain `shapeshift:55` in the affiliate param (note, only cross-chain swaps use an affiliate fee - we might want to disable same-chain butter swaps before go-live for this reason):
Ensure Butter swaps go through. 
👆
👆
See above.
> chore: add butter affiliate code + tweaks

- packages/swapper/src/types.ts
- src/components/Layout/Header/ActionCenter/components/Notifications/SwapNotification.tsx
- src/components/Layout/Header/ActionCenter/components/SwapActionCard.tsx
- src/components/MultiHopTrade/components/TradeConfirm/hooks/useTradeButtonProps.tsx
- src/hooks/useActionCenterSubscribers/useSwapActionSubscriber.tsx
Note: same as previously, that won't work with custom receive addies.
Think it's a nice first step, though, eventually we probably should leverage status endpoints to decode receive amounts, regardless of chain (i.e, we should be able to decode receive amounts for e.g UTXOs and a custom receive address, i.e an account we don't know about in app)
If anything, this keeps things consistent with current status screen, so I believe that's the perfect interim solution!
closes https://github.com/shapeshift/web/issues/10012
Low/Medium - worst case scenario, we fallback to expected
- Give this a quick spin with CoW (surplus very likely) and other swappers and …
> feat: spot notification center display actual amount

- src/lib/utils/thorchain/hooks/useIsThorchainLpDepositEnabled.tsx
This temporarily disables the RUNE/RUJI pool as there's an upstream issue causing it to not display positions and correct stats.
The actual "disabled" field comes from the server side. So this is a bit of a monkey patch added to the `useIsLpDepositEnabled` hook.
I've verified that the hook is purely used to block UI on the pools page.
closes #10031 
Low risk, this shouldn't effect anything except ruji/rune pooling
* Go to the pools page of the app and verify that RUJI/RUNE is marked as disabled
* Ensure that you can't add liquidity to the pool
> fix: disable ruji/rune pooling until upstream issue is fixed
